//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 12:09:15 PM CDT 
//


package mx.gob.imss.ctirss.delta.model.gestion.tramite.integracion.sime;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="registroPatronal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nss" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="primerApellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segundoApellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="salarioBase" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="campoGenerico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoTrabajor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tipoSalario" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="jornadaReducida" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fechaMovimiento" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="unidadMedica" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="campoGenerico2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoMovimiento" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="guia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="clave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="campoGenerico3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="curp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identificadorFormato" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registroPatronal",
    "nss",
    "primerApellido",
    "segundoApellido",
    "nombre",
    "salarioBase",
    "campoGenerico",
    "tipoTrabajor",
    "tipoSalario",
    "jornadaReducida",
    "fechaMovimiento",
    "unidadMedica",
    "campoGenerico2",
    "tipoMovimiento",
    "guia",
    "clave",
    "campoGenerico3",
    "curp",
    "identificadorFormato"
})
@XmlRootElement(name = "MovimientoAsignacionSIME", namespace = "http://delta.ctirss.imss.gob.mx/SIME")
public class MovimientoAsignacionSIMEType implements java.io.Serializable {

    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String registroPatronal;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected long nss;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String primerApellido;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String segundoApellido;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String nombre;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int salarioBase;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String campoGenerico;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int tipoTrabajor;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int tipoSalario;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int jornadaReducida;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    @XmlSchemaType(name = "date")
    protected Date fechaMovimiento;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int unidadMedica;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String campoGenerico2;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int tipoMovimiento;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int guia;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String clave;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String campoGenerico3;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME", required = true)
    protected String curp;
    @XmlElement(namespace = "http://delta.ctirss.imss.gob.mx/SIME")
    protected int identificadorFormato;

    /**
     * Gets the value of the registroPatronal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistroPatronal() {
        return registroPatronal;
    }

    /**
     * Sets the value of the registroPatronal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistroPatronal(String value) {
        this.registroPatronal = value;
    }

    /**
     * Gets the value of the nss property.
     * 
     */
    public long getNss() {
        return nss;
    }

    /**
     * Sets the value of the nss property.
     * 
     */
    public void setNss(long value) {
        this.nss = value;
    }

    /**
     * Gets the value of the primerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerApellido() {
        return primerApellido;
    }

    /**
     * Sets the value of the primerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerApellido(String value) {
        this.primerApellido = value;
    }

    /**
     * Gets the value of the segundoApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegundoApellido() {
        return segundoApellido;
    }

    /**
     * Sets the value of the segundoApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegundoApellido(String value) {
        this.segundoApellido = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the salarioBase property.
     * 
     */
    public int getSalarioBase() {
        return salarioBase;
    }

    /**
     * Sets the value of the salarioBase property.
     * 
     */
    public void setSalarioBase(int value) {
        this.salarioBase = value;
    }

    /**
     * Gets the value of the campoGenerico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampoGenerico() {
        return campoGenerico;
    }

    /**
     * Sets the value of the campoGenerico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampoGenerico(String value) {
        this.campoGenerico = value;
    }

    /**
     * Gets the value of the tipoTrabajor property.
     * 
     */
    public int getTipoTrabajor() {
        return tipoTrabajor;
    }

    /**
     * Sets the value of the tipoTrabajor property.
     * 
     */
    public void setTipoTrabajor(int value) {
        this.tipoTrabajor = value;
    }

    /**
     * Gets the value of the tipoSalario property.
     * 
     */
    public int getTipoSalario() {
        return tipoSalario;
    }

    /**
     * Sets the value of the tipoSalario property.
     * 
     */
    public void setTipoSalario(int value) {
        this.tipoSalario = value;
    }

    /**
     * Gets the value of the jornadaReducida property.
     * 
     */
    public int getJornadaReducida() {
        return jornadaReducida;
    }

    /**
     * Sets the value of the jornadaReducida property.
     * 
     */
    public void setJornadaReducida(int value) {
        this.jornadaReducida = value;
    }

    /**
     * Gets the value of the fechaMovimiento property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getFechaMovimiento() {
        return fechaMovimiento;
    }

    /**
     * Sets the value of the fechaMovimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setFechaMovimiento(Date value) {
        this.fechaMovimiento = value;
    }

    /**
     * Gets the value of the unidadMedica property.
     * 
     */
    public int getUnidadMedica() {
        return unidadMedica;
    }

    /**
     * Sets the value of the unidadMedica property.
     * 
     */
    public void setUnidadMedica(int value) {
        this.unidadMedica = value;
    }

    /**
     * Gets the value of the campoGenerico2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampoGenerico2() {
        return campoGenerico2;
    }

    /**
     * Sets the value of the campoGenerico2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampoGenerico2(String value) {
        this.campoGenerico2 = value;
    }

    /**
     * Gets the value of the tipoMovimiento property.
     * 
     */
    public int getTipoMovimiento() {
        return tipoMovimiento;
    }

    /**
     * Sets the value of the tipoMovimiento property.
     * 
     */
    public void setTipoMovimiento(int value) {
        this.tipoMovimiento = value;
    }

    /**
     * Gets the value of the guia property.
     * 
     */
    public int getGuia() {
        return guia;
    }

    /**
     * Sets the value of the guia property.
     * 
     */
    public void setGuia(int value) {
        this.guia = value;
    }

    /**
     * Gets the value of the clave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClave() {
        return clave;
    }

    /**
     * Sets the value of the clave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClave(String value) {
        this.clave = value;
    }

    /**
     * Gets the value of the campoGenerico3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampoGenerico3() {
        return campoGenerico3;
    }

    /**
     * Sets the value of the campoGenerico3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampoGenerico3(String value) {
        this.campoGenerico3 = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurp() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurp(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the identificadorFormato property.
     * 
     */
    public int getIdentificadorFormato() {
        return identificadorFormato;
    }

    /**
     * Sets the value of the identificadorFormato property.
     * 
     */
    public void setIdentificadorFormato(int value) {
        this.identificadorFormato = value;
    }

}
