
package mx.gob.imss.ctirss.sso.admonusuarios.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSPersonalSubdelegacion", targetNamespace = "http://impl.service.admonusuarios.sso.ctirss.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSPersonalSubdelegacion {


    /**
     * 
     * @param cveSubdelegacion
     * @param roles
     * @param cveDelegacion
     * @param modulo
     * @return
     *     returns mx.gob.imss.ctirss.sso.admonusuarios.service.impl.ResponsablesDelegacionDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaResponsablesDelegacion", targetNamespace = "http://impl.service.admonusuarios.sso.ctirss.imss.gob.mx/", className = "mx.gob.imss.ctirss.sso.admonusuarios.service.impl.RecuperaResponsablesDelegacion")
    @ResponseWrapper(localName = "recuperaResponsablesDelegacionResponse", targetNamespace = "http://impl.service.admonusuarios.sso.ctirss.imss.gob.mx/", className = "mx.gob.imss.ctirss.sso.admonusuarios.service.impl.RecuperaResponsablesDelegacionResponse")
    public ResponsablesDelegacionDTO recuperaResponsablesDelegacion(
        @WebParam(name = "cveDelegacion", targetNamespace = "")
        int cveDelegacion,
        @WebParam(name = "cveSubdelegacion", targetNamespace = "")
        int cveSubdelegacion,
        @WebParam(name = "roles", targetNamespace = "")
        String roles,
        @WebParam(name = "modulo", targetNamespace = "")
        int modulo);

    /**
     * 
     * @param curp
     * @return
     *     returns mx.gob.imss.ctirss.sso.admonusuarios.service.impl.UsuarioInfoDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDatosUsuario", targetNamespace = "http://impl.service.admonusuarios.sso.ctirss.imss.gob.mx/", className = "mx.gob.imss.ctirss.sso.admonusuarios.service.impl.ConsultaDatosUsuario")
    @ResponseWrapper(localName = "consultaDatosUsuarioResponse", targetNamespace = "http://impl.service.admonusuarios.sso.ctirss.imss.gob.mx/", className = "mx.gob.imss.ctirss.sso.admonusuarios.service.impl.ConsultaDatosUsuarioResponse")
    public UsuarioInfoDTO consultaDatosUsuario(
        @WebParam(name = "curp", targetNamespace = "")
        String curp);

}
