#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp

 
#Tiles redirect

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

#===== Portales ====== 

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home


#===== Generales ====== 

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

#PORTLETS
portletSolicitudesInit.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesInit.url=/WEB-INF/views/portlet/solicitudes/inicial.jsp
portletSolicitudesContenido.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesContenido.url=/WEB-INF/views/portlet/solicitudes/contenido.jsp
portletSolicitudesDetalle.(class)=org.springframework.web.servlet.view.tiles2.TilesView
portletSolicitudesDetalle.url=portletSolicitudesDetalle
portletSolicitudesDetalleSimple.(class)=org.springframework.web.servlet.view.tiles2.TilesView
portletSolicitudesDetalleSimple.url=portletSolicitudesDetalleSimple
portletSolicitudesCorreo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
portletSolicitudesCorreo.url=portletSolicitudesCorreo

#Detalle solicitud externo
detalleSolicitudExterno.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleSolicitudExterno.url=detalleSolicitudExterno