#PRODUCCION
URL_IMSS_DIGITAL=http://serviciosdigitales.imss.gob.mx/portal-web/portal
#Stage
#URL_IMSS_DIGITAL=http://serviciosdigitales-stage.imss.gob.mx/portal-web/portal

#WS para validar si el RFC tiene derecho a RIF
uri.wsOsb.validaSatDerechoRif = http://osbserviciosdigitales.imss.gob.mx/Beneficios/riss/ValidacionSatDerechoRifServices?wsdl