##################
# FTP FileConfig #
##################
filesystem.sindo.output.url=sindo/output
filesystem.canase.output.url=canase/output
filesystem.riss.output.url=riss/output

################
# Servidor ftp #
################
ftp.server.url=vzapmb03.imss.gob.mx
ftp.server.user=ftp_delta
ftp.server.passwd=ftp0d3lt1.
ftp.server.port=21

application.mode=${mvn.application.mode}


##################
# Ruta de origen #
##################
file.sindo.input.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/sindo
file.sindo.input.tmp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/sindo_temp
file.canase.input.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/canase
file.canase.input.tmp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/canase_temp
file.riss.input.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/riss
file.riss.input.tmp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/riss_temp


####################
# Ruta de respaldo #
####################
file.sindo.resp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/sindo_hist
file.canase.resp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/canase_hist
file.riss.resp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/riss_hist


########################
# Ruta de verificacion #
########################
file.canase.verif.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/canase_checksum
file.sindo.verif.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/sindo_checksum
file.riss.verif.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/checksum
file.canase.verif.time=10000
file.sindo.verif.time=10000
file.riss.verif.time=1000
file.canase.verif.retry=3
file.sindo.verif.retry=3
file.riss.verif.retry=3


############################
# Ruta de FTP (Filesystem) #
############################
filesystem.ftp.base.output.url=/share/oracle/osbapdir01_domain/delta
filesystem.global.tmp.log.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/logs


################
# Archivos CIZ #
################
sindo.file.ciz01=AYPENT_CIZ01.txt
sindo.file.ciz02=AYPENT_CIZ02.txt
sindo.file.ciz03=AYPENT_CIZ03.txt


###################
# Archivos CANASE #
###################

canase.file.asignacion=APMVIAJ.txt


#################
# Archivos RISS #
#################

riss.file.movimiento=movimientosRiss.txt


###########################
# Archivos LOG Universal  #
###########################
global.log.file=DIAGNOSTICO_IMSS_LAYOUT.txt


##########################
# Archivos de validacion #
##########################

filesystem.delta.proceso.estatus=/share/oracle/osbapdir01_domain/osb_cluster1/ftp
