<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
    <artifactId>gestionCobranza</artifactId>
    <groupId>mx.gob.imss.ctirss.delta.cobranza</groupId>
    <version>2.1-SNAPSHOT</version>
  </parent>

	<artifactId>gestionCancelacionTimbrado-servicios</artifactId>
	<version>1.0-SNAPSHOT</version>
	<groupId>mx.gob.imss.ctirss.delta.cobranza</groupId>

	<name>Modulo de Servicios de Cancelacion de Timbrado  (ejb)</name>
	<url>http://maven.apache.org</url>
	<packaging>ejb</packaging>

	

	<properties>
		<org.cometd.java.version>2.5.1</org.cometd.java.version>
		 <org.slf4j.version>1.6.1</org.slf4j.version>
	</properties>

	<dependencies>

		

		<!-- Interface de Cancelacion de Timbrado. -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.cobranza</groupId>
			<artifactId>gestionCancelacionTimbrado-interfaces</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>


<!-- HIBERNATE CORE -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate.javax.persistence</groupId>
			<artifactId>hibernate-jpa-2.0-api</artifactId>
			<version>1.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-commons-annotations</artifactId>
			<version>3.2.0.Final</version>
		</dependency>

		<!-- HIBERNATE DEPENDENCIES -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>

		<!-- EJB -->
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb-api</artifactId>
			<version>3.0</version>
			<scope>provided</scope>
		</dependency>

		

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8.2</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.0.0</version>
		</dependency>

		
	</dependencies>

	<build>
		<pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
				</configuration>
			</plugin>

			<!-- Ejecuta tareas de Ant -->
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<tasks>
								<echo message="building module..." />
								<delete dir="${project.build.outputDirectory}/interceptor" />
							</tasks>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Habilita los facets y natures para que el eclipse reconoza el proyecto 
				como de tipo de EJB. -->
			<plugin>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<additionalBuildcommands>
						<buildCommand>
							<name>org.eclipse.jdt.core.javabuilder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.common.project.facet.core.builder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.validation.validationbuilder</name>
						</buildCommand>
					</additionalBuildcommands>

					<additionalProjectnatures>
						<projectnature>org.eclipse.wst.common.project.facet.core.nature</projectnature>
						<projectnature>org.eclipse.jdt.core.javanature</projectnature>
						<projectnature>org.eclipse.wst.common.modulecore.ModuleCoreNature</projectnature>
						<projectnature>org.eclipse.jem.workbench.JavaEMFNature</projectnature>
					</additionalProjectnatures>

					<additionalConfig>
						<file>
							<name>.settings/org.eclipse.wst.common.project.facet.core.xml</name>
							<content>&lt;faceted-project&gt;
									&lt;runtime name="Weblogic Runtime" /&gt;
									&lt;fixed facet="jst.ejb" /&gt;
									&lt;fixed facet="jst.java" /&gt;
									&lt;installed facet="jst.java" version="6.0" /&gt;
									&lt;installed facet="jst.ejb" version="3.0" /&gt;
								&lt;/faceted-project&gt;</content>
						</file>
						<file>
							<name>.settings/org.eclipse.wst.common.component</name>
							<content>&lt;project-modules id="moduleCoreId" project-version="1.5.0"&gt;
									&lt;wb-module deploy-name="${project.artifactId}"&gt;
										&lt;wb-resource deploy-path="/" source-path="/src/main/java" /&gt;
										&lt;wb-resource deploy-path="/" source-path="/src/main/resources" /&gt;
										&lt;property name="java-output-path" value="target/classes" /&gt;
									&lt;/wb-module&gt;
								&lt;/project-modules&gt;</content>
						</file>
					</additionalConfig>
				</configuration>
			</plugin>
		</plugins>
		</pluginManagement>
	</build>

	<profiles>
		<profile>
			<id>activate-interceptor</id>
			<activation>
				<property>
					<name>activate-interceptor</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>compile</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<tasks>
										<echo message="building interceptor..." />
										<delete includeemptydirs="true">
											<fileset dir="${project.build.outputDirectory}/META-INF/" includes="**/*" />
										</delete>
										<copy todir="${project.build.outputDirectory}/META-INF/">
											<fileset dir="src/main/resources/interceptor/" />
										</copy>
										<delete dir="${project.build.outputDirectory}/interceptor" />
									</tasks>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
