//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.gestion.patronal;

import java.io.Serializable;
import java.util.Date;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.domicilio.MunicipioIMSS;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.TipoPersona;

public class RegistroPatronal extends AbstractModel  implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;//Identificador de la tabla DitPatronGeneral
	protected Long idPatron;//Identificador de la persona dueña del rp
	private Long idRegistroPatronal; //Identificador de la tabla DitPatronSujetoObligado
	protected Long delegacionMunicipio;
	protected String noRegPatronal;
	protected Date fechaMovimiento;
	protected boolean cct;
	private Modalidad modalidad;
	private String digVerificador;
	private TipoPersona tipoPersona;
	private Clasificacion clasificacion;
	private String nombreComercial;
	private MunicipioIMSS municipioIMSS;
	
	
	/**
	 * Gets the value of the idPatron property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getIdPatron() {
		return idPatron;
	}

	/**
	 * Sets the value of the idPatron property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setIdPatron(Long value) {
		this.idPatron = value;
	}

	/**
	 * Gets the value of the delegacionMunicipio property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getDelegacionMunicipio() {
		return delegacionMunicipio;
	}

	/**
	 * Sets the value of the delegacionMunicipio property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setDelegacionMunicipio(Long value) {
		this.delegacionMunicipio = value;
	}

	/**
	 * Gets the value of the noRegPatronal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNoRegPatronal() {
		return noRegPatronal;
	}

	/**
	 * Sets the value of the noRegPatronal property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNoRegPatronal(String value) {
		this.noRegPatronal = value;
	}

	public Date getFechaMovimiento() {
		return fechaMovimiento;
	}

	public void setFechaMovimiento(Date fechaMovimiento) {
		this.fechaMovimiento = fechaMovimiento;
	}

	public boolean isCct() {
		return cct;
	}

	public void setCct(boolean cct) {
		this.cct = cct;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getIdRegistroPatronal() {
		return idRegistroPatronal;
	}

	public void setIdRegistroPatronal(Long idRegistroPatronal) {
		this.idRegistroPatronal = idRegistroPatronal;
	}

	public Modalidad getModalidad() {
		return modalidad;
	}

	public void setModalidad(Modalidad modalidad) {
		this.modalidad = modalidad;
	}

	public TipoPersona getTipoPersona() {
		return tipoPersona;
	}

	public void setTipoPersona(TipoPersona tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public String getDigVerificador() {
		return digVerificador;
	}

	public void setDigVerificador(String digVerificador) {
		this.digVerificador = digVerificador;
	}

	public Clasificacion getClasificacion() {
		return clasificacion;
	}

	public void setClasificacion(Clasificacion clasificacion) {
		this.clasificacion = clasificacion;
	}

	public String getNombreComercial() {
		return nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}
	
	public MunicipioIMSS getMunicipioIMSS() {
		return municipioIMSS;
	}

	public void setMunicipioIMSS(MunicipioIMSS municipioIMSS) {
		this.municipioIMSS = municipioIMSS;
	}

}
