
package mx.gob.imss.ultimospatrones.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsUltimosPatrones", targetNamespace = "http://ws.ultimospatrones.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsUltimosPatrones {


    /**
     * 
     * @param nss
     * @return
     *     returns mx.gob.imss.ultimospatrones.ws.RespuestaUltimosPatrones
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUltimosPatrones", targetNamespace = "http://ws.ultimospatrones.imss.gob.mx/", className = "mx.gob.imss.ultimospatrones.ws.GetUltimosPatrones")
    @ResponseWrapper(localName = "getUltimosPatronesResponse", targetNamespace = "http://ws.ultimospatrones.imss.gob.mx/", className = "mx.gob.imss.ultimospatrones.ws.GetUltimosPatronesResponse")
    public RespuestaUltimosPatrones getUltimosPatrones(
        @WebParam(name = "nss", targetNamespace = "")
        String nss);

}
