//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 10:39:01 AM CDT 
//


package mx.gob.imss.digital.modelo.cobranza;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Entidad que repreenta un registro de validacion para el archivo SUA
 * @author NOVUTECK1
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registroValidacion", namespace = "http://mx.gob.imss.digital.modelo.cobranza")
@XmlRootElement(name = "registroValidacion", namespace = "http://mx.gob.imss.digital.modelo.cobranza")
public class RegistroValidacion implements Serializable {

	/**
	 * serial version UID
	 */
	private static final long serialVersionUID = 1L;
    /**
     * Suma de las tasas de recardos aplicadas
     */
    private BigDecimal sumaDeTasasDeRecargosYActualizacionQueSeAplico = BigDecimal.ZERO;
    /**
     * Size del archivo final en bytes
     */
    private long tamanioDelArchivoEnBytes;
    /**
     * Fecha limite de pago
     */
    private Date fechaLimiteDePago;
    /**
     * Numero de discos
     */
    private int numeroDeDiscos;
    /**
     * Version de SUA Utilizada
     */
    private String versionSUA;
    /**
     * Total a depositar en cuenta imss 4RSS
     */
    private BigDecimal totalADepositarEnCuentaIMSS4RSS = BigDecimal.ZERO;
    /**
     * total a depositar en cuenta imss RCV
     */
    private BigDecimal totalADepositarEnCuentaIMSSRCV = BigDecimal.ZERO;
    /**
     * TOTAL A DEPOSITAR CUENA INFONAVIT APORTACION PATRONAL
     */
    private BigDecimal totalADepositarINFONAVITAportacionPatronal = BigDecimal.ZERO;
    /**
     * Total a depositar infonavit amotizacion de credito
     */
    private BigDecimal totalADepositarINFONAVITAmortizacionCredito = BigDecimal.ZERO;
    /**
     * checkSum
     */
    private long checkSum;
    /**
     * cuota fija
     */
    private BigDecimal cuotaFija = BigDecimal.ZERO;
    /**
     * Cuota excedente Patrnal
     */
    private BigDecimal cuotaExcedentePatronal = BigDecimal.ZERO;
    /**
     * CUota excedente Obrero
     */
    private BigDecimal cuotaExcedenteObrero = BigDecimal.ZERO;
    /**
     * Prestaciones en dinero patron
     */
    private BigDecimal prestacionesDineroPatronal = BigDecimal.ZERO;
    /**
     * Prestaciones en dinero Obrero
     */
    private BigDecimal prestacionesDineroObrero = BigDecimal.ZERO;
    /**
     * GAstos medicos pensionados patronal
     */
    private BigDecimal gastosMedicosPensionadosPatronal = BigDecimal.ZERO;
    /**
     * Gastos medicos pensionados obrero
     */
    private BigDecimal gastosMedicosPensionadosObrero = BigDecimal.ZERO;
    /**
     * Prima de riesgo de trabajo
     */
    private BigDecimal riesgosDeTrabajo = BigDecimal.ZERO;
    /**
     * cuota de invalidez y vida patronal
     */
    private BigDecimal invalidezYVidaPatronal = BigDecimal.ZERO;
    /**
     * cuota invalidez y vida obrero
     */
    private BigDecimal invalidezYVidaObrero = BigDecimal.ZERO;
    /**
     * cuota de guaderia y prestaciones sociales
     */
    private BigDecimal guarderiaYPrestacionesSociales = BigDecimal.ZERO;
    /**
     * factor de reversion CF
     */
    private String factorDeReversionCF;
    /**
     * factor de reversion Exc patronal
     */
    private String factorDeReversionExcPatronal;
    /**
     * Factor de reversion Exc Obrera
     */
    private String factorDeReversionExcObrero;
    /**
     * FActor de reversion
     */
    private String factorDeReversionPDPatronal;
    /**
     * FActor de reversion
     */
    private String factorDeReversionPDObrero;
    /**
     * FActor de reversion
     */
    private String factorDeReversionGMPPatronal;
    /**
     * FActor de reversion
     */
    private String factorDeReversionGMPObrero;
    /**
     * FActor de reversion
     */
    private String factorDeReversionRT;
    /**
     * FActor de reversion
     */
    private String factorDeReversionIVPatronal;
    /**
     * FActor de reversion
     */
    private String factorDeReversionIVObrero;
    /**
     * FActor de reversion
     */
    private String factorDeReversionGPS;
    /**
     * FActor de ausentismo
     */
    private BigDecimal factorDeAusentismo;
    /**
     * Campo paara uso futuro
     */
    private String filler;
	/**
	 * @return the sumaDeTasasDeRecargosYActualizacionQueSeAplico
	 */
	public BigDecimal getSumaDeTasasDeRecargosYActualizacionQueSeAplico() {
		return sumaDeTasasDeRecargosYActualizacionQueSeAplico;
	}
	/**
	 * @param sumaDeTasasDeRecargosYActualizacionQueSeAplico the sumaDeTasasDeRecargosYActualizacionQueSeAplico to set
	 */
	public void setSumaDeTasasDeRecargosYActualizacionQueSeAplico(
			BigDecimal sumaDeTasasDeRecargosYActualizacionQueSeAplico) {
		this.sumaDeTasasDeRecargosYActualizacionQueSeAplico = sumaDeTasasDeRecargosYActualizacionQueSeAplico;
	}
	/**
	 * @return the tamanioDelArchivoEnBytes
	 */
	public long getTamanioDelArchivoEnBytes() {
		return tamanioDelArchivoEnBytes;
	}
	/**
	 * @param tamanioDelArchivoEnBytes the tamanioDelArchivoEnBytes to set
	 */
	public void setTamanioDelArchivoEnBytes(long tamanioDelArchivoEnBytes) {
		this.tamanioDelArchivoEnBytes = tamanioDelArchivoEnBytes;
	}
	/**
	 * @return the fechaLimiteDePago
	 */
	public Date getFechaLimiteDePago() {
		return fechaLimiteDePago;
	}
	/**
	 * @param fechaLimiteDePago the fechaLimiteDePago to set
	 */
	public void setFechaLimiteDePago(Date fechaLimiteDePago) {
		this.fechaLimiteDePago = fechaLimiteDePago;
	}
	/**
	 * @return the numeroDeDiscos
	 */
	public int getNumeroDeDiscos() {
		return numeroDeDiscos;
	}
	/**
	 * @param numeroDeDiscos the numeroDeDiscos to set
	 */
	public void setNumeroDeDiscos(int numeroDeDiscos) {
		this.numeroDeDiscos = numeroDeDiscos;
	}
	/**
	 * @return the versionSUA
	 */
	public String getVersionSUA() {
		return versionSUA;
	}
	/**
	 * @param versionSUA the versionSUA to set
	 */
	public void setVersionSUA(String versionSUA) {
		this.versionSUA = versionSUA;
	}
	/**
	 * @return the totalADepositarEnCuentaIMSS4RSS
	 */
	public BigDecimal getTotalADepositarEnCuentaIMSS4RSS() {
		return totalADepositarEnCuentaIMSS4RSS;
	}
	/**
	 * @param totalADepositarEnCuentaIMSS4RSS the totalADepositarEnCuentaIMSS4RSS to set
	 */
	public void setTotalADepositarEnCuentaIMSS4RSS(
			BigDecimal totalADepositarEnCuentaIMSS4RSS) {
		this.totalADepositarEnCuentaIMSS4RSS = totalADepositarEnCuentaIMSS4RSS;
	}
	/**
	 * @return the totalADepositarEnCuentaIMSSRCV
	 */
	public BigDecimal getTotalADepositarEnCuentaIMSSRCV() {
		return totalADepositarEnCuentaIMSSRCV;
	}
	/**
	 * @param totalADepositarEnCuentaIMSSRCV the totalADepositarEnCuentaIMSSRCV to set
	 */
	public void setTotalADepositarEnCuentaIMSSRCV(
			BigDecimal totalADepositarEnCuentaIMSSRCV) {
		this.totalADepositarEnCuentaIMSSRCV = totalADepositarEnCuentaIMSSRCV;
	}
	/**
	 * @return the totalADepositarINFONAVITAportacionPatronal
	 */
	public BigDecimal getTotalADepositarINFONAVITAportacionPatronal() {
		return totalADepositarINFONAVITAportacionPatronal;
	}
	/**
	 * @param totalADepositarINFONAVITAportacionPatronal the totalADepositarINFONAVITAportacionPatronal to set
	 */
	public void setTotalADepositarINFONAVITAportacionPatronal(
			BigDecimal totalADepositarINFONAVITAportacionPatronal) {
		this.totalADepositarINFONAVITAportacionPatronal = totalADepositarINFONAVITAportacionPatronal;
	}
	/**
	 * @return the totalADepositarINFONAVITAmortizacionCredito
	 */
	public BigDecimal getTotalADepositarINFONAVITAmortizacionCredito() {
		return totalADepositarINFONAVITAmortizacionCredito;
	}
	/**
	 * @param totalADepositarINFONAVITAmortizacionCredito the totalADepositarINFONAVITAmortizacionCredito to set
	 */
	public void setTotalADepositarINFONAVITAmortizacionCredito(
			BigDecimal totalADepositarINFONAVITAmortizacionCredito) {
		this.totalADepositarINFONAVITAmortizacionCredito = totalADepositarINFONAVITAmortizacionCredito;
	}
	/**
	 * @return the checkSum
	 */
	public long getCheckSum() {
		return checkSum;
	}
	/**
	 * @param checkSum the checkSum to set
	 */
	public void setCheckSum(long checkSum) {
		this.checkSum = checkSum;
	}
	/**
	 * @return the cuotaFija
	 */
	public BigDecimal getCuotaFija() {
		return cuotaFija;
	}
	/**
	 * @param cuotaFija the cuotaFija to set
	 */
	public void setCuotaFija(BigDecimal cuotaFija) {
		this.cuotaFija = cuotaFija;
	}
	/**
	 * @return the cuotaExcedentePatronal
	 */
	public BigDecimal getCuotaExcedentePatronal() {
		return cuotaExcedentePatronal;
	}
	/**
	 * @param cuotaExcedentePatronal the cuotaExcedentePatronal to set
	 */
	public void setCuotaExcedentePatronal(BigDecimal cuotaExcedentePatronal) {
		this.cuotaExcedentePatronal = cuotaExcedentePatronal;
	}
	/**
	 * @return the cuotaExcedenteObrero
	 */
	public BigDecimal getCuotaExcedenteObrero() {
		return cuotaExcedenteObrero;
	}
	/**
	 * @param cuotaExcedenteObrero the cuotaExcedenteObrero to set
	 */
	public void setCuotaExcedenteObrero(BigDecimal cuotaExcedenteObrero) {
		this.cuotaExcedenteObrero = cuotaExcedenteObrero;
	}
	/**
	 * @return the prestacionesDineroPatronal
	 */
	public BigDecimal getPrestacionesDineroPatronal() {
		return prestacionesDineroPatronal;
	}
	/**
	 * @param prestacionesDineroPatronal the prestacionesDineroPatronal to set
	 */
	public void setPrestacionesDineroPatronal(BigDecimal prestacionesDineroPatronal) {
		this.prestacionesDineroPatronal = prestacionesDineroPatronal;
	}
	/**
	 * @return the prestacionesDineroObrero
	 */
	public BigDecimal getPrestacionesDineroObrero() {
		return prestacionesDineroObrero;
	}
	/**
	 * @param prestacionesDineroObrero the prestacionesDineroObrero to set
	 */
	public void setPrestacionesDineroObrero(BigDecimal prestacionesDineroObrero) {
		this.prestacionesDineroObrero = prestacionesDineroObrero;
	}
	/**
	 * @return the gastosMedicosPensionadosPatronal
	 */
	public BigDecimal getGastosMedicosPensionadosPatronal() {
		return gastosMedicosPensionadosPatronal;
	}
	/**
	 * @param gastosMedicosPensionadosPatronal the gastosMedicosPensionadosPatronal to set
	 */
	public void setGastosMedicosPensionadosPatronal(
			BigDecimal gastosMedicosPensionadosPatronal) {
		this.gastosMedicosPensionadosPatronal = gastosMedicosPensionadosPatronal;
	}
	/**
	 * @return the gastosMedicosPensionadosObrero
	 */
	public BigDecimal getGastosMedicosPensionadosObrero() {
		return gastosMedicosPensionadosObrero;
	}
	/**
	 * @param gastosMedicosPensionadosObrero the gastosMedicosPensionadosObrero to set
	 */
	public void setGastosMedicosPensionadosObrero(
			BigDecimal gastosMedicosPensionadosObrero) {
		this.gastosMedicosPensionadosObrero = gastosMedicosPensionadosObrero;
	}
	/**
	 * @return the riesgosDeTrabajo
	 */
	public BigDecimal getRiesgosDeTrabajo() {
		return riesgosDeTrabajo;
	}
	/**
	 * @param riesgosDeTrabajo the riesgosDeTrabajo to set
	 */
	public void setRiesgosDeTrabajo(BigDecimal riesgosDeTrabajo) {
		this.riesgosDeTrabajo = riesgosDeTrabajo;
	}
	/**
	 * @return the invalidezYVidaPatronal
	 */
	public BigDecimal getInvalidezYVidaPatronal() {
		return invalidezYVidaPatronal;
	}
	/**
	 * @param invalidezYVidaPatronal the invalidezYVidaPatronal to set
	 */
	public void setInvalidezYVidaPatronal(BigDecimal invalidezYVidaPatronal) {
		this.invalidezYVidaPatronal = invalidezYVidaPatronal;
	}
	/**
	 * @return the invalidezYVidaObrero
	 */
	public BigDecimal getInvalidezYVidaObrero() {
		return invalidezYVidaObrero;
	}
	/**
	 * @param invalidezYVidaObrero the invalidezYVidaObrero to set
	 */
	public void setInvalidezYVidaObrero(BigDecimal invalidezYVidaObrero) {
		this.invalidezYVidaObrero = invalidezYVidaObrero;
	}
	/**
	 * @return the guarderiaYPrestacionesSociales
	 */
	public BigDecimal getGuarderiaYPrestacionesSociales() {
		return guarderiaYPrestacionesSociales;
	}
	/**
	 * @param guarderiaYPrestacionesSociales the guarderiaYPrestacionesSociales to set
	 */
	public void setGuarderiaYPrestacionesSociales(
			BigDecimal guarderiaYPrestacionesSociales) {
		this.guarderiaYPrestacionesSociales = guarderiaYPrestacionesSociales;
	}
	/**
	 * @return the factorDeReversionCF
	 */
	public String getFactorDeReversionCF() {
		return factorDeReversionCF;
	}
	/**
	 * @param factorDeReversionCF the factorDeReversionCF to set
	 */
	public void setFactorDeReversionCF(String factorDeReversionCF) {
		this.factorDeReversionCF = factorDeReversionCF;
	}
	/**
	 * @return the factorDeReversionExcPatronal
	 */
	public String getFactorDeReversionExcPatronal() {
		return factorDeReversionExcPatronal;
	}
	/**
	 * @param factorDeReversionExcPatronal the factorDeReversionExcPatronal to set
	 */
	public void setFactorDeReversionExcPatronal(String factorDeReversionExcPatronal) {
		this.factorDeReversionExcPatronal = factorDeReversionExcPatronal;
	}
	/**
	 * @return the factorDeReversionExcObrero
	 */
	public String getFactorDeReversionExcObrero() {
		return factorDeReversionExcObrero;
	}
	/**
	 * @param factorDeReversionExcObrero the factorDeReversionExcObrero to set
	 */
	public void setFactorDeReversionExcObrero(String factorDeReversionExcObrero) {
		this.factorDeReversionExcObrero = factorDeReversionExcObrero;
	}
	/**
	 * @return the factorDeReversionPDPatronal
	 */
	public String getFactorDeReversionPDPatronal() {
		return factorDeReversionPDPatronal;
	}
	/**
	 * @param factorDeReversionPDPatronal the factorDeReversionPDPatronal to set
	 */
	public void setFactorDeReversionPDPatronal(String factorDeReversionPDPatronal) {
		this.factorDeReversionPDPatronal = factorDeReversionPDPatronal;
	}
	/**
	 * @return the factorDeReversionPDObrero
	 */
	public String getFactorDeReversionPDObrero() {
		return factorDeReversionPDObrero;
	}
	/**
	 * @param factorDeReversionPDObrero the factorDeReversionPDObrero to set
	 */
	public void setFactorDeReversionPDObrero(String factorDeReversionPDObrero) {
		this.factorDeReversionPDObrero = factorDeReversionPDObrero;
	}
	/**
	 * @return the factorDeReversionGMPPatronal
	 */
	public String getFactorDeReversionGMPPatronal() {
		return factorDeReversionGMPPatronal;
	}
	/**
	 * @param factorDeReversionGMPPatronal the factorDeReversionGMPPatronal to set
	 */
	public void setFactorDeReversionGMPPatronal(String factorDeReversionGMPPatronal) {
		this.factorDeReversionGMPPatronal = factorDeReversionGMPPatronal;
	}
	/**
	 * @return the factorDeReversionGMPObrero
	 */
	public String getFactorDeReversionGMPObrero() {
		return factorDeReversionGMPObrero;
	}
	/**
	 * @param factorDeReversionGMPObrero the factorDeReversionGMPObrero to set
	 */
	public void setFactorDeReversionGMPObrero(String factorDeReversionGMPObrero) {
		this.factorDeReversionGMPObrero = factorDeReversionGMPObrero;
	}
	/**
	 * @return the factorDeReversionRT
	 */
	public String getFactorDeReversionRT() {
		return factorDeReversionRT;
	}
	/**
	 * @param factorDeReversionRT the factorDeReversionRT to set
	 */
	public void setFactorDeReversionRT(String factorDeReversionRT) {
		this.factorDeReversionRT = factorDeReversionRT;
	}
	/**
	 * @return the factorDeReversionIVPatronal
	 */
	public String getFactorDeReversionIVPatronal() {
		return factorDeReversionIVPatronal;
	}
	/**
	 * @param factorDeReversionIVPatronal the factorDeReversionIVPatronal to set
	 */
	public void setFactorDeReversionIVPatronal(String factorDeReversionIVPatronal) {
		this.factorDeReversionIVPatronal = factorDeReversionIVPatronal;
	}
	/**
	 * @return the factorDeReversionIVObrero
	 */
	public String getFactorDeReversionIVObrero() {
		return factorDeReversionIVObrero;
	}
	/**
	 * @param factorDeReversionIVObrero the factorDeReversionIVObrero to set
	 */
	public void setFactorDeReversionIVObrero(String factorDeReversionIVObrero) {
		this.factorDeReversionIVObrero = factorDeReversionIVObrero;
	}
	/**
	 * @return the factorDeReversionGPS
	 */
	public String getFactorDeReversionGPS() {
		return factorDeReversionGPS;
	}
	/**
	 * @param factorDeReversionGPS the factorDeReversionGPS to set
	 */
	public void setFactorDeReversionGPS(String factorDeReversionGPS) {
		this.factorDeReversionGPS = factorDeReversionGPS;
	}
	/**
	 * @return the factorDeAusentismo
	 */
	public BigDecimal getFactorDeAusentismo() {
		return factorDeAusentismo;
	}
	/**
	 * @param factorDeAusentismo the factorDeAusentismo to set
	 */
	public void setFactorDeAusentismo(BigDecimal factorDeAusentismo) {
		this.factorDeAusentismo = factorDeAusentismo;
	}
	/**
	 * @return the filler
	 */
	public String getFiller() {
		return filler;
	}
	/**
	 * @param filler the filler to set
	 */
	public void setFiller(String filler) {
		this.filler = filler;
	}
    

}
