//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class Consultorio  extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idUmfConsultorioTurnoMedico;
	private Long idConsultorio;
	private String descripcion;
	private Long poblacion;
	private Integer consultorioVirtual;

	public Consultorio() {
		
	}
	
	public Consultorio(Long idConsultorio) {
		this.idConsultorio = idConsultorio;
	}
	
	public Consultorio(String descripcion) {
		this.descripcion = descripcion;
	}
	
	public Consultorio(Long idConsultorio, String descripcion) {
		this.idConsultorio = idConsultorio;
		this.descripcion = descripcion;
	}
	
	public Consultorio(Long idConsultorio, String descripcion, Long poblacion) {
		this.idConsultorio = idConsultorio;
		this.descripcion = descripcion;
		this.poblacion = poblacion;
	}
	
	public Consultorio(Long idConsultorio, String descripcion, Long poblacion, Long idUmfConsultorioTurnoMedico) {
		this.idConsultorio = idConsultorio;
		this.descripcion = descripcion;
		this.poblacion = poblacion;
		this.idUmfConsultorioTurnoMedico = idUmfConsultorioTurnoMedico;
	}
	
	/**
	 * Gets the value of the idConsultorio property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getIdConsultorio() {
		return idConsultorio;
	}

	/**
	 * Sets the value of the idConsultorio property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setIdConsultorio(Long value) {
		this.idConsultorio = value;
	}

	/**
	 * Gets the value of the descripcion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * Sets the value of the descripcion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescripcion(String value) {
		this.descripcion = value;
	}
	
	public Long getPoblacion() {
		return poblacion;
	}

	public void setPoblacion(Long poblacion) {
		this.poblacion = poblacion;
	}

	public Long getIdUmfConsultorioTurnoMedico() {
		return idUmfConsultorioTurnoMedico;
	}

	public void setIdUmfConsultorioTurnoMedico(Long idUmfConsultorioTurnoMedico) {
		this.idUmfConsultorioTurnoMedico = idUmfConsultorioTurnoMedico;
	}
	
	
	public Integer getConsultorioVirtual() {
		return consultorioVirtual;
	}

	public void setConsultorioVirtual(Integer consultorioVirtual) {
		this.consultorioVirtual = consultorioVirtual;
	}

	@Override
	public String toString() {
		String consultorio = "";
		
		consultorio += "El consultorio es; idConsultorio: " + this.idConsultorio + ", descripcion: " + this.descripcion + ", poblacion: " + this.poblacion
				+ " y id de la relacion UMF-Consultorio-Turno-Medico: " + this.idUmfConsultorioTurnoMedico;
		
		return consultorio;
	}
	
}