//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.math.BigInteger;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

import mx.gob.imss.ctirss.delta.model.Usuario;
import mx.gob.imss.ctirss.delta.model.derechohabiente.negocio.Tramite;
import mx.gob.imss.ctirss.delta.model.domicilio.Domicilio;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Fisica;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Persona;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class RegistroDerechohabiente  extends Tramite {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected RazonRegistro razonRegistro;
	protected Tramite tramite;
	protected Fisica fisica;
	protected Persona personaTramite;
	protected Parentesco parentesco;
	protected BigInteger evaluacionCuestionario;
	protected Usuario usuario;
	protected Date fecRegistroActualizado;
	protected Date fecRegistroAlta;
	protected Date fecRegistroBaja;
	protected Domicilio domicilio;

	/**
	 * Gets the value of the razonRegistro property.
	 * 
	 * @return possible object is {@link RazonRegistro }
	 * 
	 */
	public RazonRegistro getRazonRegistro() {
		return razonRegistro;
	}

	/**
	 * Sets the value of the razonRegistro property.
	 * 
	 * @param value
	 *            allowed object is {@link RazonRegistro }
	 * 
	 */
	public void setRazonRegistro(RazonRegistro value) {
		this.razonRegistro = value;
	}

	/**
	 * Gets the value of the tramite property.
	 * 
	 * @return possible object is {@link Tramite }
	 * 
	 */
	public Tramite getTramite() {
		return tramite;
	}

	/**
	 * Sets the value of the tramite property.
	 * 
	 * @param value
	 *            allowed object is {@link Tramite }
	 * 
	 */
	public void setTramite(Tramite value) {
		this.tramite = value;
	}

	/**
	 * Gets the value of the fisica property.
	 * 
	 * @return possible object is {@link Fisica }
	 * 
	 */
	public Fisica getFisica() {
		return fisica;
	}

	/**
	 * Sets the value of the fisica property.
	 * 
	 * @param value
	 *            allowed object is {@link Fisica }
	 * 
	 */
	public void setFisica(Fisica value) {
		this.fisica = value;
	}

	/**
	 * Gets the value of the personaTramite property.
	 * 
	 * @return possible object is {@link Persona }
	 * 
	 */
	public Persona getPersonaTramite() {
		return personaTramite;
	}

	/**
	 * Sets the value of the personaTramite property.
	 * 
	 * @param value
	 *            allowed object is {@link Persona }
	 * 
	 */
	public void setPersonaTramite(Persona value) {
		this.personaTramite = value;
	}

	/**
	 * Gets the value of the parentesco property.
	 * 
	 * @return possible object is {@link Parentesco }
	 * 
	 */
	public Parentesco getParentesco() {
		return parentesco;
	}

	/**
	 * Sets the value of the parentesco property.
	 * 
	 * @param value
	 *            allowed object is {@link Parentesco }
	 * 
	 */
	public void setParentesco(Parentesco value) {
		this.parentesco = value;
	}

	/**
	 * Gets the value of the evaluacionCuestionario property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getEvaluacionCuestionario() {
		return evaluacionCuestionario;
	}

	/**
	 * Sets the value of the evaluacionCuestionario property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setEvaluacionCuestionario(BigInteger value) {
		this.evaluacionCuestionario = value;
	}

	public Date getFecRegistroActualizado() {
		return fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	public Date getFecRegistroAlta() {
		return fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}

	public Date getFecRegistroBaja() {
		return fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return the domicilio
	 */
	public Domicilio getDomicilio() {
		return domicilio;
	}

	/**
	 * @param domicilio the domicilio to set
	 */
	public void setDomicilio(Domicilio domicilio) {
		this.domicilio = domicilio;
	}

}
