//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;
import java.math.BigInteger;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class RestriccionServicio  extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Long idRestriccionServicio;
	protected String descripcion;
	protected BigInteger ponderacionNegativa;

	/**
	 * Gets the value of the idRestriccionServicio property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getIdRestriccionServicio() {
		return idRestriccionServicio;
	}

	/**
	 * Sets the value of the idRestriccionServicio property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setIdRestriccionServicio(Long value) {
		this.idRestriccionServicio = value;
	}

	/**
	 * Gets the value of the descripcion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * Sets the value of the descripcion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescripcion(String value) {
		this.descripcion = value;
	}

	/**
	 * Gets the value of the ponderacionNegativa property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getPonderacionNegativa() {
		return ponderacionNegativa;
	}

	/**
	 * Sets the value of the ponderacionNegativa property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setPonderacionNegativa(BigInteger value) {
		this.ponderacionNegativa = value;
	}

}
