//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.27 at 01:50:15 PM CDT 
//
//Generico
package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.Usuario;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.SujetoObligado;

public class UsuarioOrdinario  extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Usuario usuario;
	protected SujetoObligado sujetoObligado;
	protected Long idUsuarioOrdinario;
	/**
	 * @return the usuario
	 */
	public Usuario getUsuario() {
		return usuario;
	}
	/**
	 * @param usuario the usuario to set
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	/**
	 * @return the sujetoObligado
	 */
	public SujetoObligado getSujetoObligado() {
		return sujetoObligado;
	}
	/**
	 * @param sujetoObligado the sujetoObligado to set
	 */
	public void setSujetoObligado(SujetoObligado sujetoObligado) {
		this.sujetoObligado = sujetoObligado;
	}
	/**
	 * @return the idUsuarioOrdinario
	 */
	public Long getIdUsuarioOrdinario() {
		return idUsuarioOrdinario;
	}
	/**
	 * @param idUsuarioOrdinario the idUsuarioOrdinario to set
	 */
	public void setIdUsuarioOrdinario(Long idUsuarioOrdinario) {
		this.idUsuarioOrdinario = idUsuarioOrdinario;
	}

	
}
