<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>gestionSolicitud-sipare-packing</artifactId>
	<url>http://maven.apache.org</url>
	<packaging>ear</packaging>

	<parent>
		<artifactId>gestionSolicitud-sipare</artifactId>
		<groupId>mx.gob.imss.ctirss.delta.solicitudes.sipare</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<properties>
		<skipTests>true</skipTests>
		<dep>none</dep>

		<junit.version>4.8.2</junit.version>

		<!-- DEPENDENCIAS DE OTROS PROYECTOS -->
		<delta.framework.version>2.6-SNAPSHOT</delta.framework.version>
		<delta.documentos.probatorios>2.4-SNAPSHOT</delta.documentos.probatorios>
		<delta.domicilios>2.4-SNAPSHOT</delta.domicilios>
		<delta.clientews>2.2-SNAPSHOT</delta.clientews>
		<delta.solicitud>2.2-SNAPSHOT</delta.solicitud>
		<delta.medioscontacto>2.3-SNAPSHOT</delta.medioscontacto>
		<delta.personas>2.4-SNAPSHOT</delta.personas>
		<delta.patronal>2.4-SNAPSHOT</delta.patronal>
		<delta.clasificacion.empr>2.4-SNAPSHOT</delta.clasificacion.empr>
		<delta.asegurados>2.2-SNAPSHOT</delta.asegurados>
		<delta.dhabiente>2.2-SNAPSHOT</delta.dhabiente>
		<delta.cobranza>1.0-SNAPSHOT</delta.cobranza>
	</properties>

	<repositories>
		<repository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<url>http://11.254.16.21/mvn2_repo/</url>
		</repository>
	</repositories>

	<dependencies>

		<dependency>
			<artifactId>gestionSolicitud-sipare-servicios-negocio-ejb</artifactId>
			<groupId>mx.gob.imss.ctirss.delta.solicitudes.sipare</groupId>
			<version>1.0-SNAPSHOT</version>
			<type>ejb</type>
		</dependency>


		<!-- Test -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Maven EAR Plug-In -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<version>5</version>
					<defaultLibBundleDir>lib</defaultLibBundleDir>
				</configuration>
			</plugin>

			<!-- Habilita los facets y natures para que el eclipse reconoza el proyecto 
				como de tipo de EAR. -->
			<plugin>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<additionalBuildcommands>
						<buildCommand>
							<name>org.eclipse.jdt.core.javabuilder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.common.project.facet.core.builder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.validation.validationbuilder</name>
						</buildCommand>
					</additionalBuildcommands>

					<additionalProjectnatures>
						<projectnature>org.eclipse.wst.common.project.facet.core.nature</projectnature>
						<projectnature>org.eclipse.jdt.core.javanature</projectnature>
						<projectnature>org.eclipse.wst.common.modulecore.ModuleCoreNature</projectnature>
						<projectnature>org.eclipse.jem.workbench.JavaEMFNature</projectnature>
					</additionalProjectnatures>

					<additionalConfig>
						<file>
							<name>.settings/org.eclipse.wst.common.project.facet.core.xml</name>
							<content>&lt;faceted-project&gt;
								&lt;runtime name="Weblogic Runtime" /&gt;
								&lt;fixed facet="jst.ear" /&gt;
								&lt;fixed facet="jst.java" /&gt;
								&lt;installed facet="jst.java" version="6.0" /&gt;
								&lt;installed facet="jst.ear" version="5.0" /&gt;
								&lt;installed facet="wls.ear" version="10.3.4" /&gt;
								&lt;/faceted-project&gt;</content>
						</file>

						<file>
							<name>.settings/org.eclipse.wst.common.component</name>
							<content>&lt;project-modules id="moduleCoreId"
								project-version="1.5.0"&gt;
								&lt;wb-module deploy-name="${project.artifactId}"&gt;
								&lt;wb-resource deploy-path="/" source-path="/src/main/java" /&gt;
								&lt;wb-resource deploy-path="/"
								source-path="/src/main/resources" /&gt;
								&lt;property name="java-output-path" value="target/classes" /&gt;
								&lt;/wb-module&gt;
								&lt;/project-modules&gt;</content>
						</file>
					</additionalConfig>
				</configuration>
			</plugin>
		</plugins>

		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ftp</artifactId>
			</extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav</artifactId>
			</extension>
		</extensions>
	</build>

	<pluginRepositories>
		<pluginRepository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<url>http://11.254.16.21/mvn2_repo/</url>
			<layout>default</layout>
			<snapshots>
			</snapshots>
			<releases>
				<updatePolicy>never</updatePolicy>
			</releases>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<!-- use the following if you're not using a snapshot version. -->
		<repository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://11.254.16.21:8080/archiva/repository/repo</url>
		</repository>
		<snapshotRepository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://11.254.16.21:8080/archiva/repository/repo</url>
		</snapshotRepository>
	</distributionManagement>

	<scm>
		<connection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_domicilios/</connection>
		<developerConnection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_domicilios/</developerConnection>
		<url>http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_domicilios/</url>
	</scm>

	<profiles>
		<!-- Perfil para el deployment de los servicios REMOTO -->
		<profile>
			<id>qa-deploy-all</id>
			<activation>
				<property>
					<name>qa-deploy-all</name>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Weblogic Deployment Plug-In -->
					<plugin>
						<groupId>com.oracle.weblogic</groupId>
						<artifactId>weblogic-maven-plugin</artifactId>
						<version>10.3.4</version>
						<configuration>
							<adminurl>t3://172.24.116.37:15050</adminurl>
							<user>admin_wlgeceqa</user>
							<password>wlgeceqa_admin</password>
							<upload>true</upload>
							<action>deploy</action>
							<remote>true</remote>
							<verbose>true</verbose>
							<source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
							<name>${project.build.finalName}</name>
							<targets>c_geceqa_02</targets>
							<nostage>true</nostage>
						</configuration>

						<executions>
							<execution>
								<phase>install</phase>
								<goals>
									<goal>deploy</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<!-- Perfil para Remover los deploys en el ambiente de Desarrollo IMSS -->
		<profile>
			<id>qa-remove-all</id>
			<activation>
				<property>
					<name>qa-remove-all</name>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Weblogic Deployment Plug-In -->
					<plugin>
						<groupId>com.oracle.weblogic</groupId>
						<artifactId>weblogic-maven-plugin</artifactId>
						<version>10.3.4</version>
						<configuration>
							<adminurl>t3://172.24.116.37:15050</adminurl>
							<user>admin_wlgeceqa</user>
							<password>wlgeceqa_admin</password>
							<name>${project.build.finalName}</name>
							<targets>c_geceqa_02</targets>
						</configuration>

						<executions>
							<execution>
								<phase>install</phase>
								<goals>
									<goal>undeploy</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>


		<!-- Perfil para el deployment de los servicios REMOTO -->
		<profile>
			<id>dev-deploy-all</id>
			<activation>
				<property>
					<name>dev-deploy-all</name>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Weblogic Deployment Plug-In -->
					<plugin>
						<groupId>com.oracle.weblogic</groupId>
						<artifactId>weblogic-maven-plugin</artifactId>
						<version>10.3.4</version>
						<configuration>
							<adminurl>t3://172.24.116.38:11000</adminurl>
							<user>admin_wldldev</user>
							<password>wldldev_admin</password>
							<upload>true</upload>
							<action>deploy</action>
							<remote>true</remote>
							<verbose>true</verbose>
							<source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
							<name>${project.build.finalName}</name>
							<targets>c_web_digital</targets>
							<nostage>true</nostage>
						</configuration>

						<executions>
							<execution>
								<phase>install</phase>
								<goals>
									<goal>deploy</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<!-- Perfil para Remover los deploys en el ambiente de Desarrollo IMSS -->
		<profile>
			<id>dev-remove-all</id>
			<activation>
				<property>
					<name>dev-remove-all</name>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Weblogic Deployment Plug-In -->
					<plugin>
						<groupId>com.oracle.weblogic</groupId>
						<artifactId>weblogic-maven-plugin</artifactId>
						<version>10.3.4</version>
						<configuration>
							<adminurl>t3://172.24.116.38:11000</adminurl>
							<user>admin_wldldev</user>
							<password>wldldev_admin</password>
							<name>${project.build.finalName}</name>
							<targets>c_web_digital</targets>
						</configuration>

						<executions>
							<execution>
								<phase>install</phase>
								<goals>
									<goal>undeploy</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<name>SIPARE packing</name>
</project>
