welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

#Vista de wizard IVRO Personal Modalidad
#wizardIVROIndivModalidadInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
#wizardIVROIndivModalidadInit.url=wizardIVROIndivInit
#wizardIVROIndivModalidadContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
#wizardIVROIndivModalidadContenido.url = wizardIVROIndivContenido

#Seguros Individuales IVRO Widget
widgetPersonaIvroIndivInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIvroIndivInit.url=/WEB-INF/views/widget/ivro/indiv/inicial-ivro-indiv-widget.jsp
widgetPersonaIvroIndivContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIvroIndivContenido.url=/WEB-INF/views/widget/ivro/indiv/contenido-ivro-indiv-widget.jsp

############# PORTLETS #################
portletSeguroDomesticoInit.(class)=org.springframework.web.servlet.view.JstlView
portletSeguroDomesticoInit.url=/WEB-INF/views/portlet/seguroDomestico/initial.jsp
portletSeguroDomesticoContent.(class)=org.springframework.web.servlet.view.JstlView
portletSeguroDomesticoContent.url=/WEB-INF/views/portlet/seguroDomestico/content.jsp

############# WIZARDS #################

#Vista de wizard Detalle Seguros
wizardDetalleSeguroInit.(class)=org.springframework.web.servlet.view.JstlView
wizardDetalleSeguroInit.url=wizardDetalleSeguroInit
wizardDetalleSeguroContenido.(class) = org.springframework.web.servlet.view.JstlView
wizardDetalleSeguroContenido.url = wizardDetalleSeguroContenido

############# SEGURO DOM?STICO #################
wizardSeguroDomesticoAltaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoAltaInit.url=seguroDomesticoAltaInit
wizardSeguroDomesticoAltaListaTrabajadores.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoAltaListaTrabajadores.url=seguroDomesticoAltaListaTrabajadores
wizardSeguroDomesticoAltaAgregarTrabajador.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoAltaAgregarTrabajador.url=seguroDomesticoAltaAgregarTrabajador
wizardSeguroDomesticoAltaCuestionario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoAltaCuestionario.url=seguroDomesticoAltaCuestionario

wizardSeguroDomesticoComunSolicitarTipoPago.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoComunSolicitarTipoPago.url=seguroDomesticoComunSolicitarTipoPago
wizardSeguroDomesticoComunSolicitarCentroTrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoComunSolicitarCentroTrabajo.url=seguroDomesticoComunSolicitarCentroTrabajo
wizardSeguroDomesticoComunAgregarCentroTrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoComunAgregarCentroTrabajo.url=seguroDomesticoComunAgregarCentroTrabajo
wizardSeguroDomesticoComunCotizacionTrabajador.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoComunCotizacionTrabajador.url=seguroDomesticoComunCotizacionTrabajador
wizardSeguroDomesticoComunResumen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoComunResumen.url=seguroDomesticoComunResumen
wizardSeguroDomesticoComunFinal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoComunFinal.url=seguroDomesticoComunFinal

wizardSeguroDomesticoRenovacionInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoRenovacionInit.url=seguroDomesticoRenovacionInit
wizardSeguroDomesticoRenovacionListaTrabajadores.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoRenovacionListaTrabajadores.url=seguroDomesticoRenovacionListaTrabajadores
wizardSeguroDomesticoRenovacionActualizarSalario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoRenovacionActualizarSalario.url=seguroDomesticoRenovacionActualizarSalario

wizardSeguroDomesticoVentanillaListaSeguros.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroDomesticoVentanillaListaSeguros.url=seguroDomesticoVentanillaListaSeguros

###############################  Seguros individuales ####################################################
wizardIndividualInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardIndividualInit.url=wizardIndividualInit

wizardIndividualComunSolicitarTipoPago.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardIndividualComunSolicitarTipoPago.url=wizardIndividualComunSolicitarTipoPago

wizardIndividualModalidad.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardIndividualModalidad.url=wizardIndividualModalidad

wizardIndividualCotizacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardIndividualCotizacion.url=wizardIndividualCotizacion

wizardIndividualCuestionario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardIndividualCuestionario.url=wizardIndividualCuestionario

wizardIndividualResumen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardIndividualResumen.url=wizardIndividualResumen

############# SEGURO FAMILIAR (MODALIDAD 33) #################
wizardSeguroFamiliarAltaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarAltaInit.url=seguroFamiliarAltaInit
wizardSeguroFamiliarAltaCuestionario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarAltaCuestionario.url=seguroFamiliarAltaCuestionario
wizardSeguroFamiliarAltaListaIntegrantes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarAltaListaIntegrantes.url=seguroFamiliarAltaListaIntegrantes
wizardSeguroFamiliarListaSeguros.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarListaSeguros.url=seguroFamiliarListaSeguros
wizardSeguroFamiliarDetalle.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarDetalle.url=seguroFamiliarDetalle

wizardSeguroFamiliarComunSolicitarDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarComunSolicitarDomicilio.url=seguroFamiliarComunSolicitarDomicilio
wizardSeguroFamiliarComunAgregarDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarComunAgregarDomicilio.url=seguroFamiliarComunAgregarDomicilio
wizardSeguroFamiliarComunResumen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarComunResumen.url=seguroFamiliarComunResumen
wizardSeguroFamiliarComunFinal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroFamiliarComunFinal.url=seguroFamiliarComunFinal

############# CVRO - CONTINUACION VOLUNTARIA (MODALIDAD 40) #################
wizardContinuacionVoluntariaAltaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardContinuacionVoluntariaAltaInit.url=continuacionVoluntariaAltaInit

wizardSeguroCVROComunSolicitarDatosInscripcion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroCVROComunSolicitarDatosInscripcion.url=wizardSeguroCVROComunSolicitarDatosInscripcion

wizardSeguroCVROConfirmarDatos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroCVROConfirmarDatos.url=wizardSeguroCVROConfirmarDatos

wizardSeguroCVROImpresionDocumentos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroCVROImpresionDocumentos.url=wizardSeguroCVROImpresionDocumentos

wizardSeguroCVROAgregarDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroCVROAgregarDomicilio.url=wizardSeguroCVROAgregarDomicilio

wizardSeguroContinuacionVoluntariaComunAgregarDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroContinuacionVoluntariaComunAgregarDomicilio.url=wizardSeguroContinuacionVoluntariaComunAgregarDomicilio

wizardSeguroCVRODetalle.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSeguroCVRODetalle.url=seguroCVRODetalle
