//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//


package mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "ConstanciaEstudio")
public class ConstanciaEstudio
    extends DocumentoProbatorio implements Serializable
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 7264863864952321488L;
	/**
	 * 
	 */
	
    protected String nombreEscuela;
    protected String claveEscuela;
    protected String noIncorporacion;
    protected String gradoEscolar;
    protected Date fechaInicioPeriodo;
    protected Date fechaFinPeriodo;
    protected String fechaInicio;
	protected String fechaFin;
	protected String fechaExpedicionCadena;
    protected String observaciones;
    protected DetalleNivelEducativo detalleNivelEducativo;
    
    
    
    
    
    public DetalleNivelEducativo getDetalleNivelEducativo() {
		return detalleNivelEducativo;
	}

	public void setDetalleNivelEducativo(DetalleNivelEducativo detalleNivelEducativo) {
		this.detalleNivelEducativo = detalleNivelEducativo;
	}

	/**
     * Gets the value of the nombreEscuela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreEscuela() {
        return nombreEscuela;
    }

    public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
     * Sets the value of the nombreEscuela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreEscuela(String value) {
        this.nombreEscuela = value;
    }

    /**
     * Gets the value of the claveEscuela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveEscuela() {
        return claveEscuela;
    }

    /**
     * Sets the value of the claveEscuela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveEscuela(String value) {
        this.claveEscuela = value;
    }

    /**
     * Gets the value of the noIncorporacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoIncorporacion() {
        return noIncorporacion;
    }

    /**
     * Sets the value of the noIncorporacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoIncorporacion(String value) {
        this.noIncorporacion = value;
    }

    /**
     * Gets the value of the gradoEscolar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGradoEscolar() {
        return gradoEscolar;
    }

    /**
     * Sets the value of the gradoEscolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGradoEscolar(String value) {
        this.gradoEscolar = value;
    }

    /**
     * Gets the value of the fechaInicioPeriodo property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getFechaInicioPeriodo() {
        return fechaInicioPeriodo;
    }

    /**
     * Sets the value of the fechaInicioPeriodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setFechaInicioPeriodo(Date value) {
        this.fechaInicioPeriodo = value;
    }

    /**
     * Gets the value of the fechaFinPeriodo property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getFechaFinPeriodo() {
        return fechaFinPeriodo;
    }

    /**
     * Sets the value of the fechaFinPeriodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setFechaFinPeriodo(Date value) {
        this.fechaFinPeriodo = value;
    }

	public String getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(String fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getFechaExpedicionCadena() {
		return fechaExpedicionCadena;
	}

	public void setFechaExpedicionCadena(String fechaExpedicionCadena) {
		this.fechaExpedicionCadena = fechaExpedicionCadena;
	}

}
