##### TIMEOUTS  #####
servicios.externos.ws.service.timeOut.connection=${mvn.servicios.externos.ws.service.timeOut.connection}
servicios.externos.ws.service.response=${mvn.servicios.externos.ws.service.response}
