#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
 
 
nacional.detalle.(class)=org.springframework.web.servlet.view.JstlView
nacional.detalle.url=/WEB-INF/views/domicilio/detalle/nacional.jsp
 

nacional.noencontrado.(class)=org.springframework.web.servlet.view.JstlView
nacional.noencontrado.url=/WEB-INF/views/domicilio/detalle/error.jsp
 
#Tiles redirect

gestionDomicilios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
gestionDomicilios.url=gestionDomicilios

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

domicilio.registro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registro.url=domicilioRegistro

domicilio.captura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.captura.url=domicilioCaptura


domicilio.registroEmbebido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registroEmbebido.url=domicilioRegistroEmbebed

domicilio.nacional.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.nacional.url=domicilioNacional

domicilio.nacionalDelegacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.nacionalDelegacion.url=domicilioNacionalDelegacion

domicilio.nacionalUmf.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.nacionalUmf.url=domicilioNacionalUmf

domicilio.complemento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.complemento.url=domicilioNacionalComp

domicilio.complementoTerminar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.complementoTerminar.url=domicilioComplementoTerminar



tramite.inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.inicio.url=tramiteinicio

tramite.capturar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.capturar.url=tramitecapturar


domicilio.map.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.map.url=domicilioMap

initAdmonDomicilios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initAdmonDomicilios.url=initAdmonDomicilios

admon.domicilio.complemento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
admon.domicilio.complemento.url=admonDomicilioNacionalComp

consulta.detalle.domicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.detalle.domicilio.url=consultaDetalleDomicilio

############# WIZARDS #################
wizardModifDomParticularFisicaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardModifDomParticularFisicaInit.url=wizardModifDomParticularFisicaInit
wizardModifDomParticularFisicaContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardModifDomParticularFisicaContenido.url = wizardModifDomParticularFisicaContenido

wizardRegistrarDomParticularFisicaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistrarDomParticularFisicaInit.url=wizardRegistrarDomParticularFisicaInit
wizardRegistrarDomParticularFisicaInitUbicar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistrarDomParticularFisicaInitUbicar.url=wizardRegistrarDomParticularFisicaInitUbicar
wizardRegistrarDomParticularFisicaContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistrarDomParticularFisicaContenido.url = wizardRegistrarDomParticularFisicaContenido
wizardRegistrarDomParticularFisicaExistente.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistrarDomParticularFisicaExistente.url = wizardRegistrarDomParticularFisicaExistente

############# Wizard para la asignacion, cambio de domicilio y cambio de clinica #################
wizardDomicilioGeneralInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDomicilioGeneralInit.url = wizardDomicilioGeneralInit

wizardDomicilioTipoActualizacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDomicilioTipoActualizacion.url = wizardDomicilioTipoActualizacion

wizardDomicilioGeneralContent.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDomicilioGeneralContent.url = wizardDomicilioGeneralContent

############# widgets #################
widgetUmfCodigoPostalInit.(class)=org.springframework.web.servlet.view.JstlView
widgetUmfCodigoPostalInit.url=/WEB-INF/views/domicilio/widget/util/UmfImssWidget.jsp

widgetMunicipioImssAsentamientoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetMunicipioImssAsentamientoInit.url=/WEB-INF/views/domicilio/widget/util/MunicipioImssWidget.jsp

############# DOMICLIOS COMMON  #################
seccionDomiciliosCommon.(class)=org.springframework.web.servlet.view.JstlView
seccionDomiciliosCommon.url=/WEB-INF/views/domicilio/common/seccionDomiciliosCommon.jsp

wizardDomicilioGeneralAbrirDireccion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDomicilioGeneralAbrirDireccion.url=abrirDireccionWizard

componenteDomicilioRecortado.(class)=org.springframework.web.servlet.view.JstlView
componenteDomicilioRecortado.url = /WEB-INF/views/domicilio/recortado/domicilioRecortado.jsp

pruebaDomicilioRecortado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
pruebaDomicilioRecortado.url = pruebaDomicilioRecortado