#Consulta de persona fisica
consulta.personafisica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.personafisica.url=consultapersonafisica


consulta.candidatos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.candidatos.url=consultacandidatos

consulta.detallecandidato.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.detallecandidato.url=consultadetallecandidato

consulta.detallecandidatocomplementar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
#consulta.detallecandidatocomplementar.url=consultadetallecandidatocomplementar
consulta.detallecandidatocomplementar.url=consultadetallecandidato

#########################################################################
####################### CONSULTA DE PERSONA MORAL #######################
#########################################################################

consulta.personamoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.personamoral.url=consultaPersonaMoral

consulta.personamoralcandidatos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.personamoralcandidatos.url=consultaCandidatosPersonaMoral

consulta.personamoraldetalle.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.personamoraldetalle.url=consultaDetalleCandidatoPersonaMoral

consulta.personamoralcomplementar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.personamoralcomplementar.url=consultaDetalleCandidatoComplementarPersonaMoral

#########################################################################
###### Vistas del manejo de errores generales ###########################
error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

############################################################################
####### Vistas de los servicios REST #######################################
consulta.restpf.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.restpf.url=consultarestpf

consulta.restcandidatos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consulta.restcandidatos.url=consultacandidatosrest

############################################################################
###################### Identificar Cambios Automaticos #####################
ingresar-datos-fisica-test.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ingresar-datos-fisica-test.url = ingresar-datos-fisica-test

ingresar-datos-fisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ingresar-datos-fisica.url = ingresar-datos-fisica

publicar-modificacion-fisica-test.(class) = org.springframework.web.servlet.view.tiles2.TilesView
publicar-modificacion-fisica-test.url = publicar-modificacion-fisica-test

resultado-consultar-comparar-fisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
resultado-consultar-comparar-fisica.url = resultado-consultar-comparar-fisica

ingresar-datos-moral-test.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ingresar-datos-moral-test.url = ingresar-datos-moral-test

ingresar-datos-moral.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ingresar-datos-moral.url = ingresar-datos-moral

publicar-modificacion-moral-test.(class) = org.springframework.web.servlet.view.tiles2.TilesView
publicar-modificacion-moral-test.url = publicar-modificacion-moral-test

resultado-consultar-comparar-moral.(class) = org.springframework.web.servlet.view.tiles2.TilesView
resultado-consultar-comparar-moral.url = resultado-consultar-comparar-moral

############################################################################
######################## Modificacion Datos Manuales #######################
initModManualFisicaTest.(class) = org.springframework.web.servlet.view.tiles2.TilesView
initModManualFisicaTest.url = initModManualFisicaTest

initModManualFisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
initModManualFisica.url = initModManualFisica

capturarModifManualFisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
capturarModifManualFisica.url = capturarModifManualFisica

initModManualMoralTest.(class) = org.springframework.web.servlet.view.tiles2.TilesView
initModManualMoralTest.url = initModManualMoralTest

initModManualMoral.(class) = org.springframework.web.servlet.view.tiles2.TilesView
initModManualMoral.url = initModManualMoral

capturarModifManualMoral.(class) = org.springframework.web.servlet.view.tiles2.TilesView
capturarModifManualMoral.url = capturarModifManualMoral

############################################################################
############################# Notificaciones################################
notificacionesTest.(class) = org.springframework.web.servlet.view.tiles2.TilesView
notificacionesTest.url = notificacionesTest

initConsultaNotificaciones.(class) = org.springframework.web.servlet.view.JstlView
initConsultaNotificaciones.url = /WEB-INF/views/persona/notificacion/mensaje-notificaciones.jsp

detalleConsultaNotificaciones.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleConsultaNotificaciones.url = detalleConsultaNotificaciones

notificacionesResumen.(class)=org.springframework.web.servlet.view.JstlView
notificacionesResumen.url=/WEB-INF/views/persona/notificacion/resumen-notificaciones.jsp

detalle.notificacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalle.notificacion.url=detalleNotificacion

personaResumen.(class)=org.springframework.web.servlet.view.JstlView
personaResumen.url=/WEB-INF/views/persona/fisica/rest/resumenPersona.jsp


############# WIZARDS #################
wizardActualizarDatosFisicaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardActualizarDatosFisicaInit.url=wizardActualizarDatosFisicaInit
wizardActualizarDatosFisicaContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardActualizarDatosFisicaContenido.url = wizardActualizarDatosFisicaContenido

wizardActualizarDatosMoralInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardActualizarDatosMoralInit.url=wizardActualizarDatosMoralInit
wizardActualizarDatosMoralContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardActualizarDatosMoralContenido.url = wizardActualizarDatosMoralContenido

wizardModifMediosParticularesFisicaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardModifMediosParticularesFisicaInit.url=wizardModifMediosParticularesFisicaInit
wizardModifMediosParticularesFisicaContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardModifMediosParticularesFisicaContenido.url = wizardModifMediosParticularesFisicaContenido

wizardModifMediosFiscalesFisicaInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardModifMediosFiscalesFisicaInit.url=wizardModifMediosFiscalesFisicaInit
wizardModifMediosFiscalesFisicaContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardModifMediosFiscalesFisicaContenido.url = wizardModifMediosFiscalesFisicaContenido


############### WIZARDS REGISTRO USUARIO #######################
wizardRegistroUsuarioInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistroUsuarioInit.url=wizardRegistroUsuarioInit
wizardValidaUsuarioFirma.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardValidaUsuarioFirma.url = wizardValidaUsuarioFirma

############### ACTUALIZAR RFC #######################
actualizarRfcWizard.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actualizarRfcWizard.url=actualizarRfcWizard

############### WIZARDS RENOVACION FIEL#######################
wizardRenovacionFielInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRenovacionFielInit.url=wizardRenovacionFielInit
wizardRenovacionFielContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardRenovacionFielContenido.url = wizardRenovacionFielContenido

############### UBICAR PERSONA #######################
ubicar.persona.unit.test.(class)=org.springframework.web.servlet.view.tiles2.TilesView
ubicar.persona.unit.test.url=ubicarPersonaTest
ubicar.persona.init.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ubicar.persona.init.url = ubicarPersonaInit
ubicar.persona.resultados.fisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ubicar.persona.resultados.fisica.url = ubicarResultadosPersonaFisica
ubicar.persona.resultados.moral.(class) = org.springframework.web.servlet.view.tiles2.TilesView
ubicar.persona.resultados.moral.url = ubicarResultadosPersonaMoral
mostrar.vista.folio.(class) = org.springframework.web.servlet.view.tiles2.TilesView
mostrar.vista.folio.url = mostrarFolioSolicitud