############ DESCRIPCION DE LA FORMA DE PAGO PARA LOS REPORTES ############

desFormaPago_01 = Forma de pago: Efectivo
desFormaPago_02 = Forma de pago: Cheque nominativo
desFormaPago_03 = Forma de pago: Transferencia electrónica de fondos