#opciones del portlets
url_archivo = file:/share/oracle/zapdir01_domain/zapdir_cluster1/properties/subdelegaciones.properties
#ids de las delegaciones, 1: habilitada, 0: deshabilitada

#AGUASCALIENTES habilitada 19/11/2015
1 = 1
#BAJA CALIFORNIA NORTE
2 = 0
#BAJA CALIFORNIA SUR habilitada el dia 18/05/2016
3 = 1
#CAMPECHE
4 = 0
#COAHUILA
5 = 0
#COLIMA
6 = 0
#CHIAPAS
7 = 0
#CHIHUAHUA
8 = 0
#VALLE DE MEXICO
9 = 0
#DURANGO
10 = 1
#GUANAJUATO habilitada 19/11/2015
11 = 1
#GUERRERO
12 = 0
#HIDALGO habilitada 19/11/2015
13 = 1
#JALISCO
14 = 0
#VALLE DE MEXICO
15 = 0
#EDO. DE MEXICO
16 = 0
#MICHOACAN
17 = 0
#MORELOS
18 = 1
#NAYARIT
19 = 0
#NUEVO LEON
20 = 1
#OAXACA
21 = 0
#PUEBLA
22 = 0
#QUERETARO
23 = 1
#QUINTANA ROO
24 = 0
#SAN LUIS POTOSI
25 = 0
#SINALOA habilitada el dia 18/05/2016
26 = 1
#SONORA habilitada el dia 18/05/2016
27 = 1
#TABASCO
28 = 0
#TAMAULIPAS
29 = 0
#TLAXCALA
30 = 1
#VERACRUZ NORTE
31 = 1
#VERACRUZ SUR habilitada 19/11/2015
32 = 1
#YUCATAN
33 = 0
#ZACATECAS
34 = 0
#tiene fecha baja 14/02/06	DELEGACION NOROESTE (D.F.)
35 = 0
#tiene fecha baja 14/02/06	DELEGACION NORESTE (D.F.)
36 = 0
#tiene fecha baja 14/02/06	DELEGACION SUROESTE
37 = 0
#tiene fecha baja 14/02/06	DELEGACION SURESTE
38 = 0
#DELEGACION NORTE (D.F.) habilitada 19/11/2015
39 = 1
#DELEGACION SUR (D.F.) habilitada el dia 18/05/2016
40 = 1