serie = IMSS_CSD_01
aplicacion = AplPruebas
rfc.imss = IMS421231I45

## valores para version de pruebas hacia nueva infra##
#serie = IMSS_CER_QA_01
#aplicacion = GENERICO_PRUEBA
#rfc.imss = IMS421231I45


#Valores QA
boveda.url=http://msbovedaimss-documentos.apps.qaocp.imss.gob.mx/api/files/upload
boveda.projectId=831cadbb-a0ef-445c-a19c-ed345f67ee81
boveda.cookie=9ca85180f0e63a960f208f611f59dfb2=5908344c394651d3a2318f248ed616e3; CF=!aomYdmCgPEDGgVRX8qowJxNeJtnGng4taRCl/bU5eFw/9KzF2QF4KQI5pJFazo6D014Foi9HWA1fsg==

#Valores Produccion
#boveda.url=http://msbovedaimss-documentos.apps.ocp.imss.gob.mx/api/files/upload
#boveda.projectId=392e63f3-27ff-4c72-bfc0-25fb5a8bd575
#boveda.cookie=9ca85180f0e63a960f208f611f59dfb2=5908344c394651d3a2318f248ed616e3; CF=!aomYdmCgPEDGgVRX8qowJxNeJtnGng4taRCl/bU5eFw/9KzF2QF4KQI5pJFazo6D014Foi9HWA1fsg==