/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.imss.ctirss.delta.model.clasificacion;


/**
 *
 * @author Jorge A. García
 */
public enum EstatusAnalisisEnum {

//  ASIGNADO(2, "PENDIENTE DE ANALISIS"),
//  LIBERADO(10, "PENDIENTE DE ASIGNAR PARA ANALISIS"),
//	PENDIENTE_DE_ANALISIS(1, "POR ASIGNAR"),

	// Se modifica los estatus para simplificar el flujo del analisis sin asignar ni liberar rps 
    ASIGNADO(2, "PENDIENTE DE ANALISIS"),
    LIBERADO(10, "PENDIENTE DE ASIGNAR PARA ANALISIS"),    
	PENDIENTE_DE_ANALISIS(1, "PENDIENTE DE ANALISIS"),
	
    RATIFICADO_PENDIENTE_AUTORIZACION(3, "RATIFICADO PENDIENTE DE AUTORIZACION"),
    RECTIFICADO_PENDIENTE_AUTORIZACION(4, "RECTIFICADO PENDIENTE AUTORIZACION"),
    RATIFICADO_AUTORIZADO(5, "RATIFICADO AUTORIZADO"),
    RECTIFICADO_AUTORIZADO(6, "RECTIFICADO AUTORIZADO"),
    RATIFICADO_RECHAZADO(7, "RATIFICADO RECHAZADO"),
    RECTIFICADO_RECHAZADO(8, "RECTIFICADO RECHAZADO"),
    RECHAZADO_POR_REGLA_RPC(9, "RECHAZO POR VALIDACION DE REGLA RPC"),
    RATIFICADO_AUTORIZADO_Y_RECHAZADO(11, "PENDIENTE DE ANALISIS POR RECHAZO DE UNA RATIFICACION AUTORIZADA"),
    RECTIFICADO_AUTORIZADO_Y_RECHAZADO(12, "PENDIENTE DE ANALISIS POR RECHAZO DE UNA RECTIFICACION AUTORIZADA"),
    RATIFICADO_PENDIENTE_AUTORIZACION_NIVEL_2(13, "RATIFICADO PENDIENTE DE AUTORIZAR NIVEL 2"),
    RECTIFICADO_PENDIENTE_AUTORIZACION_NIVEL_2(14, "RECTIFICADO PENDIENTE DE AUTORIZAR NIVEL 2"),
    RATIFICADO_RECHAZADO_AUTORIZACION_NIVEL_2(15, "RATIFICADO RECHAZADO AUTORIZACION NIVEL 2"),
    RECTIFICADO_RECHAZADO_AUTORIZACION_NIVEL_2(16, "RECTIFICADO RECHAZADO AUTORIZACION NIVEL 2"),
    RATIFICADO_OPINION_AUTORIZADA(17, "RATIFICADO OPINION AUTORIZADA"),
    RECTIFICADO_OPINION_AUTORIZADA(18, "RECTIFICADO OPINION AUTORIZADA"),
	CANCELADO_POR_NUEVO_TRAMITE_DE_GCE(19, "CANCELADO POR NUEVO TRAMITE DE CLASIFICACION DE EMPRESAS"),
	CANCELADO_POR_BAJA_PATRONAL(20, "CANCELADO POR BAJA PATRONAL"),
	RECTIFICADO_OPINION_AUTORIZADA_RATIFICADA(21, "RECTIFICADO OPINION AUTORIZADA RATIFICADA"),
	RECTIFICADO_OPINION_AUTORIZADA_RECTIFICADA(22, "RECTIFICADO OPINION AUTORIZADA RECTIFICADA"),
    POR_REGULARIZAR(26, "POR REGULARIZAR"),
    SOLICITUD_DESECHADA(27, "SOLICITUD DESECHADA"),
    IMPOSIBILIDAD_DE_ANALISIS(28, "IMPOSIBILIDAD DE ANALISIS POR INCOSISTENCIA DE DATOS");
    
    private final int clave;
	private final String descripcion;
	
	
	private EstatusAnalisisEnum(int clave, String descripcion) {
		this.clave = clave;
		this.descripcion = descripcion;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public int getClave() {
		return clave;
	}	
}