package mx.gob.imss.ctirss.delta.model.clasificacion;
/**
 * 
 * @author Eduardo Gonzalez
 * @since 2012/10/04
 *
 */
public enum TipoCausaAnalisisEnum {
	INSCRIPCION_INICIAL(0, "INSCRIPCION INICIAL"),
	SUSTITUCION(5,"SUSTITUCION"),
	FUSION(6,"FUSION"),
	CAMBIO_POR_DISPOSICION_DE_LEY_O_DEL_RACERF(2, "CAMBIO POR DISPOSICION DE LEY O DEL RACERF"),
	RECTIFICACION_DE_LA_CLASIFICACION_INICIAL(30, "RECTIFICACION DE LA CLASIFICACION INICIAL"),
	RECTIFICACION_DE_CAMBIO_DE_ACTIVIDAD_ECONOMICA(31, "RECTIFICACION DE CAMBIO DE ACTIVIDAD ECONOMICA"),
	RECTIFICACION_DE_CAMBIO_POR_DISPOSICION_DE_LEY_O_DEL_RACERF(32, "RECTIFICACION DE CAMBIO POR DISPOSICION DE LEY O DEL RACERF"),
	RECTIFICACION_DE_INCORPORACION_DE_ACTIVIDADES(33, "RECTIFICACION DE INCORPORACION DE ACTIVIDADES"),
	RECTIFICACION_DE_ESCISION(34, "RECTIFICACION DE ESCISION"),
	RECTIFICACION_DE_SUSTITUCION_PATRONAL(35, "RECTIFICACION DE SUSTITUCION PATRONAL"),
	RECTIFICACION_DE_FUSION(36, "RECTIFICACION DE FUSION"),
	RECTIFICACION_DE_COMPRA_DE_ACTIVOS(37, "RECTIFICACION DE COMPRA DE ACTIVOS"),
	RECTIFICACION_DE_COMODATO(38, "RECTIFICACION DE COMODATO"),
	RECTIFICACION_DE_ENAJENACION(39, "RECTIFICACION DE ENAJENACION"),
	RECTIFICACION_DE_ARRENDAMIENTO(40, "RECTIFICACION DE ARRENDAMIENTO"),
	RECTIFICACION_DE_FIDEICOMISO_TRASLATIVO(41, "RECTIFICACION DE FIDEICOMISO TRASLATIVO"),
	RECTIFICACION_DE_CAMBIO_DE_DOMICILIO(42, "RECTIFICACION DE CAMBIO DE DOMICILIO"),
	RECTIFICACION_DE_REANUDACION_DE_ACTIVIDADES(43, "RECTIFICACION DE REANUDACION DE ACTIVIDADES"),
	RECTIFICACION_DE_CANCELACION_DE_RPC(44, "RECTIFICACION DE CANCELACION DE RPC"),
	RECTIFICACION_POR_ERROR_EN_EL_ANALISIS(45, "RECTIFICACION POR ERROR EN EL ANALISIS"),
	SUSTITUCION_SUBCONTRATACION(15,"SUSTITUCION SUBCONTRATACION"),
	MODIFICACION_SRT_CAMBIO_DOMICILIO_DIFERENTE_MUNICIPIO(17,"MODIFICACION EN SRT POR CAMBIO DE DOMICILIO EN DIFERENTES MUNICIPIOS"),
	
	;
	
	private final int clave;
	private final String descripcion;
	
	private TipoCausaAnalisisEnum(int cve, String des){
		this.clave = cve;
		this.descripcion = des;
	}

	public int getClave() {
		return clave;
	}

	public String getDescripcion() {
		return descripcion;
	}
	
	
}
