package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.MotivoTipoIncidenciaDTO;

/**
 * RocTipoIncidencia generated by hbm2java
 */
@Entity
@Table(name = "ROC_MOTIVO_INCIDENCIA", schema = "MGPROC01")
@Transactional
public class RocMotivoIncidencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4057071099432975428L;
	
	private Long cveMotivoTipoIncidencia;
	private RocTipoIncidencia rocTipoIncidencia;
	private RocMotivo rocMotivo;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocMotivoIncidencia() {
	}

	public RocMotivoIncidencia(Long cveMotivoTipoIncidencia,RocTipoIncidencia rocTipoIncidencia,RocMotivo rocMotivo) {
		this.cveMotivoTipoIncidencia = cveMotivoTipoIncidencia;
		this.rocTipoIncidencia = rocTipoIncidencia;
		this.rocMotivo = rocMotivo;
	}

	public RocMotivoIncidencia(Long cveMotivoTipoIncidencia, RocTipoIncidencia rocTipoIncidencia,RocMotivo rocMotivo, 
			Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {	
		this.cveMotivoTipoIncidencia = cveMotivoTipoIncidencia;
		this.rocTipoIncidencia = rocTipoIncidencia;
		this.rocMotivo = rocMotivo;		
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id
	@Column(name = "CVE_ID_MOTIVO_INCIDENCIA", unique = true, nullable = false)
	public Long getCveMotivoTipoIncidencia() {
		return this.cveMotivoTipoIncidencia;
	}

	public void setCveMotivoTipoIncidencia(Long cveMotivoTipoIncidencia) {
		this.cveMotivoTipoIncidencia = cveMotivoTipoIncidencia;
	}
	
	@ManyToOne(fetch = FetchType.LAZY,optional = false,targetEntity=RocTipoIncidencia.class)
	@JoinColumn(name = "CVE_ID_TIPO_INCIDENCIA", nullable = false)
	public RocTipoIncidencia getRocTipoIncidencia() {
		return rocTipoIncidencia;
	}

	public void setRocTipoIncidencia(RocTipoIncidencia rocTipoIncidencia) {
		this.rocTipoIncidencia = rocTipoIncidencia;
	}
	
	@ManyToOne(fetch = FetchType.LAZY , optional = false)
	@JoinColumn(name = "CVE_ID_MOTIVO", nullable = false)
	public RocMotivo getRocMotivo() {
		return rocMotivo;
	}

	public void setRocMotivo(RocMotivo rocMotivo) {
		this.rocMotivo = rocMotivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	
	public MotivoTipoIncidenciaDTO toConvertMotivoTipoIncidenciaDTO(){
		
		MotivoTipoIncidenciaDTO motivoTipoIncidenciaDTO = new MotivoTipoIncidenciaDTO();
		
		motivoTipoIncidenciaDTO.setCveMotivoTipoIncidencia(this.getCveMotivoTipoIncidencia());
		if(this.getRocTipoIncidencia() != null)
			motivoTipoIncidenciaDTO.setTipoIncidenciaDTO(this.getRocTipoIncidencia().toConvertTipoIncidenciaDTO());
		if(this.getRocMotivo() != null)
			motivoTipoIncidenciaDTO.setMotivoDTO(this.getRocMotivo().toConvertMotivoDTO());
		
		return motivoTipoIncidenciaDTO;
		
	}

}
