package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.SubDelegacionDTO;

/**
 * RocSubdelegacion generated by hbm2java
 */
@Entity
@Table(name = "DIC_SUBDELEGACION", schema = "MGPROC01")
@Transactional
public class RocSubdelegacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6339694869108423798L;
	
	private Long cveSubdelegacion;
	private String nomSubdelegacion;
	private Long cveCodigo;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;	
	private Long domicilioId;
	private RocDelegacion rocDelegacion;
	

	public RocSubdelegacion() {
	}

	public RocSubdelegacion(Long cveSubdelegacion, RocDelegacion rocDelegacion) {
		this.cveSubdelegacion = cveSubdelegacion;
		this.rocDelegacion = rocDelegacion;
	}

	public RocSubdelegacion(Long cveSubdelegacion) {
		this.cveSubdelegacion = cveSubdelegacion;
	}

		
	public RocSubdelegacion(Long cveSubdelegacion, String nomSubdelegacion,
	Long cveCodigo, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado, Long domicilioId, RocDelegacion rocDelegacion) {	
		this.cveSubdelegacion = cveSubdelegacion;
		this.nomSubdelegacion = nomSubdelegacion;
		this.cveCodigo = cveCodigo;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
		this.domicilioId = domicilioId;
		this.rocDelegacion = rocDelegacion;

	}

	@Id

	@Column(name = "CVE_ID_SUBDELEGACION", unique = true, nullable = false)
	public Long getCveSubdelegacion() {
		return this.cveSubdelegacion;
	}

	public void setCveSubdelegacion(Long cveSubdelegacion) {
		this.cveSubdelegacion = cveSubdelegacion;
	}

	@Column(name = "DES_SUBDELEGACION", length = 80)
	public String getNomSubdelegacion() {
		return this.nomSubdelegacion;
	}

	public void setNomSubdelegacion(String nomSubdelegacion) {
		this.nomSubdelegacion = nomSubdelegacion;
	}

	@Column(name = "CLAVE_SUBDELEGACION")
	public Long getCveCodigo() {
		return this.cveCodigo;
	}

	public void setCveCodigo(Long cveCodigo) {
		this.cveCodigo = cveCodigo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}	
	
	@Column(name = "DOMICILIO_ID")
	public Long getDomicilioId() {
		return domicilioId;
	}

	public void setDomicilioId(Long domicilioId) {
		this.domicilioId = domicilioId;
	}

	@ManyToOne(fetch = FetchType.EAGER, optional = false)
	@JoinColumn(name = "CVE_ID_DELEGACION")	
	public RocDelegacion getRocDelegacion() {
		return this.rocDelegacion;
	}

	public void setRocDelegacion(RocDelegacion rocDelegacion) {
		this.rocDelegacion = rocDelegacion;
	}
	
	
	
	public SubDelegacionDTO toConvertSubdelegacionDTO(){
		SubDelegacionDTO subDelegacionDTO = new SubDelegacionDTO();
		
		subDelegacionDTO.setCveSubdelegacion(this.getCveSubdelegacion());
		subDelegacionDTO.setNomSubdelegacion(this.getNomSubdelegacion());
		subDelegacionDTO.setCveCodigo(this.getCveCodigo());

		if(this.getRocDelegacion() != null)
		{
			subDelegacionDTO.setDelegacionDTO(this.getRocDelegacion().toConvertDelegacionDTO());
		}
		
		return subDelegacionDTO;
		
	}


}
