package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.TipoIncidenciaDTO;

/**
 * RocTipoIncidencia generated by hbm2java
 */
@Entity
@Table(name = "ROC_TIPO_INCIDENCIA", schema = "MGPROC01")
@Transactional
public class RocTipoIncidencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4057071099432975428L;
	
	private Long cveTipoIncidencia;
	private String desTipoIncidencia;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocTipoIncidencia() {
	}

	public RocTipoIncidencia(Long cveTipoIncidencia) {
		this.cveTipoIncidencia = cveTipoIncidencia;
	}


	public RocTipoIncidencia(Long cveTipoIncidencia, String desTipoIncidencia, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {	
		this.cveTipoIncidencia = cveTipoIncidencia;
		this.desTipoIncidencia = desTipoIncidencia;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id

	@Column(name = "CVE_ID_TIPO_INCIDENCIA", unique = true, nullable = false)
	public Long getCveTipoIncidencia() {
		return this.cveTipoIncidencia;
	}

	public void setCveTipoIncidencia(Long cveTipoIncidencia) {
		this.cveTipoIncidencia = cveTipoIncidencia;
	}

	@Column(name = "DES_TIPO_INCIDENCIA", length = 80)
	public String getDesTipoIncidencia() {
		return this.desTipoIncidencia;
	}

	public void setDesTipoIncidencia(String desTipoIncidencia) {
		this.desTipoIncidencia = desTipoIncidencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	public TipoIncidenciaDTO toConvertTipoIncidenciaDTO(){
		
		TipoIncidenciaDTO tipoIncidenciaDTO = new TipoIncidenciaDTO();
		
		tipoIncidenciaDTO.setCveTipoIncidencia(this.getCveTipoIncidencia());
		tipoIncidenciaDTO.setDesTipoIncidencia(this.getDesTipoIncidencia());
		
		return tipoIncidenciaDTO;
		
	}

}
