package mx.gob.imss.ctirss.correccion.catalogos.base.model;
// default package
// Generated 26/11/2011 12:50:35 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SacZona generated by hbm2java
 */
@MappedSuperclass
public class AbstractSacZona extends AbstractModel {

	private BigDecimal cvePk;
	private int numHibernateVersion;
	private String nomNombre;

	public AbstractSacZona() {
	}

	public AbstractSacZona(BigDecimal cvePk, int numHibernateVersion, String nomNombre) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.nomNombre = nomNombre;
	}

	@Id
	@Column(name = "CVE_PK")
	public BigDecimal getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(BigDecimal cvePk) {
		this.cvePk = cvePk;
	}

	@Column(name = "NUM_HIBERNATE_VERSION")
	public int getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(int numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	@Column(name = "NOM_NOMBRE")
	public String getNomNombre() {
		return this.nomNombre;
	}

	public void setNomNombre(String nomNombre) {
		this.nomNombre = nomNombre;
	}

}
