package mx.gob.imss.ctirss.correccion.catalogos.base.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SatAvisosub generated by hbm2java
 */
@MappedSuperclass
public class AbstractSatAvisosub extends AbstractModel {

	@Id
	@Column(name="CVE_PK")
	private BigDecimal cvePk;
	
	@Column(name="NUM_HIBERNATE_VERSION")
	private int numHibernateVersion;
	
	@Column(name="FEC_FECHAFORMATO_FC")
	private Date fecFechaformatoFc;
	
	@Column(name="FEC_FECHAINICIO_FC")
	private Date fecFechainicioFc;
	
	@Column(name="FEC_FECHATERMINO_FC")
	private Date fecFechaterminoFc;
	
	@Column(name="FEC_FECHAREGISTRO_FC")
	private Date fecFecharegistroFc;
	
	@Column(name="IND_MATERIALESYMO")
	private Boolean indMaterialesymo;
	
	@Column(name="IND_MANOOBRA")
	private Boolean indManoobra;
	
	@Column(name="REF_LUGARREGISTRO")
	private String refLugarregistro;
	
	@Column(name="REF_RFC_PATRONSUB")
	private String refRfcPatronsub;
	
	@Column(name="CVE_FK_OBRA")
	private BigDecimal cveFkObra;
	
	@Column(name="CVE_FK_PATRON")
	private BigDecimal cveFkPatron;

	public AbstractSatAvisosub() {
	}

	public AbstractSatAvisosub(BigDecimal cvePk, int numHibernateVersion,
			Date fecFechainicioFc, Date fecFechaterminoFc,
			Date fecFecharegistroFc, String refLugarregistro) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.fecFechainicioFc = fecFechainicioFc;
		this.fecFechaterminoFc = fecFechaterminoFc;
		this.fecFecharegistroFc = fecFecharegistroFc;
		this.refLugarregistro = refLugarregistro;
	}

	public AbstractSatAvisosub(BigDecimal cvePk, int numHibernateVersion,
			Date fecFechaformatoFc, Date fecFechainicioFc,
			Date fecFechaterminoFc, Date fecFecharegistroFc,
			Boolean indMaterialesymo, Boolean indManoobra,
			String refLugarregistro, String refRfcPatronsub,
			BigDecimal cveFkObra, BigDecimal cveFkPatron) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.fecFechaformatoFc = fecFechaformatoFc;
		this.fecFechainicioFc = fecFechainicioFc;
		this.fecFechaterminoFc = fecFechaterminoFc;
		this.fecFecharegistroFc = fecFecharegistroFc;
		this.indMaterialesymo = indMaterialesymo;
		this.indManoobra = indManoobra;
		this.refLugarregistro = refLugarregistro;
		this.refRfcPatronsub = refRfcPatronsub;
		this.cveFkObra = cveFkObra;
		this.cveFkPatron = cveFkPatron;
	}

	public BigDecimal getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(BigDecimal cvePk) {
		this.cvePk = cvePk;
	}

	public int getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(int numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	public Date getFecFechaformatoFc() {
		return this.fecFechaformatoFc;
	}

	public void setFecFechaformatoFc(Date fecFechaformatoFc) {
		this.fecFechaformatoFc = fecFechaformatoFc;
	}

	public Date getFecFechainicioFc() {
		return this.fecFechainicioFc;
	}

	public void setFecFechainicioFc(Date fecFechainicioFc) {
		this.fecFechainicioFc = fecFechainicioFc;
	}

	public Date getFecFechaterminoFc() {
		return this.fecFechaterminoFc;
	}

	public void setFecFechaterminoFc(Date fecFechaterminoFc) {
		this.fecFechaterminoFc = fecFechaterminoFc;
	}

	public Date getFecFecharegistroFc() {
		return this.fecFecharegistroFc;
	}

	public void setFecFecharegistroFc(Date fecFecharegistroFc) {
		this.fecFecharegistroFc = fecFecharegistroFc;
	}

	public Boolean getIndMaterialesymo() {
		return this.indMaterialesymo;
	}

	public void setIndMaterialesymo(Boolean indMaterialesymo) {
		this.indMaterialesymo = indMaterialesymo;
	}

	public Boolean getIndManoobra() {
		return this.indManoobra;
	}

	public void setIndManoobra(Boolean indManoobra) {
		this.indManoobra = indManoobra;
	}

	public String getRefLugarregistro() {
		return this.refLugarregistro;
	}

	public void setRefLugarregistro(String refLugarregistro) {
		this.refLugarregistro = refLugarregistro;
	}

	public String getRefRfcPatronsub() {
		return this.refRfcPatronsub;
	}

	public void setRefRfcPatronsub(String refRfcPatronsub) {
		this.refRfcPatronsub = refRfcPatronsub;
	}

	public BigDecimal getCveFkObra() {
		return this.cveFkObra;
	}

	public void setCveFkObra(BigDecimal cveFkObra) {
		this.cveFkObra = cveFkObra;
	}

	public BigDecimal getCveFkPatron() {
		return this.cveFkPatron;
	}

	public void setCveFkPatron(BigDecimal cveFkPatron) {
		this.cveFkPatron = cveFkPatron;
	}

}
