package mx.gob.imss.ctirss.correccion.catalogos.base.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SatIncidencia generated by hbm2java
 */
@MappedSuperclass
public class AbstractSatIncidencia extends AbstractModel {

	@Id
	@Column(name="CVE_PK")
	private BigDecimal cvePk;
	
	@Column(name="NUM_HIBERNATE_VERSION")
	private int numHibernateVersion;
	
	@Column(name="FEC_FECHAFORMATO_FC")
	private Date fecFechaformatoFc;
	
	@Column(name="FEC_FECHAINICIO_FC")
	private Date fecFechainicioFc;
	
	@Column(name="FEC_FECHATERMINO_FC")
	private Date fecFechaterminoFc;
	
	@Column(name="IMP_IMPORTE")
	private BigDecimal impImporte;
	
	@Column(name="CVE_FK_INCIDENCIA")
	private BigDecimal cveFkIncidencia;
	
	@Column(name="IMP_CUOTASIMSS")
	private BigDecimal impCuotasimss;
	
	@Column(name="POR_AVANCE")
	private Short porAvance;
	
	@Column(name="CVE_FK_OBRA")
	private BigDecimal cveFkObra;
	
	@Column(name="FEC_FECHAREGISTRO_FC")
	private Date fecFecharegistroFc;
	
	@Column(name="REF_LUGARREGISTRO")
	private String refLugarregistro;
	
	@Column(name="CVE_FK_TIPCAUSAINCIDENC")
	private BigDecimal cveFkTipcausaincidenc;
	
	@Column(name="DES_OTRA_CAUSA")
	private String desOtraCausa;
	
	@Column(name="CAN_SUPERFICIE")
	private BigDecimal canSuperficie;

	public AbstractSatIncidencia() {
	}

	public AbstractSatIncidencia(BigDecimal cvePk, int numHibernateVersion,
			BigDecimal cveFkIncidencia, BigDecimal cveFkObra,
			Date fecFecharegistroFc, String refLugarregistro) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.cveFkIncidencia = cveFkIncidencia;
		this.cveFkObra = cveFkObra;
		this.fecFecharegistroFc = fecFecharegistroFc;
		this.refLugarregistro = refLugarregistro;
	}

	public AbstractSatIncidencia(BigDecimal cvePk, int numHibernateVersion,
			Date fecFechaformatoFc, Date fecFechainicioFc,
			Date fecFechaterminoFc, BigDecimal impImporte,
			BigDecimal cveFkIncidencia, BigDecimal impCuotasimss,
			Short porAvance, BigDecimal cveFkObra, Date fecFecharegistroFc,
			String refLugarregistro, BigDecimal cveFkTipcausaincidenc,
			String desOtraCausa, BigDecimal canSuperficie) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.fecFechaformatoFc = fecFechaformatoFc;
		this.fecFechainicioFc = fecFechainicioFc;
		this.fecFechaterminoFc = fecFechaterminoFc;
		this.impImporte = impImporte;
		this.cveFkIncidencia = cveFkIncidencia;
		this.impCuotasimss = impCuotasimss;
		this.porAvance = porAvance;
		this.cveFkObra = cveFkObra;
		this.fecFecharegistroFc = fecFecharegistroFc;
		this.refLugarregistro = refLugarregistro;
		this.cveFkTipcausaincidenc = cveFkTipcausaincidenc;
		this.desOtraCausa = desOtraCausa;
		this.canSuperficie = canSuperficie;
	}

	public BigDecimal getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(BigDecimal cvePk) {
		this.cvePk = cvePk;
	}

	public int getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(int numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	public Date getFecFechaformatoFc() {
		return this.fecFechaformatoFc;
	}

	public void setFecFechaformatoFc(Date fecFechaformatoFc) {
		this.fecFechaformatoFc = fecFechaformatoFc;
	}

	public Date getFecFechainicioFc() {
		return this.fecFechainicioFc;
	}

	public void setFecFechainicioFc(Date fecFechainicioFc) {
		this.fecFechainicioFc = fecFechainicioFc;
	}

	public Date getFecFechaterminoFc() {
		return this.fecFechaterminoFc;
	}

	public void setFecFechaterminoFc(Date fecFechaterminoFc) {
		this.fecFechaterminoFc = fecFechaterminoFc;
	}

	public BigDecimal getImpImporte() {
		return this.impImporte;
	}

	public void setImpImporte(BigDecimal impImporte) {
		this.impImporte = impImporte;
	}

	public BigDecimal getCveFkIncidencia() {
		return this.cveFkIncidencia;
	}

	public void setCveFkIncidencia(BigDecimal cveFkIncidencia) {
		this.cveFkIncidencia = cveFkIncidencia;
	}

	public BigDecimal getImpCuotasimss() {
		return this.impCuotasimss;
	}

	public void setImpCuotasimss(BigDecimal impCuotasimss) {
		this.impCuotasimss = impCuotasimss;
	}

	public Short getPorAvance() {
		return this.porAvance;
	}

	public void setPorAvance(Short porAvance) {
		this.porAvance = porAvance;
	}

	public BigDecimal getCveFkObra() {
		return this.cveFkObra;
	}

	public void setCveFkObra(BigDecimal cveFkObra) {
		this.cveFkObra = cveFkObra;
	}

	public Date getFecFecharegistroFc() {
		return this.fecFecharegistroFc;
	}

	public void setFecFecharegistroFc(Date fecFecharegistroFc) {
		this.fecFecharegistroFc = fecFecharegistroFc;
	}

	public String getRefLugarregistro() {
		return this.refLugarregistro;
	}

	public void setRefLugarregistro(String refLugarregistro) {
		this.refLugarregistro = refLugarregistro;
	}

	public BigDecimal getCveFkTipcausaincidenc() {
		return this.cveFkTipcausaincidenc;
	}

	public void setCveFkTipcausaincidenc(BigDecimal cveFkTipcausaincidenc) {
		this.cveFkTipcausaincidenc = cveFkTipcausaincidenc;
	}

	public String getDesOtraCausa() {
		return this.desOtraCausa;
	}

	public void setDesOtraCausa(String desOtraCausa) {
		this.desOtraCausa = desOtraCausa;
	}

	public BigDecimal getCanSuperficie() {
		return this.canSuperficie;
	}

	public void setCanSuperficie(BigDecimal canSuperficie) {
		this.canSuperficie = canSuperficie;
	}

}
