package mx.gob.imss.ctirss.correccion.catalogos.base.model;

// default package
// Generated 22/11/2011 12:05:24 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SatReltrabajadores generated by hbm2java
 */
@MappedSuperclass
public class AbstractSatReltrabajadores extends AbstractModel {

	@Id
	@Column(name="CVE_PK")
	private BigDecimal cvePk;
	
	@Column(name="NUM_HIBERNATE_VERSION")
	private int numHibernateVersion;
	
	@Column(name="FEC_FECHAREGISTRO_FC")
	private Date fecFecharegistroFc;
	
	@Column(name="REF_LUGARREGISTRO")
	private String refLugarregistro;
	
	@Column(name="NUM_PERIODO")
	private Integer numPeriodo;
	
	@Column(name="IND_RELACIONINICIAL")
	private boolean indRelacioninicial;
	
	@Column(name="CVE_FK_OBRA")
	private BigDecimal cveFkObra;

	public AbstractSatReltrabajadores() {
	}

	public AbstractSatReltrabajadores(BigDecimal cvePk, int numHibernateVersion,
			Date fecFecharegistroFc, String refLugarregistro,
			boolean indRelacioninicial, BigDecimal cveFkObra) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.fecFecharegistroFc = fecFecharegistroFc;
		this.refLugarregistro = refLugarregistro;
		this.indRelacioninicial = indRelacioninicial;
		this.cveFkObra = cveFkObra;
	}

	public AbstractSatReltrabajadores(BigDecimal cvePk, int numHibernateVersion,
			Date fecFecharegistroFc, String refLugarregistro,
			Integer numPeriodo, boolean indRelacioninicial, BigDecimal cveFkObra) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.fecFecharegistroFc = fecFecharegistroFc;
		this.refLugarregistro = refLugarregistro;
		this.numPeriodo = numPeriodo;
		this.indRelacioninicial = indRelacioninicial;
		this.cveFkObra = cveFkObra;
	}

	public BigDecimal getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(BigDecimal cvePk) {
		this.cvePk = cvePk;
	}

	public int getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(int numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	public Date getFecFecharegistroFc() {
		return this.fecFecharegistroFc;
	}

	public void setFecFecharegistroFc(Date fecFecharegistroFc) {
		this.fecFecharegistroFc = fecFecharegistroFc;
	}

	public String getRefLugarregistro() {
		return this.refLugarregistro;
	}

	public void setRefLugarregistro(String refLugarregistro) {
		this.refLugarregistro = refLugarregistro;
	}

	public Integer getNumPeriodo() {
		return this.numPeriodo;
	}

	public void setNumPeriodo(Integer numPeriodo) {
		this.numPeriodo = numPeriodo;
	}

	public boolean isIndRelacioninicial() {
		return this.indRelacioninicial;
	}

	public void setIndRelacioninicial(boolean indRelacioninicial) {
		this.indRelacioninicial = indRelacioninicial;
	}

	public BigDecimal getCveFkObra() {
		return this.cveFkObra;
	}

	public void setCveFkObra(BigDecimal cveFkObra) {
		this.cveFkObra = cveFkObra;
	}

}
