package mx.gob.imss.ctirss.correccion.catalogos.base.model;

// default package
// Generated 8/11/2011 04:19:18 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SacEntidadfed generated by hbm2java
 */
@MappedSuperclass
public class AbstractSacEntidadfed extends AbstractModel {

	@Id
	@Column(name="CVE_PK")
	private Integer cvePk;
	
	@Column(name="NUM_HIBERNATE_VERSION")
	private Integer numHibernateVersion;
	
	@Column(name="CVE_CODIGO")
	private String cveCodigo;
	
	@Column(name="NOM_NOMBRE")
	private String nomNombre;	

	public Integer getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(Integer cvePk) {
		this.cvePk = cvePk;
	}

	public Integer getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(Integer numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	public String getCveCodigo() {
		return this.cveCodigo;
	}

	public void setCveCodigo(String cveCodigo) {
		this.cveCodigo = cveCodigo;
	}

	public String getNomNombre() {
		return this.nomNombre;
	}

	public void setNomNombre(String nomNombre) {
		this.nomNombre = nomNombre;
	}
}
