#DEFINICION DE RUTAS
#RUTA BASE UNIX PRODUCTIVO
appRutaBase=/ctirss/incorporacion/trabajadores/domains/d_trabajadores/
#RUTA BASE UNIX DESARROLLO
#appRutaBase=/cotarpt/patrones/users/wlpatrones/domains/d_trabajadores/
#RUTA BASE AMBIENTE LOCAL
#appRutaBase=/ctirss/incorporacion/trabajadores/domains/d_trabajadores/
saiiaRutaBase=archivos/archivosSaiia/
sieRuta=archivos/archivosSieReingreso/
entradaProcesoCanase=archivos/batchCanase/entrada/
salidaProcesoCanase=archivos/batchCanase/salida/
rutaCanaseTemporal=archivos/batchCanase/temporal/

saiiaExtension=txt
saiiaPrefijoReingreso=reingresoTrabajadores
saiiaPrefijoJourcan=jourcan
saiiaPrefijoSIE=reingresoTrabajadoresSIE
archivoSIEBase=SIEArchivoBase
archivoDisMagXSD=archivos/archivoDisMag.xsd



# Nombres de archivo para guardar en el cliente
archivoClienteReingresoSEI=reingSEI.txt
archivoClienteReingreso=reing.txt

# URL inicial de los Jsp's para generacion de XML
 #pathXmlToPdf=/imss/afiliacion/comunes/xml/	
pathXmlToPdf=/imss/afiliacion/trabajadores/
#pathXmlToPdf=/trimss/afiliacion/trabajadores/


# Multiple DB access
dbAccessConfigurationFile=C:/desarollo/Trabajadores/webapps/imss/WEB-INF/classes/DBSources.xml


pathDelegacionRespuestaAccesoXML=soap-env:Envelope/soap-env:Body/SalidaServicioAcceso/Persona/Direccion/DelegacionIMSS

pathSubdelegacionRespuestaAccesoXML=soap-env:Envelope/soap-env:Body/SalidaServicioAcceso/Persona/Direccion/SubdelegacionIMSS


# Parámetros de formatos de fechas y horas
# Es necesario cambiar UNICAMENTE este parametro en función del formato para manejo de fechas de la BD
formatoFechaBD=dd/MM/yyyy
formatoFechaCitas=yyyy-MM-dd kk:mm:ss
formatoHora=kk:mm:ss
formateFechaReportes=yyyy/MM/dd

# Parametros para COnexion de Acceso
idSistemaTrabajadores = 2
usuarioAltaNSS = 917
usuarioReportes = 921
#ROLES NUEVOS SEGUN ADMIN
rol_nivel_central=905
rol_ventanilla=924
rol_jefe_supervision=913
rol_jefe_oficina=918
rol_jefe_departamento=917


########################################################################
## Alias de los nombres JNDI de los datasources para conexion a BD
# Conexion a la base de datos de Patrones
patron=jdbc/dbPatrones
# Conexion a la base de datos de Reing, default al CIZ1 
sindo=jdbc/dbSindo
# Conexion a la base de datos de Reing, CIZ1
sindo1=jdbc/dbSindo
# Conexion a la base de datos de Reing, CIZ2 (Temporalmente apunta aun al CIZ1)
sindo2=jdbc/dbSindo
# Conexion a la base de datos de Reing, CIZ3 (Temporalmente apunta aun al CIZ1)
sindo3=jdbc/dbSindo
# Conexion a la base de datos de Trabajadores
trabajador=jdbc/dbTrabajadores
# Conexion a la base de datos de Acceso
acceso=jdbc/dbAcceso

#########################################################################
#propiedades para conectarse y consultar el MAINFRAME
#----PRODUCCION-----
#pathCanaseMainFrame=11.254.171.204
#cizCanaseMainFrame=CI1CN

#----DESARROLLO----
pathCanaseMainFrame=11.254.171.137
cizCanaseMainFrame=CI4NL

puertoCanaseMainFrame=23
#debugTransaccionMainFrame=false
debugTransaccionMainFrame=true
#####tiempo que espera la aplicacion la respueta de una pantalla del mainframe se mide en segundos
tiempoEsperaMainFrame=120

##############anio para cargar combos ############
anioInicioCombo=1910

#############propiedades para modulo de reportes#########################
#PRODUCCION
reportesRutaBase=/ctirss/incorporacion/trabajadores/domains/d_trabajadores/reportes/
#DESARROLLO
#reportesRutaBase=/cotarpt/patrones/users/wlpatrones/domains/d_trabajadores/reportes/

formatoFechaReportes=yyyy-MM-dd
folderImg=img/
pathReportesTrabajadores=trabajadores/
reporteTrab=trabajador

######################valor de Fehca de del y sub activos#######
fechaBajaActiva=9999-12-31

intentosCatalogo=3
intentosAlta=3
intentosBitacora=3
intentosMetrica=3

######################Valores de cuando se va realizar la separacion de alos archivos SIE#######
horaPrScheduler=15
minutoPrScheduler=20
segundoPrScheduler=00
######################Valores de cuando genera archivo  de asignacion para CANASE#######
horaPrSchedulerCanase=23
minutoPrSchedulerCanase=00
segundoPrSchedulerCanase=00


############# valored default para delegacion subdelegacion y UMF de SIE##########
subDelegacionDefaultSIE=1
delegacionDefaultSIE=40
umfDefaultSIE=34
cizDefaultSIE=1
usuarioConvencional=ESTUDIA
nrpDelegaSubdelegaUmfDefualSIE=E2375819109,1,23,01,93|B2199017321,2,23,01,94|E2317842102,3,23,01,95

############# valores para localizar el cerfiticado digital##########
rutaCertificado=archivos/certificado/
ClaveFTP=A2YKrADMe3E=
nombreCertificado=CertificadoDig.cer
############# valored default para enviar ftp a IDSE##########
ipServidorIdse=11.254.14.177
nombreUserIdse=rpadmin
passUserIdse=rpadmin
rutaDesposito=/cotarp/IDSE/repository/idse/archivoIdse/estudiantes
############# Tiempo de espera del webServices de RENAPO Segundos##########
timeOutRENAPO=5

#Modalidades de patrones aceptadas para proceso SIE, separadas por pipes "|"
modalidadesCorrectas=32