#Variables para conexion t3 con los servicios digitales
service.provider.url.servicios.digitales.original=${mvn.service.provider.url.original}
service.security.principal.servicios.digitales.original=${mvn.service.security.principal.original}
service.security.credentials.servicios.digitales.original=${mvn.service.security.credentials.original}
