
package mx.gob.imss.cit.clientes.webServices.asegurado.patronesVigentes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSPatronesVigentes", targetNamespace = "http://ws.patronesvigentes.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSPatronesVigentes {


    /**
     * 
     * @param cveAsignacionNSS
     * @return
     *     returns mx.gob.imss.cit.clientes.webServices.asegurado.patronesVigentes.RespuestaPatronesVigentes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConsultaPatronesVigentes", targetNamespace = "http://ws.patronesvigentes.imss.gob.mx/", className = "mx.gob.imss.cit.clientes.webServices.asegurado.patronesVigentes.GetConsultaPatronesVigentes")
    @ResponseWrapper(localName = "getConsultaPatronesVigentesResponse", targetNamespace = "http://ws.patronesvigentes.imss.gob.mx/", className = "mx.gob.imss.cit.clientes.webServices.asegurado.patronesVigentes.GetConsultaPatronesVigentesResponse")
    public RespuestaPatronesVigentes getConsultaPatronesVigentes(
        @WebParam(name = "cveAsignacionNSS", targetNamespace = "")
        String cveAsignacionNSS);

}
