welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

############# WIZARDS #################
wizardSolicitarRissInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardSolicitarRissInit.url=wizardSolicitarRissInit
wizardSolicitarRissContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardSolicitarRissContenido.url = wizardSolicitarRissContenido

############# PORTLETS #################


############# WIDGETS #################
widgetBeneficiosInit.(class)=org.springframework.web.servlet.view.JstlView
widgetBeneficiosInit.url=/WEB-INF/views/widget/inicial.jsp
widgetBeneficiosContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetBeneficiosContenido.url=/WEB-INF/views/widget/contenido.jsp