//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.gestion.tramite;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

import mx.gob.imss.ctirss.delta.model.Usuario;
import mx.gob.imss.ctirss.delta.model.asegurado.AsignacionNSS;
import mx.gob.imss.ctirss.delta.model.asegurado.SolicitudNssCorreo;
import mx.gob.imss.ctirss.delta.model.derechohabiente.MedicoEnTurno;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Parentesco;
import mx.gob.imss.ctirss.delta.model.derechohabiente.RazonRegistro;
import mx.gob.imss.ctirss.delta.model.domicilio.Domicilio;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Fisica;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class TramiteActualizacionCorreo  extends Tramite implements Serializable{

	private static final long serialVersionUID = 1L;
	private List <SolicitudNssCorreo> correosAActualizar;
	private List <SolicitudNssCorreo> curpADesvincularCorreo;
	private Usuario usuario;
	private int origen;
	private String correoCapturado;
	private int idBoveda;
	private String nombreDocumentoBoveda;
	private Date fechaDocumento;
	
	
	public List<SolicitudNssCorreo> getCorreosAActualizar() {
		return correosAActualizar;
	}
	public void setCorreosAActualizar(List<SolicitudNssCorreo> correosAActualizar) {
		this.correosAActualizar = correosAActualizar;
	}
	public List<SolicitudNssCorreo> getCurpADesvincularCorreo() {
		return curpADesvincularCorreo;
	}
	public void setCurpADesvincularCorreo(List<SolicitudNssCorreo> curpADesvincularCorreo) {
		this.curpADesvincularCorreo = curpADesvincularCorreo;
	}
	public Usuario getUsuario() {
		return usuario;
	}
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	public int getOrigen() {
		return origen;
	}
	public void setOrigen(int origen) {
		this.origen = origen;
	}
	public String getCorreoCapturado() {
		return correoCapturado;
	}
	public void setCorreoCapturado(String correoCapturado) {
		this.correoCapturado = correoCapturado;
	}
	public int getIdBoveda() {
		return idBoveda;
	}
	public void setIdBoveda(int idBoveda) {
		this.idBoveda = idBoveda;
	}
	public String getNombreDocumentoBoveda() {
		return nombreDocumentoBoveda;
	}
	public void setNombreDocumentoBoveda(String nombreDocumentoBoveda) {
		this.nombreDocumentoBoveda = nombreDocumentoBoveda;
	}
	public Date getFechaDocumento() {
		return fechaDocumento;
	}
	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}
	
}