##### credenciales para consumir los EJBs de servicios digitales por T3#####
service.provider.url=${mvn.service.provider.url}
service.security.principal=${mvn.service.security.principal}
service.security.credentials=${mvn.service.security.credentials}

#Variables para conexion t3 con los servicios digitales
service.provider.url.original=${mvn.service.provider.url.original}
service.security.principal.original=${mvn.service.security.principal.original}
service.security.credentials.original=${mvn.service.security.credentials.original}
