package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.EstatusObraDTO;

/**
 * RocTipoObra generated by hbm2java
 */
@Entity
@Table(name = "ROC_ESTATUS_OBRA", schema = "MGPROC01")
@Transactional
public class RocEstatusObra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4943022634302990066L;
	
	private Long cveEstatusObra;
	private String desEstatusObra;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;


	public RocEstatusObra() {
	}

	public RocEstatusObra(Long cveEstatusObra) {
		this.cveEstatusObra = cveEstatusObra;
	}

	public RocEstatusObra(Long cveEstatusObra, String desEstatusObra, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveEstatusObra = cveEstatusObra;
		this.desEstatusObra = desEstatusObra;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id

	@Column(name = "CVE_ID_ESTATUS_OBRA", unique = true, nullable = false)
	public Long getCveEstatusObra() {
		return this.cveEstatusObra;
	}

	public void setCveEstatusObra(Long cveEstatusObra) {
		this.cveEstatusObra = cveEstatusObra;
	}

	@Column(name = "DES_ESTATUS_OBRA", length = 80)
	public String getDesEstatusObra() {
		return this.desEstatusObra;
	}

	public void setDesEstatusObra(String desEstatusObra) {
		this.desEstatusObra = desEstatusObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	public EstatusObraDTO toConvertTipoObraDTO(){
		EstatusObraDTO estatusObraDTO = new EstatusObraDTO();
		
		estatusObraDTO.setCveEstatusObra(this.getCveEstatusObra());
		estatusObraDTO.setDesEstatusObra(this.getDesEstatusObra());
		
		return estatusObraDTO;
	}

}
