package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.InformacionIncidenciaDTO;

/**
 * RotInformacionIncidencia generated by hbm2java
 */
@Entity
@Table(name = "ROT_INFORMACION_INCIDENCIA")
@Transactional
public class RotInformacionIncidencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9148318273946322184L;
	
	private Long cveInformacionIncidencia;
	private Long cveInformacionObra;
	private RocMotivoIncidencia rocMotivoTipoIncidencia;
	private RocCalendarioReporte rocCalendarioReporte;	
	private RocTipoRegistro rocTipoRegistro;
	private Date stpRegIncidencia;
	private Date fecFinObra;
	private Date fecCanObra;
	private Date fecSuspencion;
	private Date fecReanudacion;
	private Date fecActualizacion;
	private Double impObra;
	private Double refSupConstruccion;
	private Double impEjercido;
	private String refMotivoAct;
	private String refAcuseInc;
	private Integer numAnio;
	private Long cveIdTramite;
	private String secNotaria;
	private Date fecRegistroAlta;
	private Date fecRegistroBaja;
	
	
	public RotInformacionIncidencia() {
	}

	public RotInformacionIncidencia(Long cveInformacionIncidencia, RocMotivoIncidencia rocMotivoTipoIncidencia,
			RocCalendarioReporte rocCalendarioReporte, RocTipoRegistro rocTipoRegistro) {
		
		this.cveInformacionIncidencia = cveInformacionIncidencia;
		this.rocMotivoTipoIncidencia = rocMotivoTipoIncidencia;
		this.rocTipoRegistro = rocTipoRegistro;
		this.rocCalendarioReporte = rocCalendarioReporte;
		
	}

	public RotInformacionIncidencia(Long cveInformacionIncidencia, RocMotivoIncidencia rocMotivoTipoIncidencia,
	RocCalendarioReporte rocCalendarioReporte, RocTipoRegistro rocTipoRegistro, Date stpRegIncidencia,
	Date fecFinObra,Date fecCanObra, Date fecSuspencion, Date fecReanudacion, Date fecActualizacion,
	Double impObra, Double refSupConstruccion, Double impEjercido, String refMotivoAct,
	String refAcuseInc,Integer numAnio, Long cveIdTramite,String secNotaria,Date fecRegistroAlta) {

		this.cveInformacionIncidencia = cveInformacionIncidencia;
		this.rocMotivoTipoIncidencia = rocMotivoTipoIncidencia;
		this.rocCalendarioReporte = rocCalendarioReporte;
		this.rocTipoRegistro = rocTipoRegistro;
		this.stpRegIncidencia = stpRegIncidencia;
		this.fecFinObra = fecFinObra;
		this.fecCanObra = fecCanObra;
		this.impObra = impObra;
		this.refSupConstruccion = refSupConstruccion;
		this.impEjercido = impEjercido;
		this.refMotivoAct = refMotivoAct;
		this.refAcuseInc = refAcuseInc;
		this.fecSuspencion = fecSuspencion;
		this.fecReanudacion = fecReanudacion;
		this.fecActualizacion = fecActualizacion;
		this.numAnio = numAnio;
		this.cveIdTramite = cveIdTramite;
		this.secNotaria = secNotaria;
		this.fecRegistroAlta =  fecRegistroAlta;
	}

	@Id
	@Column(name = "CVE_ID_INFORMACION_INCIDENCIA", unique = true, nullable = false)	
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_informacion_incidencia")
	@SequenceGenerator(name="seq_informacion_incidencia", sequenceName="SEQ_ROTINFORMACIONINCIDENCIA", allocationSize=1)	
	public Long getCveInformacionIncidencia() {
		return this.cveInformacionIncidencia;
	}

	public void setCveInformacionIncidencia(Long cveInformacionIncidencia) {
		this.cveInformacionIncidencia = cveInformacionIncidencia;
	}

	@Column(name = "CVE_ID_INFORMACION_OBRA", unique = true, nullable = false)
	public Long getCveInformacionObra() {
		return this.cveInformacionObra;
	}

	public void setCveInformacionObra(Long cveInformacionObra) {
		this.cveInformacionObra = cveInformacionObra;
	}	

	
	@ManyToOne(fetch = FetchType.EAGER,targetEntity=RocMotivoIncidencia.class)
	@JoinColumn(name = "CVE_ID_MOTIVO_INCIDENCIA", nullable = false)	
	public RocMotivoIncidencia getRocMotivoTipoIncidencia() {
		return this.rocMotivoTipoIncidencia;
	}

	public void setRocMotivoTipoIncidencia(RocMotivoIncidencia rocMotivoTipoIncidencia) {
		this.rocMotivoTipoIncidencia = rocMotivoTipoIncidencia;
	}

	@ManyToOne(fetch = FetchType.EAGER, optional= true)
	@JoinColumn(name = "CVE_ID_CALENDARIO_REP", nullable = false)
	public RocCalendarioReporte getRocCalendarioReporte() {
		return this.rocCalendarioReporte;
	}

	public void setRocCalendarioReporte(RocCalendarioReporte rocCalendarioReporte) {
		this.rocCalendarioReporte = rocCalendarioReporte;
	}	
	
	@ManyToOne(fetch = FetchType.EAGER,targetEntity=RocTipoRegistro.class)
	@JoinColumn(name = "CVE_ID_TIPO_REGISTRO")
	public RocTipoRegistro getRocTipoRegistro() {
		return this.rocTipoRegistro;
	}

	public void setRocTipoRegistro(RocTipoRegistro rocTipoRegistro) {
		this.rocTipoRegistro = rocTipoRegistro;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STP_REG_INCIDENCIA")
	public Date getStpRegIncidencia() {
		return this.stpRegIncidencia;
	}

	public void setStpRegIncidencia(Date stpRegIncidencia) {
		this.stpRegIncidencia = stpRegIncidencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_OBRA")
	public Date getFecFinObra() {
		return this.fecFinObra;
	}

	public void setFecFinObra(Date fecFinObra) {
		this.fecFinObra = fecFinObra;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_CAN_OBRA")
	public Date getFecCanObra() {
		return this.fecCanObra;
	}

	public void setFecCanObra(Date fecCanObra) {
		this.fecCanObra = fecCanObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_SUSPENSION")
	public Date getFecSuspencion() {
		return fecSuspencion;
	}

	public void setFecSuspencion(Date fecSuspencion) {
		this.fecSuspencion = fecSuspencion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REANUDACION")
	public Date getFecReanudacion() {
		return fecReanudacion;
	}

	public void setFecReanudacion(Date fecReanudacion) {
		this.fecReanudacion = fecReanudacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ACTUALIZACION")
	public Date getFecActualizacion() {
		return fecActualizacion;
	}

	public void setFecActualizacion(Date fecActualizacion) {
		this.fecActualizacion = fecActualizacion;
	}

	@Column(name = "IMP_OBRA", precision = 17, scale = 17)
	public Double getImpObra() {
		return this.impObra;
	}

	public void setImpObra(Double impObra) {
		this.impObra = impObra;
	}

	@Column(name = "REF_SUP_CONSTRUCCION")
	public Double getRefSupConstruccion() {
		return this.refSupConstruccion;
	}

	public void setRefSupConstruccion(Double refSupConstruccion) {
		this.refSupConstruccion = refSupConstruccion;
	}

	@Column(name = "IMP_EJERCIDO", precision = 17, scale = 17)
	public Double getImpEjercido() {
		return this.impEjercido;
	}

	public void setImpEjercido(Double impEjercido) {
		this.impEjercido = impEjercido;
	}

//	@Column(name = "ref_motivo_act", length = 80)
//	public String getRefMotivoAct() {
//		return this.refMotivoAct;
//	}
//
//	public void setRefMotivoAct(String refMotivoAct) {
//		this.refMotivoAct = refMotivoAct;
//	}

	@Column(name = "REF_ACUSE_INC")
	public String getRefAcuseInc() {
		return this.refAcuseInc;
	}

	public void setRefAcuseInc(String refAcuseInc) {
		this.refAcuseInc = refAcuseInc;
	}
	
	@Column(name = "NUM_ANIO")
	public Integer getNumAnio() {
		return this.numAnio;
	}

	public void setNumAnio(Integer numAnio) {
		this.numAnio = numAnio;
	}
	
	@Column(name = "CVE_ID_TRAMITE")
	public Long getCveIdTramite() {
		return cveIdTramite;
	}

	public void setCveIdTramite(Long cveIdTramite) {
		this.cveIdTramite = cveIdTramite;
	}

	@Column(name ="NUM_SEQ_NOTARIA")
	public String getSecNotaria() {
		return secNotaria;
	}

	public void setSecNotaria(String secNotaria) {
		this.secNotaria = secNotaria;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column( name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column( name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	public InformacionIncidenciaDTO toConvertInformacionIncidenciaDTO(){
		InformacionIncidenciaDTO informacionIncidenciaDTO = new InformacionIncidenciaDTO();
		
		informacionIncidenciaDTO.setCveInformacionIncidencia(this.getCveInformacionIncidencia());
		informacionIncidenciaDTO.setCveInformacionObra(this.getCveInformacionObra());
		informacionIncidenciaDTO.setFecActualizacion(this.getFecActualizacion());
		informacionIncidenciaDTO.setFecCanObra(this.getFecCanObra());
		informacionIncidenciaDTO.setFecFinObra(this.getFecFinObra());
		informacionIncidenciaDTO.setFecReanudacion(this.getFecReanudacion());
		informacionIncidenciaDTO.setFecSuspencion(this.getFecSuspencion());
		informacionIncidenciaDTO.setImpEjercido(this.getImpEjercido());
		informacionIncidenciaDTO.setImpObra(this.getImpObra());
		informacionIncidenciaDTO.setMotivoTipoIncidenciaDTO(this.getRocMotivoTipoIncidencia().toConvertMotivoTipoIncidenciaDTO());
		informacionIncidenciaDTO.setRefAcuseInc(this.getRefAcuseInc());
		informacionIncidenciaDTO.setRefSupConstruccion(this.getRefSupConstruccion());
		informacionIncidenciaDTO.setStpRegIncidencia(this.getStpRegIncidencia());
		informacionIncidenciaDTO.setTipoRegistroDTO(this.getRocTipoRegistro().toConvertTipoRegistroDTO());
		informacionIncidenciaDTO.setNumAnio(this.getNumAnio());
		if(this.getRocCalendarioReporte() != null)
			informacionIncidenciaDTO.setCalendarioReporteDTO(this.getRocCalendarioReporte().toConvertCalendarioReporteDTO());
		
		informacionIncidenciaDTO.setCveIdTramite(this.getCveIdTramite());
		informacionIncidenciaDTO.setNumSeqNotaria(this.getSecNotaria());
		
		return informacionIncidenciaDTO;
	}

}
