/**
 * 
 */
package mx.gob.imss.ctirss.delta.model.enums;

import java.util.HashMap;
import java.util.Map;

/**
 *  
 *  @Cliente: Instituto Mexicano del Seguro Social
 *  @Autor: Hugo Armando Mart-nez Cham-nica
 *  @Proyecto: delta
 *  @Archivo: TipoTramiteEnum.java
 *  @Paquete: mx.gob.imss.ctirss.delta.model.gestion.patronal
 *  @Fecha: 11:27:47
 */
public enum TipoTramiteEnum {
	DEFAULT(0),
	REGISTRO_PERSONA(1),
	ACTUALIZACION_DATOS_GENERALES(2),
	REGISTRO_DERECHOHABIENTE(23),
	REGISTRO_ASEGURADO(44),
	REGISTRO_PENSIONADO(45),
	REGISTRO_CONCUBINA_RIO(46),
	REGISTRO_CONYUGE(47),
	REGISTRO_HIJOS(48),
	REGISTRO_PADRES(49),
	REGISTRO_DH_CAMBIO_UMF(1002),
	REGISTRO_DH_CAMBIO_CIRCUNSCRIPCION(1003),
	MODIFICACION(24),
	CORRECCION_DATOS(24),
	BAJA_DEFUNCION(25),
	BAJA_CONCUBINATO(26),
	BAJA_DIVORCIO(27),
	BAJA_CONVIVENCIA(28),
	PRORROGA_ESTUDIOS(29),
	PRORROGA_ACUERDOS(33),
	PRORROGA_LAUDOS(35),
	PRORROGA_VIGENCIA_PERMANENTE(31),
	PRORROGA_VIGENCIA_TEMPORAL(32),
	PRORROGA_OBSTETRICOS(34),
	PRORROGA_ENFERMEDAD(30),
	CAMBIO_CLINICA(36),
	CAMBIO_CONSULTORIO_TURNO(37),
	AUTORIZACION_CIRCUNSCRIPCION(38),
	SUSPENSION_CIRCUNSCRIPCION(39),
	CAMBIO_CLINICA_MASIVO(62),
	ASIGNAR_CONSULTORIO_TURNO_MEDICO(41),
	ACTUALIZACION_DENOMINACION_SOCIAL(17),
	ACTUALIZACION_DATOS_CONTACTO(18),
	ACTUALIZACION_REGISTRO_SINDICATO(19),
	ACTUALIZACION_ESCRITURA_CONSTITUTIVA(20),
	CLASIFICACION_D(21),
	CLASIFICACION_E(22),
	CLASIFICACION_F(23),
//	CLASIFICACION_G(24),
//	CLASIFICACION_H(25),
//	CLASIFICACION_I(26),
	CLASIFICACION_J(24),
	CLASIFICACION_K(25),
	CLASIFICACION_L(26),
	CLASIFICACION_M(27),
	CLASIFICACION_N(28),
	CLASIFICACION_P(33),
	CLASIFICACION_Q(34),
	CLASIFICACION_R(35),
	ACTUALIZACION_SOCIO(36),
	ACTUALIZACION_REPRESENTANTE_LEGAL(37),
	ACTUALIZACION_CENTRO_TRABAJO(48),
	CAMBIO_MEDICO_POR_CONYUGE(68),
	CAMBIO_MEDICO_POR_ASEGURADO(69),
	CAMBIO_MEDICO_CIRCUNSCRIPCION_CONYUGE(70),
	CAMBIO_MEDICO_CAMBIO_CLINICA_ASEGURADO(71),
	CAMBIO_MEDICO_CAMBIO_CLINICA_CONYUGE(72),
	CAMBIO_CLINICA_POR_CAMBIO_CLINICA_ASEGURADO(73),
	CORRECCION_PATRONAL_CORP01(97),
	PRESENTACION_CORRECCION_PATRONAL_CORP02(98),
	PRORROGA_CORRECCION_PATRONAL_CORP03(99),
	IMPRESION_COMPROBANTE_FISCAL_CFDI(100),
	SOLICITUD_DE_PENSION_POR_CESANTIA(104),
	SOLICITUD_DE_PENSION_POR_VEJEZ(105),
	SOLICITUD_DE_PENSION_POR_RETIRO_ANTICIPADO(106),
	SOLICITUD_DE_PENSION_POR_INCAPACIDAD_PERMANENTE_PARCIAL(107),
	SOLICITUD_DE_PENSION_POR_INCAPACIDAD_PERMANENTE_TOTAL(108),
	SOLICITUD_DE_INDEMNIZACION_GLOBAL(109),
	SOLICITUD_DE_PENSION_INVALIDEZ(110),
	SOLICITUD_DE_PENSION_DE_ASCENDIENTES(111),
	SOLICITUD_DE_PENSION_DE_VIUDEZ(112),
	SOLICITUD_DE_PENSION_DE_ORFANDAD(113),
	SOLICITUD_DE_PENSION_DE_VIUDEZ_ORFANDAD(114),
	CERTIFICACION_RETIRO_DESEMPLEO(115),
	CARTA_NO_ADEUDO(116),
	COMPRA_SEGURO_INDIVIDUAL(118),
	RENOVACION_SEGURO_INDIVIDUAL(119),
	COMPRA_SEGURO_DOMESTICO(121),
    RENOVACION_SEGURO_DOMESTICO(122),
    INACTIVIDAD_PAGO_PARCIALIDADES(123),
    COMPRA_SEGURO_FAMILIAR(124),
    COMPRA_CONTINUACION_VOLUNTARIA(125),
	CONSULTA_RIESGOS_TRABAJO_TERMINADOS(138),
	CORRECCION_DATOS_ASEGURADO(139),
	PAGOS_SUA(142),
	MOVIMIENTOS_AFILIATORIOS(143),
	RENOVACION_SEGURO_FAMILIAR(144),
	RENOVACION_CONTINUACION_VOLUNTARIA(145),
	ACEPTACION_TERMINOS_CONDICIONES(146),
	REGISTRO_EMBARAZADA_SPPM (147),
	REGISTRO_CITA_SPPM (148),
	COMPARA_TUS_DATOS(149),        
	CORRECCION_DE_NOMBRE(162),
	CORRECCION_DE_DATOS_ESTADISTICOS(162),
	CANCELADO_POR_DUPLICIDAD(60),
	CORRESPONDE_A_UN_HOMONIMO(164),
	CORRESPONDE_A_OTRO_ASEGURADO(166),
	NO_EXISTE_EN_CANASE(163),
	SOLICITUD_BLOQUEO_DERECHOS_ARCO(170),
	SOLICITUD_DESBLOQUEO_DERECHOS_ARCO(171),
	REGISTRO_PERSONA_UNION_CIVIL(178),
	BAJA_DE_DERECHOHABIENTE_POR_TERMINO_DE_UNION_CIVIL(179), 
	ACTUALIZACION_CORREO_ELECTRONICO (177),
	PORTABILIDAD_ISSSTE_IMSS(180),
	APLICAR_BENEFICIOS_CCT_74(181),
	ELIMINAR_BENEFICIOS_CCT_74(182);
	
	
	
	private Integer codigo;
		
	private final static Map<String, TipoTramiteEnum> hashNames = new HashMap<String, TipoTramiteEnum>();
	private final static Map<Integer,TipoTramiteEnum> hashCodes = new HashMap<Integer,TipoTramiteEnum>();
	
	static{ 
		for(TipoTramiteEnum tramite : TipoTramiteEnum.values()){
			hashNames.put(tramite.name(), tramite);
			hashCodes.put(tramite.getCodigo(), tramite);
		}
	}
	
	private TipoTramiteEnum(Integer valor){
		this.codigo=valor;
		
	}
	
	public Integer getCodigo() {
		return codigo;
	}
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	
	public static TipoTramiteEnum obtenerEnumByName(String name){
		return hashNames.get(name);
	}
	
	public static TipoTramiteEnum obternerEnumById(Integer codigo){
		return hashCodes.get(codigo);
	}
}
