##################
# FTP FileConfig #
##################
filesystem.ivro.output.url=ftp_test/ivro/output

################
# Servidor ftp #
################
ftp.server.url=11.254.13.4
ftp.server.user=pruebas
ftp.server.passwd=pruebas
ftp.server.port=21

application.mode=test


##################
# Ruta de origen #
##################
file.ivro.input.url=/daemonTest/ivro
file.ivro.input.tmp.url=/daemonTest/ivro_temp


####################
# Ruta de respaldo #
####################
file.ivro.resp.url=/daemonTest/ivro_hist


########################
# Ruta de verificacion #
########################
file.ivro.verif.url=/daemonTest/ivro_temp/checksum
file.ivro.verif.time=1000
file.ivro.verif.retry=3


############################
# Ruta de FTP (Filesystem) #
############################
filesystem.ftp.base.output.url=/daemonTest/ftp/base


#################
# Archivos IVRO #
#################

sindo.file.ciz01=AYPENT_CIZ01.txt
sindo.file.ciz02=AYPENT_CIZ02.txt
sindo.file.ciz03=AYPENT_CIZ03.txt


##########################
# Archivos de validacion #
##########################

filesystem.delta.proceso.estatus=/daemonTest/bloq
