
package mx.gob.imss.cit.ws.externo.boveda.docuemntal.v3.consulta.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bovedaPort", targetNamespace = "http://www.imss.gob.mx/boveda/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BovedaPort {


    /**
     * 
     * @param getEstatusDocRequest
     * @return
     *     returns mx.gob.imss.cit.ws.externo.boveda.docuemntal.v3.consulta.schema.GetEstatusDocResponse
     */
    @WebMethod
    @WebResult(name = "getEstatusDocResponse", targetNamespace = "http://www.imss.gob.mx/boveda/ws", partName = "getEstatusDocResponse")
    public GetEstatusDocResponse getEstatusDoc(
        @WebParam(name = "getEstatusDocRequest", targetNamespace = "http://www.imss.gob.mx/boveda/ws", partName = "getEstatusDocRequest")
        GetEstatusDocRequest getEstatusDocRequest);

}
