#CONFIGURACIONES

boveda.documento.wsdl=${mvn.boveda.webservice.url}/ServiceProxyDocumentoWS?wsdl
boveda.carpeta.wsdl=${mvn.boveda.webservice.url}/ServiceProxyCarpetaWS?wsdl
boveda.documento.wsdl.v2=${mvn.boveda.webservice.url.v2}/CDAProxy?wsdl
common.connect.timeout=30000
common.request.timeout=30000