#CONFIGURACIONES IVRO SEGURO DOMESTICO Y SEGURO PERSONAL
ruta_logo_imss = /images/IMSS.png
ruta_reportes = /cuestionarios/

reporte_cuest_main=reportMain.jasper
#reporte_cuest_ivro = ReporteIvroCuestionario.jasper
#sub_reporte_cuest_ivro = ReporteIvroCuestionario_subreport1.jasper
#sub_reporte2_cuest_ivro = ReporteIvroCuestionario_subreport2.jasper
reporte_cuest_ivro = ReporteIvroCuestionarioV1.jasper
sub_reporte_cuest_ivro = ReporteIvroCuestionarioV2.jasper
sub_reporte2_cuest_ivro = ReporteIvroCuestionarioV3.jasper
