
package mx.gob.imss.cit.ws.cuentaindividual.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSNssCuentaIndividual", targetNamespace = "http://cuentaIndividual.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSNssCuentaIndividual {


    /**
     * 
     * @param nss
     * @return
     *     returns mx.gob.imss.cit.ws.cuentaindividual.cliente.RespuestaCuentaIndividual
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCuentaIndividual", targetNamespace = "http://cuentaIndividual.imss.gob.mx/", className = "mx.gob.imss.cit.ws.cuentaindividual.cliente.GetCuentaIndividual")
    @ResponseWrapper(localName = "getCuentaIndividualResponse", targetNamespace = "http://cuentaIndividual.imss.gob.mx/", className = "mx.gob.imss.cit.ws.cuentaindividual.cliente.GetCuentaIndividualResponse")
    public RespuestaCuentaIndividual getCuentaIndividual(
        @WebParam(name = "nss", targetNamespace = "")
        String nss);

}
