<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>mx.gob.imss.ctirss.delta.gestion.clasificacion</groupId>
	<artifactId>gestionClasificacion-modelo</artifactId>
	<version>2.4-SNAPSHOT</version>
	<name>Modulo de Persistencia Modelo DELTA</name>
	<url>http://maven.apache.org</url>
	<packaging>jar</packaging>


	 <parent>
                <artifactId>gestionClasificacion</artifactId>
                <groupId>mx.gob.imss.ctirss.delta.gestion.clasificacion</groupId>
                <version>2.4-SNAPSHOT</version>
     </parent>

	<properties>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		 <org.hibernate.version>3.6.9.Final</org.hibernate.version>
		 <org.springframework.version>3.0.5.RELEASE</org.springframework.version>
	</properties>


<dependencies>


	<!-- INICIO DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->

		<!-- Dependencia del Framework DELTA BASE IMSS -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-framework-base</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
		</dependency>
		
		<!-- Dependencia del Proyecto de Objetos de modelo DELTA IMSS -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
		</dependency>
		<!-- FIN DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->


<!-- 		<dependency> -->
<!-- 			<groupId>org.hibernate</groupId> -->
<!-- 			<artifactId>hibernate-entitymanager</artifactId> -->
<!-- 			<version>${org.hibernate.version}</version> -->
<!-- 			<scope>provided</scope> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.hibernate</groupId> -->
<!-- 			<artifactId>hibernate-core</artifactId> -->
<!-- 			<version>${org.hibernate.version}</version> -->
<!-- 			<scope>provided</scope> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.hibernate.javax.persistence</groupId> -->
<!-- 			<artifactId>hibernate-jpa-2.0-api</artifactId> -->
<!-- 			<version>1.0.1.Final</version> -->
<!-- 			<scope>provided</scope> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.hibernate</groupId> -->
<!-- 			<artifactId>hibernate-commons-annotations</artifactId> -->
<!-- 			<version>3.2.0.Final</version> -->
<!-- 			<scope>provided</scope> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>javax.xml.bind</groupId> -->
<!-- 			<artifactId>jaxb-api</artifactId> -->
<!-- 			<version>2.1</version> -->
<!-- 			<scope>provided</scope> -->
<!-- 		</dependency> -->
		
		<!-- Spring -->
		
<!-- 		<dependency> -->
<!-- 			<groupId>org.springframework</groupId> -->
<!-- 			<artifactId>spring-webmvc</artifactId> -->
<!-- 			<version>${org.springframework.version}</version> -->
<!-- 		</dependency> -->
		
		<!-- Jackson JSON Mapper -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.codehaus.jackson</groupId> -->
<!-- 			<artifactId>jackson-mapper-asl</artifactId> -->
<!-- 			<version>1.6.4</version> -->
<!-- 		</dependency> -->
		
		
	</dependencies>
	
	
		
</project>
