//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.asegurado;

import java.io.Serializable;
import java.util.Date;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.SujetoObligado;

public class Asegurado extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected SujetoObligado sujetoObligado;
	protected AsignacionNSS asignacionNSS;
	protected Long idAsegurado;
	protected Date fechaBaja;
	protected Date fechaAlta;
	protected boolean autorizacionPermanente;

	
	/**
	 * @return the sujetoObligado
	 */
	public SujetoObligado getSujetoObligado() {
		return sujetoObligado;
	}

	/**
	 * @param sujetoObligado the sujetoObligado to set
	 */
	public void setSujetoObligado(SujetoObligado sujetoObligado) {
		this.sujetoObligado = sujetoObligado;
	}

	/**
	 * Gets the value of the asignacionNSS property.
	 * 
	 * @return possible object is {@link AsignacionNSS }
	 * 
	 */
	public AsignacionNSS getAsignacionNSS() {
		return asignacionNSS;
	}

	/**
	 * Sets the value of the asignacionNSS property.
	 * 
	 * @param value
	 *            allowed object is {@link AsignacionNSS }
	 * 
	 */
	public void setAsignacionNSS(AsignacionNSS value) {
		this.asignacionNSS = value;
	}

	
	/**
	 * @return the idAsegurado
	 */
	public Long getIdAsegurado() {
		return idAsegurado;
	}

	/**
	 * @param idAsegurado the idAsegurado to set
	 */
	public void setIdAsegurado(Long idAsegurado) {
		this.idAsegurado = idAsegurado;
	}

	/**
	 * Gets the value of the fechaBaja property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getFechaBaja() {
		return fechaBaja;
	}

	/**
	 * Sets the value of the fechaBaja property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setFechaBaja(Date value) {
		this.fechaBaja = value;
	}

	/**
	 * Gets the value of the fechaAlta property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getFechaAlta() {
		return fechaAlta;
	}

	/**
	 * Sets the value of the fechaAlta property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setFechaAlta(Date value) {
		this.fechaAlta = value;
	}

	/**
	 * @return the autorizacionPermanente
	 */
	public boolean isAutorizacionPermanente() {
		return autorizacionPermanente;
	}

	/**
	 * @param autorizacionPermanente the autorizacionPermanente to set
	 */
	public void setAutorizacionPermanente(boolean autorizacionPermanente) {
		this.autorizacionPermanente = autorizacionPermanente;
	}

}
