#archivo donde se ubican los opciones del portal ciudadano
url_archivo = file:C:/deltaResources/opciones.properties
#indicador para saber si las opciones se tomaran del properties
opciones_por_properties = 1