
package mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.carpetaws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AddFolderActorRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AddFolderActorResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.CreateFolderRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.CreateFolderResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.FolderDescendantsRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.FolderDescendantsResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.FolderDocumentsRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.FolderDocumentsResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.FolderObjectsRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.FolderObjectsResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.UserFolderRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.UserFolderResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICarpetaWSService", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.bovedapersonalcommonschema.ObjectFactory.class,
    mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.ObjectFactory.class,
    mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.carpetaws.ObjectFactory.class,
    mx.gob.imss.cit.clienteServiciosComunes.ws.commonschema.ObjectFactory.class
})
public interface ICarpetaWSService {


    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.CreateFolderResponse
     */
    @WebMethod
    @WebResult(name = "createFolderResponse", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
    public CreateFolderResponse createFolder(
        @WebParam(name = "createFolderRequest", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
        CreateFolderRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.FolderDocumentsResponse
     */
    @WebMethod
    @WebResult(name = "getFolderDocumentsResponse", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
    public FolderDocumentsResponse getFolderDocuments(
        @WebParam(name = "getFolderDocumentsRequest", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
        FolderDocumentsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.FolderObjectsResponse
     */
    @WebMethod
    @WebResult(name = "getFolderObjectsResponse", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
    public FolderObjectsResponse getFolderObjects(
        @WebParam(name = "getFolderObjectsRequest", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
        FolderObjectsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.FolderDescendantsResponse
     */
    @WebMethod
    @WebResult(name = "getFolderDescendantsResponse", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
    public FolderDescendantsResponse getFolderDescendants(
        @WebParam(name = "getFolderDescendantsRequest", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
        FolderDescendantsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.UserFolderResponse
     */
    @WebMethod
    @WebResult(name = "getUserFolderResponse", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
    public UserFolderResponse getUserFolder(
        @WebParam(name = "getUserFolderRequest", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
        UserFolderRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AddFolderActorResponse
     */
    @WebMethod
    @WebResult(name = "addFolderActorResponse", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
    public AddFolderActorResponse addFolderActor(
        @WebParam(name = "addFolderActorRequest", targetNamespace = "http://carpetaws.ws.bp.cit.imss.gob.mx/", partName = "body")
        AddFolderActorRequest body);

}
