package  mx.gob.imss.ctirss.delta.persistence;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.gob.imss.ctirss.delta.framework.annotations.ComponentComboCampoDescripcion;
import mx.gob.imss.ctirss.delta.framework.annotations.OnSearchLlavePrimaria;


/**
 * DgCatMunicipio generated by hbm2java
 */
@Entity
@Table(name="DG_CAT_MUNICIPIO")

@OnSearchLlavePrimaria(atributos="id.cveMun")
@ComponentComboCampoDescripcion(atributo="nomMun")
public  class DgCatMunicipio implements Serializable {
	
	/**
	 * Serial
	 */
	private static final long serialVersionUID = -3817479916974951948L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cveMun", column = @Column(name = "CVE_MUN", nullable = false, length = 3)),
			@AttributeOverride(name = "cveEnt", column = @Column(name = "CVE_ENT", nullable = false, length = 2)) })
	private DgCatMunicipioPK id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_ENT", nullable = false, insertable = false, updatable = false)
	private DgCatEstado dgCatEstado;
	
	@Column(name = "NOM_MUN", nullable = false, length = 50)
	private String nomMun;
	
	
	//bi-directional many-to-one association to DitMunicipioImssInegi
	@OneToMany(mappedBy="dgCatMunicipio")
	private Set<DitMunicipioImssInegi> ditMunicipioImssInegis;
	
	public DgCatMunicipio() {
		this.id = new DgCatMunicipioPK();
	/*	this.dgCatEstado =  new DgCatEstado();
		*/
	}

	public DgCatMunicipio(DgCatMunicipioPK id, DgCatEstado dgCatEstado,
			String nomMun) {
		this.id = id;
		this.dgCatEstado = dgCatEstado;
		this.nomMun = nomMun;
	}

	
	
	public DgCatMunicipioPK getId() {
		return this.id;
	}

	public void setId(DgCatMunicipioPK id) {
		this.id = id;
	}

	
	public DgCatEstado getDgCatEstado() {
		return this.dgCatEstado;
	}

	public void setDgCatEstado(DgCatEstado dgCatEstado) {
		this.dgCatEstado = dgCatEstado;
	}

	
	public String getNomMun() {
		return this.nomMun;
	}

	public void setNomMun(String nomMun) {
		this.nomMun = nomMun;
	}

	/**
	 * @return the ditMunicipioImssInegis
	 */
	public Set<DitMunicipioImssInegi> getDitMunicipioImssInegis() {
		return ditMunicipioImssInegis;
	}

	/**
	 * @param ditMunicipioImssInegis the ditMunicipioImssInegis to set
	 */
	public void setDitMunicipioImssInegis(
			Set<DitMunicipioImssInegi> ditMunicipioImssInegis) {
		this.ditMunicipioImssInegis = ditMunicipioImssInegis;
	}



}