<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>AdmonUsuariosDelta</artifactId>
		<groupId>mx.gob.imss.ctirss.sso</groupId>
		<version>1.1-SNAPSHOT</version>
	</parent>

	<groupId>mx.gob.imss.ctirss.sso</groupId>
	<artifactId>Sauimssdigital</artifactId>
	<packaging>war</packaging>
	<version>1.1-SNAPSHOT</version>

	<name>Administracion de Usuarios Delta WEB</name>
	<url>http://maven.apache.org</url>


  
	<dependencies>
		<dependency>
			<groupId>mx.gob.imss.ctirss.sso</groupId>
			<artifactId>AdmonUsuariosDelta-remote</artifactId>
			<version>1.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.sso</groupId>
			<artifactId>AdmonUsuariosDelta-ejb</artifactId>
			<version>1.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.sso</groupId>
			<artifactId>AdmonUsuariosDelta-cliente</artifactId>
			<version>1.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.sun.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>${jsf.version}</version>
		</dependency>
		<dependency>
			<groupId>com.sun.faces</groupId>
			<artifactId>jsf-impl</artifactId>
			<version>${jsf.version}</version>
		</dependency>
		<dependency>
			<groupId>javaee</groupId>
			<artifactId>javaee-api</artifactId>
			<version>5</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.icefaces</groupId>
			<artifactId>icefaces</artifactId>
			<version>${ice.version}</version>
		</dependency>
		<dependency>
			<groupId>org.icefaces</groupId>
			<artifactId>icefaces-ace</artifactId>
			<version>${ice.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.1.1</version>
		</dependency>
	    <dependency>
             <groupId>imss_dev_frmwrk-lib</groupId>
             <artifactId>imss_dev_frmwrk</artifactId>
             <version>1</version>
    	</dependency>
    	<dependency>
             <groupId>userAdminServices-lib</groupId>
             <artifactId>userAdminServices</artifactId>
             <version>1</version>
    	</dependency>


		<dependency>
			<groupId>jcaptcha</groupId>
			<artifactId>filters</artifactId>
			<version>2.0.235</version>
		</dependency>    	

		<dependency>
			<groupId>jcaptcha</groupId>
			<artifactId>jcaptcha</artifactId>
			<version>2.0-alpha-1-SNAPSHOT</version>
		</dependency>    	

		<dependency>
			<groupId>jcaptcha</groupId>
			<artifactId>jcaptcha-api</artifactId>
			<version>1.0</version>
		</dependency>    	

		<dependency>
			<groupId>jcaptcha</groupId>
			<artifactId>jcaptcha-integration-simple-servlet</artifactId>
			<version>2.0-alpha-1-SNAPSHOT</version>
		</dependency>    	


    	<!-- Cliente de Webservices. RENAPO consulta de CURP -->
        <!-- 
         <dependency>
           <groupId>mx.gob.imss.ctirss.clienteswebservices.renapo.curp</groupId>
           <artifactId>ClientesWebservices-renapo-curp</artifactId>
           <version>1.2-SNAPSHOT</version>
        </dependency>
        --> 
         <!-- Cliente de Webservices. RENAPO consulta de CURP  en Kio-->

		<!--<dependency>
			<groupId>mx.gob.imss.ctirss.clienteswebservices.renapo.curp</groupId>
			<artifactId>ClientesWebservices-renapo-curp</artifactId>
			<version>${mvn.version.clienteswebservices.renapo.curp}</version>
		</dependency>-->

		<!-- Nuevo Cliente Webservice RENAPO consulta de CURP -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.sso</groupId>
			<artifactId>AdmonUsuariosDelta-renapo</artifactId>
			<version>1.1-SNAPSHOT</version>
		</dependency>

         
        
        <!-- Dependencia del Proyecto Base DELTA - Modelo Negocio -->
		 <dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>1.6-SNAPSHOT</version>		
		</dependency>
		
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-framework-base</artifactId>
			<version>2.6-SNAPSHOT</version>		
		</dependency>
         
         <dependency> 
		    <groupId>log4j</groupId> 
		    <artifactId>log4j</artifactId> 
		    <version>1.2.16</version> 
	     </dependency>
	     
<!-- 	     Se sustituye por el nuevo cliente en AdmonUsuariosDelta-cliente -->
<!-- 	     <dependency>  -->
<!-- 		    <groupId>usuarioimss-lib</groupId>  -->
<!-- 		    <artifactId>usuarioimss</artifactId>  -->
<!-- 		    <version>1.0</version>  -->
<!-- 	     </dependency>  -->
	     
	    <!-- Libs del servicio web -->
	     <dependency> 
		    <groupId>axis-lib</groupId> 
		    <artifactId>axis</artifactId> 
		    <version>1.0</version> 
	     </dependency> 
	     
	      <dependency> 
		    <groupId>commons-discovery-0.2-lib</groupId> 
		    <artifactId>commons-discovery-0.2</artifactId> 
		    <version>1.0</version> 
	     </dependency> 
	     
	      <dependency> 
		    <groupId>javax.wsdl_1.6.2.v201012040545-lib</groupId> 
		    <artifactId>javax.wsdl_1.6.2.v201012040545</artifactId> 
		    <version>1.0</version> 
	     </dependency> 
	     
	      <dependency> 
		    <groupId>jaxrpc-lib</groupId> 
		    <artifactId>jaxrpc</artifactId> 
		    <version>1.0</version> 
	     </dependency> 
	     
	     <dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${org.springframework.version}</version>
			<exclusions>
				<!-- Exclude Commons Logging in favor of SLF4j -->
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				 </exclusion>
			</exclusions>
		</dependency>
	     <dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>    <groupId>javax.enterprise</groupId>    <artifactId>cdi-api</artifactId>    <version>1.0</version></dependency>
		<dependency>    <groupId>org.jboss.spec.javax.interceptor</groupId>    <artifactId>jboss-interceptors-api_1.1_spec</artifactId>    <version>1.0.0.Final</version></dependency>
		<dependency>    <groupId>cglib</groupId>    <artifactId>cglib</artifactId>    <version>2.2.2</version></dependency>
		
	     			<!-- Integracion con Open AM - Spring Security -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
			<version>${spring.security.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-dao</artifactId>
			<version>${spring.security.version}</version>
		</dependency>

				<dependency>
			<groupId>com.sun.identity.provider</groupId>
			<artifactId>opensso-springsecurity</artifactId>
			<version>0.2</version>
		</dependency>

		<dependency>
			<groupId>com.forgerock.openam</groupId> 
			<artifactId>clientsdk</artifactId>
			<version>10.0.0</version>
			<scope>provided</scope>
		</dependency>
	      <dependency> 
		    <groupId>saaj-lib</groupId> 
		    <artifactId>saaj</artifactId> 
		    <version>1.0</version> 
	     </dependency>
	     
	     <!-- Cliente de Webservices. firma digital desarrollo -->
	     <!-- 
	      <dependency>
			 <groupId>mx.com.metatrust.doctrust</groupId>
		 	 <artifactId>ClienteWebServiceGuardaDocumentos</artifactId>
		  	 <version>1.1-SNAPSHOT</version> 
	      </dependency>   
		-->
	     <!-- Cliente de Webservices. firma digital kio -->
	    <dependency>
			<groupId>mx.com.metatrust.doctrust</groupId>
        	<artifactId>ClienteWebServiceGuardaDocumentos</artifactId>
<!--         	<version>1.2-RELEASE</version>  -->
        	<version>${mvn.version.clienteswebservices.guarda.documentos}</version>
	    </dependency>
 		
	    <dependency>
	    	<groupId>mx.gob.imss.ctirss.sso</groupId>
	    	<artifactId>AdmonUsuariosDelta-ttds</artifactId>
	    	<version>1.1-SNAPSHOT</version>
		</dependency>
		
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>ISO-8859-1</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.1.1</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<webResources>
                        <resource>
                            <filtering>true</filtering>
                            <directory>src/main/webapp</directory>
                            <includes>
                                <include>**/web.xml</include>
                                <include>**/general-context.xml</include>
                            </includes>
                        </resource>
                    </webResources>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.1</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<outputDirectory>${endorsed.dir}</outputDirectory>
							<silent>true</silent>
							<artifactItems>
								<artifactItem>
									<groupId>javaee</groupId>
									<artifactId>javaee-api</artifactId>
									<version>5</version>
									<type>jar</type>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<version>2.9</version>
				<configuration>
					<projectNameTemplate>[artifactId]-[version]</projectNameTemplate>
					<wtpmanifest>true</wtpmanifest>
					<wtpapplicationxml>true</wtpapplicationxml>
					<manifest>${basedir}/src/main/resources/META-INF/MANIFEST.MF</manifest>
					<wtpversion>2.0</wtpversion>
					<jeeversion>5.0</jeeversion>
					<additionalProjectFacets>
						<java>1.6</java>
						<jst.jsf>2.0</jst.jsf>
						<wst.jsdt.web>1.0</wst.jsdt.web>
					</additionalProjectFacets>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.apache.maven.plugins
										</groupId>
										<artifactId>
											maven-dependency-plugin
										</artifactId>
										<versionRange>
											[2.1,)
										</versionRange>
										<goals>
											<goal>copy</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<properties>
		<endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<jsf.version>2.1.1-b04</jsf.version>
		<ice.version>3.0.1</ice.version>
		<org.springframework.version>3.0.5.RELEASE</org.springframework.version> 
		<org.slf4j.version>1.7.5</org.slf4j.version>
		<org.aspectj.version>1.6.11</org.aspectj.version>
		<org.antlr.version>3.4</org.antlr.version>
		<org.jstl.version>1.2</org.jstl.version>
		<org.apache.karaf.assemblies.features.version>2.2.4</org.apache.karaf.assemblies.features.version>
		<org.apache.tiles.version>2.2.2</org.apache.tiles.version>
		<spring.security.version>2.0.4</spring.security.version>
	</properties>
	
	
	
</project>
