#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
 
 
#Tiles redirect

gestionDocumentoProbatorio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
gestionDocumentoProbatorio.url=gestionDocumentoProbatorio

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

domicilio.registro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registro.url=domicilioRegistro



domicilio.registroEmbebido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registroEmbebido.url=domicilioRegistroEmbebed


tramite.inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.inicio.url=tramiteinicio

tramite.capturar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.capturar.url=tramitecapturar

initAdmonDocumentosProbatorios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initAdmonDocumentosProbatorios.url=initAdmonDocumentosProbatorios

admon.doctosProbatorios.captura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
admon.doctosProbatorios.captura.url=admon.doctosProbatorios.captura

listaDocumentosRequeridos.(class)=org.springframework.web.servlet.view.JstlView
listaDocumentosRequeridos.url=/WEB-INF/views/doctosProbatorios/listaDocumentosRequeridos.jsp

initWizardCapturaDocumentos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initWizardCapturaDocumentos.url = initWizardCapturaDocumentos

#Vistas Relacionadas con captura de documentos
cedulaProfesional.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cedulaProfesional.url=cedulaProfesional

cartillaMilitar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaMilitar.url=cartillaMilitar

constanciaEstudios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
constanciaEstudios.url=constanciaEstudios

certificadoNacimiento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoNacimiento.url=certificadoNacimiento

pasaporte.(class)=org.springframework.web.servlet.view.tiles2.TilesView
pasaporte.url=pasaporte

actaComun.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaComun.url=actaComun

actaNacimiento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaNacimiento.url=actaNacimiento

curp.(class)=org.springframework.web.servlet.view.tiles2.TilesView
curp.url=curp

credencialElector.(class)=org.springframework.web.servlet.view.tiles2.TilesView
credencialElector.url=credencialElector

dictamenIncapacitado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
dictamenIncapacitado.url=dictamenIncapacitado

obstetrico.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obstetrico.url=obstetrico

certificadoSitCritica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoSitCritica.url=certificadoSitCritica

acuerdo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
acuerdo.url=acuerdo

vigenciaTemporal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vigenciaTemporal.url=vigenciaTemporal

compDom.(class)=org.springframework.web.servlet.view.tiles2.TilesView
compDom.url=compDom

adimss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
adimss.url=adimss

actaPactoCivil.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaPactoCivil.url=actaPactoCivil

actaUnionCivil.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaUnionCivil.url=actaUnionCivil

actaTerminoUnionCivil.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaTerminoUnionCivil.url=actaTerminoUnionCivil

#MUESTRA

muestraDocTram.(class)=org.springframework.web.servlet.view.tiles2.TilesView
muestraDocTram.url=muestraDocTram


cedulaProfesionalMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cedulaProfesionalMuestra.url=cedulaProfesionalMuestra

cartillaMilitarMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaMilitarMuestra.url=cartillaMilitarMuestra

constanciaEstudiosMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
constanciaEstudiosMuestra.url=constanciaEstudiosMuestra

certificadoNacimientoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoNacimientoMuestra.url=certificadoNacimientoMuestra

pasaporteMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
pasaporteMuestra.url=pasaporteMuestra

actaComunMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaComunMuestra.url=actaComunMuestra

actaNacimientoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaNacimientoMuestra.url=actaNacimientoMuestra

curpMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
curpMuestra.url=curpMuestra

adimssMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
adimssMuestra.url=adimssMuestra

actaUnionCivilMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaUnionCivilMuestra.url=actaUnionCivilMuestra

actaTerminoUnionCivilMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaTerminoUnionCivilMuestra.url=actaTerminoUnionCivilMuestra

credencialElectorMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
credencialElectorMuestra.url=credencialElectorMuestra

dictamenIncapacitadoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
dictamenIncapacitadoMuestra.url=dictamenIncapacitadoMuestra

obstetricoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obstetricoMuestra.url=obstetricoMuestra

certificadoSitCriticaMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoSitCriticaMuestra.url=certificadoSitCriticaMuestra

acuerdoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
acuerdoMuestra.url=acuerdoMuestra

vigenciaTemporalMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vigenciaTemporalMuestra.url=vigenciaTemporalMuestra

compDomMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
compDomMuestra.url=compDomMuestra

actaPactoCivilMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaPactoCivilMuestra.url=actaPactoCivilMuestra

autorizacionCorreccion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
autorizacionCorreccion.url=autorizacionCorreccion

asignarMedico.(class)=org.springframework.web.servlet.view.tiles2.TilesView
asignarMedico.url=asignarMedico

pruebaBoveda.(class)=org.springframework.web.servlet.view.JstlView
pruebaBoveda.url=/WEB-INF/views/boveda/pruebaBoveda.jsp

inicioBoveda.(class)=org.springframework.web.servlet.view.JstlView
inicioBoveda.url=/WEB-INF/views/boveda/inicioBoveda.jsp