//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 05:20:50 PM CST 
//


package mx.gob.imss.ctirss.delta.model.sua.integracion;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Trabajador complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trabajador">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoDeRegistro" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="registroPatronalIMSS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rfcPatron" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periodoDePago" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numeroDeSeguridadSocialDelTrabajador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="rfcDelTrabajador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="claveUnicaDelRegistroDePoblacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numeroDeCreditoINFONAVIT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="fechaDeInicioDelDescuentoDeCreditoINFONAVIT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numeroDeMovimientosEnElPeriodo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nombreDelTrabajador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ultimoSalarioDiarioIntegradoDelPeriodo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tipoDeTrabajador" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="jornadaPorSemanaReducida" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="diasCotizadosEnElMes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="diasDeIncapacidadEnElMes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="diasDeAusentismoEnElMes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cuotaFijaDeEnfermedadYMaternidad">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cuotaExcedenteDeEnfermedadYMaternidad">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prestacionesEnDineroDeEnfermedadYMaternidad">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="gastosMedicosPensionadosArt25">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="riesgosDeTrabajo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="invalidezYVida">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="guarderiaYPrestacionesSociales">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="actualizacionYRecargosDeLosCuatroSegurosIMSS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="diasCotizadosEnElBimestre" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="diasDeIncapacidadEnElBimestre" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="diasDeAusentismoEnElBimestre" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="retiro">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="actualizacionYRecargosDeRetiro">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cesantiaYVejezCuotaPatronal">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cesantiaYVejezCuotaTrabajador">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="actualizacionYRecargosDeCesantiaYVejez">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="aportacionVoluntaria">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="aportacionPatronalINFONAVIT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="amortizacionDeCreditoINFONAVIT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0.0"/>
 *               &lt;maxExclusive value="100000.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cuotaExcedenteCuotaObrera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prestacionesEnDineroCuotaObrera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gastosMedicosPensionadosCuotaObrera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invalidezYVidaCuotaObrera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cesantiaYVejezCuotaObrera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="municipio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="movimientos" type="{http://mx.gob.imss.ctirss.delta/movimientosua}Movimiento" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trabajador", namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", propOrder = {
    "tipoDeRegistro",
    "registroPatronalIMSS",
    "rfcPatron",
    "periodoDePago",
    "numeroDeSeguridadSocialDelTrabajador",
    "rfcDelTrabajador",
    "claveUnicaDelRegistroDePoblacion",
    "numeroDeCreditoINFONAVIT",
    "fechaDeInicioDelDescuentoDeCreditoINFONAVIT",
    "numeroDeMovimientosEnElPeriodo",
    "nombreDelTrabajador",
    "ultimoSalarioDiarioIntegradoDelPeriodo",
    "tipoDeTrabajador",
    "jornadaPorSemanaReducida",
    "diasCotizadosEnElMes",
    "diasDeIncapacidadEnElMes",
    "diasDeAusentismoEnElMes",
    "cuotaFijaDeEnfermedadYMaternidad",
    "cuotaExcedenteDeEnfermedadYMaternidad",
    "prestacionesEnDineroDeEnfermedadYMaternidad",
    "gastosMedicosPensionadosArt25",
    "riesgosDeTrabajo",
    "invalidezYVida",
    "guarderiaYPrestacionesSociales",
    "actualizacionYRecargosDeLosCuatroSegurosIMSS",
    "diasCotizadosEnElBimestre",
    "diasDeIncapacidadEnElBimestre",
    "diasDeAusentismoEnElBimestre",
    "retiro",
    "actualizacionYRecargosDeRetiro",
    "cesantiaYVejezCuotaPatronal",
    "cesantiaYVejezCuotaTrabajador",
    "actualizacionYRecargosDeCesantiaYVejez",
    "aportacionVoluntaria",
    "aportacionPatronalINFONAVIT",
    "amortizacionDeCreditoINFONAVIT",
    "cuotaExcedenteCuotaObrera",
    "prestacionesEnDineroCuotaObrera",
    "gastosMedicosPensionadosCuotaObrera",
    "invalidezYVidaCuotaObrera",
    "cesantiaYVejezCuotaObrera",
    "municipio",
    "movimientos"
})
public class Trabajador {

    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int tipoDeRegistro;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String registroPatronalIMSS;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String rfcPatron;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String periodoDePago;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected long numeroDeSeguridadSocialDelTrabajador;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String rfcDelTrabajador;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String claveUnicaDelRegistroDePoblacion;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected long numeroDeCreditoINFONAVIT;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int fechaDeInicioDelDescuentoDeCreditoINFONAVIT;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int numeroDeMovimientosEnElPeriodo;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String nombreDelTrabajador;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal ultimoSalarioDiarioIntegradoDelPeriodo;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int tipoDeTrabajador;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int jornadaPorSemanaReducida;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int diasCotizadosEnElMes;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int diasDeIncapacidadEnElMes;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int diasDeAusentismoEnElMes;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal cuotaFijaDeEnfermedadYMaternidad;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal cuotaExcedenteDeEnfermedadYMaternidad;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal prestacionesEnDineroDeEnfermedadYMaternidad;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal gastosMedicosPensionadosArt25;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal riesgosDeTrabajo;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal invalidezYVida;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal guarderiaYPrestacionesSociales;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal actualizacionYRecargosDeLosCuatroSegurosIMSS;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int diasCotizadosEnElBimestre;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int diasDeIncapacidadEnElBimestre;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua")
    protected int diasDeAusentismoEnElBimestre;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal retiro;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal actualizacionYRecargosDeRetiro;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal cesantiaYVejezCuotaPatronal;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal cesantiaYVejezCuotaTrabajador;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal actualizacionYRecargosDeCesantiaYVejez;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal aportacionVoluntaria;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal aportacionPatronalINFONAVIT;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected BigDecimal amortizacionDeCreditoINFONAVIT;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String cuotaExcedenteCuotaObrera;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String prestacionesEnDineroCuotaObrera;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String gastosMedicosPensionadosCuotaObrera;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String invalidezYVidaCuotaObrera;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String cesantiaYVejezCuotaObrera;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected String municipio;
    @XmlElement(namespace = "http://mx.gob.imss.ctirss.delta/movimientosua", required = true)
    protected List<Movimiento> movimientos;

    /**
     * Gets the value of the tipoDeRegistro property.
     * 
     */
    public int getTipoDeRegistro() {
        return tipoDeRegistro;
    }

    /**
     * Sets the value of the tipoDeRegistro property.
     * 
     */
    public void setTipoDeRegistro(int value) {
        this.tipoDeRegistro = value;
    }

    /**
     * Gets the value of the registroPatronalIMSS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistroPatronalIMSS() {
        return registroPatronalIMSS;
    }

    /**
     * Sets the value of the registroPatronalIMSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistroPatronalIMSS(String value) {
        this.registroPatronalIMSS = value;
    }

    /**
     * Gets the value of the rfcPatron property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcPatron() {
        return rfcPatron;
    }

    /**
     * Sets the value of the rfcPatron property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcPatron(String value) {
        this.rfcPatron = value;
    }

    /**
     * Gets the value of the periodoDePago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodoDePago() {
        return periodoDePago;
    }

    /**
     * Sets the value of the periodoDePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodoDePago(String value) {
        this.periodoDePago = value;
    }

    /**
     * Gets the value of the numeroDeSeguridadSocialDelTrabajador property.
     * 
     */
    public long getNumeroDeSeguridadSocialDelTrabajador() {
        return numeroDeSeguridadSocialDelTrabajador;
    }

    /**
     * Sets the value of the numeroDeSeguridadSocialDelTrabajador property.
     * 
     */
    public void setNumeroDeSeguridadSocialDelTrabajador(long value) {
        this.numeroDeSeguridadSocialDelTrabajador = value;
    }

    /**
     * Gets the value of the rfcDelTrabajador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcDelTrabajador() {
        return rfcDelTrabajador;
    }

    /**
     * Sets the value of the rfcDelTrabajador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcDelTrabajador(String value) {
        this.rfcDelTrabajador = value;
    }

    /**
     * Gets the value of the claveUnicaDelRegistroDePoblacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveUnicaDelRegistroDePoblacion() {
        return claveUnicaDelRegistroDePoblacion;
    }

    /**
     * Sets the value of the claveUnicaDelRegistroDePoblacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveUnicaDelRegistroDePoblacion(String value) {
        this.claveUnicaDelRegistroDePoblacion = value;
    }

    /**
     * Gets the value of the numeroDeCreditoINFONAVIT property.
     * 
     */
    public long getNumeroDeCreditoINFONAVIT() {
        return numeroDeCreditoINFONAVIT;
    }

    /**
     * Sets the value of the numeroDeCreditoINFONAVIT property.
     * 
     */
    public void setNumeroDeCreditoINFONAVIT(long value) {
        this.numeroDeCreditoINFONAVIT = value;
    }

    /**
     * Gets the value of the fechaDeInicioDelDescuentoDeCreditoINFONAVIT property.
     * 
     */
    public int getFechaDeInicioDelDescuentoDeCreditoINFONAVIT() {
        return fechaDeInicioDelDescuentoDeCreditoINFONAVIT;
    }

    /**
     * Sets the value of the fechaDeInicioDelDescuentoDeCreditoINFONAVIT property.
     * 
     */
    public void setFechaDeInicioDelDescuentoDeCreditoINFONAVIT(int value) {
        this.fechaDeInicioDelDescuentoDeCreditoINFONAVIT = value;
    }

    /**
     * Gets the value of the numeroDeMovimientosEnElPeriodo property.
     * 
     */
    public int getNumeroDeMovimientosEnElPeriodo() {
        return numeroDeMovimientosEnElPeriodo;
    }

    /**
     * Sets the value of the numeroDeMovimientosEnElPeriodo property.
     * 
     */
    public void setNumeroDeMovimientosEnElPeriodo(int value) {
        this.numeroDeMovimientosEnElPeriodo = value;
    }

    /**
     * Gets the value of the nombreDelTrabajador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreDelTrabajador() {
        return nombreDelTrabajador;
    }

    /**
     * Sets the value of the nombreDelTrabajador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreDelTrabajador(String value) {
        this.nombreDelTrabajador = value;
    }

    /**
     * Gets the value of the ultimoSalarioDiarioIntegradoDelPeriodo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUltimoSalarioDiarioIntegradoDelPeriodo() {
        return ultimoSalarioDiarioIntegradoDelPeriodo;
    }

    /**
     * Sets the value of the ultimoSalarioDiarioIntegradoDelPeriodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUltimoSalarioDiarioIntegradoDelPeriodo(BigDecimal value) {
        this.ultimoSalarioDiarioIntegradoDelPeriodo = value;
    }

    /**
     * Gets the value of the tipoDeTrabajador property.
     * 
     */
    public int getTipoDeTrabajador() {
        return tipoDeTrabajador;
    }

    /**
     * Sets the value of the tipoDeTrabajador property.
     * 
     */
    public void setTipoDeTrabajador(int value) {
        this.tipoDeTrabajador = value;
    }

    /**
     * Gets the value of the jornadaPorSemanaReducida property.
     * 
     */
    public int getJornadaPorSemanaReducida() {
        return jornadaPorSemanaReducida;
    }

    /**
     * Sets the value of the jornadaPorSemanaReducida property.
     * 
     */
    public void setJornadaPorSemanaReducida(int value) {
        this.jornadaPorSemanaReducida = value;
    }

    /**
     * Gets the value of the diasCotizadosEnElMes property.
     * 
     */
    public int getDiasCotizadosEnElMes() {
        return diasCotizadosEnElMes;
    }

    /**
     * Sets the value of the diasCotizadosEnElMes property.
     * 
     */
    public void setDiasCotizadosEnElMes(int value) {
        this.diasCotizadosEnElMes = value;
    }

    /**
     * Gets the value of the diasDeIncapacidadEnElMes property.
     * 
     */
    public int getDiasDeIncapacidadEnElMes() {
        return diasDeIncapacidadEnElMes;
    }

    /**
     * Sets the value of the diasDeIncapacidadEnElMes property.
     * 
     */
    public void setDiasDeIncapacidadEnElMes(int value) {
        this.diasDeIncapacidadEnElMes = value;
    }

    /**
     * Gets the value of the diasDeAusentismoEnElMes property.
     * 
     */
    public int getDiasDeAusentismoEnElMes() {
        return diasDeAusentismoEnElMes;
    }

    /**
     * Sets the value of the diasDeAusentismoEnElMes property.
     * 
     */
    public void setDiasDeAusentismoEnElMes(int value) {
        this.diasDeAusentismoEnElMes = value;
    }

    /**
     * Gets the value of the cuotaFijaDeEnfermedadYMaternidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCuotaFijaDeEnfermedadYMaternidad() {
        return cuotaFijaDeEnfermedadYMaternidad;
    }

    /**
     * Sets the value of the cuotaFijaDeEnfermedadYMaternidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCuotaFijaDeEnfermedadYMaternidad(BigDecimal value) {
        this.cuotaFijaDeEnfermedadYMaternidad = value;
    }

    /**
     * Gets the value of the cuotaExcedenteDeEnfermedadYMaternidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCuotaExcedenteDeEnfermedadYMaternidad() {
        return cuotaExcedenteDeEnfermedadYMaternidad;
    }

    /**
     * Sets the value of the cuotaExcedenteDeEnfermedadYMaternidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCuotaExcedenteDeEnfermedadYMaternidad(BigDecimal value) {
        this.cuotaExcedenteDeEnfermedadYMaternidad = value;
    }

    /**
     * Gets the value of the prestacionesEnDineroDeEnfermedadYMaternidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrestacionesEnDineroDeEnfermedadYMaternidad() {
        return prestacionesEnDineroDeEnfermedadYMaternidad;
    }

    /**
     * Sets the value of the prestacionesEnDineroDeEnfermedadYMaternidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrestacionesEnDineroDeEnfermedadYMaternidad(BigDecimal value) {
        this.prestacionesEnDineroDeEnfermedadYMaternidad = value;
    }

    /**
     * Gets the value of the gastosMedicosPensionadosArt25 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGastosMedicosPensionadosArt25() {
        return gastosMedicosPensionadosArt25;
    }

    /**
     * Sets the value of the gastosMedicosPensionadosArt25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGastosMedicosPensionadosArt25(BigDecimal value) {
        this.gastosMedicosPensionadosArt25 = value;
    }

    /**
     * Gets the value of the riesgosDeTrabajo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRiesgosDeTrabajo() {
        return riesgosDeTrabajo;
    }

    /**
     * Sets the value of the riesgosDeTrabajo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRiesgosDeTrabajo(BigDecimal value) {
        this.riesgosDeTrabajo = value;
    }

    /**
     * Gets the value of the invalidezYVida property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInvalidezYVida() {
        return invalidezYVida;
    }

    /**
     * Sets the value of the invalidezYVida property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInvalidezYVida(BigDecimal value) {
        this.invalidezYVida = value;
    }

    /**
     * Gets the value of the guarderiaYPrestacionesSociales property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuarderiaYPrestacionesSociales() {
        return guarderiaYPrestacionesSociales;
    }

    /**
     * Sets the value of the guarderiaYPrestacionesSociales property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuarderiaYPrestacionesSociales(BigDecimal value) {
        this.guarderiaYPrestacionesSociales = value;
    }

    /**
     * Gets the value of the actualizacionYRecargosDeLosCuatroSegurosIMSS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualizacionYRecargosDeLosCuatroSegurosIMSS() {
        return actualizacionYRecargosDeLosCuatroSegurosIMSS;
    }

    /**
     * Sets the value of the actualizacionYRecargosDeLosCuatroSegurosIMSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualizacionYRecargosDeLosCuatroSegurosIMSS(BigDecimal value) {
        this.actualizacionYRecargosDeLosCuatroSegurosIMSS = value;
    }

    /**
     * Gets the value of the diasCotizadosEnElBimestre property.
     * 
     */
    public int getDiasCotizadosEnElBimestre() {
        return diasCotizadosEnElBimestre;
    }

    /**
     * Sets the value of the diasCotizadosEnElBimestre property.
     * 
     */
    public void setDiasCotizadosEnElBimestre(int value) {
        this.diasCotizadosEnElBimestre = value;
    }

    /**
     * Gets the value of the diasDeIncapacidadEnElBimestre property.
     * 
     */
    public int getDiasDeIncapacidadEnElBimestre() {
        return diasDeIncapacidadEnElBimestre;
    }

    /**
     * Sets the value of the diasDeIncapacidadEnElBimestre property.
     * 
     */
    public void setDiasDeIncapacidadEnElBimestre(int value) {
        this.diasDeIncapacidadEnElBimestre = value;
    }

    /**
     * Gets the value of the diasDeAusentismoEnElBimestre property.
     * 
     */
    public int getDiasDeAusentismoEnElBimestre() {
        return diasDeAusentismoEnElBimestre;
    }

    /**
     * Sets the value of the diasDeAusentismoEnElBimestre property.
     * 
     */
    public void setDiasDeAusentismoEnElBimestre(int value) {
        this.diasDeAusentismoEnElBimestre = value;
    }

    /**
     * Gets the value of the retiro property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetiro() {
        return retiro;
    }

    /**
     * Sets the value of the retiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetiro(BigDecimal value) {
        this.retiro = value;
    }

    /**
     * Gets the value of the actualizacionYRecargosDeRetiro property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualizacionYRecargosDeRetiro() {
        return actualizacionYRecargosDeRetiro;
    }

    /**
     * Sets the value of the actualizacionYRecargosDeRetiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualizacionYRecargosDeRetiro(BigDecimal value) {
        this.actualizacionYRecargosDeRetiro = value;
    }

    /**
     * Gets the value of the cesantiaYVejezCuotaPatronal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCesantiaYVejezCuotaPatronal() {
        return cesantiaYVejezCuotaPatronal;
    }

    /**
     * Sets the value of the cesantiaYVejezCuotaPatronal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCesantiaYVejezCuotaPatronal(BigDecimal value) {
        this.cesantiaYVejezCuotaPatronal = value;
    }

    /**
     * Gets the value of the cesantiaYVejezCuotaTrabajador property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCesantiaYVejezCuotaTrabajador() {
        return cesantiaYVejezCuotaTrabajador;
    }

    /**
     * Sets the value of the cesantiaYVejezCuotaTrabajador property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCesantiaYVejezCuotaTrabajador(BigDecimal value) {
        this.cesantiaYVejezCuotaTrabajador = value;
    }

    /**
     * Gets the value of the actualizacionYRecargosDeCesantiaYVejez property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualizacionYRecargosDeCesantiaYVejez() {
        return actualizacionYRecargosDeCesantiaYVejez;
    }

    /**
     * Sets the value of the actualizacionYRecargosDeCesantiaYVejez property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualizacionYRecargosDeCesantiaYVejez(BigDecimal value) {
        this.actualizacionYRecargosDeCesantiaYVejez = value;
    }

    /**
     * Gets the value of the aportacionVoluntaria property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAportacionVoluntaria() {
        return aportacionVoluntaria;
    }

    /**
     * Sets the value of the aportacionVoluntaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAportacionVoluntaria(BigDecimal value) {
        this.aportacionVoluntaria = value;
    }

    /**
     * Gets the value of the aportacionPatronalINFONAVIT property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAportacionPatronalINFONAVIT() {
        return aportacionPatronalINFONAVIT;
    }

    /**
     * Sets the value of the aportacionPatronalINFONAVIT property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAportacionPatronalINFONAVIT(BigDecimal value) {
        this.aportacionPatronalINFONAVIT = value;
    }

    /**
     * Gets the value of the amortizacionDeCreditoINFONAVIT property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmortizacionDeCreditoINFONAVIT() {
        return amortizacionDeCreditoINFONAVIT;
    }

    /**
     * Sets the value of the amortizacionDeCreditoINFONAVIT property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmortizacionDeCreditoINFONAVIT(BigDecimal value) {
        this.amortizacionDeCreditoINFONAVIT = value;
    }

    /**
     * Gets the value of the cuotaExcedenteCuotaObrera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuotaExcedenteCuotaObrera() {
        return cuotaExcedenteCuotaObrera;
    }

    /**
     * Sets the value of the cuotaExcedenteCuotaObrera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuotaExcedenteCuotaObrera(String value) {
        this.cuotaExcedenteCuotaObrera = value;
    }

    /**
     * Gets the value of the prestacionesEnDineroCuotaObrera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrestacionesEnDineroCuotaObrera() {
        return prestacionesEnDineroCuotaObrera;
    }

    /**
     * Sets the value of the prestacionesEnDineroCuotaObrera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrestacionesEnDineroCuotaObrera(String value) {
        this.prestacionesEnDineroCuotaObrera = value;
    }

    /**
     * Gets the value of the gastosMedicosPensionadosCuotaObrera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGastosMedicosPensionadosCuotaObrera() {
        return gastosMedicosPensionadosCuotaObrera;
    }

    /**
     * Sets the value of the gastosMedicosPensionadosCuotaObrera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGastosMedicosPensionadosCuotaObrera(String value) {
        this.gastosMedicosPensionadosCuotaObrera = value;
    }

    /**
     * Gets the value of the invalidezYVidaCuotaObrera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvalidezYVidaCuotaObrera() {
        return invalidezYVidaCuotaObrera;
    }

    /**
     * Sets the value of the invalidezYVidaCuotaObrera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvalidezYVidaCuotaObrera(String value) {
        this.invalidezYVidaCuotaObrera = value;
    }

    /**
     * Gets the value of the cesantiaYVejezCuotaObrera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCesantiaYVejezCuotaObrera() {
        return cesantiaYVejezCuotaObrera;
    }

    /**
     * Sets the value of the cesantiaYVejezCuotaObrera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCesantiaYVejezCuotaObrera(String value) {
        this.cesantiaYVejezCuotaObrera = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipio(String value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the movimientos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movimientos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovimientos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Movimiento }
     * 
     * 
     */
    public List<Movimiento> getMovimientos() {
        if (movimientos == null) {
            movimientos = new ArrayList<Movimiento>();
        }
        return this.movimientos;
    }

}
