//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//


package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;


public class ClavePresupuestal  extends AbstractModel implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    protected Long idClavePresupuestal;
    protected String clavePresupuestal;
    protected String clavePresupuestalRecortada;
    protected String descripcion;

    /**
     * Gets the value of the idClavePresupuestal property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdClavePresupuestal() {
        return idClavePresupuestal;
    }

    /**
     * Sets the value of the idClavePresupuestal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdClavePresupuestal(Long value) {
        this.idClavePresupuestal = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

	/**
	 * @return the clavePresupuestalRecortada
	 */
	public String getClavePresupuestalRecortada() {
		return clavePresupuestalRecortada;
	}

	/**
	 * @param clavePresupuestalRecortada the clavePresupuestalRecortada to set
	 */
	public void setClavePresupuestalRecortada(String clavePresupuestalRecortada) {
		this.clavePresupuestalRecortada = clavePresupuestalRecortada;
	}

	/**
	 * @return the clavePresupuestal
	 */
	public String getClavePresupuestal() {
		return clavePresupuestal;
	}

	/**
	 * @param clavePresupuestal the clavePresupuestal to set
	 */
	public void setClavePresupuestal(String clavePresupuestal) {
		this.clavePresupuestal = clavePresupuestal;
	}

}
