//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.asegurado.Asegurado;
import mx.gob.imss.ctirss.delta.model.asegurado.AsignacionNSS;
import mx.gob.imss.ctirss.delta.model.derechohabiente.dto.BajaDerechohabienteDto;
import mx.gob.imss.ctirss.delta.model.domicilio.Domicilio;
import mx.gob.imss.ctirss.delta.model.gestion.tramite.TipoTramite;

@XmlRootElement(name = "GrupoFamiliar")
public class GrupoFamiliar  extends AbstractModel implements Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Derechohabiente derechohabiente;
	private AsignacionNSS asignacionNSS;
	private BigDecimal calidad;	
	private Parentesco parentesco;	
	private Domicilio domicilio;	
	private EstadoDerechohabiente estadoDerechohabiente;
	private SubEstadoDerechohabiente subEstadoDerechohabiente;	
	private Date fechaInicioVigencia;
	private Date fechaFinVigencia;
	private Date fechaRegistroAlta;
	private Date fechaRegistroActualizacion;
	private Date fechaRegistroBaja;
	private Date fechaCambioTurnoMedico;
	private MedicoEnTurno medicoEnTurno;
	private Boolean circunscripcionForaneaActiva;
	private Boolean prorrogaPermanente;
	private Boolean prorrogaActiva;
	private TipoTramite tipoProrroga;
	private Date indSimilarCalDifGpoFam;
	private String agregadoMedico;
	private String agregadoAfiliacion;
	private Integer indRegistrado;
	private Long cvePersonaDomicilio;
	private Integer indRecienNacido;
	private String conDerechoInc;
	private String conDerechoSm;
	private Integer indAcuerdo;
	private String numeroAcuerdo;
	
	
	public GrupoFamiliar(){
		
	}
	
	public GrupoFamiliar(Long idAsignacionNSS, Long idPersona) {
		this.asignacionNSS = new AsignacionNSS(idAsignacionNSS);
		this.derechohabiente = new Derechohabiente(idPersona);
	}
	
	public GrupoFamiliar(AsignacionNSS asignacionNSS, Derechohabiente derechohabiente){
		this.asignacionNSS = asignacionNSS;
		this.derechohabiente = derechohabiente;
	}
	
	/**
	 * @return the circunscripcionForaneaActiva
	 */
	public Boolean getCircunscripcionForaneaActiva() {
		return circunscripcionForaneaActiva;
	}

	/**
	 * @param circunscripcionForaneaActiva the circunscripcionForaneaActiva to set
	 */
	public void setCircunscripcionForaneaActiva(Boolean circunscripcionForaneaActiva) {
		this.circunscripcionForaneaActiva = circunscripcionForaneaActiva;
	}

	/**
	 * Gets the value of the aseguradoPension property.
	 * 
	 * @return possible object is {@link Asegurado }
	 * 
	 */
	public AsignacionNSS getAsignacionNSS() {
		return asignacionNSS;
	}

	/**
	 * Sets the value of the aseguradoPension property.
	 * 
	 * @param value
	 *            allowed object is {@link Asegurado }
	 * 
	 */
	public void setAsignacionNSS(AsignacionNSS value) {
		this.asignacionNSS = value;
	}

	/**
	 * Gets the value of the derechohabiente property.
	 * 
	 * @return possible object is {@link Derechohabiente }
	 * 
	 */
	public Derechohabiente getDerechohabiente() {
		return derechohabiente;
	}

	/**
	 * Sets the value of the derechohabiente property.
	 * 
	 * @param value
	 *            allowed object is {@link Derechohabiente }
	 * 
	 */
	public void setDerechohabiente(Derechohabiente value) {
		this.derechohabiente = value;
	}

	/**
	 * Gets the value of the parentesco property.
	 * 
	 * @return possible object is {@link Parentesco }
	 * 
	 */
	public Parentesco getParentesco() {
		return parentesco;
	}

	/**
	 * Sets the value of the parentesco property.
	 * 
	 * @param value
	 *            allowed object is {@link Parentesco }
	 * 
	 */
	public void setParentesco(Parentesco value) {
		this.parentesco = value;
	}

	/**
	 * Gets the value of the domicilio property.
	 * 
	 * @return possible object is {@link Domicilio }
	 * 
	 */
	public Domicilio getDomicilio() {
		return domicilio;
	}

	/**
	 * Sets the value of the domicilio property.
	 * 
	 * @param value
	 *            allowed object is {@link Domicilio }
	 * 
	 */
	public void setDomicilio(Domicilio value) {

		this.domicilio = value;
	}

	/**
	 * Gets the value of the estadoDerechohabiente property.
	 * 
	 * @return possible object is {@link EstadoDerechohabiente }
	 * 
	 */
	public EstadoDerechohabiente getEstadoDerechohabiente() {
		return estadoDerechohabiente;
	}

	/**
	 * Sets the value of the estadoDerechohabiente property.
	 * 
	 * @param value
	 *            allowed object is {@link EstadoDerechohabiente }
	 * 
	 */
	public void setEstadoDerechohabiente(EstadoDerechohabiente value) {
		this.estadoDerechohabiente = value;
	}

	/**
	 * Gets the value of the subEstadoDerechohabiente property.
	 * 
	 * @return possible object is {@link SubEstadoDerechohabiente }
	 * 
	 */
	public SubEstadoDerechohabiente getSubEstadoDerechohabiente() {
		return subEstadoDerechohabiente;
	}

	/**
	 * Sets the value of the subEstadoDerechohabiente property.
	 * 
	 * @param value
	 *            allowed object is {@link SubEstadoDerechohabiente }
	 * 
	 */
	public void setSubEstadoDerechohabiente(SubEstadoDerechohabiente value) {
		this.subEstadoDerechohabiente = value;
	}

	/**
	 * Gets the value of the calidad property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getCalidad() {
		return calidad;
	}

	/**
	 * Sets the value of the calidad property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setCalidad(BigDecimal value) {
		this.calidad = value;
	}

	/**
	 * Gets the value of the fechaInicioVigencia property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getFechaInicioVigencia() {
		return fechaInicioVigencia;
	}

	/**
	 * Sets the value of the fechaInicioVigencia property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setFechaInicioVigencia(Date value) {
		this.fechaInicioVigencia = value;
	}

	/**
	 * Gets the value of the fechaFinVigencia property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getFechaFinVigencia() {
		return fechaFinVigencia;
	}

	/**
	 * Sets the value of the fechaFinVigencia property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setFechaFinVigencia(Date value) {
		this.fechaFinVigencia = value;
	}

	public Date getFechaRegistroAlta() {
		return fechaRegistroAlta;
	}

	public void setFechaRegistroAlta(Date fechaRegistroAlta) {
		this.fechaRegistroAlta = fechaRegistroAlta;
	}

	public Date getFechaRegistroActualizacion() {
		return fechaRegistroActualizacion;
	}

	public void setFechaRegistroActualizacion(Date fechaRegistroActualizacion) {
		this.fechaRegistroActualizacion = fechaRegistroActualizacion;
	}

	public Date getFechaRegistroBaja() {
		return fechaRegistroBaja;
	}

	public void setFechaRegistroBaja(Date fechaRegistroBaja) {
		this.fechaRegistroBaja = fechaRegistroBaja;
	}

	/**
	 * @return the medicoEnTurno
	 */
	public MedicoEnTurno getMedicoEnTurno() {
		return medicoEnTurno;
	}

	/**
	 * @param medicoEnTurno the medicoEnTurno to set
	 */
	public void setMedicoEnTurno(MedicoEnTurno medicoEnTurno) {
		this.medicoEnTurno = medicoEnTurno;
	}

	public Boolean getProrrogaPermanente() {
		return prorrogaPermanente;
	}

	public void setProrrogaPermanente(Boolean prorrogaPermanente) {
		this.prorrogaPermanente = prorrogaPermanente;
	}

	public TipoTramite getTipoProrroga() {
		return tipoProrroga;
	}

	public void setTipoProrroga(TipoTramite tipoProrroga) {
		this.tipoProrroga = tipoProrroga;
	}

	public Boolean getProrrogaActiva() {
		return prorrogaActiva;
	}

	public void setProrrogaActiva(Boolean prorrogaActiva) {
		this.prorrogaActiva = prorrogaActiva;
	}

	public Date getFechaCambioTurnoMedico() {
		return fechaCambioTurnoMedico;
	}

	public void setFechaCambioTurnoMedico(Date fechaCambioTurnoMedico) {
		this.fechaCambioTurnoMedico = fechaCambioTurnoMedico;
	}

	public Date getIndSimilarCalDifGpoFam() {
		return indSimilarCalDifGpoFam;
	}

	public void setIndSimilarCalDifGpoFam(Date indSimilarCalDifGpoFam) {
		this.indSimilarCalDifGpoFam = indSimilarCalDifGpoFam;
	}

	public String getAgregadoMedico() {
		return agregadoMedico;
	}

	public void setAgregadoMedico(String agregadoMedico) {
		this.agregadoMedico = agregadoMedico;
	}

	public String getAgregadoAfiliacion() {
		return agregadoAfiliacion;
	}

	public void setAgregadoAfiliacion(String agregadoAfiliacion) {
		this.agregadoAfiliacion = agregadoAfiliacion;
	}

	public Integer getIndRegistrado() {
		return indRegistrado;
	}

	public void setIndRegistrado(Integer indRegistrado) {
		this.indRegistrado = indRegistrado;
	}

	public Long getCvePersonaDomicilio() {
		return cvePersonaDomicilio;
	}

	public void setCvePersonaDomicilio(Long cvePersonaDomicilio) {
		this.cvePersonaDomicilio = cvePersonaDomicilio;
	}

	public Integer getIndRecienNacido() {
		return indRecienNacido;
	}

	public void setIndRecienNacido(Integer indRecienNacido) {
		this.indRecienNacido = indRecienNacido;
	}	

	
	
	public String getConDerechoInc() {
		return conDerechoInc;
	}


	public void setConDerechoInc(String conDerechoInc) {
		this.conDerechoInc = conDerechoInc;
	}


	public String getConDerechoSm() {
		return conDerechoSm;
	}


	public void setConDerechoSm(String conDerechoSm) {
		this.conDerechoSm = conDerechoSm;
	}

	
	

	@Override
	public boolean equals(Object obj) {
		
		try{
			if (obj == this)
				return true;
			
			if( obj instanceof GrupoFamiliar  ){
				Derechohabiente derechohabiente = ((GrupoFamiliar)obj).getDerechohabiente(); 
				
				return ( this.getDerechohabiente().getAsignacionNSS().getIdAsignacionNSS().equals(derechohabiente.getAsignacionNSS().getIdAsignacionNSS()) )  
						&&  this.getDerechohabiente().getIdPersona().equals(derechohabiente.getIdPersona()  );
			}	
				
			if (!(obj instanceof BajaDerechohabienteDto))
				return false;	
			
			BajaDerechohabienteDto baja = (BajaDerechohabienteDto)obj;
			
			return ( this.getDerechohabiente().getIdPersona().equals(baja.getCveIdPersonaIntegrante()) 
					&& this.getDerechohabiente().getAsignacionNSS().getIdAsignacionNSS().equals(baja.getCveIdAsignacionNSS()) );
			
		}catch(Exception e){
			System.out.println("Ha ocurrido un error inesperado");
		}
		
		return false;
			
	}
	
	@Override
	public int hashCode(){
		
		try{
			return  (this.derechohabiente.getNombre()+ "" +this.asignacionNSS.getIdAsignacionNSS()).hashCode();
		}catch(Exception e){
			System.out.println("Ha ocurrido un error inesperado");
		}
		
		return 0;
	}

	public Integer getIndAcuerdo() {
		return indAcuerdo;
	}

	public void setIndAcuerdo(Integer indAcuerdo) {
		this.indAcuerdo = indAcuerdo;
	}

	public String getNumeroAcuerdo() {
		return numeroAcuerdo;
	}

	public void setNumeroAcuerdo(String numeroAcuerdo) {
		this.numeroAcuerdo = numeroAcuerdo;
	}
}