#
# Ruta para almacenar archivos adjuntos sobre los tramites de clasificacion
#Produccion/Stage
ruta.archivos.adjuntos.tramites.clasificacion=/share/MovPat

#Desarrollo
#ruta.archivos.adjuntos.tramites.clasificacion=C://temp//MovPat