package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.TipoRegistroDTO;

/**
 * RocTipoRegistro generated by hbm2java
 */
@Entity
@Table(name = "ROC_TIPO_REGISTRO", schema = "MGPROC01")
@Transactional
public class RocTipoRegistro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6561907336869097445L;
	private Long cveTipoRegistro;
	private String desTipoRegistro;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocTipoRegistro() {
	}

	public RocTipoRegistro(Long cveTipoRegistro) {
		this.cveTipoRegistro = cveTipoRegistro;
	}

	public RocTipoRegistro(Long cveTipoRegistro, String desTipoRegistro, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveTipoRegistro = cveTipoRegistro;
		this.desTipoRegistro = desTipoRegistro;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id
	@Column(name = "CVE_ID_TIPO_REGISTRO", unique = true, nullable = false)
	public Long getCveTipoRegistro() {
		return this.cveTipoRegistro;
	}

	public void setCveTipoRegistro(Long cveTipoRegistro) {
		this.cveTipoRegistro = cveTipoRegistro;
	}

	@Column(name = "DES_TIPO_REGISTRO", length = 80)
	public String getDesTipoRegistro() {
		return this.desTipoRegistro;
	}

	public void setDesTipoRegistro(String desTipoRegistro) {
		this.desTipoRegistro = desTipoRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}


	public TipoRegistroDTO toConvertTipoRegistroDTO(){
		
		TipoRegistroDTO tipoRegistroDTO = new TipoRegistroDTO();
		
		tipoRegistroDTO.setCveTipoRegistro(this.getCveTipoRegistro());
		tipoRegistroDTO.setDesTipoRegistro(this.getDesTipoRegistro());

		
		return tipoRegistroDTO;
		
	}
}
