##################
# FTP FileConfig #
##################
#filesystem.sie.output.url=pruebaAutomatizacion
filesystem.sie.output.url=qalogs


################
# Servidor ftp #
################
ftp.server.url=11.254.13.4
ftp.server.user=pruebas
ftp.server.passwd=pruebas
ftp.server.port=21

application.mode=test


##################
# Ruta de origen #
##################
#file.sie.input.url=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/estudiante
file.sie.input.url=/sindo/ftp/estudiante/file/layout


####################
# Ruta de respaldo #
####################
#file.sie.resp.url=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/ESTUDIANTE_HIST
file.sie.resp.url=/sindo/resp/ESTUDIANTE_HIST
file.sie.resp.origen=/sindo/ftp/estudiante/file


################
# Archivos SIE #
################
sie.file.sie01=SIEArchivoBase


##########################
# Archivos de validacion #
##########################

#filesystem.delta.proceso.estatus=/share/oracle/osbapdir01_domain/osb_cluster1/ftp
filesystem.delta.proceso.estatus=/sindo/bloq
