#reemplazar con los datos de su consola
service.provider.url=t3://localhost:7001
service.security.principal=weblogic
service.security.credentials=weblogic1

#Expresiones de tiempo
movimientoSindoJob.cronTrigger.cronExpression=59 59 11,17,23 * * ?