#spring.datasource.driverClassName=org.h2.Driver
#spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.isolation-level-for-create=default
spring.profiles.active=@spring.profiles.active@

#DataSource - Primary
spring.primary.datasource.driver-class-name=@db1.driver@
spring.primary.datasource.username=@db1.jdbc.username@
spring.primary.datasource.password=@db1.jdbc.password@
spring.primary.datasource.url=@db1url@
#DataSource - Secondary

spring.secondary.datasource.driver-class-name=@db2.driver@
spring.secondary.datasource.username=@db2.jdbc.username@
spring.secondary.datasource.password=@db2.jdbc.password@
spring.secondary.datasource.url=@db2url@

logging.file.path=./logs/
logging.file.name=batchaltas.log
logging.pattern.rolling-file-name=batchaltas-%d{ddMMyyyy}.%i.log

