##### URL SERVICIOS NSSA #####

servicios.externos.rest.url.consulta.boveda=${mvn.servicios.externos.rest.url.consulta.boveda}
servicios.externos.rest.timeOut.connection=${mvn.servicios.externos.rest.timeOut.connection}
servicios.externos.rest.timeOut.response=${mvn.servicios.externos.rest.timeOut.response}


