##################
# FTP FileConfig #
##################
filesystem.sindo.output.url=ftp_test/sindo/output
filesystem.canase.output.url=ftp_test/canase/output
filesystem.riss.output.url=ftp_test/riss/output

################
# Servidor ftp #
################
ftp.server.url=11.254.13.4
ftp.server.user=pruebas
ftp.server.passwd=pruebas
ftp.server.port=21

application.mode=test


##################
# Ruta de origen #
##################
file.sindo.input.url=/daemonTest/sindo
file.sindo.input.tmp.url=/daemonTest/sindo_temp
file.canase.input.url=/daemonTest/canase
file.canase.input.tmp.url=/daemonTest/canase_temp
file.riss.input.url=/daemonTest/riss
file.riss.input.tmp.url=/daemonTest/riss_temp


####################
# Ruta de respaldo #
####################
file.sindo.resp.url=/daemonTest/sindo_hist
file.canase.resp.url=/daemonTest/canase_hist
file.riss.resp.url=/daemonTest/riss_hist


########################
# Ruta de verificacion #
########################
file.canase.verif.url=/daemonTest/canase_temp/checksum
file.sindo.verif.url=/daemonTest/sindo_temp/checksum
file.riss.verif.url=/daemonTest/riss_temp/checksum
file.canase.verif.time=10000
file.sindo.verif.time=10000
file.riss.verif.time=1000
file.canase.verif.retry=3
file.sindo.verif.retry=3
file.riss.verif.retry=3


############################
# Ruta de FTP (Filesystem) #
############################
filesystem.ftp.base.output.url=/daemonTest/ftp/base
filesystem.global.tmp.log.url=/daemonTest/log


################
# Archivos CIZ #
################
sindo.file.ciz01=AYPENT_CIZ01.txt
sindo.file.ciz02=AYPENT_CIZ02.txt
sindo.file.ciz03=AYPENT_CIZ03.txt


###################
# Archivos CANASE #
###################

canase.file.asignacion=APMVIAJ.txt


#################
# Archivos RISS #
#################

riss.file.movimiento=movimientosRiss.txt


###########################
# Archivos LOG Universal  #
###########################
global.log.file=DIAGNOSTICO_IMSS_LAYOUT.txt


##########################
# Archivos de validacion #
##########################

filesystem.delta.proceso.estatus=/daemonTest/bloq
