#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
loginRegistro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
loginRegistro.url=loginRegistro

obtenerInformacionRenapo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obtenerInformacionRenapo.url=obtenerInformacionRenapo

seguimientoTramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
seguimientoTramite.url=seguimientoTramite

folioTramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
folioTramite.url=folioTramite

capturarDomicilioRegistro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturarDomicilioRegistro.url=capturarDomicilioRegistro

registroSolicitudCDAResponsable.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroSolicitudCDAResponsable.url=registroSolicitudCDAResponsable

inicioRegistroCDACURP.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicioRegistroCDACURP.url=correccionDatosAseguradoAltaInit

datosAdicionalesHistoriaLaboral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosAdicionalesHistoriaLaboral.url=datosAdicionalesHistoriaLaboral

datosHistoriaLaboral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosHistoriaLaboral.url=datosHistoriaLaboral

informacionHistoriaLaboral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
informacionHistoriaLaboral.url=informacionHistoriaLaboral

respuesta.(class)=org.springframework.web.servlet.view.tiles2.TilesView
respuesta.url=respuesta

confirmarDatosSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmarDatosSolicitud.url=confirmarDatosSolicitud

domicilioAclaracion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilioAclaracion.url=domicilioAclaracion

bandejaSolicitudes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
bandejaSolicitudes.url=bandejaSolicitudes

capturarDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturarDomicilio.url=capturarDomicilio

cancelarSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cancelarSolicitud.url=cancelarSolicitud

recursoNoDisponible.(class)=org.springframework.web.servlet.view.tiles2.TilesView
recursoNoDisponible.url=recursoNoDisponible

datosNSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosNSS.url=datosNSS

viewInfoAdicionalRequerida.(class)=org.springframework.web.servlet.view.tiles2.TilesView
viewInfoAdicionalRequerida.url=requeridaInfoAdicional

viewInfoAdicionalCorrecion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
viewInfoAdicionalCorrecion.url=correcionInfoAdicional