#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
 
 
nacional.detalle.(class)=org.springframework.web.servlet.view.JstlView
nacional.detalle.url=/WEB-INF/views/domicilio/detalle/nacional.jsp
 
 
#Tiles redirect

gestionCobranza.(class)=org.springframework.web.servlet.view.tiles2.TilesView
gestionCobranza.url=gestionCobranza

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError



solicitud.enproceso.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitud.enproceso.url=solicitudEnproceso

#Firma Digital
initFirmaDigitalTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaDigitalTest.url=initFirmaDigitalTest

initFirmaDigital.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaDigital.url=initFirmaDigital

seleccionTipoFirma.(class)=org.springframework.web.servlet.view.tiles2.TilesView
seleccionTipoFirma.url=seleccionTipoFirma

initFirmaConFIEL.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaConFIEL.url=initFirmaConFIEL

initFirmaConIMSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaConIMSS.url=initFirmaConIMSS

resultadoFirmaDigital.(class)=org.springframework.web.servlet.view.tiles2.TilesView
resultadoFirmaDigital.url=resultadoFirmaDigital

solicitudesPersonaFisica.(class)=org.springframework.web.servlet.view.JstlView
solicitudesPersonaFisica.url=/WEB-INF/views/solicitud/solicitudesPersonaFisica.jsp


solicitudesPersonaMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitudesPersonaMoral.url=solicitudesPersonaMoral

#Estado de Adeudo
prepararEdoAdeudo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prepararEdoAdeudo.url = prepararEdoAdeudo

reporteAdeudoTipoCobro.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
reporteAdeudoTipoCobro.url=/WEB-INF/reporteTemplates/estadoCuentaTrabajoAdeudoTipoCobro_1.jasper
reporteAdeudoTipoCobro.reportDataKey=adeudoKey

reporteAdeudoTipoCobroRCV.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
reporteAdeudoTipoCobroRCV.url=/WEB-INF/reporteTemplates/estadoCuentaTrabajoAdeudoTipoCobroRCV_1.jasper
reporteAdeudoTipoCobroRCV.reportDataKey=adeudoKey

reporteAdeudoSituacionCobro.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
reporteAdeudoSituacionCobro.url=/WEB-INF/reporteTemplates/estadoCuentaTrabajoAdeudoSituacionCobro_1.jasper
reporteAdeudoSituacionCobro.reportDataKey=adeudoKey

reporteAdeudoSituacionCobroRCV.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
reporteAdeudoSituacionCobroRCV.url=/WEB-INF/reporteTemplates/estadoCuentaTrabajoAdeudoSituacionCobroRCV_1.jasper
reporteAdeudoSituacionCobroRCV.reportDataKey=adeudoKey

#CFDI
obtenerListaComprobanteFiscal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obtenerListaComprobanteFiscal.url=obtenerListaComprobanteFiscal

errorReporte.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorReporte.url = errorReporte

#Wzards
wizardGraficas.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardGraficas.url = wizardGraficas

wizardComprobanteFiscalInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardComprobanteFiscalInit.url = wizardComprobanteFiscalInit

wizardComprobanteFiscalContenido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardComprobanteFiscalContenido.url = wizardComprobanteFiscalContenido

comprobanteFiscalXmlFormat.(class)=mx.gob.imss.ctirss.delta.cobranza.web.utils.GenericXmlAbstractView
comprobanteFiscalXmlFormat.fileName=comprobanteFiscal

#Widgets
widgetReporteCobranzaInit.(class)=org.springframework.web.servlet.view.JstlView
widgetReporteCobranzaInit.url=/WEB-INF/views/widget/cobranza/inicial.jsp

widgetReporteCobranza.(class)=org.springframework.web.servlet.view.JstlView
widgetReporteCobranza.url=/WEB-INF/views/widget/cobranza/contenido.jsp


widgetComprobanteFiscalInit.(class)=org.springframework.web.servlet.view.JstlView
widgetComprobanteFiscalInit.url=/WEB-INF/views/widget/comprobanteFiscal/inicial.jsp

widgetComprobanteFiscalContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetComprobanteFiscalContenido.url=/WEB-INF/views/widget/comprobanteFiscal/contenido.jsp

#Portlet de Estado de adeudo
portletGraficasInit.(class)=org.springframework.web.servlet.view.JstlView
portletGraficasInit.url=/WEB-INF/views/portlet/grafica/inicial.jsp

portletGraficasContenido.(class)=org.springframework.web.servlet.view.JstlView
portletGraficasContenido.url=/WEB-INF/views/portlet/grafica/contenido.jsp

#Test
ingresarDatosPatronTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
ingresarDatosPatronTest.url = ingresarDatosPatronTest

############# WIZARDS CARTA NO ADEUDO
prepararCartaNoAdeudo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prepararCartaNoAdeudo.url = prepararCartaNoAdeudo
errorCartaNoAdeudo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorCartaNoAdeudo.url = errorCartaNoAdeudo