package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.DelegacionDTO;

/**
 * RocSubdelegacion generated by hbm2java
 */
@Entity
@Table(name = "DIC_DELEGACION", schema = "MGPROC01")
@Transactional
public class RocDelegacion implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 823512179138959193L;
	
	private Long cveDelegacion;
	private String nomDelegacion;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocDelegacion() {
	}


	public RocDelegacion(Long cveDelegacion) {
		this.cveDelegacion = cveDelegacion;
	}
	
	
	public RocDelegacion(Long cveDelegacion, String nomDelegacion,Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {	
		this.cveDelegacion = cveDelegacion;
		this.nomDelegacion = nomDelegacion;		
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id

	@Column(name = "CVE_ID_DELEGACION", unique = true, nullable = false)
	public Long getCveDelegacion() {
		return this.cveDelegacion;
	}

	public void setCveDelegacion(Long cveDelegacion) {
		this.cveDelegacion = cveDelegacion;
	}

	@Column(name = "DES_DELEG", length = 80)
	public String getNomDelegacion() {
		return this.nomDelegacion;
	}

	public void setNomDelegacion(String nomDelegacion) {
		this.nomDelegacion = nomDelegacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	
	public DelegacionDTO toConvertDelegacionDTO(){
		DelegacionDTO delegacionDTO = new DelegacionDTO();
		
		delegacionDTO.setCveDelegacion(this.getCveDelegacion());
		delegacionDTO.setNomDelegacion(this.getNomDelegacion());
		
		return delegacionDTO;
	}
	
}
