 	package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.MotivoDTO;


/**
 * RocTipoObra generated by hbm2java
 */
@Entity
@Table(name = "ROC_MOTIVO", schema = "MGPROC01")
@Transactional
public class RocMotivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4943022634302990066L;
	
	private Long cveMotivo;
	private String desMotivo;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocMotivo() {
	}

	public RocMotivo(Long cveMotivo) {
		this.cveMotivo = cveMotivo;
	}


	public RocMotivo(Long cveMotivo, String desMotivo, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveMotivo = cveMotivo;
		this.desMotivo = desMotivo;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
		// this.rotInformacionObras = rotInformacionObras;
	}

	@Id

	@Column(name = "CVE_ID_MOTIVO", unique = true, nullable = false)
	public Long getCveMotivo() {
		return this.cveMotivo;
	}

	public void setCveMotivo(Long cveMotivo) {
		this.cveMotivo = cveMotivo;
	}

	@Column(name = "DES_MOTIVO", length = 80)
	public String getDesMotivo() {
		return this.desMotivo;
	}

	public void setDesMotivo(String desMotivo) {
		this.desMotivo = desMotivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	public MotivoDTO toConvertMotivoDTO(){
		MotivoDTO motivoDTO = new MotivoDTO();
		
		motivoDTO.setCveMotivo(this.getCveMotivo());
		motivoDTO.setDesMotivo(this.getDesMotivo());
		
		return motivoDTO;
	}

}
