<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>mx.gob.imss.ctirss.clienteswebservices.renapo.curp</groupId>
	<artifactId>ClientesWebservices-renapo-curp</artifactId>
	<name>ClientesWebservices-renapo-curp</name>
	<version>${revision}</version>
	<url>http://maven.apache.org</url>
	<parent>
		<groupId>mx.gob.imss.ctirss.clienteswebservices</groupId>
		<artifactId>ClientesWebservices</artifactId>
			<version>2.2</version>
	</parent>
	
	<properties>
		<revision>${mvn.ws.cliente.version}</revision>
		<delta.framework.version>${mvn.delta.framework.version}</delta.framework.version>
	</properties>
	
	<dependencies>
		
		<!-- Excepcion de WS renapo -->
		<!--
		<dependency>
		   <groupId>com.sun.xml.ws</groupId>
		   <artifactId>jaxws-rt</artifactId>
		   <version>2.2.6</version>
		   		
		</dependency>
		-->
		<!-- Ejecucion de Pruebas -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		
		<!-- Logger -->
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.16</version>			
		</dependency>
		
		<!-- Dependencia del Proyecto Base DELTA - Framework Base -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-framework-base</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>	
		</dependency>
		
		<!-- Dependencia del Proyecto Base DELTA - Modelo Negocio -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>				
		</dependency>
		
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>

		
	</dependencies>
	
	<profiles>
		<profile>
			<id>compile-stage</id>
			<properties>
				<mvn.ws.cliente.version>2.3-QA</mvn.ws.cliente.version>
				<delta.framework.version>2.6-SNAPSHOT</delta.framework.version>
			</properties>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>prepare-package</phase>
								<configuration>
									<tasks>
										<replace token="${mvn.server.ws.renapo}" value="172.16.23.227" dir="target/classes">
											<include name="**/*.xml" />
										</replace>
									</tasks>
								</configuration>
								<goals>
									<goal>run</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<id>compile-prod</id>
			<properties>
				<mvn.ws.cliente.version>2.3</mvn.ws.cliente.version>
				<delta.framework.version>2.6</delta.framework.version>
			</properties>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>prepare-package</phase>
								<configuration>
									<tasks>
										<replace token="${mvn.server.ws.renapo}" value="172.16.23.207" dir="target/classes">
											<include name="**/*.xml" />
										</replace>
									</tasks>
								</configuration>
								<goals>
									<goal>run</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>compile-prod-ipicit</id>
			<properties>
				<mvn.ws.cliente.version>2.3-IPICYT</mvn.ws.cliente.version>
				<delta.framework.version>2.6</delta.framework.version>
			</properties>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>prepare-package</phase>
								<configuration>
									<tasks>
										<replace token="${mvn.server.ws.renapo}" value="10.102.2.164" dir="target/classes">
											<include name="**/*.xml" />
										</replace>
									</tasks>
								</configuration>
								<goals>
									<goal>run</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	
	
</project>