
package mx.gob.imss.ws.vo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Modalidad33VO", targetNamespace = "http://vo.ws.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Modalidad33VO {


    /**
     * 
     * @param idAsignacionNSS
     * @return
     *     returns mx.gob.imss.ws.vo.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConsultaMod33", targetNamespace = "http://vo.ws.imss.gob.mx/", className = "mx.gob.imss.ws.vo.GetConsultaMod33")
    @ResponseWrapper(localName = "getConsultaMod33Response", targetNamespace = "http://vo.ws.imss.gob.mx/", className = "mx.gob.imss.ws.vo.GetConsultaMod33Response")
    public Return getConsultaMod33(
        @WebParam(name = "idAsignacionNSS", targetNamespace = "")
        String idAsignacionNSS);

}
