//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class CategoriaPregunta  extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Long idCategoriaPregunta;
	protected String descripcion;
	protected String noPreguntas;

	/**
	 * Gets the value of the idCategoriaPregunta property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getIdCategoriaPregunta() {
		return idCategoriaPregunta;
	}

	/**
	 * Sets the value of the idCategoriaPregunta property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setIdCategoriaPregunta(Long value) {
		this.idCategoriaPregunta = value;
	}

	/**
	 * Gets the value of the descripcion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * Sets the value of the descripcion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescripcion(String value) {
		this.descripcion = value;
	}

	/**
	 * Gets the value of the noPreguntas property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNoPreguntas() {
		return noPreguntas;
	}

	/**
	 * Sets the value of the noPreguntas property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNoPreguntas(String value) {
		this.noPreguntas = value;
	}

}
