//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

import mx.gob.imss.ctirss.delta.model.asegurado.AsignacionNSS;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Fisica;

@XmlRootElement(name = "Derechohabiente")
public class Derechohabiente extends Fisica implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Long idPersonaDerechohabiente;
	protected Fisica persona;
	protected Date fechaRegistroAlta;
	protected Date fechaRegistroBaja;
	protected Date fechaRegistroActualizado;
	protected String refMatriculaUsuarioAlta;
	protected String expedienteElectronico;
	protected AsignacionNSS asignacionNSS;

	
	public Derechohabiente(){
		
	}
	
	public Derechohabiente(Long idPersona){
		this.setIdPersona(idPersona);
	}
	
	public Long getIdPersonaDerechohabiente() {
		return idPersonaDerechohabiente;
	}

	public void setIdPersonaDerechohabiente(Long idPersonaDerechohabiente) {
		this.idPersonaDerechohabiente = idPersonaDerechohabiente;
	}

	public Date getFechaRegistroAlta() {
		return fechaRegistroAlta;
	}

	public void setFechaRegistroAlta(Date fechaRegistroAlta) {
		this.fechaRegistroAlta = fechaRegistroAlta;
	}

	public Date getFechaRegistroBaja() {
		return fechaRegistroBaja;
	}

	public void setFechaRegistroBaja(Date fechaRegistroBaja) {
		this.fechaRegistroBaja = fechaRegistroBaja;
	}

	public Date getFechaRegistroActualizado() {
		return fechaRegistroActualizado;
	}

	public void setFechaRegistroActualizado(Date fechaRegistroActualizado) {
		this.fechaRegistroActualizado = fechaRegistroActualizado;
	}

	/**
	 * @return the agregadoAfiliacion
	 */
//	public String getAgregadoAfiliacion() {
//		return agregadoAfiliacion;
//	}
//
//	/**
//	 * @param agregadoAfiliacion the agregadoAfiliacion to set
//	 */
//	public void setAgregadoAfiliacion(String agregadoAfiliacion) {
//		this.agregadoAfiliacion = agregadoAfiliacion;
//	}

	/**
	 * @return the expedienteElectronico
	 */
	public String getExpedienteElectronico() {
		return expedienteElectronico;
	}

	/**
	 * @param expedienteElectronico the expedienteElectronico to set
	 */
	public void setExpedienteElectronico(String expedienteElectronico) {
		this.expedienteElectronico = expedienteElectronico;
	}

	/**
	 * @return the persona
	 */
	public Fisica getPersona() {
		return persona;
	}

	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Fisica persona) {
		this.persona = persona;
	}

	/**
	 * @return the refMatriculaUsuarioAlta
	 */
	public String getRefMatriculaUsuarioAlta() {
		return refMatriculaUsuarioAlta;
	}

	/**
	 * @param refMatriculaUsuarioAlta the refMatriculaUsuarioAlta to set
	 */
	public void setRefMatriculaUsuarioAlta(String refMatriculaUsuarioAlta) {
		this.refMatriculaUsuarioAlta = refMatriculaUsuarioAlta;
	}

	/**
	 * @return the asignacionNSS
	 */
	public AsignacionNSS getAsignacionNSS() {
		return asignacionNSS;
	}

	/**
	 * @param asignacionNSS the asignacionNSS to set
	 */
	public void setAsignacionNSS(AsignacionNSS asignacionNSS) {
		this.asignacionNSS = asignacionNSS;
	}

}
