welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

initRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initRiss.url=initRiss

confirmarDatosRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmarDatosRiss.url=confirmarDatosRiss

confirmarDatosAdicionalesRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmarDatosAdicionalesRiss.url=confirmarDatosAdicionalesRiss

resultadoValidacionRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
resultadoValidacionRiss.url=resultadoValidacionRiss

concluirRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
concluirRiss.url=concluirRiss