#inidicador para verificar las opciones en un archivo properties
busqueda_properties = 1

url_archivo =  file:/share/oracle/zapdir01_domain/zapdir_cluster1/properties/opciones_ventanilla.properties

#opciones menu principal ventanilla
ind_alta_patronal_PF = 1
ind_alta_patronal_PM = 1
ind_alta_socio = 1
ind_baja_socio = 1
ind_baja_RL_PF = 1
ind_baja_RL_PM = 1
ind_IVRO_individual = 1
ind_IVRO_domestico = 1
ind_alta_representado_legal = 1
ind_recuperacion_patron = 1
ind_carta_no_adeudo_pf_32d = 1
ind_carta_no_adeudo_pm_32d = 1

#menu_acciones_identidad.
ind_actualizar_datos = 1
ind_actualizar_domicilio = 1
ind_actualizar_medios = 1

#menu_acciones_sujeto
ind_actualizar_datos_sujeto = 1