<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	targetNamespace="http://www.serviciosdigitales.imss.gob.mx/certificacionInactividadPagoParcialidades"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cip="http://www.serviciosdigitales.imss.gob.mx/certificacionInactividadPagoParcialidades">

	<xs:element name="certificacionInactividadRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nss" maxOccurs="1" minOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{11}"></xs:pattern>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="curp" maxOccurs="1" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="18" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="prestacionSolicitada" maxOccurs="1"
					minOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="2" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="numeroResolucion" maxOccurs="1"
					minOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{6}"></xs:pattern>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="certificacionInactividadResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="folioSolicitud" type="xs:string"
					maxOccurs="1" minOccurs="1">
				</xs:element>
				<xs:element name="certificacionInactividad" type="xs:string"
					maxOccurs="1" minOccurs="1">
				</xs:element>
				<xs:element name="exito" type="xs:unsignedShort"
					maxOccurs="1" minOccurs="1" />
				<xs:element name="claveError" type="xs:unsignedShort" />
				<xs:element name="descripcion">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="50" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>