
package mx.gob.imss.cit.clienteswebservices.boveda;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "tspiPortService", targetNamespace = "http://www.openuri.org/", wsdlLocation = "classpath:WsBovedaIMSS-IPICYT.wsdl")
public class TspiPortService
    extends Service
{

    private final static URL TSPIPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.cit.clienteswebservices.boveda.TspiPortService.class.getName());
    private final static int SERVICE_TIME_OUT = 30000;
    private final static int CONECTION_TIME_OUT = 10000;
    
    static {
        URL url = null;
        try {
           /**
        	URL baseUrl;
            baseUrl = mx.gob.imss.cit.clienteswebservices.boveda.TspiPortService.class.getResource(".");
            url = new URL(baseUrl, "http://10.102.41.200/alfresco-ws-1.0/servicios/gdocumental.wsdl");
            **/
        	url = Thread.currentThread().getContextClassLoader().getResource("WsBovedaIMSS-IPICYT.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: ', retrying as a local file" + url);
            logger.warning(e.getMessage());
        }
        TSPIPORTSERVICE_WSDL_LOCATION = url;
    }

    public TspiPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TspiPortService() {
        super(TSPIPORTSERVICE_WSDL_LOCATION, new QName("http://www.openuri.org/", "tspiPortService"));
    }

    /**
     * 
     * @return
     *     returns TspiPort
     */
    @WebEndpoint(name = "tspiPortSoap11")
    public TspiPort getTspiPortSoap11() {
    	TspiPort ws = super.getPort(new QName("http://www.openuri.org/", "tspiPortSoap11"), TspiPort.class);
        ((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", SERVICE_TIME_OUT);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", CONECTION_TIME_OUT);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", SERVICE_TIME_OUT);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", CONECTION_TIME_OUT);
      	return ws;
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TspiPort
     */
    @WebEndpoint(name = "tspiPortSoap11")
    public TspiPort getTspiPortSoap11(WebServiceFeature... features) {
    	TspiPort ws =super.getPort(new QName("http://www.openuri.org/", "tspiPortSoap11"), TspiPort.class, features);
        ((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", SERVICE_TIME_OUT);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", CONECTION_TIME_OUT);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", SERVICE_TIME_OUT);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", CONECTION_TIME_OUT);
      	return ws;
    }

}
