
package mx.gob.imss.cit.ws.cuentaindividualhistorico.cliente;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSHistoricoCentralSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", wsdlLocation = "/wsdl/WSHistoricoCentralSISEC.wsdl")
public class WSHistoricoCentralSISEC_Service
    extends Service
{

    private final static URL WSHISTORICOCENTRALSISEC_WSDL_LOCATION;
    private final static WebServiceException WSHISTORICOCENTRALSISEC_EXCEPTION;
    private final static QName WSHISTORICOCENTRALSISEC_QNAME = new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSHistoricoCentralSISEC");

    static {
        WSHISTORICOCENTRALSISEC_WSDL_LOCATION = mx.gob.imss.cit.ws.cuentaindividualhistorico.cliente.WSHistoricoCentralSISEC_Service.class.getResource("/wsdl/WSHistoricoCentralSISEC.wsdl");
        WebServiceException e = null;
        if (WSHISTORICOCENTRALSISEC_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/WSHistoricoCentralSISEC.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSHISTORICOCENTRALSISEC_EXCEPTION = e;
    }

    public WSHistoricoCentralSISEC_Service() {
        super(__getWsdlLocation(), WSHISTORICOCENTRALSISEC_QNAME);
    }

    public WSHistoricoCentralSISEC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WSHistoricoCentralSISEC
     */
    @WebEndpoint(name = "WSHistoricoCentralSISECPort")
    public WSHistoricoCentralSISEC getWSHistoricoCentralSISECPort() {
        return super.getPort(new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSHistoricoCentralSISECPort"), WSHistoricoCentralSISEC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSHistoricoCentralSISEC
     */
    @WebEndpoint(name = "WSHistoricoCentralSISECPort")
    public WSHistoricoCentralSISEC getWSHistoricoCentralSISECPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSHistoricoCentralSISECPort"), WSHistoricoCentralSISEC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSHISTORICOCENTRALSISEC_EXCEPTION!= null) {
            throw WSHISTORICOCENTRALSISEC_EXCEPTION;
        }
        return WSHISTORICOCENTRALSISEC_WSDL_LOCATION;
    }

}
