################################
# Propiedades de conexion a BD #
################################

jdbc.driverClassName=oracle.jdbc.xa.client.OracleXADataSource
#jdbc.databaseurl=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.8.136) (PORT=1630))(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.8.137) (PORT=1630))(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.8.138) (PORT=1630))(CONNECT_DATA=(SERVICE_NAME=serdg01)))
jdbc.databaseurl=jdbc:oracle:thin:@172.16.8.134:1631:bdtu1
jdbc.username=MGPBDTU1
jdbc.password=MGPBDTU1
