package mx.gob.imss.csdiss.sdroc.dto;

/**
 * RotInformacionPatron generated by hbm2java
 */
public class InformacionPatronDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6791764168927883111L;
	
	private Long cveInformacionPatron;
	private TipoPatronDTO tipoPatronDTO;
	private TipoPersonaDTO tipoPersonaDTO;
	private String cveRfc;
	private String cveRegPatronal;
	private String refApellidoPaterno;
	private String refApellidoMaterno;
	private String nomPatron;
	private String refRazonSocial;

	public InformacionPatronDTO() {
	}

	public InformacionPatronDTO(Long cveInformacionPatron) {
		this.cveInformacionPatron = cveInformacionPatron;
	}


	public InformacionPatronDTO(Long cveInformacionPatron, TipoPatronDTO tipoPatronDTO, TipoPersonaDTO tipoPersonaDTO,
			String cveRfc, String cveRegPatronal, String refApellidoPaterno, String refApellidoMaterno,
			String nomPatron, String refRazonSocial) {

		this.cveInformacionPatron = cveInformacionPatron;
		this.tipoPatronDTO = tipoPatronDTO;
		this.tipoPersonaDTO = tipoPersonaDTO;
		this.cveRfc = cveRfc;
		this.cveRegPatronal = cveRegPatronal;
		this.refApellidoPaterno = refApellidoPaterno;
		this.refApellidoMaterno = refApellidoMaterno;
		this.nomPatron = nomPatron;
		this.refRazonSocial = refRazonSocial;
	}

	public Long getCveInformacionPatron() {
		return this.cveInformacionPatron;
	}

	public void setCveInformacionPatron(Long cveInformacionPatron) {
		this.cveInformacionPatron = cveInformacionPatron;
	}

	public TipoPatronDTO getTipoPatronDTO() {
		return this.tipoPatronDTO;
	}

	public void setTipoPatronDTO(TipoPatronDTO tipoPatronDTO) {
		this.tipoPatronDTO = tipoPatronDTO;
	}

	public TipoPersonaDTO getTipoPersonaDTO() {
		return this.tipoPersonaDTO;
	}

	public void setTipoPersonaDTO(TipoPersonaDTO tipoPersonaDTO) {
		this.tipoPersonaDTO = tipoPersonaDTO;
	}

	public String getCveRfc() {
		return this.cveRfc;
	}

	public void setCveRfc(String cveRfc) {
		this.cveRfc = cveRfc;
	}

	public String getCveRegPatronal() {
		return this.cveRegPatronal;
	}

	public void setCveRegPatronal(String cveRegPatronal) {
		this.cveRegPatronal = cveRegPatronal;
	}

	public String getRefApellidoPaterno() {
		return this.refApellidoPaterno;
	}

	public void setRefApellidoPaterno(String refApellidoPaterno) {
		this.refApellidoPaterno = refApellidoPaterno;
	}

	public String getRefApellidoMaterno() {
		return this.refApellidoMaterno;
	}

	public void setRefApellidoMaterno(String refApellidoMaterno) {
		this.refApellidoMaterno = refApellidoMaterno;
	}

	public String getNomPatron() {
		return this.nomPatron;
	}

	public void setNomPatron(String nomPatron) {
		this.nomPatron = nomPatron;
	}

	public String getRefRazonSocial() {
		return this.refRazonSocial;
	}

	public void setRefRazonSocial(String refRazonSocial) {
		this.refRazonSocial = refRazonSocial;
	}

}
