<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>mx.gob.imss.ctirss.clienteswebservices</groupId>
		<artifactId>ClientesWebservices</artifactId>
		<version>2.2</version>
	</parent>
	<groupId>mx.gob.imss.ctirss.clienteswebservices.beneficiarios</groupId>
	<artifactId>ClientesWebservices-derechohabientes</artifactId>
	<name>ClientesWebservices-derechohabientes</name>
	<url>http://maven.apache.org</url>
	<version>2.3</version>
	
	<dependencies>
		
		<dependency>
		   <groupId>com.sun.xml.ws</groupId>
		   <artifactId>jaxws-rt</artifactId>
		   <version>2.2.6</version><!-- <version>2.1.3</version> -->
		   <scope>provided</scope>		
		</dependency>
		
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb-api</artifactId>
			<version>3.0</version>
			<scope>provided</scope>
		</dependency>
		
		<!-- Ejecucion de Pruebas -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		
		<!-- Logger -->
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${org.log4j.version}</version>
			<scope>provided</scope>			
		</dependency>
		
		<!-- Dependencia del Proyecto Base DELTA - Framework Base -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-framework-base</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
			<scope>provided</scope>	
		</dependency>
		
		<!-- Dependencia del Proyecto Base DELTA - Modelo Negocio -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
			<scope>provided</scope>				
		</dependency>
		
	</dependencies>
		<profiles>
		<profile>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<id>compile-stage</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>prepare-package</phase>
								<configuration>
									<tasks>
										<replace token="${mvn.url.ws.servdhab}" value="http://adodigital.imss.gob.mx" dir="target/classes">
											<include name="**/*.wsdl" />
										</replace>
										<replace token="${mvn.url.ws.pat}" value="http://11.254.13.146:7001/WSConsPatronesVigXAsig/patrones" dir="target/classes">
											<include name="**/*.wsdl" />
										</replace>
                                        <replace token="${mvn.url.ws.vigencia}" value="http://adodigital.imss.gob.mx" dir="target/classes">
                                            <include name="**/*.wsdl" />
                                        </replace>
										<replace token="${mvn.log.level.info}" value="info" dir="target/classes">
											<include name="**/log4j.xml" />
										</replace>
										<replace token="${mvn.log.level.warn}" value="warn" dir="target/classes">
											<include name="**/log4j.xml" />
										</replace>
										<replace token="${mvn.log.level.trace}" value="trace" dir="target/classes">
											<include name="**/log4j.xml" />
										</replace>
									</tasks>
								</configuration>
								<goals>
									<goal>run</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>compile-prod</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>prepare-package</phase>
								<configuration>
									<tasks>
										<replace token="${mvn.url.ws.servdhab}" value="http://vigenciaderechos.imss.gob.mx" dir="target/classes">
											<include name="**/*.wsdl" />
										</replace>
										<replace token="${mvn.url.ws.pat}" value="http://adodigital.imss.gob.mx/WSConsPatronesVigXAsig/patrones/ConsPatronesVigXAsigService" dir="target/classes">
											<include name="**/*.wsdl" />
										</replace>
                                        <replace token="${mvn.url.ws.vigencia}" value="http://172.16.23.113" dir="target/classes">
                                            <include name="**/*.wsdl" />
                                        </replace>
										<replace token="${mvn.log.level.info}" value="error" dir="target/classes">
											<include name="**/log4j.xml" />
										</replace>
										<replace token="${mvn.log.level.warn}" value="error" dir="target/classes">
											<include name="**/log4j.xml" />
										</replace>
										<replace token="${mvn.log.level.trace}" value="error" dir="target/classes">
											<include name="**/log4j.xml" />
										</replace>
									</tasks>
								</configuration>
								<goals>
									<goal>run</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
