
package mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsimsscurpSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsimsscurpSoap {


    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente.CurpKioscosBean
     */
    @WebMethod(action = "http://www.openuri.org/consultaCURP")
    @WebResult(name = "consultaCURPResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "consultaCURP", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente.ConsultaCURP")
    @ResponseWrapper(localName = "consultaCURPResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente.ConsultaCURPResponse")
    public CurpKioscosBean consultaCURP(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        ParametrosConsulta entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente.CurpKioscosBean
     */
    @WebMethod(operationName = "ConsultaDatosCURP", action = "http://www.openuri.org/ConsultaDatosCURP")
    @WebResult(name = "ConsultaDatosCURPResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "ConsultaDatosCURP", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente.ConsultaDatosCURP")
    @ResponseWrapper(localName = "ConsultaDatosCURPResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.ctirss.sso.admonusuarios.renapo.cliente.ConsultaDatosCURPResponse")
    public CurpKioscosBean consultaDatosCURP(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        String entrada);

}
