<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
 
 <groupId>mx.gob.imss.ctirss.delta.gestion.documento.probatorio</groupId>
  <artifactId>gestionDocumentoProbatorio</artifactId>
  <packaging>pom</packaging>
  <version>2.4-SNAPSHOT</version>
  
<name>Modulo  Delta de gestion de documentos  IMSS</name>
  <url>http://www.imss.gob.mx/instituto/Directorio/ctirss.htm</url>
  
  
  
  
  <properties>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<org.slf4j.version>1.6.1</org.slf4j.version>
		<org.hibernate.version>3.6.9.Final</org.hibernate.version>
		<endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
		<org.springframework.version>3.0.5.RELEASE</org.springframework.version>
		<tiles.framework.version>2.2.1</tiles.framework.version>

		<delta.framework.version>2.6-SNAPSHOT</delta.framework.version>
		<delta.framework.comboSelect>2.0-SNAPSHOT</delta.framework.comboSelect>
		<delta.documentos.probatorios>2.4-SNAPSHOT</delta.documentos.probatorios>
		<gestion.solicitud.version>2.2-SNAPSHOT</gestion.solicitud.version>
	</properties>
  
  
  
  <build>
  
  
  
  
  <!-- To define the plugin version in your parent POM -->
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.0</version>
        </plugin>
		<plugin>
		  <groupId>org.apache.maven.plugins</groupId>
		  <artifactId>maven-surefire-plugin</artifactId>
		    <configuration>
			<skipTests>true</skipTests>
		  </configuration>
		</plugin>
      </plugins>
    </pluginManagement>
  
 
  
  	<plugins>
  	
  	
  
  	
    	<!-- for use JVM 1.6 
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>-->
      
      <!-- Relase Plugin-->
		<plugin>
        	<groupId>org.apache.maven.plugins</groupId>
        	<artifactId>maven-release-plugin</artifactId>
	        <version>2.3.2</version>
    	    <configuration>
        		<tagBase>http://11.254.16.21/svn/base_arquitectura_delta/codigo/tags/</tagBase>
		        <tag>${project.artifactId}-${project.version}</tag>          	   
        	</configuration>
    	</plugin>
    	
  
    </plugins>
<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>			
				<artifactId>wagon-ftp</artifactId>
			</extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>			
				<artifactId>wagon-webdav</artifactId>
			</extension>
		</extensions>
  </build>

  
  
  
   
 <repositories>
  	<repository>
  		<id>ctirss</id>
  		<name>CTIRSS repository</name>
  		<layout>default</layout>
  		<url>http://172.16.5.134:8080/repository/repo/</url>
  		<snapshots>
  			<enabled>true</enabled>
  		</snapshots>
  	</repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>ctirss</id>
      <name>CTIRSS repository</name>
      <url>http://172.16.5.134:8080/repository/repo/</url>
      <layout>default</layout>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
    </pluginRepository>
  </pluginRepositories>

<distributionManagement>
  <!-- use the following if you're not using a snapshot version. -->
  <repository>
    <id>ctirss-archiva</id>
    <name>CTIRSS Repository Name</name>
    <url>dav:http://172.16.5.134:8080/repository/repo/</url>
    
  </repository>
    
  <snapshotRepository>
    <id>ctirss-archiva</id>
    <name>CTIRSS Repository Name</name>
        <url>dav:http://172.16.5.134:8080/repository/repo/</url>
  </snapshotRepository>

</distributionManagement>


	<scm>
			  <connection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_documentos_probatorios/gestionDocumentoProbatorio/</connection>
			  <developerConnection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_documentos_probatorios/gestionDocumentoProbatorio/</developerConnection>
			  <url>http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_documentos_probatorios/gestionDocumentoProbatorio/</url>
	</scm>

  <modules>
    <module>gestionDocumentoProbatorio-interfaces-negocio</module>
    <module>gestionDocumentoProbatorio-servicios-negocio-ejb</module>
    <module>gestionDocumentoProbatorio-web</module>
    <module>gestionDocumentoProbatorio-packing</module>
  </modules>
</project>
