#Datos del ambiente de desarrollo QA
service.provider.url=${mvn.web.app.service.provider.url}
service.security.principal=${mvn.web.app.service.provider.principal}
service.security.credentials=${mvn.web.app.service.provider.credentials}
###url del osb para consultar servicio de foto
service.ws.osb.url=http://osbserviciosdigitales.imss.gob.mx