<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>gestionSeguroVoluntario-interfaces-negocio</artifactId>
  <name>Modulo de Interfaces de Negocio DELTA</name>
  <url>http://maven.apache.org</url>
  <packaging>jar</packaging>

  <parent>
    <artifactId>gestionSeguroVoluntario</artifactId>
    <groupId>mx.gob.imss.ctirss.delta.gestion.seguroVoluntario</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <properties>
    <project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <!-- INICIO DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->
    <!-- Dependencia del Framework DELTA BASE IMSS -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta</groupId>
      <artifactId>delta-framework-base</artifactId>
      <version>${delta.framework.version}</version>
      <type>jar</type>
    </dependency>

    <!-- Dependencia del Proyecto de Objetos de modelo DELTA IMSS -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta</groupId>
      <artifactId>imssdigital-modelo</artifactId>
      <version>${delta.framework.version}</version>
      <type>jar</type>
    </dependency>
    
    <dependency>
	    <artifactId>delta-modelo-negocio</artifactId>
	    <groupId>mx.gob.imss.ctirss.delta</groupId>
	    <version>2.6-SNAPSHOT</version>
	    <scope>provided</scope>
  	 </dependency>
    
    
    <!-- FIN DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->
    <!-- Dependencias del modelo de cotizacio, este es temporal en los que obtenemos los modelos finales -->
<!--     <dependency> -->
<!--       <groupId>mx.gob.imss.ctirss.delta.gestion.motorCalculo</groupId> -->
<!--       <artifactId>gestionMotorCalculo-interfaces-negocio</artifactId> -->
<!--       <version>1.0-SNAPSHOT</version> -->
<!--     </dependency> -->

 	 

    <dependency>
      <groupId>javax.ejb</groupId>
      <artifactId>ejb-api</artifactId>
      <version>3.0</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.hibernate.javax.persistence</groupId>
      <artifactId>hibernate-jpa-2.0-api</artifactId>
      <version>1.0.1.Final</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-ejb-plugin</artifactId>
        <version>2.3</version>
        <configuration>
          <ejbVersion>3.0</ejbVersion>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.1</version>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <outputDirectory>${endorsed.dir}</outputDirectory>
              <silent>true</silent>
              <artifactItems>
                <artifactItem>
                  <groupId>javax</groupId>
                  <artifactId>javaee-endorsed-api</artifactId>
                  <version>6.0</version>
                  <type>jar</type>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself. -->
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <versionRange>[2.1,)</versionRange>
                    <goals>
                      <goal>copy</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
