
openam.url.token = http://ssoimssdigd.imss.gob.mx:7001/openam_10.0.0/identity/authenticate?
openam.url.datos = http://ssoimssdigd.imss.gob.mx:7001/openam_10.0.0/identity/attributes?subjectid=
user.openam = username=
pwd.openam = password=

