<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://mx.gob.imss.delta.global.service/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="notificacionRequest">
	  <xs:complexType>
	    <xs:sequence>
                       <xs:element minOccurs="1" name="folioSolicitud" nillable="true" type="xs:string"/>
	      <xs:element minOccurs="1" name="idTipoTramite" nillable="true" type="xs:int"/>
	      <xs:element minOccurs="1" name="idPersona" nillable="true" type="xs:long"/>
	      <xs:element minOccurs="1" name="idTipoPersona" nillable="true" type="xs:long"/>
	      <xs:element name="numeroRegistroPatronal" type="xs:string"/>
                         <xs:element name="mensaje" type="xs:string"/>
                         <xs:element minOccurs="1" name="idTipoSolicitud" nillable="true" type="xs:int"/>
                        <xs:element name="correoNotificacion" type="xs:string"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
</xs:schema>