#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp

 
#Tiles redirect

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

#===== Portales ====== 

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home


#===== Generales ====== 

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

#Widgets
widgetReporteCobranzaInit.(class)=org.springframework.web.servlet.view.JstlView
widgetReporteCobranzaInit.url=/WEB-INF/views/widget/cobranza/inicial.jsp


widgetReporteCobranza.(class)=org.springframework.web.servlet.view.JstlView
widgetReporteCobranza.url=/WEB-INF/views/widget/cobranza/contenido.jsp


widgetPortletCobranza.(class)=org.springframework.web.servlet.view.JstlView
widgetPortletCobranza.url=/WEB-INF/views/portlet/correccion/inicial.jsp

widgetPortletCorreccion.(class)=org.springframework.web.servlet.view.JstlView
widgetPortletCorreccion.url=/WEB-INF/views/portlet/correccion/contenido.jsp

