//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 06:59:28 PM CDT 
//


package mx.gob.imss.ctirss.delta.framework.base.model;

import java.io.Serializable;
import java.util.Map;
import java.util.TreeMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EmailPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmailPayloadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromAccountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReplyToAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Bcc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="EmailPayload", namespace="http://mx.gob.imss.email.model")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailPayloadType", propOrder = {
    "fromAccountName",
    "to",
    "replyToAddress",
    "subject",
    "content",
    "contentType",
    "cc",
    "bcc",
    "attachment",
    "attachments",
    "parameters",
    "extraparameters"
})
public class EmailPayloadType implements Serializable {

   /**
	 * 
	 */
	private static final long serialVersionUID = -5986216763772908477L;
	@XmlElement(name = "FromAccountName")
    protected String fromAccountName;
    @XmlElement(name = "To")
    protected String to;
    @XmlElement(name = "ReplyToAddress")
    protected String replyToAddress;
    @XmlElement(name = "Subject", required = true)
    protected String subject;
    @XmlElement(name = "Content", required = true)
    protected String content;
    @XmlElement(name = "ContentType")
    protected String contentType;
    @XmlElement(name = "Cc")
    protected String cc;
    @XmlElement(name = "Bcc")
    protected String bcc;
    @XmlElement(name = "Attachment")
    protected AttachmentContent attachment;
    @XmlElement(name = "Attachments")
    protected AttachmentContent[] attachments;
    @XmlElement(name = "Parameters")
    @XmlJavaTypeAdapter(XmlMapAdapter.class)
    protected Map<String, String> parameters;
    @XmlElement(name = "Extraparameters")
    @XmlJavaTypeAdapter(XmlMapAdapter.class)
	protected Map<String, String> extraparameters = new TreeMap<String, String>();

	/**
     * Gets the value of the fromAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromAccountName() {
        return fromAccountName;
    }

    /**
     * Sets the value of the fromAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromAccountName(String value) {
        this.fromAccountName = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the replyToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyToAddress() {
        return replyToAddress;
    }

    /**
     * Sets the value of the replyToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyToAddress(String value) {
        this.replyToAddress = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the cc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCc() {
        return cc;
    }

    /**
     * Sets the value of the cc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCc(String value) {
        this.cc = value;
    }

    /**
     * Gets the value of the bcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBcc() {
        return bcc;
    }

    /**
     * Sets the value of the bcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBcc(String value) {
        this.bcc = value;
    }
    
    /**
     * 
     * @return
     */
    public AttachmentContent getAttachment() {
		return attachment;
	}
    
    /**
     * 
     * @param attachment
     */
	public void setAttachment(AttachmentContent attachment) {
		this.attachment = attachment;
	}
	
	/**
	 * 
	 * @return
	 */
	public Map<String, String> getParameters() {
		return parameters;
	}
	
	/**
	 * 
	 * @param parameters
	 */
	public void setParameters(Map<String, String> parameters) {
		this.parameters = parameters;
	}

	/**
	 * @return
	 */
	public Map<String, String> getExtraparameters() {
		return extraparameters;
	}

	/**
	 * @param extraparameters
	 */
	public void setExtraparameters(Map<String, String> extraparameters) {
		this.extraparameters = extraparameters;
	}

	public AttachmentContent[] getAttachments() {
		return attachments;
	}

	public void setAttachments(AttachmentContent[] attachments) {
		this.attachments = attachments;
	}
}
