url.service.catalogo.empleado.siap = ${mvn.url.service.catalogo.empleado.siap}
timeOut.coneccion.servicios.externos.default.milis= ${mvn.timeOut.coneccion.servicios.externos.default.milis}
timeOut.respuesta.servicios.externos.default.milis= ${mvn.timeOut.respuesta.servicios.externos.default.milis}

###datos para conectarse al Directorio Activo del IMSS###
ulr.directorio.activo.imss = ${mvn.ulr.directorio.activo.imss}
user.directorio.activo.imss = ${mvn.user.directorio.activo.imss}
credentials.user.directorio.activo.imss = ${mvn.credentials.user.directorio.activo.imss}
base.dc.directorio.activo.imss = ${mvn.base.dc.directorio.activo.imss}
userSearchFilter.directorio.activo.imss = ${mvn.userSearchFilter.directorio.activo.imss}
basegc.metro.directorio.activo.imss = ${mvn.basegc.metro.directorio.activo.imss}
basegc.metro1.directorio.activo.imss = ${mvn.basegc.metro1.directorio.activo.imss}
basegc.norte.directorio.activo.imss = ${mvn.basegc.norte.directorio.activo.imss}
basegc.sur.directorio.activo.imss = ${mvn.basegc.sur.directorio.activo.imss}
basegc.centro.directorio.activo.imss = ${mvn.basegc.centro.directorio.activo.imss}
basegc.occidente.directorio.activo.imss = ${mvn.basegc.occidente.directorio.activo.imss}

basegc.metro2.directorio.activo.imss = ${mvn.basegc.metro2.directorio.activo.imss}
basegc.norte1.directorio.activo.imss = ${mvn.basegc.norte1.directorio.activo.imss}
basegc.sur1.directorio.activo.imss = ${mvn.basegc.sur1.directorio.activo.imss}
basegc.centro1.directorio.activo.imss = ${mvn.basegc.centro1.directorio.activo.imss}
basegc.occidente1.directorio.activo.imss = ${mvn.basegc.occidente1.directorio.activo.imss}
