//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class MedicoEnTurno  extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Long idMedicoContultorioTurno;
	protected UnidadMedicaFamiliar unidadMedicaFamiliar;
	protected Consultorio consultorio;
	protected Turno turno;
	protected MedicoFamiliar medicoFamiliar;
	protected MedicoEspecialidad medicoEspecialidad;
	protected Long poblacion;
	
	public MedicoEnTurno() {
		super();
	}
	
	public MedicoEnTurno(Long idRelacionMedicoConsultorioTurno) {
		this.idMedicoContultorioTurno = idRelacionMedicoConsultorioTurno;
	}

	/**
	 * Gets the value of the unidadMedicaFamiliar property.
	 * 
	 * @return possible object is {@link UnidadMedicaFamiliar }
	 * 
	 */
	public UnidadMedicaFamiliar getUnidadMedicaFamiliar() {
		return unidadMedicaFamiliar;
	}

	/**
	 * Sets the value of the unidadMedicaFamiliar property.
	 * 
	 * @param value
	 *            allowed object is {@link UnidadMedicaFamiliar }
	 * 
	 */
	public void setUnidadMedicaFamiliar(UnidadMedicaFamiliar value) {
		this.unidadMedicaFamiliar = value;
	}

	/**
	 * Gets the value of the consultorio property.
	 * 
	 * @return possible object is {@link Consultorio }
	 * 
	 */
	public Consultorio getConsultorio() {
		return consultorio;
	}

	/**
	 * Sets the value of the consultorio property.
	 * 
	 * @param value
	 *            allowed object is {@link Consultorio }
	 * 
	 */
	public void setConsultorio(Consultorio value) {
		this.consultorio = value;
	}

	/**
	 * Gets the value of the turno property.
	 * 
	 * @return possible object is {@link Turno }
	 * 
	 */
	public Turno getTurno() {
		return turno;
	}

	/**
	 * Sets the value of the turno property.
	 * 
	 * @param value
	 *            allowed object is {@link Turno }
	 * 
	 */
	public void setTurno(Turno value) {
		this.turno = value;
	}

	/**
	 * Gets the value of the medicoFamiliar property.
	 * 
	 * @return possible object is {@link MedicoFamiliar }
	 * 
	 */
	public MedicoFamiliar getMedicoFamiliar() {
		return medicoFamiliar;
	}

	/**
	 * Sets the value of the medicoFamiliar property.
	 * 
	 * @param value
	 *            allowed object is {@link MedicoFamiliar }
	 * 
	 */
	public void setMedicoFamiliar(MedicoFamiliar value) {
		this.medicoFamiliar = value;
	}

	public MedicoEspecialidad getMedicoEspecialidad() {
		return medicoEspecialidad;
	}

	public void setMedicoEspecialidad(MedicoEspecialidad medicoEspecialidad) {
		this.medicoEspecialidad = medicoEspecialidad;
	}

	public Long getIdMedicoContultorioTurno() {
		return idMedicoContultorioTurno;
	}

	public void setIdMedicoContultorioTurno(Long idMedicoContultorioTurno) {
		this.idMedicoContultorioTurno = idMedicoContultorioTurno;
	}

	public Long getPoblacion() {
		return poblacion;
	}

	public void setPoblacion(Long poblacion) {
		this.poblacion = poblacion;
	}

	
}
