//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class RazonRegistro extends AbstractModel  implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Long idRazonRegistro;
	protected String descripcion;

	/**
	 * Gets the value of the idRazonRegistro property.
	 * 
	 */
	public Long getIdRazonRegistro() {
		return idRazonRegistro;
	}

	/**
	 * Sets the value of the idRazonRegistro property.
	 * 
	 */
	public void setIdRazonRegistro(Long value) {
		this.idRazonRegistro = value;
	}

	/**
	 * Gets the value of the descripcion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * Sets the value of the descripcion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescripcion(String value) {
		this.descripcion = value;
	}

}
