HOST_MEXICO=relay.imss.gob.mx
USER_CORREO=g.derechohabientes
PASSWORD_CORREO=g3st10n.d3r3c#0#4b
FROMIMSS_CORREO=serviciosdigitales@imss.gob.mx
TOIMSS_CORREO=megatkdiv@gmail.com
AUTENTICACION=false
PROTOCOLO=smtp
PUERTO=25
 