
package mx.gob.imss.vigenciaderechoste;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSVigenciaXNSS", targetNamespace = "http://vigenciaderechos.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSVigenciaXNSS {


    /**
     * 
     * @param nss
     * @param cpid
     * @return
     *     returns mx.gob.imss.vigenciaderechoste.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://vigenciaderechos.imss.gob.mx/", className = "mx.gob.imss.vigenciaderechoste.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://vigenciaderechos.imss.gob.mx/", className = "mx.gob.imss.vigenciaderechoste.GetInfoResponse")
    public Return getInfo(
        @WebParam(name = "nss", targetNamespace = "")
        String nss,
        @WebParam(name = "Cpid", targetNamespace = "")
        String cpid);

}
