package mx.gob.imss.csdiss.sdroc.dto;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RotInformacionObra generated by hbm2java
 */
public class AvisoObraDTO implements java.io.Serializable {


	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4133416175452124111L;
	private Long cveAvisoObra;
	private SubDelegacionDTO subDelegacionDTO;
	private InformacionPatronDTO informacionPatronDTO;
	private String cveRegistroAvisoObra;
	private String cveRfcPatron;
	private Date fecIniObra;
	private Date fecFinObra;
	private Double impObra;
	private String refAcuseReg;
	private Date stpCreaReg;
	private String refCadenaOriginal;
	private String refSelloDigital;
	private String refSeqNotarial;
	private String refNumSerie;	
	private Boolean refEstadoReg;
	private Long cveIdTramite;
	private String folio;
	private String numSeqNotaria;
	private UbicacionObraDTO ubicacionObraDTO;
	private String numProcedimiento;
	private String codigoRespuesta; 

	public AvisoObraDTO() {
	}

	public AvisoObraDTO(Long cveAvisoObra, SubDelegacionDTO subDelegacionDTO, TipoObraDTO tipoObraDTO,
			InformacionPatronDTO informacionPatronDTO, EstatusObraDTO estatusObraDTO,UbicacionObraDTO ubicacionObraDTO,String cveRegistroAvisoObra, String cveRfcPatron) {
		this.cveAvisoObra = cveAvisoObra;
		this.subDelegacionDTO = subDelegacionDTO;
		this.informacionPatronDTO = informacionPatronDTO;
		this.cveRegistroAvisoObra = cveRegistroAvisoObra;
		this.ubicacionObraDTO = ubicacionObraDTO;
		this.cveRfcPatron = cveRfcPatron;
	}

	public AvisoObraDTO(Long cveAvisoObra, SubDelegacionDTO subDelegacionDTO, InformacionPatronDTO informacionPatronDTO,
			String cveRegistroAvisoObra, Date fecIniObra, Date fecFinObra, Double impObra,			
			String refAcuseReg, String refCadenaOriginal, String refSelloDigital,String refSeqNotarial,String refNumSerie, Boolean refEstadoReg, 
			Date stpCreaReg, UbicacionObraDTO ubicacionObraDTO, String cveRfcPatron,Long cveIdTramite,String folio, String numSeqNotaria) {

		this.cveAvisoObra = cveAvisoObra;
		this.subDelegacionDTO = subDelegacionDTO;
		this.informacionPatronDTO = informacionPatronDTO;
		this.cveRegistroAvisoObra = cveRegistroAvisoObra;
		this.fecIniObra = fecIniObra;
		this.fecFinObra = fecFinObra;
		this.impObra = impObra;
		this.refAcuseReg = refAcuseReg;
		this.ubicacionObraDTO = ubicacionObraDTO;
		this.stpCreaReg = stpCreaReg;
		this.refCadenaOriginal = refCadenaOriginal;
		this.refSelloDigital = refSelloDigital;
		this.refSeqNotarial = refSeqNotarial;
		this.refEstadoReg = refEstadoReg;
		this.refNumSerie = refNumSerie;		
		this.cveRfcPatron = cveRfcPatron;
		this.cveIdTramite = cveIdTramite;
		this.folio = folio;
		this.numSeqNotaria = numSeqNotaria;
	}

	/**
	 * @return the cveAvisoObra
	 */
	public Long getCveAvisoObra() {
		return cveAvisoObra;
	}

	/**
	 * @param cveAvisoObra the cveAvisoObra to set
	 */
	public void setCveAvisoObra(Long cveAvisoObra) {
		this.cveAvisoObra = cveAvisoObra;
	}

	/**
	 * @return the subDelegacionDTO
	 */
	public SubDelegacionDTO getSubDelegacionDTO() {
		return subDelegacionDTO;
	}

	/**
	 * @param subDelegacionDTO the subDelegacionDTO to set
	 */
	public void setSubDelegacionDTO(SubDelegacionDTO subDelegacionDTO) {
		this.subDelegacionDTO = subDelegacionDTO;
	}

	/**
	 * @return the informacionPatronDTO
	 */
	public InformacionPatronDTO getInformacionPatronDTO() {
		return informacionPatronDTO;
	}

	/**
	 * @param informacionPatronDTO the informacionPatronDTO to set
	 */
	public void setInformacionPatronDTO(InformacionPatronDTO informacionPatronDTO) {
		this.informacionPatronDTO = informacionPatronDTO;
	}

	/**
	 * @return the cveRegistroAvisoObra
	 */
	public String getCveRegistroAvisoObra() {
		return cveRegistroAvisoObra;
	}

	/**
	 * @param cveRegistroAvisoObra the cveRegistroAvisoObra to set
	 */
	public void setCveRegistroAvisoObra(String cveRegistroAvisoObra) {
		this.cveRegistroAvisoObra = cveRegistroAvisoObra;
	}

	/**
	 * @return the fecIniObra
	 */
	public Date getFecIniObra() {
		return fecIniObra;
	}

	/**
	 * @param fecIniObra the fecIniObra to set
	 */
	public void setFecIniObra(Date fecIniObra) {
		this.fecIniObra = fecIniObra;
	}

	/**
	 * @return the fecFinObra
	 */
	public Date getFecFinObra() {
		return fecFinObra;
	}

	/**
	 * @param fecFinObra the fecFinObra to set
	 */
	public void setFecFinObra(Date fecFinObra) {
		this.fecFinObra = fecFinObra;
	}

	/**
	 * @return the impObra
	 */
	public Double getImpObra() {
		return impObra;
	}

	/**
	 * @param impObra the impObra to set
	 */
	public void setImpObra(Double impObra) {
		this.impObra = impObra;
	}

	/**
	 * @return the refAcuseReg
	 */
	public String getRefAcuseReg() {
		return refAcuseReg;
	}

	/**
	 * @param refAcuseReg the refAcuseReg to set
	 */
	public void setRefAcuseReg(String refAcuseReg) {
		this.refAcuseReg = refAcuseReg;
	}

	/**
	 * @return the stpCreaReg
	 */
	public Date getStpCreaReg() {
		return stpCreaReg;
	}

	/**
	 * @param stpCreaReg the stpCreaReg to set
	 */
	public void setStpCreaReg(Date stpCreaReg) {
		this.stpCreaReg = stpCreaReg;
	}

	/**
	 * @return the refCadenaOriginal
	 */
	public String getRefCadenaOriginal() {
		return refCadenaOriginal;
	}

	/**
	 * @param refCadenaOriginal the refCadenaOriginal to set
	 */
	public void setRefCadenaOriginal(String refCadenaOriginal) {
		this.refCadenaOriginal = refCadenaOriginal;
	}

	/**
	 * @return the refSelloDigital
	 */
	public String getRefSelloDigital() {
		return refSelloDigital;
	}

	/**
	 * @param refSelloDigital the refSelloDigital to set
	 */
	public void setRefSelloDigital(String refSelloDigital) {
		this.refSelloDigital = refSelloDigital;
	}

	/**
	 * @return the refSeqNotarial
	 */
	public String getRefSeqNotarial() {
		return refSeqNotarial;
	}

	/**
	 * @param refSeqNotarial the refSeqNotarial to set
	 */
	public void setRefSeqNotarial(String refSeqNotarial) {
		this.refSeqNotarial = refSeqNotarial;
	}

	/**
	 * @return the refNumSerie
	 */
	public String getRefNumSerie() {
		return refNumSerie;
	}

	/**
	 * @param refNumSerie the refNumSerie to set
	 */
	public void setRefNumSerie(String refNumSerie) {
		this.refNumSerie = refNumSerie;
	}

	/**
	 * @return the ubicacionObraDTO
	 */
	public UbicacionObraDTO getUbicacionObraDTO() {
		return ubicacionObraDTO;
	}

	/**
	 * @param ubicacionObraDTO the ubicacionObraDTO to set
	 */
	public void setUbicacionObraDTO(UbicacionObraDTO ubicacionObraDTO) {
		this.ubicacionObraDTO = ubicacionObraDTO;
	}

	/**
	 * @return the cveRfcPatron
	 */
	public String getCveRfcPatron() {
		return cveRfcPatron;
	}

	/**
	 * @param cveRfcPatron the cveRfcPatron to set
	 */
	public void setCveRfcPatron(String cveRfcPatron) {
		this.cveRfcPatron = cveRfcPatron;
	}
	
	public Long getCveIdTramite() {
		return cveIdTramite;
	}

	public void setCveIdTramite(Long cveIdTramite) {
		this.cveIdTramite = cveIdTramite;
	}

	public String getFolio() {
		return folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}
	
	public String getNumSeqNotaria() {
		return numSeqNotaria;
	}

	public void setNumSeqNotaria(String numSeqNotaria) {
		this.numSeqNotaria = numSeqNotaria;
	}

	public Boolean getRefEstadoReg() {
		return refEstadoReg;
	}

	public void setRefEstadoReg(Boolean refEstadoReg) {
		this.refEstadoReg = refEstadoReg;
	}

	/**
	 * @return the numProcedimiento
	 */
	public String getNumProcedimiento() {
		return numProcedimiento;
	}

	/**
	 * @param numProcedimiento the numProcedimiento to set
	 */
	public void setNumProcedimiento(String numProcedimiento) {
		this.numProcedimiento = numProcedimiento;
	}

	/**
	 * @return the codigoRespuesta
	 */
	public String getCodigoRespuesta() {
		return codigoRespuesta;
	}

	/**
	 * @param codigoRespuesta the codigoRespuesta to set
	 */
	public void setCodigoRespuesta(String codigoRespuesta) {
		this.codigoRespuesta = codigoRespuesta;
	}
	
}
