//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 02:38:17 PM CST 
//


package mx.gob.imss.ctirss.delta.model.derechohabiente.dto.ws;



import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;





@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class GetFotografiaAsegurado implements Serializable {

    
	private static final long serialVersionUID = 532652550116849883L;
	
	private String nss;
    private int calidad;

    /**
     * Gets the value of the nss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNss() {
        return nss;
    }

    /**
     * Sets the value of the nss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNss(String value) {
        this.nss = value;
    }

    /**
     * Gets the value of the calidad property.
     * 
     */
    public int getCalidad() {
        return calidad;
    }

    /**
     * Sets the value of the calidad property.
     * 
     */
    public void setCalidad(int value) {
        this.calidad = value;
    }

}
