/**
 * 
 */
package mx.gob.imss.csdiss.sdroc.util;

/**
 * @author joel.fuentes
 *
 */
public abstract class CorreoTemplate {

	public static String construirPlantillaCorreo(String titulo, String mensaje){
		
		StringBuilder template = new StringBuilder();
		template.append("<html>")
		.append("<head>")
		.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />")
		.append("<title>")
		.append(titulo)
		.append("</title>")
		.append("<style type=\"text/css\">")
		.append("<![CDATA[")
		.append("a:hover {")
		.append("	color: #7b9cf0;")
		.append("}")
		.append(".header span {")
		.append("	color: #ffffff;")
		.append("	font: normal 16px Helvetica, Arial;")
		.append("	margin: 0px;")
		.append("	padding: 0px;")
		.append("	line-height: 16px;")
		.append("	margin: 0px;")
		.append("	padding: 0px;")
		.append("	padding: 0px;")
		.append("}")
		.append(".content h4 {")
		.append("	color: #5A5A5A;")
		.append("	margin: 0px;")
		.append("	padding: 0px;")
		.append("	line-height: 30px;")
		.append("	font-size: 24px;")
		.append("	font-family: Helvetica, Arial;")
		.append("}")
		.append(".content p {")
		.append("	color: #5A5A5A;")
		.append("	font-weight: normal;")
		.append("	margin: 0px;")
		.append("	padding: 0px;")
		.append("	line-height: 23px;")
		.append("	font-size: 16px;")
		.append("	font-family: Helvetica, Arial;")
		.append("}")
		.append(".content .note p {")
		.append("	color: #5A5A5A;")
		.append("	font-weight: normal;")
		.append("	margin: 0px;")
		.append("	padding: 0px;")
		.append("	font-style: italic;")
		.append("	line-height: 20px;")
		.append("	font-size: 12px;")
		.append("	font-family: Helvetica, Arial;")
		.append("}")
		.append(".footer a {")
		.append("	color: #12c;")
		.append("}")
		.append(".footer p {")
		.append("	padding: 0px;")
		.append("	font-size: 13px;")
		.append("	color: #5A5A5A;")
		.append("	margin: 0px;")
		.append("	font-family: Helvetica, Arial;")
		.append("	text-transform: uppercase;")
		.append("	color: #5A5A5A;")
		.append("}")
		.append("]]>")
		.append("</style>")
		.append("</head>")
		.append("<body style=\"margin: 0; padding: 0; background: #F3F3F3;\">")
		.append("	<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\"")
		.append("		width=\"100%\">")
		.append("		<tr>")
		.append("			<td align=\"center\"")
		.append("				style=\"margin: 0; padding: 0; background: #F3F3F3; padding: 27px 0px\">")
		.append("				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\"")
		.append("					width=\"560px\"")
		.append("					style=\"font-family: Helvetica, Arial; font-size: 16px; color: #ffffff; background: #393C3E\"")
		.append("					class=\"header\">")
		.append("					<tr>")
		.append("						<td height=\"76px\" valign=\"middle\" style=\"padding-left: 27px;\">")
		.append("							<a href=\"//www.gob.mx/\" style=\"vertical-align: middle;\"> <img")
		.append("								width=\"100%\" height=\"39\" alt=\"gob.mx\"")
		.append("								src=\"http://serviciosdigitales.imss.gob.mx/delta/resources/imagenes/gobmx/logos/gobmxlogo.png\" />")
		.append("						</a>")
		.append("						</td>")
		.append("						<td height=\"76px\" valign=\"middle\" align=\"right\"")
		.append("							style=\"padding-right: 27px;\"><span")
		.append("							style=\"color: #ffffff; font: normal 16px Helvetica, Arial; margin: 0px; padding: 0px; line-height: 16px;\">IMSS - ESCRITORIO VIRTUAL</span></td>")
		.append("					</tr>")
		.append("				</table>")
		.append("				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\"")
		.append("					width=\"560px\"")
		.append("					style=\"font-family: Helvetica, Arial; background: #ffffff;\"")
		.append("					bgcolor=\"#ffffff\">")
		.append("					<tr>")
		.append("						<td width=\"560px;\" valign=\"top\" align=\"left\" bgcolor=\"#ffffff\"")
		.append("							style=\"font-family: Helvetica, Arial; font-size: 16px; color: #5A5A5A; background: #fff; padding: 38px 27px 76px;\">")
		.append("							<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"")
		.append("								style=\"color: #717171; font: normal 16px Helvetica, Arial; margin: 0px; padding: 0;\"")
		.append("								width=\"100%\" class=\"content\">")
		.append("								<tr>")
		.append("									<td align=\"center\" style=\"padding: 15px 0px;\">")
		.append("										<h4")
		.append("											style=\"color: #5A5A5A; margin: 0px; padding: 0px; line-height: 30px; font-size: 24px; font-family: Helvetica, Arial;\">")
		.append(titulo)
		.append("</h4>")
		.append("									</td>")
		.append("								</tr>")
		.append("								<tr>")
		.append("									<td align=\"justify\"")
		.append("										style=\"padding: 15px 0px; text-align: justify;\" valign=\"top\">")
		.append("										<p style=\"color: #5A5A5A; font-weight: normal; margin: 0px; padding: 0px; line-height: 23px; font-size: 16px; font-family: Helvetica, Arial;\">")
		.append(mensaje)
		.append("										</p> <br />")
		.append("									</td>")
		.append("								</tr>")								
		.append("								<tr>")
		.append("									<td align=\"justify\"")
		.append("										style=\"padding: 15px 0px; text-align: justify;\" class=\"note\"><p")
		.append("											style=\"color: #5A5A5A; font-weight: normal; margin: 0px; padding: 0px; font-style: italic; line-height: 20px; font-size: 12px; font-family: Helvetica, Arial;\">Esta")
		.append("											dirección de correo electrónico no puede recibir respuestas</p></td>")
		.append("								</tr>")
		.append("								<tr>")
		.append("									<td align=\"justify\"")
		.append("										style=\"padding: 15px 0px; text-align: justify;\" class=\"note\"><p")
		.append("											style=\"color: #5A5A5A; font-weight: normal; margin: 0px; padding: 0px; font-style: italic; line-height: 20px; font-size: 12px; font-family: Helvetica, Arial;\">")
		.append("											<strong>AVISO DE PRIVACIDAD:</strong> Los datos personales")
		.append("						recabados serán protegidos, tratados e incorporados en el sistema")
		.append("						de datos personales denominado Catálogo Nacional de Asegurados")
		.append("						(CANASE) con fundamento en los artículos 22 de la Ley del Seguro")
		.append("						Social, 13 fracciones IV y V, 18, 19, 20 y 21 de la Ley Federal de")
		.append("						Transparencia y Acceso a la Información Pública Gubernamental,")
		.append("						cuya finalidad es proteger, contener, ordenar y clasificar los")
		.append("						datos de los patrones y asegurados, el CANASE está registrado en")
		.append("						el Listado de Sistemas de Datos Personales ante el Instituto")
		.append("						Federal de Acceso a la Información Pública <a")
		.append("							href=\"http://www.ifai.org.mx\" target=\"_blank\" class=\"link\">(www.ifai.org.mx),</a>")
		.append("						y será transmitido, al INFONAVIT y a la CONSAR con la finalidad de")
		.append("						que el asegurado haga valer su derecho de ejercicio de crédito de")
		.append("						vivienda y disposición del Seguro de Retiro, además de otras")
		.append("						transmisiones previstas en la Ley. La Unidad Administrativa")
		.append("						responsable del Sistema de Datos Personales es la Dirección de")
		.append("						Incorporación y Recaudación en coordinación con la Dirección de")
		.append("						Innovación y Desarrollo Tecnológico, ambas dependientes del IMSS;")
		.append("						en su caso el interesado podrá ejercer los derechos de acceso y")
		.append("						corrección en la Subdelegación de control que corresponde al")
		.append("						domicilio del patrón o del asegurado. Lo anterior se informa en")
		.append("						cumplimiento del decimoséptimo de los Lineamientos de Protección")
		.append("						de Datos Personales, publicados en el Diario Oficial de la")
		.append("						Federación el 30 de septiembre de 2005.")
		.append("										</p></td>")
		.append("								</tr>")
		.append("								<tr>")
		.append("									<td align=\"justify\"")
		.append("										style=\"padding: 15px 0px; text-align: justify;\" class=\"note\"><p")
		.append("											style=\"color: #5A5A5A; font-weight: normal; margin: 0px; padding: 0px; font-style: italic; line-height: 20px; font-size: 12px; font-family: Helvetica, Arial;\">")
		.append("											<strong>AVISO IMPORTANTE:</strong> Este correo electrónico y/o el")
		.append("						material adjunto es para uso exclusivo de la persona o la entidad")
		.append("						a la que expresamente se le ha enviado, el cual contiene")
		.append("						información confidencial. Si no es el destinatario legítimo del")
		.append("						mismo, por favor repórtelo inmediatamente a la cuenta del")
		.append("						remitente y elimínelo. Cualquier revisión, almacenamiento,")
		.append("						retransmisión, difusión o cualquier otro uso de este correo, por")
		.append("						personas o entidades distintas a las del destinatario legítimo,")
		.append("						queda expresamente prohibida. Este correo electrónico no pretende")
		.append("						ni debe ser considerado como constitutivo de ninguna relación")
		.append("						legal, contractual o de otra índole similar.")
		.append("										</p></td>")
		.append("								</tr>")
		.append("							</table>")
		.append("						</td>")
		.append("					</tr>")
		.append("				</table>")
		.append("				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\"")
		.append("					width=\"560px\"")
		.append("					style=\"font-family: Helvetica, Arial; font-size: 16px; color: #ffffff; background: #393C3E\"")
		.append("					class=\"mainFooter\">")
		.append("					<tr>")
		.append("						<td align=\"left\" height=\"76px\" valign=\"middle\"")
		.append("							style=\"padding-left: 27px;\"><img width=\"63\" height=\"19\"")
		.append("							alt=\"gob.mx\"")
		.append("							src=\"http://serviciosdigitales.imss.gob.mx/delta/resources/imagenes/gobmx/logos/gobmxlogo.png\" />")
		.append("						</td>")
		.append("						<td height=\"76px\" valign=\"middle\" align=\"right\"")
		.append("							style=\"padding-right: 27px;\"><img width=\"86\" height=\"35\"")
		.append("							alt=\"gob.mx\"")
		.append("							src=\"http://serviciosdigitales.imss.gob.mx/delta/resources/imagenes/gobmx/logos/logo_mexico.png\" /></td>")
		.append("					</tr>")
		.append("				</table>")
		.append("				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\"")
		.append("					width=\"560px\"")
		.append("					style=\"font-family: Helvetica, Arial; line-height: 10px;\"")
		.append("					bgcolor=\"#F3F3F3\" class=\"footer\">")
		.append("					<tr>")
		.append("						<td bgcolor=\"#F3F3F3\" align=\"center\"")
		.append("							style=\"padding: 15px 0 10px; font-size: 13px; color: #5A5A5A; margin: 0px; line-height: 1.2; font-family: Helvetica, Arial;\"")
		.append("							valign=\"top\">")
		.append("							<p")
		.append("								style=\"padding: 0px; font-size: 13px; color: #5A5A5A; margin: 0px; font-family: Helvetica, Arial; text-transform: uppercase; color: #5A5A5A;\">IMSS,")
		.append("								México - Algunos derechos reservados 2015</p>\"")
		.append("							<p")
		.append("								style=\"padding: 0px; font-size: 13px; color: #5A5A5A; margin: 0px 0px 8px 0px; font-family: Helvetica, Arial; text-transform: uppercase; color: #5A5A5A;\">")
		.append("								<a href=\"http://www.imss.gob.mx/pages/privacidad.aspx\"")
		.append("									style=\"color: #12c;\">POLÍTICA DE PRIVACIDAD Y MANEJO DE")
		.append("									DATOS PERSONALES </a> - <a target=\"_parent\"")
		.append("									href=\"http://www.imss.gob.mx/Pages/avisolegal.aspx\"")
		.append("									style=\"color: #12c;\">Aviso LEGAL</a>")
		.append("							</p>")
		.append("						</td>")
		.append("					</tr>")
		.append("				</table>")
		.append("			</td>")
		.append("		</tr>")
		.append("	</table>")
		.append("</body>")
		.append("</html>");
		
		return template.toString();
	}

}
