package mx.gob.imss.csdiss.sdroc.util;


public enum ParametroReporte {
	
	IMAGE_DIR("IMAGE_DIR"),
	FOLIO("FOLIO"),
	NUMERO_REGISTRO("NUMERO_REGISTRO"),
	NUMERO_ACUERDO("NUMERO_ACUERDO"),
	DIA_ACUERDO("DIA_ACUERDO"),
	NUMERO_ARTICULO("NUMERO_ARTICULO"),
	DELEGACION("DELEGACION"),
	SUB_DELEGACION("SUB_DELEGACION"),
	RAZON_SOCIAL("RAZON_SOCIAL"),
	REGISTRO_PATRONAL("REGISTRO_PATRONAL"),
	RFC("RFC"),
	TIPO_PATRON("TIPO_PATRON"),
	CLASE_OBRA("CLASE_OBRA"),
	TIPO_OBRA_TITULO("TIPO_OBRA_TITULO"),
	CVE_TIPO_OBRA("CVE_TIPO_OBRA"),
	TIPO_OBRA("TIPO_OBRA"),
	UBICACION("UBICACION"),
	TITULO_PERIODO("TITULO_PERIODO"),
	FEC_INICIO("FEC_INICIO"),
	FEC_TERMINO("FEC_TERMINO"),
	TITULO_MONTO("TITULO_MONTO"),
	MONTO("MONTO"),
	SUPERFICIE("SUPERFICIE"),
	NUMERO_PROCEDIMIENTO("NUMERO_PROCEDIMIENTO"),
	CADENA_FIRMA("CADENA_FIRMA"),
	SELLO_DIGITAL_ACUSE("SELLO_DIGITAL_ACUSE"),
	CADENA_ORIGINAL_ACUSE("CADENA_ORIGINAL_ACUSE"),
	IMAGEN_QR("IMAGEN_QR"),
	TIPO_TITULO("TIPO_TITULO"),
	NUMERO_LICITACION("NUMERO_LICITACION"),
	MOTIVO_ACTUALIZACION("MOTIVO_ACTUALIZACION"),
	BIMESTRE_ANO_PRESENTAR("BIMESTRE_ANO_PRESENTAR"),
	FECHA_SUSPENSION_OBRA("FECHA_SUSPENSION_OBRA"),		
	MOTIVO_SUSPENSION("MOTIVO_SUSPENSION"),
	FEC_REANUDACION("FEC_REANUDACION"),
	FECHA_CANCELACION_OBRA("FECHA_CANCELACION_OBRA"),
	MOTIVO_CANCELACION("MOTIVO_CANCELACION"),
	CALLE("CALLE"),
	FEC_REGISTRO("FEC_REGISTRO"),
	NUMERO_REGISTRO_CONTRA("NUMERO_REGISTRO_CONTRA"),
	NUM_EXT("NUM_EXT"),
	NUM_INT("NUM_INT"),
	COLONIA("COLONIA"),
	MUNICIPIO("MUNICIPIO"),
	ENTIDAD("ENTIDAD"),
	CP("CP"),
	OBSERVACIONES("OBSERVACIONES"),
	MONTO_EJERCIDO("MONTO_EJERCIDO"),
	BIMESTRE("BIMESTRE"),
	OBSERVA_REGISTRO("OBSERVA_REGISTRO"),
	FEC_ACT("FEC_ACT"),
	FEC_TER_ACT("FEC_TER_ACT"),
	MONTO_ACT("MONTO_ACT"),
	SUPERFICIE_ACT("SUPERFICIE_ACT"),
	MOTIVO_ACT("MOTIVO_ACT"),
	FEC_SUS("FEC_SUS"),
	MONTO_SUS("MONTO_SUS"),
	MOTIVO_SUS("MOTIVO_SUS"),
	FEC_REANU("FEC_REANU"),
	MONTO_EJER_REANU("MONTO_EJER_REANU"),
	FEC_TER_REANU("FEC_TER_REANU"),
	MONTO_REANU("MONTO_REANU"),
	SUPERFICIE_REANU("SUPERFICIE_REANU"),
	MOTIVO_REANU("MOTIVO_REANU"),
	FEC_CANCELA("FEC_CANCELA"),
	MONTO_CANCELA("MONTO_CANCELA"),
	MOTIVO_CANCELA("MOTIVO_CANCELA"),
	FEC_TERMINA("FEC_TERMINA"),
	MONTO_TERMINA("MONTO_TERMINA"),
	SUPERFICIE_TERMINA("SUPERFICIE_TERMINA"),
	//Parametros REPSE y num aprox de trabajadores
	NUM_APROX_TRABAJADORES("NUM_APROX_TRABAJADORES"),
	NUMERO_REPSE("NUMERO_REPSE"),
	OC_SUBESP("OC_SUBESP"),//Objeto de contrato para subcontratista especializado
	IND_REG_PAT_AMPARO("IND_REG_PAT_AMPARO")
	//Parametros Adicionales Excel
	//Registro Patronal
    ;
	
	private String valor;

    /**
     * Constructor para la clase ParametroReporte.
     * 
     * @param clave
     */
	ParametroReporte(String valor) {
        this.valor = valor;
    }

    /**
     * Retorna el valor del Enumerado.
     * 
     * @return
     */
    public String getValor() {
        return valor;
    }
    
}
