welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

############# WIZARDS #################
tramiteDummyInicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramiteDummyInicio.url=tramiteDummyInicio
tramiteDummyContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
tramiteDummyContenido.url = tramiteDummyContenido

############# PORTLETS #################
portletDummyInicial.(class)=org.springframework.web.servlet.view.JstlView
portletDummyInicial.url=/WEB-INF/views/portlet/dummy/inicial.jsp
portletDummyContenido.(class)=org.springframework.web.servlet.view.JstlView
portletDummyContenido.url=/WEB-INF/views/portlet/dummy/contenido.jsp

############# WIDGETS #################
widgetDummyInicio.(class)=org.springframework.web.servlet.view.JstlView
widgetDummyInicio.url=/WEB-INF/views/widget/dummy/inicial.jsp
widgetDummyContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDummyContenido.url=/WEB-INF/views/widget/dummy/contenido.jsp


############# CLINICA #################
clinicaInicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
clinicaInicio.url=inicialClinica

clinicaBeneficiarios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
clinicaBeneficiarios.url=beneficiariosClinica

solicitudExistente.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitudExistente.url=solicitudExistente


##opantalla de captura de curp y parentesco
inicioRegistroBeneficiario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicioRegistroBeneficiario.url =inicioRegistroBeneficiario

#caotura de datos personales registro
datosPersonalesRegistro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosPersonalesRegistro.url =datosPersonalesRegistro

wizardRegistroCapturaDomicilioUMF.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistroCapturaDomicilioUMF.url =wizardRegistroCapturaDomicilioUMF
errorReporteVigencia.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorReporteVigencia.url =errorReporteVigencia

initReporteVigencia.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initReporteVigencia.url = initReporteVigencia

viewCartaTerminos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
viewCartaTerminos.url=viewCartaTerminos

seleccionUmf.(class)=org.springframework.web.servlet.view.tiles2.TilesView
seleccionUmf.url = seleccionUmf

seleccionUmfConDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
seleccionUmfConDomicilio.url = seleccionUmfConDomicilio

detalleSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleSolicitud.url=detalleSolicitud

#Inicio de tramites derechohabientes
derechohabientes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
derechohabientes.url=derechohabientes

tramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.url=tramite

#Aviso privacidad
avisoPrivacidad.(class)=org.springframework.web.servlet.view.tiles2.TilesView
avisoPrivacidad.url=avisoPrivacidad


############# DOMICLIOS COMMON  #################
portalPrueba.(class)=org.springframework.web.servlet.view.JstlView
portalPrueba.url=/WEB-INF/views/general/pantallaPrueba.jsp

portalPruebaCont.(class)=org.springframework.web.servlet.view.JstlView
portalPruebaCont.url=/WEB-INF/views/general/pantallaPruebaCont.jsp

inicioActualizacionCURP.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicioActualizacionCURP.url = inicioActualizacionCURP

confirmacionActualizacionCURP.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmacionActualizacionCURP.url = confirmacionActualizacionCURP

solicitudActualizacionCURP.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitudActualizacionCURP.url =solicitudActualizacionCURP