//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 02:38:17 PM CST 
//


package mx.gob.imss.ctirss.delta.model.derechohabiente.dto.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the myproject.wsdl.currency package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: myproject.wsdl.currency
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFotografiaAseguradoResponse }
     * 
     */
    public GetFotografiaAseguradoResponse createGetFotografiaAseguradoResponse() {
        return new GetFotografiaAseguradoResponse();
    }

    /**
     * Create an instance of {@link GetFotografiaDerechohabiente }
     * 
     */
    public GetFotografiaDerechohabiente createGetFotografiaDerechohabiente() {
        return new GetFotografiaDerechohabiente();
    }

    /**
     * Create an instance of {@link GetFotografiaAsegurado }
     * 
     */
    public GetFotografiaAsegurado createGetFotografiaAsegurado() {
        return new GetFotografiaAsegurado();
    }

    /**
     * Create an instance of {@link GetFotografiaDerechohabienteResponse }
     * 
     */
    public GetFotografiaDerechohabienteResponse createGetFotografiaDerechohabienteResponse() {
        return new GetFotografiaDerechohabienteResponse();
    }

}
