--============================================================================================================
--Script del flujo "Retorno de informacion de SINDO MOVIMIENTO 06" paquete: PKG_LOAD_CDA_MOV06_ODS_PROD_v2
-- Ambiente:                 Prod
-- Autores                   Omar Pérez Chavira 
-- Fecha                     30/Nov/2020
--============================================================================================================


--======================================================
--- PASO: SP_LOAD_FILES_SINDO
--======================================================
--- COMANDO: DELETE TABLE DIT_BITACORA_PROC_MOV06_CDA_CP

DELETE FROM DIT_BITACORA_PROC_MOV06_CDA_CP


--======================================================
--- PASO: SP_LOAD_DIT_BITACORA_PROC_SINDO_v2
--======================================================
--- COMANDO: SP_LOAD_DIT_BITACORA_PROC_SINDO_CDA

INSERT INTO /*+ APPEND*/  DIT_BITACORA_PROC_MOV06_CDA
(CVE_ID_CDA_SINDO,
CVE_ID_TRAMITE, 
CLAVE_DELEGACION,  
CLAVE_SUBDELEGACION,
FEC_INICIO_MOVIMIENTO,         
FEC_FIN_MOVIMIENTO,       
NOM_NOMBRE_ASEGURADO_C,
FEC_REGISTRO_ALTA,        
FEC_REGISTRO_BAJA,       
FEC_REGISTRO_ACTUALIZADO,        
NUM_NSS, 
CVE_ID_RESULTADO,   
CVE_ID_ORIGEN_RES_MVTO, 
DIGITO_VERIFICADOR_NSS)
(SELECT 
SEQ_DITCDASINDO.NEXTVAL,
CVE_ID_TRAMITE, 
CLAVE_DELEGACION,  
CLAVE_SUBDELEGACION,
FEC_INICIO_MOVIMIENTO,         
FEC_FIN_MOVIMIENTO,       
NOM_NOMBRE_ASEGURADO_C,
FEC_REGISTRO_ALTA,        
FEC_REGISTRO_BAJA,       
FEC_REGISTRO_ACTUALIZADO,        
NUM_NSS, 
CVE_ID_RESULTADO,   
CVE_ID_ORIGEN_RES_MVTO, 
DIGITO_VERIFICADOR_NSS
FROM DIT_BITACORA_PROC_MOV06_CDA_CP
)

--- COMANDO: UPD_REF_OBSERVACION

UPDATE DIT_BITACORA_PROC_MOV06_CDA t1
SET REF_OBSERVACION =
(SELECT t3.CVE_ID_RESULTADO||'|'||t3.CVE_ID_ORIGEN_RES_MVTO||'|'||t4.DES_RESULTADO from DIT_BITACORA_PROC_MOV06_CDA t3,
DIC_RESULTADO_CDA_SINDO t4
WHERE  1=1 
AND t1.CVE_ID_CDA_SINDO=t3.CVE_ID_CDA_SINDO
AND t3.CVE_ID_RESULTADO=t4.CVE_ID_RESULTADO
)
WHERE T1.CVE_ID_RESULTADO <> '000'
AND TRUNC(t1.FEC_REGISTRO_ALTA)=TRUNC(sysdate)


--======================================================
--- PASO: SP_LOAD_DIT_BIT_FLUJO_ARCH_v2
--======================================================


--- COMANDO: TRUNCATE_TABLA_TMP_CIZ1

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV06CDATMP


--- COMANDO: LOAD_CIZ1_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV06CDATMP
(CVE_ID_TRAMITE,IND_CIZ1)   
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV06_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '1' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ1_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP GROUP BY CVE_ID_TRAMITE

--- COMANDO: MERGE_REGISTROS_CIZ1

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV06CDA A
USING DIT_BIT_FLUJO_ARCH_MOV06CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ1 = B.IND_CIZ1, A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ1,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ1,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CIZ2

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV06CDATMP

--- COMANDO: LOAD_CIZ2_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV06CDATMP
(CVE_ID_TRAMITE,IND_CIZ2) 
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV06_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '2' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ2_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ2

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV06CDA A
USING DIT_BIT_FLUJO_ARCH_MOV06CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ2 = B.IND_CIZ2,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ2,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ2,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CIZ3

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV06CDATMP

--- COMANDO: LOAD_CIZ3_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV06CDATMP
(CVE_ID_TRAMITE,IND_CIZ3)
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV06_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '3'
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ3_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ3

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV06CDA A
USING DIT_BIT_FLUJO_ARCH_MOV06CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ3 = B.IND_CIZ3,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ3,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ3,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CA

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV06CDATMP

--- COMANDO: LOAD_CA_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV06CDATMP
(CVE_ID_TRAMITE,IND_CA)
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV06_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '5'
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CA_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CA

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV06CDA A
USING DIT_BIT_FLUJO_ARCH_MOV06CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CA = B.IND_CA,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CA,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CA,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_HC

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV06CDATMP

--- COMANDO: LOAD_HC_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV06CDATMP
(CVE_ID_TRAMITE,IND_HC)
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV06_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '4'
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_HC_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_HC

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV06CDA A
USING DIT_BIT_FLUJO_ARCH_MOV06CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_HC = B.IND_HC,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_HC,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_HC,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_HC_BDTU

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV06CDATMP

--- COMANDO: LOAD_HC_TMP_BDTU

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV06CDATMP
(CVE_ID_TRAMITE,IND_HC)
(SELECT DISTINCT T3.CVE_ID_TRAMITE,1 AS IND_HC FROM MGCARGA1.DIT_BITACORA_PROC_MOV06_CDA T3 
WHERE NOT EXISTS
(SELECT 
T1.CVE_ID_TRAMITE,
T2.NSS
FROM MGCARGA1.DIT_BITACORA_PROC_MOV06_CDA T1,D_SINDO_SSAS_ASEG_HIST_CENTRAL T2
WHERE T2.NSS=(T1.NUM_NSS||T1.DIGITO_VERIFICADOR_NSS)
--AND T1.CVE_ID_TRAMITE=T3.CVE_ID_TRAMITE
AND TRUNC(T1.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
AND TRUNC(T3.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_HC_TMP_BDTU

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV06CDATMP GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_HC_BDTU

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV06CDA A
USING DIT_BIT_FLUJO_ARCH_MOV06CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_HC = B.IND_HC,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_HC,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_HC,SYSDATE)


--======================================================
--- PASO: SP_UPD_DIT_BIT_FLUJO_ARCH_v2
--======================================================

--- COMANDO: ACTUALIZA_HISTORICO_CENTRAL

update DIT_BIT_FLUJO_ARCH_MOV06CDA BIT set IND_HC = 1 
--select * from DIT_BIT_FLUJO_ARCH_MOV06CDA BIT
where exists (
    select 1 
    from DIT_BIT_FLUJO_ARCH_MOV06CDA BITA, DIT_BITACORA_PROC_MOV06_CDA REG
    WHERE BIT.CVE_ID_TRAMITE = BITA.CVE_ID_TRAMITE
        and REG.CVE_ID_TRAMITE = BITA.CVE_ID_TRAMITE
        AND TRUNC(REG.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE)
        AND TRUNC(BITA.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
        AND BITA.IND_HC IS NULL
        AND NOT EXISTS ( SELECT 1 FROM D_SINDO_SSAS_ASEG_HIST_CENTRAL HIST
                          WHERE HIST.NSS = REG.NUM_NSS|| REG.DIGITO_VERIFICADOR_NSS)
)

--- COMANDO: UPDATE_REF_OBS

UPDATE DIT_BIT_FLUJO_ARCH_MOV06CDA T1
SET T1.REF_OBSERVACION =
(SELECT LISTAGG(T2.REF_OBSERVACION, chr(10)) WITHIN GROUP (ORDER BY T2.REF_OBSERVACION) "REF_OBSERVACION"
FROM DIT_BITACORA_PROC_MOV06_CDA T2
WHERE T2.CVE_ID_RESULTADO <> '000'
AND  T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND TRUNC(T2.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE)
GROUP BY T2.CVE_ID_TRAMITE
)
WHERE EXISTS(
SELECT 1 
FROM DIT_BITACORA_PROC_MOV06_CDA T2
WHERE T2.CVE_ID_TRAMITE=T1.CVE_ID_TRAMITE
AND T2.CVE_ID_RESULTADO <> '000'
AND TRUNC(T2.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: UPDATE_VALIDA_ESTADO

UPDATE DIT_BIT_FLUJO_ARCH_MOV06CDA T1
SET (T1.IND_VALIDA,T1.REF_ESTADO_SOLICITUD,T1.REF_ESTADO_TRAMITE) =
(
SELECT 
CASE WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_CA+IND_HC) = 5 THEN 1
           WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_HC) in (0,1,2,3) THEN 1
           WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3)  =0 THEN 1
ELSE 0
END IND_VALIDA,
CASE WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_CA+IND_HC) = 5 THEN 5
ELSE 5
END REF_ESTADO_SOLICITUD,
CASE WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_CA+IND_HC) = 5 THEN 88
ELSE 85
END REF_ESTADO_TRAMITE
FROM DIT_BIT_FLUJO_ARCH_MOV06CDA T2
WHERE T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
GROUP BY T2.CVE_ID_TRAMITE)
WHERE EXISTS(
SELECT 1 
FROM DIT_BIT_FLUJO_ARCH_MOV06CDA T2
WHERE T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
GROUP BY T2.CVE_ID_TRAMITE)

--- COMANDO: DIT_MOV_ACLARACION_NSS_CDA 

UPDATE DIT_MOV_ACLARACION_NSS_CDA T1 SET (T1.CVE_ID_ESTADO_MOV_ENV_SINDO,T1.FEC_REGISTRO_ACTUALIZADO)=
(SELECT 
    CASE WHEN T2.REF_ESTADO_TRAMITE = '88' THEN 3  ELSE 2  END ,  SYSDATE
    FROM DIT_BIT_FLUJO_ARCH_MOV06CDA T2
    WHERE 1=1
      AND T1.CVE_ID_MOV_ACLARACION_NSS=T2.CVE_ID_TRAMITE
      AND T2.IND_VALIDA=1
      AND T1.CVE_ID_ESTADO_MOV_ENV_SINDO = 1
      AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
  )
WHERE EXISTS(SELECT 1 FROM DIT_BIT_FLUJO_ARCH_MOV06CDA T3
              WHERE 1=1
              AND T1.CVE_ID_MOV_ACLARACION_NSS=T3.CVE_ID_TRAMITE
              AND T3.IND_VALIDA=1
              AND T1.CVE_ID_ESTADO_MOV_ENV_SINDO = 1
            AND TRUNC(T3.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE))

--- COMANDO: UPDATEESTADOMOV

UPDATE DIT_MOV_ACLARACION_NSS_CDA T1 SET (T1.CVE_ID_ESTADO_MOV_ENV_SINDO,T1.FEC_REGISTRO_ACTUALIZADO)=
(SELECT T2.CVE_ID_ESTADO_MOV_ENV_SINDO, T2.FEC_REGISTRO_ACTUALIZADO
    FROM DIT_MOV_ACLARACION_NSS_CDA T2
    WHERE 1=1
      AND T1.CVE_ID_DETALLE_NSS_CDA=T2.CVE_ID_DETALLE_NSS_CDA
      AND T2.CVE_ID_TIPO_NSS_ACLARACION IN (1,2)
      AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
      AND T2.CVE_ID_ESTADO_MOV_ENV_SINDO in(2,3)
  )
WHERE EXISTS(SELECT 1 FROM DIT_MOV_ACLARACION_NSS_CDA T3
             WHERE 1=1
             AND T1.CVE_ID_DETALLE_NSS_CDA=T3.CVE_ID_DETALLE_NSS_CDA
             AND T3.CVE_ID_TIPO_NSS_ACLARACION IN (1,2)
             AND TRUNC(T3.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
             AND T3.CVE_ID_ESTADO_MOV_ENV_SINDO in (2,3))
and T1.CVE_ID_ESTADO_MOV_ENV_SINDO = 1
