--============================================================================================================
--Script del flujo "Envio de informacion a SINDO MOVIMIENTO CI" paquete: PKG_LOAD_CDA_MOVCI_ENV_PROD
-- Ambiente:                 Prod
-- Autores                   Omar Pérez Chavira 
-- Fecha                     30/Nov/2020
--============================================================================================================


--======================================================
--- PASO: SP_CREA_TMP_ENV_MOVCI_ACT
--======================================================
--- COMANDO: DROP_TEMP

DROP TABLE ENVIO_MOVCI_SINDO_TMP

--- COMANDO: CREA_TMP_MOVCI

CREATE TABLE ENVIO_MOVCI_SINDO_TMP 
TABLESPACE MG_TS_N_DATA_002_TRABAJO 
AS
SELECT  LPAD(CIC.CVE_ID_CORRECCION_CTA_IND_CDA,22,'0')||'CDA' AS FOLSOL,
        LPAD(CTAO.CVE_DELEGACION_ORIGEN, 2,'0') AS DELEGORIG,
        SUBSTR(CTAO.CVE_REGISTRO_PATRONAL, 1,8) AS REGPATORIG,
        CTAO.CVE_MODALIDAD AS MODPATORIG,
        CASE WHEN CIC.CVE_ID_MOV_OPER_ORIGEN = 'I' THEN 'A' ELSE CIC.CVE_ID_MOV_OPER_ORIGEN END  AS TIPOOPORIG,
        --CIC.CVE_ID_MOV_CORRECCION AS TIPOOPORIG,
        SUBSTR(CTAO.NSS,1,10) AS NSSORIG,
        SUBSTR(CTAO.NSS,11,1) AS DVNSSORIG,
        TO_CHAR(TO_DATE(CTAO.FEC_RECEPCION_MOV,'dd/mm/yyyy'),'DDMMYYYY') AS FERECMOVORIG,
        LPAD(CTAO.CVE_TIPO_INI_MOV, 2 ,'0') TIPMOVINIORIG,
        CTAO.CVE_INI_MOV AS ORIGMOVINIORIG, 
        --'0' AS ORIGMOVINIORIG,
        TO_CHAR(TO_DATE(CTAO.FEC_INI_MOV,'dd/mm/yyyy'),'DDMMYYYY') FECMOVINIORIG,
        LPAD(TRIM(replace( to_char(CTAO.SALARIO_BASE, '999999D99'), '.', '')),6, '0') AS SALBASEORIG,
        NVL(TRIM(CTAO.CVE_TIPO_SALARIO), '0') as TIPOSALORIG,
        NVL(TRIM(CTAO.CVE_EVENTUAL),0) AS TIPOTRABORIG,
        NVL(TRIM(CTAO.CVE_EXT_CONV_SUSP),0) AS EXTEMPORIG,
        NVL(TRIM(CTAO.CVE_SUBR_SERVICIOS),0) AS SUBROGSERVORIG,
        LPAD(CTAO.CVE_TIPO_FIN_MOV, 2, '0')  AS TIPOMOVFINORIG,
        CTAO.CVE_FIN_MOV  AS ORIGMOVFINORIG, 
        --'0' AS ORIGMOVFINORIG,
        CASE WHEN NVL(TO_CHAR(TO_DATE(CTAO.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') = '31129999' THEN '00000000' ELSE 
            NVL(TO_CHAR(TO_DATE(CTAO.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') END AS FEMOVFINORIG,
        NVL(TRIM(CTAO.CVE_JORNADA_SEMANAL),0) JORSEMORIG,
       CASE WHEN LPAD(CTAO.CVE_CONSEC_PERIODOS, 3, '0') is null THEN '000' else LPAD(CTAO.CVE_CONSEC_PERIODOS, 3, '0') end NUMCONSPERORIG,
        --LPAD(CTAO.CVE_CONSEC_PERIODOS, 3, '0') NUMCONSPERORIG,
        NVL(CTAO.CURP,'                  ') AS CURPORIG,
        SUBSTR(CTAD.CVE_REGISTRO_PATRONAL,1,8) AS REGPATDEST,                                           
        CTAD.CVE_MODALIDAD AS MODPATDEST,                                                   
       -- CIC.CVE_ID_MOV_CORRECCION AS TIPOOPERDEST,
        CASE WHEN CIC.CVE_ID_MOV_OPER_DESTINO = 'I' THEN 'A' ELSE  CIC.CVE_ID_MOV_OPER_DESTINO END  AS TIPOOPERDEST,
        SUBSTR(CTAD.NSS,1,10) NSSDEST,                                              
        SUBSTR(CTAD.NSS,11,1) DVNSSDEST,                                            
        TO_CHAR(TO_DATE(CTAD.FEC_RECEPCION_MOV,'dd/mm/yyyy'),'DDMMYYYY') AS FECRECEPMOVDEST,
        LPAD(CTAD.CVE_TIPO_INI_MOV,2,0) AS TIPOMOVDEST,                                               
        --0' AS ORIMOVINIDEST,
        CTAD.CVE_INI_MOV  AS ORIMOVINIDEST, 
        TO_CHAR(TO_DATE(CTAD.FEC_INI_MOV,'dd/mm/yyyy'),'DDMMYYYY') AS FECMOVINIDEST,        
        LPAD(TRIM(replace( to_char(CTAD.SALARIO_BASE, '999999D99'), '.', '')),6, '0') AS SALBASCOTDEST,
        NVL(TRIM(CTAD.CVE_TIPO_SALARIO), '0') AS TIPOSALDEST,
        NVL(TRIM(CTAD.CVE_EVENTUAL),0) AS TIPOTRABEVEDEST,
        NVL(TRIM(CTAD.CVE_EXT_CONV_SUSP),0) AS EXTEMPDEST,
        NVL(TRIM(CTAD.CVE_SUBR_SERVICIOS),0) AS SUBROGSERVDEST,
        LPAD(CTAD.CVE_TIPO_FIN_MOV, 2, '0')  AS TIPOMOVFINDEST,
        --'0' AS ORIMOVFINDEST,
        CTAD.CVE_FIN_MOV AS ORIMOVFINDEST,
        --TO_CHAR(TO_DATE(CTAD.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY') AS FECMOVFINDEST,
        CASE WHEN NVL(TO_CHAR(TO_DATE(CTAD.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') = '31129999' THEN '00000000' ELSE 
            NVL(TO_CHAR(TO_DATE(CTAD.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') END AS FECMOVFINDEST,
        NVL(TRIM(CTAD.CVE_JORNADA_SEMANAL),0) AS JORNSEMDEST,
        LPAD(TO_CHAR(CIC.IND_CONSECUTIVO_MOVIMIENTO),3,'0') AS NUMPERCONSECDEST,                                       
        NVL(CTAD.CURP,'                  ') CURPORIG2,                                                                       
        TO_CHAR(SYSDATE,'DDMMYYYY') AS FECENVIO,
        LPAD(' ', 50, ' ') AS FILLER
        ,CIC.CVE_ID_CORRECCION_CTA_IND_CDA AS IDTRAMITE
       ,DELE.CVE_CIZ CIZ
       ,CTAD.IND_HISTORICO_CENTRAL 
FROM DIT_SOLICITUD S,
     DIT_TRAMITE T,
     DIT_CORRECCION_DATOS_ASEG DA,
     DIT_DETALLE_NSS_CDA NSS,
     DIT_CORRECCION_CTA_IND_CDA CIC,
     DIT_CTA_IND_NSS_CDA CTAO,
     DIT_CTA_IND_NSS_CDA CTAD,
     DIC_DELEGACION DELE,
     DIT_MOV_ACLARACION_NSS_CDA MOVA 
WHERE S.CVE_ID_SOLICITUD=T.CVE_ID_SOLICITUD
AND CTAO.CVE_DELEGACION_ORIGEN = DELE.CLAVE_DELEGACION
AND T.CVE_ID_TRAMITE=DA.CVE_ID_TRAMITE
AND DA.CVE_ID_CORRECCION_DATOS_ASEG=NSS.CVE_ID_CORRECCION_DATOS_ASEG
and CIC.CVE_ID_CTA_IND_OPER_ORIGEN = CTAO.CVE_ID_CTA_IND  
and CIC.CVE_ID_CTA_IND_OPER_DESTINO = CTAD.CVE_ID_CTA_IND 
AND MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
and MOVA.CVE_ID_MOV_ACLARACION_NSS = CIC.CVE_ID_MOV_ACLARACION_NSS
--AND CTAO.CVE_ID_ORIGEN_PERIODO_CTA_IND =1
--AND CTAD.CVE_ID_ORIGEN_PERIODO_CTA_IND =2
AND S.CVE_ID_ESTADO_SOLICITUD = 5
AND S.CVE_ID_TIPO_SOLICITUD = 50
AND T.CVE_ID_ESTADO_TRAMITE in (75,37)
AND T.CVE_ID_TIPO_TRAMITE =139
AND MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS IN (3,5,6,7)
AND mova.fec_registro_baja is null
AND CIC.fec_registro_baja is null
and cic.CVE_ID_CTA_IND_OPER_DESTINO is not null
AND (CIC.CVE_ID_ESTADO_MOV_ENV_SINDO IS NULL OR CIC.CVE_ID_ESTADO_MOV_ENV_SINDO = 2)
AND NOT EXISTS(
            SELECT SOL2.CVE_ID_SOLICITUD
            FROM DIT_SOLICITUD SOL2 
            INNER JOIN DIT_TRAMITE TRAM ON SOL2.CVE_ID_SOLICITUD = TRAM.CVE_ID_SOLICITUD
            INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
            WHERE SOL2.CVE_ID_ESTADO_SOLICITUD = 5
            AND S.CVE_ID_SOLICITUD = SOL2.CVE_ID_SOLICITUD
            AND TRAM.CVE_ID_TIPO_TRAMITE = 139
            AND T.CVE_ID_ESTADO_TRAMITE in (75,37)
            AND ((MOVA.CVE_ID_TIPO_NSS_ACLARACION IN (1,2) OR MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS IN(1,2,4))
              or (MOVA.CVE_ID_TIPO_NSS_ACLARACION =5 and  MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS =8))
            AND (MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO IS NULL or  MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO != 3)
            AND NSS.CVE_ID_TIPO_NSS IN (1,2,3)
            AND mova.fec_registro_baja is null
            )
union
SELECT  LPAD(CIC.CVE_ID_CORRECCION_CTA_IND_CDA,22,'0')||'CDA' AS FOLSOL,
        LPAD(CTAO.CVE_DELEGACION_ORIGEN, 2,'0') AS DELEGORIG,
        SUBSTR(CTAO.CVE_REGISTRO_PATRONAL, 1,8) AS REGPATORIG,
        CTAO.CVE_MODALIDAD AS MODPATORIG,
        CASE WHEN CIC.CVE_ID_MOV_OPER_ORIGEN = 'I' THEN 'A' ELSE CIC.CVE_ID_MOV_OPER_ORIGEN END  AS TIPOOPORIG,
        --CIC.CVE_ID_MOV_CORRECCION AS TIPOOPORIG,
        SUBSTR(CTAO.NSS,1,10) AS NSSORIG,
        SUBSTR(CTAO.NSS,11,1) AS DVNSSORIG,
        TO_CHAR(TO_DATE(CTAO.FEC_RECEPCION_MOV,'dd/mm/yyyy'),'DDMMYYYY') AS FERECMOVORIG,
        LPAD(CTAO.CVE_TIPO_INI_MOV, 2 ,'0') TIPMOVINIORIG,
        CTAO.CVE_INI_MOV AS ORIGMOVINIORIG,
        --'0' AS ORIGMOVINIORIG,
        TO_CHAR(TO_DATE(CTAO.FEC_INI_MOV,'dd/mm/yyyy'),'DDMMYYYY') FECMOVINIORIG,
        LPAD(TRIM(replace( to_char(CTAO.SALARIO_BASE, '999999D99'), '.', '')),6, '0') AS SALBASEORIG,
        NVL(TRIM(CTAO.CVE_TIPO_SALARIO), '0') as TIPOSALORIG,
        NVL(TRIM(CTAO.CVE_EVENTUAL),0) AS TIPOTRABORIG,
        NVL(TRIM(CTAO.CVE_EXT_CONV_SUSP),0) AS EXTEMPORIG,
        NVL(TRIM(CTAO.CVE_SUBR_SERVICIOS),0) AS SUBROGSERVORIG,
        LPAD(CTAO.CVE_TIPO_FIN_MOV, 2, '0')  AS TIPOMOVFINORIG,
        CTAO.CVE_FIN_MOV  AS ORIGMOVFINORIG,
        --NVL(TO_CHAR(TO_DATE(CTAO.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') AS FEMOVFINORIG,
         CASE WHEN NVL(TO_CHAR(TO_DATE(CTAO.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') = '31129999' THEN '00000000' ELSE 
            NVL(TO_CHAR(TO_DATE(CTAO.FEC_FIN_MOV,'dd/mm/yyyy'),'DDMMYYYY'), '00000000') END AS FEMOVFINORIG,
        NVL(TRIM(CTAO.CVE_JORNADA_SEMANAL),0) JORSEMORIG,
        CASE WHEN LPAD(CTAO.CVE_CONSEC_PERIODOS, 3, '0') is null THEN '000' else LPAD(CTAO.CVE_CONSEC_PERIODOS, 3, '0') end NUMCONSPERORIG,
        --LPAD(CTAO.CVE_CONSEC_PERIODOS, 3, '0') NUMCONSPERORIG,
        NVL(CTAO.CURP,'                  ') AS CURPORIG,
        /*seccion en blanco para movimientos de eliminacion y creacion sobre el mismo NSS */
        LPAD(' ', 8, ' ')  AS REGPATDEST,                                           
        LPAD(' ', 2, ' ') AS MODPATDEST,                                                   
        LPAD(' ', 1, ' ') AS TIPOOPERDEST,
        LPAD(' ', 10, ' ') AS NSSDEST,                                              
        LPAD(' ', 1, ' ') AS DVNSSDEST,                                            
        LPAD(' ', 8 , ' ') AS FECRECEPMOVDEST,
        LPAD(' ', 2, ' ') AS TIPOMOVDEST,                                               
        LPAD(' ', 1, ' ') AS ORIMOVINIDEST,                                                             
        LPAD(' ', 8, ' ') AS FECMOVINIDEST,        
        LPAD(' ', 6, ' ') AS SALBASCOTDEST,
        LPAD(' ', 1, ' ') TIPOSALDEST,                                               
        LPAD(' ', 1, ' ') AS TIPOTRABEVEDEST,
        LPAD(' ', 1, ' ') AS EXTEMPDEST,
        LPAD(' ', 1, ' ') AS SUBROGSERVDEST,
        LPAD(' ', 2, ' ') AS TIPOMOVFINDEST,
        LPAD(' ', 1, ' ') AS ORIMOVFINDEST,                                                               
        LPAD(' ', 8, ' ') AS FECMOVFINDEST,              
        LPAD(' ', 1, ' ') AS JORNSEMDEST,
        --LPAD(TO_CHAR(CIC.IND_CONSECUTIVO_MOVIMIENTO),3,'0') AS NUMPERCONSECDEST,                                       
        LPAD(' ', 3, ' ') AS NUMPERCONSECDEST,
        LPAD(' ', 18, ' ')as CURPORIG2,                                                                       
        TO_CHAR(SYSDATE,'DDMMYYYY') AS FECENVIO,
        LPAD(' ', 50, ' ') AS FILLER
        ,CIC.CVE_ID_CORRECCION_CTA_IND_CDA AS IDTRAMITE
       ,DELE.CVE_CIZ CIZ
       ,CTAO.IND_HISTORICO_CENTRAL 
FROM DIT_SOLICITUD S,
     DIT_TRAMITE T,
     DIT_CORRECCION_DATOS_ASEG DA,
     DIT_DETALLE_NSS_CDA NSS,
     DIT_CORRECCION_CTA_IND_CDA CIC,
     DIT_CTA_IND_NSS_CDA CTAO,
     DIC_DELEGACION DELE,
     DIT_MOV_ACLARACION_NSS_CDA MOVA 
WHERE S.CVE_ID_SOLICITUD=T.CVE_ID_SOLICITUD
AND CTAO.CVE_DELEGACION_ORIGEN = DELE.CLAVE_DELEGACION
AND T.CVE_ID_TRAMITE=DA.CVE_ID_TRAMITE
AND DA.CVE_ID_CORRECCION_DATOS_ASEG=NSS.CVE_ID_CORRECCION_DATOS_ASEG
and CIC.CVE_ID_CTA_IND_OPER_ORIGEN = CTAO.CVE_ID_CTA_IND  
AND MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
and MOVA.CVE_ID_MOV_ACLARACION_NSS = CIC.CVE_ID_MOV_ACLARACION_NSS
--AND CTAO.CVE_ID_ORIGEN_PERIODO_CTA_IND =1
--AND CTAD.CVE_ID_ORIGEN_PERIODO_CTA_IND =2
AND S.CVE_ID_ESTADO_SOLICITUD = 5
AND S.CVE_ID_TIPO_SOLICITUD = 50
AND T.CVE_ID_ESTADO_TRAMITE in (75,37)
AND T.CVE_ID_TIPO_TRAMITE =139
AND MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS IN (3,5,6,7)
AND mova.fec_registro_baja is null
AND CIC.fec_registro_baja is null
and cic.CVE_ID_CTA_IND_OPER_DESTINO is null
and cic.CVE_ID_MOV_OPER_ORIGEN <> 'M'
AND (CIC.CVE_ID_ESTADO_MOV_ENV_SINDO IS NULL OR CIC.CVE_ID_ESTADO_MOV_ENV_SINDO = 2)
AND NOT EXISTS(
            SELECT SOL2.CVE_ID_SOLICITUD
            FROM DIT_SOLICITUD SOL2 
            INNER JOIN DIT_TRAMITE TRAM ON SOL2.CVE_ID_SOLICITUD = TRAM.CVE_ID_SOLICITUD
            INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
            WHERE SOL2.CVE_ID_ESTADO_SOLICITUD = 5
            AND S.CVE_ID_SOLICITUD = SOL2.CVE_ID_SOLICITUD
            AND TRAM.CVE_ID_TIPO_TRAMITE = 139
            AND T.CVE_ID_ESTADO_TRAMITE in (75,37)
            AND ((MOVA.CVE_ID_TIPO_NSS_ACLARACION IN (1,2) OR MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS IN(1,2,4))
                 or (MOVA.CVE_ID_TIPO_NSS_ACLARACION =5 and MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS =8))
            AND (MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO IS NULL or  MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO != 3)
            AND NSS.CVE_ID_TIPO_NSS IN (1,2,3)
            AND mova.fec_registro_baja is null
            )


--======================================================
--- PASO: OdiSqlUnload 1
--======================================================

SELECT   FOLSOL       AS FOLSOL           
        ,DELEGORIG   AS DELEGORIG      
        ,REGPATORIG  AS REGPATORIG      
        ,MODPATORIG  AS MODPATORIG   
        ,TIPOOPORIG  AS TIPOOPORIG      
        ,NSSORIG     AS NSSORIG      
        ,DVNSSORIG   AS DVNSSORIG      
        ,FERECMOVORIG    AS FERECMOVORIG  
        ,TIPMOVINIORIG   AS TIPMOVINIORIG 
        ,ORIGMOVINIORIG  AS ORIGMOVINIORIG 
        ,FECMOVINIORIG   AS FECMOVINIORIG 
        ,SALBASEORIG     AS SALBASEORIG  
        ,TIPOSALORIG     AS TIPOSALORIG 
        ,TIPOTRABORIG    AS TIPOTRABORIG 
        ,EXTEMPORIG      AS EXTEMPORIG
        ,SUBROGSERVORIG  AS SUBROGSERVORIG  
        ,TIPOMOVFINORIG  AS TIPOMOVFINORIG  
        ,ORIGMOVFINORIG  AS ORIGMOVFINORIG 
        ,FEMOVFINORIG    AS FEMOVFINORIG 
        ,JORSEMORIG      AS JORSEMORIG 
        ,NUMCONSPERORIG  AS NUMCONSPERORIG
        ,CURPORIG        AS CURPORIG 
        ,REGPATDEST      AS REGPATDEST 
        ,MODPATDEST      AS MODPATDEST 
        ,TIPOOPERDEST    AS TIPOOPERDEST 
        ,NSSDEST         AS NSSDEST 
        ,DVNSSDEST       AS DVNSSDEST 
        ,FECRECEPMOVDEST AS FECRECEPMOVDEST 
        ,TIPOMOVDEST     AS TIPOMOVDEST 
        ,ORIMOVINIDEST   AS ORIMOVINIDEST  
        ,FECMOVINIDEST   AS FECMOVINIDEST 
        ,SALBASCOTDEST   AS SALBASCOTDEST 
        ,TIPOSALDEST     AS TIPOSALDEST 
        ,TIPOTRABEVEDEST AS TIPOTRABEVEDEST
        ,EXTEMPDEST      AS EXTEMPDEST  
        ,SUBROGSERVDEST  AS SUBROGSERVDEST  
        ,TIPOMOVFINDEST  AS TIPOMOVFINDEST  
        ,ORIMOVFINDEST   AS ORIMOVFINDEST 
        ,FECMOVFINDEST   AS FECMOVFINDEST 
        ,JORNSEMDEST     AS JORNSEMDEST  
        ,NUMPERCONSECDEST AS NUMPERCONSECDEST  
        ,CURPORIG2       AS CURPORIG2 
        ,FECENVIO        AS FECENVIO  
        ,FILLER          AS FILLER 
FROM ENVIO_MOVCI_SINDO_TMP
WHERE CIZ = 2
AND IND_HISTORICO_CENTRAL = 0

--======================================================
--- PASO: Copia de OdiSqlUnload 1
--======================================================

SELECT   FOLSOL       AS FOLSOL           
        ,DELEGORIG   AS DELEGORIG      
        ,REGPATORIG  AS REGPATORIG      
        ,MODPATORIG  AS MODPATORIG   
        ,TIPOOPORIG  AS TIPOOPORIG      
        ,NSSORIG     AS NSSORIG      
        ,DVNSSORIG   AS DVNSSORIG      
        ,FERECMOVORIG    AS FERECMOVORIG  
        ,TIPMOVINIORIG   AS TIPMOVINIORIG 
        ,ORIGMOVINIORIG  AS ORIGMOVINIORIG 
        ,FECMOVINIORIG   AS FECMOVINIORIG 
        ,SALBASEORIG     AS SALBASEORIG  
        ,TIPOSALORIG     AS TIPOSALORIG 
        ,TIPOTRABORIG    AS TIPOTRABORIG 
        ,EXTEMPORIG      AS EXTEMPORIG
        ,SUBROGSERVORIG  AS SUBROGSERVORIG  
        ,TIPOMOVFINORIG  AS TIPOMOVFINORIG  
        ,ORIGMOVFINORIG  AS ORIGMOVFINORIG 
        ,FEMOVFINORIG    AS FEMOVFINORIG 
        ,JORSEMORIG      AS JORSEMORIG 
        ,NUMCONSPERORIG  AS NUMCONSPERORIG
        ,CURPORIG        AS CURPORIG 
        ,REGPATDEST      AS REGPATDEST 
        ,MODPATDEST      AS MODPATDEST 
        ,TIPOOPERDEST    AS TIPOOPERDEST 
        ,NSSDEST         AS NSSDEST 
        ,DVNSSDEST       AS DVNSSDEST 
        ,FECRECEPMOVDEST AS FECRECEPMOVDEST 
        ,TIPOMOVDEST     AS TIPOMOVDEST 
        ,ORIMOVINIDEST   AS ORIMOVINIDEST  
        ,FECMOVINIDEST   AS FECMOVINIDEST 
        ,SALBASCOTDEST   AS SALBASCOTDEST 
        ,TIPOSALDEST     AS TIPOSALDEST 
        ,TIPOTRABEVEDEST AS TIPOTRABEVEDEST
        ,EXTEMPDEST      AS EXTEMPDEST  
        ,SUBROGSERVDEST  AS SUBROGSERVDEST  
        ,TIPOMOVFINDEST  AS TIPOMOVFINDEST  
        ,ORIMOVFINDEST   AS ORIMOVFINDEST 
        ,FECMOVFINDEST   AS FECMOVFINDEST 
        ,JORNSEMDEST     AS JORNSEMDEST  
        ,NUMPERCONSECDEST AS NUMPERCONSECDEST  
        ,CURPORIG2       AS CURPORIG2 
        ,FECENVIO        AS FECENVIO  
        ,FILLER          AS FILLER 
FROM ENVIO_MOVCI_SINDO_TMP
WHERE CIZ = 3
AND IND_HISTORICO_CENTRAL = 0

--======================================================
--- PASO: Copia de Copia de OdiSqlUnload 1
--======================================================

SELECT   FOLSOL       AS FOLSOL           
        ,DELEGORIG   AS DELEGORIG      
        ,REGPATORIG  AS REGPATORIG      
        ,MODPATORIG  AS MODPATORIG   
        ,TIPOOPORIG  AS TIPOOPORIG      
        ,NSSORIG     AS NSSORIG      
        ,DVNSSORIG   AS DVNSSORIG      
        ,FERECMOVORIG    AS FERECMOVORIG  
        ,TIPMOVINIORIG   AS TIPMOVINIORIG 
        ,ORIGMOVINIORIG  AS ORIGMOVINIORIG 
        ,FECMOVINIORIG   AS FECMOVINIORIG 
        ,SALBASEORIG     AS SALBASEORIG  
        ,TIPOSALORIG     AS TIPOSALORIG 
        ,TIPOTRABORIG    AS TIPOTRABORIG 
        ,EXTEMPORIG      AS EXTEMPORIG
        ,SUBROGSERVORIG  AS SUBROGSERVORIG  
        ,TIPOMOVFINORIG  AS TIPOMOVFINORIG  
        ,ORIGMOVFINORIG  AS ORIGMOVFINORIG 
        ,FEMOVFINORIG    AS FEMOVFINORIG 
        ,JORSEMORIG      AS JORSEMORIG 
        ,NUMCONSPERORIG  AS NUMCONSPERORIG
        ,CURPORIG        AS CURPORIG 
        ,REGPATDEST      AS REGPATDEST 
        ,MODPATDEST      AS MODPATDEST 
        ,TIPOOPERDEST    AS TIPOOPERDEST 
        ,NSSDEST         AS NSSDEST 
        ,DVNSSDEST       AS DVNSSDEST 
        ,FECRECEPMOVDEST AS FECRECEPMOVDEST 
        ,TIPOMOVDEST     AS TIPOMOVDEST 
        ,ORIMOVINIDEST   AS ORIMOVINIDEST  
        ,FECMOVINIDEST   AS FECMOVINIDEST 
        ,SALBASCOTDEST   AS SALBASCOTDEST 
        ,TIPOSALDEST     AS TIPOSALDEST 
        ,TIPOTRABEVEDEST AS TIPOTRABEVEDEST
        ,EXTEMPDEST      AS EXTEMPDEST  
        ,SUBROGSERVDEST  AS SUBROGSERVDEST  
        ,TIPOMOVFINDEST  AS TIPOMOVFINDEST  
        ,ORIMOVFINDEST   AS ORIMOVFINDEST 
        ,FECMOVFINDEST   AS FECMOVFINDEST 
        ,JORNSEMDEST     AS JORNSEMDEST  
        ,NUMPERCONSECDEST AS NUMPERCONSECDEST  
        ,CURPORIG2       AS CURPORIG2 
        ,FECENVIO        AS FECENVIO  
        ,FILLER          AS FILLER 
FROM ENVIO_MOVCI_SINDO_TMP
WHERE CIZ = 1
AND IND_HISTORICO_CENTRAL = 0

--======================================================
--- PASO: Copia de Copia de Copia de OdiSqlUnload 1
--======================================================

SELECT   FOLSOL       AS FOLSOL           
        ,DELEGORIG   AS DELEGORIG      
        ,REGPATORIG  AS REGPATORIG      
        ,MODPATORIG  AS MODPATORIG   
        ,TIPOOPORIG  AS TIPOOPORIG      
        ,NSSORIG     AS NSSORIG      
        ,DVNSSORIG   AS DVNSSORIG      
        ,FERECMOVORIG    AS FERECMOVORIG  
        ,TIPMOVINIORIG   AS TIPMOVINIORIG 
        ,ORIGMOVINIORIG  AS ORIGMOVINIORIG 
        ,FECMOVINIORIG   AS FECMOVINIORIG 
        ,SALBASEORIG     AS SALBASEORIG  
        ,TIPOSALORIG     AS TIPOSALORIG 
        ,TIPOTRABORIG    AS TIPOTRABORIG 
        ,EXTEMPORIG      AS EXTEMPORIG
        ,SUBROGSERVORIG  AS SUBROGSERVORIG  
        ,TIPOMOVFINORIG  AS TIPOMOVFINORIG  
        ,ORIGMOVFINORIG  AS ORIGMOVFINORIG 
        ,FEMOVFINORIG    AS FEMOVFINORIG 
        ,JORSEMORIG      AS JORSEMORIG 
        ,NUMCONSPERORIG  AS NUMCONSPERORIG
        ,CURPORIG        AS CURPORIG 
        ,REGPATDEST      AS REGPATDEST 
        ,MODPATDEST      AS MODPATDEST 
        ,TIPOOPERDEST    AS TIPOOPERDEST 
        ,NSSDEST         AS NSSDEST 
        ,DVNSSDEST       AS DVNSSDEST 
        ,FECRECEPMOVDEST AS FECRECEPMOVDEST 
        ,TIPOMOVDEST     AS TIPOMOVDEST 
        ,ORIMOVINIDEST   AS ORIMOVINIDEST  
        ,FECMOVINIDEST   AS FECMOVINIDEST 
        ,SALBASCOTDEST   AS SALBASCOTDEST 
        ,TIPOSALDEST     AS TIPOSALDEST 
        ,TIPOTRABEVEDEST AS TIPOTRABEVEDEST
        ,EXTEMPDEST      AS EXTEMPDEST  
        ,SUBROGSERVDEST  AS SUBROGSERVDEST  
        ,TIPOMOVFINDEST  AS TIPOMOVFINDEST  
        ,ORIMOVFINDEST   AS ORIMOVFINDEST 
        ,FECMOVFINDEST   AS FECMOVFINDEST 
        ,JORNSEMDEST     AS JORNSEMDEST  
        ,NUMPERCONSECDEST AS NUMPERCONSECDEST  
        ,CURPORIG2       AS CURPORIG2 
        ,FECENVIO        AS FECENVIO  
        ,FILLER          AS FILLER 
FROM ENVIO_MOVCI_SINDO_TMP
WHERE IND_HISTORICO_CENTRAL = 1

--======================================================
--- PASO: SP_UPDDROP_TMP_ENV_MOVCI
--======================================================

--- COMANDO: INS_BIT_CDA_CI

INSERT INTO DIT_BITACORA_PROC_ENVIO_CDA
SELECT FOLSOL,'MOVCI', 37, 'ODI', 'SINDO', SYSDATE, NULL, NULL 
FROM ENVIO_MOVCI_SINDO_TMP

--- COMANDO: UPDATE DIT_CORRECCION_CTA_IND_CDA 

UPDATE DIT_CORRECCION_CTA_IND_CDA MOV SET MOV.CVE_ID_ESTADO_MOV_ENV_SINDO = 1, MOV.FEC_REGISTRO_ACTUALIZADO = SYSDATE, MOV.FEC_MOV_ENV_SINDO = SYSDATE
WHERE EXISTS(
   SELECT IDTRAMITE FROM  ENVIO_MOVCI_SINDO_TMP  ENVIOS
    WHERE ENVIOS.IDTRAMITE = MOV.CVE_ID_CORRECCION_CTA_IND_CDA
  )

--- COMANDO: UPD_DIT_TRAMITE

--ACTUALIZACOPON DEL TRAMITE PARA MOVIMIENTOS DE CUENTA INDIVIDUAL
UPDATE DIT_TRAMITE T SET T.CVE_ID_ESTADO_TRAMITE = 37,  T.FEC_REGISTRO_ACTUALIZADO = SYSDATE 
WHERE EXISTS(
SELECT TRAM.CVE_ID_TRAMITE
FROM DIT_TRAMITE TRAM
    INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
    INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
    INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
    INNER JOIN DIT_CORRECCION_CTA_IND_CDA CTA ON CTA.CVE_ID_MOV_ACLARACION_NSS = MOVA.CVE_ID_MOV_ACLARACION_NSS
WHERE TRAM.CVE_ID_ESTADO_TRAMITE = 75
    AND TRAM.CVE_ID_TIPO_TRAMITE =139
    AND CTA.CVE_ID_ESTADO_MOV_ENV_SINDO = 1
    AND TRUNC(CTA.FEC_MOV_ENV_SINDO) = TRUNC(SYSDATE)
    AND TRAM.CVE_ID_TRAMITE = T.CVE_ID_TRAMITE
  )

--- COMANDO: DROP_ENV_MOVCI

DROP TABLE ENVIO_MOVCI_SINDO_TMP 
  
 