--============================================================================================================
--Script del flujo "Retorno de informacion de SINDO MOVIMIENTO CI" paquete: PKG_LOAD_CDA_MOVCI_OSD_PROD
-- Ambiente:                 Prod
-- Autores                   Omar Pérez Chavira 
-- Fecha                     30/Nov/2020
--============================================================================================================


--======================================================
--- PASO: SP_LOAD_FILES_SINDO
--======================================================
--- COMANDO: DELETE TABLE TMP

DELETE FROM  DIT_BITACORA_PROC_MOVCI_CDA_CP


--======================================================
--- PASO: SP_LOAD_DIT_BITACORA_PROC_MOVCI
--======================================================
--- COMANDO: SP_LOAD_DIT_BITACORA_PROC_SINDO

INSERT INTO /*+ APPEND*/  DIT_BITACORA_PROC_MOVCI_CDA
 (CVE_ID_CDA_SINDO_MOVCI,
  CVE_ID_CDA_MOVCI,
  NOMBRE_ARCHIVO,
 -- FOLIO_SOLICITUD,
  CVE_DELEG_ORIG,
  REG_PATRONAL_ORIG,
  MOD_PATRON_ORIG,
  TIPO_OPER_ORIG,
  NSS_ORIG,
  DV_NSS_ORIG,
  FEC_RECEP_MOV_ORIG,
  TIPO_MOV_INI_ORIG,
  ORIG_MOV_INI_ORIG,
  FEC_MOV_INI_ORIG,
  SAL_BASE_COTIZ,
  TIPO_SAL_ORIG,
  TIPO_TRABAJ_ORIG,
  EXTEMPOR_ORIG,
  SUBROGAC_SERV_ORIG,
  TIPO_MOV_FIN_ORIG,
  ORIG_MOV_FIN_ORIG,
  FEC_MOV_FIN_ORIG,
  JORN_SEMANAL_ORIG,
  NUM_CONSEC_ORIG,
  CURP_ORIG,
  REG_PATR_DEST,
  MOD_PATRON_DEST,
  TIPO_OPER_DEST,
  NSS_DESTINO,
  DV_NSS_DEST,
  FEC_RECEP_MOV_DEST,
  TIPO_MOV_INIC_DEST,
  ORIG_MOV_INIC_DEST,
  FEC_MOV_INI_DEST,
  SAL_BASE_COTIZ_DEST,
  TIPO_SALARIO_DEST,
  TIPO_TRABAJ_DEST,
  EXTEMPOR_DEST,
  SUBROG_SERV_DEST,
  TIPO_MOV_FINAL_DEST,
  ORIG_MOV_FIN_DEST,
  FEC_MOV_FIN_DEST,
  JORN_SEMAN_DEST,
  NUM_CONSEC_PERIOD_DEST,
  CURP_ORIGEN,
  ORIG_DEST,
  FEC_ENVIO,
  FEC_IMPAC_MOV,
  IDENTIF_ERROR,
  FILLER,
  CVE_ID_TRAMITE,
  FEC_REGISTRO_ALTA)
(
SELECT 
  SEQ_DITCDAMOVCI.NEXTVAL,
  B.CVE_ID_CDA_MOVCI,
  B.NOMBRE_ARCHIVO,
 -- B.FOLIO_SOLICITUD,
  B.CVE_DELEG_ORIG,
  B.REG_PATRONAL_ORIG,
  B.MOD_PATRON_ORIG,
  B.TIPO_OPER_ORIG,
  B.NSS_ORIG,
  B.DV_NSS_ORIG,
  B.FEC_RECEP_MOV_ORIG,
  B.TIPO_MOV_INI_ORIG,
  B.ORIG_MOV_INI_ORIG,
  B.FEC_MOV_INI_ORIG,
  B.SAL_BASE_COTIZ,
  B.TIPO_SAL_ORIG,
  B.TIPO_TRABAJ_ORIG,
  B.EXTEMPOR_ORIG,
  B.SUBROGAC_SERV_ORIG,
  B.TIPO_MOV_FIN_ORIG,
  B.ORIG_MOV_FIN_ORIG,
  B.FEC_MOV_FIN_ORIG,
  B.JORN_SEMANAL_ORIG,
  B.NUM_CONSEC_ORIG,
  B.CURP_ORIG,
  B.REG_PATR_DEST,
  B.MOD_PATRON_DEST,
  B.TIPO_OPER_DEST,
  B.NSS_DESTINO,
  B.DV_NSS_DEST,
  B.FEC_RECEP_MOV_DEST,
  B.TIPO_MOV_INIC_DEST,
  B.ORIG_MOV_INIC_DEST,
  B.FEC_MOV_INI_DEST,
  B.SAL_BASE_COTIZ_DEST,
  B.TIPO_SALARIO_DEST,
  B.TIPO_TRABAJ_DEST,
  B.EXTEMPOR_DEST,
  B.SUBROG_SERV_DEST,
  B.TIPO_MOV_FINAL_DEST,
  B.ORIG_MOV_FIN_DEST,
  B.FEC_MOV_FIN_DEST,
  B.JORN_SEMAN_DEST,
  B.NUM_CONSEC_PERIOD_DEST,
  B.CURP_ORIGEN,
  B.ORIG_DEST,
  B.FEC_ENVIO,
  B.FEC_IMPAC_MOV,
  B.IDENTIF_ERROR,
  B.FILLER,
  B.CVE_ID_TRAMITE,
  SYSDATE AS FEC_REGISTRO_ALTA
FROM DIT_BITACORA_PROC_MOVCI_CDA_CP B
)

--- COMANDO: UPD_REF_OBSERVACION_MOVCI

UPDATE DIT_BITACORA_PROC_MOVCI_CDA t1
SET REF_OBSERVACION =(
            select OBSERVACION
            from (
            select bit2.CVE_ID_CDA_SINDO_MOVCI, bit2.IDENTIF_ERROR||'|'||bit2.CVE_ID_CDA_MOVCI||'|'||res.DES_RESULTADO as OBSERVACION
            from DIT_BITACORA_PROC_MOVCI_CDA bit2, DIC_RESULTADO_CDA_SINDO res
            where (trunc(bit2.FEC_REGISTRO_ALTA) = trunc(sysdate) or trunc(bit2.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate))
            and bit2.IDENTIF_ERROR = res.CVE_ID_RESULTADO(+)
            and bit2.IDENTIF_ERROR <> '000'
            ) detalle
            where 1=1
            and detalle.CVE_ID_CDA_SINDO_MOVCI = t1.CVE_ID_CDA_SINDO_MOVCI)
where (trunc(t1.FEC_REGISTRO_ALTA) = trunc(sysdate) or trunc(T1.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate))
and t1.NUM_CONSEC_ORIG <> '000'
and exists (
            select bit2.rowid
            from DIT_BITACORA_PROC_MOVCI_CDA bit2, DIC_RESULTADO_CDA_SINDO res
            where (trunc(bit2.FEC_REGISTRO_ALTA) = trunc(sysdate) or trunc(bit2.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate))
            and bit2.IDENTIF_ERROR = res.CVE_ID_RESULTADO(+)
            and bit2.IDENTIF_ERROR <> '000'
            and bit2.CVE_ID_CDA_SINDO_MOVCI = t1.CVE_ID_CDA_SINDO_MOVCI
)

--======================================================
--- PASO: SP_LOAD_DIT_BIT_FLUJO_ARCH_MOVCI
--======================================================


--- COMANDO: TRUNCATE_TABLA_TMP_CIZ1

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOVCICDATMP

--- COMANDO: LOAD_CIZ1_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOVCICDATMP
(CVE_ID_TRAMITE,IND_CIZ1)   
(SELECT  CVE_ID_TRAMITE, 1
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'OPERADOS_CDA_CI_CIZ01_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
UNION ALL
(SELECT  CVE_ID_TRAMITE, 0
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'ERRORES_CDA_CI_CIZ01_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ1_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ1

MERGE INTO DIT_BIT_FLUJO_ARCH_MOVCICDA A
USING DIT_BIT_FLUJO_ARCH_MOVCICDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ1 = B.IND_CIZ1, A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ1,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ1,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CIZ2

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOVCICDATMP

--- COMANDO: LOAD_CIZ2_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOVCICDATMP
(CVE_ID_TRAMITE,IND_CIZ2)   
(SELECT  CVE_ID_TRAMITE, 1
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'OPERADOS_CDA_CI_CIZ02_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
UNION ALL
(SELECT  CVE_ID_TRAMITE, 0
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'ERRORES_CDA_CI_CIZ02_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ2_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ2

MERGE INTO DIT_BIT_FLUJO_ARCH_MOVCICDA A
USING DIT_BIT_FLUJO_ARCH_MOVCICDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ2 = B.IND_CIZ2,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ2,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ2,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CIZ3

DELETE FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP

--- COMANDO: LOAD_CIZ3_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOVCICDATMP
(CVE_ID_TRAMITE,IND_CIZ3)   
(SELECT  CVE_ID_TRAMITE, 1
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'OPERADOS_CDA_CI_CIZ03_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
UNION ALL
(SELECT  CVE_ID_TRAMITE, 0
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'ERRORES_CDA_CI_CIZ03_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ3_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ3

MERGE INTO DIT_BIT_FLUJO_ARCH_MOVCICDA A
USING DIT_BIT_FLUJO_ARCH_MOVCICDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ3 = B.IND_CIZ3,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ3,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ3,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CA

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOVCICDATMP

--- COMANDO: LOAD_CA_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOVCICDATMP
(CVE_ID_TRAMITE,IND_CA)   
(SELECT  CVE_ID_TRAMITE, 1
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'OPERADOS_CDA_CI_CANAS_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
UNION ALL
(SELECT  CVE_ID_TRAMITE, 0
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'ERRORES_CDA_CI_CANAS_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CA_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CA

MERGE INTO DIT_BIT_FLUJO_ARCH_MOVCICDA A
USING DIT_BIT_FLUJO_ARCH_MOVCICDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CA = B.IND_CA,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CA,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CA,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_HC

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOVCICDATMP

--- COMANDO: LOAD_HC_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOVCICDATMP
(CVE_ID_TRAMITE,IND_HC)   
(SELECT  CVE_ID_TRAMITE, 1
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'OPERADOS_CDA_CI_HISTC_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
UNION ALL
(SELECT  CVE_ID_TRAMITE, 0
END FROM DIT_BITACORA_PROC_MOVCI_CDA
WHERE NOMBRE_ARCHIVO LIKE  'ERRORES_CDA_CI_HISTC_%' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_HC_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOVCICDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_HC

MERGE INTO DIT_BIT_FLUJO_ARCH_MOVCICDA A
USING DIT_BIT_FLUJO_ARCH_MOVCICDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_HC = B.IND_HC,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_HC,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_HC,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_HC_BDTU

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOVCICDATMP


--======================================================
--- PASO: SP_UPD_DIT_BIT_FLUJO_ARCH_MOVCI
--======================================================

--- COMANDO: UPDATE_REF_OBS

UPDATE DIT_BIT_FLUJO_ARCH_MOVCICDA t1
SET REF_OBSERVACION = (
            SELECT LISTAGG(bit2.REF_OBSERVACION, chr(10)) WITHIN GROUP (ORDER BY bit2.REF_OBSERVACION) "REF_OBSERVACION"
            from DIT_BITACORA_PROC_MOVCI_CDA bit2 
            where (trunc(bit2.FEC_REGISTRO_ALTA) = trunc(sysdate) or trunc(bit2.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate))
            and bit2.IDENTIF_ERROR <> '000'
            and bit2.CVE_ID_TRAMITE = t1.CVE_ID_TRAMITE
          ) , FEC_REGISTRO_ACTUALIZADO = SYSDATE 
where (trunc(t1.FEC_REGISTRO_ALTA) = trunc(sysdate) or trunc(T1.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate))
and exists (
            select bit2.rowid
            from DIT_BITACORA_PROC_MOVCI_CDA bit2 
            where (trunc(bit2.FEC_REGISTRO_ALTA) = trunc(sysdate) or trunc(bit2.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate))
            and bit2.IDENTIF_ERROR <> '000'
            and bit2.CVE_ID_TRAMITE = t1.CVE_ID_TRAMITE)

--- COMANDO: UPDATE VALIDA ESTADO

UPDATE DIT_BIT_FLUJO_ARCH_MOVCICDA T1
SET (T1.IND_VALIDA,T1.REF_ESTADO_SOLICITUD,T1.REF_ESTADO_TRAMITE) =
(
SELECT 
CASE WHEN SUM(NVL(IND_CIZ1,2)+ NVL(IND_CIZ2,2)+ NVL(IND_CIZ3,2) + NVL(IND_HC,2)) = 6 THEN 1
     WHEN SUM(NVL(IND_CIZ1,2)+ NVL(IND_CIZ2,2)+ NVL(IND_CIZ3,2) + NVL(IND_HC,2)) = 7 THEN 1
      ELSE null
END IND_VALIDA,
CASE WHEN SUM(NVL(IND_CIZ1,0)+ NVL(IND_CIZ2,0)+ NVL(IND_CIZ3,0) + NVL(IND_HC,0)) = 1 THEN 5
ELSE 5
END REF_ESTADO_SOLICITUD,
CASE WHEN SUM (NVL(IND_CIZ1,0)+ NVL(IND_CIZ2,0)+ NVL(IND_CIZ3,0) + NVL(IND_HC,0)) = 1 THEN 88
ELSE 85
END REF_ESTADO_TRAMITE
FROM DIT_BIT_FLUJO_ARCH_MOVCICDA T2
WHERE T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND (TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE) or TRUNC(T2.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
GROUP BY T2.CVE_ID_TRAMITE)
WHERE EXISTS(
SELECT 1 
FROM DIT_BIT_FLUJO_ARCH_MOVCICDA T2
WHERE T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND (TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE) or TRUNC(T2.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))
GROUP BY T2.CVE_ID_TRAMITE)

