--============================================================================================================
--Script del flujo "Retorno de informacion de SINDO MOVIMIENTO 05" paquete: PKG_LOAD_CDA_MOV05_OSD_PROD
-- Ambiente:                 Prod
-- Autores                   Omar Pérez Chavira 
-- Fecha                     30/Nov/2020
--============================================================================================================


--======================================================
--- PASO: SP_LOAD_FILES_MOV05
--======================================================
--- COMANDO: DELETE DIT_BITACORA_PROC_MOV05_CDA_CP

DELETE FROM  DIT_BITACORA_PROC_MOV05_CDA_CP


--======================================================
--- PASO: SP_LOAD_DIT_BITACORA_PROC_MOV05
--======================================================
--- COMANDO: SP_LOAD_DIT_BITACORA_PROC_SINDO

INSERT INTO /*+ APPEND*/  DIT_BITACORA_PROC_MOV05_CDA
(CVE_ID_CDA_SINDO,
CVE_ID_TRAMITE, 
CLAVE_DELEGACION,  
CLAVE_SUBDELEGACION,
FEC_INICIO_MOVIMIENTO,         
FEC_FIN_MOVIMIENTO,       
NOM_NOMBRE_ASEGURADO_C,
FEC_REGISTRO_ALTA,        
FEC_REGISTRO_BAJA,       
FEC_REGISTRO_ACTUALIZADO,        
NUM_NSS, 
CVE_ID_RESULTADO,   
CVE_ID_ORIGEN_RES_MVTO, 
DIGITO_VERIFICADOR_NSS)
(
SELECT 
SEQ_DITCDAMOV05.NEXTVAL,
CVE_ID_TRAMITE, 
CLAVE_DELEGACION,  
CLAVE_SUBDELEGACION,
FEC_INICIO_MOVIMIENTO,     
FEC_FIN_MOVIMIENTO,       
NOM_NOMBRE_ASEGURADO_C,
FEC_REGISTRO_ALTA,        
FEC_REGISTRO_BAJA,       
FEC_REGISTRO_ACTUALIZADO,        
NUM_NSS, 
CVE_ID_RESULTADO,   
CVE_ID_ORIGEN_RES_MVTO, 
DIGITO_VERIFICADOR_NSS
FROM 
DIT_BITACORA_PROC_MOV05_CDA_CP A
)

--- COMANDO: UPD_REF_OBSERVACION_MOV05

UPDATE DIT_BITACORA_PROC_MOV05_CDA t1
SET REF_OBSERVACION =
(SELECT t3.CVE_ID_RESULTADO||'|'||t3.CVE_ID_ORIGEN_RES_MVTO||'|'||t4.DES_RESULTADO 
    from DIT_BITACORA_PROC_MOV05_CDA t3,
             DIC_RESULTADO_CDA_SINDO t4
WHERE  1=1 
AND t1.CVE_ID_CDA_SINDO=t3.CVE_ID_CDA_SINDO
AND t3.CVE_ID_RESULTADO=t4.CVE_ID_RESULTADO
)
WHERE T1.CVE_ID_RESULTADO not in ('000', '999')
AND TRUNC(t1.FEC_REGISTRO_ALTA)=TRUNC(sysdate)


--======================================================
--- PASO: SP_LOAD_DIT_BIT_FLUJO_ARCH_MOV05
--======================================================


--- COMANDO: TRUNCATE_TABLA_TMP_CIZ1

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV05CDATMP


--- COMANDO: LOAD_CIZ1_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV05CDATMP
(CVE_ID_TRAMITE,IND_CIZ1)   
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO 
  WHEN '000' THEN '1'
-- WHEN '999' THEN '1'
  ELSE '0' 
END 
FROM DIT_BITACORA_PROC_MOV05_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '1' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ1_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ1

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV05CDA A
USING DIT_BIT_FLUJO_ARCH_MOV05CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ1 = B.IND_CIZ1, A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ1,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ1,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CIZ2

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV05CDATMP

--- COMANDO: LOAD_CIZ2_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV05CDATMP
(CVE_ID_TRAMITE,IND_CIZ2) 
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
--WHEN '999' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV05_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '2' 
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ2_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ2

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV05CDA A
USING DIT_BIT_FLUJO_ARCH_MOV05CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ2 = B.IND_CIZ2,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ2,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ2,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CIZ3

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV05CDATMP

--- COMANDO: LOAD_CIZ3_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV05CDATMP
(CVE_ID_TRAMITE,IND_CIZ3)
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
--WHEN '999' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV05_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '3'
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CIZ3_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CIZ3

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV05CDA A
USING DIT_BIT_FLUJO_ARCH_MOV05CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CIZ3 = B.IND_CIZ3,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CIZ3,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CIZ3,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_CA

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV05CDATMP

--- COMANDO: LOAD_CA_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV05CDATMP
(CVE_ID_TRAMITE,IND_CA)
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
--WHEN '999' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV05_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '5'
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_CA_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_CA

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV05CDA A
USING DIT_BIT_FLUJO_ARCH_MOV05CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_CA = B.IND_CA,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_CA,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_CA,SYSDATE)

--- COMANDO: TRUNCATE_TABLA_TMP_HC

DELETE FROM  DIT_BIT_FLUJO_ARCH_MOV05CDATMP

--- COMANDO: LOAD_HC_TMP

INSERT INTO DIT_BIT_FLUJO_ARCH_MOV05CDATMP
(CVE_ID_TRAMITE,IND_HC)
(SELECT  CVE_ID_TRAMITE, 
CASE CVE_ID_RESULTADO WHEN '000' THEN '1'
ELSE '0' 
END FROM DIT_BITACORA_PROC_MOV05_CDA
WHERE CVE_ID_ORIGEN_RES_MVTO = '4'
AND TRUNC(FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: DELETE_DUPLICADOS_HC_TMP

DELETE FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM DIT_BIT_FLUJO_ARCH_MOV05CDATMP 
GROUP BY CVE_ID_TRAMITE)

--- COMANDO: MERGE_REGISTROS_HC

MERGE INTO DIT_BIT_FLUJO_ARCH_MOV05CDA A
USING DIT_BIT_FLUJO_ARCH_MOV05CDATMP B 
ON (A.CVE_ID_TRAMITE = B.CVE_ID_TRAMITE)
WHEN MATCHED THEN UPDATE SET IND_HC = B.IND_HC,A.FEC_REGISTRO_ACTUALIZADO = SYSDATE
WHEN NOT MATCHED THEN INSERT (CVE_ID_TRAMITE,IND_HC,FEC_REGISTRO_ALTA)
VALUES (B.CVE_ID_TRAMITE,B.IND_HC,SYSDATE)


--======================================================
--- PASO: SP_UPD_DIT_BIT_FLUJO_ARCHMOV05
--======================================================

--- COMANDO: UPDATE_REF_OBS_MOV05

UPDATE DIT_BIT_FLUJO_ARCH_MOV05CDA T1
SET T1.REF_OBSERVACION =
(SELECT LISTAGG(T2.REF_OBSERVACION, chr(10)) WITHIN GROUP (ORDER BY T2.REF_OBSERVACION) "REF_OBSERVACION"
FROM DIT_BITACORA_PROC_MOV05_CDA T2
WHERE T2.CVE_ID_RESULTADO not in('000', '999')
AND  T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND TRUNC(T2.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE)
GROUP BY T2.CVE_ID_TRAMITE
)
WHERE EXISTS(
SELECT 1 
FROM DIT_BITACORA_PROC_MOV05_CDA T2
WHERE T2.CVE_ID_TRAMITE=T1.CVE_ID_TRAMITE
AND T2.CVE_ID_RESULTADO not in ('000' , '999')
AND TRUNC(T2.FEC_REGISTRO_ALTA)=TRUNC(SYSDATE))

--- COMANDO: UPDATE_VALIDA_ESTADO_MOV05

UPDATE DIT_BIT_FLUJO_ARCH_MOV05CDA T1
SET (T1.IND_VALIDA,T1.REF_ESTADO_SOLICITUD,T1.REF_ESTADO_TRAMITE) =
(
SELECT 
CASE WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_CA) = 4 THEN 1
     WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3) in (0,1,2) THEN 1
ELSE 0
END IND_VALIDA,
CASE WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_CA) = 4 THEN 5
ELSE 5
END REF_ESTADO_SOLICITUD,
CASE WHEN SUM(IND_CIZ1+IND_CIZ2+IND_CIZ3+IND_CA) = 4 THEN 88
ELSE 85
END REF_ESTADO_TRAMITE
FROM DIT_BIT_FLUJO_ARCH_MOV05CDA T2
WHERE T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
GROUP BY T2.CVE_ID_TRAMITE)
WHERE EXISTS(
SELECT 1 
FROM DIT_BIT_FLUJO_ARCH_MOV05CDA T2
WHERE T1.CVE_ID_TRAMITE=T2.CVE_ID_TRAMITE
AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
GROUP BY T2.CVE_ID_TRAMITE)

--- COMANDO: UPDATE DIT_MOV_ACLARACION_NSS_CDA

UPDATE DIT_MOV_ACLARACION_NSS_CDA T1 SET (T1.CVE_ID_ESTADO_MOV_ENV_SINDO,T1.FEC_REGISTRO_ACTUALIZADO,T1.IND_ENV_SINDO)=
(SELECT
    CASE WHEN T2.REF_ESTADO_TRAMITE = '88' THEN 3  ELSE 2  END ,  SYSDATE , '0' 
    FROM DIT_BIT_FLUJO_ARCH_MOV05CDA T2
    WHERE 1=1
      AND T1.CVE_ID_MOV_ACLARACION_NSS=T2.CVE_ID_TRAMITE
      AND T2.IND_VALIDA=1
      AND T1.CVE_ID_ESTADO_MOV_ENV_SINDO = 1
      AND TRUNC(T2.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE)
  )
WHERE EXISTS(SELECT 1 FROM DIT_BIT_FLUJO_ARCH_MOV05CDA T3
              WHERE 1=1
              AND T1.CVE_ID_MOV_ACLARACION_NSS=T3.CVE_ID_TRAMITE
              AND T3.IND_VALIDA=1
              AND T1.CVE_ID_ESTADO_MOV_ENV_SINDO = 1
            AND TRUNC(T3.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE))

--- COMANDO: DIT_MOV_ACLARACION_NSS_CDA

UPDATE DIT_MOV_ACLARACION_NSS_CDA T1 SET T1.IND_ENV_SINDO = 1, T1.FEC_REGISTRO_ACTUALIZADO = SYSDATE
                WHERE T1.CVE_ID_TIPO_NSS_ACLARACION = 3 
                                 AND T1.CVE_ID_TIPO_TRAM_CORREC_NSS = 4 
                                 AND T1.IND_ENV_SINDO is NULL
                                 AND T1.CVE_ID_DETALLE_NSS_CDA IN(select min(NSS.CVE_ID_DETALLE_NSS_CDA)
                                 from DIT_DETALLE_NSS_CDA NSS WHERE EXISTS(SELECT 1 FROM
                                 DIT_MOV_ACLARACION_NSS_CDA MOVA WHERE
      MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
      AND MOVA.CVE_ID_TIPO_NSS_ACLARACION = 3 
                                               AND MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS = 4 
                                               AND MOVA.IND_ENV_SINDO is NULL)
                                               AND NSS.CVE_ID_CORRECCION_DATOS_ASEG IN(select NSS2.CVE_ID_CORRECCION_DATOS_ASEG
                                               from DIT_DETALLE_NSS_CDA NSS2 WHERE NSS2.CVE_ID_DETALLE_NSS_CDA IN(select MOVA2.CVE_ID_DETALLE_NSS_CDA FROM DIT_MOV_ACLARACION_NSS_CDA MOVA2 
                                               WHERE MOVA2.CVE_ID_MOV_ACLARACION_NSS IN(SELECT FLU.CVE_ID_TRAMITE from DIT_BIT_FLUJO_ARCH_MOV05CDA FLU where
            FLU.IND_VALIDA=1                           
            AND FLU.REF_ESTADO_TRAMITE = '88'
            AND TRUNC(FLU.FEC_REGISTRO_ACTUALIZADO)=TRUNC(SYSDATE))))
      group by NSS.CVE_ID_CORRECCION_DATOS_ASEG)

















