--============================================================================================================
--Script del flujo "MAIN RETORNO CARGA CDA" paquete: MAIN_LOAD_CDA_OSD
-- Ambiente:                 Prod
-- Autores                   Omar Pérez Chavira 
-- Fecha                     01/Dic/2020
--============================================================================================================


--======================================================
--- PASO: actualiza Tramite
--======================================================
--- COMANDO: Comando 0

--UPDATE DE TRAMITE AL FINALIZAR EL PROCESO  PARA DEJAR COMO OPERADO SINDO
UPDATE DIT_TRAMITE T SET T.CVE_ID_ESTADO_TRAMITE = 88,  T.FEC_REGISTRO_ACTUALIZADO = SYSDATE 
--select t.* from dit_tramite t
WHERE T.CVE_ID_ESTADO_TRAMITE = 37
    AND T.CVE_ID_TIPO_TRAMITE =139
    and NOT EXISTS( select * from (
        SELECT TRAM.CVE_ID_TRAMITE
        FROM DIT_TRAMITE TRAM
            INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
            INNER JOIN DIT_CORRECCION_CTA_IND_CDA CTA ON CTA.CVE_ID_MOV_ACLARACION_NSS = MOVA.CVE_ID_MOV_ACLARACION_NSS
        WHERE TRAM.CVE_ID_ESTADO_TRAMITE = 37
            AND TRAM.CVE_ID_TIPO_TRAMITE =139
            AND (CTA.CVE_ID_ESTADO_MOV_ENV_SINDO != 3 or CTA.CVE_ID_ESTADO_MOV_ENV_SINDO is null)
            AND MOVA.fec_registro_baja is null
            AND CTA.fec_registro_baja is null
           -- AND TRUNC(CTA.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
        union
        SELECT TRAM.CVE_ID_TRAMITE
        FROM DIT_TRAMITE TRAM
            INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
        WHERE TRAM.CVE_ID_ESTADO_TRAMITE = 37
            AND TRAM.CVE_ID_TIPO_TRAMITE =139
            AND (MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO != 3 or MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO is null)
            AND MOVA.fec_registro_baja is null
            AND ((MOVA.CVE_ID_TIPO_NSS_ACLARACION IN (1,2) OR MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS IN(1,2,4))
                 or (MOVA.CVE_ID_TIPO_NSS_ACLARACION =5 and MOVA.CVE_ID_TIPO_TRAM_CORREC_NSS =8))
            
           -- AND TRUNC(MOVA.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
    ) TR
    where tr.CVE_ID_TRAMITE = t.CVE_ID_TRAMITE
  )

--- COMANDO: Comando 10

--UPDATE DE TRAMITE AL FINALIZAR EL PROCESO  PARA DEJAR COMO ERROR SINDO
UPDATE DIT_TRAMITE T SET T.CVE_ID_ESTADO_TRAMITE = 85,  T.FEC_REGISTRO_ACTUALIZADO = SYSDATE   
--select t.* from MGPBDTU9X.dit_tramite t
WHERE T.CVE_ID_ESTADO_TRAMITE = 37
    AND T.CVE_ID_TIPO_TRAMITE =139
    and EXISTS( select * from (
        SELECT TRAM.CVE_ID_TRAMITE
        FROM MGPBDTU9X.DIT_TRAMITE TRAM
            INNER JOIN MGPBDTU9X.DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN MGPBDTU9X.DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN MGPBDTU9X.DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
            INNER JOIN MGPBDTU9X.DIT_CORRECCION_CTA_IND_CDA CTA ON CTA.CVE_ID_MOV_ACLARACION_NSS = MOVA.CVE_ID_MOV_ACLARACION_NSS
        WHERE TRAM.CVE_ID_ESTADO_TRAMITE = 37
            AND TRAM.CVE_ID_TIPO_TRAMITE =139
            AND CTA.CVE_ID_ESTADO_MOV_ENV_SINDO =2
            AND MOVA.fec_registro_baja is null
            AND CTA.fec_registro_baja is null
           -- AND TRUNC(CTA.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
        union
        SELECT TRAM.CVE_ID_TRAMITE
        FROM MGPBDTU9X.DIT_TRAMITE TRAM
            INNER JOIN MGPBDTU9X.DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN MGPBDTU9X.DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN MGPBDTU9X.DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
        WHERE TRAM.CVE_ID_ESTADO_TRAMITE = 37
            AND TRAM.CVE_ID_TIPO_TRAMITE =139
            AND MOVA.CVE_ID_ESTADO_MOV_ENV_SINDO = 2 
            AND MOVA.fec_registro_baja is null
         --   AND TRUNC(MOVA.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
        
    ) TR
    where tr.CVE_ID_TRAMITE = t.CVE_ID_TRAMITE
  ) 

--- COMANDO: Comando 20

UPDATE DIT_TRAMITE T SET (FEC_REGISTRO_ACTUALIZADO, T.REF_OBSERVACION) =
    (
     SELECT  SYSDATE, substr(T.REF_OBSERVACION || ' ERROR SINDO ' || LISTAGG(REF_OBSERVACION , ' , ')  WITHIN GROUP(ORDER BY REF_OBSERVACION),1,2056) "REF_OBSERVACION" 
     FROM (
          select m6.REF_OBSERVACION, TRAM.CVE_ID_TRAMITE
           from  DIT_TRAMITE TRAM
           INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
           INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
           INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
           inner JOIN DIT_BIT_FLUJO_ARCH_MOV06CDA M6 ON MOVA.CVE_ID_MOV_ACLARACION_NSS = M6.CVE_ID_TRAMITE
           where m6.IND_VALIDA = 1
           AND M6.REF_ESTADO_TRAMITE =85
           and trunc(m6.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate)
          UNION
          select M5.REF_OBSERVACION, TRAM.CVE_ID_TRAMITE
           from  DIT_TRAMITE TRAM
           INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
           INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
           INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
           inner JOIN DIT_BIT_FLUJO_ARCH_MOV05CDA M5 ON MOVA.CVE_ID_MOV_ACLARACION_NSS = M5.CVE_ID_TRAMITE
           where m5.IND_VALIDA = 1
           AND M5.REF_ESTADO_TRAMITE =85
           and trunc(M5.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate)
           union
           select ci.REF_OBSERVACION, TRAM.CVE_ID_TRAMITE
             FROM DIT_TRAMITE TRAM
                    INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
                    INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
                    INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
                    INNER JOIN DIT_CORRECCION_CTA_IND_CDA CTA ON CTA.CVE_ID_MOV_ACLARACION_NSS = MOVA.CVE_ID_MOV_ACLARACION_NSS
                    INNER JOIN DIT_BIT_FLUJO_ARCH_MOVCICDA CI ON CTA.CVE_ID_CORRECCION_CTA_IND_CDA = CI.CVE_ID_TRAMITE
           where CI.IND_VALIDA = 1
           AND CI.REF_ESTADO_TRAMITE =85
           and trunc(CI.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate) 
        ) err
        WHERE ERR.cve_id_tramite = T.CVE_ID_TRAMITE
        AND T.CVE_ID_TIPO_TRAMITE = 139
        AND T.CVE_ID_ESTADO_TRAMITE = 85
        AND TRUNC(T.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
        group by err.CVE_ID_TRAMITE
    )
  --SELECT *  FROM DIT_TRAMITE T
  WHERE EXISTS (
  SELECT  REF_OBSERVACION FROM (
  select m6.REF_OBSERVACION, TRAM.CVE_ID_TRAMITE
  from  DIT_TRAMITE TRAM
   INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
   INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
   INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
   inner JOIN DIT_BIT_FLUJO_ARCH_MOV06CDA M6 ON MOVA.CVE_ID_MOV_ACLARACION_NSS = M6.CVE_ID_TRAMITE
   where m6.IND_VALIDA = 1
   AND M6.REF_ESTADO_TRAMITE =85
   and trunc(m6.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate)
  UNION
  select M5.REF_OBSERVACION, TRAM.CVE_ID_TRAMITE
   from  DIT_TRAMITE TRAM
   INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
   INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
   INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
   inner JOIN DIT_BIT_FLUJO_ARCH_MOV05CDA M5 ON MOVA.CVE_ID_MOV_ACLARACION_NSS = M5.CVE_ID_TRAMITE
   where m5.IND_VALIDA = 1
   AND M5.REF_ESTADO_TRAMITE =85
   and trunc(M5.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate)
   union
   select ci.REF_OBSERVACION, TRAM.CVE_ID_TRAMITE
     FROM DIT_TRAMITE TRAM
            INNER JOIN DIT_CORRECCION_DATOS_ASEG DA ON DA.CVE_ID_TRAMITE = TRAM.CVE_ID_TRAMITE
            INNER JOIN DIT_DETALLE_NSS_CDA NSS ON DA.CVE_ID_CORRECCION_DATOS_ASEG = NSS.CVE_ID_CORRECCION_DATOS_ASEG
            INNER JOIN DIT_MOV_ACLARACION_NSS_CDA MOVA ON  MOVA.CVE_ID_DETALLE_NSS_CDA =  NSS.CVE_ID_DETALLE_NSS_CDA
            INNER JOIN DIT_CORRECCION_CTA_IND_CDA CTA ON CTA.CVE_ID_MOV_ACLARACION_NSS = MOVA.CVE_ID_MOV_ACLARACION_NSS
            INNER JOIN DIT_BIT_FLUJO_ARCH_MOVCICDA CI ON CTA.CVE_ID_CORRECCION_CTA_IND_CDA = CI.CVE_ID_TRAMITE
   where CI.IND_VALIDA = 1
   AND CI.REF_ESTADO_TRAMITE =85
   and trunc(CI.FEC_REGISTRO_ACTUALIZADO) = trunc(sysdate)
   ) err
   WHERE ERR.cve_id_tramite = T.CVE_ID_TRAMITE
   )
   AND T.CVE_ID_TIPO_TRAMITE = 139
   AND T.CVE_ID_ESTADO_TRAMITE = 85
   AND TRUNC(T.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)

--- COMANDO: update bitacora XML

update DIT_DETALLE_TRAMITE dt set (dt.fec_registro_actualizado,  dt.REF_DATOS_TRAMITE_XML) =
      (select SYSDATE, 
      INSERTCHILDXML(XMLType(REPLACE(DT.REF_DATOS_TRAMITE_XML,CHR(0),'')), '/tramiteCorreccionCurp',
      'observacionesSubdelegacion', XMLType('<observacionesSubdelegacion><cveEstado>'||t.CVE_ID_ESTADO_TRAMITE ||'</cveEstado>
                                              <asignado>'||s.CVE_ID_USUARIO ||'</asignado>
                                              <fechaActualizacion>'||to_char(current_timestamp, 'YYYY-MM-DD"T"HH24:MI:SSX"00-06:00"')||'</fechaActualizacion>
                                              <usuario>SINDO</usuario>
                                              <detalle>'||t.REF_OBSERVACION ||'</detalle>
                                              </observacionesSubdelegacion>')
      ).getclobval()
        from dit_solicitud s, DIT_TRAMITE t
        where s.CVE_ID_SOLICITUD = t.CVE_ID_SOLICITUD
        and t.CVE_ID_TRAMITE = dt.CVE_ID_TRAMITE
        AND T.CVE_ID_TIPO_TRAMITE =139
        AND T.CVE_ID_ESTADO_TRAMITE in (85,88)
        AND TRUNC(T.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
        --and dt.REF_DATOS_TRAMITE_XML is not null 
      )
where exists(
      select t.rowid
      from dit_solicitud s, DIT_TRAMITE t
        where s.CVE_ID_SOLICITUD = t.CVE_ID_SOLICITUD
        and t.CVE_ID_TRAMITE = dt.CVE_ID_TRAMITE
        AND T.CVE_ID_TIPO_TRAMITE =139
        AND T.CVE_ID_ESTADO_TRAMITE in (85,88)
        AND TRUNC(T.FEC_REGISTRO_ACTUALIZADO) = TRUNC(SYSDATE)
        --and dt.REF_DATOS_TRAMITE_XML is not null
)
