package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * DgCatVialidad generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatVialidad extends AbstractModel {

	private BigDecimal cveTipoVial;
	private String descripcion;
	

	public AbstractDgCatVialidad() {
	}

	public AbstractDgCatVialidad(BigDecimal cveTipoVial, String descripcion) {
	/*	this.cveTipoVial = cveTipoVial;
		this.descripcion = descripcion;
		*/
	}


//	@Id
//	@Column(name = "CVE_TIPO_VIAL", unique = true, nullable = true, precision = 22, scale = 0)
	public BigDecimal getCveTipoVial() {
		
		if(cveTipoVial!=null && cveTipoVial.intValue()<=0) return null;
		
		return this.cveTipoVial;
	}

	public void setCveTipoVial(BigDecimal cveTipoVial) {
		this.cveTipoVial = cveTipoVial;
	}

//	@Column(name = "DESCRIPCION", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


}
