welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

############# WIZARDS #################
tramiteDummyInicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramiteDummyInicio.url=tramiteDummyInicio
tramiteDummyContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
tramiteDummyContenido.url = tramiteDummyContenido

############# PORTLETS #################
portletDummyInicial.(class)=org.springframework.web.servlet.view.JstlView
portletDummyInicial.url=/WEB-INF/views/portlet/dummy/inicial.jsp
portletDummyContenido.(class)=org.springframework.web.servlet.view.JstlView
portletDummyContenido.url=/WEB-INF/views/portlet/dummy/contenido.jsp

############# WIDGETS #################
widgetDummyInicio.(class)=org.springframework.web.servlet.view.JstlView
widgetDummyInicio.url=/WEB-INF/views/widget/dummy/inicial.jsp
widgetDummyContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDummyContenido.url=/WEB-INF/views/widget/dummy/contenido.jsp

############# GENERACION CUESTIONARIOS #################
crearCuestionario.(class)=org.springframework.web.servlet.view.JstlView
crearCuestionario.url=/WEB-INF/views/cuestionario/armarCuestionario.jsp
test.(class)=org.springframework.web.servlet.view.tiles2.TilesView
test.url=test