
package gob.imss.webservice.imss.riss.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidacionRissService", targetNamespace = "http://mx.gob.imss.delta.global.service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidacionRissService {


    /**
     * 
     * @param validacionRissRequest
     * @return
     *     returns gob.imss.webservice.imss.riss.ValidacionRissResponse
     */
    @WebMethod
    @WebResult(name = "validacionRissResponse", targetNamespace = "http://mx.gob.imss.delta.global.service/", partName = "validacionRissResponse")
    ValidacionRissResponse validar(
        @WebParam(name = "validacionRissRequest", targetNamespace = "http://mx.gob.imss.delta.global.service/", partName = "validacionRissRequest")
        ValidacionRissRequest validacionRissRequest);

}
