############ PRODUCCION ############

#RUTA CERTIFICADO DIGITAL
#ruta.certificado.digital=timbradoCFDI/certificados/certificadoCSD.cer

#RUTA LLAVE DIGITAL
#ruta.llave.digital=timbradoCFDI/certificados/privateCSD.key

#PASSWORD DE LLAVE DIGITAL
#password.llave.digital=CC.COP.2014

#RUTA ARCHIVO XML GENERADO
#ruta.archivo.xml.generado=/Users/noimporta/

############ STAGE ############

#RUTA CERTIFICADO DIGITAL
ruta.certificado.digital=timbradoCFDI/certificados/CSD_CFDI_Pruebas_WAL99092955A.cer

#RUTA LLAVE DIGITAL
ruta.llave.digital=timbradoCFDI/certificados/CSD_CFDI_Pruebas_WAL99092955A.key

#PASSWORD DE LLAVE DIGITAL
password.llave.digital=12345678a

#RUTA ARCHIVO XML GENERADO
ruta.archivo.xml.generado=/Users/noimporta/

############ DESARROLLO ############

#RUTA CERTIFICADO DIGITAL
#ruta.certificado.digital=C:\\tmp\\CFDI\\cert\\CSD_CFDI_Pruebas_WAL99092955A.cer

#RUTA LLAVE DIGITAL
#ruta.llave.digital=C:\\tmp\\CFDI\\cert\\CSD_CFDI_Pruebas_WAL99092955A.key

#PASSWORD DE LLAVE DIGITAL
#password.llave.digital=12345678a

#RUTA ARCHIVO XML GENERADO
#ruta.archivo.xml.generado=/Users/noimporta/