
package mx.gob.imss.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServVigGpoFamEstService", targetNamespace = "http://services.imss.gob.mx/", wsdlLocation = "file:/share/oracle/servapdir01_domain/servapdir_cluster1/wsdl/ServVigGpoFamEstService.wsdl")
public class ServVigGpoFamEstService
    extends Service
{

    private final static URL SERVVIGGPOFAMESTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.services.ServVigGpoFamEstService.class.getName());
    private final static int serviceTimeOut = 10000;
    private final static int connectTimeOut = 5000;
    static {
        URL url = null;
        try {
        	url = Thread.currentThread().getContextClassLoader().getResource("file:/share/oracle/servapdir01_domain/servapdir_cluster1/wsdl/ServVigGpoFamEstService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/IMSSWorkspace/GestionClientesWS/04IMP-nuevo/ClientesWebservices-derechohabientes/src/main/resources/ServVigGpoFamEstService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVVIGGPOFAMESTSERVICE_WSDL_LOCATION = url;
    }

    public ServVigGpoFamEstService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServVigGpoFamEstService() {
        super(SERVVIGGPOFAMESTSERVICE_WSDL_LOCATION, new QName("http://services.imss.gob.mx/", "ServVigGpoFamEstService"));
    }

    /**
     * 
     * @return
     *     returns ServVigGpoFamEst
     */
    @WebEndpoint(name = "ServVigGpoFamEstPort")
    public ServVigGpoFamEst getServVigGpoFamEstPort() {
    	ServVigGpoFamEst ws = super.getPort(new QName("http://services.imss.gob.mx/", "ServVigGpoFamEstPort"), ServVigGpoFamEst.class);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
      	return ws;
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServVigGpoFamEst
     */
    @WebEndpoint(name = "ServVigGpoFamEstPort")
    public ServVigGpoFamEst getServVigGpoFamEstPort(WebServiceFeature... features) {
    	ServVigGpoFamEst ws = super.getPort(new QName("http://services.imss.gob.mx/", "ServVigGpoFamEstPort"), ServVigGpoFamEst.class, features);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
      	return ws;
    }

}
