
package mx.com.metatrust.doctrust.wsfirmaelectronicaseg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FirmaElectronicaSegPortType", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirmaElectronicaSegPortType {


    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.RegistroSeguimientoResponseType
     */
    @WebMethod(operationName = "RegistroSeguimiento", action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/RegistroSeguimiento")
    @WebResult(name = "RegistroSeguimientoResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    RegistroSeguimientoResponseType registroSeguimiento(
        @WebParam(name = "RegistroSeguimientoRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        RegistroSeguimientoRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.FirmaSimpleResponseType
     */
    @WebMethod(operationName = "FirmaSimple", action = "http://idtrust.metatrust.com.mx/WsFirmaElectronicaSeg/FirmaSimple")
    @WebResult(name = "FirmaSimpleResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    FirmaSimpleResponseType firmaSimple(
        @WebParam(name = "FirmaSimpleRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaSimpleRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.FirmaXMLSegResponseType
     */
    @WebMethod(operationName = "FirmaXML", action = "http://idtrust.metatrust.com.mx/WsFirmaElectronicaSeg/FirmaXML")
    @WebResult(name = "FirmaXMLSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    FirmaXMLSegResponseType firmaXML(
        @WebParam(name = "FirmaXMLSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaXMLSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.ConfirmaCveSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/confirmaClaves")
    @WebResult(name = "ConfirmaCveSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    ConfirmaCveSegResponseType confirmaClaves(
        @WebParam(name = "ConfirmaCveSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ConfirmaCveSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.ConsultaCertSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/consultaCertificado")
    @WebResult(name = "ConsultaCertSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    ConsultaCertSegResponseType consultaCertificado(
        @WebParam(name = "ConsultaCertSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ConsultaCertSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.EliminaCvesSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/eliminaClaves")
    @WebResult(name = "EliminaCvesSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    EliminaCvesSegResponseType eliminaClaves(
        @WebParam(name = "EliminaCvesSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        EliminaCvesSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.FirmaSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/firma")
    @WebResult(name = "FirmaSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    FirmaSegResponseType firma(
        @WebParam(name = "FirmaSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.GeneraCvesSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/generaClaves")
    @WebResult(name = "GeneraCvesSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    GeneraCvesSegResponseType generaClaves(
        @WebParam(name = "GeneraCvesSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        GeneraCvesSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.RegistraCvesSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/registraClaves")
    @WebResult(name = "RegistraCvesSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    RegistraCvesSegResponseType registraClaves(
        @WebParam(name = "RegistraCvesSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        RegistraCvesSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.ValidaFirmaSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/validaFirma")
    @WebResult(name = "ValidaFirmaSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    ValidaFirmaSegResponseType validaFirma(
        @WebParam(name = "ValidaFirmaSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ValidaFirmaSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.RecuperaArchivoResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/recuperaArchivo")
    @WebResult(name = "RecuperaArchivoResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    RecuperaArchivoResponseType recuperaArchivo(
        @WebParam(name = "RecuperaArchivoRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        RecuperaArchivoRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.ValidaCertificadoSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/validaCertificado")
    @WebResult(name = "ValidaCertificadoSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    ValidaCertificadoSegResponseType validaCertificado(
        @WebParam(name = "ValidaCertificadoSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ValidaCertificadoSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.ValidaCMSV2ResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/validaCMSV2")
    @WebResult(name = "ValidaCMSV2Response", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    ValidaCMSV2ResponseType validaCMSV2(
        @WebParam(name = "ValidaCMSV2Request", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ValidaCMSV2RequestType body);

}
