<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>mx.imss.ctirss</groupId>
		<artifactId>denuncia</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<groupId>mx.imss.ctirss.ejb</groupId>
	<artifactId>denuncia-service-business-ejb</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>ejb</packaging>

	<name>arquetipo-service-business-ejb</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>8859_1</project.build.sourceEncoding>
		<org.springframework.version>3.0.5.RELEASE</org.springframework.version>
		<org.hibernate.version>3.5.5-Final</org.hibernate.version>
		<org.slf4j.version>1.6.1</org.slf4j.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>mx.imss.ctirss.framework</groupId>
			<artifactId>denuncia-framework-base</artifactId>
			<version>1.0-SNAPSHOT</version>
			<type>jar</type>
		</dependency>


		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.10</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>mx.imss.ctirss.interface</groupId>
			<artifactId>denuncia-service-business-interface</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>mx.imss.ctirss.pojo</groupId>
			<artifactId>denuncia-model-business-pojo</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
			
<!-- EJB -->
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb-api</artifactId>
			<version>3.0</version>
		</dependency>

		<!-- Spring -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${org.springframework.version}</version>
			<exclusions>
				<!-- Exclude Commons Logging in favor of SLF4j -->
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- jpa2 -->
		<!--dependency> <groupId>javax</groupId> <artifactId>persistence-api</artifactId> 
			<version>2</version> <type>jar</type> </dependency -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aspects</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
			<version>1.6.4</version>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
			<version>1.6.4</version>
		</dependency>

		<!-- Hibernate -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-annotations</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>4.2.0.Final</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-search</artifactId>
			<version>3.4.1.Final</version>
		</dependency>

		<!-- Logging -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>

		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.15</version>
			<!--scope>runtime</scope -->
			<exclusions>
				<exclusion>
					<groupId>javax.jms</groupId>
					<artifactId>jms</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.jdmk</groupId>
					<artifactId>jmxtools</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.jmx</groupId>
					<artifactId>jmxri</artifactId>
				</exclusion>

				<exclusion>
					<groupId>org.apache.lucene</groupId>
					<artifactId>lucene-memory</artifactId>
				</exclusion>

			</exclusions>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>commons</artifactId>
			<version>1.4.0</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>infraestructura-integracion</artifactId>
			<version>1.2.5</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>invocaServicio</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>ServiciosIntegracion</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>commons-digester</artifactId>
			<version>1.6</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>xmlparserv2</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.fiscalizacion.dictamen</groupId>
			<artifactId>xml</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.idse</groupId>
			<artifactId>WSFirmaDigitalClient</artifactId>
			<version>2.0.0p</version>
		</dependency>
		<dependency>
			<groupId>axis</groupId>
			<artifactId>axis</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>commons-discovery</groupId>
			<artifactId>commons-discovery</artifactId>
			<version>0.4</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.1</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<outputDirectory>${endorsed.dir}</outputDirectory>
							<silent>true</silent>
							<artifactItems>
								<artifactItem>
									<groupId>javax</groupId>
									<artifactId>javaee-endorsed-api</artifactId>
									<version>6.0</version>
									<type>jar</type>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
