package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgAsentamiento;

/**
 * DgCodigosPostales generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCodigosPostales extends AbstractModel {

	private AbstractDgCodigosPostalesId id;
	private DgAsentamiento dgAsentamiento;
	private String agregado;
	

	public AbstractDgCodigosPostales() {
		this.id = new AbstractDgCodigosPostalesId();
	
	}

	public AbstractDgCodigosPostales(AbstractDgCodigosPostalesId id,
			DgAsentamiento dgAsentamiento) {
		this.id = id;
		this.dgAsentamiento = dgAsentamiento;
	}

	public AbstractDgCodigosPostales(AbstractDgCodigosPostalesId id,
			DgAsentamiento dgAsentamiento, String agregado) {
		this.id = id;
		this.dgAsentamiento = dgAsentamiento;
		this.agregado = agregado;
	
	}

//	@EmbeddedId
//	@AttributeOverrides({
//			@AttributeOverride(name = "codigo", column = @Column(name = "CODIGO", nullable = false, length = 5)),
//			@AttributeOverride(name = "cveAsen", column = @Column(name = "CVE_ASEN", nullable = false, length = 13)),
//			@AttributeOverride(name = "cveEnt", column = @Column(name = "CVE_ENT", nullable = false, length = 2)),
//			@AttributeOverride(name = "cveMun", column = @Column(name = "CVE_MUN", nullable = false, length = 3)),
//			@AttributeOverride(name = "cveLoc", column = @Column(name = "CVE_LOC", nullable = false, length = 4)),
//			@AttributeOverride(name = "cvePeriodo", column = @Column(name = "CVE_PERIODO", nullable = false, precision = 2, scale = 0)) })
	public AbstractDgCodigosPostalesId getId() {
		return this.id;
	}

	public void setId(AbstractDgCodigosPostalesId id) {
		this.id = id;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumns({
//			@JoinColumn(name = "CVE_ASEN", referencedColumnName = "CVE_ASEN", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", nullable = false, insertable = false, updatable = false) })
	public DgAsentamiento getDgAsentamiento() {
		return this.dgAsentamiento;
	}

	public void setDgAsentamiento(DgAsentamiento dgAsentamiento) {
		this.dgAsentamiento = dgAsentamiento;
	}

//	@Column(name = "AGREGADO", length = 1)
	public String getAgregado() {
		return this.agregado;
	}

	public void setAgregado(String agregado) {
		this.agregado = agregado;
	}


}
