package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * DgCatAdministracion generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatAdministracion extends AbstractModel {

	private Integer cveCac;
	private String nombre;

	public AbstractDgCatAdministracion() {
	}

	public AbstractDgCatAdministracion(Integer cveCac, String nombre) {
		this.cveCac = cveCac;
		this.nombre = nombre;
	}

	
//	@Id
//	@Column(name = "CVE_CAC", unique = true, nullable = false, precision = 1, scale = 0)
	public Integer isCveCac() {
		return this.cveCac;
	}

	public void setCveCac(Integer cveCac) {
		this.cveCac = cveCac;
	}

//	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	

}
