<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>mx.gob.imss.ctirss.delta.derechohabientes.ws</groupId>
	<artifactId>gestionDerechohabientes-ws-servicios-negocio-ejb</artifactId>
	<version>2.2</version>
	
	<name>Modulo de Web services de derechohabientes  (ws)</name>
	<url>http://maven.apache.org</url>
	<packaging>ejb</packaging>

	<parent>
		<artifactId>gestionDerechohabientes</artifactId>
		<groupId>mx.gob.imss.ctirss.delta.derechohabientes</groupId>
		<version>2.2</version>
	</parent>



	<properties>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<org.springframework.version>3.0.5.RELEASE</org.springframework.version>
		<org.slf4j.version>1.6.1</org.slf4j.version>
		<org.hibernate.version>3.6.9.Final</org.hibernate.version>
	</properties>



	<dependencies>
	
		<!-- INICIO DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->

		

		<!-- Dependencia del Proyecto de Objetos de modelo DELTA IMSS -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
		</dependency>
		
		
	
<!-- Dependencia a las interfaces de negocio de derechohabientes -->
		<dependency>
		<groupId>mx.gob.imss.ctirss.delta.derechohabientes</groupId>
	<artifactId>gestionDerechohabientes-interfaces-negocio</artifactId>
	<version>${delta.derechohabientes.version}</version>
		</dependency>
		




		<!-- FIN DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->
		<!-- HIBERNATE CORE --> 
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>	
			<version>${org.hibernate.version}</version>	
		</dependency>
		<dependency>
			<groupId>org.hibernate.javax.persistence</groupId>
			<artifactId>hibernate-jpa-2.0-api</artifactId>
			<version>1.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-commons-annotations</artifactId>
			<version>3.2.0.Final</version>
		</dependency>            		




		<!-- HIBERNATE DEPENDECIES-->
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.16</version>
		</dependency>
		
			<!-- EJB -->
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb-api</artifactId>
			<version>3.0</version>
			<scope>provided</scope>
		</dependency>

				
		<!-- WEBLOGIC -->
		<dependency>
			<groupId>weblogic</groupId>
			<artifactId>wlfullclient</artifactId>
			<version>10.3.4</version>
			<scope>test</scope>			
		</dependency>
		
	
		</dependencies>

	




	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
				</configuration>
			</plugin>
		</plugins>
	</build></project>
