<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>mx.gob.imss.ctirss.delta</groupId>
	<artifactId>delta</artifactId>
	<packaging>pom</packaging>
	<version>2.6</version>
	
	<name>Modulo  Delta  IMSS</name>
	<url>http://www.imss.gob.mx/instituto/Directorio/ctirss.htm</url>

	<properties>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<delta.framework.version>2.6</delta.framework.version>
	</properties>

	<build>
		<!-- To define the plugin version in your parent POM -->
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-site-plugin</artifactId>
					<version>3.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<configuration>
						<skipTests>true</skipTests>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>

			<!-- for use JVM 1.6 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
			<!-- Relase Plugin-->
			 <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <tagBase>http://11.254.16.21/svn/base_arquitectura_delta/codigo/tags/</tagBase>

          	   
        </configuration>
      </plugin>
			
		</plugins>

		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>			
				<artifactId>wagon-ftp</artifactId>
			</extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>			
				<artifactId>wagon-webdav</artifactId>
			</extension>
		</extensions>

	</build>

	<repositories>
		<repository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<layout>default</layout>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<layout>default</layout>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<updatePolicy>never</updatePolicy>
			</releases>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<!-- use the following if you're not using a snapshot version. -->
		<repository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://172.16.5.134:8080/repository/repo/</url>

		</repository>

		<snapshotRepository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://172.16.5.134:8080/repository/repo/</url>
		</snapshotRepository>
		
		
		

	</distributionManagement>
	<scm>
			  <connection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/delta_base</connection>
			  <developerConnection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/delta_base/</developerConnection>
			  <url>http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/delta_base/</url>
	</scm>

	<modules>
		<module>delta-framework-base</module>
		<module>delta-modelo-negocio</module>
		<module>delta-modelo-xmlsolicitud</module>
        <module>imssdigital-modelo</module>
		<module>delta-persistencia</module>
		<module>delta-interfaces-negocio</module>
		<module>delta-servicios-negocio-ejb</module>
		<!--<module>delta-packing</module>-->
		<module>delta_modelo-base</module>
		<module>delta-comboSelect</module>
    <module>jaxb-utils</module>
  </modules>
</project>
