
package mx.gob.imss.ws.pagos.ivro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSPAGOSIVRO", targetNamespace = "http://ivro.pagos.ws.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSPAGOSIVRO {


    /**
     * 
     * @param mensaje
     * @return
     *     returns mx.gob.imss.ws.pagos.ivro.RespWSPagosIvroSimple
     */
    @WebMethod
    @WebResult(name = "Respuesta", targetNamespace = "")
    @RequestWrapper(localName = "pagoPorFechas", targetNamespace = "http://ivro.pagos.ws.imss.gob.mx/", className = "mx.gob.imss.ws.pagos.ivro.PagoPorFechas")
    @ResponseWrapper(localName = "pagoPorFechasResponse", targetNamespace = "http://ivro.pagos.ws.imss.gob.mx/", className = "mx.gob.imss.ws.pagos.ivro.PagoPorFechasResponse")
    public RespWSPagosIvroSimple pagoPorFechas(
        @WebParam(name = "Mensaje", targetNamespace = "")
        MsgWSPagosIvroByFec mensaje);

    /**
     * 
     * @param mensaje
     * @return
     *     returns mx.gob.imss.ws.pagos.ivro.RespWSPagosIvroSimple
     */
    @WebMethod
    @WebResult(name = "Respuesta", targetNamespace = "")
    @RequestWrapper(localName = "pagoPorPeriodo", targetNamespace = "http://ivro.pagos.ws.imss.gob.mx/", className = "mx.gob.imss.ws.pagos.ivro.PagoPorPeriodo")
    @ResponseWrapper(localName = "pagoPorPeriodoResponse", targetNamespace = "http://ivro.pagos.ws.imss.gob.mx/", className = "mx.gob.imss.ws.pagos.ivro.PagoPorPeriodoResponse")
    public RespWSPagosIvroSimple pagoPorPeriodo(
        @WebParam(name = "Mensaje", targetNamespace = "")
        MsgWSPagosIvroByPeriodo mensaje);

}
