<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>mx.gob.imss.cit.dacvass.utils</groupId>
	<artifactId>captcha-utils</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>

	<name>Utileria para generar captchas</name>
	<url>http://maven.apache.org</url>

	<parent>
		<artifactId>delta</artifactId>
		<groupId>mx.gob.imss.ctirss.delta</groupId>
		<version>2.6-SNAPSHOT</version>
	</parent>

	<properties>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<org.hibernate.version>3.6.9.Final</org.hibernate.version>
	</properties>

	<dependencies>
		
	<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.16</version>
		</dependency>
		<!-- BeanUtils -->
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.8.3</version>
		</dependency>
		<!-- Servlet -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.5</version>
			<scope>provided</scope>
		</dependency>
		<!-- Dependencia para implementacion de jcaptcha -->
		<dependency>
			<groupId>com.octo.captcha</groupId>
			<artifactId>jcaptcha-all</artifactId>
			<version>1.0-RC6</version>
		</dependency>
			<!-- Commons -->
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.5</version>
		</dependency>
		
	</dependencies>


	<repositories>
		<repository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<layout>default</layout>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<snapshots>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<layout>default</layout>
			<snapshots>
			</snapshots>
			<releases>
				<updatePolicy>never</updatePolicy>
			</releases>
		</pluginRepository>
	</pluginRepositories>
</project>
