jndi.datasource=DSDelta

#reemplazar con los datos de su consola
#service.provider.url=t3://localhost:7001
#service.security.principal=weblogic
#service.security.credentials=weblogic9


service.provider.context=weblogic.jndi.WLInitialContextFactory

#Datos del ambiente de desarrollo QA para la llamda de domicilios
#service.provider.url=t3://172.24.116.37:15051,172.24.116.37:15052
#service.security.principal=admin_wlgeceqa
#service.security.credentials=wlgeceqa_admin

#Stage
service.provider.url=t3://vzapma07.imss.gob.mx:8001,vzapma07.imss.gob.mx:8003,vzapma12.imss.gob.mx:8001,vzapma12.imss.gob.mx:8003,vzapmb09.imss.gob.mx:8001,vzapmb09.imss.gob.mx:8003
service.security.principal=wloperator
service.security.credentials=53rv4p%wl%1p1r1t1r$.