jndi.datasource=DSDelta
service.provider.context=weblogic.jndi.WLInitialContextFactory

service.provider.url=${service.provider.url}
service.security.principal=${service.security.principal}
service.security.credentials=${service.security.credentials}