##################
# FTP FileConfig #
##################
filesystem.canase.tmp.output.url=ftp_test/canase/temp
filesystem.sindo.tmp.output.url=ftp_test/sindo/temp


################
# Servidor ftp #
################
ftp.server.url=11.254.13.4
ftp.server.user=pruebas
ftp.server.passwd=pruebas
ftp.server.port=21


######################
# Modo de aplicacion #
######################
application.mode=test


##################
# Ruta de origen #
##################
filesystem.global.tmp.log.url=/daemonTest/log
filesystem.global.tmp.log.dir.canase=canase_temp
filesystem.global.tmp.log.dir.sindo=sindo_temp


############################
# Ruta de FTP (Filesystem) #
############################
filesystem.ftp.base.output.url=/daemonTest/ftp/base


###########################
# Archivos CANASE y SINDO #
###########################

canase.file.asignacion=APMVIAJ.txt
sindo.file.ciztemp=AYPENT_TEMP.txt

###########################
# Archivos LOG Universal  #
###########################
global.log.file=DIAGNOSTICO_IMSS_LAYOUT.txt

##########################
# Archivos de validacion #
##########################

filesystem.delta.proceso.estatus=/daemonTest/bloq
