#Datos del ambiente de desarrollo QA
service.provider.url=t3://desarrollo.imss.gob.mx:7001
service.security.principal=weblogic
service.security.credentials=weblogic1

jdbc.url=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.8.136) (PORT=1630))(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.8.137) (PORT=1630))(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.8.138) (PORT=1630))(CONNECT_DATA=(SERVICE_NAME=serdg01)))  
