
package mx.com.metatrust.idtrust.wsidtrust;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IDTrustPortType", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDTrustPortType {


    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.FirmaResponseType
     */
    @WebMethod(operationName = "Firma", action = "http://idtrust.metatrust.com.mx/WsIDTrust/Firma")
    @WebResult(name = "FirmaResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public FirmaResponseType firma(
        @WebParam(name = "FirmaRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        FirmaRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.FirmaSimpleResponseType
     */
    @WebMethod(operationName = "FirmaSimple", action = "http://idtrust.metatrust.com.mx/WsIDTrust/FirmaSimple")
    @WebResult(name = "FirmaSimpleResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public FirmaSimpleResponseType firmaSimple(
        @WebParam(name = "FirmaSimpleRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        FirmaSimpleRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.CertificadoResponseType
     */
    @WebMethod(operationName = "Certificado", action = "http://idtrust.metatrust.com.mx/WsIDTrust/Certificado")
    @WebResult(name = "CertificadoResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public CertificadoResponseType certificado(
        @WebParam(name = "CertificadoRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        CertificadoRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.GeneraCvesResponseType
     */
    @WebMethod(operationName = "GeneraCves", action = "http://idtrust.metatrust.com.mx/WsIDTrust/GeneraCves")
    @WebResult(name = "GeneraCvesResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public GeneraCvesResponseType generaCves(
        @WebParam(name = "GeneraCvesRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        GeneraCvesRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ConfirmaCvesResponseType
     */
    @WebMethod(operationName = "ConfirmaCves", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ConfirmaCves")
    @WebResult(name = "ConfirmaCvesResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ConfirmaCvesResponseType confirmaCves(
        @WebParam(name = "ConfirmaCvesRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ConfirmaCvesRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.RegistraCvesResponseType
     */
    @WebMethod(operationName = "RegistraCves", action = "http://idtrust.metatrust.com.mx/WsIDTrust/RegistraCves")
    @WebResult(name = "RegistraCvesResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public RegistraCvesResponseType registraCves(
        @WebParam(name = "RegistraCvesRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        RegistraCvesRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.EliminaCvesResponseType
     */
    @WebMethod(operationName = "EliminaCves", action = "http://idtrust.metatrust.com.mx/WsIDTrust/EliminaCves")
    @WebResult(name = "EliminaCvesResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public EliminaCvesResponseType eliminaCves(
        @WebParam(name = "EliminaCvesRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        EliminaCvesRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ValidaFirmaResponseType
     */
    @WebMethod(operationName = "ValidaFirma", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ValidaFirma")
    @WebResult(name = "ValidaFirmaResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ValidaFirmaResponseType validaFirma(
        @WebParam(name = "ValidaFirmaRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ValidaFirmaRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ValidaFirmaResponseType
     */
    @WebMethod(operationName = "ValidaFirmaHash", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ValidaFirmaHash")
    @WebResult(name = "ValidaFirmaHashResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ValidaFirmaResponseType validaFirmaHash(
        @WebParam(name = "ValidaFirmaHashRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ValidaFirmaHashRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ValidaFirmaResponseType
     */
    @WebMethod(operationName = "ValidaFirmaRuta", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ValidaFirmaRuta")
    @WebResult(name = "ValidaFirmaRutaResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ValidaFirmaResponseType validaFirmaRuta(
        @WebParam(name = "ValidaFirmaRutaRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ValidaFirmaRutaRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ValidaFirmaResponseType
     */
    @WebMethod(operationName = "ValidaFirmaCMS", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ValidaFirmaCMS")
    @WebResult(name = "ValidaFirmaCMSResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ValidaFirmaResponseType validaFirmaCMS(
        @WebParam(name = "ValidaFirmaCMSRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ValidaFirmaCMSRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ValidaFirmaResponseType
     */
    @WebMethod(operationName = "ValidaFirmaCMSHash", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ValidaFirmaCMSHash")
    @WebResult(name = "ValidaFirmaCMSHashResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ValidaFirmaResponseType validaFirmaCMSHash(
        @WebParam(name = "ValidaFirmaCMSHashRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ValidaFirmaCMSHashRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.idtrust.wsidtrust.ValidaFirmaResponseType
     */
    @WebMethod(operationName = "ValidaFirmaCMSRuta", action = "http://idtrust.metatrust.com.mx/WsIDTrust/ValidaFirmaCMSRuta")
    @WebResult(name = "ValidaFirmaCMSRutaResponse", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
    public ValidaFirmaResponseType validaFirmaCMSRuta(
        @WebParam(name = "ValidaFirmaCMSRutaRequest", targetNamespace = "http://idtrust.metatrust.com.mx/WsIDTrust.xsd", partName = "body")
        ValidaFirmaCMSRutaRequestType body);

}
