package mx.gob.imss.csdiss.sdroc.dto;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CalendarioReporteDTO generated by hbm2java
 */
public class CalendarioReporteDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3711668517669025296L;
	
	private Long cveCalendarioRep;
	private Long cveBimCalendario;
	private Date fecIniPerDeclarado;
	private Date fecFinPerDeclarado;
	private Date fecIniPerPresentado;
	private Date fecFinPerPresentado;
//	private Set rotReporteBimestralObras = new HashSet(0);

	public CalendarioReporteDTO() {
	}

	public CalendarioReporteDTO(Long cveCalendarioRep) {
		this.cveCalendarioRep = cveCalendarioRep;
	}

	
	public CalendarioReporteDTO(Long cveCalendarioRep, Long cveBimCalendario, Date fecIniPerDeclarado,
			Date fecFinPerDeclarado, Date fecIniPerPresentado, Date fecFinPerPresentado) {
		this.cveCalendarioRep = cveCalendarioRep;
		this.cveBimCalendario = cveBimCalendario;
		this.fecIniPerDeclarado = fecIniPerDeclarado;
		this.fecFinPerDeclarado = fecFinPerDeclarado;
		this.fecIniPerPresentado = fecIniPerPresentado;
		this.fecFinPerPresentado = fecFinPerPresentado;

	}
	
	
	public Long getCveCalendarioRep() {
		return this.cveCalendarioRep;
	}

	public void setCveCalendarioRep(Long cveCalendarioRep) {
		this.cveCalendarioRep = cveCalendarioRep;
	}

	public Long getCveBimCalendario() {
		return this.cveBimCalendario;
	}

	public void setCveBimCalendario(Long cveBimCalendario) {
		this.cveBimCalendario = cveBimCalendario;
	}

	public Date getFecIniPerDeclarado() {
		return this.fecIniPerDeclarado;
	}

	public void setFecIniPerDeclarado(Date fecIniPerDeclarado) {
		this.fecIniPerDeclarado = fecIniPerDeclarado;
	}

	public Date getFecFinPerDeclarado() {
		return this.fecFinPerDeclarado;
	}

	public void setFecFinPerDeclarado(Date fecFinPerDeclarado) {
		this.fecFinPerDeclarado = fecFinPerDeclarado;
	}

	public Date getFecIniPerPresentado() {
		return this.fecIniPerPresentado;
	}

	public void setFecIniPerPresentado(Date fecIniPerPresentado) {
		this.fecIniPerPresentado = fecIniPerPresentado;
	}

	public Date getFecFinPerPresentado() {
		return this.fecFinPerPresentado;
	}

	public void setFecFinPerPresentado(Date fecFinPerPresentado) {
		this.fecFinPerPresentado = fecFinPerPresentado;
	}


}
