package mx.gob.imss.ctirss.correccion.catalogos.base.model;
// default package
// Generated 25/11/2011 10:08:26 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SacTipincidenc generated by hbm2java
 */
@MappedSuperclass
public class AbstractSacTipincidenc extends AbstractModel {

	private BigDecimal cvePk;
	private int numHibernateVersion;
	private String cveCodigo;
	private String desTipincidenc;

	public AbstractSacTipincidenc() {
	}

	public AbstractSacTipincidenc(BigDecimal cvePk, int numHibernateVersion,
			String cveCodigo, String desTipincidenc) {
		this.cvePk = cvePk;
		this.numHibernateVersion = numHibernateVersion;
		this.cveCodigo = cveCodigo;
		this.desTipincidenc = desTipincidenc;
	}

	@Id
	@Column(name = "CVE_PK")
	public BigDecimal getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(BigDecimal cvePk) {
		this.cvePk = cvePk;
	}

	@Column(name = "NUM_HIBERNATE_VERSION")
	public int getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(int numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	@Column(name = "CVE_CODIGO")
	public String getCveCodigo() {
		return this.cveCodigo;
	}

	public void setCveCodigo(String cveCodigo) {
		this.cveCodigo = cveCodigo;
	}

	@Column(name = "DES_TIPINCIDENC")
	public String getDesTipincidenc() {
		return this.desTipincidenc;
	}

	public void setDesTipincidenc(String desTipincidenc) {
		this.desTipincidenc = desTipincidenc;
	}

}
