package mx.gob.imss.ctirss.correccion.catalogos.base.model;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;

import mx.gob.imss.ctirss.correccion.catalogos.model.SacDelegacion;
import mx.gob.imss.ctirss.correccion.catalogos.model.SacSubdelegacion;
import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.correccion.model.CgcCatTipo;
import mx.gob.imss.ctirss.correccion.model.SacMunicipio;

/**
 * SacSubdelegacion generated by hbm2java
 */
@MappedSuperclass
public class AbstractSacSubdelegacion extends AbstractModel {

	@Id
	@Column(name="CVE_PK")
	private Long cvePk;
	
	@Column(name="NUM_HIBERNATE_VERSION")
	private Integer numHibernateVersion;
	
	@Column(name="CVE_CODIGO")
	private String cveCodigo;
	
	@Column(name="NOM_NOMBRE")
	private String nomNombre;
	
	@Column(name="CVE_FK_UBICACION")
	private Integer cveFkUbicacion;

    @ManyToOne
	@JoinColumn(name="CVE_FK_DELEGACION")
	private SacDelegacion sacDelegacion;

	

    
	public SacDelegacion getSacDelegacion() {
		return sacDelegacion;
	}

	public void setSacDelegacion(SacDelegacion sacDelegacion) {
		this.sacDelegacion = sacDelegacion;
	}

	public Long getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(Long cvePk) {
		this.cvePk = cvePk;
	}

	public Integer getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(Integer numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	public String getCveCodigo() {
		return this.cveCodigo;
	}

	public void setCveCodigo(String cveCodigo) {
		this.cveCodigo = cveCodigo;
	}

	public String getNomNombre() {
		return this.nomNombre;
	}

	public void setNomNombre(String nomNombre) {
		this.nomNombre = nomNombre;
	}

	public Integer getCveFkUbicacion() {
		return this.cveFkUbicacion;
	}

	public void setCveFkUbicacion(Integer cveFkUbicacion) {
		this.cveFkUbicacion = cveFkUbicacion;
	}
}
