package mx.gob.imss.ctirss.correccion.catalogos.base.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * SatObra generated by hbm2java
 */
@MappedSuperclass
public class AbstractSatObra extends AbstractModel {

	@Id
	@Column(name="CVE_PK")
	private BigDecimal cvePk;
	
	@Column(name="NUM_HIBERNATE_VERSION")
	private int numHibernateVersion;
	
	@Column(name="FEC_FECHAFORMATO_FC")
	private Date fecFechaformatoFc;
	
	@Column(name="FEC_FECHAINICIO_FC")
	private Date fecFechainicioFc;
	
	@Column(name="FEC_FECHAREGISTRO_FC")
	private Date fecFecharegistroFc;
	
	@Column(name="FEC_FECHATERMINO_FC")
	private Date fecFechaterminoFc;
	
	@Column(name="REF_LUGARREGISTRO")
	private String refLugarregistro;
	
	@Column(name="CAN_SUPERFICIE")
	private BigDecimal canSuperficie;
	
	@Column(name="CVE_FK_UBICACION")
	private BigDecimal cveFkUbicacion;
	
	@Column(name="CVE_FK_PATRON")
	private BigDecimal cveFkPatron;
	
	@Column(name="CVE_FK_EXPINSUMOS")
	private BigDecimal cveFkExpinsumos;
	
	@Column(name="CVE_NROREGOBRA")
	private long cveNroregobra;
	
	@Column(name="IMP_IMPORTE")
	private BigDecimal impImporte;
	
	@Column(name="IND_ART251")
	private boolean indArt251;
	
	@Column(name="NOM_CONTRATANTE")
	private String nomContratante;
	
	@Column(name="CVE_NROCONTRATO")
	private String cveNrocontrato;
	
	@Column(name="CVE_NROLICITACION")
	private String cveNrolicitacion;
	
	@Column(name="TIP_CLASEOBRA")
	private String tipClaseobra;
	
	@Column(name="CVE_FK_FASECONSTRUCCION")
	private BigDecimal cveFkFaseconstruccion;
	
	@Column(name="FEC_FECHACONTRATO_FC")
	private Date fecFechacontratoFc;
	
	@Column(name="CVE_FK_UNIDADMEDIDA")
	private BigDecimal cveFkUnidadmedida;
	
	@Column(name="CVE_FK_OBRAPRINCIPAL")
	private BigDecimal cveFkObraPrincipal;
	
	@Column(name="IND_AFIL15")
	private boolean indAfil15;
	
	@Column(name="CVE_FK_CANCELACION")
	private BigDecimal cveFkCancelacion;
	
	@Column(name="IND_FASECONS_REC")
	private boolean indFaseconsRec;
	
	@Column(name="DES_OTRA_FASE")
	private String desOtraFase;
	
	@Column(name="REF_RFC_PATRON")
	private String refRfcPatron;
	
	@Column(name="IND_HISTORICO")
	private Boolean indHistorico;

	public BigDecimal getCvePk() {
		return this.cvePk;
	}

	public void setCvePk(BigDecimal cvePk) {
		this.cvePk = cvePk;
	}
	
	public int getNumHibernateVersion() {
		return this.numHibernateVersion;
	}

	public void setNumHibernateVersion(int numHibernateVersion) {
		this.numHibernateVersion = numHibernateVersion;
	}

	public Date getFecFechaformatoFc() {
		return this.fecFechaformatoFc;
	}

	public void setFecFechaformatoFc(Date fecFechaformatoFc) {
		this.fecFechaformatoFc = fecFechaformatoFc;
	}

	public Date getFecFechainicioFc() {
		return this.fecFechainicioFc;
	}

	public void setFecFechainicioFc(Date fecFechainicioFc) {
		this.fecFechainicioFc = fecFechainicioFc;
	}

	public Date getFecFecharegistroFc() {
		return this.fecFecharegistroFc;
	}

	public void setFecFecharegistroFc(Date fecFecharegistroFc) {
		this.fecFecharegistroFc = fecFecharegistroFc;
	}

	public Date getFecFechaterminoFc() {
		return this.fecFechaterminoFc;
	}

	public void setFecFechaterminoFc(Date fecFechaterminoFc) {
		this.fecFechaterminoFc = fecFechaterminoFc;
	}

	public String getRefLugarregistro() {
		return this.refLugarregistro;
	}

	public void setRefLugarregistro(String refLugarregistro) {
		this.refLugarregistro = refLugarregistro;
	}

	public BigDecimal getCanSuperficie() {
		return this.canSuperficie;
	}

	public void setCanSuperficie(BigDecimal canSuperficie) {
		this.canSuperficie = canSuperficie;
	}

	public BigDecimal getCveFkUbicacion() {
		return this.cveFkUbicacion;
	}

	public void setCveFkUbicacion(BigDecimal cveFkUbicacion) {
		this.cveFkUbicacion = cveFkUbicacion;
	}

	public BigDecimal getCveFkPatron() {
		return this.cveFkPatron;
	}

	public void setCveFkPatron(BigDecimal cveFkPatron) {
		this.cveFkPatron = cveFkPatron;
	}

	public BigDecimal getCveFkExpinsumos() {
		return this.cveFkExpinsumos;
	}

	public void setCveFkExpinsumos(BigDecimal cveFkExpinsumos) {
		this.cveFkExpinsumos = cveFkExpinsumos;
	}

	public long getCveNroregobra() {
		return this.cveNroregobra;
	}

	public void setCveNroregobra(long cveNroregobra) {
		this.cveNroregobra = cveNroregobra;
	}

	public BigDecimal getImpImporte() {
		return this.impImporte;
	}

	public void setImpImporte(BigDecimal impImporte) {
		this.impImporte = impImporte;
	}

	public boolean isIndArt251() {
		return this.indArt251;
	}

	public void setIndArt251(boolean indArt251) {
		this.indArt251 = indArt251;
	}

	public String getNomContratante() {
		return this.nomContratante;
	}

	public void setNomContratante(String nomContratante) {
		this.nomContratante = nomContratante;
	}

	public String getCveNrocontrato() {
		return this.cveNrocontrato;
	}

	public void setCveNrocontrato(String cveNrocontrato) {
		this.cveNrocontrato = cveNrocontrato;
	}

	public String getCveNrolicitacion() {
		return this.cveNrolicitacion;
	}

	public void setCveNrolicitacion(String cveNrolicitacion) {
		this.cveNrolicitacion = cveNrolicitacion;
	}

	public String getTipClaseobra() {
		return this.tipClaseobra;
	}

	public void setTipClaseobra(String tipClaseobra) {
		this.tipClaseobra = tipClaseobra;
	}

	public BigDecimal getCveFkFaseconstruccion() {
		return this.cveFkFaseconstruccion;
	}

	public void setCveFkFaseconstruccion(BigDecimal cveFkFaseconstruccion) {
		this.cveFkFaseconstruccion = cveFkFaseconstruccion;
	}

	public Date getFecFechacontratoFc() {
		return this.fecFechacontratoFc;
	}

	public void setFecFechacontratoFc(Date fecFechacontratoFc) {
		this.fecFechacontratoFc = fecFechacontratoFc;
	}

	public BigDecimal getCveFkUnidadmedida() {
		return this.cveFkUnidadmedida;
	}

	public void setCveFkUnidadmedida(BigDecimal cveFkUnidadmedida) {
		this.cveFkUnidadmedida = cveFkUnidadmedida;
	}

	public boolean isIndAfil15() {
		return this.indAfil15;
	}

	public void setIndAfil15(boolean indAfil15) {
		this.indAfil15 = indAfil15;
	}

	public BigDecimal getCveFkCancelacion() {
		return this.cveFkCancelacion;
	}

	public void setCveFkCancelacion(BigDecimal cveFkCancelacion) {
		this.cveFkCancelacion = cveFkCancelacion;
	}

	public boolean isIndFaseconsRec() {
		return this.indFaseconsRec;
	}

	public void setIndFaseconsRec(boolean indFaseconsRec) {
		this.indFaseconsRec = indFaseconsRec;
	}

	public String getDesOtraFase() {
		return this.desOtraFase;
	}

	public void setDesOtraFase(String desOtraFase) {
		this.desOtraFase = desOtraFase;
	}

	public String getRefRfcPatron() {
		return this.refRfcPatron;
	}

	public void setRefRfcPatron(String refRfcPatron) {
		this.refRfcPatron = refRfcPatron;
	}

	public Boolean getIndHistorico() {
		return this.indHistorico;
	}

	public void setIndHistorico(Boolean indHistorico) {
		this.indHistorico = indHistorico;
	}

	public BigDecimal getCveFkObraPrincipal() {
		return cveFkObraPrincipal;
	}

	public void setCveFkObraPrincipal(BigDecimal cveFkObraPrincipal) {
		this.cveFkObraPrincipal = cveFkObraPrincipal;
	}
	
}
