#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
#Tiles redirect

bienvenida.(class)=org.springframework.web.servlet.view.tiles2.TilesView
bienvenida.url=bienvenida
 
analisisConsulta.(class)=org.springframework.web.servlet.view.tiles2.TilesView
analisisConsulta.url=analisisConsulta

consultaReportes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaReportes.url=consultaReportes

consultaBitacora.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaBitacora.url=consultaBitacora

consultaConcentrado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaConcentrado.url=consultaConcentrado

detalleSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleSolicitud.url=detalleSolicitud

detalleSolicitudDictamen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleSolicitudDictamen.url=detalleSolicitudDictamen

rectificacionMovimiento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
rectificacionMovimiento.url=rectificacionMovimiento

rectificacionMovimientoDictamen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
rectificacionMovimientoDictamen.url=rectificacionMovimientoDictamen

omisionesDictamen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
omisionesDictamen.url=omisionesDictamen

autorizarRectificacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
autorizarRectificacion.url=capturaDatosClem

modificaDatosClem.(class)=org.springframework.web.servlet.view.tiles2.TilesView
modificaDatosClem.url=capturaDatosClem

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

internalErrorMsj.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalErrorMsj.url=internalErrorMsj

analisisConsultaDictamen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
analisisConsultaDictamen.url=analisisConsultaDictamen

datosPatronDictamen.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosPatronDictamen.url=datosPatronDictamen

detalleDictamen.(class)=org.springframework.web.servlet.view.JstlView
detalleDictamen.url=/WEB-INF/views/analisis/detalleDictamen.jsp

autenticacionFirma.(class)=org.springframework.web.servlet.view.tiles2.TilesView
autenticacionFirma.url=autenticacionFirma

firmaClem.(class)=org.springframework.web.servlet.view.tiles2.TilesView
firmaClem.url=firmaClem

verClemFirmada.(class)=org.springframework.web.servlet.view.tiles2.TilesView
verClemFirmada.url=verClemFirmada

desecharSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
desecharSolicitud.url=desecharSolicitud
