#weblogic.autodeploy=/Applications/Servidores/weblogic/10.3.4/wls1034_dev/user_projects/domains/delta_domain/autodeploy

weblogic.autodeploy = C:\\Oracle\\Middleware\\user_projects\\domains\\dev_domain\\autodeploy