


#Datos del ambiente de desarrollo QA


service.provider.context=weblogic.jndi.WLInitialContextFactory

#service.provider.url=t3://172.24.116.37:15051,172.24.116.37:15052
#service.security.principal=admin_wlgeceqa
#service.security.credentials=wlgeceqa_admin


#Stage
service.provider.url=t3://vzapma07.imss.gob.mx:8001,vzapma07.imss.gob.mx:8003,vzapma12.imss.gob.mx:8001,vzapma12.imss.gob.mx:8003,vzapmb09.imss.gob.mx:8001,vzapmb09.imss.gob.mx:8003
service.security.principal=wloperator
service.security.credentials=53rv4p%wl%1p1r1t1r$.




service.jndi.bean=domicilioServiceBusiness#mx.gob.imss.ctirss.delta.gestion.domicilio.service.interfaces.domicilio.DomicilioServiceBusinessRemote
service.jndi.bean.solicitud=solicitudBusiness#mx.gob.imss.ctirss.delta.gestion.solicitud.service.interfaces.SolicitudBusinessRemote
service.jndi.bean.sujetoObligado=sujetoObligadoServiceBusiness#mx.gob.imss.ctirss.delta.gestion.patronal.service.interfaces.SujetoObligadoServiceBusinessRemote
service.jndi.bean.firmaSolicitud=firmaDigitalBusiness#mx.gob.imss.ctirss.delta.gestion.solicitud.service.interfaces.FirmaDigitalBusinessRemote

