
/*
 * 
 */

package mx.gob.imss.consulta.tramites.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 28 11:30:16 CDT 2014
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "ServActualizaFuentesBDTUService", 
                  wsdlLocation = "file:/share/oracle/servapdir01_domain/servapdir_cluster1/wsdl/ServActualizaFuentesBDTUService.wsdl",
                  targetNamespace = "http://service.tramites.consulta.imss.gob.mx/") 
public class ServActualizaFuentesBDTUService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.tramites.consulta.imss.gob.mx/", "ServActualizaFuentesBDTUService");
    public final static QName ServActualizaFuentesBDTUPort = new QName("http://service.tramites.consulta.imss.gob.mx/", "ServActualizaFuentesBDTUPort");
    private final static int serviceTimeOut = 10000;
    private final static int connectTimeOut = 5000;
    static {
        URL url = null;
        try {
        	url = Thread.currentThread().getContextClassLoader().getResource("file:/share/oracle/servapdir01_domain/servapdir_cluster1/wsdl/ServActualizaFuentesBDTUService.wsdl");
        } catch (Exception e) {
            System.err.println("Can not initialize the default wsdl from http://adodigital.imss.gob.mx/WSActualizaFuentesBDTU/ServActualizaFuentesBDTUService?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ServActualizaFuentesBDTUService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServActualizaFuentesBDTUService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServActualizaFuentesBDTUService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ServActualizaFuentesBDTU
     */
    @WebEndpoint(name = "ServActualizaFuentesBDTUPort")
    public ServActualizaFuentesBDTU getServActualizaFuentesBDTUPort() {
        ServActualizaFuentesBDTU ws =  super.getPort(ServActualizaFuentesBDTUPort, ServActualizaFuentesBDTU.class);
        ((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
    	return ws;
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServActualizaFuentesBDTU
     */
    @WebEndpoint(name = "ServActualizaFuentesBDTUPort")
    public ServActualizaFuentesBDTU getServActualizaFuentesBDTUPort(WebServiceFeature... features) {
    	ServActualizaFuentesBDTU ws =  super.getPort(ServActualizaFuentesBDTUPort, ServActualizaFuentesBDTU.class, features);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
     	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
     	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
     	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
     	return ws;
    }

}
