
package mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IESServicioSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IESServicioSoap {


    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.SalidaAlta
     */
    @WebMethod(operationName = "AltaDocumento", action = "http://www.openuri.org/AltaDocumento")
    @WebResult(name = "AltaDocumentoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "AltaDocumento", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.AltaDocumento")
    @ResponseWrapper(localName = "AltaDocumentoResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.AltaDocumentoResponse")
    public SalidaAlta altaDocumento(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        EntradaAlta entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.SalidaBajaLogica
     */
    @WebMethod(operationName = "BajaLogicaDocumento", action = "http://www.openuri.org/BajaLogicaDocumento")
    @WebResult(name = "BajaLogicaDocumentoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "BajaLogicaDocumento", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.BajaLogicaDocumento")
    @ResponseWrapper(localName = "BajaLogicaDocumentoResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.BajaLogicaDocumentoResponse")
    public SalidaBajaLogica bajaLogicaDocumento(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        EntradaBajaLogica entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.SalidaBaja
     */
    @WebMethod(operationName = "BajaDocumento", action = "http://www.openuri.org/BajaDocumento")
    @WebResult(name = "BajaDocumentoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "BajaDocumento", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.BajaDocumento")
    @ResponseWrapper(localName = "BajaDocumentoResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.BajaDocumentoResponse")
    public SalidaBaja bajaDocumento(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        EntradaBaja entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.SalidaConsulta
     */
    @WebMethod(operationName = "ConsultaDocumento", action = "http://www.openuri.org/ConsultaDocumento")
    @WebResult(name = "ConsultaDocumentoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "ConsultaDocumento", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.ConsultaDocumento")
    @ResponseWrapper(localName = "ConsultaDocumentoResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.ConsultaDocumentoResponse")
    public SalidaConsulta consultaDocumento(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        EntradaConsulta entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.SalidaActualizacion
     */
    @WebMethod(operationName = "ActualizacionDocumento", action = "http://www.openuri.org/ActualizacionDocumento")
    @WebResult(name = "ActualizacionDocumentoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "ActualizacionDocumento", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.ActualizacionDocumento")
    @ResponseWrapper(localName = "ActualizacionDocumentoResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.v2.ActualizacionDocumentoResponse")
    public SalidaActualizacion actualizacionDocumento(
        @WebParam(name = "entrada", targetNamespace = "http://www.openuri.org/")
        EntradaActualizacion entrada);

}
