home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

vista.tramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vista.tramite.url=vistaTramite

vista.menu.principal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vista.menu.principal.url=vistMenuPrincipal

detalleIdentidad.(class)=org.springframework.web.servlet.view.JstlView
detalleIdentidad.url=/WEB-INF/views/portal/detalle/identidad/detalleIdentidad.jsp

detalleNRP.(class)=org.springframework.web.servlet.view.JstlView
detalleNRP.url=/WEB-INF/views/portal/detalle/sujeto/detalleNRP.jsp

detalleNSS.(class)=org.springframework.web.servlet.view.JstlView
detalleNSS.url=/WEB-INF/views/portal/detalle/sujeto/detalleNSS.jsp

listaNrp.(class)=org.springframework.web.servlet.view.JstlView
listaNrp.url=/WEB-INF/views/portal/detalle/sujeto/listaNRP.jsp

formularioBusqueda.(class)=org.springframework.web.servlet.view.JstlView
formularioBusqueda.url=/WEB-INF/views/portal/formularioBusqueda.jsp

accionesIdentidad.(class)=org.springframework.web.servlet.view.JstlView
accionesIdentidad.url=/WEB-INF/views/portal/detalle/identidad/accionesIdentidad.jsp

accionesSujeto.(class)=org.springframework.web.servlet.view.JstlView
accionesSujeto.url=/WEB-INF/views/portal/detalle/sujeto/accionesSujeto.jsp