package mx.gob.imss.ctirss.delta.persistence;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import mx.gob.imss.ctirss.delta.framework.annotations.ComponentComboCampoDescripcion;
import mx.gob.imss.ctirss.delta.framework.annotations.OnSearchLlavePrimaria;


/**
 * DgCatVialidad generated by hbm2java
 */
@Entity
@Table(name="DG_CAT_VIALIDAD")

@OnSearchLlavePrimaria(atributos="cveTipoVial")
@ComponentComboCampoDescripcion(atributo="descripcion")
public  class DgCatVialidad implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer cveTipoVial;
	private String descripcion;
	

	public DgCatVialidad() {
	}

	public DgCatVialidad(BigDecimal cveTipoVial, String descripcion) {
	/*	this.cveTipoVial = cveTipoVial;
		this.descripcion = descripcion;
		*/
	}


	@Id
	@Column(name = "CVE_TIPO_VIAL", nullable = true, precision = 22, scale = 0)
	public Integer getCveTipoVial() {
		
		if(cveTipoVial!=null && cveTipoVial.intValue()<=0) return null;
		
		return this.cveTipoVial;
	}

	public void setCveTipoVial(Integer cveTipoVial) {
		this.cveTipoVial = cveTipoVial;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


}