package mx.gob.imss.ctirss.delta.persistence;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * DgDomicilioGeografico generated by hbm2java
 */

@Entity
@Table(name = "DG_DOMICILIO_GEOGRAFICO")
public class DgDomicilioGeografico implements Serializable {

	private static final long serialVersionUID = 1L;
	private Long domicilioId;
	private DgAsentamiento dgAsentamiento;
	private DgCatLocalidad dgCatLocalidad;
	private DgCatTipoDom dgCatTipoDom;
	private DgCodigosPostale DgCodigosPostale;
	
	private String nomvial;
	private Integer numextnum;
	private String numextalf;
	private String numextAnt;
	private Integer numintnum;
	private String numintalf;

	private BigDecimal refLatitud;
	private BigDecimal refLongitud;

	private DgVialidad dgVialidadByCveViaPrin;
	private DgVialidad dgVialidadByCveViaRef1;
	private DgVialidad dgVialidadByCveViaRef2;
	private DgVialidad dgVialidadByCveViaRef3;

	private String descripc;
	private String domGeog;
	private Date fechaHoraAlta;
	private String cveUsuario;
	
	private DgDomiciliosCamino dgDomiciliosCamino;
	private DgDomiciliosCarretera dgDomiciliosCarretera;

	private String hastableKeyDG;

	private Date fecRegistroAlta;
	private Date fecRegistroActualizado;
	private Date fecRegistroBaja;
	
	
	/*se adicionaron los atributos simples de localidad para hacer el insert **/
	private String cveLoc;
	private long cvePeriodo; 
	
	
	
	
	public DgDomicilioGeografico() {

		// this.dgDomiciliosCaminos = new DgDomiciliosCaminos();
		// this.dgDomiciliosCarreteras = new DgDomiciliosCarreteras();

	}

	public DgDomicilioGeografico(Long domicilioId,
			DgAsentamiento dgAsentamiento, DgCatTipoDom dgCatTipoDom,
			DgCodigosPostale DgCodigosPostale, String nomvial) {
		this.domicilioId = domicilioId;
		this.dgAsentamiento = dgAsentamiento;
		this.dgCatTipoDom = dgCatTipoDom;
		this.DgCodigosPostale = DgCodigosPostale;
		this.nomvial = nomvial;
	}
	
	public DgDomicilioGeografico(Long domicilioId,
			DgAsentamiento dgAsentamiento, DgCatTipoDom dgCatTipoDom,
			DgCodigosPostale DgCodigosPostale, String nomvial, 
			DgDomiciliosCamino dgDomiciliosCamino, 
			DgDomiciliosCarretera dgDomiciliosCarretera) {
		this.domicilioId = domicilioId;
		this.dgAsentamiento = dgAsentamiento;
		this.dgCatTipoDom = dgCatTipoDom;
		this.DgCodigosPostale = DgCodigosPostale;
		this.nomvial = nomvial;
		this.dgDomiciliosCamino = dgDomiciliosCamino;
		this.dgDomiciliosCarretera = dgDomiciliosCarretera;
	}

	public DgDomicilioGeografico(Long domicilioId,
			DgVialidad dgVialidadByCveViaRef3,
			DgVialidad dgVialidadByCveViaPrin,
			DgVialidad dgVialidadByCveViaRef2, DgAsentamiento dgAsentamiento,
			DgCatLocalidad dgCatLocalidad, DgCatTipoDom dgCatTipoDom,
			DgVialidad dgVialidadByCveViaRef1,
			DgCodigosPostale DgCodigosPostale, String nomvial,
			Integer numextnum, String numextalf, String numextAnt,
			Integer numintnum, String numintalf, String descripc,
			String domGeog, Date fechaHoraAlta, String cveUsuario) {
		this.domicilioId = domicilioId;
		this.dgAsentamiento = dgAsentamiento;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatTipoDom = dgCatTipoDom;
		this.DgCodigosPostale = DgCodigosPostale;
		this.nomvial = nomvial;
		this.numextnum = numextnum;
		this.numextalf = numextalf;
		this.numextAnt = numextAnt;
		this.numintnum = numintnum;
		this.numintalf = numintalf;
		this.descripc = descripc;
		this.domGeog = domGeog;
		this.fechaHoraAlta = fechaHoraAlta;
		this.cveUsuario = cveUsuario;
		this.dgVialidadByCveViaRef1 = dgVialidadByCveViaRef1;
		this.dgVialidadByCveViaRef2 = dgVialidadByCveViaRef2;
		this.dgVialidadByCveViaRef3 = dgVialidadByCveViaRef3;
		this.dgVialidadByCveViaPrin = dgVialidadByCveViaPrin;
		
		
		// this.dgDomiciliosCaminos = dgDomiciliosCaminos;
		// this.dgDomiciliosCarreteras = dgDomiciliosCarreteras;
	}
	
	
	public DgDomicilioGeografico(Long domicilioId,
			DgVialidad dgVialidadByCveViaRef3,
			DgVialidad dgVialidadByCveViaPrin,
			DgVialidad dgVialidadByCveViaRef2, DgAsentamiento dgAsentamiento,
			DgCatLocalidad dgCatLocalidad, DgCatTipoDom dgCatTipoDom,
			DgVialidad dgVialidadByCveViaRef1,
			DgCodigosPostale DgCodigosPostale, String nomvial,
			Integer numextnum, String numextalf, String numextAnt,
			Integer numintnum, String numintalf, String descripc,
			String domGeog, Date fechaHoraAlta, String cveUsuario, DgDomiciliosCamino dgDomiciliosCamino,
			DgDomiciliosCarretera dgDomiciliosCarretera) {
		this.domicilioId = domicilioId;
		this.dgAsentamiento = dgAsentamiento;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatTipoDom = dgCatTipoDom;
		this.DgCodigosPostale = DgCodigosPostale;
		this.nomvial = nomvial;
		this.numextnum = numextnum;
		this.numextalf = numextalf;
		this.numextAnt = numextAnt;
		this.numintnum = numintnum;
		this.numintalf = numintalf;
		this.descripc = descripc;
		this.domGeog = domGeog;
		this.fechaHoraAlta = fechaHoraAlta;
		this.cveUsuario = cveUsuario;
		this.dgVialidadByCveViaRef1 = dgVialidadByCveViaRef1;
		this.dgVialidadByCveViaRef2 = dgVialidadByCveViaRef2;
		this.dgVialidadByCveViaRef3 = dgVialidadByCveViaRef3;
		this.dgVialidadByCveViaPrin = dgVialidadByCveViaPrin;
		this.dgDomiciliosCamino = dgDomiciliosCamino;
		this.dgDomiciliosCarretera = dgDomiciliosCarretera;
	}


	@Id
	@Column(name = "DOMICILIO_ID", nullable = false, precision = 10, scale = 0)
	@SequenceGenerator(name = "CRS_DOMICILIO_ID_GENERATOR", sequenceName = "SEQ_DGDOMICILIOGEOGRAFICO", allocationSize = 1)
	@GeneratedValue(generator = "CRS_DOMICILIO_ID_GENERATOR")
	public Long getDomicilioId() {
		return this.domicilioId;
	}

	public void setDomicilioId(Long domicilioId) {
		this.domicilioId = domicilioId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CODIGO", referencedColumnName = "CODIGO", nullable = false),
			@JoinColumn(name = "CVE_ASEN", referencedColumnName = "CVE_ASEN", nullable = false),
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", nullable = false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", nullable = false)
			/*
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", nullable = false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", nullable = false)
			*/ 
			
			})
	public DgCodigosPostale getDgCodigosPostale() {
		return this.DgCodigosPostale;
	}

	public void setDgCodigosPostale(DgCodigosPostale DgCodigosPostale) {
		this.DgCodigosPostale = DgCodigosPostale;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CVE_ASEN", referencedColumnName = "CVE_ASEN", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", nullable = false, insertable = false, updatable = false)
			/*
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", nullable = false, insertable = false, updatable = false) 
			*/
			})
	public DgAsentamiento getDgAsentamiento() {
		return this.dgAsentamiento;
	}

	public void setDgAsentamiento(DgAsentamiento dgAsentamiento) {
		this.dgAsentamiento = dgAsentamiento;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_PRIN")
	public DgVialidad getDgVialidadByCveViaPrin() {
		return this.dgVialidadByCveViaPrin;
	}

	public void setDgVialidadByCveViaPrin(DgVialidad dgVialidadByCveViaPrin) {
		this.dgVialidadByCveViaPrin = dgVialidadByCveViaPrin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_REF1")
	public DgVialidad getDgVialidadByCveViaRef1() {
		return this.dgVialidadByCveViaRef1;
	}

	public void setDgVialidadByCveViaRef1(DgVialidad dgVialidadByCveViaRef1) {
		this.dgVialidadByCveViaRef1 = dgVialidadByCveViaRef1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_REF2")
	public DgVialidad getDgVialidadByCveViaRef2() {
		return this.dgVialidadByCveViaRef2;
	}

	public void setDgVialidadByCveViaRef2(DgVialidad dgVialidadByCveViaRef2) {
		this.dgVialidadByCveViaRef2 = dgVialidadByCveViaRef2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_REF3")
	public DgVialidad getDgVialidadByCveViaRef3() {
		return this.dgVialidadByCveViaRef3;
	}

	public void setDgVialidadByCveViaRef3(DgVialidad dgVialidadByCveViaRef3) {
		this.dgVialidadByCveViaRef3 = dgVialidadByCveViaRef3;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", insertable = false, updatable = false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", insertable = false, updatable = false),
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", insertable = false, updatable = false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", insertable = false, updatable = false) })
	public DgCatLocalidad getDgCatLocalidad() {
		return this.dgCatLocalidad;
	}

	public void setDgCatLocalidad(DgCatLocalidad dgCatLocalidad) {
		this.dgCatLocalidad = dgCatLocalidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_TIPO_DOM", nullable = false)
	public DgCatTipoDom getDgCatTipoDom() {
		return this.dgCatTipoDom;
	}

	public void setDgCatTipoDom(DgCatTipoDom dgCatTipoDom) {
		this.dgCatTipoDom = dgCatTipoDom;
	}

	@Column(name = "NOMVIAL", nullable = false, length = 256)
	public String getNomvial() {

		if (this.nomvial == null)
			return "";

		return this.nomvial;
	}

	public void setNomvial(String nomvial) {
		this.nomvial = nomvial;
	}

	@Column(name = "NUMEXTNUM", precision = 5, scale = 0)
	public Integer getNumextnum() {
		return this.numextnum;
	}

	public void setNumextnum(Integer numextnum) {
		this.numextnum = numextnum;
	}

	@Column(name = "NUMEXTALF", length = 35)
	public String getNumextalf() {
		return this.numextalf;
	}

	public void setNumextalf(String numextalf) {
		this.numextalf = numextalf;
	}

	@Column(name = "NUMEXT_ANT", length = 35)
	public String getNumextAnt() {
		return this.numextAnt;
	}

	public void setNumextAnt(String numextAnt) {
		this.numextAnt = numextAnt;
	}

	@Column(name = "NUMINTNUM", precision = 5, scale = 0)
	public Integer getNumintnum() {
		return this.numintnum;
	}

	public void setNumintnum(Integer numintnum) {
		this.numintnum = numintnum;
	}

	@Column(name = "NUMINTALF", length = 35)
	public String getNumintalf() {
		return this.numintalf;
	}

	public void setNumintalf(String numintalf) {
		this.numintalf = numintalf;
	}

	// TODO Cambiar la precision y escala correcta
	@Column(name = "REF_LATITUD", precision = 11, scale = 8)
	public BigDecimal getRefLatitud() {
		return refLatitud;
	}

	public void setRefLatitud(BigDecimal refLatitud) {
		this.refLatitud = refLatitud;
	}

	// TODO Cambiar a la precision y escala correcta
	@Column(name = "REF_LONGITUD", precision = 11, scale = 8)
	public BigDecimal getRefLongitud() {
		return refLongitud;
	}

	public void setRefLongitud(BigDecimal refLongitud) {
		this.refLongitud = refLongitud;
	}

	@Column(name = "DESCRIPC")
	public String getDescripc() {
		return this.descripc;
	}

	public void setDescripc(String descripc) {
		this.descripc = descripc;
	}

	@Column(name = "DOM_GEOG")
	public String getDomGeog() {
		return this.domGeog;
	}

	public void setDomGeog(String domGeog) {
		this.domGeog = domGeog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_HORA_ALTA")
	public Date getFechaHoraAlta() {
		return this.fechaHoraAlta;
	}

	public void setFechaHoraAlta(Date fechaHoraAlta) {
		this.fechaHoraAlta = fechaHoraAlta;
	}

	@Column(name = "CVE_USUARIO", length = 20)
	public String getCveUsuario() {
		return this.cveUsuario;
	}

	public void setCveUsuario(String cveUsuario) {
		this.cveUsuario = cveUsuario;
	}

	
	
	 @OneToOne(fetch = FetchType.EAGER, mappedBy = "dgDomicilioGeografico")
	 public DgDomiciliosCamino getDgDomiciliosCamino() {
	 return this.dgDomiciliosCamino;
	 }
	 public void setDgDomiciliosCamino(DgDomiciliosCamino
	 dgDomiciliosCaminos) {
	 this.dgDomiciliosCamino = dgDomiciliosCaminos;
	 }
	
	 @OneToOne(fetch = FetchType.EAGER, mappedBy = "dgDomicilioGeografico")
	 public DgDomiciliosCarretera getDgDomiciliosCarretera() {
	 return this.dgDomiciliosCarretera;
	 }
	
	 public void setDgDomiciliosCarretera(
			 DgDomiciliosCarretera dgDomiciliosCarretera) {
	 this.dgDomiciliosCarretera = dgDomiciliosCarretera;
	 }

	@Transient
	public String getHastableKeyDG() {
		return hastableKeyDG;
	}

	public void setHastableKeyDG(String hastableKeyDG) {
		this.hastableKeyDG = hastableKeyDG;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}
	
	@Column(name="CVE_LOC", length=4)
	public String getCveLoc() {
		return cveLoc;
	}

	public void setCveLoc(String cveLoc) {
		this.cveLoc = cveLoc;
	}

	@Column(name="CVE_PERIODO", precision=2)
	public long getCvePeriodo() {
		return cvePeriodo;
	}

	public void setCvePeriodo(long cvePeriodo) {
		this.cvePeriodo = cvePeriodo;
	}


}