package mx.gob.imss.ctirss.delta.persistence;


// Generated 15/12/2014 09:02:31 PM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SpcStatusNotificacion generated by hbm2java
 */
@Entity
@Table(name = "SPC_STATUS_NOTIFICACION")
public class SpcStatusNotificacion implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "CVE_ID_ESTADO_NOTIFICACION")
	private long cveIdEstadoNotificacion;
	
	@Column(name = "DES_ESTADO_NOTIFICACION")
	private String desEstadoNotificacion;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_ALTA")
	private Date fecRegistroAlta;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	private Date fecRegistroActualizado;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_BAJA")
	private Date fecRegistroBaja;
	
	@OneToMany(mappedBy = "spcStatusNotificacion")
	private Set<SptNotificaTramPensiones> sptNotificaTramPensioneses;

	public SpcStatusNotificacion() {}

	
	public long getCveIdEstadoNotificacion() {
		return cveIdEstadoNotificacion;
	}

	public void setCveIdEstadoNotificacion(long cveIdEstadoNotificacion) {
		this.cveIdEstadoNotificacion = cveIdEstadoNotificacion;
	}

	public String getDesEstadoNotificacion() {
		return desEstadoNotificacion;
	}

	public void setDesEstadoNotificacion(String desEstadoNotificacion) {
		this.desEstadoNotificacion = desEstadoNotificacion;
	}

	public Date getFecRegistroAlta() {
		return fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}

	public Date getFecRegistroActualizado() {
		return fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	public Date getFecRegistroBaja() {
		return fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	public Set<SptNotificaTramPensiones> getSptNotificaTramPensioneses() {
		return sptNotificaTramPensioneses;
	}

	public void setSptNotificaTramPensioneses(
			Set<SptNotificaTramPensiones> sptNotificaTramPensioneses) {
		this.sptNotificaTramPensioneses = sptNotificaTramPensioneses;
	}
}
