package mx.gob.imss.ctirss.delta.persistence;


import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SpcTipoNotificacion generated by hbm2java
 */
@Entity
@Table(name = "SPC_TIPO_NOTIFICACION")
public class SpcTipoNotificacion implements Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "CVE_ID_TIPO_NOTIFICACION")
	private long cveIdTipoNotificacion;
	
	@Column(name = "DES_NOTIFICACION")
	private String desNotificacion;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_ALTA")
	private Date fecRegistroAlta;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	private Date fecRegistroActualizado;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_BAJA")
	private Date fecRegistroBaja;
	
	@Column(name = "NUM_DURACION_MAXIMA")
	private Integer numDuracionMaxima;
	
	@Column(name = "NUM_FRECUENCIA")
	private Integer numFrecuencia;
	
	@Column(name = "IND_TIPO_DIAS_LABORABLE")
	private Integer indTipoDiasLaborable;
	
	@OneToMany(mappedBy = "spcTipoNotificacion")
	private Set<SptNotificaTramPensiones> sptNotificaTramPensioneses ;

	public SpcTipoNotificacion() {}

	public long getCveIdTipoNotificacion() {
		return cveIdTipoNotificacion;
	}

	public void setCveIdTipoNotificacion(long cveIdTipoNotificacion) {
		this.cveIdTipoNotificacion = cveIdTipoNotificacion;
	}

	public String getDesNotificacion() {
		return desNotificacion;
	}

	public void setDesNotificacion(String desNotificacion) {
		this.desNotificacion = desNotificacion;
	}

	public Date getFecRegistroAlta() {
		return fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}

	public Date getFecRegistroActualizado() {
		return fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	public Date getFecRegistroBaja() {
		return fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	public Integer getNumDuracionMaxima() {
		return numDuracionMaxima;
	}

	public void setNumDuracionMaxima(Integer numDuracionMaxima) {
		this.numDuracionMaxima = numDuracionMaxima;
	}

	public Integer getNumFrecuencia() {
		return numFrecuencia;
	}

	public void setNumFrecuencia(Integer numFrecuencia) {
		this.numFrecuencia = numFrecuencia;
	}

	public Integer getIndTipoDiasLaborable() {
		return indTipoDiasLaborable;
	}

	public void setIndTipoDiasLaborable(Integer indTipoDiasLaborable) {
		this.indTipoDiasLaborable = indTipoDiasLaborable;
	}

	public Set<SptNotificaTramPensiones> getSptNotificaTramPensioneses() {
		return sptNotificaTramPensioneses;
	}

	public void setSptNotificaTramPensioneses(
			Set<SptNotificaTramPensiones> sptNotificaTramPensioneses) {
		this.sptNotificaTramPensioneses = sptNotificaTramPensioneses;
	}
}
