package mx.gob.imss.ctirss.delta.persistence;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SptNotificaTramPensiones generated by hbm2java
 */
@Entity
@Table(name = "SPT_NOTIFICA_TRAM_PENSIONES")
public class SptNotificaTramPensiones implements Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "CVE_ID_NOTIFICACIONES")
	private long cveIdNotificaciones;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CVE_ID_TIPO_NOTIFICACION")
	private SpcTipoNotificacion spcTipoNotificacion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CVE_ID_ESTADO_NOTIFICACION")
	private SpcStatusNotificacion spcStatusNotificacion;
	
	@Column(name = "CVE_ID_TRAMITE_PENSION")
	private long cveIdTramitePension;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_EMISION")
	private Date fecEmision;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_ATENCION")
	private Date fecAtencion;
	
	@Column(name = "CVE_CUENTA_USUARIO")
	private String cveCuentaUsuario;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_ALTA")
	private Date fecRegistroAlta;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	private Date fecRegistroActualizado;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_REGISTRO_BAJA")
	private Date fecRegistroBaja;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_SIGUIENTE_NOTIFICACION")
	private Date fecSiguienteNotificacion;
	
	@Column(name = "DES_URL_NOTIFICACION")
	private String desUrlNotificacion;

	
	public SptNotificaTramPensiones(){}


	public long getCveIdNotificaciones() {
		return cveIdNotificaciones;
	}


	public void setCveIdNotificaciones(long cveIdNotificaciones) {
		this.cveIdNotificaciones = cveIdNotificaciones;
	}


	public SpcTipoNotificacion getSpcTipoNotificacion() {
		return spcTipoNotificacion;
	}


	public void setSpcTipoNotificacion(SpcTipoNotificacion spcTipoNotificacion) {
		this.spcTipoNotificacion = spcTipoNotificacion;
	}


	public SpcStatusNotificacion getSpcStatusNotificacion() {
		return spcStatusNotificacion;
	}


	public void setSpcStatusNotificacion(SpcStatusNotificacion spcStatusNotificacion) {
		this.spcStatusNotificacion = spcStatusNotificacion;
	}


	public long getCveIdTramitePension() {
		return cveIdTramitePension;
	}


	public void setCveIdTramitePension(long cveIdTramitePension) {
		this.cveIdTramitePension = cveIdTramitePension;
	}


	public Date getFecEmision() {
		return fecEmision;
	}


	public void setFecEmision(Date fecEmision) {
		this.fecEmision = fecEmision;
	}


	public Date getFecAtencion() {
		return fecAtencion;
	}


	public void setFecAtencion(Date fecAtencion) {
		this.fecAtencion = fecAtencion;
	}


	public String getCveCuentaUsuario() {
		return cveCuentaUsuario;
	}


	public void setCveCuentaUsuario(String cveCuentaUsuario) {
		this.cveCuentaUsuario = cveCuentaUsuario;
	}


	public Date getFecRegistroAlta() {
		return fecRegistroAlta;
	}


	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}


	public Date getFecRegistroActualizado() {
		return fecRegistroActualizado;
	}


	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}


	public Date getFecRegistroBaja() {
		return fecRegistroBaja;
	}


	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}


	public Date getFecSiguienteNotificacion() {
		return fecSiguienteNotificacion;
	}


	public void setFecSiguienteNotificacion(Date fecSiguienteNotificacion) {
		this.fecSiguienteNotificacion = fecSiguienteNotificacion;
	}


	public String getDesUrlNotificacion() {
		return desUrlNotificacion;
	}


	public void setDesUrlNotificacion(String desUrlNotificacion) {
		this.desUrlNotificacion = desUrlNotificacion;
	}
}
