<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>ClientesWebservices</artifactId>
    <groupId>mx.gob.imss.ctirss.clienteswebservices</groupId>
    <version>2.2-SNAPSHOT</version>
  </parent>
  <groupId>mx.gob.imss.ctirss.ws.asignacion</groupId>
  <artifactId>WebServiceAsignacionNSS</artifactId>
  <version>2.0-SNAPSHOT</version>
  <name>WebServiceAsignacionNSS</name>
  <url>http://maven.apache.org</url>
  <packaging>ejb</packaging>
  <properties>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<delta.framework.version>1.6-SNAPSHOT</delta.framework.version>
		<org.slf4j.version>1.6.1</org.slf4j.version>
		<endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
</properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
		<groupId>mx.gob.imss.trabajadores</groupId>
		<artifactId>excepcionesIMSS</artifactId>
		<version>1.0</version>
	</dependency>
	<dependency>
		<groupId>mx.gob.imss.trabajadores</groupId>
		<artifactId>iwtelnet</artifactId>
		<version>1.0</version>
	</dependency>
	<dependency>
		<groupId>mx.gob.imss.trabajadores</groupId>
		<artifactId>commons-lang</artifactId>
		<version>1.0</version>
	</dependency>
    <dependency>
		<groupId>javax.ejb</groupId>
		<artifactId>ejb-api</artifactId>
		<version>3.0</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring</artifactId>
		<version>2.5.6</version>
	</dependency>	
	<dependency>
   		<groupId>org.springframework</groupId>
   		<artifactId>spring-jdbc</artifactId>
   		<version>2.0.8</version>
	</dependency>
	<!-- Dependencias para el lOG -->
	<dependency>
		<groupId>log4j</groupId>
		<artifactId>log4j</artifactId>
		<version>1.2.16</version>
	</dependency>
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-api</artifactId>
		<version>${org.slf4j.version}</version>
	</dependency>
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-log4j12</artifactId>
		<version>${org.slf4j.version}</version>
	</dependency>
  </dependencies>
  
  <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
				</configuration>
			</plugin>
			</plugins>
			</build>
  
  <repositories>
		<repository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<layout>default</layout>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<layout>default</layout>
			<snapshots>
			</snapshots>
			<releases>
				<updatePolicy>never</updatePolicy>
			</releases>
		</pluginRepository>
	</pluginRepositories>
  
  <distributionManagement>
		<!-- use the following if you're not using a snapshot version. -->
		<repository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://172.16.5.134:8080/repository/repo/</url>
		</repository>
		<snapshotRepository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://172.16.5.134:8080/repository/repo/</url>
		</snapshotRepository>
	</distributionManagement>
  
</project>
