package mx.gob.imss.ctirss.delta.model.gestion.patronal;

public enum TipoAccionAfectacionEnum {
	 
	AGREGAR(1L),
	MODIFICAR(2L),
	ELIMINAR(3L),
	MOSTRAR_DETALLE_MODIFICACION_SRT(4L),
	MOSTRAR_ACUSE_DE_MODIFICACION_SRT(5L),
	MOSTRAR_AVISO_DE_MODIFICACION_SRT(6L),
	MOSTRAR_ACUSE_DATOS_PATRONALES(7L),
	MOSTRAR_DETALLE_MODIFICACION_DATOS_PATRONALES(8L),
	MOSTRAR_DETALLE_MODIFICACION_CENTRO_TRABAJO(9L),
	MOSTRAR_ACUSE_CENTRO_TRABAJO(10L),
	MOSTRAR_COMPROBANTE_TRAMITE_CENTRO_TRABAJO(11L),
	SOLICITAR_ASIGNACION(12L),
	AGREGAR_SOLICITUD(13L),
	AGREGAR_TRAMITE_SOLICITUD(14L),
	ACTUALIZAR_TRAMITE(15L),
	MOSTRAR_MENSAJE_SOLICITUD_CREADA(16L),
	MOSTRAR_MENSAJE_TRAMITE_ACTUALIZADO(17L),
	MOSTRAR_MENSAJE_RATIFICACION(18L),
	ATTACH_ACUSE(19L),
	ATTACH_COMPROBANTE_TRAMITE(20L),
	GUARDAR(21L),
	RATIFICAR(22L),
	ACCESO_NO_AUTORIZADO(23L);
	
	private TipoAccionAfectacionEnum(Long valor) {
		this.codigo = valor;
	}

	private Long codigo;

	public Long getValor() {
		return codigo;
	}

	public void setValor(Long valor) {
		this.codigo = valor;
	}

}
