#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp

consultaRiesgosTrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaRiesgosTrabajo.url=consultaRiesgosTrabajo

consultaRiesgosTrabajoRfc.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaRiesgosTrabajoRfc.url=consultaRiesgosTrabajoRfc

consultaSinRegistros.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaSinRegistros.url=consultaSinRegistros

errorRiesgostrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorRiesgostrabajo.url=errorRiesgostrabajo

paramNotExist.(class)=org.springframework.web.servlet.view.tiles2.TilesView
paramNotExist.url=paramNotExist

paginadorRiesgosTrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
paginadorRiesgosTrabajo.url=tablaRiesgosTrabajo

historialRiesgoTrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
historialRiesgoTrabajo.url=historialRiesgoTrabajo

consultaHistorialRiesgosTrabajo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaHistorialRiesgosTrabajo.url=consultaHistorialRiesgosTrabajo

consultaReporteXrfc.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaReporteXrfc.url=consultaReporteXrfc

logout.(class)=org.springframework.web.servlet.view.tiles2.TilesView
logout.url=logoutRiesgoTrabajo

errorHistorialRiesgos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorHistorialRiesgos.url=errorHistorial

terminosCondiciones.(class)=org.springframework.web.servlet.view.tiles2.TilesView
terminosCondiciones.url=terminosCondiciones

historialRTTNombres.(class)=org.springframework.web.servlet.view.tiles2.TilesView
historialRTTNombres.url=historialRTTNombres

inicialEscrito.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicialEscrito.url=inicialEscrito

contenidoEscrito.(class)=org.springframework.web.servlet.view.tiles2.TilesView
contenidoEscrito.url=contenidoEscrito

inicioEscritoVentanilla.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicioEscritoVentanilla.url=inicioEscritoVentanilla

contenidoEscritoVentanilla.(class)=org.springframework.web.servlet.view.tiles2.TilesView
contenidoEscritoVentanilla.url=contenidoEscritoVentanilla

finalizacionVentanilla.(class)=org.springframework.web.servlet.view.tiles2.TilesView
finalizacionVentanilla.url=finalizacionVentanilla

solicitudEscritoEncontrada.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitudEscritoEncontrada.url=solicitudEscritoEncontrada

consultaEscritoDesacuerdo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaEscritoDesacuerdo.url=consultaEscritoDesacuerdo

homeDesacuerdo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
homeDesacuerdo.url=homeDesacuerdo

listaEscritoDesacuerdo.(class)=org.springframework.web.servlet.view.JstlView
listaEscritoDesacuerdo.url=/WEB-INF/views/wizard/desacuerdo/consulta/listaEscritoDesacuerdo.jsp

escritoDesacuerdoDetalle.(class)=org.springframework.web.servlet.view.JstlView
escritoDesacuerdoDetalle.url=/WEB-INF/views/wizard/desacuerdo/consulta/escritoDesacuerdoDetalle.jsp

errorConexionBase.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorConexionBase.url=errorConexion