
package gob.imss.webservice.renapo.curp.cliente;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "wsimsscurp", targetNamespace = "http://www.openuri.org/", wsdlLocation = "file:/C:/workplace/desarrollo/entidades/IMSS/NMCE/codigo-nb71/WebserviceClienteRenapoSat/WsdlRenapoCurp.xml")
public class Wsimsscurp
    extends Service
{

    private final static URL WSIMSSCURP_WSDL_LOCATION;
    private final static WebServiceException WSIMSSCURP_EXCEPTION;
    private final static QName WSIMSSCURP_QNAME = new QName("http://www.openuri.org/", "wsimsscurp");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/workplace/desarrollo/entidades/IMSS/NMCE/codigo-nb71/WebserviceClienteRenapoSat/WsdlRenapoCurp.xml");
        	url = Thread.currentThread().getContextClassLoader().getResource("WsdlRenapoCurp.xml");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        WSIMSSCURP_WSDL_LOCATION = url;
        WSIMSSCURP_EXCEPTION = e;
    }

    public Wsimsscurp() {
        super(__getWsdlLocation(), WSIMSSCURP_QNAME);
    }

    public Wsimsscurp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WsimsscurpSoap
     */
    @WebEndpoint(name = "wsimsscurpSoap")
    public WsimsscurpSoap getWsimsscurpSoap() {
        return super.getPort(new QName("http://www.openuri.org/", "wsimsscurpSoap"), WsimsscurpSoap.class);
    }

    /**
     * 
     * @return
     *     returns WsimsscurpHttpGet
     */
    @WebEndpoint(name = "wsimsscurpHttpGet")
    public WsimsscurpHttpGet getWsimsscurpHttpGet() {
        return super.getPort(new QName("http://www.openuri.org/", "wsimsscurpHttpGet"), WsimsscurpHttpGet.class);
    }

    /**
     * 
     * @return
     *     returns WsimsscurpHttpPost
     */
    @WebEndpoint(name = "wsimsscurpHttpPost")
    public WsimsscurpHttpPost getWsimsscurpHttpPost() {
        return super.getPort(new QName("http://www.openuri.org/", "wsimsscurpHttpPost"), WsimsscurpHttpPost.class);
    }

    private static URL __getWsdlLocation() {
        if (WSIMSSCURP_EXCEPTION!= null) {
            throw WSIMSSCURP_EXCEPTION;
        }
        return WSIMSSCURP_WSDL_LOCATION;
    }

}
