//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.asegurado.Asegurado;
import mx.gob.imss.ctirss.delta.model.asegurado.AsignacionNSS;
import mx.gob.imss.ctirss.delta.model.derechohabiente.dto.BajaDerechohabienteDto;
import mx.gob.imss.ctirss.delta.model.domicilio.Domicilio;
import mx.gob.imss.ctirss.delta.model.gestion.tramite.TipoTramite;

@XmlRootElement(name = "ActualizaCorreo")
public class ActualizaCorreo  extends AbstractModel implements Serializable {


	private static final long serialVersionUID = 1L;
	
	public Integer idSolicitud;
	public Integer idTramite;
	public String folio;
	public String fechaRegistroAlta;
	public String nss;
	public String nombre;
	public String primerApellido;
	public String segundoApellido;
	public String curp;
	public Integer idUsuario;
	public Integer idSubdelegacion;
	public String idEstado;
	public String estadoTramite;
	
	public ActualizaCorreo(){
		
	}

	@Override
	public String toString() {
		return "ActualizaCorreo [idSolicitud=" + idSolicitud + ", idTramite=" + idTramite + ", folio=" + folio
				+ ", fechaRegistroAlta=" + fechaRegistroAlta + ", nss=" + nss + ", nombre=" + nombre
				+ ", primerApellido=" + primerApellido + ", segundoApellido=" + segundoApellido + ", curp=" + curp
				+ ", idUsuario=" + idUsuario + ", idSubdelegacion=" + idSubdelegacion + "]";
	}

	public Integer getIdSolicitud() {
		return idSolicitud;
	}

	public void setIdSolicitud(Integer idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	
	public String getFolio() {
		return folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public String getFechaRegistroAlta() {
		return fechaRegistroAlta;
	}

	public void setFechaRegistroAlta(String fechaRegistroAlta) {
		this.fechaRegistroAlta = fechaRegistroAlta;
	}

	public String getNss() {
		return nss;
	}

	public void setNss(String nss) {
		this.nss = nss;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPrimerApellido() {
		return primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public String getSegundoApellido() {
		return segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public String getCurp() {
		return curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	public Integer getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getIdSubdelegacion() {
		return idSubdelegacion;
	}

	public void setIdSubdelegacion(Integer idSubdelegacion) {
		this.idSubdelegacion = idSubdelegacion;
	}

	public Integer getIdTramite() {
		return idTramite;
	}

	public void setIdTramite(Integer idTramite) {
		this.idTramite = idTramite;
	}

	public String getIdEstado() {
		return idEstado;
	}

	public void setIdEstado(String idEstado) {
		this.idEstado = idEstado;
	}

	public String getEstadoTramite() {
		return estadoTramite;
	}

	public void setEstadoTramite(String estadoTramite) {
		this.estadoTramite = estadoTramite;
	}


}