//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class Turno extends AbstractModel implements Serializable {

    private static final long serialVersionUID = -7996262209427113508L;
    protected Long idTurno;
    protected String descripcion;
    protected String horaInicioTurno;
    protected String horaFinTurno;

    public Turno() {
    	
    }
    
    public Turno(Long idTurno) {
    	this.idTurno = idTurno;
    }
    
    public Turno(String descripcion) {
    	this.descripcion = descripcion;
    }
    
    public Turno(Long idTurno, String descripcion) {
    	this.idTurno = idTurno;
    	this.descripcion = descripcion;
    }
    
    public Long getIdTurno() {
        return idTurno;
    }

    public void setIdTurno(final Long idTurno) {
        this.idTurno = idTurno;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(final String descripcion) {
        this.descripcion = descripcion;
    }

    public String getHoraInicioTurno() {
        return horaInicioTurno;
    }

    public void setHoraInicioTurno(final String horaInicioTurno) {
        this.horaInicioTurno = horaInicioTurno;
    }

    public String getHoraFinTurno() {
        return horaFinTurno;
    }

    public void setHoraFinTurno(final String horaFinTurno) {
        this.horaFinTurno = horaFinTurno;
    }

}
