service.provider.url=t3://vzapma07.imss.gob.mx:8001,vzapma07.imss.gob.mx:8003,vzapma12.imss.gob.mx:8001,vzapma12.imss.gob.mx:8003,vzapmb09.imss.gob.mx:8001,vzapmb09.imss.gob.mx:8003
service.security.principal=wloperator
service.security.credentials=53rv4p%wl%1p1r1t1r$.
#service.provider.url=t3://localhost:7001
#service.security.principal=weblogic
#service.security.credentials=w3blogic
