
package mx.gob.imss.cit.ClienteWebServiceBoveda;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.BindingProvider;

import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.core.io.Resource;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IESServicio", targetNamespace = "http://www.openuri.org/", wsdlLocation = "classpath:boveda.wsdl")
public class IESServicio
    extends Service
{

    private final static URL IESSERVICIO_WSDL_LOCATION;
    private final static WebServiceException IESSERVICIO_EXCEPTION;
    private final static QName IESSERVICIO_QNAME = new QName("http://www.openuri.org/", "IESServicio");
    private static DefaultResourceLoader loader= new DefaultResourceLoader(); 
    private static Resource resource = loader.getResource("classpath:boveda.wsdl"); 
    private final static int serviceTimeOut = 30000;
    private final static int connectTimeOut = 10000;

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = resource.getURL();
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (IOException e1) {
        	e = new WebServiceException(e1);
        }
        IESSERVICIO_WSDL_LOCATION = url;
        IESSERVICIO_EXCEPTION = e;
    }

    public IESServicio() {
        super(__getWsdlLocation(), IESSERVICIO_QNAME);
    }

    public IESServicio(WebServiceFeature... features) {
        super(__getWsdlLocation(), IESSERVICIO_QNAME, features);
    }

    public IESServicio(URL wsdlLocation) {
        super(wsdlLocation, IESSERVICIO_QNAME);
    }

    public IESServicio(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IESSERVICIO_QNAME, features);
    }

    public IESServicio(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IESServicio(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IESServicioSoap
     */
    @WebEndpoint(name = "IESServicioSoap")
    public IESServicioSoap getIESServicioSoap() {
    	IESServicioSoap ws = super.getPort(new QName("http://www.openuri.org/", "IESServicioSoap"), IESServicioSoap.class);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
        return ws;
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IESServicioSoap
     */
    @WebEndpoint(name = "IESServicioSoap")
    public IESServicioSoap getIESServicioSoap(WebServiceFeature... features) {
    	IESServicioSoap ws = super.getPort(new QName("http://www.openuri.org/", "IESServicioSoap"), IESServicioSoap.class, features);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
        return ws;
    }

    private static URL __getWsdlLocation() {
        if (IESSERVICIO_EXCEPTION!= null) {
            throw IESSERVICIO_EXCEPTION;
        }
        return IESSERVICIO_WSDL_LOCATION;
    }

}
