#welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
#welcome.url=welcome
 
#login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
#login.url=login

#home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
#home.url=home

#########################################################################
###### Vistas del manejo de errores generales ###########################
error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

#########################################################################

#Pagina principal RISS
iniciarRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
iniciarRiss.url=iniciarRiss
#Pagina con resultado de RPs asociados al RFC
confirmarDatosRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmarDatosRiss.url=confirmarDatosRiss
#Pagina del asegurado notificando que cuenta con RPs asociados (Posible 35)
confirmarDatosAdicionalesRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmarDatosAdicionalesRiss.url=confirmarDatosAdicionalesRiss
#Pagina de errores RISS
resultadoValidacionRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
resultadoValidacionRiss.url=resultadoValidacionRiss
#Pagina para concluir solicitud RISS
concluirRiss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
concluirRiss.url=concluirRiss


