#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
 
 
nacional.detalle.(class)=org.springframework.web.servlet.view.JstlView
nacional.detalle.url=/WEB-INF/views/domicilio/detalle/nacional.jsp
 
 
#Tiles redirect

portal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
portal.url=portal

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError


#Consulta por datos basicos
consultapor.datosbasicos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultapor.datosbasicos.url=consultaDatosBasicos

#Persona ya registrada
persona.yaRegistrada.(class)=org.springframework.web.servlet.view.tiles2.TilesView
persona.yaRegistrada.url=personaYaRegistrada


#Pantalla de la captura de los datos basicos cuando se encuentra en las entidades externas
captura.limitada.(class)=org.springframework.web.servlet.view.tiles2.TilesView
captura.limitada.url=capturaDatosBasicosLimitada


#Pantalla de la captura de los datos basicos libre
captura.libre.(class)=org.springframework.web.servlet.view.tiles2.TilesView
captura.libre.url=capturaDatosBasicosLibre

#Pantalla de la captura de los complementos (paso 3 de origen en ventanilla)
captura.complementos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
captura.complementos.url=capturaComplementos

#Pantalla de la captura de los complementos + serie (paso 3 alterno para solicitudes pendientes de origen internet)
captura.complementosConSerie.(class)=org.springframework.web.servlet.view.tiles2.TilesView
captura.complementosConSerie.url=capturaComplementosConSerie


#captura

tramite.inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.inicio.url=tramiteinicio

tramite.capturar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.capturar.url=tramitecapturar

#concluir la solicitud
concluir.solicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
concluir.solicitud.url=concluirSolicitud

#confirmacion de solicitud pendiente cancelada
confirmacion.solicitudCancelada.(class) = org.springframework.web.servlet.view.tiles2.TilesView
confirmacion.solicitudCancelada.url = confirmacionCancelacionSolicitudPendiente

#concluir la solicitud para usuarios externos
concluir.solicitudExterno.(class)=org.springframework.web.servlet.view.tiles2.TilesView
concluir.solicitudExterno.url=concluirSolicitudExterno

# reporte comprobante de tramite alta asegurado interno o ventanilla
comprobante.interno.solicitud.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
comprobante.interno.solicitud.url=/WEB-INF/views/tramite/reporte/ReporteComprobanteInternoAsignacion.jasper

# reporte comprobante de tramite alta asegurado externo o internet
comprobante.externo.solicitud.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
comprobante.externo.solicitud.url=/WEB-INF/views/tramite/reporte/ReporteComprobanteExternoAsignacion.jasper

#WIZARD NSS
wizardAsignacionNSSInitTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardAsignacionNSSInitTest.url=wizardAsignacionNSSInitTest
wizardAsignacionNSSInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardAsignacionNSSInit.url=wizardAsignacionNSSInit
wizardAsignacionNSSContenido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardAsignacionNSSContenido.url=wizardAsignacionNSSContenido
wizardAsignacionNSSConfirmacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardAsignacionNSSConfirmacion.url=wizardAsignacionNSSConfirmacion
wizardAsignacionNSSFin.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardAsignacionNSSFin.url=wizardAsignacionNSSFin

#URLS para el modulo de consulta de vigencia.
consultaVigencia.home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaVigencia.home.url=homeVigencia
consultaVigencia.datosbasicos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaVigencia.datosbasicos.url=consultaVigencia
consultaVigencia.salida.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaVigencia.salida.url=salidaVigencia

loginVigencia.(class)=org.springframework.web.servlet.view.tiles2.TilesView
loginVigencia.url=loginVigencia

vigenciaFinaliza.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vigenciaFinaliza.url=vigenciaFinaliza

actCorreo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actCorreo.url=actCorreo

capturaDocs.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturaDocs.url=capturaDocs

#URLS para el modulo de consulta de cartilla.
consultaCartilla.home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaCartilla.home.url=homeCartilla
consultaCartilla.datosbasicos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaCartilla.datosbasicos.url=consultaCartilla
consultaCartilla.salida.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaCartilla.salida.url=salidaCartilla

loginCartilla.(class)=org.springframework.web.servlet.view.tiles2.TilesView
loginCartilla.url=loginCartilla

cartillaFinaliza.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaFinaliza.url=cartillaFinaliza

cartillaFinalizaNSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaFinalizaNSS.url=cartillaFinalizaNSS

initConsultaPersona.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initConsultaPersona.url=initConsultaPersona

initConsultaNss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initConsultaNss.url = initConsultaNss

mostrarTarjetaNSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mostrarTarjetaNSS.url = mostrarTarjetaNSS

loginAsignacionNSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
loginAsignacionNSS.url=loginAsignacionNSS

capturaDomicilioNSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturaDomicilioNSS.url=capturaDomicilioNSS

asignacionFinalizada.(class)=org.springframework.web.servlet.view.tiles2.TilesView
asignacionFinalizada.url=asignacionFinalizada