#reemplazar con los datos de su consola
service.provider.url=t3://localhost:7001
service.security.principal=weblogic
service.security.credentials=weblogic1


#Datos del ambiente de desarrollo stage
#service.provider.url=t3://172.24.116.37:11052,172.24.116.37:11054
#service.security.principal=admin_wlmovpat
#service.security.credentials=wlmovpat_admin
