sso_umf=578
sso_curp=BAMI711215MDGXRL02
sso_user=BAMI711215MDGXRL02
sso_perfiles=TRAMITADOR
sso_delegacion=10
sso_subdelegacion=32
sso_id_persona=1
sso_list_sistemas=FOLIOS PAC,GESTION PERSONAS,GESTION ASIGNACION NSS,VISOR DE SOLICITUDES,SEMANAS COTIZADAS (SISEC),CORRECCION DATOS ASEGURADO,RIESGOS TRABAJO,GESTION CLASIFICACION EMPRESAS,DERECHOHABIENTES,GESTION PATRONAL,PMC CASUISTICA