package mx.gob.imss.ctirss.delta.model.enums;

/**
 * Enum que representa la tabla DIC_DOCUMENTO
 * 
 * @author Marco
 *
 */
public enum DocumentosEnum {
	CURP(34L, "CURP"),
	ACTA_NACIMIENTO(1L, "ACTA DE NACIMIENTO"),
	ACTA_MATRIMONIO(2L,"ACTA DE MATRIMONIO"),
	ACTA_RECONOCIMIENTO(3L, "ACTA DE RECONOCIMIENTO"),
	ACTA_ADOPCION(4L, "ACTA DE ADOPCI\u00d3N"),
	ESTADO_DE_CUENTA_BANCARIO(7L, "ESTADO DE CUENTA BANCARIO"),
	RECIBO_DE_TELEVISION(9L, "RECIBO DE TELEVISIÓN"),
	PAGO_DE_TENENCIA_VEHICULAR(10L, "PAGO DE TENENCIA VEHICULAR"), 
	RECIBO_DE_GAS(11L, "RECIBO DE GAS"),
	RECIBO_DE_LUZ(12L, "RECIBO DE LUZ"),
	RECIBO_DE_TELEFONO(13L, "RECIBO DE TELÉFONO"),
	ESCRITURA_DE_PROPIEDAD_INMOBILIARIA(14L, "ESCRITURA DE PROPIEDAD INMOBILIARIA"),
	RECIBO_DE_AGUA(15L, "RECIBO DE AGUA"),
	PAGO_DE_PREDIAL(16L, "PAGO DE PREDIAL"),
	TIP(44L, "TIP"),
	ARP(45L, "ARP"),
	DOCUMENTO_MIGRATORIO(28L, "DOCUMENTO MIGRATORIO"),
	CARTA_NATURALIZACION(27L, "CARTA DE NATURALIZACI\u00d3N"),
	NUMERO_UNICO_DE_EXTRANJERO(47L, "N\u00daMERO \u00daNICO EXTRANJERO"),
	CERTIFICADO_DE_NACIONALIDAD_MEXICANA(48L, "CERTIFICADO DE NACIONALIDAD MEXICANA"),
	OFICIO_SOLICITANTE_DE_REFUGIADO(49L, "OFICIO SOLICITANTE DE REFUGIADO"),
	FORMA_MIGRATORIA_TURISTA(50L, "FORMA MIGRATORIA TURISTA"),
	ACTA_PACTO_CIVIL(65L,"ACTA DE PACTO CIVIL DE SOLIDARIDAD");
		

	DocumentosEnum(Long id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	private Long id;
	private String descripcion;
	
	public Long getId() {
		return this.id;
	}
	
	public String getDescripcion(){
		return this.descripcion;
	}
}
