//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 07:16:49 PM CDT 
//


package mx.gob.imss.ctirss.delta.model.gestion.individuo;

import java.util.Date;
import java.util.List;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.domicilio.DomicilioFiscal;
import mx.gob.imss.ctirss.delta.model.gestion.medio.contacto.TipoMedioContacto;

public class Sat extends AbstractModel {

    private final static long serialVersionUID = 1234321L;
    protected String primerApellido;
    protected String segundoApellido;
    protected String curp;
    protected String nit;
    protected Long idNacionalidad;
    protected String desNacionalidad;
    protected String nombreComercial;
    protected String nombre;
    protected Long idPaisOrigen;
    protected String desPaisOrigen;
    protected String razonSocial;
    protected String cSitCont;
    protected String cSitContDom;
    protected String cSitDom;
    protected String cDetSitCont;
    protected String dSitCont;
    protected String dSitContDom;
    protected String dSitDom;
    protected Date fechaConstitucion;
    protected Date fechaInicioOperaciones;
    protected Date fechaNacimiento;
    protected Date fechaSitCont;
    protected Integer idTipoSociedad;
    protected String desTipoSociedad;
    protected String rfc;
    
    /**
     * Ubicacion - Domicilio que se recupera de la informacion
     * de la respuesta del SAT.
     */
    protected DomicilioFiscal ubicacion;
    protected String telefono1;
    protected String telefono2;
    protected TipoMedioContacto tipoTelefono1;
    protected TipoMedioContacto tipoTelefono2;
    protected String email;

    protected String rfcOriginal;
    protected String rfcSolicitado;
    protected String rfcVigente; 
    protected List<Regimen> regimenes;
    protected boolean rif;
    
    public boolean isRif() {
		return rif;
	}

	public void setRif(boolean rif) {
		this.rif = rif;
	}

	/**
     * Gets the value of the primerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerApellido() {
        return primerApellido;
    }

    /**
     * Sets the value of the primerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerApellido(String value) {
        this.primerApellido = value;
    }

    /**
     * Gets the value of the segundoApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegundoApellido() {
        return segundoApellido;
    }

    /**
     * Sets the value of the segundoApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegundoApellido(String value) {
        this.segundoApellido = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurp() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurp(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the nit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNit() {
        return nit;
    }

    /**
     * Sets the value of the nit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNit(String value) {
        this.nit = value;
    }

    /**
     * Gets the value of the idNacionalidad property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdNacionalidad() {
        return idNacionalidad;
    }

    /**
     * Sets the value of the idNacionalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdNacionalidad(Long value) {
        this.idNacionalidad = value;
    }

    /**
     * Gets the value of the desNacionalidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesNacionalidad() {
        return desNacionalidad;
    }

    /**
     * Sets the value of the desNacionalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesNacionalidad(String value) {
        this.desNacionalidad = value;
    }

    /**
     * Gets the value of the nombreComercial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreComercial() {
        return nombreComercial;
    }

    /**
     * Sets the value of the nombreComercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreComercial(String value) {
        this.nombreComercial = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the idPaisOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdPaisOrigen() {
        return idPaisOrigen;
    }

    /**
     * Sets the value of the idPaisOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdPaisOrigen(Long value) {
        this.idPaisOrigen = value;
    }

    /**
     * Gets the value of the desPaisOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesPaisOrigen() {
        return desPaisOrigen;
    }

    /**
     * Sets the value of the desPaisOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesPaisOrigen(String value) {
        this.desPaisOrigen = value;
    }

    /**
     * Gets the value of the razonSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazonSocial() {
        return razonSocial;
    }

    /**
     * Sets the value of the razonSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazonSocial(String value) {
        this.razonSocial = value;
    }

    /**
     * Gets the value of the cSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSitCont() {
        return cSitCont;
    }

    /**
     * Sets the value of the cSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSitCont(String value) {
        this.cSitCont = value;
    }

    /**
     * Gets the value of the cSitContDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSitContDom() {
        return cSitContDom;
    }

    /**
     * Sets the value of the cSitContDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSitContDom(String value) {
        this.cSitContDom = value;
    }

    /**
     * Gets the value of the cSitDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSitDom() {
        return cSitDom;
    }

    /**
     * Sets the value of the cSitDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSitDom(String value) {
        this.cSitDom = value;
    }

    /**
     * Gets the value of the cDetSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDetSitCont() {
        return cDetSitCont;
    }

    /**
     * Sets the value of the cDetSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDetSitCont(String value) {
        this.cDetSitCont = value;
    }

    /**
     * Gets the value of the dSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSitCont() {
        return dSitCont;
    }

    /**
     * Sets the value of the dSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSitCont(String value) {
        this.dSitCont = value;
    }

    /**
     * Gets the value of the dSitContDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSitContDom() {
        return dSitContDom;
    }

    /**
     * Sets the value of the dSitContDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSitContDom(String value) {
        this.dSitContDom = value;
    }

    /**
     * Gets the value of the dSitDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSitDom() {
        return dSitDom;
    }

    /**
     * Sets the value of the dSitDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSitDom(String value) {
        this.dSitDom = value;
    }

    /**
     * Gets the value of the fechaConstitucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaConstitucion() {
        return fechaConstitucion;
    }

    /**
     * Sets the value of the fechaConstitucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaConstitucion(Date value) {
        this.fechaConstitucion = value;
    }

    /**
     * Gets the value of the fechaInicioOperaciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaInicioOperaciones() {
        return fechaInicioOperaciones;
    }

    /**
     * Sets the value of the fechaInicioOperaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInicioOperaciones(Date value) {
        this.fechaInicioOperaciones = value;
    }

    /**
     * Gets the value of the fechaNacimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * Sets the value of the fechaNacimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaNacimiento(Date value) {
        this.fechaNacimiento = value;
    }

    /**
     * Gets the value of the fechaSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaSitCont() {
        return fechaSitCont;
    }

    /**
     * Sets the value of the fechaSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaSitCont(Date value) {
        this.fechaSitCont = value;
    }

    /**
     * Gets the value of the idTipoSociedad property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdTipoSociedad() {
        return idTipoSociedad;
    }

    /**
     * Sets the value of the idTipoSociedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdTipoSociedad(Integer value) {
        this.idTipoSociedad = value;
    }

    /**
     * Gets the value of the desTipoSociedad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesTipoSociedad() {
        return desTipoSociedad;
    }

    /**
     * Sets the value of the desTipoSociedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesTipoSociedad(String value) {
        this.desTipoSociedad = value;
    }

    /**
     * Gets the value of the rfc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfc() {
        return rfc;
    }

    /**
     * Sets the value of the rfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfc(String value) {
        this.rfc = value;
    }

    public Object createNewInstance() {
        return new Sat();
    }

	/**
	 * @return the ubicacion
	 */
	public DomicilioFiscal getUbicacion() {
		return ubicacion;
	}

	/**
	 * @param ubicacion the ubicacion to set
	 */
	public void setUbicacion(DomicilioFiscal ubicacion) {
		this.ubicacion = ubicacion;
	}

	/**
	 * @return the telefono1
	 */
	public String getTelefono1() {
		return telefono1;
	}

	/**
	 * @param telefono1 the telefono1 to set
	 */
	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	/**
	 * @return the telefono2
	 */
	public String getTelefono2() {
		return telefono2;
	}

	/**
	 * @param telefono2 the telefono2 to set
	 */
	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	/**
	 * @return the tipoTelefono1
	 */
	public TipoMedioContacto getTipoTelefono1() {
		return tipoTelefono1;
	}

	/**
	 * @param tipoTelefono1 the tipoTelefono1 to set
	 */
	public void setTipoTelefono1(TipoMedioContacto tipoTelefono1) {
		this.tipoTelefono1 = tipoTelefono1;
	}

	/**
	 * @return the tipoTelefono2
	 */
	public TipoMedioContacto getTipoTelefono2() {
		return tipoTelefono2;
	}

	/**
	 * @param tipoTelefono2 the tipoTelefono2 to set
	 */
	public void setTipoTelefono2(TipoMedioContacto tipoTelefono2) {
		this.tipoTelefono2 = tipoTelefono2;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the rfcOriginal
	 */
	public String getRfcOriginal() {
		return rfcOriginal;
	}

	/**
	 * @param rfcOriginal the rfcOriginal to set
	 */
	public void setRfcOriginal(String rfcOriginal) {
		this.rfcOriginal = rfcOriginal;
	}

	/**
	 * @return the rfcSolicitado
	 */
	public String getRfcSolicitado() {
		return rfcSolicitado;
	}

	/**
	 * @param rfcSolicitado the rfcSolicitado to set
	 */
	public void setRfcSolicitado(String rfcSolicitado) {
		this.rfcSolicitado = rfcSolicitado;
	}

	/**
	 * @return the rfcVigente
	 */
	public String getRfcVigente() {
		return rfcVigente;
	}

	/**
	 * @param rfcVigente the rfcVigente to set
	 */
	public void setRfcVigente(String rfcVigente) {
		this.rfcVigente = rfcVigente;
	}

	public List<Regimen> getRegimenes() {
		return regimenes;
	}

	public void setRegimenes(List<Regimen> regimenes) {
		this.regimenes = regimenes;
	}
	
}
