package mx.gob.imss.ctirss.clasificador.model.business;

// Generated 08-ago-2011 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApcGrupoId generated by hbm2java
 */
@Embeddable 
public class GrupoId implements java.io.Serializable {

	private int cveGrupo;
	private int cveDivision;

	public GrupoId() {
	}

	public GrupoId(int cveGrupo, int cveDivision) {
		this.cveGrupo = cveGrupo;
		this.cveDivision = cveDivision;
	}

	@Column(name = "CVE_GRUPO", nullable = false)
	public int getCveGrupo() {
		return this.cveGrupo;
	}

	public void setCveGrupo(int cveGrupo) {
		this.cveGrupo = cveGrupo;
	}

	@Column(name = "CVE_DIVISION", nullable = false)
	public int getCveDivision() {
		return this.cveDivision;
	}

	public void setCveDivision(int cveDivision) {
		this.cveDivision = cveDivision;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrupoId))
			return false;
		GrupoId castOther = (GrupoId) other;

		return (this.getCveGrupo() == castOther.getCveGrupo())
				&& (this.getCveDivision() == castOther.getCveDivision());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCveGrupo();
		result = 37 * result + this.getCveDivision();
		return result;
	}

}
