#Datos para la conexion al FTP
host.ftp.desarrollo=11.254.13.208
host.ftp.qa=11.254.13.208
host.ftp.produccion=vzapma04.imss.gob.mx
host.ftp.stage=172.16.5.173


user.desarrollo=sisconet
user.qa=sisconetqa
user.produccion=sisconet_Produccion
user.stage=sisconet_Stage

password.desarrollo=S1sc0n3t
password.qa=S1sc0n3tQ4
password.produccion=S1sc0n3t
password.stage=S1sc0n3t



# Host de despliegue 
host.desarrollo=172.24.116.54
host.qa=11.254.14.71
host.produccion=172.16.5.7
host.produccionN2=172.16.5.6
host.stage=172.16.5.171
host.stageN2=172.16.5.172