<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>mx.gob.imss.ctirss.delta.gestion.individuo</groupId>
	<artifactId>gestionIndividuo</artifactId>
	<version>2.4</version>
	<packaging>pom</packaging>

	<name>Modulo Delta de Gestion de Personas IMSS</name>
	<url>http://maven.apache.org</url>

	<properties>
		<skipTests>true</skipTests>
		<dep>none</dep>
		<project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
		<org.hibernate.version>3.6.9.Final</org.hibernate.version>
		<org.slf4j.version>1.6.1</org.slf4j.version>
		<org.log4j.version>1.2.16</org.log4j.version>
		<org.springframework.version>3.0.5.RELEASE</org.springframework.version>
		<tiles.framework.version>2.2.1</tiles.framework.version>
		<junit.version>4.8.2</junit.version>

		<!-- DEPENDENCIAS DE OTROS PROYECTOS IMSS -->
		<delta.framework.version>2.6</delta.framework.version>
		<delta.framework.comboSelect>2.0</delta.framework.comboSelect>
		<gestion.solicitud.version>2.2</gestion.solicitud.version>
		<delta.domicilios>2.4</delta.domicilios>
		<delta.medioscontacto>2.3</delta.medioscontacto>
		<delta.documentos.probatorios>2.4</delta.documentos.probatorios>
		<delta.clientews>2.2</delta.clientews>
		<delta.clientews.renapo>2.3</delta.clientews.renapo>
		<delta.clientews.usuario>2.3</delta.clientews.usuario>
		<delta.patronal>2.4</delta.patronal>
		<delta.personas>2.4</delta.personas>
		<delta.clasificacion.empr>2.4</delta.clasificacion.empr>
		<delta.derechohabientes>2.2</delta.derechohabientes>
		<clientes.buzon.tributario>${mvn.version.cliente}</clientes.buzon.tributario>
	</properties>

	<build>
		<plugins>

			<plugin>
				<groupId>org.zeroturnaround</groupId>
				<artifactId>jrebel-maven-plugin</artifactId>
				<version>1.1.1</version>
				<executions>
					<execution>
						<id>generate-rebel-xml</id>
						<phase>process-resources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>



			<!-- Release Plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<tagBase>http://11.254.16.21/svn/gestion_individuos/codigo/tags/</tagBase>

				</configuration>
			</plugin>

			<!--Weblogic Deployment Plugin
			<plugin>
				<groupId>com.oracle.weblogic</groupId>
				<artifactId>weblogic-maven-plugin</artifactId>
				<version>10.3.4</version>
				<configuration>
					<adminurl>t3://localhost:7001</adminurl>
					<user>weblogic</user>
					<password>weblogic1</password>
					<upload>true</upload>
					<action>deploy</action>
					<remote>false</remote>
					<verbose>true</verbose>
					<source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
					<name>${project.build.finalName}</name>
				</configuration>
				<executions>
					<execution>
						<phase>install</phase>
						<goals>
							<goal>deploy</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			-->

		</plugins>

		<!--Extension necesaria para el deploy (instalacion) de los componentes 
			en el repositorio central -->
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ftp</artifactId>
			</extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav</artifactId>
			</extension>
		</extensions>
	</build>

	<repositories>
		<repository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<layout>default</layout>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>ctirss</id>
			<name>CTIRSS repository</name>
			<url>http://172.16.5.134:8080/repository/repo/</url>
			<layout>default</layout>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<updatePolicy>never</updatePolicy>
			</releases>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<!-- use the following if you're not using a snapshot version. -->
		<repository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://172.16.5.134:8080/repository/repo/</url>
		</repository>
		<snapshotRepository>
			<id>ctirss-archiva</id>
			<name>CTIRSS Repository Name</name>
			<url>dav:http://172.16.5.134:8080/repository/repo/</url>
		</snapshotRepository>
	</distributionManagement>


	<scm>
		<connection>scm:svn:http://11.254.16.21/svn/gestion_individuos/codigo/trunk/gestionIndividuo</connection>
		<developerConnection>scm:svn:http://11.254.16.21/svn/gestion_individuos/codigo/trunk/gestionIndividuo</developerConnection>
		<url>http://11.254.16.21/svn/gestion_individuos/codigo/trunk/gestionIndividuo</url>
	</scm>


	<profiles>
		

		<!--Perfil para el despliegue en DESARROLLO de la capa de la vista -->
		<profile>
			<id>dev-deploy-view</id>
			<activation>
				<property>
					<name>dev-deploy</name>
					<value>view</value>
				</property>
			</activation>
			<modules>
				<module>gestionIndividuo-packing-web</module>
			</modules>
		</profile>

		<!--Perfil para el despliegue en DESARROLLO de la capa de los servicios -->
		<profile>
			<id>dev-deploy-services</id>
			<activation>
				<property>
					<name>dev-deploy</name>
					<value>services</value>
				</property>
			</activation>
			<modules>
				<module>gestionIndividuo-packing</module>
			</modules>
		</profile>

		<!--Perfil para el despliegue en DESARROLLO de las capas de servicio y 
			vista -->
		<profile>
			<id>dev-deploy-all</id>
			<activation>
				<property>
					<name>dev-deploy-all</name>
				</property>
			</activation>
			<modules>
				<module>gestionIndividuo-packing</module>
				<module>gestionIndividuo-packing-web</module>
			</modules>
		</profile>
		
		
		<!--Perfil para el BORRADO en DESARROLLO de los despliegues -->
		<profile>
			<id>dev-deploy-remove</id>
			<activation>
				<property>
					<name>dev-remove-all</name>
					
				</property>
			</activation>
			<modules>
				<module>gestionIndividuo-packing</module>
				<module>gestionIndividuo-packing-web</module>
			</modules>
			<properties>
				<mvn.version.cliente>2.2-SNAPSHOT</mvn.version.cliente>
			</properties>
		</profile>
		
		<profile>
			<id>compile-stage</id>
			<activation>
			<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<mvn.version.cliente>2.2-SNAPSHOT</mvn.version.cliente>
			</properties>
		</profile>
		
		<profile>
			<id>compile-prod</id>
			<properties>
				<mvn.version.cliente>2.2</mvn.version.cliente>
			</properties>
		</profile>
	</profiles>
	
	<modules>
		<module>gestionIndividuo-service-business-interface</module>
		<module>gestionIndividuo-service-business-ejb</module>
		<module>gestionIndividuo-web</module>
		<module>gestionIndividuo-consulta-web</module>
		<module>correcciondatosaseguradoF2</module>
		<module>gestionIndividuo-packing</module>
		<!--<module>gestionIndividuo-packing-web</module>-->		
	</modules>
	
</project>
