<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>mx.gob.imss.ctirss.delta.gestion.asegurado</groupId>
	<artifactId>gestionAsegurados-servicios-negocio-ejb</artifactId>
	<version>2.2-SNAPSHOT</version>

	<name>Modulo de Servicios de Negocio (ejb)</name>
	<url>http://maven.apache.org</url>
	<packaging>ejb</packaging>

	<parent>
		<artifactId>gestionAsegurados</artifactId>
		<groupId>mx.gob.imss.ctirss.delta.gestion.asegurado</groupId>
		<version>2.2-SNAPSHOT</version>
	</parent>

	<dependencies>
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.asegurado</groupId>
			<artifactId>gestionAsegurados-interfaces-negocio</artifactId>
			<version>${delta.asegurados}</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.individuo.service.interface</groupId>
			<artifactId>gestionIndividuo-service-business-interface</artifactId>
			<version>${delta.personas}</version>
		</dependency>

		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.derechohabientes</groupId>
			<artifactId>gestionDerechohabientes-interfaces-negocio</artifactId>
			<version>${delta.dhabiente}</version>
		</dependency>
 
		<!-- Dependencia del Proyecto de Objetos de modelo DELTA IMSS -->
		
	    <dependency>
	      <groupId>mx.gob.imss.ctirss.delta</groupId>
	      <artifactId>imssdigital-modelo</artifactId>
	      <version>${delta.framework.version}</version>
	      <type>jar</type>
	    </dependency>
			
		
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
		</dependency>

		<!-- Dependencia del Proyecto de Objetos de Persistencia DELTA IMSS -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-persistencia</artifactId>
			<version>${delta.framework.version}</version>
		</dependency>

		<!-- Dependencia del Proyecto Base DELTA - Framework Base -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-framework-base</artifactId>
			<version>${delta.framework.version}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.solicitud</groupId>
			<artifactId>gestionSolicitud-interfaces-negocio</artifactId>
			<version>${gestion.solicitud.version}</version>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.individuo.service.interface</groupId>
			<artifactId>gestionIndividuo-service-business-interface</artifactId>
			<version>${delta.personas}</version>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.patronal</groupId>
			<artifactId>delta-gestionPatronal-interfaces-negocio</artifactId>
			<version>${gestion.patronal.version}</version>
		</dependency>
		
		<!-- Dependencia con otros proyectos. Gestion Domicilios -->
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.domicilio</groupId>
			<artifactId>gestionDomicilios-interfaces-negocio</artifactId>
			<version>${delta.domicilios}</version>
	    </dependency> 
		
		
		<!--  dependencia para los servicios de asegurados de paso y cambio al -->
		 <dependency>
		 <groupId>mx.gob.imss.ctirss.ws.asignacion</groupId>
		 <artifactId>ClienteWebServices-asignacion-nss</artifactId>
  			<version>2.0-SNAPSHOT</version>
		</dependency>
		
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.documento.probatorio</groupId>
			<artifactId>gestionDocumentoProbatorio-interfaces-negocio</artifactId>
			<version>${delta.documentos.probatorios}</version>
	    </dependency> 
		
		
		<!--
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.individuo.service.ejb</groupId>
			<artifactId>gestionIndividuo-service-business-ejb</artifactId>
			<version>${delta.personas}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.patronal</groupId>
			<artifactId>delta-gestionPatronal-interfaces-negocio</artifactId>
			<version>${gestion.patronal.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>mx.gob.imss.ctirss.delta.gestion.patronal</groupId>
			<artifactId>delta-gestionPatronal-servicios-negocio-ejb</artifactId>
			<version>${gestion.patronal.version}</version>
			<scope>test</scope>
		</dependency>
		-->

		<!-- HIBERNATE CORE -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${org.hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate.javax.persistence</groupId>
			<artifactId>hibernate-jpa-2.0-api</artifactId>
			<version>1.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-commons-annotations</artifactId>
			<version>3.2.0.Final</version>
		</dependency>

		<!-- HIBERNATE DEPENDECIES -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${org.log4j.version}</version>
		</dependency>

		<!-- EJB -->
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb-api</artifactId>
			<version>3.0</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>4.0.1</version>
			
			<exclusions>
				<exclusion>
					<groupId>antlr</groupId>
					<artifactId>antlri</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-beanutils</groupId>
					<artifactId>commons-beanutils</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-javaflow</groupId>
					<artifactId>commons-javaflow</artifactId>
				</exclusion>
				<exclusion>
					<groupId>eclipse</groupId>
					<artifactId>jdtcore</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.persistence</groupId>
					<artifactId>persistence-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.xml.soap</groupId>
					<artifactId>saaj-api</artifactId>
				</exclusion>

				<exclusion>
					<groupId>jaxen</groupId>
					<artifactId>jaxen</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jfree</groupId>
					<artifactId>jcommon</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jfree</groupId>
					<artifactId>jfreechart</artifactId>
				</exclusion>
				<exclusion>
					<groupId>mondrian</groupId>
					<artifactId>mondrian</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.sf.barcode4j</groupId>
					<artifactId>barcode4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.sourceforge.barbecue</groupId>
					<artifactId>barbecue</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.sourceforge.jexcelapi</groupId>
					<artifactId>jxl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.ant</groupId>
					<artifactId>velocity</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.poi</groupId>
					<artifactId>poi</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.poi</groupId>
					<artifactId>poi-ooxml</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.velocity</groupId>
					<artifactId>velocity</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-awt-util</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-bridge</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-css</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-dom</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-gvt</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-script</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-svg-dom</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-svggen</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.xmlgraphics</groupId>
					<artifactId>batik-util</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.beanshell</groupId>
					<artifactId>bsh</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.codehaus.castor</groupId>
					<artifactId>castor</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.codehaus.groovy</groupId>
					<artifactId>groovy-all</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-beans</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>rhino</groupId>
					<artifactId>js</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-digester</groupId>
					<artifactId>commons-digester</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
				
			</exclusions>
		</dependency>
		
		
		<!-- Commons -->
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.3</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.2</version>
		</dependency>
		
		<!-- DEPENDENCIAS PARA EL DESARROLLO DE PRUEBAS -->
		<dependency>
			<groupId>weblogic</groupId>
			<artifactId>wlfullclient</artifactId>
			<version>10.3.4</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>oracle.jdbc</groupId>
			<artifactId>ojdbc</artifactId>
			<version>6</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.1.1</version>
			<scope>test</scope>
		</dependency>
		<!-- Inicio OpenEJB -->
		<dependency>
			<groupId>org.apache.openejb</groupId>
			<artifactId>openejb-core</artifactId>
			<version>4.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>3.6.9.Final</version>
			<scope>test</scope>
		</dependency>
		<!-- Fin del OpenEJB -->
		
		<!-- Joda Time -->
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>1.6.2</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
				<generateClient>true</generateClient>
				</configuration>
			</plugin>

			<!-- Ejecuta tareas de Ant -->
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<tasks>
								<echo message="building module..." />
								<delete dir="${project.build.outputDirectory}/interceptor" />
							</tasks>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Habilita los facets y natures para que el eclipse reconoza el proyecto 
				como de tipo de EJB. -->
			<plugin>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<additionalBuildcommands>
						<buildCommand>
							<name>org.eclipse.jdt.core.javabuilder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.common.project.facet.core.builder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.validation.validationbuilder</name>
						</buildCommand>
					</additionalBuildcommands>

					<additionalProjectnatures>
						<projectnature>org.eclipse.wst.common.project.facet.core.nature</projectnature>
						<projectnature>org.eclipse.jdt.core.javanature</projectnature>
						<projectnature>org.eclipse.wst.common.modulecore.ModuleCoreNature</projectnature>
						<projectnature>org.eclipse.jem.workbench.JavaEMFNature</projectnature>
					</additionalProjectnatures>

					<additionalConfig>
						<file>
							<name>.settings/org.eclipse.wst.common.project.facet.core.xml</name>
							<content>
							<![CDATA[
								<faceted-project>
									<runtime name="Weblogic Runtime" />
									<fixed facet="jst.ejb" />
									<fixed facet="jst.java" />
									<installed facet="jst.java" version="6.0" />
									<installed facet="jst.ejb" version="3.0" />
								</faceted-project>
							]]>
							</content>
						</file>

						<file>
							<name>.settings/org.eclipse.wst.common.component</name>
							<content>
							<![CDATA[
								<project-modules id="moduleCoreId" project-version="1.5.0">
									<wb-module deploy-name="${project.artifactId}">
										<wb-resource deploy-path="/" source-path="/src/main/java" />
										<wb-resource deploy-path="/" source-path="/src/main/resources" />
										<property name="java-output-path" value="target/classes" />
									</wb-module>
								</project-modules>
							]]>
							</content>
						</file>
					</additionalConfig>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>activate-interceptor</id>
			<activation>
				<property>
					<name>activate-interceptor</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>compile</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<tasks>
										<echo message="building interceptor..." />
										<delete includeemptydirs="true">
											<fileset dir="${project.build.outputDirectory}/META-INF/" includes="**/*" />
										</delete>
										<copy todir="${project.build.outputDirectory}/META-INF/">
											<fileset dir="src/main/resources/interceptor/"/>
										</copy>
										<delete dir="${project.build.outputDirectory}/interceptor" />
									</tasks>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
