//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.27 at 01:50:15 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente.negocio;
//General
import java.io.Serializable;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

public class PerfilUsuario extends AbstractModel  implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Long idPerfilUsuario;
	protected String descripcion;

	/**
	 * Gets the value of the idPerfilUsuario property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getIdPerfilUsuario() {
		return idPerfilUsuario;
	}

	/**
	 * Sets the value of the idPerfilUsuario property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setIdPerfilUsuario(Long value) {
		this.idPerfilUsuario = value;
	}

	/**
	 * Gets the value of the descripcion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * Sets the value of the descripcion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescripcion(String value) {
		this.descripcion = value;
	}

}
