<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>correcciondatosasegurado-servicios-negocio-ejb</artifactId>
  <name>Modulo Servicios de Negocio CDA CURP (ejb)</name>
  <url>http://maven.apache.org</url>
  <packaging>ejb</packaging>

  <parent>
    <artifactId>correcciondatosasegurado</artifactId>
    <groupId>mx.gob.imss.cit.cda</groupId>
    <version>1.0</version>
  </parent>

  <properties>
    <project.build.sourceEncoding>iso-8859-1</project.build.sourceEncoding>
    <org.springframework.version>3.0.5.RELEASE</org.springframework.version>
    <org.slf4j.version>1.6.1</org.slf4j.version>
    <org.hibernate.version>3.6.9.Final</org.hibernate.version>
    <interfaz.solicitudes>2.2</interfaz.solicitudes>
    <interfaz.medio.contacto>2.3</interfaz.medio.contacto>
    <mvn.responsables.web.service.url>http://saudigital-stage.imss.gob.mx:80/Sauimssdigital/WSPersonalSubdelegacionService</mvn.responsables.web.service.url>
    <delta.documentos.probatorios>2.4</delta.documentos.probatorios>
    <gestionsolicitud.flujo.trabajo>1.0</gestionsolicitud.flujo.trabajo>
    <cliente.boveda.ipicyt>1.0-QA</cliente.boveda.ipicyt>
  </properties>

  <dependencies>
    
    <!-- Test -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-test</artifactId>
      <version>${org.springframework.version}</version>
      <scope>test</scope>
    </dependency>

    <!-- INICIO DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->

    <!-- Dependencia del Proyecto de Objetos de modelo DELTA IMSS -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta</groupId>
      <artifactId>imssdigital-modelo</artifactId>
      <version>${delta.framework.version}</version>
      <type>jar</type>
    </dependency>

    <!-- Dependencia del Proyecto de Objetos de Persistencia DELTA IMSS -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta</groupId>
      <artifactId>delta-persistencia</artifactId>
      <version>${delta.framework.version}</version>
      <type>jar</type>
    </dependency>
    
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta</groupId>
      <artifactId>delta-modelo-negocio</artifactId>
      <version>${delta.framework.version}</version>
      <type>jar</type>
    </dependency>
    
    <!-- INICIO DEPENDENCIAS DEL GESTOR DE FLUJOS -->
    <dependency>
      <groupId>mx.gob.imss.cit.gestion.solicitud</groupId>
      <artifactId>gestionsolicitud-flujo-trabajo-interfaces-negocio</artifactId>
      <version>${gestionsolicitud.flujo.trabajo}</version>
    </dependency>
    
    <!--  Dependencia del JaxbUtils -->
    <dependency>
      <groupId>mx.gob.imss.distss.digital</groupId>
      <artifactId>jaxb-utils</artifactId>
      <version>1.0</version>
      <exclusions>
        <exclusion>
          <groupId>mx.gob.imss.ctirss.delta</groupId>
          <artifactId>delta-modelo-negocio</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>mx.gob.imss.ctirss.delta.gestion.solicitud</groupId>
      <artifactId>gestionSolicitud-interfaces-negocio</artifactId>
      <version>${interfaz.solicitudes}</version>
    </dependency>
    <dependency>
      <groupId>mx.gob.imss.cit.cda</groupId>
      <artifactId>correcciondatosasegurado-interfaces-negocio</artifactId>
      <version>${delta.correcciondatosasegurado}</version>
    </dependency>
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta.gestion.domicilio</groupId>
      <artifactId>gestionDomicilios-interfaces-negocio</artifactId>
      <version>${delta.domicilios}</version>
    </dependency>
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta.gestion.individuo.service.interface</groupId>
      <artifactId>gestionIndividuo-service-business-interface</artifactId>
      <version>${delta.personas}</version>
    </dependency>
	
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta.gestion.documento.probatorio</groupId>
      <artifactId>gestionDocumentoProbatorio-interfaces-negocio</artifactId>
      <version>${delta.documentos.probatorios}</version>
    </dependency> 
    
    <!-- Cliente de Webservices. Responsables Subdelegacion -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.clienteswebservices.responsables.subdelegacion</groupId>
      <artifactId>ClientesWebservices-responsables-subdelegacion</artifactId>
      <version>${delta.clientews}</version>
    </dependency>
		
    <!-- Cliente de Webservices. NSS Cuenta Individual -->
    <dependency>
      <groupId>mx.gob.imss.cit.ws</groupId>
      <artifactId>ClientesWebservices-nss-cuenta-individual</artifactId>
      <version>${delta.clientews}</version>
    </dependency>
		
    <!-- Cliente de Webservices. Registro Patronal -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.wsConsultaPatron</groupId>
      <artifactId>WSPatronCliente</artifactId>
      <version>1.0</version>
    </dependency>
		
    <!-- Dependencia para envio de correo -->
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta.derechohabientes</groupId>
      <artifactId>gestionDerechohabientes-interfaces-negocio</artifactId>
      <version>${delta.derechohabientes.version}</version>
    </dependency>
		
    <dependency>
      <groupId>mx.gob.imss.ctirss.delta.gestion.asegurado</groupId>
      <artifactId>gestionAsegurados-interfaces-negocio</artifactId>
      <version>${delta.asegurados}</version>
    </dependency>
		
    <!-- Dependencia con gestion Patronal para busqueda de NRP -->
    <dependency>
      <artifactId>delta-gestionPatronal-interfaces-negocio</artifactId>
      <groupId>mx.gob.imss.ctirss.delta.gestion.patronal</groupId>
      <version>${delta.gestionPatronal}</version>
    </dependency>
		
    <!--<dependency>
      <groupId>mx.gob.imss.cit</groupId>
      <artifactId>clienteServiciosComunes</artifactId>
      <version>1.0-0</version>
      <exclusions>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-web</artifactId>
        </exclusion>
      </exclusions>
    </dependency>-->

    <dependency>
      <groupId>mx.gob.imss.cit.clienteswebservices.boveda</groupId>
      <artifactId>WsBovedaLegadaIMSS-IPICYT</artifactId>
      <version>${cliente.boveda.ipicyt}</version>
    </dependency>

    <!-- FIN DE LAS DEPENDENCIAS DEL FRAMEWORK DELTA -->

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8.1</version>
      <scope>compile</scope>
    </dependency>

    
    <!-- HIBERNATE CORE -->
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-entitymanager</artifactId>
      <version>${org.hibernate.version}</version>
    </dependency>

    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>${org.hibernate.version}</version>
    </dependency>

    <dependency>
      <groupId>org.hibernate.javax.persistence</groupId>
      <artifactId>hibernate-jpa-2.0-api</artifactId>
      <version>1.0.1.Final</version>
    </dependency>

    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-commons-annotations</artifactId>
      <version>3.2.0.Final</version>
    </dependency>

    <!-- HIBERNATE DEPENDECIES -->
    <dependency>
      <groupId>antlr</groupId>
      <artifactId>antlr</artifactId>
      <version>2.7.6</version>
    </dependency>

    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
      <version>3.1</version>
    </dependency>

    <dependency>
      <groupId>dom4j</groupId>
      <artifactId>dom4j</artifactId>
      <version>1.6.1</version>
    </dependency>

    <dependency>
      <groupId>javax.transaction</groupId>
      <artifactId>jta</artifactId>
      <version>1.1</version>
    </dependency>

    <dependency>
      <groupId>cglib</groupId>
      <artifactId>cglib-nodep</artifactId>
      <version>2.2</version>
    </dependency>

    <dependency>
      <groupId>asm</groupId>
      <artifactId>asm</artifactId>
      <version>3.1</version>
    </dependency>

    <dependency>
      <groupId>javassist</groupId>
      <artifactId>javassist</artifactId>
      <version>3.12.0.GA</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${org.slf4j.version}</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>${org.slf4j.version}</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>${org.slf4j.version}</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.16</version>
    </dependency>

    <dependency>
      <groupId>oracle.jdbc</groupId>
      <artifactId>ojdbc</artifactId>
      <version>6</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.1</version>
    </dependency>
	
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.4</version>
    </dependency> 

    <!-- EJB -->
    <dependency>
      <groupId>javax.ejb</groupId>
      <artifactId>ejb-api</artifactId>
      <version>3.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>weblogic</groupId>
      <artifactId>wlfullclient</artifactId>
      <version>10.3.4</version>
      <scope>provided</scope>
    </dependency>
    
    <!-- JASPER -->
    <dependency>        
      <groupId>net.sf.jasperreports</groupId>
      <artifactId>jasperreports</artifactId>
      <version>4.0.1</version>
      <exclusions>
        <exclusion>
          <groupId>antlr</groupId>
          <artifactId>antlri</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-beanutils</groupId>
          <artifactId>commons-beanutils</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-collections</groupId>
          <artifactId>commons-collections</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-javaflow</groupId>
          <artifactId>commons-javaflow</artifactId>
        </exclusion>
        <exclusion>
          <groupId>eclipse</groupId>
          <artifactId>jdtcore</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.persistence</groupId>
          <artifactId>persistence-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.servlet</groupId>
          <artifactId>servlet-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.xml.soap</groupId>
          <artifactId>saaj-api</artifactId>
        </exclusion>
	      		
        <exclusion>
          <groupId>jaxen</groupId>
          <artifactId>jaxen</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>jfree</groupId>
          <artifactId>jcommon</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jfree</groupId>
          <artifactId>jfreechart</artifactId>
        </exclusion>    		
        <exclusion>
          <groupId>mondrian</groupId>
          <artifactId>mondrian</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sf.barcode4j</groupId>
          <artifactId>barcode4j</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sourceforge.barbecue</groupId>
          <artifactId>barbecue</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sourceforge.jexcelapi</groupId>
          <artifactId>jxl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.ant</groupId>
          <artifactId>velocity</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>org.apache.poi</groupId>
          <artifactId>poi</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>org.apache.poi</groupId>
          <artifactId>poi-ooxml</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>org.apache.velocity</groupId>
          <artifactId>velocity</artifactId>
        </exclusion>   		
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-awt-util</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-bridge</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-css</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-dom</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-gvt</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-script</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-svg-dom</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-svggen</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-util</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>org.beanshell</groupId>
          <artifactId>bsh</artifactId>
        </exclusion>     		
        <exclusion>
          <groupId>org.codehaus.castor</groupId>
          <artifactId>castor</artifactId>
        </exclusion>     		
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-all</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>org.hibernate</groupId>
          <artifactId>hibernate</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-beans</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>rhino</groupId>
          <artifactId>js</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>xalan</groupId>
          <artifactId>xalan</artifactId>
        </exclusion>      		
        <exclusion>
          <groupId>xml-apis</groupId>
          <artifactId>xml-apis</artifactId>
        </exclusion>
      </exclusions>		
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>3.0.5.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>commons-digester</groupId>
      <artifactId>commons-digester</artifactId>
      <version>2.1</version>
    </dependency>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.1.1</version>
    </dependency>
    <dependency>
      <groupId>mx.gob.imss.mac</groupId>
      <artifactId>poi</artifactId>
      <version>3.5</version>
    </dependency>
	
    <dependency>
      <groupId>mx.gob.imss.utilerias</groupId>
      <artifactId>utilMail</artifactId>
      <version>1.0.03</version>
    </dependency>
		
    <dependency>
      <groupId>javax.mail</groupId>
      <artifactId>javax.mail-api</artifactId>
      <version>1.5.1</version>
    </dependency>	
	
    <!--  DEPENDECIES FOR WS -->
    <dependency>
      <groupId>javax.xml</groupId>
      <artifactId>jaxrpc-api</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.axis</groupId>
      <artifactId>axis</artifactId>
      <version>1.4</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/commons-discovery/commons-discovery -->
    <!-- <dependency>
        <groupId>commons-discovery</groupId>
        <artifactId>commons-discovery</artifactId>
        <version>0.5</version>
    </dependency>
    https://mvnrepository.com/artifact/axis/axis-wsdl4j
    <dependency>
        <groupId>axis</groupId>
        <artifactId>axis-wsdl4j</artifactId>
        <version>1.2</version>
    </dependency> -->
    
  </dependencies>
  
  <repositories>
    <repository>
      <id>ctirss</id>
      <name>CTIRSS repository</name>
      <layout>default</layout>
      <url>http://172.16.5.134:8080/repository/repo/</url>
      <snapshots>
      </snapshots>
    </repository>
  </repositories>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    
    <plugins>
      <!-- Utilizar el cliente en la dependencia 
      <plugin>
        <groupId>org.jvnet.jax-ws-commons</groupId>
        <artifactId>jaxws-maven-plugin</artifactId>
        <version>2.3</version>
        <executions>
          
          <execution>
            <goals>
              <goal>wsimport</goal>
            </goals>
            <configuration>
              <target>2.1</target>
              <verbose>true</verbose>
              <args>
                <arg>-B-XautoNameResolution</arg>
              </args>
              <packageName>mx.gob.imss.cit.ws.cuentaindividualhistorico.cliente</packageName>
              <wsdlDirectory>${basedir}/src/main/resources/wsdl</wsdlDirectory>
              <wsdlFiles>
                <wsdlFile>WSHistoricoCentralSISEC.wsdl</wsdlFile>
              </wsdlFiles>
              <sourceDestDir>${project.build.directory}/generated-sources/classes</sourceDestDir>
              <xnocompile>true</xnocompile>
              <extension>true</extension>
              <verbose>true</verbose>              
              <catalog>${basedir}/src/jax-ws-catalog.xml</catalog>
              <wsdlLocation>/wsdl/*</wsdlLocation>
              <staleFile>${project.build.directory}/jaxws/stale/WSHistoricoCentralSISEC.stale</staleFile>
              <vmArgs>
                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
              </vmArgs>
            </configuration>
            <id>wsimport-generate-WSHistoricoCentralSISEC</id>
            <phase>generate-sources</phase>
          </execution>
					
        </executions>
        <dependencies>
          <dependency>
            <groupId>javax.xml</groupId>
            <artifactId>webservices-api</artifactId>
            <version>2.0</version>
          </dependency>
        </dependencies>
        <configuration>
          <sourceDestDir>${project.build.directory}/generated-sources/jaxws-wsimport</sourceDestDir>
          <destDir>${project.build.directory}/generated-sources/classes</destDir>
          <xnocompile>true</xnocompile>
          <verbose>true</verbose>
          <extension>true</extension>
          <catalog>${basedir}/src/jax-ws-catalog.xml</catalog>
        </configuration>
      </plugin -->
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-ejb-plugin</artifactId>
        <version>2.3</version>
        <configuration>
          <ejbVersion>3.0</ejbVersion>
        </configuration>
      </plugin>

      <!-- Habilita los facets y natures para que el eclipse reconoza el proyecto como de tipo de EJB. -->
      <plugin>
        <artifactId>maven-eclipse-plugin</artifactId>
        <configuration>
          <additionalBuildcommands>
            <buildCommand>
              <name>org.eclipse.jdt.core.javabuilder</name>
            </buildCommand>
            <buildCommand>
              <name>org.eclipse.wst.common.project.facet.core.builder</name>
            </buildCommand>
            <buildCommand>
              <name>org.eclipse.wst.validation.validationbuilder</name>
            </buildCommand>
          </additionalBuildcommands>

          <additionalProjectnatures>
            <projectnature>org.eclipse.wst.common.project.facet.core.nature</projectnature>
            <projectnature>org.eclipse.jdt.core.javanature</projectnature>
            <projectnature>org.eclipse.wst.common.modulecore.ModuleCoreNature</projectnature>
            <projectnature>org.eclipse.jem.workbench.JavaEMFNature</projectnature>
          </additionalProjectnatures>

          <additionalConfig>
            <file>
              <name>.settings/org.eclipse.wst.common.project.facet.core.xml</name>
              <content>&lt;faceted-project&gt;
                &lt;runtime name="Weblogic Runtime" /&gt;
                &lt;fixed facet="jst.ejb" /&gt;
                &lt;fixed facet="jst.java" /&gt;
                &lt;installed
                facet="jst.java" version="6.0" /&gt;
                &lt;installed facet="jst.ejb" version="3.0" /&gt;
                &lt;/faceted-project&gt;</content>
            </file>
            <file>
              <name>.settings/org.eclipse.wst.common.component</name>
              <content>&lt;project-modules id="moduleCoreId"
                project-version="1.5.0"&gt;
                &lt;wb-module deploy-name="${project.artifactId}"&gt;
                &lt;wb-resource deploy-path="/"
                source-path="/src/main/java" /&gt;
                &lt;wb-resource deploy-path="/"
                source-path="/src/main/resources" /&gt;
                &lt;property name="java-output-path"
                value="target/classes" /&gt;
                &lt;/wb-module&gt;
                &lt;/project-modules&gt;</content>
            </file>
          </additionalConfig>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
	    
    <!-- Perfil para prod y QA  -->
    <profile>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <id>compile-dev-ventanilla</id>
      <properties>
        <mvn.registro.patronal.webservice.url>http://dictamendigital-stage.imss.gob.mx/wsBDTUPatrones/WSConsultaPatronService</mvn.registro.patronal.webservice.url>
        <mvn.cuentaindividual.documento.wsdl>http://11.254.13.146:7001/WSNssCuentaIndividual/WSNssCuentaIndividual?wsdl</mvn.cuentaindividual.documento.wsdl>
        <mvn.cuentaindivhistorico.documento.wsdl>http://11.254.13.146:7001/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC</mvn.cuentaindivhistorico.documento.wsdl>
      </properties>
    </profile>
    
    <profile>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <id>compile-stage-ventanilla</id>
      <properties>
        <mvn.registro.patronal.webservice.url>http://dictamendigital.imss.gob.mx/wsBDTUPatrones/WSConsultaPatronService</mvn.registro.patronal.webservice.url>
        <mvn.cuentaindividual.documento.wsdl>http://11.254.13.146:7001/WSNssCuentaIndividual/WSNssCuentaIndividual?wsdl</mvn.cuentaindividual.documento.wsdl>
        <mvn.cuentaindivhistorico.documento.wsdl>http://11.254.13.146:7001/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC</mvn.cuentaindivhistorico.documento.wsdl>
      </properties>
    </profile>
    <profile>
      <id>compile-stage-ventanilla-autorizador</id>
      <properties>
        <mvn.registro.patronal.webservice.url>http://dictamendigital.imss.gob.mx/wsBDTUPatrones/WSConsultaPatronService</mvn.registro.patronal.webservice.url>
        <mvn.cuentaindividual.documento.wsdl>http://adodigital.imss.gob.mx/WSNssCuentaIndividual/WSNssCuentaIndividual?wsdl</mvn.cuentaindividual.documento.wsdl>
        <mvn.cuentaindivhistorico.documento.wsdl>http://adodigital.imss.gob.mx/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC</mvn.cuentaindivhistorico.documento.wsdl>
      </properties>
    </profile>
    <profile>
      <id>compile-prod-ventanilla-internet</id>
      <properties>
        <mvn.registro.patronal.webservice.url>http://dictamendigital.imss.gob.mx/wsBDTUPatrones/WSConsultaPatronService</mvn.registro.patronal.webservice.url>
        <mvn.cuentaindividual.documento.wsdl>http://adodigital.imss.gob.mx/WSNssCuentaIndividual/WSNssCuentaIndividual?wsdl</mvn.cuentaindividual.documento.wsdl>
        <mvn.cuentaindivhistorico.documento.wsdl>http://adodigital.imss.gob.mx/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC</mvn.cuentaindivhistorico.documento.wsdl>
      </properties>
    </profile>
    <profile>
      <id>compile-prod-ventanilla-internet-autorizador</id>
      <properties>
        <mvn.registro.patronal.webservice.url>http://dictamendigital.imss.gob.mx/wsBDTUPatrones/WSConsultaPatronService</mvn.registro.patronal.webservice.url>
        <mvn.cuentaindividual.documento.wsdl>http://adodigital.imss.gob.mx/WSNssCuentaIndividual/WSNssCuentaIndividual?wsdl</mvn.cuentaindividual.documento.wsdl>
        <mvn.cuentaindivhistorico.documento.wsdl>http://adodigital.imss.gob.mx/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC</mvn.cuentaindivhistorico.documento.wsdl>
      </properties>
    </profile>
  </profiles>	
</project>
