##### URL SERVICIOS NSSA #####

servicios.externos.rest.url.valida.retroactividad=${mvn.servicios.externos.rest.url.valida.retroactividad}
servicios.externos.rest.url.calculo.pagos=${mvn.servicios.externos.rest.url.calculo.pagos}
servicios.externos.rest.url.generacion.multilinea=${mvn.servicios.externos.rest.url.generacion.multilinea}
servicios.externos.rest.timeOut.connection=${mvn.servicios.externos.rest.timeOut.connection}
servicios.externos.rest.timeOut.response=${mvn.servicios.externos.rest.timeOut.response}


