##################
# FTP FileConfig #
##################
filesystem.ivro.output.url=ivro/output

################
# Servidor ftp #
################
ftp.server.url=vzapmb03.imss.gob.mx
ftp.server.user=ftp_delta
ftp.server.passwd=ftp0d3lt1.
ftp.server.port=21

application.mode=${mvn.application.mode}


##################
# Ruta de origen #
##################
file.ivro.input.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/sindo/ivro
file.ivro.input.tmp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/ivro_temp


####################
# Ruta de respaldo #
####################
file.ivro.resp.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/ivro_hist


########################
# Ruta de verificacion #
########################
file.ivro.verif.url=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/checksum
file.ivro.verif.time=1000
file.ivro.verif.retry=3


############################
# Ruta de FTP (Filesystem) #
############################
filesystem.ftp.base.output.url=/share/oracle/osbapdir01_domain/delta


#################
# Archivos IVRO #
#################

sindo.file.ciz01=AYPENT_CIZ01.txt
sindo.file.ciz02=AYPENT_CIZ02.txt
sindo.file.ciz03=AYPENT_CIZ03.txt


##########################
# Archivos de validacion #
##########################

filesystem.delta.proceso.estatus=/share/oracle/osbapdir01_domain/osb_cluster1/ftp/lock/ivro
