<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>gestionMotorCalculo-packing</artifactId>
  <name>Modulo Empaquetador de Servicios DELTA</name>
  <url>http://maven.apache.org</url>
  <packaging>ear</packaging>

  <parent>
    <artifactId>gestionMotorCalculo</artifactId>
    <groupId>mx.gob.imss.ctirss.delta.gestion.motorCalculo</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <properties>
    <skipTests>true</skipTests>
  </properties>

  <repositories>
    <repository>
      <id>ctirss</id>
      <name>CTIRSS repository</name>
      <url>http://172.16.5.134:8080/repository/repo/</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <artifactId>gestionMotorCalculo-servicios-negocio-ejb</artifactId>
      <groupId>mx.gob.imss.ctirss.delta.gestion.motorCalculo</groupId>
      <version>1.0-SNAPSHOT</version>
      <type>ejb</type>
    </dependency>    
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-ear-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <version>5</version>
          <defaultLibBundleDir>lib</defaultLibBundleDir>
        </configuration>
      </plugin>

      <!-- Habilita los facets y natures para que el eclipse reconoza el proyecto como de tipo de EAR. -->
      </plugins>

    <extensions>
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
        <artifactId>wagon-ftp</artifactId>
      </extension>
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
        <artifactId>wagon-webdav</artifactId>
      </extension>
    </extensions>
  </build>

  <pluginRepositories>
    <pluginRepository>
      <id>ctirss</id>
      <name>CTIRSS repository</name>
      <url>http://172.16.5.134:8080/repository/repo/</url>
      <layout>default</layout>
      <snapshots>
      </snapshots>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
    </pluginRepository>
  </pluginRepositories>

  <distributionManagement>
    <!-- use the following if you're not using a snapshot version. -->
    <repository>
      <id>ctirss-archiva</id>
      <name>CTIRSS Repository Name</name>
      <url>dav:http://172.16.5.134:8080/repository/repo/</url>
    </repository>
    <snapshotRepository>
      <id>ctirss-archiva</id>
      <name>CTIRSS Repository Name</name>
      <url>dav:http://172.16.5.134:8080/repository/repo/</url>
    </snapshotRepository>
  </distributionManagement>

  <scm>
    <connection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_domicilios/</connection>
    <developerConnection>scm:svn:http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_domicilios/</developerConnection>
    <url>http://11.254.16.21/svn/base_arquitectura_delta/codigo/trunk/gestion_domicilios/</url>
  </scm>

  <profiles>
    <!-- Perfil para el deployment de los servicios REMOTO -->
    <profile>
      <id>qa-deploy-all</id>
      <activation>
        <property>
          <name>qa-deploy-all</name>
        </property>
      </activation>
      <build>
        <plugins>
          <!-- Weblogic Deployment Plug-In -->
          <plugin>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-maven-plugin</artifactId>
            <version>10.3.4</version>
            <configuration>
              <adminurl>t3://172.24.116.37:15050</adminurl>
              <user>admin_wlgeceqa</user>
              <password>wlgeceqa_admin</password>
              <upload>true</upload>
              <action>deploy</action>
              <remote>true</remote>
              <verbose>true</verbose>
              <source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
              <name>${project.build.finalName}</name>
              <targets>c_geceqa_02</targets>
              <nostage>true</nostage>
            </configuration>

            <executions>
              <execution>
                <phase>install</phase>
                <goals>
                  <goal>deploy</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <!-- Perfil para Remover los deploys en el ambiente de Desarrollo IMSS -->
    <profile>
      <id>qa-remove-all</id>
      <activation>
        <property>
          <name>qa-remove-all</name>
        </property>
      </activation>
      <build>
        <plugins>
          <!-- Weblogic Deployment Plug-In -->
          <plugin>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-maven-plugin</artifactId>
            <version>10.3.4</version>
            <configuration>
              <adminurl>t3://172.24.116.37:15050</adminurl>
              <user>admin_wlgeceqa</user>
              <password>wlgeceqa_admin</password>
              <name>${project.build.finalName}</name>
              <targets>c_geceqa_02</targets>
            </configuration>

            <executions>
              <execution>
                <phase>install</phase>
                <goals>
                  <goal>undeploy</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>


    <!-- Perfil para el deployment de los servicios REMOTO -->
    <profile>
      <id>dev-deploy-all</id>
      <activation>
        <property>
          <name>dev-deploy-all</name>
        </property>
      </activation>
      <build>
        <plugins>
          <!-- Weblogic Deployment Plug-In -->
          <plugin>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-maven-plugin</artifactId>
            <version>10.3.4</version>
            <configuration>
              <adminurl>t3://172.24.116.38:11000</adminurl>
              <user>admin_wldldev</user>
              <password>wldldev_admin</password>
              <upload>true</upload>
              <action>deploy</action>
              <remote>true</remote>
              <verbose>true</verbose>
              <source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
              <name>${project.build.finalName}</name>
              <targets>c_web_digital</targets>
              <nostage>true</nostage>
            </configuration>

            <executions>
              <execution>
                <phase>install</phase>
                <goals>
                  <goal>deploy</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <!-- Perfil para Remover los deploys en el ambiente de Desarrollo IMSS -->
    <profile>
      <id>dev-remove-all</id>
      <activation>
        <property>
          <name>dev-remove-all</name>
        </property>
      </activation>
      <build>
        <plugins>
          <!-- Weblogic Deployment Plug-In -->
          <plugin>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-maven-plugin</artifactId>
            <version>10.3.4</version>
            <configuration>
              <adminurl>t3://172.24.116.38:11000</adminurl>
              <user>admin_wldldev</user>
              <password>wldldev_admin</password>
              <name>${project.build.finalName}</name>
              <targets>c_web_digital</targets>
            </configuration>

            <executions>
              <execution>
                <phase>install</phase>
                <goals>
                  <goal>undeploy</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
