<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>gestionSolicitud</artifactId>
    <groupId>mx.gob.imss.ctirss.delta.gestion.solicitud</groupId>
    <version>2.2-SNAPSHOT</version>
  </parent>
  <groupId>mx.gob.imss.ctirss.delta.solicitud</groupId>
  <artifactId>jms-client-local</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>jms-client-local</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>weblogic</groupId>
      <artifactId>wlfullclient</artifactId>
      <version>10.3.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.1</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>1.7.3</version>
    </dependency>
    
    <dependency>
			<groupId>mx.gob.imss.ctirss.delta</groupId>
			<artifactId>delta-modelo-negocio</artifactId>
			<version>2.6-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
	</dependency>
    
	<dependency>
		<groupId>mx.gob.imss.ctirss.delta.gestion.solicitud</groupId>
		<artifactId>gestionSolicitud-servicios-negocio-ejb</artifactId>
		<version>2.2-SNAPSHOT</version>
		<!--<type>ejb</type>-->
	</dependency>
    
  </dependencies>
  <build>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-surefire-plugin</artifactId>
              <configuration>
                  <skipTests>false</skipTests>
              </configuration>
          </plugin>
      </plugins>
  </build>
</project>
