#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp

guardaSolicitud.(class) = org.springframework.web.servlet.view.JstlView
guardaSolicitud.url = /WEB-INF/views/guardarSolicitud.jsp

#Tiles redirect
welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=login
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

inicial.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicial.url =inicial

busquedaPrincipal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaPrincipal.url=busquedaPrincipal

homeNormativoCE.(class)=org.springframework.web.servlet.view.tiles2.TilesView
homeNormativoCE.url=homeNormativoCE

homeNormativoCEReportes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
homeNormativoCEReportes.url=homeNormativoCEReportes

homeNormativoJefe.(class)=org.springframework.web.servlet.view.tiles2.TilesView
homeNormativoJefe.url=homeNormativoJefe

homeJefeDeptoSuper.(class)=org.springframework.web.servlet.view.tiles2.TilesView
homeJefeDeptoSuper.url=homeJefeDeptoSuper

registroConyugeConcubinario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroConyugeConcubinario.url=registroConyugeConcubinario

menuTramitador.(class)=org.springframework.web.servlet.view.tiles2.TilesView
menuTramitador.url=menuTramitador

menuAtendidas.(class)=org.springframework.web.servlet.view.tiles2.TilesView
menuAtendidas.url=menuAtendidas

menuPendientesAut.(class)=org.springframework.web.servlet.view.tiles2.TilesView
menuPendientesAut.url=menuPendientesAut


test.(class)=org.springframework.web.servlet.view.tiles2.TilesView
test.url=test\t

buscarAsentamiento.(class) = org.springframework.web.servlet.view.tiles2.TilesView
buscarAsentamiento.url = buscarAsentamiento

#Modulo Gestion de derechohabientes
prorrogas.(class)=org.springframework.web.servlet.view.JstlView
prorrogas.url=/WEB-INF/views/prorrogas/prorrogaServiciosMedicos.jsp

prorrogasEstudios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prorrogasEstudios.url=prorrogaEstudios

registroEstudios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroEstudios.url= registroProrrogaEstudios


prorrogasEnfermedad.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prorrogasEnfermedad.url= prorrogasEnfermedad

prorrogasInvalidez.(class)=org.springframework.web.servlet.view.JstlView
prorrogasInvalidez.url=/WEB-INF/views/prorrogas/ConsultaDerechohabientesPorInvalidez.jsp

prorrogasLaudo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prorrogasLaudo.url= prorrogasLaudo

prorrogasObstetricos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prorrogasObstetricos.url=prorrogasObstetricos

prorrogasTemporal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prorrogasTemporal.url=prorrogasTemporal


consultaProrrogas.(class)=org.springframework.web.servlet.view.tiles2.TilesView
consultaProrrogas.url= consultaProrrogas

prorrogasPermanente.(class)=org.springframework.web.servlet.view.tiles2.TilesView
prorrogasPermanente.url=prorrogasPermanente

registroProrrogas.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroProrrogas.url= registroProrrogas

registroInvalidez.(class)=org.springframework.web.servlet.view.JstlView
registroInvalidez.url=/WEB-INF/views/prorrogas/RegistroProrrogaPorInvalidez.jsp

registroPermanente.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPermanente.url=registroPermanente

registroLaudo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroLaudo.url=registroProrrogaLaudo

registroEnfermedad.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroEnfermedad.url=registroEnfermedad


contenedor.(class)=org.springframework.web.servlet.view.JstlView
contenedor.url=/WEB-INF/views/prorrogas/contenedorPdf.jsp

documentos.(class)=org.springframework.web.servlet.view.JstlView
documentos.url=/WEB-INF/views/general/cargadorDocumentos.jsp

grupoFamiliar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
grupoFamiliar.url=grupoFamiliar

grupoFamiliar2.(class)=org.springframework.web.servlet.view.tiles2.TilesView
grupoFamiliar2.url=grupoFamiliar2

citaProgramada.(class)=org.springframework.web.servlet.view.tiles2.TilesView
citaProgramada.url=citaProgramada

registro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registro.url=registro

validar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
validar.url=validar

comprobantes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
comprobantes.url=comprobantes

comprobantesAut.(class)=org.springframework.web.servlet.view.tiles2.TilesView
comprobantesAut.url=comprobantesAut

confirmacion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmacion.url=confirmacion

#Vistas para la entidad Solicitud
detalleSolicitud.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleSolicitud.url= detalleSolicitud

detalleRegistro.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleRegistro.url= detalleRegistro

citaSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
citaSolicitud.url=citaSolicitud

citaSolicitudGeneral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
citaSolicitudGeneral.url=citaSolicitudGeneral


rechazoSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
rechazoSolicitud.url=rechazoSolicitud

detalleCorreccion.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleCorreccion.url= detalleCorreccion

detalleCircunscripcion.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleCircunscripcion.url= detalleCircunscripcion

detalleCambioMedico.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleCambioMedico.url= detalleCambioMedico

detalleCambioUmf.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleCambioUmf.url = detalleCambioUmf

detalleProrroga.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleProrroga.url = detalleProrroga

detalleAsignacionMedico.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleAsignacionMedico.url = detalleAsignacionMedico

detalleTramiteDerechohabiente.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleTramiteDerechohabiente.url = detalleTramiteDerechohabiente

detalleSolicitudReg.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleSolicitudReg.url= detalleSolicitudReg

muestraSolicitudesPenAut.(class) = org.springframework.web.servlet.view.tiles2.TilesView
muestraSolicitudesPenAut.url = muestraSolicitudesPenAut

muestraSolicitudesAtendidas.(class) = org.springframework.web.servlet.view.tiles2.TilesView
muestraSolicitudesAtendidas.url = muestraSolicitudesAtendidas

#Vistas Relacionadas con derechohabiente
detalleDerechohabiente.(class) = org.springframework.web.servlet.view.tiles2.TilesView
detalleDerechohabiente.url= detalleDerechohabiente

listaBajaDefuncion.(class) = org.springframework.web.servlet.view.tiles2.TilesView
listaBajaDefuncion.url =  listaBajaDefuncion

listaBajaAdministrativa.(class) = org.springframework.web.servlet.view.tiles2.TilesView
listaBajaAdministrativa.url = listaBajaAdministrativa

listaBajaDivorcio.(class) = org.springframework.web.servlet.view.tiles2.TilesView
listaBajaDivorcio.url =  listaBajaDivorcio

inicioBajaConcubinato.(class) = org.springframework.web.servlet.view.tiles2.TilesView
inicioBajaConcubinato.url =  inicioBajaConcubinato

inicioBajaDivorcio.(class) = org.springframework.web.servlet.view.tiles2.TilesView
inicioBajaDivorcio.url =  inicioBajaDivorcio

listaBajaConcubinato.(class) = org.springframework.web.servlet.view.tiles2.TilesView
listaBajaConcubinato.url =  listaBajaConcubinato

listaBajaConvivencia.(class) = org.springframework.web.servlet.view.tiles2.TilesView
listaBajaConvivencia.url =  listaBajaConvivencia

validarBaja.(class) = org.springframework.web.servlet.view.tiles2.TilesView
validarBaja.url =  validarBaja

autorizarBaja.(class) = org.springframework.web.servlet.view.tiles2.TilesView
autorizarBaja.url = autorizarBaja

tramitarValidarBaja.(class) = org.springframework.web.servlet.view.tiles2.TilesView
tramitarValidarBaja.url = tramitarValidarBaja

#Vistas Relacionadas con correccion de derechohabiente
cambioClinicaHome.(class) = org.springframework.web.servlet.view.tiles2.TilesView
cambioClinicaHome.url = cambioClinicaHome

datosCorreccionDerechohabiente.(class) = org.springframework.web.servlet.view.tiles2.TilesView
datosCorreccionDerechohabiente.url = datosCorreccionDerechohabiente

datosCorreccionDerechohabienteView.(class) = org.springframework.web.servlet.view.tiles2.TilesView
datosCorreccionDerechohabienteView.url = datosCorreccionDerechohabienteView

#Mapeo para la asignacion de domicilio cuando el derechohabiente no cuenta con uno
asignacionDomicilioDerechohabiente.(class)=org.springframework.web.servlet.view.tiles2.TilesView
asignacionDomicilioDerechohabiente.url=asignacionDomicilioDerechohabiente

#Pantalla final de asignacion de domicilio
finalizaAsignacionDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
finalizaAsignacionDomicilio.url=finalizaAsignacionDomicilio

correccionMedicoEnTurno.(class) = org.springframework.web.servlet.view.tiles2.TilesView
correccionMedicoEnTurno.url = correccionMedicoEnTurno

correccionUMF.(class) = org.springframework.web.servlet.view.tiles2.TilesView
correccionUMF.url = correccionUMF

cambioClinicaMultiple.(class) = org.springframework.web.servlet.view.tiles2.TilesView
cambioClinicaMultiple.url =cambioClinicaMultiple

correccionCircunscripcion.(class) = org.springframework.web.servlet.view.tiles2.TilesView
correccionCircunscripcion.url = correccionCircunscripcion

suspencionCircunscripcion.(class) = org.springframework.web.servlet.view.tiles2.TilesView
suspencionCircunscripcion.url = datosSuspensionCircunscripcion

candidatosCorreccionDerechohabiente.(class) = org.springframework.web.servlet.view.tiles2.TilesView
candidatosCorreccionDerechohabiente.url = candidatosCorreccionDerechohabiente

finalizacionCorreccion.(class) = org.springframework.web.servlet.view.tiles2.TilesView
finalizacionCorreccion.url = finalizacionCorreccion

finalizacionTramite.(class) = org.springframework.web.servlet.view.tiles2.TilesView
finalizacionTramite.url = finalizacionTramite

cuestionario.(class) = org.springframework.web.servlet.view.tiles2.TilesView
cuestionario.url = cuestionario

#pantalla de prueba de invocacion de cuestionarios
principal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
principal.url=principal

corroborarResultado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
corroborarResultado.url=corroborarResultado

#Pantalla Inicio
inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicio.url=inicio


#Vistas Relacionadas con captura de documentos
cedulaProfesional.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cedulaProfesional.url=cedulaProfesional

cartillaMilitar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaMilitar.url=cartillaMilitar

constanciaEstudios.(class)=org.springframework.web.servlet.view.tiles2.TilesView
constanciaEstudios.url=constanciaEstudios

certificadoNacimiento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoNacimiento.url=certificadoNacimiento

pasaporte.(class)=org.springframework.web.servlet.view.tiles2.TilesView
pasaporte.url=pasaporte

actaComun.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaComun.url=actaComun

actaNacimiento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaNacimiento.url=actaNacimiento

curp.(class)=org.springframework.web.servlet.view.tiles2.TilesView
curp.url=curp

credencialElector.(class)=org.springframework.web.servlet.view.tiles2.TilesView
credencialElector.url=credencialElector

dictamenIncapacitado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
dictamenIncapacitado.url=dictamenIncapacitado

obstetrico.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obstetrico.url=obstetrico

certificadoSitCritica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoSitCritica.url=certificadoSitCritica

acuerdo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
acuerdo.url=acuerdo

vigenciaTemporal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vigenciaTemporal.url=vigenciaTemporal

compDom.(class)=org.springframework.web.servlet.view.tiles2.TilesView
compDom.url=compDom

adimss.(class)=org.springframework.web.servlet.view.tiles2.TilesView
adimss.url=adimss

actaPactoCivil.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaPactoCivil.url=actaPactoCivil

#MUESTRA

muestraDocTram.(class)=org.springframework.web.servlet.view.tiles2.TilesView
muestraDocTram.url=muestraDocTram


cedulaProfesionalMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cedulaProfesionalMuestra.url=cedulaProfesionalMuestra

cartillaMilitarMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaMilitarMuestra.url=cartillaMilitarMuestra

constanciaEstudiosMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
constanciaEstudiosMuestra.url=constanciaEstudiosMuestra

certificadoNacimientoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoNacimientoMuestra.url=certificadoNacimientoMuestra

pasaporteMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
pasaporteMuestra.url=pasaporteMuestra

actaComunMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaComunMuestra.url=actaComunMuestra

actaNacimientoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaNacimientoMuestra.url=actaNacimientoMuestra

curpMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
curpMuestra.url=curpMuestra

adimssMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
adimssMuestra.url=adimssMuestra

credencialElectorMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
credencialElectorMuestra.url=credencialElectorMuestra

dictamenIncapacitadoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
dictamenIncapacitadoMuestra.url=dictamenIncapacitadoMuestra

obstetricoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obstetricoMuestra.url=obstetricoMuestra

certificadoSitCriticaMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
certificadoSitCriticaMuestra.url=certificadoSitCriticaMuestra

acuerdoMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
acuerdoMuestra.url=acuerdoMuestra

vigenciaTemporalMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vigenciaTemporalMuestra.url=vigenciaTemporalMuestra

compDomMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
compDomMuestra.url=compDomMuestra

actaPactoCivilMuestra.(class)=org.springframework.web.servlet.view.tiles2.TilesView
actaPactoCivilMuestra.url=actaPactoCivilMuestra

autorizacionCorreccion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
autorizacionCorreccion.url=autorizacionCorreccion

asignarMedico.(class)=org.springframework.web.servlet.view.tiles2.TilesView
asignarMedico.url=asignarMedico




#Cambio clinica mas
cambioClinicaMasCol.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cambioClinicaMasCol.url=cambioClinicaMasCol

resultadoProrroga.(class)=org.springframework.web.servlet.view.tiles2.TilesView
resultadoProrroga.url=resultadoProrroga

cartillaNacionalSalud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cartillaNacionalSalud.url=cartillaNacionalSalud

documentoSAV007.(class)=org.springframework.web.servlet.view.tiles2.TilesView
documentoSAV007.url=documentoSAV007

documentoSAV017A.(class)=org.springframework.web.servlet.view.tiles2.TilesView
documentoSAV017A.url=documentoSAV017A

documentoSAV017S.(class)=org.springframework.web.servlet.view.tiles2.TilesView
documentoSAV017S.url=documentoSAV017S

documentoSAV005.(class)=org.springframework.web.servlet.view.tiles2.TilesView
documentoSAV005.url=documentoSAV005

detalleTramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleTramite.url=detalleTramite

mostrarDetalleTramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mostrarDetalleTramite.url=mostrarDetalleTramite

mostrarDetalleSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mostrarDetalleSolicitud.url = mostrarDetalleSolicitud

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url = internalError

initBusquedaCurp.(class)=org.springframework.web.servlet.view.JstlView
initBusquedaCurp.url=/WEB-INF/views/busquedaPersonaPorCurp.jsp

logOut.(class)=org.springframework.web.servlet.view.tiles2.TilesView
logOut.url=logOut

#nueva pantalla para el registro de derechohabientes
inicioRegistroDerechohabiente.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicioRegistroDerechohabiente.url=inicioRegistroDerechohabiente

confirmacionRegistro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmacionRegistro.url=confirmacionRegistro

finalizacionRegistro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
finalizacionRegistro.url=finalizacionRegistro

asignacionDomicilioEstudiante.(class)=org.springframework.web.servlet.view.tiles2.TilesView
asignacionDomicilioEstudiante.url = asignacionDomicilioEstudiante

grupoFamiliarEstudiantes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
grupoFamiliarEstudiantes.url = grupoFamiliarEstudiantes


grupoFamiliarInconsistentes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
grupoFamiliarInconsistentes.url = grupoFamiliarInconsistentes

razonRechazoOtrosMedios.(class)=org.springframework.web.servlet.view.JstlView
razonRechazoOtrosMedios.url=/WEB-INF/views/solicitud/razonRechazoSolicitudOtroOrigen.jsp

candidatosTramitesAdministrativos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
candidatosTramitesAdministrativos.url =candidatosTramitesAdministrativos

capturaDatosAdministrativos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturaDatosAdministrativos.url =capturaDatosAdministrativos

candidatosAcuerdoPadres.(class)=org.springframework.web.servlet.view.tiles2.TilesView
candidatosAcuerdoPadres.url =candidatosAcuerdoPadres

capturaAcuerdo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturaAcuerdo.url =capturaAcuerdo
