//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.gestion.asegurado.integracion;

import java.math.BigDecimal;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.domicilio.Subdelegacion;

public class UMFSimple extends AbstractModel {

	private static final long serialVersionUID = 6880458108995275343L;

	private Long idUMF;
	private BigDecimal noEconomico;
	private Subdelegacion subdelegacion;

	public Long getIdUMF() {
		return idUMF;
	}

	public void setIdUMF(Long idUMF) {
		this.idUMF = idUMF;
	}

	public BigDecimal getNoEconomico() {
		return noEconomico;
	}

	public void setNoEconomico(BigDecimal noEconomico) {
		this.noEconomico = noEconomico;
	}

	public Subdelegacion getSubdelegacion() {
		return subdelegacion;
	}

	public void setSubdelegacion(Subdelegacion subdelegacion) {
		this.subdelegacion = subdelegacion;
	}

}
