#CONFIGURACIONES IVRO SEGURO DOMESTICO Y SEGURO PERSONAL
ruta_reportes = /reports/
reporte_cuest_main=reportMain.jasper
reporte_cuest_ivro = ReporteIvroCuestionario.jasper
sub_reporte_cuest_ivro = ReporteIvroCuestionario_subreport1.jasper
sub_reporte2_cuest_ivro = ReporteIvroCuestionario_subreport2.jasper

ruta_logo_imss = /images/IMSS.png

#Mensaje de exito de guardado solicitud ivro personal
label_ivro_success_saved_begin=<p>Su solicitud de compra ha sido registrada. El folio de la operaci\u00f3n es:
label_ivro_success_saved_end = . Puede imprimir su comprobante desde la lista de acciones en la parte inferior de esta pantalla. </p> <p>Le recordamos que para activar su seguro debe imprimir sus l\u00edneas de captura y realizar  el pago correspondiente.</p> <p> Debe imprimir  sus l\u00edneas de captura en la secci\u00f3n "Seguros Personales" mediante la opci\u00f3n "Detalle",  en esta misma opci\u00f3n podr\u00e1; realizar la  impresi\u00f3n de su comprobante si as\u00ed lo requiere.</p><p>Debe imprimir Cuestionario M\u00e9dico para presentar en la UMF.</p><p>Para que el IMSS est\u00e9 en contacto con usted, es necesario que tenga registrada una direcci\u00f3n de correo electr\u00f3nico, si no cuenta con una ingrese a la secci\u00f3n de Datos Personales y actualice sus Medios de Contacto</p>