package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.ClasificacionObraDTO;

/**
 * RocTipoObra generated by hbm2java
 */
@Entity
@Table(name = "ROC_CLASIFICACION_OBRA", schema = "MGPROC01")
@Transactional
public class RocClasificacionObra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4943022634302990066L;
	
	private Long cveClasificacionObra;
	private String desClasificacionObra;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocClasificacionObra() {
	}

	public RocClasificacionObra(Long cveClasificacionObra) {
		this.cveClasificacionObra = cveClasificacionObra;
	}

	public RocClasificacionObra(Long cveClasificacionObra, String desClasificacionObra, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveClasificacionObra = cveClasificacionObra;
		this.desClasificacionObra = desClasificacionObra;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;		
	}

	@Id
	@Column(name = "CVE_ID_CLASIFICACION_OBRA", unique = true, nullable = false)
	public Long getCveClasificacionObra() {
		return this.cveClasificacionObra;
	}

	public void setCveClasificacionObra(Long cveClasificacionObra) {
		this.cveClasificacionObra = cveClasificacionObra;
	}

	@Column(name = "DES_CLASIFICACION_OBRA", length = 80)
	public String getDesClasificacionObra() {
		return this.desClasificacionObra;
	}

	public void setDesClasificacionObra(String desClasificacionObra) {
		this.desClasificacionObra = desClasificacionObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	
	public ClasificacionObraDTO toConvertClasificacionObraDTO(){
		ClasificacionObraDTO clasificacionObraDTO = new ClasificacionObraDTO();
		
		clasificacionObraDTO.setCveClasificacionObra(this.getCveClasificacionObra());
		clasificacionObraDTO.setDesClasificacionObra(this.getDesClasificacionObra());

		return clasificacionObraDTO;
	}

}
