package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.CalendarioReporteDTO;

/**
 * RocCalendarioReporte generated by hbm2java
 */
@Entity
@Table(name = "ROC_CALENDARIO_REPORTE", schema = "MGPROC01")
@Transactional
public class RocCalendarioReporte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8298994502882899477L;
	private Long cveCalendarioRep;
	private Long cveBimCalendario;
	private Date fecIniPerDeclarado;
	private Date fecFinPerDeclarado;
	private Date fecIniPerPresentado;
	private Date fecFinPerPresentado;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;	
	

	public RocCalendarioReporte() {
	}

	public RocCalendarioReporte(Long cveCalendarioRep) {
		this.cveCalendarioRep = cveCalendarioRep;
	}

	
	public RocCalendarioReporte(Long cveCalendarioRep, Long cveBimCalendario, Date fecIniPerDeclarado,
			Date fecFinPerDeclarado, Date fecIniPerPresentado, Date fecFinPerPresentado,Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {
		this.cveCalendarioRep = cveCalendarioRep;
		this.cveBimCalendario = cveBimCalendario;
		this.fecIniPerDeclarado = fecIniPerDeclarado;
		this.fecFinPerDeclarado = fecFinPerDeclarado;
		this.fecIniPerPresentado = fecIniPerPresentado;
		this.fecFinPerPresentado = fecFinPerPresentado;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;		

	}
	
	
	@Id

	@Column(name = "CVE_ID_CALENDARIO_REP", unique = true, nullable = false)
	public Long getCveCalendarioRep() {
		return this.cveCalendarioRep;
	}

	public void setCveCalendarioRep(Long cveCalendarioRep) {
		this.cveCalendarioRep = cveCalendarioRep;
	}

	@Column(name = "CVE_BIM_CALENDARIO")
	public Long getCveBimCalendario() {
		return this.cveBimCalendario;
	}

	public void setCveBimCalendario(Long cveBimCalendario) {
		this.cveBimCalendario = cveBimCalendario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INI_PER_DECLARADO", length = 13)
	public Date getFecIniPerDeclarado() {
		return this.fecIniPerDeclarado;
	}

	public void setFecIniPerDeclarado(Date fecIniPerDeclarado) {
		this.fecIniPerDeclarado = fecIniPerDeclarado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_PER_DECLARADO", length = 13)
	public Date getFecFinPerDeclarado() {
		return this.fecFinPerDeclarado;
	}

	public void setFecFinPerDeclarado(Date fecFinPerDeclarado) {
		this.fecFinPerDeclarado = fecFinPerDeclarado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INI_PER_PRESENTADO", length = 13)
	public Date getFecIniPerPresentado() {
		return this.fecIniPerPresentado;
	}

	public void setFecIniPerPresentado(Date fecIniPerPresentado) {
		this.fecIniPerPresentado = fecIniPerPresentado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_PER_PRESENTADO", length = 13)
	public Date getFecFinPerPresentado() {
		return this.fecFinPerPresentado;
	}

	public void setFecFinPerPresentado(Date fecFinPerPresentado) {
		this.fecFinPerPresentado = fecFinPerPresentado;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	
	public CalendarioReporteDTO toConvertCalendarioReporteDTO(){
		
		CalendarioReporteDTO calendarioReporteDTO = new CalendarioReporteDTO();
		
		calendarioReporteDTO.setCveBimCalendario(this.cveBimCalendario);
		calendarioReporteDTO.setCveCalendarioRep(this.cveCalendarioRep);
		calendarioReporteDTO.setFecFinPerDeclarado(this.fecFinPerDeclarado);
		calendarioReporteDTO.setFecFinPerPresentado(this.fecFinPerPresentado);
		calendarioReporteDTO.setFecIniPerDeclarado(this.fecIniPerDeclarado);
		calendarioReporteDTO.setFecIniPerPresentado(this.fecIniPerPresentado);
				
		return calendarioReporteDTO;
	}


}
