package mx.gob.imss.csdiss.sdroc.entity;
// default package

// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.TipoPatronDTO;

/**
 * RocTipoPatron generated by hbm2java
 */
@Entity
@Table(name = "ROC_TIPO_PATRON", schema = "MGPROC01")
@Transactional
public class RocTipoPatron implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4584312816920071373L;
	
	private Long cveTipoPatron;
	private String desTipoPatron;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocTipoPatron() {
	}

	public RocTipoPatron(Long cveTipoPatron) {
		this.cveTipoPatron = cveTipoPatron;
	}

	public RocTipoPatron(Long cveTipoPatron, String desTipoPatron, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveTipoPatron = cveTipoPatron;
		this.desTipoPatron = desTipoPatron;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id

	@Column(name = "CVE_ID_TIPO_PATRON", unique = true, nullable = false)
	public Long getCveTipoPatron() {
		return this.cveTipoPatron;
	}

	public void setCveTipoPatron(Long cveTipoPatron) {
		this.cveTipoPatron = cveTipoPatron;
	}

	@Column(name = "DES_TIPO_PATRON", length = 80)
	public String getDesTipoPatron() {
		return this.desTipoPatron;
	}

	public void setDesTipoPatron(String desTipoPatron) {
		this.desTipoPatron = desTipoPatron;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	public TipoPatronDTO toConvertTipoPatronDTO(){
		TipoPatronDTO tipoPatronDTO = new TipoPatronDTO();
		
		tipoPatronDTO.setCveTipoPatron(this.getCveTipoPatron());
		tipoPatronDTO.setDesTipoPatron(this.getDesTipoPatron());

		return tipoPatronDTO;
	}

}
