package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.TipoPersonaDTO;

/**
 * RocTipoPersona generated by hbm2java
 */
@Entity
@Table(name = "ROC_TIPO_PERSONA", schema = "MGPROC01")
@Transactional
public class RocTipoPersona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7980424119501794260L;
	private Long cveTipoPersona;
	private String desTipoPersona;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocTipoPersona() {
	}

	public RocTipoPersona(Long cveTipoPersona) {
		this.cveTipoPersona = cveTipoPersona;
	}

		public RocTipoPersona(Long cveTipoPersona, String desTipoPersona, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado ) {
		
		this.cveTipoPersona = cveTipoPersona;
		this.desTipoPersona = desTipoPersona;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id

	@Column(name = "CVE_ID_TIPO_PERSONA", unique = true, nullable = false)
	public Long getCveTipoPersona() {
		return this.cveTipoPersona;
	}

	public void setCveTipoPersona(Long cveTipoPersona) {
		this.cveTipoPersona = cveTipoPersona;
	}

	@Column(name = "DES_TIPO_PERSONA", length = 80)
	public String getDesTipoPersona() {
		return this.desTipoPersona;
	}

	public void setDesTipoPersona(String desTipoPersona) {
		this.desTipoPersona = desTipoPersona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	public TipoPersonaDTO toConvertTipoPersonaDTO(){
		
		TipoPersonaDTO tipoPersonaDTO = new TipoPersonaDTO();
		
		tipoPersonaDTO.setCveTipoPersona(this.getCveTipoPersona());
		tipoPersonaDTO.setDesTipoPersona(this.getDesTipoPersona());

		
		return tipoPersonaDTO;
	}

}
