home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

#GENERALES 
error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

#PORTLETS
totalPorOrigenInit.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenInit.url=/WEB-INF/views/portlet/graficas/totalPorOrigen/inicial.jsp
totalPorOrigenContenido.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenContenido.url=/WEB-INF/views/portlet/graficas/totalPorOrigen/contenido.jsp

totalPorOrigenTipoMovimientoInit.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenTipoMovimientoInit.url=/WEB-INF/views/portlet/graficas/totalPorOrigenTipoMovimiento/inicial.jsp
totalPorOrigenTipoMovimientoContenido.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenTipoMovimientoContenido.url=/WEB-INF/views/portlet/graficas/totalPorOrigenTipoMovimiento/contenido.jsp

totalPorOrigenAsignacionFechaInit.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenAsignacionFechaInit.url=/WEB-INF/views/portlet/graficas/totalPorOrigenFecha/asignacion/inicial.jsp
totalPorOrigenAsignacionFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenAsignacionFechaContenido.url=/WEB-INF/views/portlet/graficas/totalPorOrigenFecha/asignacion/contenido.jsp

totalPorOrigenAltaPatFechaInit.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenAltaPatFechaInit.url=/WEB-INF/views/portlet/graficas/totalPorOrigenFecha/altaPatronal/inicial.jsp
totalPorOrigenAltaPatFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenAltaPatFechaContenido.url=/WEB-INF/views/portlet/graficas/totalPorOrigenFecha/altaPatronal/contenido.jsp

totalPorOrigenTipoMovimientoFechaInit.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenTipoMovimientoFechaInit.url=/WEB-INF/views/portlet/graficas/totalPorOrigenTipoMovimientoFecha/inicial.jsp
totalPorOrigenTipoMovimientoFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
totalPorOrigenTipoMovimientoFechaContenido.url=/WEB-INF/views/portlet/graficas/totalPorOrigenTipoMovimientoFecha/contenido.jsp

edoAdeudoTotalTipoFechaInit.(class)=org.springframework.web.servlet.view.JstlView
edoAdeudoTotalTipoFechaInit.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoFecha/edoAdeudo/inicial.jsp
edoAdeudoTotalTipoFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
edoAdeudoTotalTipoFechaContenido.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoFecha/edoAdeudo/contenido.jsp

movPatronesTotalTipoFechaInit.(class)=org.springframework.web.servlet.view.JstlView
movPatronesTotalTipoFechaInit.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoFecha/movPatrones/inicial.jsp
movPatronesTotalTipoFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
movPatronesTotalTipoFechaContenido.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoFecha/movPatrones/contenido.jsp

movCorreccionTotalTipoFechaInit.(class)=org.springframework.web.servlet.view.JstlView
movCorreccionTotalTipoFechaInit.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoFecha/movCorreccion/inicial.jsp
movCorreccionTotalTipoFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
movCorreccionTotalTipoFechaContenido.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoFecha/movCorreccion/contenido.jsp

movRegistroUsuarioTotalFechaInit.(class)=org.springframework.web.servlet.view.JstlView
movRegistroUsuarioTotalFechaInit.url=/WEB-INF/views/portlet/graficas/totalPorFechaRegistroUsuario/inicial.jsp
movRegistroUsuarioTotalFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
movRegistroUsuarioTotalFechaContenido.url=/WEB-INF/views/portlet/graficas/totalPorFechaRegistroUsuario/contenido.jsp

solRissTotalFechaEstadoInit.(class)=org.springframework.web.servlet.view.JstlView
solRissTotalFechaEstadoInit.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoEstadoFecha/riss/inicial.jsp
solRissTotalFechaEstadoContenido.(class)=org.springframework.web.servlet.view.JstlView
solRissTotalFechaEstadoContenido.url=/WEB-INF/views/portlet/graficas/totalTipoMovimientoEstadoFecha/riss/contenido.jsp

movImpresionCfdiTotalFechaInit.(class)=org.springframework.web.servlet.view.JstlView
movImpresionCfdiTotalFechaInit.url=/WEB-INF/views/portlet/graficas/totalPorFechaImpresionCfdi/inicial.jsp
movImpresionCfdiTotalFechaContenido.(class)=org.springframework.web.servlet.view.JstlView
movImpresionCfdiTotalFechaContenido.url=/WEB-INF/views/portlet/graficas/totalPorFechaImpresionCfdi/contenido.jsp

totalUsuariosSipareInit.(class)=org.springframework.web.servlet.view.JstlView
totalUsuariosSipareInit.url=/WEB-INF/views/portlet/graficas/totalPorFecha/sipare/usuarios/inicial.jsp
totalUsuariosSipareContenido.(class)=org.springframework.web.servlet.view.JstlView
totalUsuariosSipareContenido.url=/WEB-INF/views/portlet/graficas/totalPorFecha/sipare/usuarios/contenido.jsp

dashboard.home.(class)=org.springframework.web.servlet.view.JstlView
dashboard.home.url=/WEB-INF/views/dashboard/index.jsp
