package mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio;

import java.io.Serializable;

public enum DocumentoEnum implements Serializable{
	
	ACTA_NACIMIENTO(1),
	ACTA_MATRIMONIO(2),
	DOC_ACTA_RECONOCIMIENTO(3),
	ACTA_ADOPCION(4),
	ACTA_MATRIMONIO_DICTAMEN_DIS(5),
	ACTA_CONSTITUTIVA(6),
	ESTADO_CUENTA_BANCARIO(7),
	CONTRATO_ARRENDAMIENTO(8),
	RECIBO_TELEVISION(9),
	PAGO_TENENCIA_VEHICULAR(10),
	RECIBO_GAS(11),
	RECIBO_LUZ(12),
	RECIBO_TELEFONO(13),
	ESCRITURA_PROPIEDAD_INMOBILIARIA(14),
	RECIBO_AGUA(15),
	PAGO_PREDIAL(16),
	DOC_ACUERDO ( 17),
	VIGENCIA_TEMPORAL ( 18 ),
	CONSTANCIA_ESTUDIOS ( 19),
	DOC_OBSTETRICO ( 20),
	CERTIFICADO_SIT_CRITICA ( 21),
	LAUDO ( 22),
	DICTAMEN_INCAPACITADO( 23),
	CERTIFICADO_NACIMIENTO ( 24),
	DOCUMENTO_MIGRATORIO ( 28),
	CURP ( 34),
	CEDULA_PROFESIONAL ( 35),
	CREDENCIAL_ELECTOR ( 36),
	CARTILLA_MILITAR ( 37),
	PASAPORTE ( 38),
	ACTA_DIVORCIO ( 40),
	ACTA_DEFUNCION ( 41),
	PENSION ( 42),
	ADIMSS ( 46),
	IDENTIDAD_EXTRANJEROS ( 47),
	AVISOS_AFILIATORIOS ( 176),
	MATRICULA_CONSULAR ( 130),
	CEDULA_IDENTIDAD_PERSONAL ( 134),
	COMPROBANTES_DE_PAGO ( 148),
	CUENTA_AFORE ( 149),
	//Comprobante Asignacion NSS
	TARJETA_AFILIACION ( 177),
	CONSTANCIA_TRAMITE (169),
	CITAS_MEDICAS ( 170),
	CERTIFICADO_DE_INCAPACIDAD ( 178),
	CREDENCIAL_ADIMSS ( 179),
	LIQUIDACIONES_PAGADAS ( 171),
	CARTA_RENUNCIA ( 172),
	PODER_NOTARIAL(174),
	FORMATO_SOLICITUD_CDA(175),
	CONSTANCIA_CONCUBINATO(180),
	ACTA_CERTIFICADA_DEFUNCION ( 167),
	OTROS ( 173);
	
	private int id;
	
	private DocumentoEnum(int id) {
		this.id=id;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
}
