service.provider.url=${mvn.web.app.service.provider.url}
service.security.principal=${mvn.web.app.service.security.principal}
service.security.credentials=${mvn.web.app.service.security.credentials}

service.ws.osb.url=${mvn.web.app.service.ws.osb.url}

#WebService para consulta de vigencia gestionSegurosVoluntarios
ws.consulta.estatus.vigencia.ivro.url = ${mvn.ws.consulta.estatus.vigencia.ivro.url}
ws.consulta.estatus.vigencia.ssf.url = ${mvn.ws.consulta.estatus.vigencia.ssf.url}
ws.consulta.estatus.vigencia.cvro.url = ${mvn.ws.consulta.estatus.vigencia.cvro.url}
ws.consulta.request.timeout = 20000
ws.consulta.connect.timeout = 20000