
package mx.gob.imss.ctirss.gestionpersonas.servicios.hlda.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsHldaService", targetNamespace = "http://mx/gob/imss/ws/hlda/ws", wsdlLocation = "http://11.254.172.131:9100/WsHlda/WsHlda?wsdl")
public class WsHldaService
    extends Service
{

    private final static URL WSHLDASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.ctirss.gestionpersonas.servicios.hlda.wsclient.WsHldaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.gob.imss.ctirss.gestionpersonas.servicios.hlda.wsclient.WsHldaService.class.getResource(".");
            url = new URL(baseUrl, "http://11.254.172.131:9100/WsHlda/WsHlda?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://11.254.172.131:9100/WsHlda/WsHlda?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSHLDASERVICE_WSDL_LOCATION = url;
    }

    public WsHldaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsHldaService() {
        super(WSHLDASERVICE_WSDL_LOCATION, new QName("http://mx/gob/imss/ws/hlda/ws", "WsHldaService"));
    }

    /**
     * 
     * @return
     *     returns WsHlda
     */
    @WebEndpoint(name = "WsHldaSoapPort")
    public WsHlda getWsHldaSoapPort() {
        return super.getPort(new QName("http://mx/gob/imss/ws/hlda/ws", "WsHldaSoapPort"), WsHlda.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsHlda
     */
    @WebEndpoint(name = "WsHldaSoapPort")
    public WsHlda getWsHldaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx/gob/imss/ws/hlda/ws", "WsHldaSoapPort"), WsHlda.class, features);
    }

}
