########## STAGE ##########
servicio.registropatronal=${mvn.registro.patronal.webservice.url}
servicio.cuentaindividual.documento.wsdl=${mvn.cuentaindividual.documento.wsdl}
servicio.cuentaindivhistorico.documento.wsdl=${mvn.cuentaindivhistorico.documento.wsdl}
common.connect.timeout=30000
common.request.timeout=30000




