package mx.gob.imss.csdiss.sdroc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

/**
 * RocSubdelegacion generated by hbm2java
 */
@Entity
@Table(name = "DIT_LLAVE_PATRON")
@Transactional
public class DitLlavePatron implements java.io.Serializable {

	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -4167398815056557406L;
	private Long cveIdPatronSujetoObligado;
	private Long cveIdPatronGeneral;
	private Long cveIdPersonaMoral;	
	private Long cveIdPersonaFisica;
	private Long cveIdPersona;
	private Long tipPersona;
	private String refBusca;

	public DitLlavePatron() {
	}


	
	
	public DitLlavePatron(Long cveIdPatronSujetoObligado, Long cveIdPatronGeneral, Long cveIdPersonaMoral,
			Long cveIdPersonaFisica, Long cveIdPersona, Long tipPersona, String refBusca) {

		this.cveIdPatronSujetoObligado = cveIdPatronSujetoObligado;
		this.cveIdPatronGeneral = cveIdPatronGeneral;
		this.cveIdPersonaMoral = cveIdPersonaMoral;
		this.cveIdPersonaFisica = cveIdPersonaFisica;
		this.cveIdPersona = cveIdPersona;
		this.tipPersona = tipPersona;
		this.refBusca = refBusca;
	}




	public DitLlavePatron(Long cveIdPatronSujetoObligado) {
		this.cveIdPatronSujetoObligado = cveIdPatronSujetoObligado;
	}
	

	@Id
	@Column(name = "CVE_ID_PATRON_SUJETO_OBLIGADO", unique = true, nullable = false)
	public Long getCveIdPatronSujetoObligado() {
		return cveIdPatronSujetoObligado;
	}

	public void setCveIdPatronSujetoObligado(Long cveIdPatronSujetoObligado) {
		this.cveIdPatronSujetoObligado = cveIdPatronSujetoObligado;
	}

	@Column(name = "CVE_ID_PATRON_GENERAL")
	public Long getCveIdPatronGeneral() {
		return cveIdPatronGeneral;
	}

	public void setCveIdPatronGeneral(Long cveIdPatronGeneral) {
		this.cveIdPatronGeneral = cveIdPatronGeneral;
	}

	@Column(name = "CVE_ID_PERSONA_MORAL")	
	public Long getCveIdPersonaMoral() {
		return cveIdPersonaMoral;
	}

	public void setCveIdPersonaMoral(Long cveIdPersonaMoral) {
		this.cveIdPersonaMoral = cveIdPersonaMoral;
	}

	@Column(name = "CVE_ID_PERSONA_FISICA")	
	public Long getCveIdPersonaFisica() {
		return cveIdPersonaFisica;
	}

	public void setCveIdPersonaFisica(Long cveIdPersonaFisica) {
		this.cveIdPersonaFisica = cveIdPersonaFisica;
	}

	@Column(name = "CVE_ID_PERSONA")	
	public Long getCveIdPersona() {
		return cveIdPersona;
	}

	public void setCveIdPersona(Long cveIdPersona) {
		this.cveIdPersona = cveIdPersona;
	}

	@Column(name = "TIP_PERSONA")	
	public Long getTipPersona() {
		return tipPersona;
	}

	public void setTipPersona(Long tipPersona) {
		this.tipPersona = tipPersona;
	}

	@Column(name = "REF_BUSCA")
	public String getRefBusca() {
		return refBusca;
	}

	public void setRefBusca(String refBusca) {
		this.refBusca = refBusca;
	}
	
}
