package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.UbicacionObraDTO;

/**
 * RotUbicacionObra generated by hbm2java
 */
@Entity
@Table(name = "ROT_UBICACION_OBRA")
@Transactional
public class RotUbicacionObra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5183185610768866692L;
	
	private Long cveUbicacionObra;
	private String calle;
	private Integer numExterior;
	private String numExteriorAlf;
	private Integer numExteriorDos;
	private String numInteriorAlf;	
	private Integer numInterior;
	private String codigoPostal;
	private String refEntidad;
	private String refMunicipio;
	private String refColonia;
	private String refObservacion;
	private String refPosterior;
	private String refPrimaria;
	private String refSecundaria;
	private int cveEntidad;
	private int cveMunicipio;
	private int cveLocalidad;
	private Long domicilioId;

	public RotUbicacionObra() {
	}

	public RotUbicacionObra(Long cveUbicacionObra) {
		this.cveUbicacionObra = cveUbicacionObra;
	}

		
	public RotUbicacionObra(Long cveUbicacionObra, String calle,
			Integer numExterior, String numExteriorAlf, Integer numExteriorDos,String numInteriorAlf, Integer numInterior, String codigoPostal, String refEntidad, 
			String refMunicipio,String refColonia,String refObservacion,String refPosterior, String refPrimaria, String refSecundaria,
			int cveEntidad, int cveMunicipio, int cveLocalidad,Long domicilioId) {
		this.cveUbicacionObra = cveUbicacionObra;
		this.calle = calle;
		this.numExterior = numExterior;
		this.numExteriorAlf = numExteriorAlf;
		this.numExteriorDos = numExteriorDos;
		this.numInteriorAlf = numInteriorAlf;
		this.numInterior = numInterior;
		this.codigoPostal = codigoPostal;
		this.refEntidad = refEntidad;
		this.refMunicipio = refMunicipio;
		this.cveEntidad = cveEntidad;
		this.cveMunicipio = cveMunicipio;
		this.refColonia = refColonia;
		this.refObservacion = refObservacion;
		this.refPosterior = refPosterior;
		this.refPrimaria = refPrimaria;
		this.refSecundaria = refSecundaria;		
		this.domicilioId = domicilioId;

	}

	@Id
	@Column(name = "CVE_ID_UBICACION_OBRA", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_ubicacion_obra")
	@SequenceGenerator(name="seq_ubicacion_obra", schema="public", sequenceName="SEQ_ROTUBICACIONOBRA", allocationSize=1)	
	public Long getCveUbicacionObra() {
		return this.cveUbicacionObra;
	}

	public void setCveUbicacionObra(Long cveUbicacionObra) {
		this.cveUbicacionObra = cveUbicacionObra;
	}

	@Column(name = "CALLE", length = 100)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "NUM_EXTERIOR")
	public Integer getNumExterior() {
		return this.numExterior;
	}

	public void setNumExterior(Integer numExterior) {
		this.numExterior = numExterior;
	}
	
	@Column(name = "NUM_EXTERIOR_ALF")
	public String getNumExteriorAlf() {
		return this.numExteriorAlf;
	}

	public void setNumExteriorAlf(String numExteriorAlf) {
		this.numExteriorAlf = numExteriorAlf;
	}	

	@Column(name = "NUM_EXTERIOR_DOS")
	public Integer getNumExteriorDos() {
		return this.numExteriorDos;
	}

	public void setNumExteriorDos(Integer numExteriorDos) {
		this.numExteriorDos = numExteriorDos;
	}	
	
	@Column(name = "NUM_INTERIOR")
	public Integer getNumInterior() {
		return this.numInterior;
	}

	public void setNumInterior(Integer numInterior) {
		this.numInterior = numInterior;
	}

	@Column(name = "NUM_INTERIOR_ALF")
	public String getNumInteriorAlf() {
		return this.numInteriorAlf;
	}

	public void setNumInteriorAlf(String numInteriorAlf) {
		this.numInteriorAlf = numInteriorAlf;
	}	
	
	@Column(name = "CODIGO_POSTAL")
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "REF_ENTIDAD")
	public String getRefEntidad() {
		return this.refEntidad;
	}

	public void setRefEntidad(String refEntidad) {
		this.refEntidad = refEntidad;
	}

	@Column(name = "REF_MUNICIPIO")
	public String getRefMunicipio() {
		return this.refMunicipio;
	}

	public void setRefMunicipio(String refMunicipio) {
		this.refMunicipio = refMunicipio;
	}
	
	@Column(name = "REF_COLONIA")
	public String getRefColonia() {
		return this.refColonia;
	}

	public void setRefColonia(String refColonia) {
		this.refColonia = refColonia;
	}
	
	@Column(name = "REF_POSTERIOR")
	public String getRefPosterior() {
		return this.refPosterior;
	}

	public void setRefPosterior(String refPosterior) {
		this.refPosterior = refPosterior;
	}

	@Column(name = "REF_PRIMARIA")
	public String getRefPrimaria() {
		return this.refPrimaria;
	}

	public void setRefPrimaria(String refPrimaria) {
		this.refPrimaria = refPrimaria;
	}	

	@Column(name = "REF_SECUNDARIA")
	public String getRefSecundaria() {
		return this.refSecundaria;
	}

	public void setRefSecundaria(String refSecundaria) {
		this.refSecundaria = refSecundaria;
	}
	
	@Column(name = "REF_OBSERVACION")
	public String getRefObservacion() {
		return this.refObservacion;
	}

	public void setRefObservacion(String refObservacion) {
		this.refObservacion = refObservacion;
	}	
	
	@Column(name = "CVE_ENTIDAD")
	public int getCveEntidad() {
		return this.cveEntidad;
	}

	public void setCveEntidad(int cveEntidad) {
		this.cveEntidad = cveEntidad;
	}

	@Column(name = "CVE_MUNICIPIO")
	public int getCveMunicipio() {
		return this.cveMunicipio;
	}

	public void setCveMunicipio(int cveMunicipio) {
		this.cveMunicipio = cveMunicipio;
	}

	@Column(name = "CVE_LOCALIDAD")
	public int getCveLocalidad() {
		return this.cveLocalidad;
	}

	public void setCveLocalidad(int cveLocalidad) {
		this.cveLocalidad = cveLocalidad;
	}
		
	@Column(name = "DOMICILIO_ID")
	public Long getDomicilioId() {
		return domicilioId;
	}

	public void setDomicilioId(Long domicilioId) {
		this.domicilioId = domicilioId;
	}

	public UbicacionObraDTO toConvertUbicacionObraDTO(){
		
		UbicacionObraDTO ubicacionObraDTO = new UbicacionObraDTO();
		
		ubicacionObraDTO.setCalle(this.calle);
		ubicacionObraDTO.setCodigoPostal(this.codigoPostal);
		ubicacionObraDTO.setCveEntidad(this.cveEntidad);
		ubicacionObraDTO.setCveLocalidad(this.cveLocalidad);
		ubicacionObraDTO.setCveMunicipio(this.cveMunicipio);
		ubicacionObraDTO.setCveUbicacionObra(this.cveUbicacionObra);
		if(this.getNumExterior() != null)
			ubicacionObraDTO.setNumExterior(this.getNumExterior().toString());
		ubicacionObraDTO.setNumExteriorAlf(this.getNumExteriorAlf());
		if(this.getNumExteriorDos() != null)
		ubicacionObraDTO.setNumExteriorDos(this.getNumExteriorDos().toString());
		ubicacionObraDTO.setNumInteriorAlf(this.getNumInteriorAlf());
		if(this.getNumInterior() != null)
			ubicacionObraDTO.setNumInterior(this.getNumInterior().toString());
		ubicacionObraDTO.setRefEntidad(this.refEntidad);
		ubicacionObraDTO.setRefMunicipio(this.refMunicipio);
		ubicacionObraDTO.setRefColonia(this.getRefColonia());
		ubicacionObraDTO.setRefObservacion(this.getRefObservacion());
		ubicacionObraDTO.setRefPosterior(this.getRefPosterior());
		ubicacionObraDTO.setRefPrimaria(this.getRefPrimaria());
		ubicacionObraDTO.setRefSecundaria(this.getRefSecundaria());

		return ubicacionObraDTO;
		
	}

}