//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//

package mx.gob.imss.ctirss.delta.model.derechohabiente;

import java.io.Serializable;
import java.math.BigInteger;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Fisica;
import mx.gob.imss.ctirss.delta.model.gestion.solicitud.PersonaInteresadaSolicitud;
import mx.gob.imss.ctirss.delta.model.gestion.tramite.Tramite;
import mx.gob.imss.ctirss.delta.model.gestion.tramite.TramiteRegistroDerechohabiente;

public class RespuestaCuestionario  extends AbstractModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Pregunta pregunta;
	protected Fisica persona;
	protected Long cveIdCuestionario;
	protected TramiteRegistroDerechohabiente registroDerechohabiente;
	protected Respuesta respuestaPrimerpersona;
	protected Respuesta respuestaTerceraPersona;
	protected PersonaInteresadaSolicitud personaInteresadaSol;
	protected Integer valorRespuesta;
	protected Tramite tramite;
	
	/**
	 * Gets the value of the pregunta property.
	 * 
	 * @return possible object is {@link Pregunta }
	 * 
	 */
	public Pregunta getPregunta() {
		return pregunta;
	}

	/**
	 * Sets the value of the pregunta property.
	 * 
	 * @param value
	 *            allowed object is {@link Pregunta }
	 * 
	 */
	public void setPregunta(Pregunta value) {
		this.pregunta = value;
	}

	/**
	 * Gets the value of the persona property.
	 * 
	 * @return possible object is {@link Fisica }
	 * 
	 */
	public Fisica getPersona() {
		return persona;
	}

	/**
	 * Sets the value of the persona property.
	 * 
	 * @param value
	 *            allowed object is {@link Fisica }
	 * 
	 */
	public void setPersona(Fisica value) {
		this.persona = value;
	}

	/**
	 * Gets the value of the valorRespuesta property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public Integer getValorRespuesta() {
		return valorRespuesta;
	}

	public TramiteRegistroDerechohabiente getRegistroDerechohabiente() {
		return registroDerechohabiente;
	}

	public void setRegistroDerechohabiente(
			TramiteRegistroDerechohabiente registroDerechohabiente) {
		this.registroDerechohabiente = registroDerechohabiente;
	}

	public Respuesta getRespuestaPrimerpersona() {
		return respuestaPrimerpersona;
	}

	public void setRespuestaPrimerpersona(Respuesta respuestaPrimerpersona) {
		this.respuestaPrimerpersona = respuestaPrimerpersona;
	}

	public Respuesta getRespuestaTerceraPersona() {
		return respuestaTerceraPersona;
	}

	public void setRespuestaTerceraPersona(Respuesta respuestaTerceraPersona) {
		this.respuestaTerceraPersona = respuestaTerceraPersona;
	}

	/**
	 * Sets the value of the valorRespuesta property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setValorRespuesta(Integer value) {
		this.valorRespuesta = value;
	}

	public PersonaInteresadaSolicitud getPersonaInteresadaSol() {
		return personaInteresadaSol;
	}

	public void setPersonaInteresadaSol(
			PersonaInteresadaSolicitud personaInteresadaSol) {
		this.personaInteresadaSol = personaInteresadaSol;
	}

	public Long getCveIdCuestionario() {
		return cveIdCuestionario;
	}

	public void setCveIdCuestionario(Long cveIdCuestionario) {
		this.cveIdCuestionario = cveIdCuestionario;
	}

	public Tramite getTramite() {
		return tramite;
	}

	public void setTramite(Tramite tramite) {
		this.tramite = tramite;
	}

}
