package mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio;

/**
 * 
 * Enum que representa la tabla DIT_DOCUMENTO_POR_TIPO,
 * sólo contiene la columna CVE_ID_DOCTO_PROB_POR_TIPO
 * 
 * @author Marco Sánchez
 *
 */
public enum DocumentoPorTipoEnum {

	ACTA_NACIMIENTO(17L),
	CARTA_NATURALIZACION(49L),
	DOCUMENTO_MIGRATORIO(50L),
	NUMERO_UNICO_EXTRANJERO(51L),
	CERTIFICADO_NACIONALIDAD_MEXICANA(52L),
	OFICIO_SOLICITANTE_REFUGIADO(53L),
	FORMA_MIGRATORIA_TURISTA(54L),
	TIP(55L),
	ARP(56L),
	AVISO_DE_MODIFICACION(57L),
	CARTA_TERMINOS_FIEL(58L),
	COMPROBANTE_ASIGNACION(59L),
	COMPROBANTE_LOCALIZACION_NSS(69L),
	COMPROBANTE_ALTA_BENEFICIO_RISS(70L),
	COMPROBANTE_VIGENCIA_DERECHOS(71L),
	SAV005(29L),
	SAV007(30L),
	SAV008(31L),
	SAV011(32L),
	SAV017(33L),
	CARTILLA(73L),
	D_4305A(76L),
	SAV002(75L),
	ACUSE_TRAMITE(74L),
	COMPROBANTE_IVRO(85L),
	CREDENCIAL_FM2(93L),
	CREDENCIAL_FM3(94L),
	COMPROBANTE_SEGURO_FAMILIAR(129L),
	COMPROBANTE_CVRO(130L),
	COMPROBANTE_ASIGNACION_SIMPLE_QR(131L),
	CONSTANCIA_TRAMIE_ADMIN(138L),
	AVISOS_AFILIATORIOS(149L),
	COMPROBANTE_RENOVACION_IVRO(154L),
	COMPROBANTE_RENOVACION_SSF(155L),
	COMPROBANTE_RENOVACION_CVRO(156L),
	COMPROBANTE_DE_CORRECCION_DATOS_ASEGURADO(157L),
	ACUSE_ACTUALIIZACION_CORREO_ELECTRONICO(194L),
	OTROS(159L);
	
	
	private DocumentoPorTipoEnum(Long id) {
		this.id = id;
	}

	private Long id;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}
	
	
	
}
