package mx.gob.imss.ctirss.delta.model.enums;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;


public enum TipoSolicitudEnum implements Serializable{
	
	REGISTRO(1),
	REGISTRO_DE_DERECHOHABIENTES(1),
	PRORROGA(2),
	CORRECCION(3),
	CORRECCION_DATOS_DERECHOHABIENTE(3),
	BAJA(4),
	BAJA_DERECHOHABIENTES(4),
	CAMBIO_MASIVO(5),
	CAMBIO_MASIVO_DE_CLINICA(5),
	ACTUALIZACION_DATOS_GENERALES(6),
	ACTUALIZACION_RAZON_DENOMINACION_SOCIAL(7),
	ACTUALIZACION_REGISTRO_SINDICATO(9),
	ACTUALIZACION_ESCRITURA_CONSTITUTIVA(10),
	ACTUALIZACION_DE_CLASIFICACION(11),
	ACTUALIZACION_DE_SOCIO(12),
	ACTUALIZACION_DE_REPRESENTANTE_LEGAL(13),
	ACTUALIZACION_DATOS_PATRONALES(6),
	ACTUALIZACION_CENTRO_TRABAJO(14),
	ALTA_PATRONAL(15),
	BAJA_PATRONAL(16),
	ASIGNACION_NSS(17),
	REGISTRO_USUARIOS_SSO(18),
	IMPRESION_EDO_ADEUDO(7),
	IMPRESION_DE_SEMANAS_COTIZADAS(19),
	INCORPORACION_BENEFICIO(20),
	REGISTRO_PERSONA(21),
	IMPRESION_DE_DOCUMENTO_DERECHOHABIENTE(22),
	COMPROBANTE_DE_VIGENCIA_DE_DERECHOS(23),
	CORRECCION_PATRONAL(24),
	IMPRESION_COMPROBANTE_FISCAL(25),
	CARTA_NO_ADEUDO(32),
	COMPRA_SEGURO(33),
	SOLICITUD_PENSION(35),
	INCORPORACION_SEGURO_FAMILIAR(36),
    CONTINUACION_VOLUNTARIA_REGIMEN_OBLIGATORIO(37),
    BAJA_ADMINISTRATIVA(45),
    SUSPENCION_ADMINISTRATIVA(46),
    REACTIVACION_ADMINISTRATIVA(47),
    CONSULTA_RIESGOS_TRABAJO_TERMINADOS(49),
    CORRECCION_DATOS_ASEGURADO(50),
    PAGOS_MOVIMIENTOS_AFILIATORIOS(51),
    SIMPLIFICACION_PROCESO_PRESTACIONES_MATERNIDAD(52),
    COMPARA_TUS_DATOS(53),
    REGISTRO_ACUERDO_DERECHOHABIENTES(58),
	SOLICITUD_DERECHOS_ARCO(64),
	SOLICITUD_DE_PORTABILIDAD_ISSSTE_IMSS(68),
	TODAS(-1);
	
	private final static Map<Integer,TipoSolicitudEnum> hashCodes = new HashMap<Integer,TipoSolicitudEnum>();
	
	static{ 
		for(TipoSolicitudEnum solicitud : TipoSolicitudEnum.values()){
			hashCodes.put(solicitud.getValor(), solicitud);
		}
	}
	
	
	private long id;
	
	private TipoSolicitudEnum(long id) {
		// TODO Auto-generated constructor stub
		this.id=id;
	}
	
	public long getId(){
		return this.id;
	}
	
	public Integer getValor() {
		return Integer.valueOf(Long.toString(this.id));
	}
	
}
