
package mx.gob.imss.macii.ws;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.core.io.Resource;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSClasificacionMACIIService", targetNamespace = "http://ws.macii.imss.gob.mx/", wsdlLocation = "classpath:WSClasificacionMACII.wsdl")
public class WSClasificacionMACIIService
    extends Service
{

    private final static URL WSCLASIFICACIONMACIISERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCLASIFICACIONMACIISERVICE_EXCEPTION;
    private final static Logger logger = Logger.getLogger(WSClasificacionMACIIService.class.getName());
    private final static QName WSCLASIFICACIONMACIISERVICE_QNAME = new QName("http://ws.macii.imss.gob.mx/", "WSClasificacionMACIIService");
    private static DefaultResourceLoader loader= new DefaultResourceLoader(); 
    private static Resource resource = loader.getResource("classpath:WSClasificacionMACII.wsdl"); 

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = resource.getURL();
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (IOException ioe) {
            logger.warning(ioe.getMessage());
            ioe.printStackTrace();
        }
        WSCLASIFICACIONMACIISERVICE_WSDL_LOCATION = url;
        WSCLASIFICACIONMACIISERVICE_EXCEPTION = e;
    }
    
    public String getURLWS() {
    	return WSCLASIFICACIONMACIISERVICE_WSDL_LOCATION.getProtocol() + "" + WSCLASIFICACIONMACIISERVICE_WSDL_LOCATION.getHost() + " " + WSCLASIFICACIONMACIISERVICE_WSDL_LOCATION.getPort();
    }

    public WSClasificacionMACIIService() {
        super(__getWsdlLocation(), WSCLASIFICACIONMACIISERVICE_QNAME);
    }

    public WSClasificacionMACIIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCLASIFICACIONMACIISERVICE_QNAME, features);
    }

    public WSClasificacionMACIIService(URL wsdlLocation) {
        super(wsdlLocation, WSCLASIFICACIONMACIISERVICE_QNAME);
    }

    public WSClasificacionMACIIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCLASIFICACIONMACIISERVICE_QNAME, features);
    }

    public WSClasificacionMACIIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSClasificacionMACIIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSClasificacionMACII
     */
    @WebEndpoint(name = "WSClasificacionMACIIPort")
    public WSClasificacionMACII getWSClasificacionMACIIPort() {
        return super.getPort(new QName("http://ws.macii.imss.gob.mx/", "WSClasificacionMACIIPort"), WSClasificacionMACII.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSClasificacionMACII
     */
    @WebEndpoint(name = "WSClasificacionMACIIPort")
    public WSClasificacionMACII getWSClasificacionMACIIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.macii.imss.gob.mx/", "WSClasificacionMACIIPort"), WSClasificacionMACII.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCLASIFICACIONMACIISERVICE_EXCEPTION!= null) {
            throw WSCLASIFICACIONMACIISERVICE_EXCEPTION;
        }
        return WSCLASIFICACIONMACIISERVICE_WSDL_LOCATION;
    }

}
