# FileConfig
filesystem.input.url=asegurado/input
filesystem.output.url=asegurado/output

# Servidor ftp
ftp.server.url=vzapmb03.imss.gob.mx
ftp.server.user=ftp_delta
ftp.server.passwd=ftp0d3lt1.
ftp.server.port=21
