#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp

#Tiles redirect

portal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
portal.url=portal

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

#===== Portales ====== 
home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

personaRepresentadaPortal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
personaRepresentadaPortal.url=personaRepresentadaPortal

patronPortal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
patronPortal.url=patronPortal

#===== Generales ====== 
error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

domicilio.registro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registro.url=domicilioRegistro

domicilio.registroEmbebido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registroEmbebido.url=domicilioRegistroEmbebed

tramite.inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.inicio.url=tramiteinicio

tramite.capturar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.capturar.url=tramitecapturar

testPatronal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
testPatronal.url=testPatronal

#===== WIDGETS ====== 
widgetPersonaFisicaInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaFisicaInit.url=/WEB-INF/views/widget/persona/fisica/inicial.jsp
widgetPersonaFisicaContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaFisicaContenido.url=/WEB-INF/views/widget/persona/fisica/contenido.jsp

widgetPersonaMoralInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaMoralInit.url=/WEB-INF/views/widget/persona/moral/inicial.jsp
widgetPersonaMoralContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaMoralContenido.url=/WEB-INF/views/widget/persona/moral/contenido.jsp

widgetPatronCentroTrabajoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPatronCentroTrabajoInit.url=/WEB-INF/views/widget/patron/centroTrabajo/inicial.jsp
widgetPatronCentroTrabajoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPatronCentroTrabajoContenido.url=/WEB-INF/views/widget/patron/centroTrabajo/contenido.jsp

widgetPatronGralCentroTrabajoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPatronGralCentroTrabajoInit.url=/WEB-INF/views/widget/patron/general/inicial.jsp
widgetPatronGralCentroTrabajoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPatronGralCentroTrabajoContenido.url=/WEB-INF/views/widget/patron/general/contenido.jsp

widgetPersonaIdentidadInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIdentidadInit.url=/WEB-INF/views/widget/persona/identidad/inicial.jsp
widgetPersonaIdentidadContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIdentidadContenido.url=/WEB-INF/views/widget/persona/identidad/contenido.jsp

widgetPersonaIdentidadAseguradoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIdentidadAseguradoInit.url=/WEB-INF/views/widget/persona/identidad/inicialForAsegurado.jsp
widgetPersonaIdentidadAseguradoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIdentidadAseguradoContenido.url=/WEB-INF/views/widget/persona/identidad/contenido.jsp

widgetPersonaIdentidadDerechohabienteInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIdentidadDerechohabienteInit.url=/WEB-INF/views/widget/persona/identidad/inicialForDerechohabiente.jsp
widgetPersonaIdentidadDerechohabienteContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIdentidadDerechohabienteContenido.url=/WEB-INF/views/widget/persona/identidad/contenido.jsp




widgetPersonaFiscalInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaFiscalInit.url=/WEB-INF/views/widget/fiscal/inicial.jsp
widgetPersonaFiscalContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaFiscalContenido.url=/WEB-INF/views/widget/fiscal/contenido.jsp

widgetMediosParticularesInit.(class)=org.springframework.web.servlet.view.JstlView
widgetMediosParticularesInit.url=/WEB-INF/views/widget/medios/particulares/inicial.jsp
widgetMediosParticularesContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetMediosParticularesContenido.url=/WEB-INF/views/widget/medios/particulares/contenido.jsp

widgetMediosFiscalesInit.(class)=org.springframework.web.servlet.view.JstlView
widgetMediosFiscalesInit.url=/WEB-INF/views/widget/medios/fiscales/inicial.jsp
widgetMediosFiscalesContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetMediosFiscalesContenido.url=/WEB-INF/views/widget/medios/fiscales/contenido.jsp

widgetMediosCentroTrabajoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetMediosCentroTrabajoInit.url=/WEB-INF/views/widget/medios/centroTrabajo/inicial.jsp
widgetMediosCentroTrabajoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetMediosCentroTrabajoContenido.url=/WEB-INF/views/widget/medios/centroTrabajo/contenido.jsp

widgetDomiciliosParticularesInit.(class)=org.springframework.web.servlet.view.JstlView
widgetDomiciliosParticularesInit.url=/WEB-INF/views/widget/domicilios/particulares/inicial.jsp
widgetDomiciliosParticularesContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDomiciliosParticularesContenido.url=/WEB-INF/views/widget/domicilios/particulares/contenido.jsp

widgetDomiciliosFiscalesInit.(class)=org.springframework.web.servlet.view.JstlView
widgetDomiciliosFiscalesInit.url=/WEB-INF/views/widget/domicilios/fiscales/inicial.jsp
widgetDomiciliosFiscalesContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDomiciliosFiscalesContenido.url=/WEB-INF/views/widget/domicilios/fiscales/contenido.jsp

widgetDomiciliosCentroTrabajoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetDomiciliosCentroTrabajoInit.url=/WEB-INF/views/widget/domicilios/centroTrabajo/inicial.jsp
widgetDomiciliosCentroTrabajoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDomiciliosCentroTrabajoContenido.url=/WEB-INF/views/widget/domicilios/centroTrabajo/contenido.jsp

widgetNSSInit.(class)=org.springframework.web.servlet.view.JstlView
widgetNSSInit.url=/WEB-INF/views/widget/nss/persona/inicial.jsp
widgetNSSContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetNSSContenido.url=/WEB-INF/views/widget/nss/persona/contenido.jsp
widgetNSSRecuperadoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetNSSRecuperadoContenido.url=/WEB-INF/views/widget/nss/persona/contenido_NSS_recuperado.jsp

widgetNSSEstudiantesInit.(class)=org.springframework.web.servlet.view.JstlView
widgetNSSEstudiantesInit.url=/WEB-INF/views/widget/nss/estudiantes/inicial.jsp
widgetNSSEstudiantesContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetNSSEstudiantesContenido.url=/WEB-INF/views/widget/nss/estudiantes/contenido.jsp

widgetDatosFiscalesInit.(class)=org.springframework.web.servlet.view.JstlView
widgetDatosFiscalesInit.url=/WEB-INF/views/widget/datos/fiscales/inicial.jsp
widgetDatosFiscalesContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDatosFiscalesContenido.url=/WEB-INF/views/widget/datos/fiscales/contenido.jsp

#Seguros Individuales IVRO Widget
widgetPersonaIvroIndivInit.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIvroIndivInit.url=/WEB-INF/views/widget/ivro/indiv/inicial-ivro-indiv-widget.jsp
widgetPersonaIvroIndivContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetPersonaIvroIndivContenido.url=/WEB-INF/views/widget/ivro/indiv/contenido-ivro-indiv-widget.jsp


#===== PORTLETS ====== 
portletPatronesAsociadosInit.(class)=org.springframework.web.servlet.view.JstlView
portletPatronesAsociadosInit.url=/WEB-INF/views/portlet/patrones/asociados-persona/inicial.jsp
portletPatronesAsociadosContenido.(class)=org.springframework.web.servlet.view.JstlView
portletPatronesAsociadosContenido.url=/WEB-INF/views/portlet/patrones/asociados-persona/contenido.jsp

portletConsultaPersonaFisicaInit.(class)=org.springframework.web.servlet.view.JstlView
portletConsultaPersonaFisicaInit.url=/WEB-INF/views/portlet/persona/fisica/inicial.jsp
portletConsultaPersonaFisicaContent.(class)=org.springframework.web.servlet.view.JstlView
portletConsultaPersonaFisicaContent.url=/WEB-INF/views/portlet/persona/fisica/contenido.jsp

portletPatronesAutorizadosInit.(class)=org.springframework.web.servlet.view.JstlView
portletPatronesAutorizadosInit.url=/WEB-INF/views/portlet/patrones/autorizados/inicial.jsp
portletPatronesAutorizadosContenido.(class)=org.springframework.web.servlet.view.JstlView
portletPatronesAutorizadosContenido.url=/WEB-INF/views/portlet/patrones/autorizados/contenido.jsp

portletPatronesClasificacionInit.(class)=org.springframework.web.servlet.view.JstlView
portletPatronesClasificacionInit.url=/WEB-INF/views/portlet/patrones/clasificacion/inicial.jsp
portletPatronesClasificacionContenido.(class)=org.springframework.web.servlet.view.JstlView
portletPatronesClasificacionContenido.url=/WEB-INF/views/portlet/patrones/clasificacion/contenido.jsp

portletSolicitudesInit.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesInit.url=/WEB-INF/views/portlet/solicitudes/inicial.jsp
portletSolicitudesContenido.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesContenido.url=/WEB-INF/views/portlet/solicitudes/contenido.jsp

portletSolicitudesRegPatInit.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesRegPatInit.url=/WEB-INF/views/portlet/patrones/solicitudes/inicial.jsp
portletSolicitudesRegPatContenido.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesRegPatContenido.url=/WEB-INF/views/portlet/patrones/solicitudes/contenido.jsp

#======== WIZARDS ===========
wizardRecuperacionPatronInit.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardRecuperacionPatronInit.url = wizardRecuperacionPatronInit
wizardRecuperacionPatronContent.(class) = org.springframework.web.servlet.view.tiles2.TilesView
wizardRecuperacionPatronContent.url = wizardRecuperacionPatronContent


formularioNombreComercial.(class)=org.springframework.web.servlet.view.tiles2.TilesView
formularioNombreComercial.url=formularioNombreComercial

opcionesUsuario.(class)=org.springframework.web.servlet.view.tiles2.TilesView
opcionesUsuario.url=opcionesUsuario

portalPrueba.(class)=org.springframework.web.servlet.view.tiles2.TilesView
portalPrueba.url=portalPrueba

aseguradoPortal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
aseguradoPortal.url = aseguradoPortal

derechohabientePortal.(class)=org.springframework.web.servlet.view.tiles2.TilesView
derechohabientePortal.url = derechohabientePortal

opcionesMenu.(class)=org.springframework.web.servlet.view.JstlView
opcionesMenu.url=/WEB-INF/views/general/opciones.jsp

opcionesSubmenuPatron.(class)=org.springframework.web.servlet.view.JstlView
opcionesSubmenuPatron.url=/WEB-INF/views/general/opcionesSubmenuPatrones.jsp

opcionesMenuAdscripcion.(class)=org.springframework.web.servlet.view.JstlView
opcionesMenuAdscripcion.url=/WEB-INF/views/general/opcionesMenuAdscripcion.jsp

opcionesMenuGrupoFamiliar.(class)=org.springframework.web.servlet.view.JstlView
opcionesMenuGrupoFamiliar.url=/WEB-INF/views/general/opcionesPortletGrupoFamiliar.jsp

opcionesWidgetTramite.(class)=org.springframework.web.servlet.view.JstlView
opcionesWidgetTramite.url=/WEB-INF/views/general/opcionesWidgetTramites.jsp

