//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 07:16:49 PM CDT 
//


package mx.gob.imss.ctirss.delta.model.gestion.individuo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import mx.gob.imss.ctirss.delta.framework.base.model.AbstractModel;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id-tipo-sociedad" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="des-tipo-sociedad-abrev" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "tipo-sociedad")
public class TipoSociedad
    extends AbstractModel
    implements Serializable
{

    private final static long serialVersionUID = 1234321L;
    @XmlAttribute(name = "id-tipo-sociedad")
    protected Integer idTipoSociedad;
    @XmlAttribute(name = "des-tipo-sociedad-abrev")
    protected String desTipoSociedadAbrev;

    /**
     * Gets the value of the idTipoSociedad property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdTipoSociedad() {
        return idTipoSociedad;
    }

    /**
     * Sets the value of the idTipoSociedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdTipoSociedad(Integer value) {
        this.idTipoSociedad = value;
    }

    /**
     * Gets the value of the desTipoSociedadAbrev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesTipoSociedadAbrev() {
        return desTipoSociedadAbrev;
    }

    /**
     * Sets the value of the desTipoSociedadAbrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesTipoSociedadAbrev(String value) {
        this.desTipoSociedadAbrev = value;
    }

}
