<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>mx.gob.imss.dacvass.scheduler</groupId>
		<artifactId>scheduler-consulta-cfdi</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	
	<artifactId>scheduler-consulta-cfdi-web</artifactId>
	<packaging>war</packaging>
	<name>scheduler-consulta-cfdi-web Maven Webapp</name>
	<url>http://maven.apache.org</url>
	
	<properties>
		<!-- Configuracion del Encoding -->
		<junit.version>4.12</junit.version>
		<org.slf4j.version>1.6.1</org.slf4j.version>
		<org.springframework.version>3.0.5.RELEASE</org.springframework.version>
		<tiles.framework.version>2.2.1</tiles.framework.version>
		<spring.security.version>2.0.4</spring.security.version>
	</properties>
	
	<dependencies>
		
		<dependency>
			<groupId>mx.gob.imss.dacvass.scheduler</groupId>
			<artifactId>scheduler-consulta-cfdi-interfaces-negocio</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>jar</type>
		</dependency>
	
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${org.slf4j.version}</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${org.slf4j.version}</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.16</version>
		</dependency>
	    
		<!-- Spring -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${org.springframework.version}</version>
			<exclusions>
<!-- 				Exclude Commons Logging in favor of SLF4j -->
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		
<!-- 		QuartzJobBean in spring-context-support.jar -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-support</artifactId>
		    <version>2.0.8</version>
		</dependency>
		
<!-- 		Quartz framework -->
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>1.8.6</version>
		</dependency>
		
<!-- 		Spring + Quartz need transaction -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		
<!-- 		Dependencias EJB -->
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb-api</artifactId>
			<version>3.0</version>
<!-- 			Se pone provided ya que esta api será proporcionada por el servidor sobre el que se despliegue la aplicación. -->
			<scope>provided</scope>
		</dependency>
		
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<compilerArguments>
						<endorseddirs>${endorsed.dir}</endorseddirs>
					</compilerArguments>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.1.1</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.1</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<outputDirectory>${endorsed.dir}</outputDirectory>
							<silent>true</silent>
							<artifactItems>
								<artifactItem>
									<groupId>javax</groupId>
									<artifactId>javaee-endorsed-api</artifactId>
									<version>6.0</version>
									<type>jar</type>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Habilita los facets y natures para que el eclipse reconoza el proyecto 
				como de tipo de Dynamic Web. -->
			<plugin>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<additionalBuildcommands>
						<buildCommand>
							<name>org.eclipse.jdt.core.javabuilder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.common.project.facet.core.builder</name>
						</buildCommand>
						<buildCommand>
							<name>org.eclipse.wst.validation.validationbuilder</name>
						</buildCommand>

					</additionalBuildcommands>
					<additionalProjectnatures>
						<projectnature>org.eclipse.wst.common.project.facet.core.nature</projectnature>
						<projectnature>org.eclipse.jdt.core.javanature</projectnature>
						<projectnature>org.eclipse.wst.common.modulecore.ModuleCoreNature</projectnature>
						<projectnature>org.eclipse.jem.workbench.JavaEMFNature</projectnature>
						<projectnature>org.eclipse.wst.jsdt.core.jsNature</projectnature>

					</additionalProjectnatures>
					<additionalConfig>
						<file>
							<name>.settings/org.eclipse.wst.common.project.facet.core.xml</name>
							<content>&lt;faceted-project&gt;
								&lt;runtime name="Weblogic
								Runtime" /&gt;
								&lt;fixed facet="java" /&gt;
								&lt;fixed
								facet="jst.web" /&gt;
								&lt;fixed facet="wst.jsdt.web" /&gt;
								&lt;installed facet="java" version="1.6" /&gt;
								&lt;installed
								facet="jst.web" version="2.5" /&gt;
								&lt;installed facet="wls.web"
								version="10.3.4" /&gt;
								&lt;installed facet="wst.jsdt.web"
								version="1.0" /&gt;
								&lt;/faceted-project&gt;</content>
						</file>
						<file>
							<name>.settings/org.eclipse.wst.common.component</name>
							<content>&lt;project-modules id="moduleCoreId"
								project-version="1.5.0"&gt;
								&lt;wb-module
								deploy-name="dynamic"&gt;
								&lt;wb-resource deploy-path="/"
								source-path="/src/main/webapp"
								tag="defaultRootSource" /&gt;
								&lt;wb-resource deploy-path="/" source-path="/src/main/java"
								/&gt;
								&lt;wb-resource deploy-path="/"
								source-path="/src/main/resources" /&gt;
								&lt;property
								name="context-root" value="${project.artifactId}" /&gt;
								&lt;property name="java-output-path" value="target/classes"
								/&gt;
								&lt;/wb-module&gt;
								&lt;/project-modules&gt;</content>
						</file>
					</additionalConfig>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.apache.maven.plugins</groupId>
										<artifactId>maven-dependency-plugin</artifactId>
										<versionRange>[2.1,)</versionRange>
										<goals>
											<goal>copy</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
		
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>
	
</project>
