#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
 
 
nacional.detalle.(class)=org.springframework.web.servlet.view.JstlView
nacional.detalle.url=/WEB-INF/views/domicilio/detalle/nacional.jsp
 
 
#Tiles redirect

gestionSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
gestionSolicitud.url=gestionSolicitud

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError



solicitud.enproceso.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitud.enproceso.url=solicitudEnproceso

#Firma Digital
initFirmaDigitalTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaDigitalTest.url=initFirmaDigitalTest

initFirmaDigital.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaDigital.url=initFirmaDigital

seleccionTipoFirma.(class)=org.springframework.web.servlet.view.tiles2.TilesView
seleccionTipoFirma.url=seleccionTipoFirma

initFirmaConFIEL.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaConFIEL.url=initFirmaConFIEL

initFirmaConIMSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initFirmaConIMSS.url=initFirmaConIMSS

resultadoFirmaDigital.(class)=org.springframework.web.servlet.view.tiles2.TilesView
resultadoFirmaDigital.url=resultadoFirmaDigital

solicitudesPersonaFisica.(class)=org.springframework.web.servlet.view.JstlView
solicitudesPersonaFisica.url=/WEB-INF/views/solicitud/solicitudesPersonaFisica.jsp


solicitudesPersonaMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
solicitudesPersonaMoral.url=solicitudesPersonaMoral

wizardCartaTerminos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardCartaTerminos.url=wizardCartaTerminos

wizardCartaTerminosRepresentante.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardCartaTerminosRepresentante.url=wizardCartaTerminosRepresentante

reporteCartaTerminosFiel.(class)=org.springframework.web.servlet.view.jasperreports.JasperReportsPdfView
reporteCartaTerminosFiel.url=/WEB-INF/reportesTemplates/cartaTerminosCondicionesFiel.jasper
reporteCartaTerminosFiel.reportDataKey=datosKey

pruebaCartaTerminos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
pruebaCartaTerminos.url=pruebaCartaTerminos