package mx.gob.imss.csdiss.sdroc.dto;

/**
 * RocTipoIncidencia generated by hbm2java
 */
public class TipoIncidenciaDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1726916668401744696L;
	
	private Long cveTipoIncidencia;
	private String desTipoIncidencia;

	public TipoIncidenciaDTO() {
	}

	public TipoIncidenciaDTO(Long cveTipoIncidencia) {
		this.cveTipoIncidencia = cveTipoIncidencia;
	}

	public TipoIncidenciaDTO(Long cveTipoIncidencia, String desTipoIncidencia) {	
		this.cveTipoIncidencia = cveTipoIncidencia;
		this.desTipoIncidencia = desTipoIncidencia;
	}

	public Long getCveTipoIncidencia() {
		return this.cveTipoIncidencia;
	}

	public void setCveTipoIncidencia(Long cveTipoIncidencia) {
		this.cveTipoIncidencia = cveTipoIncidencia;
	}

	public String getDesTipoIncidencia() {
		return this.desTipoIncidencia;
	}

	public void setDesTipoIncidencia(String desTipoIncidencia) {
		this.desTipoIncidencia = desTipoIncidencia;
	}

}
