###########
# General #
###########
general.url_archivo = file:c:/application.properties
general.busqueda_properties = 1

#################
# Servidor SMTP #
#################

mail.smtp.sendmail=0
mail.smtp.host=11.254.12.85
mail.smtp.user=aseg53.caro
mail.smtp.password=aseg53
mail.smtp.from=totalesimssdigital@imss.gob.mx
mail.smtp.from.name=Cifras IMSS Digital
mail.smtp.replyto=noreply@imss.gob.mx
mail.smtp.replyto.name=NO REPLY

## Corte de Asignacion
mail.smtp.subjects.asig.hoy=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.asig.ayer=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.asig.rango=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com

mail.smtp.subjects.altapat.hoy=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.altapat.ayer=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.altapat.rango=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com

mail.smtp.subjects.modifclas.vent.hoy=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.modifclas.vent.ayer=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.modifclas.vent.rango=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com

mail.smtp.subjects.modifclas.ext.hoy=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.modifclas.ext.ayer=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.modifclas.ext.rango=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com

mail.smtp.subjects.riss.hoy=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.riss.ayer=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com
mail.smtp.subjects.riss.rango=jose.ortega@novutek.com,ignacio.espinosav@imss.gob.mx,ignacio.espinosav@gmail.com

##################
# Datos de corte #
##################
canase.corte.hora=21:00
canase.corte.tolerancia=10

