package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;

/**
 * DgCatTermGen generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatTermGen extends AbstractModel {

	private Integer cveTer;
	private String nombre;
	
	public AbstractDgCatTermGen() {
	}

	public AbstractDgCatTermGen(Integer cveTer, String nombre) {
		this.cveTer = cveTer;
		this.nombre = nombre;
	}

	

	@Id
	@Column(name = "CVE_TER", unique = true, nullable = false, precision = 2, scale = 0)
	public Integer getCveTer() {
		return this.cveTer;
	}

	public void setCveTer(Integer cveTer) {
		this.cveTer = cveTer;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
