package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;


import mx.imss.ctirss.framework.base.model.AbstractModel;

/**
 * DgCatAmbito generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatAmbito extends AbstractModel {

	private Integer ambito;
	private String nombre;
	

	public AbstractDgCatAmbito() {
	}

	public AbstractDgCatAmbito(Integer ambito, String nombre) {
		this.ambito = ambito;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "AMBITO", unique = true, nullable = false, precision = 1, scale = 0)
	public Integer getAmbito() {
		return this.ambito;
	}

	public void setAmbito(Integer ambito) {
		this.ambito = ambito;
	}

	@Column(name = "NOMBRE", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
}
