package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;

/**
 * DgCatTipoAsen generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatTipoAsen extends AbstractModel {

	private Integer cveTipoAsen;
	private String nombre;
	

	public AbstractDgCatTipoAsen() {
	}

	public AbstractDgCatTipoAsen(Integer cveTipoAsen, String nombre) {
		this.cveTipoAsen = cveTipoAsen;
		this.nombre = nombre;
	}

	

	@Id
	@Column(name = "CVE_TIPO_ASEN", unique = true, nullable = false, precision = 2, scale = 0)
	public Integer getCveTipoAsen() {
		return this.cveTipoAsen;
	}

	public void setCveTipoAsen(Integer cveTipoAsen) {
		this.cveTipoAsen = cveTipoAsen;
	}

	@Column(name = "NOMBRE", nullable = false, length = 21)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
