package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatAdministracion;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatDerechosTransito;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgDomicilioGeografico;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DgDomiciliosCarreteras generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgDomiciliosCarreteras extends AbstractModel {
	

	private Long domicilioId;
	private DgCatAdministracion dgCatAdministracion;
	private DgDomicilioGeografico dgDomicilioGeografico;
	private DgCatDerechosTransito dgCatDerechosTransito;
	private String nomvial;
	private String origen;
	private String destino;
	private String cadenamiento;

	public AbstractDgDomiciliosCarreteras() {
	/*	this.dgCatAdministracion = new DgCatAdministracion();
		this.dgDomicilioGeografico = new DgDomicilioGeografico();
		this.dgCatDerechosTransito = new DgCatDerechosTransito();
		*/
	}

	public AbstractDgDomiciliosCarreteras(DgDomicilioGeografico dgDomicilioGeografico,
			String nomvial) {
		this.dgDomicilioGeografico = dgDomicilioGeografico;
		this.nomvial = nomvial;
	}

	public AbstractDgDomiciliosCarreteras(DgCatAdministracion dgCatAdministracion,
			DgDomicilioGeografico dgDomicilioGeografico,
			DgCatDerechosTransito dgCatDerechosTransito, String nomvial,
			String origen, String destino, String cadenamiento) {
		this.dgCatAdministracion = dgCatAdministracion;
		this.dgDomicilioGeografico = dgDomicilioGeografico;
		this.dgCatDerechosTransito = dgCatDerechosTransito;
		this.nomvial = nomvial;
		this.origen = origen;
		this.destino = destino;
		this.cadenamiento = cadenamiento;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "dgDomicilioGeografico"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "DOMICILIO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getDomicilioId() {
		return this.domicilioId;
	}

	public void setDomicilioId(Long domicilioId) {
		this.domicilioId = domicilioId;
	}
 
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CVE_CAC")
	public DgCatAdministracion getDgCatAdministracion() {
		return this.dgCatAdministracion;
	}

	public void setDgCatAdministracion(DgCatAdministracion dgCatAdministracion) {
		this.dgCatAdministracion = dgCatAdministracion;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public DgDomicilioGeografico getDgDomicilioGeografico() {
		return this.dgDomicilioGeografico;
	}

	public void setDgDomicilioGeografico(
			DgDomicilioGeografico dgDomicilioGeografico) {
		this.dgDomicilioGeografico = dgDomicilioGeografico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CVE_CDT")
	public DgCatDerechosTransito getDgCatDerechosTransito() {
		return this.dgCatDerechosTransito;
	}

	public void setDgCatDerechosTransito(
			DgCatDerechosTransito dgCatDerechosTransito) {
		this.dgCatDerechosTransito = dgCatDerechosTransito;
	}

	@Column(name = "NOMVIAL", nullable = false)
	public String getNomvial() {
		return this.nomvial;
	}

	public void setNomvial(String nomvial) {
		this.nomvial = nomvial;
	}

	@Column(name = "ORIGEN")
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "DESTINO")
	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	@Column(name = "CADENAMIENTO")
	public String getCadenamiento() {
		return this.cadenamiento;
	}

	public void setCadenamiento(String cadenamiento) {
		this.cadenamiento = cadenamiento;
	}

}
