package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;

/**
 * DgCatDerechosTransito generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatDerechosTransito extends AbstractModel {

	private Integer cveCdt;
	private String nombre;
	

	public AbstractDgCatDerechosTransito() {
	}

	public AbstractDgCatDerechosTransito(Integer cveCdt, String nombre) {
		this.cveCdt = cveCdt;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "CVE_CDT", unique = true, nullable = false, precision = 2, scale = 0)
	public Integer getCveCdt() {
		return this.cveCdt;
	}

	public void setCveCdt(Integer cveCdt) {
		this.cveCdt = cveCdt;
	}

	@Column(name = "NOMBRE", nullable = false, length = 13)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


}
