package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import mx.imss.ctirss.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatAmbito;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatMunicipio;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatPeriodo;

/**
 * DgCatLocalidad generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatLocalidad extends AbstractModel {

	private AbstractDgCatLocalidadId id;
	private DgCatAmbito dgCatAmbito;
	private DgCatMunicipio dgCatMunicipio;
	private DgCatPeriodo dgCatPeriodo;
	private String nomLoc;
	private String agregada;
	
	public AbstractDgCatLocalidad() {
		this.id = new AbstractDgCatLocalidadId();
	
	}

	public AbstractDgCatLocalidad(AbstractDgCatLocalidadId id, DgCatAmbito dgCatAmbito,
			DgCatMunicipio dgCatMunicipio, DgCatPeriodo dgCatPeriodo,
			String nomLoc) {
		this.id = id;
		this.dgCatAmbito = dgCatAmbito;
		this.dgCatMunicipio = dgCatMunicipio;
		this.dgCatPeriodo = dgCatPeriodo;
		this.nomLoc = nomLoc;
	}

	public AbstractDgCatLocalidad(AbstractDgCatLocalidadId id, DgCatAmbito dgCatAmbito,
			DgCatMunicipio dgCatMunicipio, DgCatPeriodo dgCatPeriodo,
			String nomLoc, String agregada) {
		this.id = id;
		this.dgCatAmbito = dgCatAmbito;
		this.dgCatMunicipio = dgCatMunicipio;
		this.dgCatPeriodo = dgCatPeriodo;
		this.nomLoc = nomLoc;
		this.agregada = agregada;
	/*	this.dgVialidads = dgVialidads;
		this.dgAsentamientos = dgAsentamientos;
		this.dgDomicilioGeograficos = dgDomicilioGeograficos;
		*/
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cveEnt", column = @Column(name = "CVE_ENT", nullable = false, length = 2)),
			@AttributeOverride(name = "cveMun", column = @Column(name = "CVE_MUN", nullable = false, length = 3)),
			@AttributeOverride(name = "cveLoc", column = @Column(name = "CVE_LOC", nullable = false, length = 4)),
			@AttributeOverride(name = "cvePeriodo", column = @Column(name = "CVE_PERIODO", nullable = false, precision = 2, scale = 0)) })
	public AbstractDgCatLocalidadId getId() {
		return this.id;
	}

	public void setId(AbstractDgCatLocalidadId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "AMBITO", nullable = false)
	public DgCatAmbito getDgCatAmbito() {
		return this.dgCatAmbito;
	}

	public void setDgCatAmbito(DgCatAmbito dgCatAmbito) {
		this.dgCatAmbito = dgCatAmbito;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", nullable = false, insertable = false, updatable = false) })
	public DgCatMunicipio getDgCatMunicipio() {
		return this.dgCatMunicipio;
	}

	public void setDgCatMunicipio(DgCatMunicipio dgCatMunicipio) {
		this.dgCatMunicipio = dgCatMunicipio;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_PERIODO", nullable = false, insertable = false, updatable = false)
	public DgCatPeriodo getDgCatPeriodo() {
		return this.dgCatPeriodo;
	}

	public void setDgCatPeriodo(DgCatPeriodo dgCatPeriodo) {
		this.dgCatPeriodo = dgCatPeriodo;
	}

	@Column(name = "NOM_LOC", nullable = false, length = 100)
	public String getNomLoc() {
		return this.nomLoc;
	}

	public void setNomLoc(String nomLoc) {
		this.nomLoc = nomLoc;
	}

	@Column(name = "AGREGADA", length = 1)
	public String getAgregada() {
		return this.agregada;
	}

	public void setAgregada(String agregada) {
		this.agregada = agregada;
	}

}
