package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatAmbito;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatLocalidad;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatVialidad;

/**
 * DgVialidad generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgVialidad extends AbstractModel {

	private Long cveVia;
	private DgCatLocalidad dgCatLocalidad;
	private DgCatAmbito dgCatAmbito;
	private DgCatVialidad dgCatVialidad;
	private String nomVia;
	private Character agregada;

	public AbstractDgVialidad() {
	/*	this.dgCatLocalidad = new DgCatLocalidad();
		this.dgCatAmbito= new DgCatAmbito();
		this.dgCatVialidad= new DgCatVialidad();
		*/

	}

	public AbstractDgVialidad(Long cveVia, DgCatLocalidad dgCatLocalidad,
			DgCatAmbito dgCatAmbito, DgCatVialidad dgCatVialidad, String nomVia) {
		this.cveVia = cveVia;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatAmbito = dgCatAmbito;
		this.dgCatVialidad = dgCatVialidad;
		this.nomVia = nomVia;
	}

	public AbstractDgVialidad(Long cveVia, DgCatLocalidad dgCatLocalidad,
			DgCatAmbito dgCatAmbito, DgCatVialidad dgCatVialidad,
			String nomVia, Character agregada) {
		this.cveVia = cveVia;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatAmbito = dgCatAmbito;
		this.dgCatVialidad = dgCatVialidad;
		this.nomVia = nomVia;
		this.agregada = agregada;
	}

	@Id
	@Column(name = "CVE_VIA", unique = true, nullable = true, precision = 10, scale = 0, updatable=false, insertable=false)
	public Long getCveVia() {
		
		if(cveVia!=null && cveVia.intValue()<=0) return null;
		
		return this.cveVia;
	}

	public void setCveVia(Long cveVia) {
		this.cveVia = cveVia;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", nullable = false, updatable=false, insertable=false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", nullable = false, updatable=false, insertable=false),
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", nullable = false, updatable=false, insertable=false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", nullable = false, updatable=false, insertable=false) })
	public DgCatLocalidad getDgCatLocalidad() {
		return this.dgCatLocalidad;
	}

	public void setDgCatLocalidad(DgCatLocalidad dgCatLocalidad) {
		this.dgCatLocalidad = dgCatLocalidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "AMBITO", nullable = false, updatable=false, insertable=false)
	public DgCatAmbito getDgCatAmbito() {
		return this.dgCatAmbito;
	}

	public void setDgCatAmbito(DgCatAmbito dgCatAmbito) {
		this.dgCatAmbito = dgCatAmbito;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_TIPO_VIAL", nullable = false, updatable=false, insertable=false)
	public DgCatVialidad getDgCatVialidad() {
		return this.dgCatVialidad;
	}

	public void setDgCatVialidad(DgCatVialidad dgCatVialidad) {
		this.dgCatVialidad = dgCatVialidad;
	}

	@Column(name = "NOM_VIA", nullable = false, updatable=false, insertable=false)
	public String getNomVia() {
		return this.nomVia;
	}

	public void setNomVia(String nomVia) {
		this.nomVia = nomVia;
	}

	@Column(name = "AGREGADA", length = 1, updatable=false, insertable=false)
	public Character getAgregada() {
		return this.agregada;
	}

	public void setAgregada(Character agregada) {
		this.agregada = agregada;
	}

}
