package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;

/**
 * DgCatTipoDom generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatTipoDom extends AbstractModel {

	private Integer cveTipoDom;
	private String descripcion;
	private String compEspac;
	
	public AbstractDgCatTipoDom() {
	}

	public AbstractDgCatTipoDom(Integer cveTipoDom, String descripcion, String compEspac) {
		this.cveTipoDom = cveTipoDom;
		this.descripcion = descripcion;
		this.compEspac = compEspac;
	}


	@Id
	@Column(name = "CVE_TIPO_DOM", unique = true, nullable = false, precision = 1, scale = 0)
	public Integer getCveTipoDom() {
		return this.cveTipoDom;
	}

	public void setCveTipoDom(Integer cveTipoDom) {
		this.cveTipoDom = cveTipoDom;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 240)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "COMP_ESPAC", nullable = false, length = 240)
	public String getCompEspac() {
		return this.compEspac;
	}

	public void setCompEspac(String compEspac) {
		this.compEspac = compEspac;
	}


}
