package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import mx.imss.ctirss.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgAsentamiento;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatLocalidad;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatTipoDom;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCodigosPostales;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgDomicilioGeografico;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgDomiciliosCaminos;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgDomiciliosCarreteras;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgVialidad;

/**
 * DgDomicilioGeografico generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgDomicilioGeografico extends AbstractModel {

	private Long domicilioId;
	private DgAsentamiento dgAsentamiento;
	private DgCatLocalidad dgCatLocalidad;
	private DgCatTipoDom dgCatTipoDom;
	private DgCodigosPostales dgCodigosPostales;
	private String nomvial;
	private Integer numextnum;
	private String numextalf;
	private String numextAnt;
	private Integer numintnum;
	private String numintalf;
	
	
	private DgVialidad dgVialidadByCveViaPrin;
	private DgVialidad dgVialidadByCveViaRef1;
	private DgVialidad dgVialidadByCveViaRef2;
	private DgVialidad dgVialidadByCveViaRef3;
	
	
	private String descripc;
	private String domGeog;
	private Date fechaHoraAlta;
	private String cveUsuario;
//	private DgDomiciliosCaminos dgDomiciliosCaminos;
//	private DgDomiciliosCarreteras dgDomiciliosCarreteras;

	
	
	private String hastableKeyDG;
	
		
	public AbstractDgDomicilioGeografico() {
		  this.dgAsentamiento = new DgAsentamiento();
		  this.dgCatLocalidad = new DgCatLocalidad();
		  this.dgCatTipoDom = new DgCatTipoDom();
		  this.dgCodigosPostales = new DgCodigosPostales();
		  this.dgVialidadByCveViaPrin = new DgVialidad();
		  this.dgVialidadByCveViaRef1 = new DgVialidad();
		  this.dgVialidadByCveViaRef2 = new DgVialidad();
		  this.dgVialidadByCveViaRef3 = new DgVialidad();
			
//		  this.dgDomiciliosCaminos = new DgDomiciliosCaminos();
//		  this.dgDomiciliosCarreteras = new DgDomiciliosCarreteras();
		
	}

	public AbstractDgDomicilioGeografico(Long domicilioId,
			DgAsentamiento dgAsentamiento, DgCatTipoDom dgCatTipoDom,
			DgCodigosPostales dgCodigosPostales, String nomvial) {
		this.domicilioId = domicilioId;
		this.dgAsentamiento = dgAsentamiento;
		this.dgCatTipoDom = dgCatTipoDom;
		this.dgCodigosPostales = dgCodigosPostales;
		this.nomvial = nomvial;
	}

	public AbstractDgDomicilioGeografico(Long domicilioId,
			DgVialidad dgVialidadByCveViaRef3,
			DgVialidad dgVialidadByCveViaPrin,
			DgVialidad dgVialidadByCveViaRef2,
			DgAsentamiento dgAsentamiento, DgCatLocalidad dgCatLocalidad,
			DgCatTipoDom dgCatTipoDom, DgVialidad dgVialidadByCveViaRef1,
			DgCodigosPostales dgCodigosPostales,
			String nomvial, Integer numextnum, String numextalf,
			String numextAnt, Integer numintnum, String numintalf,
			String descripc,String domGeog, Date fechaHoraAlta, String cveUsuario) {
		this.domicilioId = domicilioId;
		this.dgAsentamiento = dgAsentamiento;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatTipoDom = dgCatTipoDom;
		this.dgCodigosPostales = dgCodigosPostales;
		this.nomvial = nomvial;
		this.numextnum = numextnum;
		this.numextalf = numextalf;
		this.numextAnt = numextAnt;
		this.numintnum = numintnum;
		this.numintalf = numintalf;
		this.descripc = descripc;
		this.domGeog = domGeog;
		this.fechaHoraAlta = fechaHoraAlta;
		this.cveUsuario = cveUsuario;
		this.dgVialidadByCveViaRef1 = dgVialidadByCveViaRef1;
		this.dgVialidadByCveViaRef2 = dgVialidadByCveViaRef2;
		this.dgVialidadByCveViaRef3 = dgVialidadByCveViaRef3;
		this.dgVialidadByCveViaPrin = dgVialidadByCveViaPrin;
//		this.dgDomiciliosCaminos = dgDomiciliosCaminos;
//		this.dgDomiciliosCarreteras = dgDomiciliosCarreteras;
	}

	@Id
	@Column(name = "DOMICILIO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	@SequenceGenerator(name="CRS_DOMICILIO_ID_GENERATOR", sequenceName="SEQ_CVE_DOMICILIO_ID")
	@GeneratedValue(generator="CRS_DOMICILIO_ID_GENERATOR")
	public Long getDomicilioId() {
		return this.domicilioId;
	}

	public void setDomicilioId(Long domicilioId) {
		this.domicilioId = domicilioId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CODIGO", referencedColumnName = "CODIGO", nullable = false),
			@JoinColumn(name = "CVE_ASEN", referencedColumnName = "CVE_ASEN", nullable = false),
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT",  nullable = false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN",  nullable = false),
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC",  nullable = false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO",  nullable = false) })
	public DgCodigosPostales getDgCodigosPostales() {
		return this.dgCodigosPostales;
	}

	public void setDgCodigosPostales(DgCodigosPostales dgCodigosPostales) {
		this.dgCodigosPostales = dgCodigosPostales;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CVE_ASEN", referencedColumnName = "CVE_ASEN", nullable = false,insertable = false, updatable = false),
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT",nullable = false,insertable = false, updatable = false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN",nullable = false,insertable = false, updatable = false),
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC",nullable = false,insertable = false, updatable = false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO",nullable = false,insertable = false, updatable = false) })
	public DgAsentamiento getDgAsentamiento() {
		return this.dgAsentamiento;
	}

	public void setDgAsentamiento(DgAsentamiento dgAsentamiento) {
		this.dgAsentamiento = dgAsentamiento;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_PRIN")
	public DgVialidad getDgVialidadByCveViaPrin() {
		return this.dgVialidadByCveViaPrin;
	}

	public void setDgVialidadByCveViaPrin(DgVialidad dgVialidadByCveViaPrin) {
		this.dgVialidadByCveViaPrin = dgVialidadByCveViaPrin;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_REF1")
	public DgVialidad getDgVialidadByCveViaRef1() {
		return this.dgVialidadByCveViaRef1;
	}

	public void setDgVialidadByCveViaRef1(DgVialidad dgVialidadByCveViaRef1) {
		this.dgVialidadByCveViaRef1 = dgVialidadByCveViaRef1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_REF2")
	public DgVialidad getDgVialidadByCveViaRef2() {
		return this.dgVialidadByCveViaRef2;
	}

	public void setDgVialidadByCveViaRef2(DgVialidad dgVialidadByCveViaRef2) {
		this.dgVialidadByCveViaRef2 = dgVialidadByCveViaRef2;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_VIA_REF3")
	public DgVialidad getDgVialidadByCveViaRef3() {
		return this.dgVialidadByCveViaRef3;
	}

	public void setDgVialidadByCveViaRef3(DgVialidad dgVialidadByCveViaRef3) {
		this.dgVialidadByCveViaRef3 = dgVialidadByCveViaRef3;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", insertable = false, updatable = false),
			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", insertable = false, updatable = false),
			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", insertable = false, updatable = false),
			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", insertable = false, updatable = false) })
	public DgCatLocalidad getDgCatLocalidad() {
		return this.dgCatLocalidad;
	}

	public void setDgCatLocalidad(DgCatLocalidad dgCatLocalidad) {
		this.dgCatLocalidad = dgCatLocalidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_TIPO_DOM", nullable = false)
	public DgCatTipoDom getDgCatTipoDom() {
		return this.dgCatTipoDom;
	}

	public void setDgCatTipoDom(DgCatTipoDom dgCatTipoDom) {
		this.dgCatTipoDom = dgCatTipoDom;
	}


	
	@Column(name = "NOMVIAL", nullable = false, length = 256)
	public String getNomvial() {
		
		if(this.nomvial==null) return "";
		
		return this.nomvial;
	}

	public void setNomvial(String nomvial) {
		this.nomvial = nomvial;
	}

	@Column(name = "NUMEXTNUM", precision = 5, scale = 0)
	public Integer getNumextnum() {
		return this.numextnum;
	}

	public void setNumextnum(Integer numextnum) {
		this.numextnum = numextnum;
	}

	@Column(name = "NUMEXTALF", length = 35)
	public String getNumextalf() {
		return this.numextalf;
	}

	public void setNumextalf(String numextalf) {
		this.numextalf = numextalf;
	}

	@Column(name = "NUMEXT_ANT", length = 35)
	public String getNumextAnt() {
		return this.numextAnt;
	}

	public void setNumextAnt(String numextAnt) {
		this.numextAnt = numextAnt;
	}

	@Column(name = "NUMINTNUM", precision = 5, scale = 0)
	public Integer getNumintnum() {
		return this.numintnum;
	}

	public void setNumintnum(Integer numintnum) {
		this.numintnum = numintnum;
	}

	@Column(name = "NUMINTALF", length = 35)
	public String getNumintalf() {
		return this.numintalf;
	}

	public void setNumintalf(String numintalf) {
		this.numintalf = numintalf;
	}


	@Column(name = "DESCRIPC")
	public String getDescripc() {
		return this.descripc;
	}

	public void setDescripc(String descripc) {
		this.descripc = descripc;
	}

	@Column(name = "DOM_GEOG")
	public String getDomGeog() {
		return this.domGeog;
	}

	public void setDomGeog(String domGeog) {
		this.domGeog = domGeog;
	}

	@Temporal( TemporalType.DATE)
	@Column(name = "FECHA_HORA_ALTA")
	public Date getFechaHoraAlta() {
		return this.fechaHoraAlta;
	}

	public void setFechaHoraAlta(Date fechaHoraAlta) {
		this.fechaHoraAlta = fechaHoraAlta;
	}

	@Column(name = "CVE_USUARIO", length = 20)
	public String getCveUsuario() {
		return this.cveUsuario;
	}

	public void setCveUsuario(String cveUsuario) {
		this.cveUsuario = cveUsuario;
	}

//	@OneToOne(fetch = FetchType.EAGER, mappedBy = "dgDomicilioGeografico")
//	public DgDomiciliosCaminos getDgDomiciliosCaminos() {
//		return this.dgDomiciliosCaminos;
//	}
//
//	public void setDgDomiciliosCaminos(DgDomiciliosCaminos dgDomiciliosCaminos) {
//		this.dgDomiciliosCaminos = dgDomiciliosCaminos;
//	}
//
//	@OneToOne(fetch = FetchType.EAGER, mappedBy = "dgDomicilioGeografico")
//	public DgDomiciliosCarreteras getDgDomiciliosCarreteras() {
//		return this.dgDomiciliosCarreteras;
//	}
//
//	public void setDgDomiciliosCarreteras(
//			DgDomiciliosCarreteras dgDomiciliosCarreteras) {
//		this.dgDomiciliosCarreteras = dgDomiciliosCarreteras;
//	}

	
	@Transient
	public String getHastableKeyDG() {
		return hastableKeyDG;
	}

	public void setHastableKeyDG(String hastableKeyDG) {
		this.hastableKeyDG = hastableKeyDG;
	}

}
