package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.imss.ctirss.framework.base.model.AbstractModel;

/**
 * DgCatPeriodo generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatPeriodo extends AbstractModel {

	private Integer cvePeriodo;
	private String descripcion;
	private Date fecha;


	public AbstractDgCatPeriodo() {
	}

	public AbstractDgCatPeriodo(Integer cvePeriodo, String descripcion, Date fecha) {
		this.cvePeriodo = cvePeriodo;
		this.descripcion = descripcion;
		this.fecha = fecha;
	}

	
	@Id
	@Column(name = "CVE_PERIODO", unique = true, nullable = false, precision = 2, scale = 0)
	public Integer getCvePeriodo() {
		return this.cvePeriodo;
	}

	public void setCvePeriodo(Integer cvePeriodo) {
		this.cvePeriodo = cvePeriodo;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
