package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import mx.imss.ctirss.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatEstadoCp;

/**
 * DgCatEstado generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatEstado extends AbstractModel {

	private String cveEnt;
	private String nomEnt;
	

	public AbstractDgCatEstado() {
	//	this.dgCatEstadoCp = new DgCatEstadoCp();
	}

	public AbstractDgCatEstado(String cveEnt, String nomEnt) {
		this.cveEnt = cveEnt;
		this.nomEnt = nomEnt;
	}

	public AbstractDgCatEstado(String cveEnt, String nomEnt,
			DgCatEstadoCp dgCatEstadoCp) {
		this.cveEnt = cveEnt;
		this.nomEnt = nomEnt;
		
	}

	@Id
	@Column(name = "CVE_ENT", unique = true, nullable = false, length = 2)
	public String getCveEnt() {
		return this.cveEnt;
	}

	public void setCveEnt(String cveEnt) {
		this.cveEnt = cveEnt;
	}

	@Column(name = "NOM_ENT", nullable = false, length = 50)
	public String getNomEnt() {
		return this.nomEnt;
	}

	public void setNomEnt(String nomEnt) {
		this.nomEnt = nomEnt;
	}



}
