package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import mx.imss.ctirss.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatEstado;

/**
 * DgCatMunicipio generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatMunicipio extends AbstractModel {

	private AbstractDgCatMunicipioId id;
	private DgCatEstado dgCatEstado;
	private String nomMun;
	

	public AbstractDgCatMunicipio() {
		this.id = new AbstractDgCatMunicipioId();
	/*	this.dgCatEstado =  new DgCatEstado();
		*/
	}

	public AbstractDgCatMunicipio(AbstractDgCatMunicipioId id, DgCatEstado dgCatEstado,
			String nomMun) {
		this.id = id;
		this.dgCatEstado = dgCatEstado;
		this.nomMun = nomMun;
	}

	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cveMun", column = @Column(name = "CVE_MUN", nullable = false, length = 3)),
			@AttributeOverride(name = "cveEnt", column = @Column(name = "CVE_ENT", nullable = false, length = 2)) })
	public AbstractDgCatMunicipioId getId() {
		return this.id;
	}

	public void setId(AbstractDgCatMunicipioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_ENT", nullable = false, insertable = false, updatable = false)
	public DgCatEstado getDgCatEstado() {
		return this.dgCatEstado;
	}

	public void setDgCatEstado(DgCatEstado dgCatEstado) {
		this.dgCatEstado = dgCatEstado;
	}

	@Column(name = "NOM_MUN", nullable = false, length = 50)
	public String getNomMun() {
		return this.nomMun;
	}

	public void setNomMun(String nomMun) {
		this.nomMun = nomMun;
	}



}
