#################### ARCHIVO DE CONFIGURACION PARA EL SERVIDOR DE LDAP ####################

java.naming.factory.initial = com.sun.jndi.ldap.LdapCtxFactory
java.naming.security.authentication = simple
base.dn.usuarios = ou=people,dc=imss,dc=gob,dc=mx
base.dn.roles = ou=groups,dc=imss,dc=gob,dc=mx
base.dn.perfiles = ou=profiles,dc=imss,dc=gob,dc=mx
base.dn.groups = ou=groups,dc=imss,dc=gob,dc=mx

#java.naming.security.credentials = {SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=
#ldap.auth.password.encryption.algorithm = ldap.auth.password.encryption.algorithm.types=MD5,SHA,SSHA512
#ldap.password.policy.enabled = false

#################### DESARROLLO ####################

#java.naming.provider.url = ldap://ssoimssdigd.imss.gob.mx:1389
#java.naming.security.credentials = dirmanadmin

#java.naming.security.principal = cn=Directory Manager

#################### STAGE ####################

########## OpenAM 10 ##########

#java.naming.provider.url = ldap://vzapma01.imss.gob.mx:1389
#java.naming.security.credentials = dirmanadmin

#java.naming.security.principal = cn=Directory Manager

#userSingleton = cn=Directory Manager
#passSingleton = dirmanadmin
#hostSingleton = 172.16.5.187
#portSingleton = 1389

########## AM 6 ##########

##### 172.16.5.124 #####
#java.naming.provider.url = ldap://ldapdata.imss.gob.mx:1389
#java.naming.security.credentials = 4dmD1g54U13
#
#java.naming.security.principal = cn=AdminQA,ou=saudigital,dc=imss,dc=gob,dc=mx
#
#userSingleton = cn=AdminQA,ou=saudigital,dc=imss,dc=gob,dc=mx
#passSingleton = 4dmD1g54U13
#hostSingleton = ldapdata.imss.gob.mx
#portSingleton = 1389

#################### PRODUCCION ####################

########## OpenAM 10 ##########

#java.naming.provider.url = ldap://ldapadmin.imss.gob.mx:1389
#java.naming.security.credentials = D1RAQICZzvqA5hz

#userSingleton = cn=Directory Manager
#passSingleton = D1RAQICZzvqA5hz
#portSingleton = 1389

########## AM 6 ##########

#java.naming.provider.url = ldap://ldapdata.imss.gob.mx:1389
#java.naming.security.credentials = moFW99QDEj8GlpJfLD
#
#java.naming.security.principal = cn=AdminPRO,ou=saudigital,dc=imss,dc=gob,dc=mx
#
#userSingleton = cn=AdminPRO,ou=saudigital,dc=imss,dc=gob,dc=mx
#passSingleton = moFW99QDEj8GlpJfLD
#hostSingleton = ldapdata.imss.gob.mx
#hostSingleton = 172.18.227.188
#portSingleton = 1389


java.naming.provider.url = ${mvn.java.naming.provider.url}
java.naming.security.credentials = ${mvn.java.naming.security.credentials}
java.naming.security.principal = ${mvn.java.naming.security.principal}
userSingleton = ${mvn.userSingleton}
passSingleton = ${mvn.passSingleton}
hostSingleton = ${mvn.hostSingleton}
portSingleton = ${mvn.portSingleton}

