#Archivo de configuración para el servidor de LDAP
java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory
#java.naming.provider.url=ldap://test2.imss.gob.mx:389 ldap://test2.imss.gob.mx:389
#java.naming.provider.url=ldap://sso-delta.imss.gob.mx:1389 ldap://sso-delta.imss.gob.mx:1389

#url kio
#java.naming.provider.url=ldap://vzapma01.imss.gob.mx:1389
#credenciales kio
#java.naming.security.credentials=dirmanadmin

java.naming.security.authentication=simple
java.naming.security.principal=cn=Directory Manager

base.dn.usuarios=ou=people,dc=imss,dc=gob,dc=mx
base.dn.roles=ou=groups,dc=imss,dc=gob,dc=mx
base.dn.perfiles=ou=profiles,dc=imss,dc=gob,dc=mx
base.dn.groups=ou=groups,dc=imss,dc=gob,dc=mx