package mx.gob.imss.csdiss.sdroc.dto;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.Set;

/**
 * RotInformacionObra generated by hbm2java
 */
public class InformacionObraDTO extends TramiteBaseDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1435676822029830087L;
	private Long cveInformacionObra;
	private SubDelegacionDTO subDelegacionDTO;
	private TipoObraDTO tipoObraDTO;
	private InformacionPatronDTO informacionPatronDTO;
	private Long cveTipoPatron;
	private ObjetoContratoDTO objetoContratoDTO;
	private String desObjetoContratoSubEsp;
	private String cveRegistroObra;
	private Long cveRegistroObraPrincipal;
	private String cveRegistroObraPrincipalReporte;
	private Date fecIniObra;
	private Date fecFinObra;
	private Double impObra;
	private Double refSupConstruccion;
	private String refObservacion;
	private String numProcedimiento;
	private String numLicitacion;
	private Date fecIniContrato;
	private Date fecFinContrato;
	private Short refObjetoContrato;
	private Double impEjercido;
	private Double impContratado;
	private String refAcuseReg;
	private int numIncumplimientos;
	private int numEvaluacionD32;
	private Date stpCreaReg;
	private String refNumSerie;	
	private Set<InformacionIncidenciaDTO> rotInformacionIncidencias;
	private UbicacionObraDTO ubicacionObraDTO;
	private EstatusObraDTO estatusObraDTO;
	private int numActualiza;
	private String refCveAvisoObra;
	private String refOtroObjetoContrato;
	private int numAproxTrabajadores;
	private String numRegStps;
	private boolean aplicaIncRemplazo;
	private String cveObraRemplazado;

	public InformacionObraDTO() {
	}

	public InformacionObraDTO(Long cveInformacionObra, SubDelegacionDTO subDelegacionDTO, TipoObraDTO tipoObraDTO,
			InformacionPatronDTO informacionPatronDTO, EstatusObraDTO estatusObraDTO,ObjetoContratoDTO objetoContratoDTO,String cveRegistroObra, String refCveAvisoObra) {
		this.cveInformacionObra = cveInformacionObra;
		this.subDelegacionDTO = subDelegacionDTO;
		this.tipoObraDTO = tipoObraDTO;
		this.informacionPatronDTO = informacionPatronDTO;
		this.cveRegistroObra = cveRegistroObra;
		this.objetoContratoDTO = objetoContratoDTO;
		this.refCveAvisoObra = refCveAvisoObra;
	}

	public InformacionObraDTO(Long cveIdTramite, String numSeqNotaria, String folio, String refMotivoAct,
	  	String refAcuseInc, String refSelloDigital, String refCadenaOriginal, Long cveInformacionObra,
	  	SubDelegacionDTO subDelegacionDTO, TipoObraDTO tipoObraDTO, InformacionPatronDTO informacionPatronDTO,
	  	ObjetoContratoDTO objetoContratoDTO, String cveRegistroObra,
	  	Long cveRegistroObraPrincipal, String cveRegistroObraPrincipalReporte, Date fecIniObra, Date fecFinObra,
	  	Double impObra, Double refSupConstruccion, String refObservacion, String numProcedimiento, String numLicitacion,
	  	Date fecIniContrato, Date fecFinContrato, Short refObjetoContrato, Double impEjercido, Double impContratado,
	  	String refAcuseReg, int numIncumplimientos, int numEvaluacionD32, Date stpCreaReg, String refNumSerie,
	  	Set<InformacionIncidenciaDTO> rotInformacionIncidencias, UbicacionObraDTO ubicacionObraDTO,
	  	EstatusObraDTO estatusObraDTO, int numActualiza, String refCveAvisoObra, String refOtroObjetoContrato,
		int numAproxTrabajadores, String numRegStps) {
		super(cveIdTramite, numSeqNotaria, folio, refMotivoAct, refAcuseInc, refSelloDigital, refCadenaOriginal);
		this.cveInformacionObra = cveInformacionObra;
		this.subDelegacionDTO = subDelegacionDTO;
		this.tipoObraDTO = tipoObraDTO;
		this.informacionPatronDTO = informacionPatronDTO;
		this.objetoContratoDTO = objetoContratoDTO;
		this.cveRegistroObra = cveRegistroObra;
		this.cveRegistroObraPrincipal = cveRegistroObraPrincipal;
		this.cveRegistroObraPrincipalReporte = cveRegistroObraPrincipalReporte;
		this.fecIniObra = fecIniObra;
		this.fecFinObra = fecFinObra;
		this.impObra = impObra;
		this.refSupConstruccion = refSupConstruccion;
		this.refObservacion = refObservacion;
		this.numProcedimiento = numProcedimiento;
		this.numLicitacion = numLicitacion;
		this.fecIniContrato = fecIniContrato;
		this.fecFinContrato = fecFinContrato;
		this.refObjetoContrato = refObjetoContrato;
		this.impEjercido = impEjercido;
		this.impContratado = impContratado;
		this.refAcuseReg = refAcuseReg;
		this.numIncumplimientos = numIncumplimientos;
		this.numEvaluacionD32 = numEvaluacionD32;
		this.stpCreaReg = stpCreaReg;
		this.refNumSerie = refNumSerie;
		this.rotInformacionIncidencias = rotInformacionIncidencias;
		this.ubicacionObraDTO = ubicacionObraDTO;
		this.estatusObraDTO = estatusObraDTO;
		this.numActualiza = numActualiza;
		this.refCveAvisoObra = refCveAvisoObra;
		this.refOtroObjetoContrato = refOtroObjetoContrato;
		this.numAproxTrabajadores = numAproxTrabajadores;
		this.numRegStps = numRegStps;
	}

	public Long getCveInformacionObra() {
		return this.cveInformacionObra;
	}

	public void setCveInformacionObra(Long cveInformacionObra) {
		this.cveInformacionObra = cveInformacionObra;
	}

	public SubDelegacionDTO getSubDelegacionDTO() {
		return this.subDelegacionDTO;
	}

	public void setSubDelegacionDTO(SubDelegacionDTO subDelegacionDTO) {
		this.subDelegacionDTO = subDelegacionDTO;
	}

	public TipoObraDTO getTipoObraDTO() {
		return this.tipoObraDTO;
	}

	public void setTipoObraDTO(TipoObraDTO tipoObraDTO) {
		this.tipoObraDTO = tipoObraDTO;
	}

	public InformacionPatronDTO getInformacionPatronDTO() {
		return this.informacionPatronDTO;
	}

	public void setInformacionPatronDTO(InformacionPatronDTO informacionPatronDTO) {
		this.informacionPatronDTO = informacionPatronDTO;
	}

	public String getCveRegistroObra() {
		return cveRegistroObra;
	}

	public void setCveRegistroObra(String cveRegistroObra) {
		this.cveRegistroObra = cveRegistroObra;
	}

	public Long getCveRegistroObraPrincipal() {
		return cveRegistroObraPrincipal;
	}

	public void setCveRegistroObraPrincipal(Long cveRegistroObraPrincipal) {
		this.cveRegistroObraPrincipal = cveRegistroObraPrincipal;
	}
	
	
	public Date getFecIniObra() {
		return this.fecIniObra;
	}

	public void setFecIniObra(Date fecIniObra) {
		this.fecIniObra = fecIniObra;
	}

	public Date getFecFinObra() {
		return this.fecFinObra;
	}

	public void setFecFinObra(Date fecFinObra) {
		this.fecFinObra = fecFinObra;
	}

	public Double getImpObra() {
		return this.impObra;
	}

	public void setImpObra(Double impObra) {
		this.impObra = impObra;
	}

	public Double getRefSupConstruccion() {
		return this.refSupConstruccion;
	}

	public void setRefSupConstruccion(Double refSupConstruccion) {
		this.refSupConstruccion = refSupConstruccion;
	}

	public String getRefObservacion() {
		return this.refObservacion;
	}

	public void setRefObservacion(String refObservacion) {
		this.refObservacion = refObservacion;
	}

	public String getNumProcedimiento() {
		return this.numProcedimiento;
	}

	public void setNumProcedimiento(String numProcedimiento) {
		this.numProcedimiento = numProcedimiento;
	}

	public String getNumLicitacion() {
		return this.numLicitacion;
	}

	public void setNumLicitacion(String numLicitacion) {
		this.numLicitacion = numLicitacion;
	}

	public Date getFecIniContrato() {
		return this.fecIniContrato;
	}

	public void setFecIniContrato(Date fecIniContrato) {
		this.fecIniContrato = fecIniContrato;
	}

	public Date getFecFinContrato() {
		return this.fecFinContrato;
	}

	public void setFecFinContrato(Date fecFinContrato) {
		this.fecFinContrato = fecFinContrato;
	}

	public Short getRefObjetoContrato() {
		return this.refObjetoContrato;
	}

	public void setRefObjetoContrato(Short refObjetoContrato) {
		this.refObjetoContrato = refObjetoContrato;
	}

	public Double getImpEjercido() {
		return this.impEjercido;
	}

	public void setImpEjercido(Double impEjercido) {
		this.impEjercido = impEjercido;
	}

	public Double getImpContratado() {
		return this.impContratado;
	}

	public void setImpContratado(Double impContratado) {
		this.impContratado = impContratado;
	}

	public String getRefAcuseReg() {
		return this.refAcuseReg;
	}

	public void setRefAcuseReg(String refAcuseReg) {
		this.refAcuseReg = refAcuseReg;
	}
	
	public int getNumIncumplimientos() {
		return numIncumplimientos;
	}

	public void setNumIncumplimientos(int numIncumplimientos) {
		this.numIncumplimientos = numIncumplimientos;
	}

	public Set<InformacionIncidenciaDTO> getRotInformacionIncidencias() {
		return this.rotInformacionIncidencias;
	}

	public void setRotInformacionIncidencias(Set<InformacionIncidenciaDTO> rotInformacionIncidencias) {
		this.rotInformacionIncidencias = rotInformacionIncidencias;
	}


	/**
	 * @return the ubicacionObraDTO
	 */
	public UbicacionObraDTO getUbicacionObraDTO() {
		return ubicacionObraDTO;
	}

	/**
	 * @param ubicacionObraDTO the ubicacionObraDTO to set
	 */
	public void setUbicacionObraDTO(UbicacionObraDTO ubicacionObraDTO) {
		this.ubicacionObraDTO = ubicacionObraDTO;
	}

	public EstatusObraDTO getEstatusObraDTO() {
		return estatusObraDTO;
	}

	public void setEstatusObraDTO(EstatusObraDTO estatusObraDTO) {
		this.estatusObraDTO = estatusObraDTO;
	}

	/**
	 * @return the objetoContratoDTO
	 */
	public ObjetoContratoDTO getObjetoContratoDTO() {
		return objetoContratoDTO;
	}

	/**
	 * @param objetoContratoDTO the objetoContratoDTO to set
	 */
	public void setObjetoContratoDTO(ObjetoContratoDTO objetoContratoDTO) {
		this.objetoContratoDTO = objetoContratoDTO;
	}

	/**
	 * @return the numEvaluacionD32
	 */
	public int getNumEvaluacionD32() {
		return numEvaluacionD32;
	}

	/**
	 * @param numEvaluacionD32 the numEvaluacionD32 to set
	 */
	public void setNumEvaluacionD32(int numEvaluacionD32) {
		this.numEvaluacionD32 = numEvaluacionD32;
	}
	
	public Date getStpCreaReg() {
		return this.stpCreaReg;
	}

	public void setStpCreaReg(Date stpCreaReg) {
		this.stpCreaReg = stpCreaReg;
	}

	/**
	 * @return the refNumSerie
	 */
	public String getRefNumSerie() {
		return refNumSerie;
	}

	/**
	 * @param refNumSerie the refNumSerie to set
	 */
	public void setRefNumSerie(String refNumSerie) {
		this.refNumSerie = refNumSerie;
	}

	/**
	 * @return the num_actualiza
	 */
	public int getNumActualiza() {
		return numActualiza;
	}

	/**
	 * @param num_actualiza the num_actualiza to set
	 */
	public void setNumActualiza(int numActualiza) {
		this.numActualiza = numActualiza;
	}

	public String getCveRegistroObraPrincipalReporte() {
		return cveRegistroObraPrincipalReporte;
	}

	public void setCveRegistroObraPrincipalReporte(String cveRegistroObraPrincipalReporte) {
		this.cveRegistroObraPrincipalReporte = cveRegistroObraPrincipalReporte;
	}

	/**
	 * @return the refCveAvisoObra
	 */
	public String getRefCveAvisoObra() {
		return refCveAvisoObra;
	}

	/**
	 * @param refCveAvisoObra the refCveAvisoObra to set
	 */
	public void setRefCveAvisoObra(String refCveAvisoObra) {
		this.refCveAvisoObra = refCveAvisoObra;
	}

	public String getRefOtroObjetoContrato() {
		return refOtroObjetoContrato;
	}

	public void setRefOtroObjetoContrato(String refOtroObjetoContrato) {
		this.refOtroObjetoContrato = refOtroObjetoContrato;
	}

	public int getNumAproxTrabajadores() {
		return numAproxTrabajadores;
	}

	public void setNumAproxTrabajadores(int numAproxTrabajadores) {
		this.numAproxTrabajadores = numAproxTrabajadores;
	}

	public String getNumRegStps() {
		return numRegStps;
	}

	public void setNumRegStps(String numRegStps) {
		this.numRegStps = numRegStps;
	}

	public Long getCveTipoPatron() {
		return cveTipoPatron;
	}

	public void setCveTipoPatron(Long cveTipoPatron) {
		this.cveTipoPatron = cveTipoPatron;
	}

	public boolean isAplicaIncRemplazo() {
		return aplicaIncRemplazo;
	}

	public void setAplicaIncRemplazo(boolean aplicaIncRemplazo) {
		this.aplicaIncRemplazo = aplicaIncRemplazo;
	}

	public String getDesObjetoContratoSubEsp() {
		return desObjetoContratoSubEsp;
	}

	public void setDesObjetoContratoSubEsp(String desObjetoContratoSubEsp) {
		this.desObjetoContratoSubEsp = desObjetoContratoSubEsp;
	}

	public String getCveObraRemplazado() {
		return cveObraRemplazado;
	}

	public void setCveObraRemplazado(String cveObraRemplazado) {
		this.cveObraRemplazado = cveObraRemplazado;
	}

}
