package mx.gob.imss.csdiss.sdroc.dto;

/**
 * RotUbicacionObra generated by hbm2java
 */
public class UbicacionObraDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7215061189316568652L;
	private Long cveUbicacionObra;
	private String calle;
	private String numExterior;
	private String numExteriorAlf;
	private String numExteriorDos;
	private String numInteriorAlf;	
	private String numInterior;
	private String codigoPostal;
	private String refEntidad;
	private String refMunicipio;
	private String refColonia;
	private String refObservacion;
	private String refPosterior;
	private String refPrimaria;
	private String refSecundaria;
	private int cveEntidad;
	private int cveMunicipio;
	private int cveLocalidad;

	public UbicacionObraDTO() {
	}

	public UbicacionObraDTO(Long cveUbicacionObra) {
		this.cveUbicacionObra = cveUbicacionObra;
	}

	public UbicacionObraDTO(Long cveUbicacionObra, String calle,
			String numExterior,String numExteriorAlf, String numExteriorDos,String numInteriorAlf, String numInterior, String codigoPostal, String refEntidad, 
			String refMunicipio,String refColonia,String refObservacion,String refPosterior, String refPrimaria, String refSecundaria,
			int cveEntidad, int cveMunicipio, int cveLocalidad) {
		this.cveUbicacionObra = cveUbicacionObra;
		this.calle = calle;
		this.numExterior = numExterior;
		this.numExteriorAlf = numExteriorAlf;
		this.numExteriorDos = numExteriorDos;
		this.numInteriorAlf = numInterior;		
		this.numInterior = numInterior;
		this.codigoPostal = codigoPostal;
		this.refEntidad = refEntidad;
		this.refMunicipio = refMunicipio;
		this.cveEntidad = cveEntidad;
		this.cveMunicipio = cveMunicipio;
		this.cveLocalidad = cveLocalidad;
		this.refColonia = refColonia;
		this.refObservacion = refObservacion;
		this.refPosterior = refPosterior;
		this.refPrimaria = refPrimaria;
		this.refSecundaria = refSecundaria;
	}

	public Long getCveUbicacionObra() {
		return this.cveUbicacionObra;
	}

	public void setCveUbicacionObra(Long cveUbicacionObra) {
		this.cveUbicacionObra = cveUbicacionObra;
	}


	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumExterior() {
		return this.numExterior;
	}

	public void setNumExterior(String numExterior) {
		this.numExterior = numExterior;
	}

	
	/**
	 * @return the numExteriorAlf
	 */
	public String getNumExteriorAlf() {
		return numExteriorAlf;
	}

	/**
	 * @param numExteriorAlf the numExteriorAlf to set
	 */
	public void setNumExteriorAlf(String numExteriorAlf) {
		this.numExteriorAlf = numExteriorAlf;
	}

	/**
	 * @return the numExteriorDos
	 */
	public String getNumExteriorDos() {
		return numExteriorDos;
	}

	/**
	 * @param numExteriorDos the numExteriorDos to set
	 */
	public void setNumExteriorDos(String numExteriorDos) {
		this.numExteriorDos = numExteriorDos;
	}

	/**
	 * @return the numInteriorAlf
	 */
	public String getNumInteriorAlf() {
		return numInteriorAlf;
	}

	/**
	 * @param numInteriorAlf the numInteriorAlf to set
	 */
	public void setNumInteriorAlf(String numInteriorAlf) {
		this.numInteriorAlf = numInteriorAlf;
	}

	public String getNumInterior() {
		return this.numInterior;
	}

	public void setNumInterior(String numInterior) {
		this.numInterior = numInterior;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getRefEntidad() {
		return this.refEntidad;
	}

	public void setRefEntidad(String refEntidad) {
		this.refEntidad = refEntidad;
	}

	public String getRefMunicipio() {
		return this.refMunicipio;
	}

	public void setRefMunicipio(String refMunicipio) {
		this.refMunicipio = refMunicipio;
	}

	/**
	 * @return the refColonia
	 */
	public String getRefColonia() {
		return refColonia;
	}

	/**
	 * @param refColonia the refColonia to set
	 */
	public void setRefColonia(String refColonia) {
		this.refColonia = refColonia;
	}

	/**
	 * @return the refObservacion
	 */
	public String getRefObservacion() {
		return refObservacion;
	}

	/**
	 * @param refObservacion the refObservacion to set
	 */
	public void setRefObservacion(String refObservacion) {
		this.refObservacion = refObservacion;
	}
	

	/**
	 * @return the refPosterior
	 */
	public String getRefPosterior() {
		return refPosterior;
	}

	/**
	 * @param refPosterior the refPosterior to set
	 */
	public void setRefPosterior(String refPosterior) {
		this.refPosterior = refPosterior;
	}

	/**
	 * @return the refPrimaria
	 */
	public String getRefPrimaria() {
		return refPrimaria;
	}

	/**
	 * @param refPrimaria the refPrimaria to set
	 */
	public void setRefPrimaria(String refPrimaria) {
		this.refPrimaria = refPrimaria;
	}

	/**
	 * @return the refSecundaria
	 */
	public String getRefSecundaria() {
		return refSecundaria;
	}

	/**
	 * @param refSecundaria the refSecundaria to set
	 */
	public void setRefSecundaria(String refSecundaria) {
		this.refSecundaria = refSecundaria;
	}

	public int getCveEntidad() {
		return this.cveEntidad;
	}

	public void setCveEntidad(int cveEntidad) {
		this.cveEntidad = cveEntidad;
	}

	public int getCveMunicipio() {
		return this.cveMunicipio;
	}

	public void setCveMunicipio(int cveMunicipio) {
		this.cveMunicipio = cveMunicipio;
	}

	public int getCveLocalidad() {
		return this.cveLocalidad;
	}

	public void setCveLocalidad(int cveLocalidad) {
		this.cveLocalidad = cveLocalidad;
	}

}
