#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp

obtenerInformacionRenapo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
obtenerInformacionRenapo.url=obtenerInformacionRenapo

seguimientoTramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
seguimientoTramite.url=seguimientoTramite

folioTramite.(class)=org.springframework.web.servlet.view.tiles2.TilesView
folioTramite.url=folioTramite

capturarDomicilioRegistro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturarDomicilioRegistro.url=capturarDomicilioRegistro

registroSolicitudCDAResponsable.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroSolicitudCDAResponsable.url=registroSolicitudCDAResponsable

inicioRegistroCDACURP.(class)=org.springframework.web.servlet.view.tiles2.TilesView
inicioRegistroCDACURP.url=correccionDatosAseguradoAltaInit

datosAdicionalesHistoriaLaboral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosAdicionalesHistoriaLaboral.url=datosAdicionalesHistoriaLaboral

datosHistoriaLaboral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosHistoriaLaboral.url=datosHistoriaLaboral

informacionHistoriaLaboral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
informacionHistoriaLaboral.url=informacionHistoriaLaboral

respuesta.(class)=org.springframework.web.servlet.view.tiles2.TilesView
respuesta.url=respuesta

confirmarDatosSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmarDatosSolicitud.url=confirmarDatosSolicitud

domicilioAclaracion.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilioAclaracion.url=domicilioAclaracion

atencionResponsable.(class)=org.springframework.web.servlet.view.tiles2.TilesView
atencionResponsable.url=atencionResponsable

capturarDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
capturarDomicilio.url=capturarDomicilio

cancelarSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cancelarSolicitud.url=cancelarSolicitud

atencionAutorizador.(class)=org.springframework.web.servlet.view.tiles2.TilesView
atencionAutorizador.url=atencionAutorizador

recursoNoDisponible.(class)=org.springframework.web.servlet.view.tiles2.TilesView
recursoNoDisponible.url=recursoNoDisponible

responsableSeguimiento.(class)=org.springframework.web.servlet.view.tiles2.TilesView
responsableSeguimiento.url=responsableSeguimiento

datosNSS.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosNSS.url=datosNSS

vistaReportes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
vistaReportes.url=vistaReportes

cuentaIndividual.(class)=org.springframework.web.servlet.view.tiles2.TilesView
cuentaIndividual.url=cuentaIndividual

datosBeneficiarioRepresentante.(class)=org.springframework.web.servlet.view.tiles2.TilesView
datosBeneficiarioRepresentante.url=datosBeneficiarioRepresentante
