<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://servicios.flujocontrol.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://servicios.flujocontrol.com/" name="Services">
<types>
<xsd:schema>
<xsd:import namespace="http://servicios.flujocontrol.com/" schemaLocation="file:/xsdl_jonima.xml"/>
</xsd:schema>
</types>
<message name="CreateDocument">
<part name="parameters" element="tns:CreateDocument"/>
</message>
<message name="CreateDocumentResponse">
<part name="parameters" element="tns:CreateDocumentResponse"/>
</message>
<message name="RefreshToken">
<part name="parameters" element="tns:RefreshToken"/>
</message>
<message name="RefreshTokenResponse">
<part name="parameters" element="tns:RefreshTokenResponse"/>
</message>
<message name="ExecuteProcedure">
<part name="parameters" element="tns:ExecuteProcedure"/>
</message>
<message name="ExecuteProcedureResponse">
<part name="parameters" element="tns:ExecuteProcedureResponse"/>
</message>
<message name="Authenticate">
<part name="parameters" element="tns:Authenticate"/>
</message>
<message name="AuthenticateResponse">
<part name="parameters" element="tns:AuthenticateResponse"/>
</message>
<message name="CreateUser">
<part name="parameters" element="tns:CreateUser"/>
</message>
<message name="CreateUserResponse">
<part name="parameters" element="tns:CreateUserResponse"/>
</message>
<portType name="Services">
<operation name="CreateDocument">
<input wsam:Action="http://servicios.flujocontrol.com/Services/CreateDocumentRequest" message="tns:CreateDocument"/>
<output wsam:Action="http://servicios.flujocontrol.com/Services/CreateDocumentResponse" message="tns:CreateDocumentResponse"/>
</operation>
<operation name="RefreshToken">
<input wsam:Action="http://servicios.flujocontrol.com/Services/RefreshTokenRequest" message="tns:RefreshToken"/>
<output wsam:Action="http://servicios.flujocontrol.com/Services/RefreshTokenResponse" message="tns:RefreshTokenResponse"/>
</operation>
<operation name="ExecuteProcedure">
<input wsam:Action="http://servicios.flujocontrol.com/Services/ExecuteProcedureRequest" message="tns:ExecuteProcedure"/>
<output wsam:Action="http://servicios.flujocontrol.com/Services/ExecuteProcedureResponse" message="tns:ExecuteProcedureResponse"/>
</operation>
<operation name="Authenticate">
<input wsam:Action="http://servicios.flujocontrol.com/Services/AuthenticateRequest" message="tns:Authenticate"/>
<output wsam:Action="http://servicios.flujocontrol.com/Services/AuthenticateResponse" message="tns:AuthenticateResponse"/>
</operation>
<operation name="CreateUser">
<input wsam:Action="http://servicios.flujocontrol.com/Services/CreateUserRequest" message="tns:CreateUser"/>
<output wsam:Action="http://servicios.flujocontrol.com/Services/CreateUserResponse" message="tns:CreateUserResponse"/>
</operation>
</portType>
<binding name="ServicesPortBinding" type="tns:Services">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="CreateDocument">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
<operation name="RefreshToken">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
<operation name="ExecuteProcedure">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
<operation name="Authenticate">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
<operation name="CreateUser">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="Services">
<port name="ServicesPort" binding="tns:ServicesPortBinding">
<soap:address location="https://jonima.com.mx/PerfectTask/Services"/>
</port>
</service>
</definitions>