
package mx.gob.imss.service.pagoscfdi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSConsPagosCFDIRegPatron", targetNamespace = "http://pagoscfdi.service.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSConsPagosCFDIRegPatron {


    /**
     * 
     * @param request
     * @return
     *     returns mx.gob.imss.service.pagoscfdi.Response
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "obtienePagoCFDI", targetNamespace = "http://pagoscfdi.service.imss.gob.mx/", className = "mx.gob.imss.service.pagoscfdi.ObtienePagoCFDI")
    @ResponseWrapper(localName = "obtienePagoCFDIResponse", targetNamespace = "http://pagoscfdi.service.imss.gob.mx/", className = "mx.gob.imss.service.pagoscfdi.ObtienePagoCFDIResponse")
    Response obtienePagoCFDI(
        @WebParam(name = "request", targetNamespace = "")
        MessageWSConsPagosCFDIRegPatron request);

}
