1=ENE|Enero
2=FEB|Febrero
3=MAR|Marzo
4=ABR|Abril
5=MAY|Mayo
6=JUN|Junio
7=JUL|Julio
8=AGO|Agosto
9=SEP|Septiembre
10=OCT|Octubre
11=NOV|Noviembre
12=DIC|Diciembre
13=S/M|S/M
0=S/M|S/M
ENE=1
FEB=2
MAR=3
ABR=4
MAY=5
JUN=6
JUL=7
AGO=8
SEP=9
OCT=10
NOV=11
DIC=12
S/M=13
S/M=0

en1 = AS
en2 = BC
en3 = BS
en4 = CC
en5 = CL
en6 = CM
en7 = CS
en8 = CH
en9 = DF
en10 = DG
en11 = GT
en12 = GR
en13 = HG
en14 = JC
en15 = MC
en16 = MN
en17 = MS
en18 = NT
en19 = NL
en20 = OC
en21 = PL
en22 = QT
en23 = QR
en24 = SP
en25 = SL
en26 = SR
en27 = TC
en28 = TS
en29 = TL
en30 = VZ
en31 = YN
en32 = ZS
en35 = ME

se1=HOMBRE
se2=MUJER