#Datos del ambiente de desarrollo QA
service.provider.url=${mvn.service.provider.url}
service.security.principal=${mvn.service.security.principal}
service.security.credentials=${mvn.service.security.credentials}
