package mx.gob.imss.ctirss.correccion.seguimiento.promocion.model;

public class ConsultasEstatusObra {
	
	public static String CONSULTA_INCIDENCIAS_DE_OBRA="select B.CVE_PK, B.CVE_FK_INCIDENCIA, "
	       + "D.DES_TIPINCIDENC AS TIPO_INCIDENCIA, B.FEC_FECHAINICIO_FC AS "
           + "FEC_INI_INCI, B.FEC_FECHATERMINO_FC AS FEC_FIN_INCI, "
	       + "B.FEC_FECHAREGISTRO_FC AS FEC_PRESENTACION_INCI "
           + "FROM SAT_INCIDENCIA B "
           + "LEFT JOIN SAT_OBRA A ON B.CVE_FK_OBRA=A.CVE_PK "
           + "LEFT JOIN SAC_TIPINCIDENC D ON D.CVE_PK=B.CVE_FK_INCIDENCIA "
           + "WHERE A.CVE_NROREGOBRA=:numRegObra ORDER BY 1,3,5";
	
	
	public static String CONSULTA_RELACIONES_DE_TRABAJADORES="select A.CVE_NROREGOBRA, "
			+ "A.FEC_FECHAINICIO_FC AS FEC_INICIAL, A.FEC_FECHATERMINO_FC AS FEC_FINAL,"
            + "C.NUM_PERIODO, C.FEC_FECHAREGISTRO_FC AS FEC_PRESENTA_REL "
            + "FROM SAT_OBRA A LEFT JOIN SAT_RELTRABAJADORES C ON C.CVE_FK_OBRA=A.CVE_PK "
            + "WHERE A.CVE_NROREGOBRA=:numRegObra and C.NUM_PERIODO is not null ORDER BY 2,3,4";


	public static String CONSULTA_RELACIONES_DE_TRABAJADORES_NUEVO = " SELECT * FROM " +
			" ( " +
			" SELECT A.CVE_NROREGOBRA, A.FEC_FECHAINICIO_FC AS FEC_INICIAL, A.FEC_FECHATERMINO_FC AS FEC_FINAL " +
			" , A.NUM_PERIODO AS PERIODOSPRESENTADOS, A.FEC_FECHAREGISTRO_FC  AS FEC_PRESENTA_REL " +
			" FROM (" +
			" " +
			" SELECT O.CVE_NROREGOBRA, O.FEC_FECHAINICIO_FC, O.FEC_FECHATERMINO_FC, " +
			" RT.NUM_PERIODO, RT.IND_RELACIONINICIAL," +
			" RT.FEC_FECHAREGISTRO_FC, RT.REF_LUGARREGISTRO, " +
			" O.CVE_PK CVE_PK_OBRA, O.CVE_FK_OBRAPRINCIPAL, RT.CVE_PK CVE_PK_RELTRABAJADORES " +
			" FROM SAT_OBRA O, SAT_RELTRABAJADORES RT " +
			" WHERE O.CVE_PK = RT.CVE_FK_OBRA " +
			" AND O.CVE_NROREGOBRA = :numRegObra " +
			" ) A " +
			" GROUP BY A.CVE_NROREGOBRA, A.FEC_FECHAINICIO_FC, A.FEC_FECHATERMINO_FC, A.NUM_PERIODO ,A.FEC_FECHAREGISTRO_FC " +
			" ) X, (SELECT TO_CHAR(ADD_MONTHS(TRUNC(TO_DATE('10/03/2013','DD/MM/YYYY'), 'mm'), 1 - ROWNUM),'yyyymm') AS PERIODOS " +
			" FROM DUAL " +
			" CONNECT BY LEVEL < (MONTHS_BETWEEN(TO_DATE('10/03/2013','DD/MM/YYYY'), TRUNC(TO_DATE('10/03/2011','DD/MM/YYYY'), 'mm')) + 1)) Y " +
			" WHERE X.PERIODOSPRESENTADOS(+) = Y.PERIODOS " +
			" and PERIODOSPRESENTADOS is not null " +
			" ORDER BY PERIODOS ";
}



