#NOTA: Cuando el parámetro sea texto y contega comas, es necesario escaparlas

#URL en filesystem
url_archivo = file:/share/oracle/zapdir01_domain/zapdir_cluster1/properties/params.properties

##############################################
###### PARAMETROS CARTA NO ADEUDO (32D) ######
##############################################
32D.ind_mostrar_msg_num_pat = true
32D.msg_num_pat = En la secci\u00F3n de \u0022Mis registros patronales\u0022\, no se muestran la totalidad de los registros patronales asociados a su RFC; sin embargo\, la \u0022Opini\u00F3n de cumplimiento de obligaciones en materia de Seguridad Social\u0022 se emite por la totalidad de los registros patronales asociados a su RFC.