<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" targetNamespace="http://mx.gob.imss.delta.global.service/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="validacionApartadoARequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nss" type="xs:string" />
				<xs:element name="cveAsignacion" type="xs:long" />
				<xs:element name="indicadorApartadoC" type="xs:boolean" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="validacionApartadoAResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="indDerechoBeneficioApartadoA" type="xs:boolean" />
				<xs:element name="motivoDeRechazo" type="xs:string" />
				<xs:element name="exito" type="xs:int" />
				<xs:element name="claveError" type="xs:int" />
				<xs:element name="descripcion" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>