
package mx.gob.imss.webservices.patrones.servicio;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.core.io.Resource;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConsPatronesVigXAsigServices", targetNamespace = "http://mx/gob/imss/webservices/patrones/servicio", wsdlLocation = "classpath:ConsPatronesVigXAsigService.wsdl")
public class ConsPatronesVigXAsigServices
    extends Service
{

    private final static URL CONSPATRONESVIGXASIGSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.webservices.patrones.servicio.ConsPatronesVigXAsigServices.class.getName());
    private final static int serviceTimeOut = 10000;
    private final static int connectTimeOut = 5000;
    private static DefaultResourceLoader loader= new DefaultResourceLoader(); 
    private static Resource resource = loader.getResource("classpath:ConsPatronesVigXAsigService.wsdl"); 
    
    static {
        URL url = null;
        try {
            url = resource.getURL();
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'classpath:ConsPatronesVigXAsigService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (IOException e) {
			e.printStackTrace();
		}
        CONSPATRONESVIGXASIGSERVICES_WSDL_LOCATION = url;
    }

    public ConsPatronesVigXAsigServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsPatronesVigXAsigServices() {
        super(CONSPATRONESVIGXASIGSERVICES_WSDL_LOCATION, new QName("http://mx/gob/imss/webservices/patrones/servicio", "ConsPatronesVigXAsigServices"));
    }

    /**
     * 
     * @return
     *     returns ConsPatronesVigXAsigService
     */
    @WebEndpoint(name = "ConsPatronesVigXAsigServiceSoap11")
    public ConsPatronesVigXAsigService getConsPatronesVigXAsigServiceSoap11() {
    	ConsPatronesVigXAsigService ws = super.getPort(new QName("http://mx/gob/imss/webservices/patrones/servicio", "ConsPatronesVigXAsigServiceSoap11"), ConsPatronesVigXAsigService.class);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
      	return ws;
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsPatronesVigXAsigService
     */
    @WebEndpoint(name = "ConsPatronesVigXAsigServiceSoap11")
    public ConsPatronesVigXAsigService getConsPatronesVigXAsigServiceSoap11(WebServiceFeature... features) {
    	ConsPatronesVigXAsigService ws = super.getPort(new QName("http://mx/gob/imss/webservices/patrones/servicio", "ConsPatronesVigXAsigServiceSoap11"), ConsPatronesVigXAsigService.class, features);
    	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.internal.ws.connect.timeout", connectTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.request.timeout", serviceTimeOut);
      	((BindingProvider) ws).getRequestContext().put("com.sun.xml.ws.connect.timeout", connectTimeOut);
      	return ws;
    }

}
