/**
 * 
 */
package mx.gob.imss.ctirss.delta.model.gestion.patronal;

import java.util.HashMap;
import java.util.Map;

/**
 *  
 *  @Cliente: Instituto Mexicano del Seguro Social
 *  @Autor: Hugo Armando Mart-nez Cham-nica
 *  @Proyecto: delta
 *  @Archivo: TipoTramiteEnum.java
 *  @Paquete: mx.gob.imss.ctirss.delta.model.gestion.patronal
 *  @Fecha: 11:27:47
 */
public enum TipoTramiteEnum {
	DEFAULT(0),
	ALTA_SRT(1),
	ACTUALIZACION_DATOS_GENERALES(2),
	ACTUALIZACION_DENOMINACION_SOCIAL(2),
	ACTUALIZACION_DATOS_CONTACTO(3),
	ACTUALIZACION_ESCRITURA_CONSTITUTIVA(4),
	ACTUALIZACION_REGISTRO_SINDICATO(5),
	ACTUALIZACION_DOMICILIO_PARTICULAR(6),
	//ACTUALIZACION_DOMICILIO_FISCAL(6),
	ACTUALIZACION_CENTRO_TRABAJO(7),
	ACTUALIZACION_SOCIO(8),	//ALTA SOCIO
	ACTUALIZACION_REPRESENTANTE_LEGAL(9),
	PERSONAS_AUTORIZADAS(10),//PERSONAS AUTORIZADAS
	ACTIVIDAD_ECONOMICA(11),//ACTIV ECONOMICA (D)
	DISPOSICION_DE_LEY(12),//DISPOSICION DE LEY (E)
	INCORPORACION_DE_ACTIVIDADES(13),//INCORPORACION DE ACTIVIDADES (F)
//	CLASIFICACION_G(24),
//	CLASIFICACION_H(25),
//	CLASIFICACION_I(26),
	COMPRA_DE_ACTIVOS(14),//COMPRA DE ACTIVOS (J)
	COMODATO(15),//COMODATO (K)
	ENAJENACION(16),//ENAJENACION (L)
	ARRENDAMIENTO(17),//ARRENDAMIENTO (M)
	FIDEICOMISO_TRASLATIVO(18),//FIDEICOMISO TRASLATIVO (N)
	ESCISION(19),//ESCISION (O)
	SUSTITUCION_PATRONAL(20),//SUST PATRONAL (P)
	FUSION(21),//FUSION (Q)
	REANUDACION_DE_ACTIVIDADES(22),//REANUDACION ACTIVIDADES (R)
	REGISTRO_DE_DERECHOHABIENTE(23),
	MODIFICACION_DE_DERECHOHABIENTE(24),
	BAJA_DE_DERECHOHABIENTE_POR_DEFUNCION(25),
	BAJA_DE_DERECHOHABIENTE_POR_TERMINO_DE_CONCUBINATO(26),
	BAJA_DE_DERECHOHABIENTE_POR_DIVORCIO(27),
	BAJA_DE_DERECHOHABIENTE_POR_TERMINO_DE_CONVIVENCIA(28),
	PRORROGA_POR_ESTUDIOS(29),
	PRORROGA_POR_ENFERMEDAD_CRONICA_PSIQUICA_FISICA(30),
	PRORROGA_POR_VIGENCIA_PERMANENTE(31),
	PRORROGA_POR_VIGENCIA_TEMPORAL(32),
	PRORROGA_POR_ACUERDOS_HCCD_HCT(33),
	PRORROGA_POR_SERVICIOS_OBSTETRICOS(34),
	PRORROGA_POR_LAUDO(35),
	CAMBIO_CLINICA(36),
	CAMBIO_CONSULTORIO_TURNO(37),
	AUTORIZACION_SERVICIOS_CIRCUNSCRIPCION_FORANEA(38),
	SUSPENSION_SERVICIOS_CIRCUNSCRIPCION_FORANEA(39),
	PRORROGA_POR_ENFERMEDAD_CRONICA_PSIQUICA_FISICA_25(40),
	ASIGNACION_CONSULTORIO_TURNO_MEDICO(41),
	REGISTRO_DE_PERSONA(42),
	ASIGNACION_NSS(43),
	REGISTRO_ASEGURADO(44),
	REGISTRO_PENSIONADO(45),
	REGISTRO_CONCUBINA_RIO(46),
	REGISTRO_CONYUGUE(47),
	REGISTRO_HIJOS(48),
	REGISTRO_PADRES(49),
	BAJA_PATRONAL(50),
	AMPLIACION_MODALIDAD(51),
	APERTURA_SUCESION(52),
	HUELGA(53),
	MATRIZ_SUCURSAL(54),
	RPU(55),
	REGISTRO_CONTRATOS_OUTSOURCING(56),
	REPOSICION_TIP(57),
	SUSPENSION(58),
	CIERRE_ACTIVIDADES(59),
	DUPLICIDAD(60),
	CANCELACION_RPC(61),
	CAMBIO_DE_CLINICA_MASIVO(62),
	PRORROGA_POR_INVALIDEZ(63),
	CLASIFICACION_ANEXO_V(64),
	RECTIFICACION_DE_LA_CLASIFICACION_POR_PROCESO_DE_ANALISIS(74),
	RECTIFICACION_POR_ERROR_EN_EL_ANALISIS(75),
	ALTA_USUARIOS_SSO(76),
	BAJA_REPRESENTANTE_LEGAL(77),
	BAJA_PERSONA_AUTORIZADA(78),
	RECUPERACION_REGISTRO_PATRONAL(79),
	ACTUALIZACION_CUENTA_USUARIO(80),
	IMPRESION_SITUACION_ADEUDO(81),
	IMPRESON_SITUACION_COBRO_RCV(82),
	IMPRESION_TIPO_COBRO(83),
	IMPRESION_TIPO_COBRO_RCV(84),
	LOCALIZACION_NSS(85),
	ACTUALIZACION_DATOS_ASEGURADO(86),
	CONSULTA_DE_SEMANAS_COTIZADAS(87),
	ACTUALIZACION_DATOS_USUARIO(90),
	ASIGNACION_MASIVA_NSS_SIE(88),
	ALTA_RIF(91),
	BAJA_RIF(89),
	REGISTRO_PERSONA_MORAL(92),
	REIMPRESION_SAV002(93),
	COMPROBANTE_DE_VIGENCIA_DE_DERECHOHAB(94),
	CARTILLA_NACIONAL_DE_SALUD(95),
	TARJETA_DE_ADSCRIPCION_430A5(96),
	SOLICITUD_CORRECCION_PATRONAL(97),
	PRESENTACION_CORRECCION_PATRONAL(98),
	PRORROGA_CORRECCION_PATRONAL(99),
	IMPRESION_COMPROBANTE_FISCAL_CFDI(100),
	ASIGNACION_DE_DOMICILIO_PARTICULAR_DH (101),
	BAJA_DE_DERECHOHABIENTE_POR_AUTORIDAD_NORMATIVA(102),
	BAJA_SOCIO(103),
	SOLICITUD_DE_PENSION_POR_CESANTIA(104),
	SOLICITUD_DE_PENSION_POR_VEJEZ(105),
	SOLICITUD_DE_PENSION_POR_RETIRO_ANTICIPADO(106),
	SOLICITUD_DE_PENSION_POR_INCAPACIDAD_PERMANENTE_PARCIAL(107),
	SOLICITUD_DE_PENSION_POR_INCAPACIDAD_PERMANENTE_TOTAL(108),
	SOLICITUD_DE_INDEMNIZACION_GLOBAL(109),
	SOLICITUD_DE_PENSION_INVALIDEZ(110),
	SOLICITUD_DE_PENSION_DE_ASCENDIENTES(111),
	SOLICITUD_DE_PENSION_DE_VIUDEZ(112),
	SOLICITUD_DE_PENSION_DE_ORFANDAD(113),
	SOLICITUD_DE_PENSION_DE_VIUDEZ_ORFANDAD(114),
	CERTIFICACION_RETIRO_DESEMPLEO(115),
	CARTA_NO_ADEUDO(116),
	CONSULTA_DE_VIGENCIA_DE_DERECHOS(117),
	COMPRA_SEGURO_INDIVIDUAL(118),
	RENOVACION_SEGURO_INDIVIDUAL(119),
	ALTA_SRT_PM(120),
	COMPRA_SEGURO_DOMESTICO(121),
    RENOVACION_SEGURO_DOMESTICO(122),
    INACTIVIDAD_PAGO_PARCIALIDADES(123),
    COMPRA_SEGURO_FAMILIAR(124),
    COMPRA_CONTINUACION_VOLUNTARIA(125),
    ACTUALIZACION_CURP_ASEGURADO(126),
    BAJA_ADMINISTRATIVA(134),
    SUSPENCION_ADMINISTRATIVA(135),
    REACTIVACION_ADMINISTRATIVA(136),
    CONSULTA_RIESGOS_TRABAJO_TERMINADOS(138),
    CORRECCION_DATOS_ASEGURADO(139),
    RENOVACION_SEGURO_FAMILIAR(144),
    RENOVACION_CONTINUACION_VOLUNTARIA(145),
    ACEPTACION_TERMINOS_CONDICIONES(146),
    REGISTRO_EMBARAZADA_SPPM (147),
	REGISTRO_CITA_SPPM (148),
	COMPARA_DATOS(149),
	REGISTRO_ACUERDO_DERECHOHAB(154),
	REGISTRO_ESCRITO_DESACUERDO(155),
	SUSTITUCION_PATRONAL_SUBCONTRATACION(175),//SUST PATRONAL POR SUBCONTRATACION (P)
	CAMBIO_DE_DOMICILIO_DIFERENTE_MUNICIPIO(176);
			
	private Integer codigo;
		
	private final static Map<String, TipoTramiteEnum> hashNames = new HashMap<String, TipoTramiteEnum>();
	private final static Map<Integer,TipoTramiteEnum> hashCodes = new HashMap<Integer,TipoTramiteEnum>();
	
	static{ 
		for(TipoTramiteEnum tramite : TipoTramiteEnum.values()){
			hashNames.put(tramite.name(), tramite);
			hashCodes.put(tramite.getCodigo(), tramite);
		}
	}
	
	private TipoTramiteEnum(Integer valor){
		this.codigo=valor;
		
	}
	
	public Integer getCodigo() {
		return codigo;
	}
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	
	public static TipoTramiteEnum obtenerEnumByName(String name){
		return hashNames.get(name);
	}
	
	public static TipoTramiteEnum obternerEnumById(Integer codigo){
		return hashCodes.get(codigo);
	}
}
