##################
# FTP FileConfig #
##################
#filesystem.sie.output.url=pruebaAutomatizacion
filesystem.sie.output.url=../../idse/data/procesos/afiliacion/estudiantes


################
# Servidor ftp #
################
ftp.server.url=172.24.116.23
ftp.server.user=rpadmin
ftp.server.passwd=rpadmin
ftp.server.port=21

application.mode=test


##################
# Ruta de origen #
##################
#file.sie.input.url=/sindo/ftp/estudiante/file/layout
file.sie.input.url=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/estudiante/file/layout


####################
# Ruta de respaldo #
####################
#file.sie.resp.url=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/ESTUDIANTE_HIST
file.sie.resp.url=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/ESTUDIANTE_HIST
file.sie.resp.origen=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/estudiante/file


################
# Archivos SIE #
################
sie.file.sie01=SIEArchivoBase


##########################
# Archivos de validacion #
##########################

#filesystem.delta.proceso.estatus=/share/oracle/osbapdir01_domain/osb_cluster1/ftp
filesystem.delta.proceso.estatus=/ctirss/w/servicios4/srvs04/domains/d_osb/delta/estudiante/bloq
