package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.ClasificacionObraDTO;
import mx.gob.imss.csdiss.sdroc.dto.TipoObraDTO;

/**
 * RocTipoObra generated by hbm2java
 */
@Entity
@Table(name = "ROC_TIPO_OBRA", schema = "MGPROC01")
@Transactional
public class RocTipoObra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4943022634302990066L;
	
	private Long cveTipoObra;
	private String desTipoObra;
	private RocClasificacionObra rocClasificacionObra;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocTipoObra() {
	}

	public RocTipoObra(Long cveTipoObra, RocClasificacionObra rocClasificacionObra) {
		this.cveTipoObra = cveTipoObra;
		this.rocClasificacionObra = rocClasificacionObra;
	}

	public RocTipoObra(Long cveTipoObra,RocClasificacionObra rocClasificacionObra, String desTipoObra, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveTipoObra = cveTipoObra;
		this.rocClasificacionObra = rocClasificacionObra;
		this.desTipoObra = desTipoObra;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id
	@Column(name = "CVE_ID_TIPO_OBRA", unique = true, nullable = false)
	public Long getCveTipoObra() {
		return this.cveTipoObra;
	}

	public void setCveTipoObra(Long cveTipoObra) {
		this.cveTipoObra = cveTipoObra;
	}
	
	@ManyToOne(fetch=FetchType.EAGER,optional = false)
	@JoinColumn(name = "CVE_ID_CLASIFICACION_OBRA", nullable = false)
	public RocClasificacionObra getRocClasificacionObra() {
		return this.rocClasificacionObra;
	}

	public void setRocClasificacionObra(RocClasificacionObra rocClasificacionObra) {
		this.rocClasificacionObra = rocClasificacionObra;
	}

	@Column(name = "DES_TIPO_OBRA", length = 80)
	public String getDesTipoObra() {
		return this.desTipoObra;
	}

	public void setDesTipoObra(String desTipoObra) {
		this.desTipoObra = desTipoObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	
	public TipoObraDTO toConvertTipoObraDTO(){
		TipoObraDTO tipoObraDTO = new TipoObraDTO();
		
		tipoObraDTO.setCveTipoObra(this.getCveTipoObra());
		tipoObraDTO.setDesTipoObra(this.getDesTipoObra());
		tipoObraDTO.setClasificacionObraDTO(this.getRocClasificacionObra().toConvertClasificacionObraDTO());
		
		return tipoObraDTO;
	}
	
	

}
