package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.AvisoObraDTO;

/**
 * RotInformacionObra generated by hbm2java
 */
@Entity
@Table(name = "ROT_AVISO_OBRA", schema = "MGPROC01")
@Transactional
public class RotAvisoObra implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -5423761108487486336L;
	private Long cveAvisoObra;
	private RocSubdelegacion rocSubdelegacion;
	private RotInformacionPatron rotInformacionPatron;
	private RotUbicacionObra rotUbicacionObra;
	private String cveRegistroAvisoObra;
	private String cveRfcPatron;
	private Date fecIniObra;
	private Date fecFinObra;
	private Double impObra;
	private String refAcuseReg;	
	private String refCadenaOriginal;
	private String refSelloDigital;
	private String refSeqNotarial;
	private String refNumSerie;		
	private Boolean refEstadoReg;
	private String cveUsuarioCreaReg;
	private String cveUsuarioModificaReg;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;
	private Long cveIdTramite;
	private String numSeqNotaria;
	
	
	

	public RotAvisoObra() {
	}

	public RotAvisoObra(Long cveAvisoObra, RocSubdelegacion rocSubdelegacion, RotUbicacionObra rotUbicacionObra,
			RotInformacionPatron rotInformacionPatron, String cveRegistroAvisoObra) {
		this.cveAvisoObra = cveAvisoObra;
		this.rocSubdelegacion = rocSubdelegacion;
		this.rotInformacionPatron = rotInformacionPatron;
		this.cveRegistroAvisoObra = cveRegistroAvisoObra;
		this.rotUbicacionObra = rotUbicacionObra;
	}

	public RotAvisoObra(Long cveAvisoObra, RocSubdelegacion rocSubdelegacion, 
			RotInformacionPatron rotInformacionPatron, String cveRegistroAvisoObra, String cveRfcPatron,Date fecIniObra, Date fecFinObra, Double impObra,
			String refAcuseReg,String refCadenaOriginal, String refSelloDigital,String refSeqNotarial,String refNumSerie, 
			RotUbicacionObra rotUbicacionObra, Boolean refEstadoReg, String cveUsuarioCreaReg, String cveUsuarioModificaReg, 
			Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado,Long cveIdTramite,String numSeqNotaria) {

		this.cveAvisoObra = cveAvisoObra;
		this.rocSubdelegacion = rocSubdelegacion;
		this.rotInformacionPatron = rotInformacionPatron;
		this.rotUbicacionObra = rotUbicacionObra;
		this.cveRegistroAvisoObra = cveRegistroAvisoObra;
		this.fecIniObra = fecIniObra;
		this.fecFinObra = fecFinObra;
		this.impObra = impObra;
		this.refAcuseReg = refAcuseReg;
		this.refEstadoReg = refEstadoReg;
		this.refCadenaOriginal = refCadenaOriginal;
		this.refSelloDigital = refSelloDigital;
		this.refSeqNotarial = refSeqNotarial;
		this.refNumSerie = refNumSerie;
		this.cveRfcPatron = cveRfcPatron;
		this.cveUsuarioCreaReg = cveUsuarioCreaReg;
		this.cveUsuarioModificaReg = cveUsuarioModificaReg;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
		this.cveIdTramite = cveIdTramite;
		this.numSeqNotaria = numSeqNotaria;
		
	}

	@Id

	@Column(name = "CVE_ID_AVISO_OBRA", unique = true, nullable = false)	
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_informacion_obra")
	@SequenceGenerator(name="seq_informacion_obra", schema="public", sequenceName="SEQ_ROTAVISOOBRA", allocationSize=1)	
	public Long getCveAvisoObra() {
		return this.cveAvisoObra;
	}

	public void setCveAvisoObra(Long cveAvisoObra) {
		this.cveAvisoObra = cveAvisoObra;
	}

	@ManyToOne
	@JoinColumn(name = "CVE_ID_SUBDELEGACION", nullable = false)
	public RocSubdelegacion getRocSubdelegacion() {
		return this.rocSubdelegacion;
	}

	public void setRocSubdelegacion(RocSubdelegacion rocSubdelegacion) {
		this.rocSubdelegacion = rocSubdelegacion;
	}

	@ManyToOne(cascade=CascadeType.ALL,optional=false,targetEntity=RotInformacionPatron.class)
	@JoinColumn(name = "CVE_ID_INFORMACION_PATRON", nullable = false)
	public RotInformacionPatron getRotInformacionPatron() {
		return this.rotInformacionPatron;
	}

	public void setRotInformacionPatron(RotInformacionPatron rotInformacionPatron) {
		this.rotInformacionPatron = rotInformacionPatron;
	}

	@Column(name= "CVE_REGISTRO_AVISO_OBRA", nullable = true)
	public String getCveRegistroAvisoObra() {
		return cveRegistroAvisoObra;
	}

	public void setCveRegistroAvisoObra(String cveRegistroAvisoObra) {
		this.cveRegistroAvisoObra = cveRegistroAvisoObra;
	}
	
	@Column(name = "CVE_RFC_PATRON", length = 20)
	public String getCveRfcPatron() {
		return this.cveRfcPatron;
	}

	public void setCveRfcPatron(String cveRfcPatron) {
		this.cveRfcPatron = cveRfcPatron;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INI_OBRA", length = 13)
	public Date getFecIniObra() {
		return this.fecIniObra;
	}

	public void setFecIniObra(Date fecIniObra) {
		this.fecIniObra = fecIniObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_OBRA", length = 13)
	public Date getFecFinObra() {
		return this.fecFinObra;
	}

	public void setFecFinObra(Date fecFinObra) {
		this.fecFinObra = fecFinObra;
	}

	@Column(name = "IMP_OBRA", precision = 17, scale = 17)
	public Double getImpObra() {
		return this.impObra;
	}

	public void setImpObra(Double impObra) {
		this.impObra = impObra;
	}


	@Column(name = "REF_ACUSE_REG")
	public String getRefAcuseReg() {
		return this.refAcuseReg;
	}

	public void setRefAcuseReg(String refAcuseReg) {
		this.refAcuseReg = refAcuseReg;
	}
	
	@Column(name = "REF_CADENA_ORIGINAL")
	public String getRefCadenaOriginal() {
		return refCadenaOriginal;
	}

	public void setRefCadenaOriginal(String refCadenaOriginal) {
		this.refCadenaOriginal = refCadenaOriginal;
	}

	@Column(name = "REF_SELLO_DIGITAL")
	public String getRefSelloDigital() {
		return refSelloDigital;
	}

	public void setRefSelloDigital(String refSelloDigital) {
		this.refSelloDigital = refSelloDigital;
	}

	@Column(name = "REF_SEQ_NOTARIA")	
	public String getRefSeqNotarial() {
		return refSeqNotarial;
	}

	public void setRefSeqNotarial(String refSeqNotarial) {
		this.refSeqNotarial = refSeqNotarial;
	}

	@Column(name = "REF_NUM_SERIE")
	public String getRefNumSerie() {
		return refNumSerie;
	}

	public void setRefNumSerie(String refNumSerie) {
		this.refNumSerie = refNumSerie;
	}
	

	@OneToOne(cascade = CascadeType.ALL,optional = false)
	@JoinColumn(name="CVE_ID_UBICACION_OBRA")
	public RotUbicacionObra getRotUbicacionObras() {
		return this.rotUbicacionObra;
	}

	public void setRotUbicacionObras(RotUbicacionObra rotUbicacionObra) {
		this.rotUbicacionObra = rotUbicacionObra;
	}
	
	@Column(name = "CVE_ID_USUARIO_CREA_REG")
	public String getCveUsuarioCreaReg() {
		return cveUsuarioCreaReg;
	}

	public void setCveUsuarioCreaReg(String cveUsuarioCreaReg) {
		this.cveUsuarioCreaReg = cveUsuarioCreaReg;
	}

	@Column(name = "CVE_ID_USUARIO_MODIFICA_REG")
	public String getCveUsuarioModificaReg() {
		return cveUsuarioModificaReg;
	}

	public void setCveUsuarioModificaReg(String cveUsuarioModificaReg) {
		this.cveUsuarioModificaReg = cveUsuarioModificaReg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}	
	
	@Column(name = "CVE_ID_TRAMITE")
	public Long getCveIdTramite() {
		return cveIdTramite;
	}

	public void setCveIdTramite(Long cveIdTramite) {
		this.cveIdTramite = cveIdTramite;
	}
	
	@Column(name = "NUM_SEQ_NOTARIA")
	public String getNumSeqNotaria() {
		return numSeqNotaria;
	}

	public void setNumSeqNotaria(String numSeqNotaria) {
		this.numSeqNotaria = numSeqNotaria;
	}
	
	
	@Column(name = "REF_ESTADO_REG")
	public Boolean getRefEstadoReg() {
		return refEstadoReg;
	}

	public void setRefEstadoReg(Boolean refEstadoReg) {
		this.refEstadoReg = refEstadoReg;
	}

	public AvisoObraDTO toConvertAvisoObraDTO(){
		AvisoObraDTO avisoObraDTO = new AvisoObraDTO();
		
		avisoObraDTO.setCveAvisoObra(this.getCveAvisoObra());
		avisoObraDTO.setCveRegistroAvisoObra(this.getCveRegistroAvisoObra());
		avisoObraDTO.setCveRfcPatron(this.getCveRfcPatron());
		avisoObraDTO.setFecFinObra(this.fecFinObra);
		avisoObraDTO.setFecIniObra(this.fecIniObra);
		avisoObraDTO.setImpObra(this.impObra);
		avisoObraDTO.setRefAcuseReg(this.refAcuseReg);
		avisoObraDTO.setStpCreaReg(this.getFecRegistroAlta());
		avisoObraDTO.setRefCadenaOriginal(this.getRefCadenaOriginal());
		avisoObraDTO.setRefSelloDigital(this.getRefSelloDigital());
		avisoObraDTO.setRefSeqNotarial(this.getRefSeqNotarial());
		avisoObraDTO.setRefNumSerie(this.getRefNumSerie());
		avisoObraDTO.setCveIdTramite(this.getCveIdTramite());
		avisoObraDTO.setNumSeqNotaria(this.getNumSeqNotaria());
		avisoObraDTO.setRefEstadoReg(this.refEstadoReg);
		
		
		if(this.getRocSubdelegacion() != null)
			avisoObraDTO.setSubDelegacionDTO(this.getRocSubdelegacion().toConvertSubdelegacionDTO());
		if(this.getRotUbicacionObras() != null)
			avisoObraDTO.setUbicacionObraDTO(this.getRotUbicacionObras().toConvertUbicacionObraDTO());
		if(this.getRotInformacionPatron() != null)
			avisoObraDTO.setInformacionPatronDTO(this.getRotInformacionPatron().toConvertInformacionPatronDTO());
		
		return avisoObraDTO;
	}
}