package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;


/**
 * RotInformacionObra generated by hbm2java
 */
@Entity
@Table(name = "ROT_INFORMACION_OBRA")
@Transactional
public class RotInformacionObra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3584909158989841151L;
	private Long cveInformacionObra;
	private RocSubdelegacion rocSubdelegacion;
	private RocTipoObra rocTipoObra;
	private RotInformacionPatron rotInformacionPatron;
	private RocObjetoContrato rocObjetoContrato;
	private String cveRegistroObra;
	private Long cveRegistroObraPrincipal;
	private Date fecIniObra;
	private Date fecFinObra;
	private Double impObra;
	private Double refSupConstruccion;
	private String refObservacion;
	private String numProcedimiento;
	private String numLicitacion;
	private Date fecIniContrato;
	private Date fecFinContrato;
	private Double impEjercido;
	private Double impContratado;
	private String refAcuseReg;
	private Date fecRegistroAlta;	
//	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;	
	private Set<RotInformacionIncidencia> rotInformacionIncidencias;
	private RotUbicacionObra rotUbicacionObra;
	private RocEstatusObra rocEstatusObra;
	private Integer numActualiza;
	private Long cveIdTramite;
	private String numSeqNotaria;
	private Date fecBloqueoObra;
	private String cveIdUsuarioBloqueo;
	private Long refCveAvisoObra;
	private String refOtroObjetoContrato;
	private Integer numAproxTrabajadores;
	private String numRegStps;
	private String refObjetoContratoSubEsp;
	private String cveObraRemplazado;

	@Id
	@Column(name = "CVE_ID_INFORMACION_OBRA", unique = true, nullable = false)	
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_informacion_obra")
	@SequenceGenerator(name="seq_informacion_obra", schema="public", sequenceName="SEQ_ROTINFORMACIONOBRA", allocationSize=1)	
	public Long getCveInformacionObra() {
		return this.cveInformacionObra;
	}

	public void setCveInformacionObra(Long cveInformacionObra) {
		this.cveInformacionObra = cveInformacionObra;
	}

	@ManyToOne
	@JoinColumn(name = "CVE_ID_SUBDELEGACION", nullable = false)
	public RocSubdelegacion getRocSubdelegacion() {
		return this.rocSubdelegacion;
	}

	public void setRocSubdelegacion(RocSubdelegacion rocSubdelegacion) {
		this.rocSubdelegacion = rocSubdelegacion;
	}

	@ManyToOne(optional=false,targetEntity=RocTipoObra.class)
	@JoinColumn(name = "CVE_ID_TIPO_OBRA")
	public RocTipoObra getRocTipoObra() {
		return this.rocTipoObra;
	}

	public void setRocTipoObra(RocTipoObra rocTipoObra) {
		this.rocTipoObra = rocTipoObra;
	}

	@ManyToOne(cascade=CascadeType.ALL,optional=false,targetEntity=RotInformacionPatron.class)
	@JoinColumn(name = "CVE_ID_INFORMACION_PATRON", nullable = false)
	public RotInformacionPatron getRotInformacionPatron() {
		return this.rotInformacionPatron;
	}

	public void setRotInformacionPatron(RotInformacionPatron rotInformacionPatron) {
		this.rotInformacionPatron = rotInformacionPatron;
	}

	@Column(name= "CVE_REGISTRO_OBRA", nullable = true)
	public String getCveRegistroObra() {
		return cveRegistroObra;
	}

	public void setCveRegistroObra(String cveRegistroObra) {
		this.cveRegistroObra = cveRegistroObra;
	}

	@Column(name= "CVE_ID_INFORMACION_OBRA_PRIN", nullable = true)
	public Long getCveRegistroObraPrincipal() {
		return cveRegistroObraPrincipal;
	}

	public void setCveRegistroObraPrincipal(Long cveRegistroObraPrincipal) {
		this.cveRegistroObraPrincipal = cveRegistroObraPrincipal;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INI_OBRA", length = 13)
	public Date getFecIniObra() {
		return this.fecIniObra;
	}

	public void setFecIniObra(Date fecIniObra) {
		this.fecIniObra = fecIniObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_OBRA", length = 13)
	public Date getFecFinObra() {
		return this.fecFinObra;
	}

	public void setFecFinObra(Date fecFinObra) {
		this.fecFinObra = fecFinObra;
	}

	@Column(name = "IMP_OBRA", precision = 17, scale = 17)
	public Double getImpObra() {
		return this.impObra;
	}

	public void setImpObra(Double impObra) {
		this.impObra = impObra;
	}

	@Column(name = "REF_SUP_CONSTRUCCION")
	public Double getRefSupConstruccion() {
		return this.refSupConstruccion;
	}

	public void setRefSupConstruccion(Double refSupConstruccion) {
		this.refSupConstruccion = refSupConstruccion;
	}

	@Column(name = "REF_OBSERVACION")
	public String getRefObservacion() {
		return this.refObservacion;
	}

	public void setRefObservacion(String refObservacion) {
		this.refObservacion = refObservacion;
	}

	@Column(name = "NUM_PROCEDIMIENTO")
	public String getNumProcedimiento() {
		return this.numProcedimiento;
	}

	public void setNumProcedimiento(String numProcedimiento) {
		this.numProcedimiento = numProcedimiento;
	}

	@Column(name = "NUM_LICITACION")
	public String getNumLicitacion() {
		return this.numLicitacion;
	}

	public void setNumLicitacion(String numLicitacion) {
		this.numLicitacion = numLicitacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INI_CONTRATO", length = 13)
	public Date getFecIniContrato() {
		return this.fecIniContrato;
	}

	public void setFecIniContrato(Date fecIniContrato) {
		this.fecIniContrato = fecIniContrato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_CONTRATO", length = 13)
	public Date getFecFinContrato() {
		return this.fecFinContrato;
	}

	public void setFecFinContrato(Date fecFinContrato) {
		this.fecFinContrato = fecFinContrato;
	}

	@Column(name = "IMP_EJERCIDO", precision = 17, scale = 17)
	public Double getImpEjercido() {
		return this.impEjercido;
	}

	public void setImpEjercido(Double impEjercido) {
		this.impEjercido = impEjercido;
	}

	@Column(name = "IMP_CONTRATADO", precision = 17, scale = 17)
	public Double getImpContratado() {
		return this.impContratado;
	}

	public void setImpContratado(Double impContratado) {
		this.impContratado = impContratado;
	}

	@Column(name = "REF_ACUSE_REG")
	public String getRefAcuseReg() {
		return this.refAcuseReg;
	}

	public void setRefAcuseReg(String refAcuseReg) {
		this.refAcuseReg = refAcuseReg;
	}
	

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "CVE_ID_INFORMACION_OBRA")
	public Set<RotInformacionIncidencia> getRotInformacionIncidencias() {
		return this.rotInformacionIncidencias;
	}

	public void setRotInformacionIncidencias(Set<RotInformacionIncidencia> rotInformacionIncidencias) {
		this.rotInformacionIncidencias = rotInformacionIncidencias;
	}

	@OneToOne(cascade = CascadeType.ALL)	
	@JoinColumn(name="CVE_ID_UBICACION_OBRA")
	public RotUbicacionObra getRotUbicacionObras() {
		return this.rotUbicacionObra;
	}

	public void setRotUbicacionObras(RotUbicacionObra rotUbicacionObra) {
		this.rotUbicacionObra = rotUbicacionObra;
	}
	
	@OneToOne( optional = false)
	@JoinColumn(name="CVE_ID_ESTATUS_OBRA")	
	public RocEstatusObra getRocEstatusObra() {
		return rocEstatusObra;
	}

	public void setRocEstatusObra(RocEstatusObra rocEstatusObra) {
		this.rocEstatusObra = rocEstatusObra;
	}
	
	@OneToOne
	@JoinColumn(name="CVE_ID_OBJETO_CONTRATO")	
	public RocObjetoContrato getRocObjetoContrato() {
		return rocObjetoContrato;
	}

	public void setRocObjetoContrato(RocObjetoContrato rocObjetoContrato) {
		this.rocObjetoContrato = rocObjetoContrato;
	}
	
	@Column(name = "num_actualiza")
	public Integer getNumActualiza() {
		return numActualiza;
	}

	/**
	 * @param num_actualiza the num_actualiza to set
	 */
	public void setNumActualiza(Integer numActualiza) {
		this.numActualiza = numActualiza;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "FEC_REGISTRO_BAJA")
//	public Date getFecRegistroBaja() {
//		return this.fecRegistroBaja;
//	}
//
//	public void setFecRegistroBaja(Date fecRegistroBaja) {
//		this.fecRegistroBaja = fecRegistroBaja;
//	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}	

	@Column(name = "CVE_ID_TRAMITE")
	public Long getCveIdTramite() {
		return cveIdTramite;
	}

	public void setCveIdTramite(Long cveIdTramite) {
		this.cveIdTramite = cveIdTramite;
	}
	
	@Column(name = "NUM_SEQ_NOTARIA")
	public String getNumSeqNotaria() {
		return numSeqNotaria;
	}

	public void setNumSeqNotaria(String numSeqNotaria) {
		this.numSeqNotaria = numSeqNotaria;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_BLOQUEO_OBRA")
	public Date getFecBloqueoObra() {
		return fecBloqueoObra;
	}

	public void setFecBloqueoObra(Date fecBloqueoObra) {
		this.fecBloqueoObra = fecBloqueoObra;
	}

	@Column(name = "CVE_ID_USUARIO_BLOQUEO")
	public String getCveIdUsuarioBloqueo() {
		return cveIdUsuarioBloqueo;
	}

	public void setCveIdUsuarioBloqueo(String cveIdUsuarioBloqueo) {
		this.cveIdUsuarioBloqueo = cveIdUsuarioBloqueo;
	}

	/**
	 * @param refCveAvisoObra the refCveAvisoObra to set
	 */
	@Column(name = "CVE_ID_AVISO_OBRA")
	public Long getRefCveAvisoObra() {
		return refCveAvisoObra;
	}
	
	public void setRefCveAvisoObra(Long refCveAvisoObra) {
		this.refCveAvisoObra = refCveAvisoObra;
	}

	@Column(name = "REF_OTRO_OBJETO_CONTRATO")
	public String getRefOtroObjetoContrato() {
		return refOtroObjetoContrato;
	}

	public void setRefOtroObjetoContrato(String refOtroObjetoContrato) {
		this.refOtroObjetoContrato = refOtroObjetoContrato;
	}

	@Column(name = "NUM_APROX_TRABAJADORES")
	public Integer getNumAproxTrabajadores() {
		return numAproxTrabajadores;
	}

	public void setNumAproxTrabajadores(Integer numAproxTrabajadores) {
		this.numAproxTrabajadores = numAproxTrabajadores;
	}

	@Column(name = "NUM_REG_STPS")
	public String getNumRegStps() {
		return numRegStps;
	}

	public void setNumRegStps(String numRegStps) {
		this.numRegStps = numRegStps;
	}

	@Column(name = "REF_OBJCONT_SUBESP")
	public String getRefObjetoContratoSubEsp() {
		return refObjetoContratoSubEsp;
	}

	public void setRefObjetoContratoSubEsp(String refObjetoContratoSubEsp) {
		this.refObjetoContratoSubEsp = refObjetoContratoSubEsp;
	}

	@Column(name = "CVE_OBRA_REMPLAZADO")
	public String getCveObraRemplazado() {
		return cveObraRemplazado;
	}

	public void setCveObraRemplazado(String cveObraRemplazado) {
		this.cveObraRemplazado = cveObraRemplazado;
	}

	@Override
	public String toString() {
		return "RotInformacionObra{" +
				"cveInformacionObra=" + cveInformacionObra +
				", rocSubdelegacion=" + rocSubdelegacion +
				", rocTipoObra=" + rocTipoObra +
				", rotInformacionPatron=" + rotInformacionPatron +
				", rocObjetoContrato=" + rocObjetoContrato +
				", cveRegistroObra='" + cveRegistroObra + '\'' +
				", cveRegistroObraPrincipal=" + cveRegistroObraPrincipal +
				", fecIniObra=" + fecIniObra +
				", fecFinObra=" + fecFinObra +
				", impObra=" + impObra +
				", refSupConstruccion=" + refSupConstruccion +
				", refObservacion='" + refObservacion + '\'' +
				", numProcedimiento='" + numProcedimiento + '\'' +
				", numLicitacion='" + numLicitacion + '\'' +
				", fecIniContrato=" + fecIniContrato +
				", fecFinContrato=" + fecFinContrato +
				", impEjercido=" + impEjercido +
				", impContratado=" + impContratado +
				", refAcuseReg='" + refAcuseReg + '\'' +
				", fecRegistroAlta=" + fecRegistroAlta +
				", fecRegistroActualizado=" + fecRegistroActualizado +
				", rotInformacionIncidencias=" + rotInformacionIncidencias +
				", rotUbicacionObra=" + rotUbicacionObra +
				", rocEstatusObra=" + rocEstatusObra +
				", numActualiza=" + numActualiza +
				", cveIdTramite=" + cveIdTramite +
				", numSeqNotaria='" + numSeqNotaria + '\'' +
				", fecBloqueoObra=" + fecBloqueoObra +
				", cveIdUsuarioBloqueo='" + cveIdUsuarioBloqueo + '\'' +
				", refCveAvisoObra=" + refCveAvisoObra +
				", refOtroObjetoContrato='" + refOtroObjetoContrato + '\'' +
				", numAproxTrabajadores=" + numAproxTrabajadores +
				", numRegStps='" + numRegStps + '\'' +
				", refObjetoContratoSubEsp='" + refObjetoContratoSubEsp + '\'' +
				", cveObraRemplazado='" + cveObraRemplazado + '\'' +
				'}';
	}
}

	