
#HOST_MEXICO=11.254.13.200
HOST_MEXICO=${mvn.smtp.mail.host}
USER_DERECHOHABIENTES=${mvn.smtp.mail.user}
PASSWORD_DERECHOHABIENTES=${mvn.smtp.mail.password}
PROTOCOLO=smtp
PUERTO=25
DEBUG_ENABLE=false
AUTENTICACION=false
#HOST_MEXICO=11.254.13.116
#USER_DERECHOHABIENTES=
#PASSWORD_DERECHOHABIENTES=
FROMIMSS_DERECHOHABIENTES_NOTIFICACION=gestion.derechohabientes@imss.gob.mx

