
package mx.gob.imss.cit.dpes.core.modelo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "JwsServiceSoapBindingQSService", targetNamespace = "http://www.openuri.org/", wsdlLocation = "http://172.16.168.141:8001/SolicitudTramite/SolicitudService?wsdl")
public class JwsServiceSoapBindingQSService extends Service {

    private final static URL JWSSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger
            .getLogger(mx.gob.imss.cit.dpes.core.modelo.JwsServiceSoapBindingQSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.gob.imss.cit.dpes.core.modelo.JwsServiceSoapBindingQSService.class.getResource(".");
            url = new URL(baseUrl, "http://172.16.168.141:8001/SolicitudTramite/SolicitudService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning(
                    "Failed to create URL for the wsdl Location: 'http://172.31.240.51/SolicitudTramite/SolicitudService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JWSSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
    }

    public JwsServiceSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JwsServiceSoapBindingQSService() {
        super(JWSSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION,
                new QName("http://www.openuri.org/", "JwsServiceSoapBindingQSService"));
    }

    /**
     * @return
     *         returns Jws
     */
    @WebEndpoint(name = "JwsServiceSoapBindingQSPort")
    public Jws getJwsServiceSoapBindingQSPort() {

        return super.getPort(new QName("http://www.openuri.org/", "JwsServiceSoapBindingQSPort"), Jws.class);
    }

    /**
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return
     *         returns Jws
     */
    @WebEndpoint(name = "JwsServiceSoapBindingQSPort")
    public Jws getJwsServiceSoapBindingQSPort(WebServiceFeature... features) {

        return super.getPort(new QName("http://www.openuri.org/", "JwsServiceSoapBindingQSPort"), Jws.class, features);
    }

}
