package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatLocalidad;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatTipoAsen;

/**
 * DgAsentamiento generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgAsentamiento extends AbstractModel {

	private AbstractDgAsentamientoId id;
	private DgCatLocalidad dgCatLocalidad;
	private DgCatTipoAsen dgCatTipoAsen;
	private String nomAsen;
	private String agregado;
	

	public AbstractDgAsentamiento() {
		id = new AbstractDgAsentamientoId();

	}

	public AbstractDgAsentamiento(AbstractDgAsentamientoId id, DgCatLocalidad dgCatLocalidad,
			DgCatTipoAsen dgCatTipoAsen, String nomAsen) {
		this.id = id;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatTipoAsen = dgCatTipoAsen;
		this.nomAsen = nomAsen;
	}

	public AbstractDgAsentamiento(AbstractDgAsentamientoId id, DgCatLocalidad dgCatLocalidad,
			DgCatTipoAsen dgCatTipoAsen, String nomAsen, String agregado) {
		this.id = id;
		this.dgCatLocalidad = dgCatLocalidad;
		this.dgCatTipoAsen = dgCatTipoAsen;
		this.nomAsen = nomAsen;
		this.agregado = agregado;
	
	}

//	@EmbeddedId
//	@AttributeOverrides({
//			@AttributeOverride(name = "cveAsen", column = @Column(name = "CVE_ASEN", nullable = false, length = 13)),
//			@AttributeOverride(name = "cveEnt", column = @Column(name = "CVE_ENT", nullable = false, length = 2)),
//			@AttributeOverride(name = "cveMun", column = @Column(name = "CVE_MUN", nullable = false, length = 3)),
//			@AttributeOverride(name = "cveLoc", column = @Column(name = "CVE_LOC", nullable = false, length = 4)),
//			@AttributeOverride(name = "cvePeriodo", column = @Column(name = "CVE_PERIODO", nullable = false, precision = 2, scale = 0)) })
	public AbstractDgAsentamientoId getId() {
		return this.id;
	}

	public void setId(AbstractDgAsentamientoId id) {
		this.id = id;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumns({
//			@JoinColumn(name = "CVE_ENT", referencedColumnName = "CVE_ENT", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_MUN", referencedColumnName = "CVE_MUN", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_LOC", referencedColumnName = "CVE_LOC", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CVE_PERIODO", referencedColumnName = "CVE_PERIODO", nullable = false, insertable = false, updatable = false) })
	public DgCatLocalidad getDgCatLocalidad() {
		return this.dgCatLocalidad;
	}

	public void setDgCatLocalidad(DgCatLocalidad dgCatLocalidad) {
		this.dgCatLocalidad = dgCatLocalidad;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "CVE_TIPO_ASEN", nullable = false)
	public DgCatTipoAsen getDgCatTipoAsen() {
		return this.dgCatTipoAsen;
	}

	public void setDgCatTipoAsen(DgCatTipoAsen dgCatTipoAsen) {
		this.dgCatTipoAsen = dgCatTipoAsen;
	}

//	@Column(name = "NOM_ASEN", nullable = false)
	public String getNomAsen() {
		return this.nomAsen;
	}

	public void setNomAsen(String nomAsen) {
		this.nomAsen = nomAsen;
	}

//	@Column(name = "AGREGADO", length = 1)
	public String getAgregado() {
		return this.agregado;
	}

	public void setAgregado(String agregado) {
		this.agregado = agregado;
	}

	

}
