package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;

/**
 * DgCatMargen generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgCatMargen extends AbstractModel {

	private Integer cveMargen;
	private String descripcion;
	
	public AbstractDgCatMargen() {
	}

	public AbstractDgCatMargen(Integer cveMargen, String descripcion) {
		this.cveMargen = cveMargen;
		this.descripcion = descripcion;
	}

	
//	@Id
//	@Column(name = "CVE_MARGEN", unique = true, nullable = false, precision = 2, scale = 0)
	public Integer getCveMargen() {
		return this.cveMargen;
	}

	public void setCveMargen(Integer cveMargen) {
		this.cveMargen = cveMargen;
	}

//	@Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	

}
