package mx.gob.imss.ctirss.domiciliosInegi.base.model;

// Generated 17/11/2011 11:55:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatMargen;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgCatTermGen;
import mx.gob.imss.ctirss.domiciliosInegi.model.DgDomicilioGeografico;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DgDomiciliosCaminos generated by hbm2java
 */
@MappedSuperclass
public abstract class AbstractDgDomiciliosCaminos extends AbstractModel {

	private long domicilioId;
	private DgDomicilioGeografico dgDomicilioGeografico;
	private DgCatTermGen dgCatTermGen;
	private DgCatMargen dgCatMargen;
	private String nomvial;
	private String origen;
	private String destino;
	private String cadenamiento;
	

	public AbstractDgDomiciliosCaminos() {
	/*	this.dgDomicilioGeografico = new DgDomicilioGeografico();
		this.dgCatTermGen = new DgCatTermGen();
		this.dgCatMargen = new DgCatMargen();
		*/
	}

	public AbstractDgDomiciliosCaminos(DgDomicilioGeografico dgDomicilioGeografico,
			DgCatTermGen dgCatTermGen, String nomvial) {
		this.dgDomicilioGeografico = dgDomicilioGeografico;
		this.dgCatTermGen = dgCatTermGen;
		this.nomvial = nomvial;
	}

	public AbstractDgDomiciliosCaminos(DgDomicilioGeografico dgDomicilioGeografico,
			DgCatTermGen dgCatTermGen, DgCatMargen dgCatMargen, String nomvial,
			String origen, String destino, String cadenamiento) {
		this.dgDomicilioGeografico = dgDomicilioGeografico;
		this.dgCatTermGen = dgCatTermGen;
		this.dgCatMargen = dgCatMargen;
		this.nomvial = nomvial;
		this.origen = origen;
		this.destino = destino;
		this.cadenamiento = cadenamiento;
	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "dgDomicilioGeografico"))
//	@Id
//	@GeneratedValue(generator = "generator")
//	@Column(name = "DOMICILIO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDomicilioId() {
		return this.domicilioId;
	}

	public void setDomicilioId(long domicilioId) {
		this.domicilioId = domicilioId;
	}

//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
	@Transient
	public DgDomicilioGeografico getDgDomicilioGeografico() {
		return this.dgDomicilioGeografico;
	}

	public void setDgDomicilioGeografico(
			DgDomicilioGeografico dgDomicilioGeografico) {
		this.dgDomicilioGeografico = dgDomicilioGeografico;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "CVE_TER", nullable = false)
	public DgCatTermGen getDgCatTermGen() {
		return this.dgCatTermGen;
	}

	public void setDgCatTermGen(DgCatTermGen dgCatTermGen) {
		this.dgCatTermGen = dgCatTermGen;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "CVE_MARGEN")
	public DgCatMargen getDgCatMargen() {
		return this.dgCatMargen;
	}

	public void setDgCatMargen(DgCatMargen dgCatMargen) {
		this.dgCatMargen = dgCatMargen;
	}

//	@Column(name = "NOMVIAL", nullable = false, length = 240)
	public String getNomvial() {
		return this.nomvial;
	}

	public void setNomvial(String nomvial) {
		this.nomvial = nomvial;
	}

//	@Column(name = "ORIGEN")
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

//	@Column(name = "DESTINO")
	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

//	@Column(name = "CADENAMIENTO")
	public String getCadenamiento() {
		return this.cadenamiento;
	}

	public void setCadenamiento(String cadenamiento) {
		this.cadenamiento = cadenamiento;
	}

}
