package mx.gob.imss.csdiss.sdroc.entity;

// default package
// Generated Jul 20, 2016 6:54:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.ObjetoContratoDTO;

/**
 * RocTipoObra generated by hbm2java
 */
@Entity
@Table(name = "ROC_OBJETO_CONTRATO", schema = "MGPROC01")
@Transactional
public class RocObjetoContrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4943022634302990066L;
	
	private Long cveObjetoContrato;
	private String desObjetoContrato;
	private Date fecRegistroAlta;	
	private Date fecRegistroBaja;
	private Date fecRegistroActualizado;

	public RocObjetoContrato() {
	}

	public RocObjetoContrato(Long cveObjetoContrato) {
		this.cveObjetoContrato = cveObjetoContrato;
	}

	public RocObjetoContrato(Long cveObjetoContrato, String desObjetoContrato, Date fecRegistroAlta, Date fecRegistroBaja, Date fecRegistroActualizado) {

		this.cveObjetoContrato = cveObjetoContrato;
		this.desObjetoContrato = desObjetoContrato;
		this.fecRegistroAlta = fecRegistroAlta;
		this.fecRegistroBaja = fecRegistroBaja;
		this.fecRegistroActualizado = fecRegistroActualizado;
	}

	@Id
	@Column(name = "CVE_ID_OBJETO_CONTRATO", unique = true, nullable = false)
	public Long getCveObjetoContrato() {
		return this.cveObjetoContrato;
	}

	public void setCveObjetoContrato(Long cveObjetoContrato) {
		this.cveObjetoContrato = cveObjetoContrato;
	}

	@Column(name = "DES_OBJETO_CONTRATO", length = 80)
	public String getDesObjetoContrato() {
		return this.desObjetoContrato;
	}

	public void setDesObjetoContrato(String desObjetoContrato) {
		this.desObjetoContrato = desObjetoContrato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ALTA")
	public Date getFecRegistroAlta() {
		return this.fecRegistroAlta;
	}

	public void setFecRegistroAlta(Date fecRegistroAlta) {
		this.fecRegistroAlta = fecRegistroAlta;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_BAJA")
	public Date getFecRegistroBaja() {
		return this.fecRegistroBaja;
	}

	public void setFecRegistroBaja(Date fecRegistroBaja) {
		this.fecRegistroBaja = fecRegistroBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_REGISTRO_ACTUALIZADO")
	public Date getFecRegistroActualizado() {
		return this.fecRegistroActualizado;
	}

	public void setFecRegistroActualizado(Date fecRegistroActualizado) {
		this.fecRegistroActualizado = fecRegistroActualizado;
	}
	
	public ObjetoContratoDTO toConvertObjetoContratoDTO(){
		ObjetoContratoDTO objetoContratoDTO = new ObjetoContratoDTO();

		objetoContratoDTO.setCveObjetoContrato(this.getCveObjetoContrato());
		objetoContratoDTO.setDesObjetoContrato(this.getDesObjetoContrato());
		
		return objetoContratoDTO;
	}

}
