package mx.gob.imss.csdiss.sdroc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

import mx.gob.imss.csdiss.sdroc.dto.InformacionPatronDTO;

/**
 * RotInformacionPatron generated by hbm2java
 */
@Entity
@Table(name = "ROT_INFORMACION_PATRON")
@Transactional
public class RotInformacionPatron implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9089383572768438515L;
	
	private Long cveInformacionPatron;
	private RocTipoPatron rocTipoPatron;
	private RocTipoPersona rocTipoPersona;
	private String cveRfc;
	private String cveRegPatronal;
	private String refApellidoPaterno;
	private String refApellidoMaterno;
	private String nomPatron;
	private String refRazonSocial;

	public RotInformacionPatron() {
	}

	public RotInformacionPatron(Long cveInformacionPatron) {
		this.cveInformacionPatron = cveInformacionPatron;
	}


	public RotInformacionPatron(Long cveInformacionPatron, RocTipoPatron rocTipoPatron, RocTipoPersona rocTipoPersona,
			String cveRfc, String cveRegPatronal, String refApellidoPaterno, String refApellidoMaterno,
			String nomPatron, String refRazonSocial) {

		this.cveInformacionPatron = cveInformacionPatron;
		this.rocTipoPatron = rocTipoPatron;
		this.rocTipoPersona = rocTipoPersona;
		this.cveRfc = cveRfc;
		this.cveRegPatronal = cveRegPatronal;
		this.refApellidoPaterno = refApellidoPaterno;
		this.refApellidoMaterno = refApellidoMaterno;
		this.nomPatron = nomPatron;
		this.refRazonSocial = refRazonSocial;
	}

	@Id
	@Column(name = "CVE_ID_INFORMACION_PATRON", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_informacion_patron")
	@SequenceGenerator(name="seq_informacion_patron", sequenceName="SEQ_ROTINFORMACIONPATRON", allocationSize=1)		
	public Long getCveInformacionPatron() {
		return this.cveInformacionPatron;
	}

	public void setCveInformacionPatron(Long cveInformacionPatron) {
		this.cveInformacionPatron = cveInformacionPatron;
	}

	@ManyToOne( optional = false)
	@JoinColumn(name = "CVE_ID_TIPO_PATRON")
	public RocTipoPatron getRocTipoPatron() {
		return this.rocTipoPatron;
	}

	public void setRocTipoPatron(RocTipoPatron rocTipoPatron) {
		this.rocTipoPatron = rocTipoPatron;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "CVE_ID_TIPO_PERSONA")
	public RocTipoPersona getRocTipoPersona() {
		return this.rocTipoPersona;
	}

	public void setRocTipoPersona(RocTipoPersona rocTipoPersona) {
		this.rocTipoPersona = rocTipoPersona;
	}

	@Column(name = "ROT_RFC", length = 20)
	public String getCveRfc() {
		return this.cveRfc;
	}

	public void setCveRfc(String cveRfc) {
		this.cveRfc = cveRfc;
	}

	@Column(name = "ROT_REG_PATRONAL", length = 20)
	public String getCveRegPatronal() {
		return this.cveRegPatronal;
	}

	public void setCveRegPatronal(String cveRegPatronal) {
		this.cveRegPatronal = cveRegPatronal;
	}

	@Column(name = "ROT_APELLIDO_PATERNO", length = 50)
	public String getRefApellidoPaterno() {
		return this.refApellidoPaterno;
	}

	public void setRefApellidoPaterno(String refApellidoPaterno) {
		this.refApellidoPaterno = refApellidoPaterno;
	}

	@Column(name = "ROT_APELLIDO_MATERNO", length = 50)
	public String getRefApellidoMaterno() {
		return this.refApellidoMaterno;
	}

	public void setRefApellidoMaterno(String refApellidoMaterno) {
		this.refApellidoMaterno = refApellidoMaterno;
	}

	@Column(name = "ROT_NOM_PATRON", length = 50)
	public String getNomPatron() {
		return this.nomPatron;
	}

	public void setNomPatron(String nomPatron) {
		this.nomPatron = nomPatron;
	}

	@Column(name = "ROT_RAZON_SOCIAL", length = 50)
	public String getRefRazonSocial() {
		return this.refRazonSocial;
	}

	public void setRefRazonSocial(String refRazonSocial) {
		this.refRazonSocial = refRazonSocial;
	}
	
	public InformacionPatronDTO toConvertInformacionPatronDTO(){
		
		InformacionPatronDTO informacionPatronDTO = new InformacionPatronDTO();
		
		informacionPatronDTO.setCveInformacionPatron(this.cveInformacionPatron);
		informacionPatronDTO.setCveRegPatronal(this.cveRegPatronal);
		informacionPatronDTO.setCveRfc(this.cveRfc);
		informacionPatronDTO.setNomPatron(this.nomPatron);
		informacionPatronDTO.setRefApellidoMaterno(this.refApellidoMaterno);
		informacionPatronDTO.setRefApellidoPaterno(this.refApellidoPaterno);
		informacionPatronDTO.setRefRazonSocial(this.refRazonSocial);
		if(this.getRocTipoPatron() != null)
			informacionPatronDTO.setTipoPatronDTO(this.getRocTipoPatron().toConvertTipoPatronDTO());
		if(this.getRocTipoPersona() != null)
			informacionPatronDTO.setTipoPersonaDTO(this.getRocTipoPersona().toConvertTipoPersonaDTO());
				
		return informacionPatronDTO;
		
	}

}
