#RUTA ALMACEN DE LLAVES
#ruta.almacen.key.rampart=/Users/weblogic/Documents/keystore.jks
ruta.almacen.key.rampart=timbradoCFDI/keystore/keystore.jks

#USER KEYSTORE
#user.keystore.rampart=ims421231i45_1202201056
user.keystore.rampart=importkey

#PASSWORD KEYSTORE
#password.keystore.rampart=CTDIVCONT.2012#0mssr1ss2014
password.keystore.rampart=importkey

#TYPE KEYSTORE
type.keystore.rampart=JKS

#IMSS RFC
############ Produccion ############
#rfc.imss.timbrado = IMS421231I45

############ Desarrollo y QA ############
rfc.imss.timbrado = WAL99092955A

#ENGAGE MODULE RAMPART
engage.security.rampart=rampart

#RUTA RAMPART
modulos.security.rampart=modules/rampart-1.6.2
