//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.23 at 01:44:56 PM CST 
//
 
package mx.gob.imss.ctirss.delta.model.derechohabientes;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import mx.gob.imss.ctirss.delta.model.domicilio.Delegacion;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.Division;
import mx.gob.imss.ctirss.delta.model.gestion.solicitud.EstadoSolicitud;

public class AltaTransaccional implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected Division division;
	protected EstadoSolicitud estadoSolicitud;
	protected Delegacion delegacion;

	/**
	 * Gets the value of the division property.
	 * 
	 * @return possible object is {@link Division }
	 * 
	 */
	public Division getDivision() {
		return division;
	}

	/**
	 * Sets the value of the division property.
	 * 
	 * @param value
	 *            allowed object is {@link Division }
	 * 
	 */
	public void setDivision(final Division value) {
		division = value;
	}

	
	
	/**
	 * @return the estadoSolicitud
	 */
	public EstadoSolicitud getEstadoSolicitud() {
		return estadoSolicitud;
	}

	/**
	 * @param estadoSolicitud the estadoSolicitud to set
	 */
	public void setEstadoSolicitud(EstadoSolicitud estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}

	/**
	 * Gets the value of the delegacion property.
	 * 
	 * @return possible object is {@link Delegacion }
	 * 
	 */
	public Delegacion getDelegacion() {
		return delegacion;
	}

	/**
	 * Sets the value of the delegacion property.
	 * 
	 * @param value
	 *            allowed object is {@link Delegacion }
	 * 
	 */
	public void setDelegacion(final Delegacion value) {
		delegacion = value;
	}

}
