//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.23 at 01:44:56 PM CST 
//

package mx.gob.imss.ctirss.delta.model.derechohabientes; 

import javax.xml.bind.annotation.XmlRegistry;

import mx.gob.imss.ctirss.delta.model.domicilio.Delegacion;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.Division;
import mx.gob.imss.ctirss.delta.model.gestion.solicitud.EstadoSolicitud;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * mx.gob.imss.ctirss.proyectotransaccional.modelo.negocio package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * mx.gob.imss.ctirss.proyectotransaccional.modelo.negocio
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Delegacion }
	 * 
	 */
	public Delegacion createDelegacion() {
		return new Delegacion();
	}

	/**
	 * Create an instance of {@link Division }
	 * 
	 */
	public Division createDivision() {
		return new Division();
	}

	/**
	 * Create an instance of {@link EjecucionServicio }
	 * 
	 */
	public EjecucionServicio createEjecucionServicio() {
		return new EjecucionServicio();
	}

	/**
	 * Create an instance of {@link EstatusSolicitud }
	 * 
	 */
	public EstadoSolicitud createEstadoSolicitud() {
		return new EstadoSolicitud();
	}

	/**
	 * Create an instance of {@link AltaTransaccional }
	 * 
	 */
	public AltaTransaccional createAltaTransaccional() {
		return new AltaTransaccional();
	}

}
