package mx.gob.imss.ctirss.correccion.base.model;

// Generated 29/11/2011 12:35:23 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.gob.imss.ctirss.correccion.framework.base.model.AbstractModel;
import mx.gob.imss.ctirss.correccion.model.SatPatron;

/**
 * CrtInvitacion generated by hbm2java
 */

@MappedSuperclass
public class AbstractCrtInvitacion extends AbstractModel {
	private static final long serialVersionUID = 1L;

	private BigDecimal cveInvitacion;
	private SatPatron satPatron;
	private BigDecimal cvePromocion;
	private BigDecimal cveDeteccion;
	private BigDecimal cveFkSubdelegacion;
	private String nuOficioinv;
	private Date fecFechaoficioinv;
	private Date fecFechaemision;
	private Date fecFechanotifi;
	private Date fecFechareg;
	private String cveUsuario;
	private String nuFolioInvitacion;
	private Date fecAtencion;
	
	private Long idMotivoCancelacion;
	private Date fecCancelacion;
	private String numOficioCancelacion;
	private Long cveIdAuditor;
	
	private Date fecPeriodoIni;
	private Date fecPeriodoFin;
	public Integer idCriterioSeleccion;
	private String txObservaciones;
	private Long idVariosRPS;
	private Long cveEstatus;
//	private Long cveAuditorAsignado;
	private String cveAuditorAsignado;
	
	private Date fechaDerSubdelegacion; 
	private Date fechaAisoDictamen;
	private Date fechaPeriodoIniDic;
	private Date fechaPeriodoFInDic;
	private String cveUsuarioAutoriza;
	private Date fecchaPai;
	private String txRfrpai;
	private String numAvisoDictamen;
	private Long cvePatronFiscal;
	private Long cveSubdelegDest;
	private String txReferenciaSubdeleg;
	private Long cveDomicilioFiscal;
	
	public AbstractCrtInvitacion() {
	}

	public AbstractCrtInvitacion(BigDecimal cveInvitacion) {
		this.cveInvitacion = cveInvitacion;
	}

	public AbstractCrtInvitacion(BigDecimal cveInvitacion, 
			BigDecimal cvePromocion, BigDecimal cveDeteccion,
			BigDecimal cveFkSubdelegacion, String nuOficioinv,
			Date fecFechaoficioinv, Date fecFechaemision, Date fecFechanotifi,
			Date fecFechareg, String cveUsuario, String nuFolioInvitacion) {
		this.cveInvitacion = cveInvitacion;
		this.cvePromocion = cvePromocion;
		this.cveDeteccion = cveDeteccion;
		this.cveFkSubdelegacion = cveFkSubdelegacion;
		this.nuOficioinv = nuOficioinv;
		this.fecFechaoficioinv = fecFechaoficioinv;
		this.fecFechaemision = fecFechaemision;
		this.fecFechanotifi = fecFechanotifi;
		this.fecFechareg = fecFechareg;
		this.cveUsuario = cveUsuario;
		this.nuFolioInvitacion = nuFolioInvitacion;
		
	}
	
	/**
	 * Constructor para Auditor
	 * @author Enrique Duran JImenez
	 * @since 25/05/2012
	 */
	public AbstractCrtInvitacion(BigDecimal cveInvitacion, String nuFolioInvitacion, SatPatron fkPatron,
			Date fecPeriodoIni, Date fecPeriodoFin, Date fecFechaemision) {
		this.cveInvitacion = cveInvitacion;
		this.nuFolioInvitacion = nuFolioInvitacion;
		this.satPatron = fkPatron;
		this.fecPeriodoIni = fecPeriodoIni;
		this.fecPeriodoFin = fecPeriodoFin;
		this.fecFechaemision = fecFechaemision;	
	}

	@Id
	@SequenceGenerator(name="CVE_INVITACION_GENERATOR", sequenceName="CRS_CVE_INVITACION")
	@GeneratedValue(generator="CVE_INVITACION_GENERATOR")
	@Column(name="CVE_INVITACION")
	public BigDecimal getCveInvitacion() {
		return this.cveInvitacion;
	}

	public void setCveInvitacion(BigDecimal cveInvitacion) {
		this.cveInvitacion = cveInvitacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CVE_FK_PATRON")
	public SatPatron getSatPatron() {
		return this.satPatron;
	}

	public void setSatPatron(SatPatron satPatron) {
		this.satPatron = satPatron;
	}

	@Column(name = "CVE_PROMOCION", precision = 22, scale = 0)
	public BigDecimal getCvePromocion() {
		return this.cvePromocion;
	}

	public void setCvePromocion(BigDecimal cvePromocion) {
		this.cvePromocion = cvePromocion;
	}

	@Column(name = "CVE_DETECCION", precision = 22, scale = 0)
	public BigDecimal getCveDeteccion() {
		return this.cveDeteccion;
	}

	public void setCveDeteccion(BigDecimal cveDeteccion) {
		this.cveDeteccion = cveDeteccion;
	}

	@Column(name = "CVE_FK_SUBDELEGACION", scale = 0)
	public BigDecimal getCveFkSubdelegacion() {
		return this.cveFkSubdelegacion;
	}

	public void setCveFkSubdelegacion(BigDecimal cveFkSubdelegacion) {
		this.cveFkSubdelegacion = cveFkSubdelegacion;
	}

	@Column(name = "NU_OFICIOINV", length = 18)
	public String getNuOficioinv() {
		return this.nuOficioinv;
	}

	public void setNuOficioinv(String nuOficioinv) {
		this.nuOficioinv = nuOficioinv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_FECHAOFICIOINV")
	public Date getFecFechaoficioinv() {
		return this.fecFechaoficioinv;
	}

	public void setFecFechaoficioinv(Date fecFechaoficioinv) {
		this.fecFechaoficioinv = fecFechaoficioinv;
	}

	 @Temporal( TemporalType.DATE)
	@Column(name = "FEC_FECHAEMISION")
	public Date getFecFechaemision() {
		return this.fecFechaemision;
	}

	public void setFecFechaemision(Date fecFechaemision) {
		this.fecFechaemision = fecFechaemision;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_FECHANOTIFI")
	public Date getFecFechanotifi() {
		return this.fecFechanotifi;
	}

	public void setFecFechanotifi(Date fecFechanotifi) {
		this.fecFechanotifi = fecFechanotifi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FECHAREG")
	public Date getFecFechareg() {
		return this.fecFechareg;
	}

	public void setFecFechareg(Date fecFechareg) {
		this.fecFechareg = fecFechareg;
	}

	@Column(name = "CVE_USUARIO", length = 20)
	public String getCveUsuario() {
		return this.cveUsuario;
	}

	public void setCveUsuario(String cveUsuario) {
		this.cveUsuario = cveUsuario;
	}
	
	@Column(name = "NU_FOLIOINVITACION", length = 20)
	public String getNuFolioInvitacion() {
		return nuFolioInvitacion;
	}

	public void setNuFolioInvitacion(String nuFolioInvitacion) {
		this.nuFolioInvitacion = nuFolioInvitacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name="FEC_ATENCION")
	public Date getFecAtencion() {
		return fecAtencion;
	}

	public void setFecAtencion(Date fecAtencion) {
		this.fecAtencion = fecAtencion;
	}

	@Column(name = "ID_MOTIVOCANCELACION", length = 20)
	public Long getIdMotivoCancelacion() {
		return idMotivoCancelacion;
	}

	public void setIdMotivoCancelacion(Long idMotivoCancelacion) {
		this.idMotivoCancelacion = idMotivoCancelacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name="FEC_FECHACANCELA")
	public Date getFecCancelacion() {
		return fecCancelacion;
	}

	public void setFecCancelacion(Date fecCancelacion) {
		this.fecCancelacion = fecCancelacion;
	}

	@Column(name = "NUM_OFICIOCAN", length = 25)
	public String getNumOficioCancelacion() {
		return numOficioCancelacion;
	}

	public void setNumOficioCancelacion(String numOficioCancelacion) {
		this.numOficioCancelacion = numOficioCancelacion;
	}

	/**
	 * @return the fecPeriodoIni
	 */
	@Temporal(TemporalType.DATE)
	@Column(name="FEC_PERIODOINI")
	public Date getFecPeriodoIni() {
		return fecPeriodoIni;
	}

	/**
	 * @param fecPeriodoIni the fecPeriodoIni to set
	 */
	public void setFecPeriodoIni(Date fecPeriodoIni) {
		this.fecPeriodoIni = fecPeriodoIni;
	}

	/**
	 * @return the fecPeriodoFin
	 */
	@Temporal(TemporalType.DATE)
	@Column(name="FEC_PERIODOFIN")
	public Date getFecPeriodoFin() {
		return fecPeriodoFin;
	}

	/**
	 * @param fecPeriodoFin the fecPeriodoFin to set
	 */
	public void setFecPeriodoFin(Date fecPeriodoFin) {
		this.fecPeriodoFin = fecPeriodoFin;
	}

	/**
	 * @return the idCriterioSeleccion
	 */
	@Column(name = "ID_CRITERIOSELECCION")
	public Integer getIdCriterioSeleccion() {
		return idCriterioSeleccion;
	}

	/**
	 * @param idCriterioSeleccion the idCriterioSeleccion to set
	 */
	public void setIdCriterioSeleccion(Integer idCriterioSeleccion) {
		this.idCriterioSeleccion = idCriterioSeleccion;
	}

	/**
	 * @return the txObservaciones
	 */
	@Column(name = "TX_OBSERVACIONES")
	public String getTxObservaciones() {
		return txObservaciones;
	}

	/**
	 * @param txObservaciones the txObservaciones to set
	 */
	public void setTxObservaciones(String txObservaciones) {
		this.txObservaciones = txObservaciones;
	}

	/**
	 * @return the idVariosRPS
	 */
	@Column(name = "ID_VARIOS_RPS")
	public Long getIdVariosRPS() {
		return idVariosRPS;
	}

	/**
	 * @param idVariosRPS the idVariosRPS to set
	 */
	public void setIdVariosRPS(Long idVariosRPS) {
		this.idVariosRPS = idVariosRPS;
	}

	/**
	 * @return the cveEstatus
	 */
	@Column(name = "CVE_ESTATUS")
	public Long getCveEstatus() {
		return cveEstatus;
	}

	/**
	 * @param cveEstatus the cveEstatus to set
	 */
	public void setCveEstatus(Long cveEstatus) {
		this.cveEstatus = cveEstatus;
	}

//	/**
//	 * @return the cveAuditorAsignado
//	 */
//	@Column(name = "CVE_AUDITOR_ASIGNADO")
//	public Long getCveAuditorAsignado() {
//		return cveAuditorAsignado;
//	}
//
//	/**
//	 * @param cveAuditorAsignado the cveAuditorAsignado to set
//	 */
//	public void setCveAuditorAsignado(Long cveAuditorAsignado) {
//		this.cveAuditorAsignado = cveAuditorAsignado;
//	}
	
	/**
	 * @return the cveAuditorAsignado
	 */
	@Column(name = "CVE_AUDITOR_ASIGNADO")
	public String getCveAuditorAsignado() {
		return cveAuditorAsignado;
	}

	/**
	 * @param cveAuditorAsignado the cveAuditorAsignado to set
	 */
	public void setCveAuditorAsignado(String cveAuditorAsignado) {
		this.cveAuditorAsignado = cveAuditorAsignado;
	}

	/**
	 * @return the fechaDerSubdelegacion
	 */
	@Column(name="FEC_FECHADERISUBDELEG")
	public Date getFechaDerSubdelegacion() {
		return fechaDerSubdelegacion;
	}
	/**
	 * @param fechaDerSubdelegacion the fechaDerSubdelegacion to set
	 */	
	public void setFechaDerSubdelegacion(Date fechaDerSubdelegacion) {
		this.fechaDerSubdelegacion = fechaDerSubdelegacion;
	}

	/**
	 * @return the fechaAisoDictamen
	 */
	@Column(name="FEC_AVISODICTAMEN")
	public Date getFechaAisoDictamen() {
		return fechaAisoDictamen;
	}
	/**
	 * @param fechaAisoDictamen the fechaAisoDictamen to set
	 */
	public void setFechaAisoDictamen(Date fechaAisoDictamen) {
		this.fechaAisoDictamen = fechaAisoDictamen;
	}

	/**
	 * @return the fechaPeriodoIniDic
	 */
	@Column(name="FEC_PERIODOINIDIC")
	public Date getFechaPeriodoIniDic() {
		return fechaPeriodoIniDic;
	}

	/**
	 * @param fechaPeriodoIniDic the fechaPeriodoIniDic to set
	 */
	public void setFechaPeriodoIniDic(Date fechaPeriodoIniDic) {
		this.fechaPeriodoIniDic = fechaPeriodoIniDic;
	}

	/**
	 * @return the fechaPeriodoFInDic
	 */
	@Column(name="FEC_PERIODOFINDIC")
	public Date getFechaPeriodoFInDic() {
		return fechaPeriodoFInDic;
	}
	/**
	 * @param fechaPeriodoFInDic the fechaPeriodoFInDic to set
	 */
	public void setFechaPeriodoFInDic(Date fechaPeriodoFInDic) {
		this.fechaPeriodoFInDic = fechaPeriodoFInDic;
	}

	/**
	 * @return the cveUsuarioAutoriza
	 */
	@Column(name="CVE_USER_AUTORIZA")
	public String getCveUsuarioAutoriza() {
		return cveUsuarioAutoriza;
	}
	/**
	 * @param cveUsuarioAutoriza the cveUsuarioAutoriza to set
	 */
	public void setCveUsuarioAutoriza(String cveUsuarioAutoriza) {
		this.cveUsuarioAutoriza = cveUsuarioAutoriza;
	}

	/**
	 * @return the fecchaPai
	 */
	@Column(name="FEC_FECHAPAI")
	public Date getFecchaPai() {
		return fecchaPai;
	}
	/**
	 * @param fecchaPai the fecchaPai to set
	 */
	public void setFecchaPai(Date fecchaPai) {
		this.fecchaPai = fecchaPai;
	}

	/**
	 * @return the txRfrpai
	 */
	@Column(name="TX_RFRPAI")
	public String getTxRfrpai() {
		return txRfrpai;
	}

	/**
	 * @param txRfrpai the txRfrpai to set
	 */
	public void setTxRfrpai(String txRfrpai) {
		this.txRfrpai = txRfrpai;
	}

	/**
	 * @return the numAvisoDictamen
	 */
	@Column(name="NUM_AVISODICTAMEN")
	public String getNumAvisoDictamen() {
		return numAvisoDictamen;
	}

	/**
	 * @param numAvisoDictamen the numAvisoDictamen to set
	 */
	public void setNumAvisoDictamen(String numAvisoDictamen) {
		this.numAvisoDictamen = numAvisoDictamen;
	}

	/**
	 * @return the cvePatronFiscal
	 */
	@Column(name="CVE_FK_PATRON_FISCA")
	public Long getCvePatronFiscal() {
		return cvePatronFiscal;
	}
	/**
	 * @param cvePatronFiscal the cvePatronFiscal to set
	 */
	public void setCvePatronFiscal(Long cvePatronFiscal) {
		this.cvePatronFiscal = cvePatronFiscal;
	}

	/**
	 * @return the cveSubdelegDest
	 */
	@Column(name="CVE_FK_SUBDELEG_DEST")
	public Long getCveSubdelegDest() {
		return cveSubdelegDest;
	}
	/**
	 * @param cveSubdelegDest the cveSubdelegDest to set
	 */
	public void setCveSubdelegDest(Long cveSubdelegDest) {
		this.cveSubdelegDest = cveSubdelegDest;
	}

	/**
	 * @return the txReferenciaSubdeleg
	 */
	@Column(name="TX_RFRENCIA_SBDELEG")
	public String getTxReferenciaSubdeleg() {
		return txReferenciaSubdeleg;
	}
	/**
	 * @param txReferenciaSubdeleg the txReferenciaSubdeleg to set
	 */
	public void setTxReferenciaSubdeleg(String txReferenciaSubdeleg) {
		this.txReferenciaSubdeleg = txReferenciaSubdeleg;
	}

	/**
	 * @return the cveDomicilioFiscal
	 */
	@Column(name="CVE_ID_DOMICILIO_FISCA")
	public Long getCveDomicilioFiscal() {
		return cveDomicilioFiscal;
	}
	/**
	 * @param cveDomicilioFiscal the cveDomicilioFiscal to set
	 */
	public void setCveDomicilioFiscal(Long cveDomicilioFiscal) {
		this.cveDomicilioFiscal = cveDomicilioFiscal;
	}
	
	
}
