<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><xs:schema xmlns:tns="http://service.central.historico.imss.gob.mx/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://service.central.historico.imss.gob.mx/">

<xs:element name="getHistoricoCentralByNss" type="tns:getHistoricoCentralByNss"/>

<xs:element name="getHistoricoCentralByNssResponse" type="tns:getHistoricoCentralByNssResponse"/>

<xs:complexType name="getHistoricoCentralByNss">
<xs:sequence>
<xs:element name="nss" type="xs:string" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getHistoricoCentralByNssResponse">
<xs:sequence>
<xs:element name="return" type="tns:respuestaHistoricoCentral" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="respuestaHistoricoCentral">
<xs:complexContent>
<xs:extension base="tns:respuestaWS">
<xs:sequence>
<xs:element name="listaRespuesta" type="tns:HistoricoCentralVo" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="respuestaWS">
<xs:sequence>
<xs:element name="clave" type="xs:string"/>
<xs:element name="mensaje" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="HistoricoCentralVo">
<xs:sequence>
<xs:element name="nss" type="xs:string" minOccurs="0"/>
<xs:element name="registroPatronal" type="xs:string" minOccurs="0"/>
<xs:element name="claveModalidad" type="xs:string" minOccurs="0"/>
<xs:element name="fechaInicioMovimiento" type="xs:string" minOccurs="0"/>
<xs:element name="numeroConsecutivoPeriodos" type="xs:long"/>
<xs:element name="curp" type="xs:string" minOccurs="0"/>
<xs:element name="fechaFinalMovimiento" type="xs:string" minOccurs="0"/>
<xs:element name="origenMovimientoInicial" type="xs:string" minOccurs="0"/>
<xs:element name="origenMovimientoFinal" type="xs:string" minOccurs="0"/>
<xs:element name="tipoMovimientoInicial" type="xs:int"/>
<xs:element name="tipoMovimientoFinal" type="xs:int"/>
<xs:element name="fechaRecepcionMovimiento" type="xs:string" minOccurs="0"/>
<xs:element name="salarioBase" type="xs:double" minOccurs="0"/>
<xs:element name="tipoSalario" type="xs:string" minOccurs="0"/>
<xs:element name="semJor" type="xs:string" minOccurs="0"/>
<xs:element name="idEventual" type="xs:string" minOccurs="0"/>
<xs:element name="idSubrServ" type="xs:string" minOccurs="0"/>
<xs:element name="huelga" type="xs:string" minOccurs="0"/>
<xs:element name="extConSusp" type="xs:string" minOccurs="0"/>
<xs:element name="fecAct" type="xs:string" minOccurs="0"/>
<xs:element name="cveDelegOrig" type="xs:string" minOccurs="0"/>
<xs:element name="claveCiz" type="xs:int"/>
</xs:sequence>
</xs:complexType>
</xs:schema>