#HOST_MEXICO=127.0.0.1
#USER_CORREO=prueba
#PASSWORD_CORREO=prueba
#FROMIMSS_CORREO=pablo.bombela@imss.gob.mx
#TOIMSS_CORREO=pablo.bombela@imss.gob.mx


#HOST_MEXICO=11.254.12.85
HOST_MEXICO=relay.imss.gob.mx
USER_CORREO=g.derechohabientes
PASSWORD_CORREO=g3st10n.d3r3c#0#4b
FROMIMSS_CORREO=gestion.derechohabientes@imss.gob.mx
TOIMSS_CORREO=ignacio.espinosav@imss.gob.mx
AUTENTICACION=false
PROTOCOLO=smtp
PUERTO=25