//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.10 at 01:37:48 PM CDT 
//


package mx.gob.imss.ctirss.delta.model.derechohabiente.negocio;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import mx.gob.imss.ctirss.delta.model.asegurado.Asegurado;
import mx.gob.imss.ctirss.delta.model.asegurado.AseguradoPension;
import mx.gob.imss.ctirss.delta.model.asegurado.AsignacionNSS;
import mx.gob.imss.ctirss.delta.model.asegurado.BalancePrestacion;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Caracter;
import mx.gob.imss.ctirss.delta.model.derechohabiente.CategoriaPregunta;
import mx.gob.imss.ctirss.delta.model.derechohabiente.ClavePresupuestal;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Consultorio;
import mx.gob.imss.ctirss.delta.model.derechohabiente.CorreccionDatoDerechohabiente;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Derechohabiente;
import mx.gob.imss.ctirss.delta.model.derechohabiente.DiasFestivos;
import mx.gob.imss.ctirss.delta.model.derechohabiente.EstadoDerechohabiente;
import mx.gob.imss.ctirss.delta.model.derechohabiente.GrupoFamiliar;
import mx.gob.imss.ctirss.delta.model.derechohabiente.MedicoEnTurno;
import mx.gob.imss.ctirss.delta.model.derechohabiente.MedicoFamiliar;
import mx.gob.imss.ctirss.delta.model.derechohabiente.NivelAtencion;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Parentesco;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Pregunta;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Prorroga;
import mx.gob.imss.ctirss.delta.model.derechohabiente.RazonCancelacion;
import mx.gob.imss.ctirss.delta.model.derechohabiente.RazonRegistro;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Respuesta;
import mx.gob.imss.ctirss.delta.model.derechohabiente.RespuestaCuestionario;
import mx.gob.imss.ctirss.delta.model.derechohabiente.RestriccionServicio;
import mx.gob.imss.ctirss.delta.model.derechohabiente.SubEstadoDerechohabiente;
import mx.gob.imss.ctirss.delta.model.derechohabiente.TipoCuestionario;
import mx.gob.imss.ctirss.delta.model.derechohabiente.TipoPregunta;
import mx.gob.imss.ctirss.delta.model.derechohabiente.TipoUMF;
import mx.gob.imss.ctirss.delta.model.derechohabiente.Turno;
import mx.gob.imss.ctirss.delta.model.derechohabiente.UMFTurno;
import mx.gob.imss.ctirss.delta.model.derechohabiente.UnidadMedicaFamiliar;
import mx.gob.imss.ctirss.delta.model.domicilio.Asentamiento;
import mx.gob.imss.ctirss.delta.model.domicilio.CodigoPostal;
import mx.gob.imss.ctirss.delta.model.domicilio.CodigoPostalAsentamiento;
import mx.gob.imss.ctirss.delta.model.domicilio.Delegacion;
import mx.gob.imss.ctirss.delta.model.domicilio.Domicilio;
import mx.gob.imss.ctirss.delta.model.domicilio.EntidadFederativa;
import mx.gob.imss.ctirss.delta.model.domicilio.Localidad;
import mx.gob.imss.ctirss.delta.model.domicilio.Municipio;
import mx.gob.imss.ctirss.delta.model.domicilio.Subdelegacion;
import mx.gob.imss.ctirss.delta.model.domicilio.TipoAsentamiento;
import mx.gob.imss.ctirss.delta.model.domicilio.TipoVialidad;
import mx.gob.imss.ctirss.delta.model.domicilio.Vialidad;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Acta;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Acuerdo;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.CURP;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.CartillaMilitar;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.CedulaProfesional;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.CertificadoNacimiento;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.CertificadoSituacionCritica;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.ComprobanteDomicilio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.ConstanciaEstudio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.DictamenIntegranteIncapacitado;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Divorcio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.DocumentoProbatorio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Ife;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Matrimonio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Nacimiento;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Obstetrico;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Pasaporte;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.Reconocimiento;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.TipoActa;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.TipoComprobanteDomicilio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.TipoDocumentoProbatorio;
import mx.gob.imss.ctirss.delta.model.gestion.documento.probatorio.VigenciaTemporal;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.EstadoCivil;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.EstadoPersona;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Fisica;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Moral;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Persona;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.PersonaDomicilio;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.RazonResultado;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Sexo;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.Situacion;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.TipoEmpresa;
import mx.gob.imss.ctirss.delta.model.gestion.individuo.TipoPersona;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.EstadoSolicitud;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.EstadoTramite;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.Modalidad;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.RegistroPatronal;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.Servicio;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.ServiciosModalidad;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.SujetoObligado;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.TipoMovimientoPatronal;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.TipoSolicitud;
import mx.gob.imss.ctirss.delta.model.gestion.patronal.TipoTramite;
import mx.gob.imss.ctirss.delta.model.gestion.solicitud.SubEstadoValidado;
import mx.gob.imss.ctirss.delta.model.gestion.tramite.DocumentacionTramite;
import mx.gob.imss.ctirss.delta.model.gestion.tramite.TramiteRegistroDerechohabiente;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.imss.ctirss.delta.derechohabientes.model.negocio package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocumentoProbatorio_QNAME = new QName("modelo", "DocumentoProbatorio");
    private final static QName _TipoRetiro_QNAME = new QName("modelo", "TipoRetiro");
    private final static QName _DomicilioParticular_QNAME = new QName("modelo", "DomicilioParticular");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.imss.ctirss.delta.derechohabientes.model.negocio
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VigenciaTemporal }
     * 
     */
    public VigenciaTemporal createVigenciaTemporal() {
        return new VigenciaTemporal();
    }

    /**
     * Create an instance of {@link SujetoObligado }
     * 
     */
    public SujetoObligado createSujetoObligado() {
        return new SujetoObligado();
    }

    /**
     * Create an instance of {@link EstadoTramite }
     * 
     */
    public EstadoTramite createEstadoTramite() {
        return new EstadoTramite();
    }

    /**
     * Create an instance of {@link TipoPregunta }
     * 
     */
    public TipoPregunta createTipoPregunta() {
        return new TipoPregunta();
    }

    /**
     * Create an instance of {@link Nacimiento }
     * 
     */
    public Nacimiento createNacimiento() {
        return new Nacimiento();
    }

    /**
     * Create an instance of {@link Modalidad }
     * 
     */
    public Modalidad createModalidad() {
        return new Modalidad();
    }

    /**
     * Create an instance of {@link EstadoPersona }
     * 
     */
    public EstadoPersona createEstadoPersona() {
        return new EstadoPersona();
    }

    /**
     * Create an instance of {@link Acta }
     * 
     */
    public Acta createActa() {
        return new Acta();
    }

    /**
     * Create an instance of {@link Caracter }
     * 
     */
    public Caracter createCaracter() {
        return new Caracter();
    }

    /**
     * Create an instance of {@link Situacion }
     * 
     */
    public Situacion createSituacion() {
        return new Situacion();
    }

    /**
     * Create an instance of {@link Acuerdo }
     * 
     */
    public Acuerdo createAcuerdo() {
        return new Acuerdo();
    }

    /**
     * Create an instance of {@link AseguradoPension }
     * 
     */
    public AseguradoPension createAseguradoPension() {
        return new AseguradoPension();
    }

    /**
     * Create an instance of {@link TipoComprobanteDomicilio }
     * 
     */
    public TipoComprobanteDomicilio createTipoComprobanteDomicilio() {
        return new TipoComprobanteDomicilio();
    }

    /**
     * Create an instance of {@link UmfTurno }
     * 
     */
    public UMFTurno createUmfTurno() {
        return new UMFTurno();
    }

    /**
     * Create an instance of {@link Matrimonio }
     * 
     */
    public Matrimonio createMatrimonio() {
        return new Matrimonio();
    }

    /**
     * Create an instance of {@link Derechohabiente }
     * 
     */
    public Derechohabiente createDerechohabiente() {
        return new Derechohabiente();
    }

    /**
     * Create an instance of {@link CedulaProfesional }
     * 
     */
    public CedulaProfesional createCedulaProfesional() {
        return new CedulaProfesional();
    }

   

    /**
     * Create an instance of {@link TipoDocumentoProbatorio }
     * 
     */
    public TipoDocumentoProbatorio createTipoDocumentoProbatorio() {
        return new TipoDocumentoProbatorio();
    }

    /**
     * Create an instance of {@link SubdelegacionIMSS }
     * 
     */
    public Subdelegacion createSubdelegacion() {
        return new Subdelegacion();
    }

    /**
     * Create an instance of {@link Moral }
     * 
     */
    public Moral createMoral() {
        return new Moral();
    }

  
    /**
     * Create an instance of {@link NivelAtencion }
     * 
     * 
     */
    public NivelAtencion createNivelAtencion() {
        return new NivelAtencion();
    }

    /**
     * Create an instance of {@link Localidad }
     * 
     */
    public Localidad createLocalidad() {
        return new Localidad();
    }

    /**
     * Create an instance of {@link Vialidad }
     * 
     */
    public Vialidad createVialidad() {
        return new Vialidad();
    }

    /**
     * Create an instance of {@link Asegurado }
     * 
     */
    public Asegurado createAsegurado() {
        return new Asegurado();
    }

    /**
     * Create an instance of {@link CorreccionDatoDerechohabiente }
     * 
     */
    public CorreccionDatoDerechohabiente createCorreccionDatoDerechohabiente() {
        return new CorreccionDatoDerechohabiente();
    }

    /**
     * Create an instance of {@link DocumentoProbatorio }
     * 
     */
    public DocumentoProbatorio createDocumentoProbatorio() {
        return new DocumentoProbatorio();
    }

  

    /**
     * Create an instance of {@link GrupoFamiliar }
     * 
     */
    public GrupoFamiliar createGrupoFamiliar() {
        return new GrupoFamiliar();
    }

    /**
     * Create an instance of {@link MedicoEnTurno }
     * 
     */
    public MedicoEnTurno createMedicoEnTurno() {
        return new MedicoEnTurno();
    }

    /**
     * Create an instance of {@link SubEstadoDerechohabiente }
     * 
     */
    public SubEstadoDerechohabiente createSubEstadoDerechohabiente() {
        return new SubEstadoDerechohabiente();
    }

    /**
     * Create an instance of {@link CategoriaPregunta }
     * 
     */
    public CategoriaPregunta createCategoriaPregunta() {
        return new CategoriaPregunta();
    }

    /**
     * Create an instance of {@link Obstetrico }
     * 
     */
    public Obstetrico createObstetrico() {
        return new Obstetrico();
    }

    /**
     * Create an instance of {@link TipoAsentamiento }
     * 
     */
    public TipoAsentamiento createTipoAsentamiento() {
        return new TipoAsentamiento();
    }

    /**
     * Create an instance of {@link Pasaporte }
     * 
     */
    public Pasaporte createPasaporte() {
        return new Pasaporte();
    }

    /**
     * Create an instance of {@link SubEstadoValidado }
     * 
     */
    public SubEstadoValidado createSubEstadoValidado() {
        return new SubEstadoValidado();
    }

  
    /**
     * Create an instance of {@link ClavePresupuestal }
     * 
     */
    public ClavePresupuestal createClavePresupuestal() {
        return new ClavePresupuestal();
    }

    /**
     * Create an instance of {@link DocumentacionTramite }
     * 
     */
    public DocumentacionTramite createDocumentacionTramite() {
        return new DocumentacionTramite();
    }

    /**
     * Create an instance of {@link Solicitud }
     * 
     */
    public Solicitud createSolicitud() {
        return new Solicitud();
    }

    /**
     * Create an instance of {@link Ife }
     * 
     */
    public Ife createIfe() {
        return new Ife();
    }

    /**
     * Create an instance of {@link ConstanciaEstudio }
     * 
     */
    public ConstanciaEstudio createConstanciaEstudio() {
        return new ConstanciaEstudio();
    }

    /**
     * Create an instance of {@link EstadoDerechohabiente }
     * 
     */
    public EstadoDerechohabiente createEstadoDerechohabiente() {
        return new EstadoDerechohabiente();
    }

   
    /**
     * Create an instance of {@link TramiteRegistroDerechohabiente }
     * 
     */
    public TramiteRegistroDerechohabiente createRegistroDerechohabiente() {
        return new TramiteRegistroDerechohabiente();
    }

    /**
     * Create an instance of {@link RazonRegistro }
     * 
     */
    public RazonRegistro createRazonRegistro() {
        return new RazonRegistro();
    }

    /**
     * Create an instance of {@link TipoSolicitud }
     * 
     */
    public TipoSolicitud createTipoSolicitud() {
        return new TipoSolicitud();
    }

    /**
     * Create an instance of {@link CodigoPostal }
     * 
     */
    public CodigoPostal createCodigoPostal() {
        return new CodigoPostal();
    }

    /**
     * Create an instance of {@link Fisica }
     * 
     */
    public Fisica createFisica() {
        return new Fisica();
    }

    /**
     * Create an instance of {@link RestriccionServicio }
     * 
     */
    public RestriccionServicio createRestriccionServicio() {
        return new RestriccionServicio();
    }

    /**
     * Create an instance of {@link RegistroPatronal }
     * 
     */
    public RegistroPatronal createRegistroPatronal() {
        return new RegistroPatronal();
    }

  
    /**
     * Create an instance of {@link Consultorio }
     * 
     */
    public Consultorio createConsultorio() {
        return new Consultorio();
    }

    /**
     * Create an instance of {@link Reconocimiento }
     * 
     */
    public Reconocimiento createReconocimiento() {
        return new Reconocimiento();
    }

    /**
     * Create an instance of {@link ComprobanteDomicilio }
     * 
     */
    public ComprobanteDomicilio createComprobanteDomicilio() {
        return new ComprobanteDomicilio();
    }

    /**
     * Create an instance of {@link EstadoSolicitud }
     * 
     */
    public EstadoSolicitud createEstadoSolicitud() {
        return new EstadoSolicitud();
    }

   
    /**
     * Create an instance of {@link MedicoFamiliar }
     * 
     */
    public MedicoFamiliar createMedicoFamiliar() {
        return new MedicoFamiliar();
    }

   
    /**
     * Create an instance of {@link Parentesco }
     * 
     */
    public Parentesco createParentesco() {
        return new Parentesco();
    }

    /**
     * Create an instance of {@link RazonResultado }
     * 
     */
    public RazonResultado createRazonResultado() {
        return new RazonResultado();
    }

    /**
     * Create an instance of {@link TipoPersona }
     * 
     */
    public TipoPersona createTipoPersona() {
        return new TipoPersona();
    }

    /**
     * Create an instance of {@link Servicio }
     * 
     */
    public Servicio createServicio() {
        return new Servicio();
    }

    

    /**
     * Create an instance of {@link TipoVialidad }
     * 
     */
    public TipoVialidad createTipoVialidad() {
        return new TipoVialidad();
    }

    /**
     * Create an instance of {@link RespuestaCuestionario }
     * 
     */
    public RespuestaCuestionario createRespuestaCuestionario() {
        return new RespuestaCuestionario();
    }

    /**
     * Create an instance of {@link Asentamiento }
     * 
     */
    public Asentamiento createAsentamiento() {
        return new Asentamiento();
    }

    /**
     * Create an instance of {@link AsignacionNSS }
     * 
     */
    public AsignacionNSS createAsignacionNSS() {
        return new AsignacionNSS();
    }

    /**
     * Create an instance of {@link Turno }
     * 
     */
    public Turno createTurno() {
        return new Turno();
    }

    /**
     * Create an instance of {@link RazonCancelacion }
     * 
     */
    public RazonCancelacion createRazonCancelacion() {
        return new RazonCancelacion();
    }

    /**
     * Create an instance of {@link Domicilio }
     * 
     */
    public Domicilio createDomicilio() {
        return new Domicilio();
    }

    /**
     * Create an instance of {@link FuncionarioPublicoIMSS }
     * 
     */
    public FuncionarioPublicoIMSS createFuncionarioPublicoIMSS() {
        return new FuncionarioPublicoIMSS();
    }

    /**
     * Create an instance of {@link BalancePrestacion }
     * 
     */
    public BalancePrestacion createBalancePrestacion() {
        return new BalancePrestacion();
    }

    /**
     * Create an instance of {@link CertificadoSituacionCritica }
     * 
     */
    public CertificadoSituacionCritica createCertificadoSituacionCritica() {
        return new CertificadoSituacionCritica();
    }

    /**
     * Create an instance of {@link TipoEmpresa }
     * 
     */
    public TipoEmpresa createTipoEmpresa() {
        return new TipoEmpresa();
    }

    /**
     * Create an instance of {@link TipoMovimientoPatronal }
     * 
     */
    public TipoMovimientoPatronal createTipoMovimientoPatronal() {
        return new TipoMovimientoPatronal();
    }

    /**
     * Create an instance of {@link Rol }
     * 
     */
    public Rol createRol() {
        return new Rol();
    }

    /**
     * Create an instance of {@link PersonaDomicilio }
     * 
     */
    public PersonaDomicilio createPersonaDomicilio() {
        return new PersonaDomicilio();
    }

    /**
     * Create an instance of {@link EntidadFederativa }
     * 
     */
    public EntidadFederativa createEntidadFederativa() {
        return new EntidadFederativa();
    }

    /**
     * Create an instance of {@link EstadoCivil }
     * 
     */
    public EstadoCivil createEstadoCivil() {
        return new EstadoCivil();
    }

    /**
     * Create an instance of {@link ServiciosModalidad }
     * 
     */
    public ServiciosModalidad createServiciosModalidad() {
        return new ServiciosModalidad();
    }

    /**
     * Create an instance of {@link TipoUMF }
     * 
     */
    public TipoUMF createTipoUMF() {
        return new TipoUMF();
    }

    /**
     * Create an instance of {@link Pregunta }
     * 
     */
    public Pregunta createPregunta() {
        return new Pregunta();
    }

    /**
     * Create an instance of {@link Municipio }
     * 
     */
    public Municipio createMunicipio() {
        return new Municipio();
    }

    /**
     * Create an instance of {@link DiasFestivos }
     * 
     */
    public DiasFestivos createDiasFestivos() {
        return new DiasFestivos();
    }

    /**
     * Create an instance of {@link Sexo }
     * 
     */
    public Sexo createSexo() {
        return new Sexo();
    }

   
    /**
     * Create an instance of {@link DelegacionIMSS }
     * 
     */
    public Delegacion createDelegacion() {
        return new Delegacion();
    }

    /**
     * Create an instance of {@link CertificadoNacimiento }
     * 
     */
    public CertificadoNacimiento createCertificadoNacimiento() {
        return new CertificadoNacimiento();
    }

    /**
     * Create an instance of {@link TipoCuestionario }
     * 
     */
    public TipoCuestionario createTipoCuestionario() {
        return new TipoCuestionario();
    }

    /**
     * Create an instance of {@link Divorcio }
     * 
     */
    public Divorcio createDivorcio() {
        return new Divorcio();
    }

    /**
     * Create an instance of {@link Respuesta }
     * 
     */
    public Respuesta createRespuesta() {
        return new Respuesta();
    }

    /**
     * Create an instance of {@link Persona }
     * 
     */
    public Persona createPersona() {
        return new Persona();
    }

    /**
     * Create an instance of {@link TipoActa }
     * 
     */
    public TipoActa createTipoActa() {
        return new TipoActa();
    }

    /**
     * Create an instance of {@link TipoTramite }
     * 
     */
    public TipoTramite createTipoTramite() {
        return new TipoTramite();
    }

    /**
     * Create an instance of {@link Prorroga }
     * 
     */
    public Prorroga createProrroga() {
        return new Prorroga();
    }

    /**
     * Create an instance of {@link UnidadMedicaFamiliar }
     * 
     */
    public UnidadMedicaFamiliar createUnidadMedicaFamiliar() {
        return new UnidadMedicaFamiliar();
    }

    /**
     * Create an instance of {@link Tramite }
     * 
     */
    public Tramite createTramite() {
        return new Tramite();
    }

    /**
     * Create an instance of {@link CURP }
     * 
     */
    public CURP createCURP() {
        return new CURP();
    }

    /**
     * Create an instance of {@link CartillaMilitar }
     * 
     */
    public CartillaMilitar createCartillaMilitar() {
        return new CartillaMilitar();
    }

    /**
     * Create an instance of {@link CodigoPostalAsentamiento }
     * 
     */
    public CodigoPostalAsentamiento createCodigoPostalAsentamiento() {
        return new CodigoPostalAsentamiento();
    }

    /**
     * Create an instance of {@link DictamenIntegranteIncapacitado }
     * 
     */
    public DictamenIntegranteIncapacitado createDictamenIntegranteIncapacitado() {
        return new DictamenIntegranteIncapacitado();
    }

  

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentoProbatorio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "modelo", name = "DocumentoProbatorio")
    public JAXBElement<DocumentoProbatorio> createDocumentoProbatorio(DocumentoProbatorio value) {
        return new JAXBElement<DocumentoProbatorio>(_DocumentoProbatorio_QNAME, DocumentoProbatorio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "modelo", name = "TipoRetiro")
    public JAXBElement<Object> createTipoRetiro(Object value) {
        return new JAXBElement<Object>(_TipoRetiro_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Domicilio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "modelo", name = "DomicilioParticular")
    public JAXBElement<Domicilio> createDomicilioParticular(Domicilio value) {
        return new JAXBElement<Domicilio>(_DomicilioParticular_QNAME, Domicilio.class, null, value);
    }

}
