#PAGINA DE INICIO DEL SISTEMA DE GESTION DE PERSONAS
PaginaInicialPersonas.(class)=org.springframework.web.servlet.view.tiles2.TilesView
PaginaInicialPersonas.url=PaginaInicialPersonas

busquedaSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaSolicitud.url=busquedaSolicitud

resultadoBusquedaSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
resultadoBusquedaSolicitud.url=resultadoBusquedaSolicitud

################################################################################
########################### PERSONAS FISICAS ###################################
################################################################################

registroPersonaFisica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPersonaFisica.url=registroPersonaFisica

registroPersonaFisicaCaptura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPersonaFisicaCaptura.url=registroPersonaFisicaCaptura

busquedaPersonaFisica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaPersonaFisica.url=busquedaPersonaFisica

registroPersonaFisicaIMSSResultado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPersonaFisicaIMSSResultado.url=registroPersonaFisicaIMSSResultado

confirmacionRegistroPersona.(class)=org.springframework.web.servlet.view.tiles2.TilesView
confirmacionRegistroPersona.url=confirmacionRegistroPersona

CargaMasivaFisica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
CargaMasivaFisica.url=CargaMasivaFisica

modificacionPersonaFisica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
modificacionPersonaFisica.url=modificacionPersonaFisica

busquedaDatosComplementariosPersonaFisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
busquedaDatosComplementariosPersonaFisica.url = busquedaDatosComplementariosPersonaFisica

busquedaEmbebidaPersonaFisica.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaEmbebidaPersonaFisica.url=busquedaEmbebidaPersonaFisica

################################################################################
########################### PERSONAS MORALES ###################################
################################################################################

registroPersonaMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPersonaMoral.url=registroPersonaMoral

registroPersonaMoralCaptura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPersonaMoralCaptura.url=registroPersonaMoralCaptura

busquedaPersonaMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaPersonaMoral.url=busquedaPersonaMoral

registroPersonaMoralIMSSResultado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
registroPersonaMoralIMSSResultado.url=registroPersonaMoralIMSSResultado

CargaMasivaMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
CargaMasivaMoral.url=CargaMasivaMoral

busquedaDatosComplementariosPersonaMoral.(class) = org.springframework.web.servlet.view.tiles2.TilesView
busquedaDatosComplementariosPersonaMoral.url = busquedaDatosComplementariosPersonaMoral

busquedaEmbebidaPersonaMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaEmbebidaPersonaMoral.url=busquedaEmbebidaPersonaMoral

################################################################################
################################################################################
################################################################################

bienvenido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
bienvenido.url=bienvenido

orquestador.(class)=org.springframework.web.servlet.view.tiles2.TilesView
orquestador.url=orquestador

mensajes.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mensajes.url=mensajes

busquedaComprobanteSolicitud.(class)=org.springframework.web.servlet.view.tiles2.TilesView
busquedaComprobanteSolicitud.url=busquedaComprobanteSolicitud

# Definicion de la pantalla del contenedor de las selecciones de las busquedas de personas fisicas #
contenedorBusquedaPersonaFisica.(class) = org.springframework.web.servlet.view.tiles2.TilesView
contenedorBusquedaPersonaFisica.url = contenedorBusquedaPersonaFisica

#### Definicion de la pantalla de la consulta embebida de personas fisicas #####
busquedaEmbebidaPersonaFisicaResultados.(class)=org.springframework.web.servlet.view.JstlView
busquedaEmbebidaPersonaFisicaResultados.url=/WEB-INF/views/persona/fisica/busqueda/resultados.jsp

#### Definicion de la pantalla de la consulta embebida de personas morales #####
busquedaEmbebidaPersonaMoralResultados.(class)=org.springframework.web.servlet.view.JstlView
busquedaEmbebidaPersonaMoralResultados.url=/WEB-INF/views/persona/moral/busqueda/resultados.jsp


##Componentes
detalleIndividuo.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleIndividuo.url=detalleIndividuo

detalleIndividuoMoral.(class)=org.springframework.web.servlet.view.tiles2.TilesView
detalleIndividuoMoral.url=detalleIndividuoMoral


individuoTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
individuoTest.url=individuoTest



#########################################################################
###### Vistas del manejo de errores generales ###########################
error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError
S