#sellado.keystore=/Users/vanderluk/Downloads/CFDI/ProyectosCFDI/factura-electronica-master/resources/certs/keystore.jks
sellado.keystore=/weblogic/oracle/Middleware/user_projects/domains/perifericosdev01_domain/keystore.jks
sellado.alias=ctdivcont.2012
sellado.pwd=CTDIVCONT.2012
#sellado.xslt=/Users/vanderluk/timbrado/xslt/cadenaoriginal_3_2.xslt

###### Version 3.2 ######
#sellado.xslt=/xslt/cadenaoriginal_3_2.xslt

###### Version 3.3 ######
sellado.xslt=/xslt/cadenaoriginal_3_3.xslt
#sellado.xslt=/example.xslt