<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>AdmonUsuariosDelta</artifactId>
        <groupId>mx.gob.imss.ctirss.sso</groupId>
        <version>1.1-SNAPSHOT</version>
    </parent>

    <groupId>mx.gob.imss.ctirss.sso</groupId>
    <artifactId>AdmonUsuariosDelta-ear</artifactId>
    <version>1.1-SNAPSHOT</version>
    <packaging>ear</packaging>

    <name>Administración de Usuarios Delta EAR</name>
    <url>http://maven.apache.org</url>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.0.2</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                    <encoding>ISO-8859-1</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <version>5</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                </configuration>
            </plugin>
        </plugins>
        <pluginManagement>
        	<plugins>
        		<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
        		<plugin>
        			<groupId>org.eclipse.m2e</groupId>
        			<artifactId>lifecycle-mapping</artifactId>
        			<version>1.0.0</version>
        			<configuration>
        				<lifecycleMappingMetadata>
        					<pluginExecutions>
        						<pluginExecution>
        							<pluginExecutionFilter>
        								<groupId>
        									org.apache.maven.plugins
        								</groupId>
        								<artifactId>
        									maven-ear-plugin
        								</artifactId>
        								<versionRange>
        									[2.6,)
        								</versionRange>
        								<goals>
        									<goal>
        										generate-application-xml
        									</goal>
        								</goals>
        							</pluginExecutionFilter>
        							<action>
        								<ignore></ignore>
        							</action>
        						</pluginExecution>
        					</pluginExecutions>
        				</lifecycleMappingMetadata>
        			</configuration>
        		</plugin>
        	</plugins>
        </pluginManagement>
    </build>
    <dependencies>
        <dependency>
            <groupId>mx.gob.imss.ctirss.sso</groupId>
            <artifactId>AdmonUsuariosDelta-ejb</artifactId>
            <version>1.1-SNAPSHOT</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>mx.gob.imss.ctirss.sso</groupId>
            <artifactId>Sauimssdigital</artifactId>
            <version>1.1-SNAPSHOT</version>
            <type>war</type>
        </dependency>        
       <!-- <dependency>
        	<groupId>mx.gob.imss.ctirss.sso</groupId>
        	<artifactId>RegistroSolicitudUsrDelta-war</artifactId>
        	<version>1.0-SNAPSHOT</version> 
        	<type>war</type>       	
    	</dependency> -->
    </dependencies>
    <properties>
        <netbeans.hint.deploy.server>gfv3ee6</netbeans.hint.deploy.server>
    </properties>
    <profiles>
        <profile>
            <id>QA</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.oracle.weblogic</groupId>
                        <artifactId>weblogic-maven-plugin</artifactId>
                        <version>10.3.4</version>
                        <executions>
                            <execution>
                                <id>Deploy</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>deploy</goal>
                                </goals>
                                <configuration>
                                    <adminurl>t3://11.254.13.171:8001</adminurl>
                                    <user>weblogic</user>
                                    <password>w3bl0g1c</password>
                                    <upload>true</upload>
                                    <action>deploy</action>
                                    <remote>true</remote>
                                    <verbose>true</verbose>
                                    <source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
                                    <name>${project.build.finalName}</name>
                                </configuration>
                            </execution>
                            <execution>
                                <id>Undeploy</id>
                                <phase>clean</phase>
                                <goals>
                                    <goal>undeploy</goal>
                                </goals>
                                <configuration>
                                    <adminurl>t3://11.254.13.171:8001</adminurl>
                                    <user>weblogic</user>
                                    <password>w3bl0g1c</password>
                                    <upload>true</upload>
                                    <action>undeploy</action>
                                    <remote>true</remote>
                                    <verbose>true</verbose>
                                    <name>${project.build.finalName}</name>
                                    <graceful>false</graceful>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
