welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

############# WIZARDS #################
tramiteDummyInicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramiteDummyInicio.url=tramiteDummyInicio
tramiteDummyContenido.(class) = org.springframework.web.servlet.view.tiles2.TilesView
tramiteDummyContenido.url = tramiteDummyContenido

wizardDetalleDerechohabienteContenido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDetalleDerechohabienteContenido.url = wizardDetalleDerechohabienteContenido

listadoCandidatos.(class)=org.springframework.web.servlet.view.tiles2.TilesView
listadoCandidatos.url = listadoCandidatos

wizardCorreccionDerechohabienteInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardCorreccionDerechohabienteInit.url = wizardCorreccionDerechohabienteInit

wizardCorreccionDerechohabienteContent.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardCorreccionDerechohabienteContent.url = wizardCorreccionDerechohabienteContent

wizardBajaDerechohabienteInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardBajaDerechohabienteInit.url = wizardBajaDerechohabienteInit

wizardBajaDerechohabienteCiudadanoInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardBajaDerechohabienteCiudadanoInit.url = wizardBajaDerechohabienteCiudadanoInit

wizardBajaDerechohabienteContent.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardBajaDerechohabienteContent.url = wizardBajaDerechohabienteContent

wizardRegistroDerechohabienteInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistroDerechohabienteInit.url = wizardRegistroDerechohabienteInit

wizardRegistroCapturaPersona.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistroCapturaPersona.url = wizardRegistroCapturaPersona

wizardRegistroCapturaDomicilio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistroCapturaDomicilio.url = wizardRegistroCapturaDomicilio

wizardRegistroCapturaUmf.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardRegistroCapturaUmf.url = wizardRegistroCapturaUmf

wizardProrrogaDerechohabienteInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardProrrogaDerechohabienteInit.url = wizardProrrogaDerechohabienteInit

wizardProrrogaDerechohabienteCiudadanoInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardProrrogaDerechohabienteCiudadanoInit.url = wizardProrrogaDerechohabienteCiudadanoInit

wizardProrrogaDerechohabienteContent.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardProrrogaDerechohabienteContent.url = wizardProrrogaDerechohabienteContent

############# Wizard para la asignacion, cambio de domicilio y cambio de clinica #################
wizardDomicilioClinicaDerechohabienteInit.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDomicilioClinicaDerechohabienteInit.url = wizardDomicilioClinicaDerechohabienteInit

wizardDomicilioClinicaDerechohabienteContent.(class)=org.springframework.web.servlet.view.tiles2.TilesView
wizardDomicilioClinicaDerechohabienteContent.url = wizardDomicilioClinicaDerechohabienteContent

############# PORTLETS #################
portletDummyInicial.(class)=org.springframework.web.servlet.view.JstlView
portletDummyInicial.url=/WEB-INF/views/portlet/dummy/inicial.jsp
portletDummyContenido.(class)=org.springframework.web.servlet.view.JstlView
portletDummyContenido.url=/WEB-INF/views/portlet/dummy/contenido.jsp

portletGrupoFamiliarInit.(class)=org.springframework.web.servlet.view.JstlView
portletGrupoFamiliarInit.url=/WEB-INF/views/portlet/grupoFamiliar/inicial.jsp

portletGrupoFamiliarContenido.(class)=org.springframework.web.servlet.view.JstlView
portletGrupoFamiliarContenido.url=/WEB-INF/views/portlet/grupoFamiliar/contenido.jsp

portletDetalleIntegranteInit.(class)=org.springframework.web.servlet.view.JstlView
portletDetalleIntegranteInit.url=/WEB-INF/views/portlet/detalleIntegrante/inicial.jsp

portletDetalleIntegranteContenido.(class)=org.springframework.web.servlet.view.JstlView
portletDetalleIntegranteContenido.url=/WEB-INF/views/portlet/detalleIntegrante/contenido.jsp

portletDatosPatronInit.(class)=org.springframework.web.servlet.view.JstlView
portletDatosPatronInit.url=/WEB-INF/views/portlet/patron/inicial.jsp

portletDatosPatronContenido.(class)=org.springframework.web.servlet.view.JstlView
portletDatosPatronContenido.url=/WEB-INF/views/portlet/patron/contenido.jsp

portletSolicitudesProcesoInit.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesProcesoInit.url=/WEB-INF/views/portlet/solicitud/proceso/inicial.jsp

portletSolicitudesBeneficiarioInit.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesBeneficiarioInit.url=/WEB-INF/views/portlet/solicitud/beneficiario/inicial.jsp

portletSolicitudesProcesoContenido.(class)=org.springframework.web.servlet.view.JstlView
portletSolicitudesProcesoContenido.url=/WEB-INF/views/portlet/solicitud/proceso/contenido.jsp

portletOtrosGruposInit.(class)=org.springframework.web.servlet.view.JstlView
portletOtrosGruposInit.url=/WEB-INF/views/portlet/otrosGrupos/inicial.jsp

portletOtrosGruposContenido.(class)=org.springframework.web.servlet.view.JstlView
portletOtrosGruposContenido.url=/WEB-INF/views/portlet/otrosGrupos/contenido.jsp

portletPensionesInit.(class)=org.springframework.web.servlet.view.JstlView
portletPensionesInit.url=/WEB-INF/views/portlet/pensiones/inicial.jsp

############# WIDGETS #################
widgetDummyInicio.(class)=org.springframework.web.servlet.view.JstlView
widgetDummyInicio.url=/WEB-INF/views/widget/dummy/inicial.jsp
widgetDummyContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDummyContenido.url=/WEB-INF/views/widget/dummy/contenido.jsp

widgetArticulo82.(class)=org.springframework.web.servlet.view.JstlView
widgetArticulo82.url=/WEB-INF/views/widget/restricciones/articulo82.jsp
widgetArticulo83.(class)=org.springframework.web.servlet.view.JstlView
widgetArticulo83.url=/WEB-INF/views/widget/restricciones/articulo83.jsp
widgetArticulo84.(class)=org.springframework.web.servlet.view.JstlView
widgetArticulo84.url=/WEB-INF/views/widget/restricciones/articulo84.jsp

widgetVigenciaDerechohabienteInit.(class)=org.springframework.web.servlet.view.JstlView
widgetVigenciaDerechohabienteInit.url=/WEB-INF/views/widget/vigencia/inicial.jsp
widgetVigenciaDerechohabienteContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetVigenciaDerechohabienteContenido.url=/WEB-INF/views/widget/vigencia/contenido.jsp

widgetAdscripcionVigenciaInit.(class)=org.springframework.web.servlet.view.JstlView
widgetAdscripcionVigenciaInit.url=/WEB-INF/views/widget/adscripcionYVigencia/inicial.jsp
widgetAdscripcionVigenciaContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetAdscripcionVigenciaContenido.url=/WEB-INF/views/widget/adscripcionYVigencia/contenido.jsp

widgetServiciosAseguradoInit.(class)=org.springframework.web.servlet.view.JstlView
widgetServiciosAseguradoInit.url=/WEB-INF/views/widget/servicios/inicial.jsp
widgetServiciosAseguradoContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetServiciosAseguradoContenido.url=/WEB-INF/views/widget/servicios/contenido.jsp

widgetDomicilioGrupoFamiliarInit.(class)=org.springframework.web.servlet.view.JstlView
widgetDomicilioGrupoFamiliarInit.url=/WEB-INF/views/widget/domicilioGrupoFamiliar/inicial.jsp
widgetDomicilioGrupoFamiliarContenido.(class)=org.springframework.web.servlet.view.JstlView
widgetDomicilioGrupoFamiliarContenido.url=/WEB-INF/views/widget/domicilioGrupoFamiliar/contenido.jsp

errorReporteVigencia.(class)=org.springframework.web.servlet.view.tiles2.TilesView
errorReporteVigencia.url = errorReporteVigencia

initReporteVigencia.(class)=org.springframework.web.servlet.view.tiles2.TilesView
initReporteVigencia.url = initReporteVigencia