
package mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.documentows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AddDocumentActorRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AddDocumentActorResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AllDocumentVersionsByDocRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AllDocumentVersionsByDocResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AllDocumentVersionsMetadataByDocRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AllDocumentVersionsMetadataByDocResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AllMetadataByMetadataRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.AllMetadataByMetadataResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.CreateDocumentRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.CreateDocumentResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.DeleteDocumentRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.DeleteDocumentResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.DocumentRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.DocumentResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.DocumentsByMetadataRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.DocumentsByMetadataResponse;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.MetadataByDocRequest;
import mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.MetadataByDocResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IDocumentoWSService", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.ObjectFactory.class,
    mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.documentows.ObjectFactory.class,
    mx.gob.imss.cit.clienteServiciosComunes.bovedaPersonal.ws.bovedapersonalcommonschema.ObjectFactory.class,
    mx.gob.imss.cit.clienteServiciosComunes.ws.commonschema.ObjectFactory.class
})
public interface IDocumentoWSService {


    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DocumentResponse
     */
    @WebMethod
    @WebResult(name = "getDocumentResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public DocumentResponse getDocument(
        @WebParam(name = "getDocumentRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        DocumentRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.CreateDocumentResponse
     */
    @WebMethod
    @WebResult(name = "createDocumentResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public CreateDocumentResponse createDocument(
        @WebParam(name = "createDocumentRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        CreateDocumentRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DocumentsByMetadataResponse
     */
    @WebMethod
    @WebResult(name = "findDocumentsByMetadataResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public DocumentsByMetadataResponse findDocumentsByMetadata(
        @WebParam(name = "findDocumentsByMetadataRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        DocumentsByMetadataRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DeleteDocumentResponse
     */
    @WebMethod
    @WebResult(name = "deleteDocumentResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public DeleteDocumentResponse deleteDocument(
        @WebParam(name = "deleteDocumentRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        DeleteDocumentRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllMetadataByMetadataResponse
     */
    @WebMethod
    @WebResult(name = "getAllMetadataByMetadataResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public AllMetadataByMetadataResponse getAllMetadataByMetadata(
        @WebParam(name = "getAllMetadataByMetadataRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        AllMetadataByMetadataRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.MetadataByDocResponse
     */
    @WebMethod
    @WebResult(name = "getMetadataByDocResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public MetadataByDocResponse getMetadataByDoc(
        @WebParam(name = "getMetadataByDocRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        MetadataByDocRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocResponse
     */
    @WebMethod
    @WebResult(name = "getAllDocumentVersionsByDocResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public AllDocumentVersionsByDocResponse getAllDocumentVersionsByDoc(
        @WebParam(name = "getAllDocumentVersionsByDocRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        AllDocumentVersionsByDocRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocResponse
     */
    @WebMethod
    @WebResult(name = "getAllDocumentVersionsMetadataByDocResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public AllDocumentVersionsMetadataByDocResponse getAllDocumentVersionsMetadataByDoc(
        @WebParam(name = "getAllDocumentVersionsMetadataByDocRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        AllDocumentVersionsMetadataByDocRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AddDocumentActorResponse
     */
    @WebMethod
    @WebResult(name = "addDocumentActorResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
    public AddDocumentActorResponse addDocumentActor(
        @WebParam(name = "addDocumentActorRequest", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", partName = "body")
        AddDocumentActorRequest body);

}
