#inidicador para verificar las opciones en un archivo properties 
busqueda_properties = 1

#opciones del portlets
url_archivo = file:/share/oracle/zapdir01_domain/zapdir_cluster1/properties/opciones.properties

#url_archivo = file:d:/opciones.properties
#registro de patron
ind_reg_patron = 1
#opcion para activar la opcion para personas morales  en el widget
ind_reg_patron_pm=1
#recuperacion de patron
# Menu --Mis registros patronales--
ind_rec_patron = 0
#registro de empresa representada
ind_reg_repdo = 1
#Baja de empresa representada
ind_baja_repdo = 1
#baja de representante legal
ind_baja_repte = 1

#portlet de clasificacion
#tramite de modificacion ante el srt
ind_mod_srt = 1

#opciones de widgets

#widget de persona
#actualizar datos de medios de contacto
ind_datos_per = 1
#actualizar domicilio
ind_cambio_dom = 1
#Administrar medios de contacto
ind_medios_con = 1

#widget patron y opciones de patron
#ver detalle del patron
ind_detalle_patron = 1
#efectuar tramite de cambio de domicilio
ind_cambio_dom_patron = 1
#efectuar tramite de cambio de domicilio diferente municipio
ind_cambio_dom_patron_dif_mun=1
#efetuar tramite de cambio de datos de contacto
ind_medios_patron = 1
#indicador RIF
ind_rif = 1
#Ampliación para registros eventuales Modaidad 14
#ind_amp_reg_event_mod14 = 1
#Registro de Movimientos Afiliatorios
# Menu --Mis registros patronales--
ind_reg_mov_afil=0

#opciones de estado de adeudo
#impresion de estado de adeudo por motivo de cobro
ind_mostrar_adeudo = 1
ind_edo_cta_imss = 1
ind_edo_cta_rcv = 1
ind_comprobante_fiscal = 1

#opciones portal asegurado
ind_baja_defuncion = 1
ind_baja_dependencia = 1
ind_baja_concubina = 1
ind_baja_divorcio = 1
ind_registro_derechohabiente = 1
ind_correccion_datos_dhabiente = 1
ind_solicitud_pension = 1
ind_solicitud_cartilla = 1

#opciones prorroga.
ind_prorroga_permanente = 0
ind_prorroga_acuerdo = 0
ind_prorroga_obstetrica = 1
ind_prorrga_fisica_psiquica = 1
ind_prorroga_estudios = 1
ind_prorrga_laudo = 0
ind_prorroga_temporal = 0

#opcion de cammbiar domicilio
ind_cambio_domicilio = 1

#opcion para cambio de clinica
ind_cambio_clinica = 1

#indicador portlets personas autorizadas
ind_personas_aut = 1

#indicador portlets socios
ind_socios_pm = 1

#opciones de IVRO
ind_alta_seguro_voluntario = 1

#opciones de carta de no adeudo
ind_carta_no_adeudo = 0

#opcion de descarga de CFDI
ind_descarga_cfdi = 1

#opciones widget vigencia
ind_detalle_vigencia = 1

#opciones para el portal ciudadano
#asignacion de nss desde el portal ciudadano
ind_asignacion_nss = 0
#registro asegurado
ind_registro_asegurado = 1
#registro beneficiarios
ind_registro_beneficiarios = 0
#registro de hijos
ind_registro_hijos = 1
#registro de padres
ind_registro_padres = 0
#registro de conyuges
ind_registro_conyuge = 0
#registro de concubinas
ind_registro_concubina = 0
#cambio clinica del asegurado
ind_cambio_clinica_asegurado = 1
#cambio clinica de beneficiarios
ind_cambio_clinica_beneficiarios = 0
#baja defuncion ciudadano
ind_baja_defuncion_c = 1
#baja por termino de concubinato
ind_baja_concubinato_c = 1
#baja por divorcio
ind_baja_divorcio_c = 1
#baja por termino de dependencia
ind_baja_dependencia_c = 1
#consulta de vigencia en el portal ciudadano
ind_consulta_vigencia = 1
#IVRO individual
ind_ivro_individual = 0
#Actualizar Domicilio
ind_act_dom_ciudadano = 0
#IVRO Domestico
ind_ivro_domestico = 0
#RISS
ind_beneficios_riss_ciudadano = 0
#registro de patron
ind_registro_patronal_ciudadano = 0
#registro de patron SAT
#Menu --Registros Patronales--
ind_registro_patronal_ciudadano_sat = 0
#IVRO individual SAT
ind_ivro_individual_ciudadano_sat = 1
#Seguro familiar (Modalidad 33)
ind_seguro_familiar_ciudadano = 1
#CVRO - Continuacion Voluntaria (Modalidad 40)
ind_inscripcion_cvro_ciudadano = 1
#Prorroga por estudio portal Ciudadano
ind_prorroga_estudios_p = 0

#opciones para erechohabientes ventanilla
#registro de derechohabientes incluye todos los parentescos
ind_registro_derechohabientes_v = 1
#correccion de datos personales
ind_correccion_derechohabiente_v = 1
#cambio de clinica en origen y destino
ind_cambio_clinica_origen = 0
#cambio de clinica en origen y destino
ind_cambio_clinica_destino = 1
#cambio de medico consultorio y turno
ind_cambio_medico_turno_v = 1
#autorizacion para recibir servicios en circunscripcion foranea
ind_autorizacion_circunscripcion_v = 1
#suspencion de servicios en circunscripcion foranea
ind_suspencion_circunscripcion_v = 1
#aginacion de consultorio medico y turno
ind_asignacion_medico_v = 1
#baja defuncion ventanilla
ind_baja_defuncion_v = 1
#baja por termino de concubinato
ind_baja_concubinato_v = 1
#baja por divorcio
ind_baja_divorcio_v = 1
#baja por termino de dependencia
ind_baja_dependencia_v = 1
#baja administrativa
ind_baja_administrativa_v = 0
#prorroga por vigencia permanente
ind_prorroga_permanente_v = 0
#prorroga por acuerdos
ind_prorroga_acuerdo_v = 1
#prorroga por obstetricos
ind_prorroga_obstetrico_v =1
#prorroga por enfermedad fisica o psiquica
ind_prorroga_enfermedad_v = 1
#prorroga por estudios
ind_prorroga_estudios_v = 1
#prorroga por laudo
ind_prorroga_laudo_v = 1
#prorrga por vigencia temportal
ind_prorroga_temporal_v = 0
#cambio de clinica masivo
ind_cambio_clinica_masivo = 0
#registro de obra
ind_registro_obra = 1
#NMPS
ind_consulta_incap_folio = 1
ind_rango_fechas = 1
ind_nss = 1
ind_reembolso_subsidios = 1
ind_nmps_asegurado = 1
#habilitar el menu de la bandeja de incapacidades del patron
ind_nmps_bandeja_incap = 1
ind_nmps_validacion_cta_clabe = 1
#escrito de desacuerdo
ind_escrito_des = 1

#opciones del menu de tramites en seccion patronal para convenios
ind_solicitud_convenio=1
ind_consulta_convenio=1
ind_aviso_convenio=1
#Opciones del menu de tramites en seccion patronal para riesgos de trabajo 
ind_riesgo_trabajo_terminado =1
ind_riesgo_trabajo_terminado_rfc =1
#opciones para saber si se muestra  el mensaje de buzon tributario al ingresar la portal con fiel
ind_buzon_tributario_mostrar=0
#opcion para sistema SIST para produccion y dev
ind_sist_acceso_dev=0
ind_sist_acceso_prod=1


