#Simple JSP redirect
body.(class)=org.springframework.web.servlet.view.JstlView
body.url=/WEB-INF/views/layout/body.jsp
 
 
#Telefono fijo
telefono.fijo.(class)=org.springframework.web.servlet.view.JstlView
telefono.fijo.url=/WEB-INF/views/mediosContacto/telefonofijo.jsp

#Telefono movil
telefono.movil.(class)=org.springframework.web.servlet.view.JstlView
telefono.movil.url=/WEB-INF/views/mediosContacto/telefonomovil.jsp


#Correo
correo.(class)=org.springframework.web.servlet.view.JstlView
correo.url=/WEB-INF/views/mediosContacto/correo.jsp

 
#Tiles redirect

gestionMediosContacto.(class)=org.springframework.web.servlet.view.tiles2.TilesView
gestionMediosContacto.url=gestionMediosContacto

welcome.(class)=org.springframework.web.servlet.view.tiles2.TilesView
welcome.url=welcome
 
login.(class)=org.springframework.web.servlet.view.tiles2.TilesView
login.url=login

home.(class)=org.springframework.web.servlet.view.tiles2.TilesView
home.url=home

error.(class)=org.springframework.web.servlet.view.tiles2.TilesView
error.url=error

databaseError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
databaseError.url=databaseError

internalError.(class)=org.springframework.web.servlet.view.tiles2.TilesView
internalError.url=internalError

domicilio.registro.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registro.url=domicilioRegistro



domicilio.registroEmbebido.(class)=org.springframework.web.servlet.view.tiles2.TilesView
domicilio.registroEmbebido.url=domicilioRegistroEmbebed


tramite.inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.inicio.url=tramiteinicio

tramite.capturar.(class)=org.springframework.web.servlet.view.tiles2.TilesView
tramite.capturar.url=tramitecapturar

medioContacto.(class)=org.springframework.web.servlet.view.tiles2.TilesView
medioContacto.url=medioContacto

mediosContacto.inicio.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mediosContacto.inicio.url=mediosContacto.inicio

mediosContacto.finalizado.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mediosContacto.finalizado.url=mediosContacto.finalizado

mediosContacto.captura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
mediosContacto.captura.url=mediosContacto.captura

admonMediosContactoTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
admonMediosContactoTest.url=admonMediosContactoTest

admonMediosContactoWrapper.(class)=org.springframework.web.servlet.view.JstlView
admonMediosContactoWrapper.url=/WEB-INF/views/mediosContacto/administrar/admonMediosContactoWrapper.jsp

initAdmonMediosContacto.(class)=org.springframework.web.servlet.view.JstlView
initAdmonMediosContacto.url=/WEB-INF/views/mediosContacto/administrar/initAdmonMediosContacto.jsp

admon.mediosContacto.captura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
admon.mediosContacto.captura.url=admon.mediosContacto.captura



admonMediosFiscalesTest.(class)=org.springframework.web.servlet.view.tiles2.TilesView
admonMediosFiscalesTest.url=admonMediosFiscalesTest

admonMediosFiscalesWrapper.(class)=org.springframework.web.servlet.view.JstlView
admonMediosFiscalesWrapper.url=/WEB-INF/views/mediosContacto/administrar/admonMediosFiscalesWrapper.jsp

initAdmonMediosContactoFiscales.(class)=org.springframework.web.servlet.view.JstlView
initAdmonMediosContactoFiscales.url=/WEB-INF/views/mediosContacto/administrar/initAdmonMediosContactoFiscales.jsp

admon.mediosContactoFiscales.captura.(class)=org.springframework.web.servlet.view.tiles2.TilesView
admon.mediosContactoFiscales.captura.url=admon.mediosContactoFiscales.captura



############# MEDIOS CONTACTO COMMON  #################
seccionMediosContactoCommon.(class)=org.springframework.web.servlet.view.JstlView
seccionMediosContactoCommon.url=/WEB-INF/views/mediosContacto/common/seccionMediosContactoCommon.jsp