package mx.gob.imss.distss.derechohabientes.adimss.service.utility;

public interface Constantes {


	String DOM_METRO = "@imss.gob.mx";
	String ERROR_SYS = "FAVOR DE INTENTAR MAS TARDE.";
	String ERROR_SYS_LOGEO = "NO SE PUEDE ACEDDER AL SISTEMA.";
	String USER_EXIST = "EL USUARIO YA EXISTE.";
	String DISPATH_ERROR_LOGIN ="errorLogin";
	String DISPATH_SUCESS ="success";
	String WITHOUTIMG = "SIN IMAGEN";
	
	//login.jsp
	String NOT_DATA_BASE = "NO SE ENCONTRARON LOS DATOS EN LA BASE FAVOR DE VERIFICAR.";
	String NOT_DATA = "USUARIO O CONTRASEÑA INCORRECTOS.";
	String USER_DOWN = "USUARIO DADO DE BAJA.";
	String DISC_USR = "FAVOR DE INGRESAR CORRECTAMENTE EL USUARIO Y CONTRASEÑA.";
	
	//showBeneficiarios.jsp
	String ERROR_PERFIL = "NO TIENE EL PERFIL REQUERIDO.";
	String ERROR_ASEG [] = {"NO SE ENCUENTRAN DATOS DEL ASEGURADO.",
							"NO SE ENCONTRARON LOS DATOS DEL ASEGURADO."};
	String ERROR_WSDL [] = {"EL RECURSO DE CONSULTA DE VIGENIA NO SE ENCUENTRA DISPONIBLE POR EL MOMENTO.",
							"ERROR CON LA PETICION AL RECURSO WSDL."};
	String ERROR_RESPUESTA_WSDL = "EXISTE UN PROBLEMA DE COMUNICACIÓN CON EL SERVICIO DE CONSULTA DE VIGENCIA.";
	String ERROR_NSS = "FAVOR DE VERIFICAR EL NSS.";
	String ERROR_EMAIL = "NO SE HA PODIDO ENVIAR EL CORREO.";
	String ERROR_DATA_WSDL = "EL NSS NO EXISTE O TIENE BAJA MAYOR A UN AÑO.";
	
	String DATA_ACCEDER_CURP = "NO SE ENCONTRÓ LA CURP EN LA BASE DE ACCEDER.";
	String DATA_ACCEDER_NOM = "NO SE ENCONTRÓ EL NOMBRE EN LA BASE DE ACCEDER.";
	
	//session
	String SESSION_USER = "sessionUser";
	String NOT_SESSION = "SESION EXPIRADA.";
	String SESSION_ASEGURADO = "sessionAseg";
	
	//Calidad beneficiario
	//Favor de pasar a la ventanilla a verificar la calidad.
	String NOT_CALIDAD = "FAVOR DE ACUDIR AL MÓDULO DE CONTROL DE PRESTACIONES.";
	
	String ERROR_PRESENTAR_PDF = "ERROR AL PRESENTAR EL ARCHIVO PDF CON LOS DATOS DEL ASEGURADO.";
	String ERROR_GENERAR_ARCHIVO = "ERROR EN GENERAR EL DOCUMENTO.";
	
	String ERROR_RESPUESTA_WSNECE = "HAY UN ERROR INTERNO EN WSNECE";
	
	Integer SEG_WSDL_TIME_OUT = 20;
	
	String CAMPO_VACIO = "";
	String CAMPO_GUION = "--";
	
	String AGREAGADO_MED_NULO = "NO SÉ IDENTIFICO NINGÚN DERECHOHABIENTE DENTRO DEL GRUPO FAMILIAR CON EL AGREGADO MÉDICO ";
	
	String ESTILO_CON_AGREGADO_ASEG = "cajacolor15";
	String ESTILO_SIN_AGREGADO_ASEG_1 = "dataAseg1";
	String ESTILO_SIN_AGREGADO_ASEG_2 = "dataAseg2";
	String ESTILO_CON_AGREGADO_BEN = "cajacolor15";
	
//	String URL_DNS = "http://vigencia.imss.gob.mx/VigenciaAseg/";
}
